### ISSUE TITLE
Make sure Cybran T2 Subhunters can be seen by water vision

### ISSUE THREAD

**Issue by aeoncleanse** [FAForever/fa#1002]
Reported in 2 instances by visionik in 3652 beta

**Comment by aeoncleanse** [comment]
So, update to this. When the subhunter is surfaced, it is visible, so normal vision works. When submerged with stealth on, it's totally unseen. When stealth is toggled off, the radar blip appears, but the unit doesn't.

Tested with a variety of other subs. It looks like either water vision is inactive, or they all gained water cloaks. Sera Destroyer is also a victim to this.

**Comment by duk3luk3** [comment]
Thank you for the investigation. I hope I can look into it soon (if nobody else does).
