### ISSUE TITLE
Assisting engineers fail to reclaim

### ISSUE THREAD

**Issue by HardlySoftly** [FAForever/fa#1004]
Replay number 4040083 as an example.

To reproduce:
  1) Set engineers to assist another engineer (main engineer)
  2) Set main engineer to reclaim some unit (e.g a factory)
  3) Tell main engineer to stop

The assisting engineers will continue to reclaim the unit forever, the unit's hp will reach 0 but it will not be destroyed.

Only tested with t1 engies and ACU as main engineer, and the unit as a t1 factory.

**Comment by HardlySoftly** [comment]
This is an issue in current patch as well as beta patch

**Comment by aeoncleanse** [comment]
Thanks for the report.

**Comment by Crotalus** [comment]
Interesting, you can't assist the secondary engineer either, it seems to be in some "fake reclaim" mode

**Comment by Crotalus** [comment]
Changing OnStartReclaim in Unit.lua to this will solve it:

~~~lua
OnStartReclaim = function(self, target)
    self:DoUnitCallbacks('OnStartReclaim', target)
    self:StartReclaimEffects(target)
    self:PlayUnitSound('StartReclaim')
    self:PlayUnitAmbientSound('ReclaimLoop')
     
    local guard = self:GetGuardedUnit()
    if guard then
        IssueClearCommands({self})
        IssueReclaim({self}, target)
        IssueGuard({self}, guard)
    end
end,
~~~

Maybe there is some other solution though

**Comment by aeoncleanse** [comment]
Looked into using those others, looks like your original is the best way.
