### ISSUE TITLE
ACU able to move during upgrades - non-beta

### ISSUE THREAD

**Issue by aeoncleanse** [FAForever/fa#1015]
http://forums.faforever.com/forums/viewtopic.php?f=2&t=11089&p=113751#p113751

**Comment by HUSSAR-mtrela** [comment]
I have verified that this issue is already fixed in 3652 release and it was related to issue #1048 which was fixed by me and @Crotalus

**Comment by HUSSAR-mtrela** [comment]
someone else should confirm it and close this issue

**Comment by zlo-faf** [comment]
So it should be fixed in beta now already? I can test it later today

**Comment by Sheeo** [comment]
@zlo-faf yes, if it's fixed in the release branch it should be live in the beta now.

**Comment by zlo-faf** [comment]
If fix exists, it is not in beta yet
http://content.faforever.com/faf/vault/replay_vault/replay.php?id=4193776

**Comment by HUSSAR-mtrela** [comment]
I will investigate this issue. Thanks @zlo-faf for the replay.

**Comment by HUSSAR-mtrela** [comment]
@zlo-faf, I saw this issue in your replay but I cannot reproduce it in the latest beta. I even removed all my mods, and gave ACU move - upgrade - move commands very fast but that did not trigger this issue. Can someone else try to reproduce this issue in FAF beta?

**Comment by zlo-faf** [comment]
@HUSSAR-mtrela, looks like FAF beta was just updated, and now this issue is fixed (at least i can't do it anymore) makes me happy and sad at the same time

**Comment by HUSSAR-mtrela** [comment]
@Sheeo can you close this issue?
