### ISSUE TITLE
T3/T4 Arty turn to face target

### ISSUE THREAD

**Issue by aeoncleanse** [FAForever/fa#1021]
Apofenas - "I had weird things a week ago wit t3 arty. T3 and t4 arty seem to count as "defence structures too", so they rotate entire building instead of cannon which looks really weird especially with t3 pgen adjacency. Was it reported or fixed already? These structures should be rotated by 90,180 and 270 degrees from their standard, but so their cannon turn to the center of map as less time as possible."

We need to do something about this, and about T2 Arty too if needed. Anything with adjacency. Either do 90 degree turns, or make the gun rotate rather than the body.

**Comment by duk3luk3** [comment]
Build T4 artillery in normal position, but give them a huge turning speed boost that lasts until they fire their first shot.

**Comment by duk3luk3** [comment]
Also: Arty turrets reset when unit is gifted, maybe this should be changed as well.

**Comment by aeoncleanse** [comment]
Can't, units technically spawn anew when they change team, so are 'built' again. It's not a huge problem I think.

**Comment by duk3luk3** [comment]
we should make sure the fix for this issue applies to gifted units as well then

**Comment by aeoncleanse** [comment]
Well, TBH having built them now, I'm  not so sure it needs changing. The win of turn time is worth it, and it doesn't look THAT bad. BTW: Changes of turn rate on the fly can't be done. :(

**Comment by Exotic-Retard** [comment]
i think the original suggestion of aligning them to the nearest 90 degrees is best.

also with t3 arty it might be worth to consider increasing the turn rate - usually after their initial turning period they dont turn that much at all - so most of the difference is where we want it.

**Comment by aeoncleanse** [comment]
Zock has spoken. We're going to have to do 90 degrees with no turn-rate improvement, or simply leave it as it. I don't think it looks too bad TBH.

**Comment by aeoncleanse** [comment]
Wrong button... :/

**Comment by aeoncleanse** [comment]
Crotalus can you get this done please, T3/T4 Arty to nearest 90 degrees.

**Comment by Crotalus** [comment]
f9160b7ca6506e3d900146da15c9ef1ded6ed8e3

**Comment by aeoncleanse** [comment]
Commit tested working for all 4 dimensions.
