### ISSUE TITLE
Using the stop command with nothing selected hard crashes the game

### ISSUE THREAD

**Issue by aeoncleanse** [FAForever/fa#1025]
In beta

**Comment by duk3luk3** [comment]
Please specify "hard crash"?

**Comment by Sheeo** [comment]
Please add a replay and a game log.

**Comment by Sheeo** [comment]
I was just guessing here, but I don't know your keybindings. Please be more descriptive in the future :)

**Comment by aeoncleanse** [comment]
It doesn't save a replay or a log. It just terminates the process with no warnings or errors.

**Comment by aeoncleanse** [comment]
LOG from git bisect:

E:\GITHUB\fa [(a63ede8...)|BISECTING]> git bisect log
git bisect start
# bad: [137659904c30cd0c5cd9d5248b9e45a0cef61f34] Re-add categories to UEF commander drone
git bisect bad 137659904c30cd0c5cd9d5248b9e45a0cef61f34
# good: [e80acb95fb96c6d5fe1986f86cd5e11fe72cf33f] Update map blacklist
git bisect good e80acb95fb96c6d5fe1986f86cd5e11fe72cf33f
# good: [494f3fa67a6113f9a785c85e8e8660334ff98803] Update version number
git bisect good 494f3fa67a6113f9a785c85e8e8660334ff98803
# good: [69c3ce3033d6c0bf2f2a0b5af90c9efa15be8eda] New lobby options to reveal civilians
git bisect good 69c3ce3033d6c0bf2f2a0b5af90c9efa15be8eda
# bad: [026d983e4afb9f307f9dda4a89c5045ad774e722] Make sure focus player isn't -1 when refresh pings
git bisect bad 026d983e4afb9f307f9dda4a89c5045ad774e722
# bad: [83574c49affba61b61bdb769bb2fd033ef0ca63a] Nonfunctional cleanup for selfdestruct.lua
git bisect bad 83574c49affba61b61bdb769bb2fd033ef0ca63a
# good: [51a587265dacb1d33ababcd4953dc056a3345ddd] New functions: ResetOrderQueue / ResetOrderQueues
git bisect good 51a587265dacb1d33ababcd4953dc056a3345ddd
# bad: [e9fda5d88cf1a67bd7d3c6c6043c111172080eb8] Restore beam for Rhino
git bisect bad e9fda5d88cf1a67bd7d3c6c6043c111172080eb8
# bad: [2c2395964c86f976041426e33adfe30fff69021d] Calculate AvgFPS in waitseconds instead
git bisect bad 2c2395964c86f976041426e33adfe30fff69021d
E:\GITHUB\fa [(a63ede8...)|BISECTING]>

**Comment by Sheeo** [comment]
➜  fa git:(release/3652) git bisect replay bisect.log
        ➜  fa git:(a63ede8) git bisect bad
        Bisecting: 0 revisions left to test after this (roughly 0 steps)
        [9d3e8f8b5a7fb655663be58e63787c8e953515d5] Add UI support for soft stopping factories and silo
        ➜  fa git:(9d3e8f8) git bisect bad
        9d3e8f8b5a7fb655663be58e63787c8e953515d5 is the first bad commit
        commit 9d3e8f8b5a7fb655663be58e63787c8e953515d5
        Author: Crotalus <Crotalus@users.noreply.github.com>
        Date:   Sat Oct 3 03:41:29 2015 +0200

            Add UI support for soft stopping factories and silo

            Soft stopping silos cancels all orders but won't touch the missile build process

            Added new key-mapping 'soft_stop'

        :040000 040000 98bc110bc4d1e39f3863bbc1a91beb241248b36d eaf6c4ea18c833e41e2bcc523a93c56a96bd908d M  lua

**Comment by Sheeo** [comment]
Appears @Crotalus forgot to make sure the selection is non-empty before passing it to `EntityCategoryFilterDown`.

**Comment by Crotalus** [comment]
Very evil behavior by `EntityCategoryFilterOut`, `EntityCategoryFilterDown` handles nil just fine.

Overrode the function in userInit.lua to prevent this behavior:
d938ffd
