### ISSUE TITLE
Ctrl-k countdown doesnt get cancelled.

### ISSUE THREAD

**Issue by Exotic-Retard** [FAForever/fa#1028]
so you press ctrl k on something, and what used to happen before is if you give it any order it cancels the countdown
now even the stop command doesn't seem to do it.
i want this functionality back. so that any order cancels the countdown. including move orders.
replay: 
4091917
this affected me in a couple of games now so yeah : /
now im being civilized about this here but i do have a few choice ways of describing this issue, and i would really appreciate it if this was fixed. preferably for next patch.

**Comment by aeoncleanse** [comment]
So I've had a look. Anyone got any clue where the code for this is/was? I can't find it.

**Comment by Crotalus** [comment]
lua/selfdestruct.lua contains the self-destruct stuff.

**Comment by aeoncleanse** [comment]
Actually got around to testing this ingame... It works fine! It cancels the boom, at least in 3652.
