### ISSUE TITLE
FA doesn't use system file cache, low hanging fruits

### ISSUE THREAD

**Issue by Crotalus** [FAForever/fa#1040]
We know that FA currently doesn't use the system disk cache efficiently when *.SCD files are used in the VFS. 

If we unzip (they aren't compressed anyway) the SCDs we will reduce the amount of disk reads and bytes read by up to 90% (when fully in disk cache)

This is an example benchmark by running a Setons replay until ~20 min in game time, look at the I/O-numbers, 130 MB vs 1 GB. I ran this on an SSD disk also so the gain performance wise should be even higher on a slower disk. The actual user time numbers isn't that exact, I stopped the test manually when it reached 20 min.

(ran a warmup session before each benchmark and have verified the I/O numbers by several tests, 
used process hacker and procmon to track disk reads)

Current FAF:
![current_faf2](https://cloud.githubusercontent.com/assets/254972/11444092/053c351c-9523-11e5-9ccf-e01898a9aad0.png)

Flatten out `fa/gamedata/[unit|textures|projectiles|effect|env].scd`
![full_opti2](https://cloud.githubusercontent.com/assets/254972/11444090/03dda3fe-9523-11e5-88ed-9033dfc1b3a4.png)

Another gain could be to actually reduce the number of mount points and instead merge the different directories, so that *.nx2 overwrites the files in the unzipped base-game files. That way we get even less I/O.

**Comment by duk3luk3** [comment]
:+1:

**Comment by speed2CZ** [comment]
Any progress on this? :)

**Comment by MrRowey** [comment]
@Garanas might be something you interested in looking into with perf increasing

**Comment by Garanas** [comment]
@Crotalus Do you recall whether you experienced a performance gain? Because you're trading with random read / write.

**Comment by Crotalus** [comment]
Can't remember how much the actual gain was, I guess it would be substantial if someone is using an old disk but with modern SSD it's probably not much.

With patch updates, unzipping the SCDs could be a bit problematic for someone with a slow disk. They are already a bit slow just by downloading / replacing the scds.

Would need something like git or some other diff/rsync/bireus like patching system so it doesn't have to unzip all files every patch change.

**Comment by MrRowey** [comment]
@Garanas Can this be closed if it only provides minimal performance gain ?
