### ISSUE TITLE
Possible to build factories in factories due to hotbuild

### ISSUE THREAD

**Issue by Crotalus** [FAForever/fa#1043]
This commit makes it possible to order factories in factories from hotbuild UI:

2d82debb30c50997f6236ccd50fd8d2ce5284e48

Build a t2 naval yard, then order a t1 naval factory to build support factory. I think the problem is that the command is sent from hotbuild as BuildFactory instead of Upgrade.

The real problem is implementation of engymod though, the `'BUILTBYTIER1FACTORY' on support factories makes it possible to order build instead of upgrade.  That category shouldn't be needed but it's there to make it appear in the build UI. Should be changed when construction.lua is refactored

**Comment by duk3luk3** [comment]
This actually queues the factory *and* a t1 engineer. That is very weird.

**Comment by duk3luk3** [comment]
I am confused. I removed the BUILTBYTIER1FACTORY category from zab9501 (Aeon T2 Support Naval Fac) and it changed nothing.

**Comment by duk3luk3** [comment]
I'm not sure how to fix this properly in `construction.lua`. Since the engymod support fac stuff is based on unit restrictions, I would have to check the restrictions somehow.

I tried this but it doesn't seem to work:
```
        if allFactory then
            -- Add support factories
            if not EntityCategoryEmpty(buildableCategories * categories.SUPPORTFACTORY) then
                local allFacs = EntityCategoryGetUnitList(categories.SUPPORTFACTORY)
                for i, facid in allFacs do
                  if facid ~= selection[1]:GetBlueprint().BlueprintId and __blueprints[facid].General.UpgradesFrom == selection[1]:GetBlueprint().BlueprintId then
                    table.insert(buildableUnits, facid)
                    WARN("Found fac upgrade: " .. facid)
                  end
                end
            end
```

**Comment by aeoncleanse** [comment]
Reverted Crotalus's approach. If we go with that method, we HAVE to find a way to only cancel the factory, and not the engineer ordered simultaneously. 

A better method by far would be to adapt Hotbuild to detect when a factory structure is selected and either exclude the support factories from the hotbuild menu in that case, or have it issue that command as an upgrade (Similar to using hotbuild's 'upgrade' key) rather than as a build order.

**Comment by Crotalus** [comment]
Why are you suggestion an UI restrictions solution to something that clearly needs a sim-side solution?  It's the same logic that caused the "oops you can build restriction units, just bypass the UI" bugs.

The right solution in this case would be to remove BUILTBYTIERXFACTORY on all T2+ factories and make sure UI can figure out correct buildableUnits, probably by syncing HQ information from sim.

**Comment by duk3luk3** [comment]
We need to do both.

**Comment by aeoncleanse** [comment]
Yup. We do. The sim part needs to be a complete re-write of the support factory system, because it's absolutely stupid.

For now, we need to fix this new feature WITHOUT breaking an already working one please.

**Comment by aeoncleanse** [comment]
Fixed in 57322217791cf2b85bf3b4000996b939e6531549 as a temporary measure. Strange UI things happen, but the actual building of the Factory is skipped when its turn comes up.

**Comment by duk3luk3** [comment]
Since we have enough other issues concerning how engymod is utterly broken this issue can be closed I think.

**Comment by Sheeo** [comment]
This issue needs to stay open while it's relevant.

**Comment by Sheeo** [comment]
Symptoms are gone as of 83867abbeee1491aed110613da9c46948e8bdfab, retargeting the 'proper' fix for 3654.
