### ISSUE TITLE
T3 Static arty not shooting

### ISSUE THREAD

**Issue by speed2CZ** [FAForever/fa#1044]
Ive played a game on Canis and our opponent Iszh had a Duke, trying to kill our scathis. And even when he had vision on it, his arty was refusing to shoot at it.

It was at the point when the scathis moved to the front shield coverage. You'll notice it in chat as well, since Iszh wasnt too happy about it.
http://replay.faforever.com/4133664

Me noob didn't have log saving enabled after latest FAF reinstall :( hopefully the replay will be enough for someone to investigate.

**Comment by Crotalus** [comment]
I think it's due to his energy being in the negative and relying entirely on team overflow, an energy storage would maybe have helped his case.

**Comment by speed2CZ** [comment]
yup, power issues
