### ISSUE TITLE
Unit nanolathe animation is not destroyed with factory

### ISSUE THREAD

**Issue by speed2CZ** [FAForever/fa#1045]
http://replay.faforever.com/4141788

https://www.youtube.com/watch?v=lntKNSCVKRQ&feature=youtu.be&t=2353

You see that UEF Battleship in dead factory? Rreplay is desynced few minutes before it happened but still can be seen there.
Might be that factory wasnt killed but died when player left the game?
# 3650patch

**Comment by aeoncleanse** [comment]
Might also have something to do with a ridiculous game mod that lets navy be built on land?

**Comment by aeoncleanse** [comment]
Apparently been seen recently.
