### ISSUE TITLE
Cannot restrict T3 Heavy Arty without also restricting Paragon and Satellites 

### ISSUE THREAD

**Issue by HUSSAR-mtrela** [FAForever/fa#1046]

**Comment by HUSSAR-mtrela** [comment]
Selecting "No Game Enders" in the Unit Manager T3 Heavy Arty as well as Paragon and Satellites and it would be good to have a way to individual restrictions for T3 Heavy Arty like we do for Paragon and Satellites. Something like attached image:
![pasted_image_at_2015_12_06_11_21_pm](https://cloud.githubusercontent.com/assets/11665978/11637100/b2db1356-9ced-11e5-85dc-fdff687dc071.png)

**Comment by HUSSAR-mtrela** [comment]
Please assign this issue to me since I have a fix for it

**Comment by aeoncleanse** [comment]
7feef8fa305d073b0f77bfb3da18e7b5fa4f060d
