### ISSUE TITLE
Restricted ACU upgrade can be finished by starting/stopping allowed upgrade and then starting restricted upgrade 

### ISSUE THREAD

**Issue by HUSSAR-mtrela** [FAForever/fa#1047]
1. Start the game with restricted "Teleport" in unit manager
2. Start upgrading any allowed enhancement , e.g. Tech 2 Engineering Suite
3. Stop upgrading enhancement in middle of progress or close to finish
4. Start upgrading "Teleport"  enhancement and it has progress from the stopped enhancement!!!

Result: 
The "Teleport"  enhancement finishes even it was restricted.

Root Cause: 

EnhanceTask.lua throws nil error when setting unit:SetWorkProgress(current) on line 68
Construction.lua does not disable/hide restricted enhancements because EnhanceCommon.GetRestricted() function always returns empty table.

Once restricted enhancement  is finished it cannot be removed by starting other enhancements in the same tab.

Proposed fix: 
- Construction.lua should hide/disable restricted enhancements by checking RestrictedCategories in SessionGetScenarioInfo().Options against restrictedUnits table 
- EnhanceTask.lua should also check for RestrictedCategories  becasue Construction.lua can be overridden in UI mod

**Comment by HUSSAR-mtrela** [comment]
Please assign it to me because I have a fix for this issue
Also add labels: UI, Bug, Critical

**Comment by Sheeo** [comment]
This must be a sim problem.
