### ISSUE TITLE
Selecting Teleport or Billy upgrade restrictions does not hide or disable it in the UI of commanders

### ISSUE THREAD

**Issue by HUSSAR-mtrela** [FAForever/fa#1048]
This issue is related to #1047

**Comment by HUSSAR-mtrela** [comment]
Please assign this issue to me since I have a fix for it

**Comment by Sheeo** [comment]
Where is the pull request, in this case?

**Comment by HUSSAR-mtrela** [comment]
Im still working on it and I will have the pull request tomorrow

**Comment by HUSSAR-mtrela** [comment]
This issue has regression in the latest FAF beta and it should be re-opened

**Comment by HUSSAR-mtrela** [comment]
PR  #1172 has a fix for this issue

**Comment by aeoncleanse** [comment]
7feef8fa305d073b0f77bfb3da18e7b5fa4f060d
