### ISSUE TITLE
Selecting T3 Mobile Anit Air restrictions does not hide it in build menu of Megaliths

### ISSUE THREAD

**Issue by HUSSAR-mtrela** [FAForever/fa#1049]
Selecting T3 Mobile Anit Air restrictions in unit manager, does not hide it in build menu of Megaliths. As result they can build T3 Mobile Anit Air and it explodes when finished building.

**Comment by HUSSAR-mtrela** [comment]
Please assign to me and add labels: low, bug, restriction

**Comment by HUSSAR-mtrela** [comment]
Please disregard this issue as it was my mistake in testing. The T3 Mobile Anit Air restriction works as expected

**Comment by speed2CZ** [comment]
as you wish
