### ISSUE TITLE
Aeon Rapid Arty (Salvation) should be categorized as Experimental instead of Tech3

### ISSUE THREAD

**Issue by HUSSAR-mtrela** [FAForever/fa#1052]
Aeon Rapid Arty (Salvation) should be categorized as Experimental instead of Tech3 because it costs much more than Tech3 Heavy Arty and it does damage roughly equallyvalent to other experimental arty units in other factions: Scathis and Mavor

Labels UI, bug, low

**Comment by aeoncleanse** [comment]
Been argued for a long time. I don't think it's necessary. Yes, it's strong, but it's also T3. Since there's no functional difference, and it's just about that special feel, there's no real need to move it and give Aeon more experimental slots than anyone else.

**Comment by Sheeo** [comment]
Arguably not a bug, just an odd choice of classification.

**Comment by Zockyzock** [comment]
I'm neutral on this, you can make a case for both. It makes sense to put it into exp if you base it on the power of the unit. The argument against it was and is that Aeon will have one more exp than other factions which may be regarded as unfair or irritating by people that are not very familiar with the game and wouldn't notice the "unfairness" right away when it's in t3. 

But people are used to it as it is, if in doubt, don't change it.

**Comment by zlo-faf** [comment]
I remember when i just started playing i thought that it is quite counter intuitive to have such powerfull, long range, expencive unit in t3 stage instead of t4 stage

**Comment by HUSSAR-mtrela** [comment]
Argument of more experimental slots for Aeon than other faction is not valid. Seraphim dont have one less experimental and we are not moving experimental from other faction to t3 just to match number of experimental units for all factions. Just compare damage/cost of Salvation with other experimental and you will see that it is actually experimental unit and should be classified as such, Also, it is one of super-game-ender (Scathis, Mavor,Yollona Oss). It even cost 3 times than Scathis!

http://spooky.github.io/unitdb/#/URL0401,XAB2307,UEB2401

**Comment by HUSSAR-mtrela** [comment]
@aeoncleanse @Zockyzock 
Gyle has spoken and we should correct classification of the Rapid Artillery: 
https://www.youtube.com/watch?v=zaYEq2EbGVE&feature=youtu.be&t=1h2m13s

**Comment by Zockyzock** [comment]
fine with me

**Comment by aeoncleanse** [comment]
Oh my god we can do it :D
