### ISSUE TITLE
Notes when joining game lobby

### ISSUE THREAD

**Issue by Cheyans** [FAForever/fa#1056]
Posted this for Petricpwnz 
http://forums.faforever.com/forums/viewtopic.php?f=42&t=11241

**Comment by duk3luk3** [comment]
Isn't there already a "rules" field in lobby that is for essentially that?

**Comment by Sheeo** [comment]
Pretty much the rules feature does exactly this.

I personally wouldn't want annoying popups when joining games.

**Comment by MrRowey** [comment]
@Garanas this can be closed we don't want to clutter the lobby Ui with more buttons and tabs just to make things more confusing
