### ISSUE TITLE
Some logspam in beta

### ISSUE THREAD

**Issue by aeoncleanse** [FAForever/fa#1061]
I've been seeing this a lot. It all seems to do with dead things not clearing up properly, so we probably need defensive checks. The main culprits are cybranunits.lua line 124, URS0201_script.lua line 83, and URB0103_script.lua line 37.

**Comment by aeoncleanse** [comment]
Defensive checks for unit existing do *not* fix this issue. I don't know what to try next.

Can be reproduced by making UEF T2 Naval Factory, building and Engineer, then using stop to halt construction. It will error to log.

**Comment by duk3luk3** [comment]
The error I get for cancelling the T2 engineer on current release/3652 is this:

> WARNING: Error running lua script: e:\git\fa\lua\terranunits.lua(153): Game object has been destroyed
>         stack traceback:
>         	[C]: in function `CreateAnimator'
>         	e:\git\fa\lua\terranunits.lua(153): in function <e:\git\fa\lua\terranunits.lua:150

Is that the same issue? Please be more precise about which units the problem applies to.

**Comment by duk3luk3** [comment]
Fix for engineers and cybran destros is here: https://github.com/duk3luk3/fa/tree/hotfix/transformthreads

How to repoduce issue for naval fac?

**Comment by aeoncleanse** [comment]
Yeah it is. I tried to be a specific as I could, but it randomly pops up for different, additional units every now and again :/

Why the hell is it made in Air? :/ :/

**Comment by duk3luk3** [comment]
It's not made in air, it changes layer to air specifically when its construction is stopped. Why? GPG only knows.

**Comment by aeoncleanse** [comment]
¯\_(ツ)_/¯

**Comment by Sheeo** [comment]
Unclear what this issue represents any more. Please create more specific issues for specific problems
