### ISSUE TITLE
ingame map select filters conflict with faf map select

### ISSUE THREAD

**Issue by Exotic-Retard** [FAForever/fa#1066]
im sure everyone has had this before: host some game, click options, and then the map changes to some retarded voodoo tournament map or something.

been here for a long time but i think ive tracked it down:
its a combination of a few things:
1. the map filters in the game lobby
2. the map select in the host game dialog
3. the auto select of maps in the options of the ingame lobby

in short; when you select a map in the faf game dialogue (which is actually very nice and much faster than in game, and works with keyboard and text search)
and the filters in the game lobby are such that the map is filtered out,
it defaults to the first map in the available list
and it automatically selects that map
and if you press ok without even mousing over the map list then it sets that map.

solution?

make it reset the map filters to all on every game host (they are written to game.prefs afaik). this removes the issue while keeping all other functionality.

**Comment by duk3luk3** [comment]
I think we had a good reason when we implemented persistence of the filter settings in the first place. But I don't remember.

**Comment by duk3luk3** [comment]
Made a tentative PR here: #1079
