### ISSUE TITLE
[FAF beta] personal shields don't turn off when energy is negative

### ISSUE THREAD

**Issue by ppipp** [FAForever/fa#1071]
Just tested something in FAF beta and noticed units with personal shields like Harbingers or Obsidians don't lose their shields when you have negative energy income.

**Comment by aeoncleanse** [comment]
I just tested Harbs and... Yeah they do... :/ So does every other PShield unit. You got logs for me to look at mate?

**Comment by aeoncleanse** [comment]
Nice catch. Looks like somewhere down the line shields were made to check for <= 0 E in storage, where the more normal stall situation is for that number to be between 0 and 1. Intel stuff watches for <1 for this reason. Testing this change now.

**Comment by aeoncleanse** [comment]
Hopefully fixed with a2183ac2d48315eefedaaa59c6accd08e29fdae0
