### ISSUE TITLE
Distinguish mutually agreed draws from normal draws in GPGNet messages

### ISSUE THREAD

**Issue by Sheeo** [FAForever/fa#1074]

**Comment by aeoncleanse** [comment]
@Sheeo - What exactly is this going to require in game code? Do we need to create some UI stuff for it, to agree to such a draw, or is it a simpler change than that?

**Comment by micheljung** [comment]
@aeoncleanse as far as I understand it, if players click the "Draw" button in game, the game should send a `MutualDraw` message to the server

**Comment by MrRowey** [comment]
@Garanas  Seemed to have been merged into the Server

**Comment by Garanas** [comment]
I used it this month - closing this issue.
