### ISSUE TITLE
Cybran SCU - regen rate not displaying correctly after upgrade change

### ISSUE THREAD

**Issue by Nojoke185** [FAForever/fa#1075]
To recreate...

build basic cybran SCU
- note base regen is 25hp sec

upgrade to nano repair system (back)

- note new regen is 400hp sec

upgrade to personal stealth (back) - choose yes to question "are you sure" (to destroy existing upgrade)

after upgrade is done:

- note regen is still 400hp sec

if you build a basic cybran SCU and upgrade direct to personal stealth (back) base regen is 25hp sec

I dont think the regen is actually 400hp sec after the upgrade change, its just seems the UI is not updated

Would be good to see if anyone else has the same results

**Comment by aeoncleanse** [comment]
Checked this sequence out in 3652, it appears to have been fixed by the regen buff changes.
