### ISSUE TITLE
Introduce direct chain upgrade for factories

### ISSUE THREAD

**Issue by aeoncleanse** [FAForever/fa#1076]
Will require complex code exceptions I think. I've turned off the confusing arrows for factories in 3652 where it's not supported.

Turned off in 05b0d7ca2233c34fe6a6a962206a769c5c4620b1

Follows from #1057

**Comment by duk3luk3** [comment]
> Turned off in 05b0d7c

:+1: 

> Will require complex code exceptions I think

We should probably change the UpgradesTo Blueprint property to contain a list of unit ids instead of a single unit id. Following the chain would not be too ugly or expensive.

**Comment by aeoncleanse** [comment]
@duk3luk3 - Think you can find time before christmas to handle this?

**Comment by MrRowey** [comment]
@Garanas Do we really need a Direct Chain for an upgrade for factories ? I've Testes it and seem that when you upgrade to a T2 HQ you don't get the T3 HQ to upgrade it want to upgrade you to a T2 Support

**Comment by Garanas** [comment]
I'm not entirely sure what a 'Direct Chain' means?

**Comment by MrRowey** [comment]
@Garanas Direct Chain is a Set Upgrade phat for a building EG most common on is the mex it ass the arrows in and also you can just click the t3 and it dose them in sequence . 

![image](https://user-images.githubusercontent.com/20344151/141449478-344fd493-90ab-4fe9-9785-0f24b48001d5.png)

**Comment by Garanas** [comment]
Ah - I see. That doesn't work at this moment. Not sure if this is something we want to add - it is nice, but not a necessity.

**Comment by MrRowey** [comment]
@Garanas im closing this as i dont see this as being somthing that nessasary for the land, air, navy factorys.
