### ISSUE TITLE
Introduce different team colours for "toggle player colours" feature (Ctrl+E)

### ISSUE THREAD

**Issue by Sir-Prize** [FAForever/fa#1080]
Ctrl+E is really useful if you can't remember who is who (including whether you're red or blue on ladder sometimes if you're me, but most people aren't THAT stupid). It would be good if when you used this in a team game you got a range of greens and blues for your own side and reds and oranges for the opposition. I think it would be good if you were struggling to remember who's on your team, particularly if someone is playing in your/someone else's "usual" colour. 

I also searched the forums and found this, which is slightly different and looks like it was impossible in the end.

http://forums.faforever.com/forums/viewtopic.php?f=2&t=8484&p=80349&hilit=team+colours#p80349

EDIT: Maybe it's more similar than I realised and this is just entirely impossible. Anyway, food for thought for people that would know.

**Comment by duk3luk3** [comment]
Just from reading that thread, without doing any code investigation or testing, it sounds like the only way to do this properly is as a lobby option for custom games.

**Comment by Sir-Prize** [comment]
Ah if default colouring is forced on all players when the host switches it on, it's probably not worth the effort. If the host is enabling a toggle for each player to choose between default and everyone's selected colour that'd be great. 

And yeah obviously if the icons could be modded to enable the UI control, that would be what I'm talking about :)

Thanks for the response.

**Comment by CookieNoob** [comment]
this would be really great for replays and casting. There was a mod that did a similar thing for the game http://forums.faforever.com/viewtopic.php?f=2&t=8484
Make it toggleable with the same button as the normal teamcolor button. New project after notify integration @aeoncleanse ?

**Comment by MrRowey** [comment]
@Garanas Is this something that could be merged as Cookie seems to have already made a Commit ?

**Comment by MrRowey** [comment]
Dated issues. if this is something that's wanted it can be reopen and implemnted
