### ISSUE TITLE
cybran SCU emp (maybe all emp?) doesn't stun units with personal shield 

### ISSUE THREAD

**Issue by Zockyzock** [FAForever/fa#1086]
tested on titans, supposedly applying to all personal shields

**Comment by aeoncleanse** [comment]
Yeah it never has. Personally I think we should keep this, it's one of the very, very few advantages of a shield over more HP.

**Comment by Zockyzock** [comment]
It feels unintuitive to me

**Comment by aeoncleanse** [comment]
Really? Surely an energy shield prevents the blast making contact with the body and shorting out the electrics? makes perfect sense. Remove this and we may as well remove personal shields from every non-SCU/ACU unit. They are a mostly a handicap, not a benefit.

**Comment by Zockyzock** [comment]
If shields are weak, buffing them is discussable, it shouldn't determine if they should block emp or not.

**Comment by aeoncleanse** [comment]
No, that would be the fact it's an energy shield which physically prevents the EMP blast from ever making contact with anything electrical...

**Comment by MrRowey** [comment]
@Tagada14 I would class this as something balance should decide if they want to change or not. if not can you please close
