### ISSUE TITLE
unit (pd) not firing

### ISSUE THREAD

**Issue by shalkya** [FAForever/fa#1089]
http://forums.faforever.com/forums/viewtopic.php?f=3&t=11487

**Comment by MrRowey** [comment]
@Jip close off issues as all PD are fine and the the from post is on the old Forum so cant access the Issues that was happing via the link

**Comment by Garanas** [comment]
The issue that Keyser referenced has been closed. There is https://github.com/FAForever/fa/issues/3278 and I think that is what this issue is about. Closing this issue in favor of the more recent one.
