### ISSUE TITLE
Large units immune to Firebeetles

### ISSUE THREAD

**Issue by aeoncleanse** [FAForever/fa#109]
If the minimum bounding box size is more than double the Firebeetle's trigger range, it can't get close enough to detonate! (Fatboy is an example, it can't be hit except from right at the side)

**Comment by aeoncleanse** [comment]
What are we doing with this? Is there any point the issue being here if it's unsolvable outside of source code or a balance change?

**Comment by Sheeo** [comment]
It's not unfixable.

**Comment by CookieNoob** [comment]
so why does adding crotalus code to OnStopBeingBuild() or OnCreate() not work and fix this issue?

**Comment by aeoncleanse** [comment]
It just didn't work right.

**Comment by MrRowey** [comment]
@Tagada14 is this still an issue if not can it be closed off

**Comment by Sheikah45** [comment]
This is still an issue

**Comment by MrRowey** [comment]
@Garanas is this still an issuse ?

**Comment by Garanas** [comment]
Yes - and it won't be fixed without changing how the fire beetle works.

**Comment by Garanas** [comment]
Closing this - it would require a complete revamp of how the beetle works at the moment. It is possible to make it work, if that is desired I can create a new issue with a technical description on how to approach it.
