### ISSUE TITLE
 near finish shield get kill and reset health of com

### ISSUE THREAD

**Issue by shalkya** [FAForever/fa#1094]
http://forums.faforever.com/forums/viewtopic.php?f=3&t=11145

**Comment by duk3luk3** [comment]
The health loss does not come from a normal attack since OnDamage is not called. Very interesting.

**Comment by duk3luk3** [comment]
The shield actually got finished and blinked on for a tick, when it was already destroyed. That probably has something to do with the glitch.

**Comment by zlo-faf** [comment]
http://forums.faforever.com/forums/viewtopic.php?f=63&t=11300

Another example and replay where i reproduced bug

**Comment by duk3luk3** [comment]
Thanks!

**Comment by Crotalus** [comment]
A known bug, fixed in release/3652 here: 
https://github.com/FAForever/fa/commit/0822d1043b5dfe54e7d77d6daae8b6a71b75827a

Seems like not only sinking structures had the no-collision flag set, also structures that get animated at death (like a shield).

**Comment by duk3luk3** [comment]
Huh I don't understand why I didn't find that SetHealth call in my debugging.

**Comment by Nojoke185** [comment]
anymore reports of this or solved?

**Comment by Crotalus** [comment]
Solved as mentioned earlier, closing.
