### ISSUE TITLE
issue scu shield 

### ISSUE THREAD

**Issue by shalkya** [FAForever/fa#1098]
there is still some issue for scu shield. 
test made on faf beta.

http://forums.faforever.com/forums/viewtopic.php?f=3&t=11513

**Comment by aeoncleanse** [comment]
Cannot reproduce. Ahwassa VS stage 1 Aeon SCU shield, 11000 damage, no overkill.

**Comment by aeoncleanse** [comment]
Got it, the shield overkill one was a restructuring error. Fixed in c80b75a2dd8913839c1acd39877075c722ed8fc5

Still need to debug part 2, the mesh FX not going away...

**Comment by shalkya** [comment]
this has been fixed
