### ISSUE TITLE
sera T1 subs can dodge torpedo when surface

### ISSUE THREAD

**Issue by shalkya** [FAForever/fa#1104]
http://forums.faforever.com/forums/viewtopic.php?f=3&t=9770

tested on beta, bug still work

**Comment by aeoncleanse** [comment]
How is this a bug and not a balance issue?

**Comment by shalkya** [comment]
well I think it's a bug (not intended), but can be keeped since T1 sera subs can lose in 1v1 to other subs (when not surface + micro)
We can ask zock opinion indeed.

**Comment by shalkya** [comment]
zock : hmm either we fix sera sub, or we make all subs able to dodge torps a bit?
maybe better since subs are weak and adding some more micro possibilities
don't see any form of abuse for it

keyser : zock i was able to kill a T1 torpedo with 1 subs though

zock : yeah maybe have to reduce it a bit for sera?

keyser : and in 5v5, i was able to keep 3 alive or more

zock : but making subs able to dodge in general sounds good?
maybe harder/not so much
not sure if thats possible
maybe you can try something with values?

keyser : will see

zock : it shouldnt beat torp launcher of course

**Comment by aeoncleanse** [comment]
How the hell does it beat HOMING torps though?

**Comment by aeoncleanse** [comment]
Bones were crappy set up. Fixed 4324a5081978ae7e52008fc600a352b0aca5e156
