### ISSUE TITLE
targetting with torpedo com bug

### ISSUE THREAD

**Issue by shalkya** [FAForever/fa#1105]
http://forums.faforever.com/forums/viewtopic.php?f=3&t=9699

maybe link with this : https://github.com/FAForever/fa/issues/1090

**Comment by aeoncleanse** [comment]
Not sure this can be changed. Controlling target focus happens with the primary weapon, which is why in most cases primary weapon has the longest range.

**Comment by shalkya** [comment]
can the primary weapon be changed when we get in water ? 
(though it can fuck up when you use gun on the coast/shallow water)

**Comment by aeoncleanse** [comment]
No, it's set at launch.

**Comment by CookieNoob** [comment]
what about this: we add a dummy weapon as primary weapon with the same range as the normal gun (range scales with gun upgrade). In the OnLayerChange function we increase the range to the torpedo range if that upgrade is completed and check if the unit is underwater when completing torpedo to increase the range in that case as well. When going back on land, we reduce the range again.
