### ISSUE TITLE
dead sea reclaim bugs

### ISSUE THREAD

**Issue by shalkya** [FAForever/fa#1106]
http://forums.faforever.com/forums/viewtopic.php?f=3&t=11515

no replay, no logs...

**Comment by duk3luk3** [comment]
I fixed that bug but I can't find the issue or PR now :/

**Comment by duk3luk3** [comment]
There we go: https://github.com/FAForever/fa/issues/1081

Could you post this on the forum please, I can't log in right now.

Should be live on beta.

**Comment by duk3luk3** [comment]
Nevermind, I should read more carefully.

> Not sure if these have been accounted for and or now known but thought i'd post anyway. Amphibious units leave full mass in sea (Exps, wagner/brick/percy, sacus) Hover doesn't. HARMS leaves full mass but t1/t2 torp launchers don't. 

This was discussed in the issue thread for #1081 and we should maybe think about that again since we only considered amphibious land units and not torp launchers or hover units.

> And SACU upgrades done after gate don't count towards mass (but presets do) but I seem to think it is already well known?

That is interesting and should be thought about.

**Comment by shalkya** [comment]
obviously upgrade done after gate should be taken into account for the value of the reclaim.

By the way, if i removed all my upgrade on my sacu to leave less reclaim, is it "fairplay", should it be fix or should it be taken as a "smart move" ?

**Comment by aeoncleanse** [comment]
The entire preset thing is dumb, stupid, and needs to die.

**Comment by shalkya** [comment]
i don't really agree, i feel like it help a lot with the micro. better than having a rally point where unit are doing their upgrade.
