### ISSUE TITLE
can't rebuild harms/myrmidon/eye of rihanne on wreckage

### ISSUE THREAD

**Issue by shalkya** [FAForever/fa#1107]
harms can't be rebuild as if it was a mobile unit. doesn't make much sense to me.

same for myrmidon (T3 static aa cybran) on water.

and eye of rihanne

**Comment by aeoncleanse** [comment]
Beta? Not beta? Both?

**Comment by Sheeo** [comment]
Reproduced on beta.

**Comment by aeoncleanse** [comment]
This is confirmed to be working as intended for the named units, and for all naval factories.
