### ISSUE TITLE
Possible to build factory using hotbuild

### ISSUE THREAD

**Issue by Sheeo** [FAForever/fa#1108]
STR:

- Have t1 factory assist t2 factory
- Use 'w' binding to issue engineer in t1 factory
- t1 fac will build a t2 support factory

**Comment by aeoncleanse** [comment]
This will be fixed by duk3's engiemod rewrite.

**Comment by duk3luk3** [comment]
This is an exact duplicate of #1043.

**Comment by Sheeo** [comment]
Then why is that issue closed?
