### ISSUE TITLE
Civilian reveal in beta

### ISSUE THREAD

**Issue by speed2CZ** [FAForever/fa#1110]
On my map Seraphim Outpost civilians have bit problems with revealing, on first try, it showed like 30% of them, on second try nothing anymore. Same happened to @Zockyzock when he was trying it and other 2 people that tried it for me. So should be easy to reproduce.

**Comment by speed2CZ** [comment]
first try should look +- like this http://puu.sh/mFTtb/2f99f69267.jpg

**Comment by Sheeo** [comment]
@speed2CZ do you use a script to spawn the civilian structures -- and if so, what's the delay for spawning them?

The way the reveal feature works is that it marks civilians as your ally for the first second of the game. So any units spawned after this will not be revealed.

**Comment by speed2CZ** [comment]
in new version I use script to only spawn crystals, all the other building and walls are same as on other maps. And this thing as I described it happened on older version before I moved crystals to be spawned by script, but I dont think that matters at all, since Tokyto was testing it with this new version and got same result.

**Comment by Crotalus** [comment]
Hmm intel system is very strange with its lag and stuff. A solution could be to switch out the 1 second delay and instead keep alliance until OnIntelChange is called on the brain, I'll dig into it.

**Comment by Crotalus** [comment]
So only 30% of a civilian units was shown? They were all part of the same army?

**Comment by speed2CZ** [comment]
only like 30% and only first time playing the map, yes same army

**Comment by speed2CZ** [comment]
And on my map Monaki, nothing gets revealed at all

**Comment by Crotalus** [comment]
I'll take a look, 8 player version?

**Comment by Crotalus** [comment]
On 2p Monaki they don't reveal due to being NEUTRAL_CIVILIAN as string.

**Comment by speed2CZ** [comment]
is this feature set to reveal only the extra army and not NEUTRAL_CIVILIAN army? cause most of the civilian building are usually in NEUTRAL_CIVILIAN.
If you it should be set on that army as well

**Comment by speed2CZ** [comment]
else it was tested on 2v2 verison of my mapa and iirc it didnt work on 8 player version as well

**Comment by Crotalus** [comment]
Neutrals should be revealed now as well
