### ISSUE TITLE
FAF lobby unknown symbol issue

### ISSUE THREAD

**Issue by FAF-Leo** [FAForever/fa#1115]
This issue happens when ppl use symbols on the game path. like:

E:\Apsalar's Stuff\Games\Supreme Commander\Supreme Commander - Forged Alliance

_______________________________________________________________________________    Failed to setup initial search path.

    Program : C:\ProgramData\FAForever\bin\ForgedAlliance.exe
    Cmd line arguments : /mean 1500.0 /deviation 500.0 /init init_faf.lua /numgames 0 /nobugreport /savereplay gpgnet://localhost/4397323/Ranmyakki.SCFAreplay /gpgnet 127.0.0.1:56703

    Callstack:
       Unknown symbol (address 0x008cef50)

    Last 100 lines of log...

    warning: Running "C:\ProgramData\FAForever\bin\init_faf.lua" failed: C:\ProgramData\FAForever\bin\..\fa_path.lua(1): `=' expected near `Stuff'
             stack traceback:
                [C]: in function `dofile'
                C:\ProgramData\FAForever\bin\init_faf.lua(2): in main chunk
_______________________________________________________________________________

**Comment by duk3luk3** [comment]
I don't think that can be fixed, the dofile() function just doesn't handle paths with symbols.

**Comment by Sheeo** [comment]
Doesn't it just need to be properly quoted?

**Comment by Sheeo** [comment]
Seems like a client bug with this:

```def writeFAPathLua():
    """
    Writes a small lua file to disk that helps the new SupComDataPath.lua find the actual install of the game
    """
    name = os.path.join(util.APPDATA_DIR, u"fa_path.lua")
    gamepath_fa = config.Settings.get("ForgedAlliance/app/path", type=str)

    code = u"fa_path = '" + gamepath_fa.replace(u"\\", u"\\\\") + u"'\n"

    gamepath_sc = config.Settings.get("SupremeCommander/app/path", type=str)
    if gamepath_sc:
        code = code + u"sc_path = '" + gamepath_sc.replace(u"\\", u"\\\\") + u"'\n"

    with open(name, "w+") as lua:
        lua.write(code.encode("utf-8"))
        lua.flush()
        os.fsync(lua.fileno())  # Ensuring the file is absolutely, positively on disk.```
