### ISSUE TITLE
Coop lobby crashes when selecting the options. 

### ISSUE THREAD

**Issue by PostalBlab** [FAForever/fa#1117]
I've got this problem: https://github.com/FAForever/client/issues/230
I deleted everything i could find (Steam FA Folder, FAForever install, FAForever under ProgramData) and reinstalled it, twice.

Here is the log:
EXCEPTION_ACCESS_VIOLATION (0xc0000005) at address 0x00938ac8
    attempted to read memory at 0x00000000

Program : C:\ProgramData\FAForever\bin\ForgedAlliance.exe
Cmd line arguments : /mean 1500.0 /deviation 500.0 /country DE /init init_faf.lua /numgames 0 /log C:\ProgramData\FAForever\logs\game.log /nobugreport /savereplay gpgnet://localhost/4416724/PostalDude.SCFAreplay /gpgnet 127.0.0.1:2581

Callstack:
	Unknown symbol (address 0x00938ac8)
	Unknown symbol (address 0x00914412)
	Unknown symbol (address 0x10e669bb)

Last 100 lines of log...

info: GPGNET: setting nat handler to 0x11471004
info: LOBBY: Game port 6113[UDP] opened.
info: LOBBY: starting with local uid of 102761 [PostalDude]
info: GPGNET: entering lobby state.
debug: Wavebank prepared: 2e79828
debug: Wavebank prepared: 2e7a368
warning: {
warning: }
warning: {
warning: }
warning: {
warning:     MEAN = 1500
warning:     StartSpot = 1
warning:     ArmyColor = 2
warning:     PlayerClan = ""
warning:     NG = 0
warning:     Team = 1
warning:     Ready = false
warning:     PlayerColor = 2
warning:     Country = "de"
warning:     PlayerName = "PostalDude"
warning:     AIPersonality = ""
warning:     ObserverListIndex = -1
warning:     BadMap = false
warning:     Civilian = false
warning:     Faction = 1
warning:     OwnerID = "102761"
warning:     RC = "ffffffff"
warning:     PL = 0
warning:     DEV = 500
warning:     Human = true
warning: }
info: SetGameOption(key="UnitCap",val="750")
info: SetGameOption(key="ShareUnitCap",val="none")
info: SetGameOption(key="FogOfWar",val="explored")
info: SetGameOption(key="Victory",val="domination")
info: SetGameOption(key="Timeouts",val="3")
info: SetGameOption(key="GameSpeed",val="normal")
info: SetGameOption(key="AllowObservers",val=false)
info: SetGameOption(key="CheatsEnabled",val="false")
info: SetGameOption(key="CivilianAlliance",val="removed")
info: SetGameOption(key="PrebuiltUnits",val="Off")
info: SetGameOption(key="NoRushOption",val="Off")
info: SetGameOption(key="RandomMap",val="Off")
info: SetGameOption(key="Score",val="yes")
info: SetGameOption(key="Share",val="yes")
info: SetGameOption(key="TeamSpawn",val="random")
info: SetGameOption(key="TeamLock",val="locked")
info: SetGameOption(key="AutoTeams",val="none")
info: SetGameOption(key="CheatMult",val="2.0")
info: SetGameOption(key="BuildMult",val="2.0")
info: SetGameOption(key="TMLRandom",val="0")
info: SetGameOption(key="LandExpansionsAllowed",val="5")
info: SetGameOption(key="NavalExpansionsAllowed",val="4")
info: SetGameOption(key="OmniCheat",val="on")
info: SetGameOption(key="ScenarioFile",val="/maps/scmp_007/scmp_007_scenario.lua")
debug: Loading module '\000/lua/maui/effecthelpers.lua\000'
debug: Loading module '\000/lua/ui/controls/combo.lua\000'
debug: Loading module '\000/lua/maui/statusbar.lua\000'
debug: Loading module '\000/lua/ui/controls/columnlayout.lua\000'
debug: Loading module '\000/lua/ui/lobby/changelog.lua\000'
debug: Loading module '\000/lua/ui/lobby/aitypes.lua\000'
debug: Loading module '\000/lua/ai/customais_v2/sorianai.lua\000'
info: ConnectToPeer (name=masch, uid=105161, address=127.0.0.1:54530)
info: NET: using deflate compression for sends to mp02.maniaplanet.com:54530.
info: LOBBY: Adding peer "masch" [mp02.maniaplanet.com:54530, uid=105161]
info: NET: using deflate compression for receives from mp02.maniaplanet.com:54530
info: LOBBY: connection to "masch" [mp02.maniaplanet.com:54530, uid=105161] made, status=Pending.
info: LOBBY: Got join (name="masch", uid=105161) from mp02.maniaplanet.com:54530
warning: {
warning: }
warning: {
warning: }
warning: {
warning:     MEAN = 1500
warning:     StartSpot = 1
warning:     ArmyColor = 5
warning:     PlayerClan = ""
warning:     NG = 0
warning:     Team = 1
warning:     Ready = false
warning:     PlayerColor = 5
warning:     Civilian = false
warning:     PlayerName = "masch"
warning:     AIPersonality = ""
warning:     ObserverListIndex = -1
warning:     Country = "de"
warning:     OwnerID = "105161"
warning:     PL = 0
warning:     Faction = 5
warning:     RC = "ffffffff"
warning:     Human = true
warning:     BadMap = false
warning:     DEV = 500
warning: }
info: LOBBY: "masch" [mp02.maniaplanet.com:54530, uid=105161] has established connections to: 102761
debug: Loading module '\000/lua/ui/dialogs/mapselect.lua\000'
debug: Loading module '\000/lua/ui/menus/main.lua\000'
debug: Loading module '\000/lua/maui/movie.lua\000'
debug: Loading module '\000/lua/ui/lobby/modsmanager.lua\000'

**Comment by PostalBlab** [comment]
I was able to find the option which is responsible for the exception.
Steps to reproduce:
1. Host a game
2. Go to "Options" and select a fitlerset which leads to an empty map list
3. Click "OK" and then "Exit", the filter is stored in Game.prefs->stored_filter_state
4. Host a game
5. Go to "Options"
6. Null pointer Exception

**Comment by JJ173** [comment]
Usually deleting your game.prefs fixes this issue but I'll have a look into it, thanks for the reproduction steps.

**Comment by duk3luk3** [comment]
Can't reproduce this in 3652, we recently made a change there (#1066 -> #1079) that should result in there never being an empty list.

**Comment by speed2CZ** [comment]
https://github.com/FAForever/fa-coop/pull/39 fixes it
