### ISSUE TITLE
Refactor UEF build effects

### ISSUE THREAD

**Issue by speed2CZ** [FAForever/fa#1125]
@Crotalus could the build box effect be also rotated according to the building?

http://puu.sh/nbf6q/e9aa546106.png

**Comment by Crotalus** [comment]
Good catch, I'll take a look at the code, hopefully easy to fix

**Comment by Crotalus** [comment]
UEF build effects need to be refactored, for instance, 100 engineers assisting a factory will spawn 100 projectiles constantly for every unit produced. Another ugliness is that the "cutting" of the box isn't synced at all with build beams.

Lets transform this issue into a more general UEF build effect one and fix it all at once

**Comment by aeoncleanse** [comment]
@Crotalus  - Think you can handle this one some-time before December?

**Comment by MrRowey** [comment]
@Garanas is this something that could also come under that Cybran changes you were looking at with the Engies ?

**Comment by Garanas** [comment]
Yes it is - good spot. I was aware of the projectiles being spawned, similar issue as with the drones initializing with all the unit logic while they are dummies.

**Comment by Garanas** [comment]
Closed in favor of #3371 .
