### ISSUE TITLE
Warning when dettaching units from transports

### ISSUE THREAD

**Issue by speed2CZ** [FAForever/fa#1130]
```
WARNING: Error running OnTransportDetach script in Entity xsa0104 at 20475608: ...\multimedia\documents\github\fa\lua\defaultunits.lua(1763): table index is nil
         stack traceback:
         	...\multimedia\documents\github\fa\lua\defaultunits.lua(1763): in function <...\multimedia\documents\github\fa\lua\defaultunits.lua:1760>
```
In current beta, coop
Units were loaded into transports using this function https://github.com/FAForever/fa/blob/develop/lua/ScenarioFramework.lua#L1307
This warning is for every unit dropped from the transport.

**Comment by Crotalus** [comment]
Oh, that's a nice function which would have been needed with transport lock I would have guess

**Comment by speed2CZ** [comment]
It's also causing shielded units not to turn on shields when dropped

**Comment by Crotalus** [comment]
See if latest commit fixes your issue, seems like the function sent the wrong bone to OnTransportAttach

**Comment by speed2CZ** [comment]
Yes, thanks, fixed by https://github.com/FAForever/fa/commit/bdbe55714a0d048368f3fc736d5ac997df9abbc2
