### ISSUE TITLE
ACU enhancements restrictions don't work anymore

### ISSUE THREAD

**Issue by speed2CZ** [FAForever/fa#1136]
In current beta ACU upgrade restrictions atopped working. It's done via this code I think
https://github.com/FAForever/fa/blob/develop/lua/ScenarioFramework.lua#L811

**Comment by aeoncleanse** [comment]
Sandbox, or part of your coop mission?

**Comment by speed2CZ** [comment]
part of the missions

**Comment by aeoncleanse** [comment]
Finally got a chance to test this. Can I ask exactly which enhancement restrictions you had fail, because in sandbox they seem to be all functioning correctly. I suspect it's a coop-only error.

**Comment by speed2CZ** [comment]
any, it doesnt work for any restriction, no matter what oyu put in the restriction table. Since beta patch

**Comment by aeoncleanse** [comment]
Must be something that 3652 changes that has not been copied to coop shadows.

**Comment by Crotalus** [comment]
@speed2CZ easiest way to quickly test it? I tried the first Aeon coop map and their the ACU gets new enhancements along the mission progress.

**Comment by speed2CZ** [comment]
Did you test in beta?

Else you can test it on any skirmish map. Edit it's script to this:
```
local ScenarioUtils = import('/lua/sim/ScenarioUtilities.lua')
local ScenarioFramework = import('/lua/ScenarioFramework.lua')
   
function OnPopulate()
   	ScenarioUtils.InitializeArmies()
end
   
function OnStart(self)
	ScenarioFramework.RestrictEnhancements({'ResourceAllocation',
                                            	'DamageStablization',
                                            	'AdvancedEngineering',
                                            	'T3Engineering',
                                            	'HeavyAntiMatterCannon',
                                            	'LeftPod',
                                            	'RightPod',
                                            	'Shield',
                                            	'ShieldGeneratorField',
                                            	'TacticalMissile',
                                            	'TacticalNukeMissile',
                                            	'Teleporter'})
end
```

**Comment by Crotalus** [comment]
Tested on a map now with 3652, it's still working for me :confused:
