### ISSUE TITLE
Seraphim wreck are almost invisible, Beta

### ISSUE THREAD

**Issue by speed2CZ** [FAForever/fa#1141]
http://puu.sh/nrzzM/0a54fa39a2.png T1 land units
http://puu.sh/nrzre/0594b697a6.png T1 T2 naval units
from quick test it affect all seraphim units
maybe caused by some of the @Crotalus recent reclaim changes?

**Comment by Crotalus** [comment]
:disappointed: 

Unfortunately shaders are not my strong point so reverted the change, some gfx dude can probably revisit it later if it is still wanted.
