### ISSUE TITLE
Wrecks immune to nukes

### ISSUE THREAD

**Issue by Crotalus** [FAForever/fa#1146]
You can no longer clear wreckages by nuking them, probably a regression from the "nuke bubble shield" change

**Comment by aeoncleanse** [comment]
I highly doubt it's that change. No, it will be the fact that nukes now damage things in an area directly using GetUnitsAroundPoint. Guess I need to do the same to fetch all props. Do you know how to go about doing that?

**Comment by Crotalus** [comment]
That's the change I meant, get the wrecks with GetReclaimablesInRect() and then check VDist2(wreck-pos, nuke-pos) to get the circle form of DamageArea

**Comment by aeoncleanse** [comment]
Could you quickly rig this up? Code's in sim/nukedamage.lua, I've too much uni work tonight

**Comment by Crotalus** [comment]
cf7c973
