### ISSUE TITLE
Did range ring changes cause this in BlackOps?

### ISSUE THREAD

**Issue by aeoncleanse** [FAForever/fa#1149]
"did the anti teleport unit lose its range ring with the new 3652 changes? (in blackops) at least it showed the ring before the latest build (i think!)

[12:18] 
let me change that statement - the range ring seems to exist ok when the units have been built - but the ring does not show while you have the unit selected for build (but not yet placed/started) seems to affect T2/T3 teleport tower and cloak generator for cybran (rings show ok for omni etc). Have not checked other factions for similar (edited)"

Could this have been the change which fuses engie buildranges?

**Comment by Crotalus** [comment]
I would guess blackops uses OVERLAYMISC for the anti teleport tower? A quick fix is changing it to OVERLAYINTEL instead and give radar ability to the tower, (if it doesn't have that). That way range will be shown.

**Comment by Exotic-Retard** [comment]
i take it overlaymisc is used since we cant add a new range ring?
kinda a shame since overlaymisc is supposed to be purple but now its that ugly yellow colour : (
