### ISSUE TITLE
Cybran nuke broken BETA

### ISSUE THREAD

**Issue by speed2CZ** [FAForever/fa#1154]
Ive got a report from one guy who was testing coop, that in second FA mission once AI's nuke themselves the umpack effect buggs out.
report here by Krizman http://forums.faforever.com/viewtopic.php?f=42&t=11868&start=10#p122420

I havent managed to reproduce it in sandbox yet, but I found out that if you nuke unscouted civilians, it won't kill them (tested with cybran nuke on Monaki map.)

his log got spammed by this:
```
warning: Error running OnImpact script in Entity /projectiles/cifempfluxwarhead01/cifempfluxwarhead01_proj.bp at 9d590280: c:\users\kristo\documents\fa\lua\sim\damagearea.lua(5): Game object has been destroyed
         stack traceback:
         	[C]: in function `GetArmy'
         	c:\users\kristo\documents\fa\lua\sim\damagearea.lua(5): in function `DamageArea'
         	c:\users\kristo\documents\fa\lua\sim\nukedamage.lua(16): in function `DoNukeDamage'
         	c:\users\kristo\documents\fa\lua\sim\projectile.lua(82): in function `DoDamage'
         	c:\users\kristo\documents\fa\lua\sim\projectile.lua(319): in function `OnImpact'
         	...s\kristo\documents\fa\lua\sim\defaultprojectiles.lua(140): in function <...s\kristo\documents\fa\lua\sim\defaultprojectiles.lua:128>
```

**Comment by aeoncleanse** [comment]
This suggests it's not forwarding an army, which I fixed... Hmmm. As for nuking of unscouted civilians, I'm entirely unsure of how to fix it. However, I consider it a better situation to have that happen over inconsistent performance against shielding, as it will so rarely make any difference. Also, the whole "Flash intel at start of map" means there should be no such thing as unscouted civilians any more anyway.

**Comment by speed2CZ** [comment]
if you've fixed that... how can is be happening?

reveal civs can be turned off, but anyway that feature doesn't work on my map

**Comment by aeoncleanse** [comment]
1c8251b6c29661085f77ed82230d5467e93177ea

This should fix the error with coop. Not tested against unscouted civs, though again, this should never be a thing anyway. Need to also test against stealthed, unscouted, and cloaked enemy units as well.

**Comment by aeoncleanse** [comment]
Crap. This doesn't go through Stealth...

**Comment by aeoncleanse** [comment]
Ugly hacks... Feedback please:

```        elseif damageAllies or not IsAlly(army, u:GetArmy()) then
            Damage(instigator, location, u, damage, type)
            
            -- Mark those damaged, then fall back on the original DamageArea to hit stuff out of intel
            if not u.Dead and u.CanTakeDamage then
                u:SetCantTakeDamage(false)
                u.Marked = true
            end
        end
    end
    
    oldDamageArea(instigator, location, radius, damage, type, damageAllies, damageSelf)
    for _, u in units do
        if not u.Dead and u.Marked then
                u:SetCantTakeDamage(true)
                u.Marked = nil
            end
        end
    end```

**Comment by aeoncleanse** [comment]
@Crotalus @speed2CZ Can I get final checks vs unscouted, stealth, and cloaked units please.

**Comment by speed2CZ** [comment]
Well coop worked, unscouted civs died as well but nuke explosion decal did not show up.

**Comment by aeoncleanse** [comment]
Decal as in the smudge on the ground?

**Comment by speed2CZ** [comment]
yes

**Comment by aeoncleanse** [comment]
3734907076140b9c20ef7de6824f8b7a90aea896
