### ISSUE TITLE
3652 - strange static stealth stuff

### ISSUE THREAD

**Issue by Exotic-Retard** [FAForever/fa#1155]
note: i could not replicate this in 3650. only the beta patch.
when you start energy stalling, stuff switches on/off repeatedly.
stealth is one of those things, and thats fine. so when you are e stalling it jumps up and down, and turns on /off

the issue is when you manually disable stealth generators (stationary) they continue behaving as if they are enabled! they dont drain e but they do start/stop their animations and effects. 
this is OBVIOUS with the aeon stealth gen, but true for all factions.

and then you stop energy stalling - then all stealth enables, but still being manually disabled
they all look like they are enabled, but dont drain e and dont provide stealth (you can still tell by the toggle and the strategic icon being crossed out)

whats perhaps more strange is that they toggle/trigger/something the OnIntelEnabled/OnIntelDisabled bits inside the unit scripts - which is visually annoying but if you have functionality in there then its functionally annoying too.

heres a picture of my disabled but unpacked aeon stealth generator: http://puu.sh/nE3mn/ff58aa9977.jpg

no sim mods were running when i was testing this (i know what you're all thinking!)

**Comment by aeoncleanse** [comment]
This seems to be what broke it: https://github.com/FAForever/fa/commit/3be2ac7a50c5e474fd3e03b7c177605d2534402d

Any ideas, @duk3luk3 ?

**Comment by Crotalus** [comment]
Maybe it respect evaluation order though...

**Comment by aeoncleanse** [comment]
0fb8d7a8132cf393fd18be35fc4ff2cde2d077ef
