### ISSUE TITLE
Torpedo killing sub nuke missile

### ISSUE THREAD

**Issue by Crotalus** [FAForever/fa#1164]
Seems like collisions between torpedos and missiles are allowed which resulted in a sub nuke missile being destroyed 1 tick after it was lauched.

On one hand it's cool that such thing can happen but in this case it was non-obvious that it actually happened (people are used with nuke missiles disappearing mysteriously but this was beta).

**Comment by aeoncleanse** [comment]
Regression or not?

**Comment by Crotalus** [comment]
No regression, could happen in / before 3650
