### ISSUE TITLE
Engineers assist nuke at an incorrect level

### ISSUE THREAD

**Issue by HardlySoftly** [FAForever/fa#1166]
Engineers went from the normal spend on nuke assist (-0m, -40e) to (-7m, -520e) after launching a nuke.  The nuke started being constructed at a much faster rate.

Replay 4569130, ~31 mins into game, Softles' nuke launcher.

As yet unable to reproduce in sandbox.

**Comment by aeoncleanse** [comment]
Duplicate of #1159 ?

**Comment by HardlySoftly** [comment]
The engineers were set to assist the nuke building not the com, so it is different to the issue described in #1159

**Comment by aeoncleanse** [comment]
Righto. Is this a regression or an old bug?

**Comment by Crotalus** [comment]
Well, the ACU (which built the nuke) was upgrading when the engineer's updated their consumption between nukes so this is the same issue. Something that's been in the game for a very long time.

**Comment by aeoncleanse** [comment]
I need confirmation this was fixed withh #1159

**Comment by Exotic-Retard** [comment]
just tested it and it appears fixed, reproduced it in 3650 but not in beta. hope this helps
