### ISSUE TITLE
Mermaid Hitbox Bug

### ISSUE THREAD

**Issue by manread** [FAForever/fa#1169]
The Mermaid cannot be hit by the UEF Battlecruiser or the Seraphim Destroyer aside from a little damage on the first firing cycle.

Replay where I originally found the bug: #4576105
Replay where I replicated the bug: #4576682 

If I have missed anything contact me on the client, username is the same

**Comment by aeoncleanse** [comment]
@Exotic-Retard  - Is this fixed in EQ? :p

**Comment by aeoncleanse** [comment]
Biass is making a few new bones to solve this.
