### ISSUE TITLE
Deleted move orders show up in spread attack

### ISSUE THREAD

**Issue by yorick-ne** [FAForever/fa#1177]
When you queue up some attack orders with some move orders inbetween, for example by missclicks, and delete those move orders by pressing ctrl-shift-rightclick on them, they will still appear after the spread attack command as if they never were deleted.

See Replay 4588278 
PS: It seems that if move-orders seems seperate groups of attack orders, these attack orders will only be shuffled within their group. Is this intentional and if so is this documented ?

**Comment by aeoncleanse** [comment]
This has been around since the feature was first made. Assigning 3653.

**Comment by speed2CZ** [comment]
The command is copied to spread attack here https://github.com/FAForever/fa/blob/develop/lua/ui/game/commandmode.lua#L257
Problem is that deleting a command does not trigger `OnCommandIssued` and therefore the new set of commands is not pasted to the spread attack.

**Comment by aeoncleanse** [comment]
Yep, that's where I dead-ended as well.
