### ISSUE TITLE
Errors in beta replay at last

### ISSUE THREAD

**Issue by aeoncleanse** [FAForever/fa#1178]
```WARNING: Error running lua script: ...alliance\gamedata\lua.scd\lua\ui\dialogs\options.lua(497): attempt to call method `SetText' (a nil value)
         stack traceback:
         	...alliance\gamedata\lua.scd\lua\ui\dialogs\options.lua(497): in function <...alliance\gamedata\lua.scd\lua\ui\dialogs\options.lua:494>```

```WARNING: Error running lua command: ...alliance\gamedata\lua.scd\lua\ui\game\zoomslider.lua(71): attempt to call method `GetMaxZoom' (a nil value)
         stack traceback:
         	...alliance\gamedata\lua.scd\lua\ui\game\zoomslider.lua(71): in function `ZoomOut'
         	[string "import("/lua/ui/game/zoomslider.lua").ZoomO..."](1): in main chunk
WARNING: UI layer has not been initialized.
WARNING: stack traceback:
WARNING:         [C]: in function `GetFrame'
WARNING:         ...nce\gamedata\mohodata.scd\lua\maui\effecthelpers.lua(28): in main chunk
WARNING:         [C]: in function `doscript'
WARNING:         [C]: in function `pcall'
WARNING:         ...alliance\gamedata\mohodata.scd\lua\system\import.lua(48): in function `import'
WARNING:         ...alliance\gamedata\mohodata.scd\lua\system\import.lua(37): in function `import'
WARNING:         ...data\faforever\gamedata\lua.nx4\lua\ui\game\chat.lua(4): in main chunk
WARNING:         [C]: in function `doscript'
WARNING:         [C]: in function `pcall'
WARNING:         ...alliance\gamedata\mohodata.scd\lua\system\import.lua(48): in function `import'
WARNING:         ...alliance\gamedata\mohodata.scd\lua\system\import.lua(37): in function `import'
WARNING:         ...
WARNING:         ...forever\gamedata\lua.nx4\lua\ui\game\commandmode.lua(10): in main chunk
WARNING:         [C]: in function `doscript'
WARNING:         [C]: in function `pcall'
WARNING:         ...alliance\gamedata\mohodata.scd\lua\system\import.lua(48): in function `import'
WARNING:         ...alliance\gamedata\mohodata.scd\lua\system\import.lua(37): in function `import'
WARNING:         ...\faforever\gamedata\modules.nx4\modules\hotbuild.lua(5): in main chunk
WARNING:         [C]: in function `doscript'
WARNING:         [C]: in function `pcall'
WARNING:         ...alliance\gamedata\mohodata.scd\lua\system\import.lua(48): in function `import'
WARNING:         [string "import('/modules/hotbuild.lua').buildAction..."](1): in main chunk
WARNING: ...alliance\gamedata\mohodata.scd\lua\system\import.lua(37): Error importing '/lua/maui/effecthelpers.lua'
WARNING: stack traceback:
WARNING:         [C]: in function `error'
WARNING:         ...alliance\gamedata\mohodata.scd\lua\system\import.lua(52): in function `import'
WARNING:         ...alliance\gamedata\mohodata.scd\lua\system\import.lua(37): in function `import'
WARNING:         ...data\faforever\gamedata\lua.nx4\lua\ui\game\chat.lua(4): in main chunk
WARNING:         [C]: in function `doscript'
WARNING:         [C]: in function `pcall'
WARNING:         ...alliance\gamedata\mohodata.scd\lua\system\import.lua(48): in function `import'
WARNING:         ...alliance\gamedata\mohodata.scd\lua\system\import.lua(37): in function `import'
WARNING:         ...\faforever\gamedata\lua.nx4\lua\ui\game\gamemain.lua(35): in main chunk
WARNING:         [C]: in function `doscript'
WARNING:         [C]: in function `pcall'
WARNING:         ...
WARNING:         ...forever\gamedata\lua.nx4\lua\ui\game\commandmode.lua(10): in main chunk
WARNING:         [C]: in function `doscript'
WARNING:         [C]: in function `pcall'
WARNING:         ...alliance\gamedata\mohodata.scd\lua\system\import.lua(48): in function `import'
WARNING:         ...alliance\gamedata\mohodata.scd\lua\system\import.lua(37): in function `import'
WARNING:         ...\faforever\gamedata\modules.nx4\modules\hotbuild.lua(5): in main chunk
WARNING:         [C]: in function `doscript'
WARNING:         [C]: in function `pcall'
WARNING:         ...alliance\gamedata\mohodata.scd\lua\system\import.lua(48): in function `import'
WARNING:         [string "import('/modules/hotbuild.lua').buildAction..."](1): in main chunk
WARNING: ...alliance\gamedata\mohodata.scd\lua\system\import.lua(37): Error importing '/lua/ui/game/chat.lua'
WARNING: stack traceback:
WARNING:         [C]: in function `error'
WARNING:         ...alliance\gamedata\mohodata.scd\lua\system\import.lua(52): in function `import'
WARNING:         ...alliance\gamedata\mohodata.scd\lua\system\import.lua(37): in function `import'
WARNING:         ...\faforever\gamedata\lua.nx4\lua\ui\game\gamemain.lua(35): in main chunk
WARNING:         [C]: in function `doscript'
WARNING:         [C]: in function `pcall'
WARNING:         ...alliance\gamedata\mohodata.scd\lua\system\import.lua(48): in function `import'
WARNING:         ...alliance\gamedata\mohodata.scd\lua\system\import.lua(37): in function `import'
WARNING:         ...orever\gamedata\lua.nx4\lua\ui\game\construction.lua(21): in main chunk
WARNING:         [C]: in function `doscript'
WARNING:         [C]: in function `pcall'
WARNING:         ...
WARNING:         ...forever\gamedata\lua.nx4\lua\ui\game\commandmode.lua(10): in main chunk
WARNING:         [C]: in function `doscript'
WARNING:         [C]: in function `pcall'
WARNING:         ...alliance\gamedata\mohodata.scd\lua\system\import.lua(48): in function `import'
WARNING:         ...alliance\gamedata\mohodata.scd\lua\system\import.lua(37): in function `import'
WARNING:         ...\faforever\gamedata\modules.nx4\modules\hotbuild.lua(5): in main chunk
WARNING:         [C]: in function `doscript'
WARNING:         [C]: in function `pcall'
WARNING:         ...alliance\gamedata\mohodata.scd\lua\system\import.lua(48): in function `import'
WARNING:         [string "import('/modules/hotbuild.lua').buildAction..."](1): in main chunk
WARNING: ...alliance\gamedata\mohodata.scd\lua\system\import.lua(37): Error importing '/lua/ui/game/gamemain.lua'
WARNING: stack traceback:
WARNING:         [C]: in function `error'
WARNING:         ...alliance\gamedata\mohodata.scd\lua\system\import.lua(52): in function `import'
WARNING:         ...alliance\gamedata\mohodata.scd\lua\system\import.lua(37): in function `import'
WARNING:         ...orever\gamedata\lua.nx4\lua\ui\game\construction.lua(21): in main chunk
WARNING:         [C]: in function `doscript'
WARNING:         [C]: in function `pcall'
WARNING:         ...alliance\gamedata\mohodata.scd\lua\system\import.lua(48): in function `import'
WARNING:         ...alliance\gamedata\mohodata.scd\lua\system\import.lua(37): in function `import'
WARNING:         ...forever\gamedata\lua.nx4\lua\ui\game\commandmode.lua(10): in main chunk
WARNING:         [C]: in function `doscript'
WARNING:         [C]: in function `pcall'
WARNING:         ...alliance\gamedata\mohodata.scd\lua\system\import.lua(48): in function `import'
WARNING:         ...alliance\gamedata\mohodata.scd\lua\system\import.lua(37): in function `import'
WARNING:         ...\faforever\gamedata\modules.nx4\modules\hotbuild.lua(5): in main chunk
WARNING:         [C]: in function `doscript'
WARNING:         [C]: in function `pcall'
WARNING:         ...alliance\gamedata\mohodata.scd\lua\system\import.lua(48): in function `import'
WARNING:         [string "import('/modules/hotbuild.lua').buildAction..."](1): in main chunk
WARNING: ...alliance\gamedata\mohodata.scd\lua\system\import.lua(37): Error importing '/lua/ui/game/construction.lua'
WARNING: stack traceback:
WARNING:         [C]: in function `error'
WARNING:         ...alliance\gamedata\mohodata.scd\lua\system\import.lua(52): in function `import'
WARNING:         ...alliance\gamedata\mohodata.scd\lua\system\import.lua(37): in function `import'
WARNING:         ...forever\gamedata\lua.nx4\lua\ui\game\commandmode.lua(10): in main chunk
WARNING:         [C]: in function `doscript'
WARNING:         [C]: in function `pcall'
WARNING:         ...alliance\gamedata\mohodata.scd\lua\system\import.lua(48): in function `import'
WARNING:         ...alliance\gamedata\mohodata.scd\lua\system\import.lua(37): in function `import'
WARNING:         ...\faforever\gamedata\modules.nx4\modules\hotbuild.lua(5): in main chunk
WARNING:         [C]: in function `doscript'
WARNING:         [C]: in function `pcall'
WARNING:         ...alliance\gamedata\mohodata.scd\lua\system\import.lua(48): in function `import'
WARNING:         [string "import('/modules/hotbuild.lua').buildAction..."](1): in main chunk
WARNING: ...alliance\gamedata\mohodata.scd\lua\system\import.lua(37): Error importing '/lua/ui/game/commandmode.lua'
WARNING: stack traceback:
WARNING:         [C]: in function `error'
WARNING:         ...alliance\gamedata\mohodata.scd\lua\system\import.lua(52): in function `import'
WARNING:         ...alliance\gamedata\mohodata.scd\lua\system\import.lua(37): in function `import'
WARNING:         ...\faforever\gamedata\modules.nx4\modules\hotbuild.lua(5): in main chunk
WARNING:         [C]: in function `doscript'
WARNING:         [C]: in function `pcall'
WARNING:         ...alliance\gamedata\mohodata.scd\lua\system\import.lua(48): in function `import'
WARNING:         [string "import('/modules/hotbuild.lua').buildAction..."](1): in main chunk```

```WARNING: Error running lua command: [string "import('/modules/hotbuild.lua').buildAction..."](1): Error importing '/modules/hotbuild.lua'
         stack traceback:
         	[C]: in function `error'
         	...alliance\gamedata\mohodata.scd\lua\system\import.lua(52): in function `import'
         	[string "import('/modules/hotbuild.lua').buildAction..."](1): in main chunk```

**Comment by aeoncleanse** [comment]
First one is in default code, not FAF hooked yet. Called right after a wait, so good chance the element can die.

**Comment by aeoncleanse** [comment]
@speed2CZ @Crotalus any clue on the other two?

**Comment by Crotalus** [comment]
Hmm, when did this happen? The top-most error in that log indicates an error when verifying options change (the OK button with timer)

**Comment by aeoncleanse** [comment]
Was a replay I found when replaying a slew of beta games looking for errors about a month ago. Anything here to worry about?
