### ISSUE TITLE
Feature: Intergate Supreme Score Board mod

### ISSUE THREAD

**Issue by HUSSAR-mtrela** [FAForever/fa#1182]
1. UI change - Intergate the Supreme Score Board (SSB) mod which also provides functionality of LazyShare mod in the Score Board UI.
   http://forums.faforever.com/viewtopic.php?f=41&t=10887
2. UI change - Add options for setting what data columns are displayed in the Score UI.
3. SIM change - Allow allied players to see their score data (mass income, energy overflow etc.)  Re-use some code from EcoManager  mod is doing it
4. Blacklist obsolete mods (LazyShare, SSB)

![ssb-in-game-session](https://cloud.githubusercontent.com/assets/11665978/14089418/d3a4f364-f502-11e5-9a47-f3175f2d388c.jpg)
![ssb-in-replay-session](https://cloud.githubusercontent.com/assets/11665978/14089419/d3aa42a6-f502-11e5-946b-0be60b7f974d.jpg)

**Comment by HUSSAR-mtrela** [comment]
@Sheeo can you add the following labels?
enhancement, nice to have, sim, UI, 3653

**Comment by MrRowey** [comment]
@Garanas #2982 the defult scoreboard has some of the features as SSB , share mass and energy / give units, shows income of team and storage

**Comment by Garanas** [comment]
Closed due to age of the issue and the fact that some of the features are implemented by KionX (from the top of my head) in the default scoreboard.
