### ISSUE TITLE
In-game Units Tooltips show inaccurate stats 

### ISSUE THREAD

**Issue by HUSSAR-mtrela** [FAForever/fa#1184]
In-game Units Tooltips show:
- inaccurate stats for DPS and rate of fire (e.g. beam weapons)
- wrong number of weapons
  http://forums.faforever.com/viewtopic.php?f=41&t=12106&p=124050#p124050

Proposed fix: 
- Re-use code to get correct stats used in tooltips of Units Manager 
- Add option to group stats for weapons by their type (anti-air, anti-naval, direct/indirect fire) or list stats for each weapon (current behavior). Which should be the default behavior?

**Comment by HUSSAR-mtrela** [comment]
@speed2CZ please add labels:  low, ui, bug, 3653

**Comment by MrRowey** [comment]
@Garanas 
![image](https://user-images.githubusercontent.com/20344151/140662492-123468c1-48e0-41ba-9229-c831279280da.png)
 This can be Close as this is already integrated in way
