### ISSUE TITLE
Potential fix for Mass Fabricators

### ISSUE THREAD

**Issue by Ravice** [FAForever/fa#1190]
A potential fix for mass fabricators that is currently solved by the likes of ecomod-esque UI mods by pausing is kindof inelegant.

I was recently made aware that that functionality for Anti/Nuke draining minimal energy/mass in a stall is hardcoded to anything with "SILO" in the BP.

So i would propose using this, by testing adding "SILO" to the mass fabricators' blueprints to provide the functionality of reducing fab energy drain in a stall without having to resort to UI mods.

**Comment by aeoncleanse** [comment]
It's also worth investigating other forms of auto-pause. Having an auto-manager coupled with a shield/radar like re-activation delay would make fabs easier to use, worth using, and render pointless all the grey-area ui mods which deal with this stuff in one fell swoop.

**Comment by Ravice** [comment]
i agree its good idea to use the autopause functionality too, in light of the upcoming OC changes, paused to use only excess power overflow seems the natural behaviour of mass fabs.

**Comment by speed2CZ** [comment]
Adding "SILO" to them will mess with targeting and most likely fuck up AI

**Comment by Thimization** [comment]
It seems easy enough to find and duplicate whatever the "SILO" tag is doing now to a "FABRICATOR" tag and leave the AI undamaged.

**Comment by aeoncleanse** [comment]
It's not. The effects of the tag are engine-side, and rather mysterious.

**Comment by MrRowey** [comment]
@Tagada14 If this is still something that doesn't need looking into can you close please :)

**Comment by MrRowey** [comment]
@Garanas this is fixed with your new implementation for mass fabs
