### ISSUE TITLE
Reporting Player BIK

### ISSUE THREAD

**Issue by Ecthelon** [FAForever/fa#1191]
Sorry if this is the wrong place to post this, but I couldn't find anywhere else.

Basically, I'm reporting a player called BIK for using drones to build on the cliff near the end of the attached replay, ruining the game.
Thanks in advance,
Ecthelon

**Comment by Ecthelon** [comment]
Oh sorry, apparently I cant attach the replay, what should I do?

**Comment by Sheeo** [comment]
Contact moderators. This is not the place.

**Comment by Ecthelon** [comment]
sorry.
