### ISSUE TITLE
Glorious new abuse of mass fabricators (pretty brutal too)

### ISSUE THREAD

**Issue by Exotic-Retard** [FAForever/fa#1192]
forget megalith egg abuse
you can stack the adjacency bonus! woohoooooo!
produce percivals for free!
(aren't you glad that e clan exists?)
http://puu.sh/o8qMg/4b4b291075.jpg
http://puu.sh/o8qN7/1579f3ffdc.jpg
http://puu.sh/o8qWK/47376b1f34.jpg
and finally the best one http://puu.sh/o8u6s/983e91c2e8.jpg
actually this one is even better: http://puu.sh/o8uAZ/9f8b7ef273.jpg

must be the whole point of engy mod i guess

from what i can tell:
1.build fabs first
2.turn off fabs
3.build factory and start production
4.receive free adjacency bonus with turned off fabs!
5.turn on fabs
6.receive double the adjacency bonus :D:D:D:D:D:D

oh and also that adjacency bonus still works when the fabs are disabled (not double though)
and it seems that the double adjacency is carried onto the future percies so you only need to setup once.
graciously discovered AND reported by e clan.
#VoteeclanForCouncilors
#WeAreTheLeadersFAFNeedsButNotTheOnesItDeserves
#AllPowerToeClan
#HopeForTheBest

**Comment by aeoncleanse** [comment]
Please don't be in beta... The number of times we've fixed fabs working when turned off...

**Comment by speed2CZ** [comment]
Both current patch and beta

**Comment by Exotic-Retard** [comment]
it looks like the bonuses are being applied when the fac is finished being built and when the fab is enabled.
so if you finish building and THEN enable they stack. there should be a check for any existing bonuses when fab is enabled? i dunno

**Comment by aeoncleanse** [comment]
94f9097c1a7962b91f54e726aa62a4702b25c410

Ta daa.
