### ISSUE TITLE
Wrong ACU DeathNuke Damage

### ISSUE THREAD

**Issue by speed2CZ** [FAForever/fa#1193]
Buildings take same damage as units 2500dmg, in super close range even 3500dmg.

**Comment by aeoncleanse** [comment]
Errrm? Wut? 2500 isn't a number related to nukes... Nor is 3500... Beta? Sandbox? Coop? Wut do!

**Comment by speed2CZ** [comment]
yeah and 3500dmg in very close range is some new stuff

beta, I guess your nuke changes broke it?

**Comment by aeoncleanse** [comment]
Must have... Odd that it didn't show in testing. Or perhaps I'm just ignorant of what the values should be. Can you give me a before/after for inner and outer values?

**Comment by speed2CZ** [comment]
well I didnt go that much in detail to check if outer radius works (by that I mean if its not by accident same as inner or something) but from the test most of the stuff got damaged by 2500 which should be right but for mobile units.

2000 inner 
500 outer 

I had only some T1 building around me so hard to say on pgens or mexes how much damage they took since they died, but only the factory that was almost touching ACU took 3500 damage. Other that were bit further away (still very close) took 2500.

- [ ] Fix the extra 1000 damage in close range
- [ ] Make buildings armor work again
- [ ] Check if outer damage works properly (is bigger)
- [ ] Check if sACU explosions works as intended

I think it would not be a bad idea to check other nukes as well to be sure if they work as intended.
- [ ] T3 nukes (inner/outer damage value/radius)
- [ ] T4 nuke (inner/outer damage value/radius)
- [ ] Nuke Subs + Sera Battleship (inner/outer damage value/radius)

**Comment by aeoncleanse** [comment]
Should be fixed with 7b450901d3c63c941832a20ba68bd3dafa512278

**Comment by Exotic-Retard** [comment]
tested this and all the czechboxes that speed2 provided are ok:
acu explosion: 2000+500 on buildings ; 64+16 on buildings.
sacu explosion: 1000+2(damn) on everything
nuke: 70,000+500 on expssss
sub nuke: 22,000+3,000 on expssss
BS nuke: 30,000 + 500 (hm not too impressed that this was forgotten about during the nuke sub changes)
exp nuke: 1,000,000 + 7500 on modified super expsssss
