### ISSUE TITLE
No Transport Restriction Prevents Building of UEF Stinger Gunships

### ISSUE THREAD

**Issue by HUSSAR-mtrela** [FAForever/fa#1198]
@everywhere116 pointed out to me that the "No Transports" restriction preset (in Units Manager) prevents building of UEF Stinger gunships. Since they can transport 1 unit but the main role of these units, is ground attack. So let's decide whether or not this restriction should exclude UEF Stinger gunships or is it correct right now?

**Comment by speed2CZ** [comment]
I would allow them, I'm not sure how often will this restriction be applied anyway but don't think it will be that gamebreaking.

Another problem is that no nukes will restrict seraphim battleship, But there isn't much to do with that I guess.

Maybe if restrictions are enabled to mod units to remove these special abilities from them.

**Comment by HUSSAR-mtrela** [comment]
@aeoncleanse @Crotalus @duk3luk3 
Let's have a few more people share their views on the no transport and then I will change if required.

As to nukes, we dont have no nukes restriction anymore but rather the following preset restrictions which help are more refined way of setting nuke restrictions:
- [x] No T4 Nuke Launchers which prevents T4 structures with strategic missile launchers (SML)
- [x] No T3 Nuke Launchers which prevents T3 structures with strategic missile launchers (SML)
- [x] No T3 Nuke Defense which prevents T3 structures with strategic missile defense (SMD)
- [x] No Nuke Naval Launchers which prevents T3 naval ships with strategic missile launchers (nuke subs + SERA battleship)
In addition, user can manually set custom restrictions by selecting/selecting units.

![unit-manager-v2 0](https://cloud.githubusercontent.com/assets/11665978/14531938/37167166-022d-11e6-8829-2cf6e451569a.png)

Ideally, we could check for categories set on weapons to determine whether or not a weapon should be restricted. However, that would require additional logic and all weapons (in projectiles.bp) would have to have correct categories). We can revise the units manager in the next patch if the current system is not good enough.

**Comment by aeoncleanse** [comment]
The overarching 'No Transports' should restrict the Gunship. Likewise, 'No Nukes' would restrict the Battleship and the Billy, however that's done fine above.

The _entire point_ of building this granular system was to nullify decisions like this. If it can transport a unit, it gets blocked, because that's the more major concern (Units arriving at inaccessible locations). If the host wants the Stinger enabled for some reason, all he has to do it turn it back on!!

**Comment by speed2CZ** [comment]
"People would use Stinger to build on the cliffs on Thermo" .. not possible, thermo is played no air :dart:

**Comment by aeoncleanse** [comment]
Not always. I've played at least a dozen games where air is allowed, but they didn't want PD/arty on the cliffs for some reason.

**Comment by HUSSAR-mtrela** [comment]
closing this issue since no one found it as valid issue given that Stinger can transport units so the "No Transports" restriction preset is defined correctly.
