### ISSUE TITLE
Units Manager is using an old icon for Seraphim faction

### ISSUE THREAD

**Issue by HUSSAR-mtrela** [FAForever/fa#1199]
Issue was found by @everywhere116

- [x] Icon of Seraphim faction in FAF Lobby:
![sera-lobby](https://cloud.githubusercontent.com/assets/11665978/14515682/46973fe8-01ca-11e6-9cdf-504f6e982197.png)

- [ ] Icon of Seraphim faction in Units Manager:
![sera-icon](https://cloud.githubusercontent.com/assets/11665978/14515681/4695c136-01ca-11e6-9501-44ea831b3936.png)

**Comment by aeoncleanse** [comment]
Just update to use the same path as the main lobby one.

**Comment by HUSSAR-mtrela** [comment]
verified a fix in FAF beta... closing this issue.
