### ISSUE TITLE
UnitsManager shows incorrect mass production for some units in tooltips

### ISSUE THREAD

**Issue by HUSSAR-mtrela** [FAForever/fa#1202]
Reported by @PerfectWay on forum thread:
http://forums.faforever.com/viewtopic.php?f=45&t=11336&sid=41029a21b41b033930ec7cf76e9ac216&p=125309#p125309

I noticed a few issues related to the economic characteristics of the units:
- T2 Mass Fabs show "Mass production: 0", but it should be 1
- ACUs (all factions) show "Mass production: 0", but it should be 1
- SACUs (except Seraphim) show "Mass production: 0", but it should be 1

**Comment by aeoncleanse** [comment]
It's probably this, no?

```local function init(value) 
    return value > 1 and value or 0 
end ```

Why is this here again?

**Comment by HUSSAR-mtrela** [comment]
I'm working on it but I dont think this code is the root cause of this issue. This code ensure that stats don't throw error when a value is nil.

**Comment by aeoncleanse** [comment]
It also ensures that values ranging 0-1 are returned 0, even if == 1. Should it not be return value => 1 ?

**Comment by HUSSAR-mtrela** [comment]
yes, that should be => 1

**Comment by aeoncleanse** [comment]
eda30c36089c41aef50cd13c2df02c71fa70e5e8

**Comment by HUSSAR-mtrela** [comment]
@aeoncleanse please push PR  #1206 because it has a hotfix for this issue

**Comment by aeoncleanse** [comment]
It's done. A close comment with a hash means the fix is merged :)
