### ISSUE TITLE
[3562] lobby dynamic string bug, showing extra %, and others.

### ISSUE THREAD

**Issue by Exotic-Retard** [FAForever/fa#1203]
so there are kinda 3 bugs with the lobby atm. 

the ai land expansion limit says 5% and not just 5 like it should. for naval expansion its correct.
http://puu.sh/ojmlk/25c9d5ed1e.png

2 boxes have the same descriptions. (yes sorry its in russian.)
the ai omni settings and the aix build multiplier have the same description on mouseover.
the omni needs to use aisettings_0148 and it looks like its using aisettings_0055
http://puu.sh/ojodo/d9edce499c.png
http://puu.sh/ojn0p/bb27096215.png

the presets button is using the wrong description on mouseover. 
it uses tooltipui_0691 which is an ingame description for "auto rebuild drones on death"

**Comment by aeoncleanse** [comment]
OK so land % is a reversion. Same description on the settings boxes is not. Neither is the presets button. 5s all over the no-rush is.

**Comment by aeoncleanse** [comment]
All issues here, as well as the 5 repeating in the No Rush options, fixed here:

Lobby: 94d544e6e784c54ba57f897aa28f91e3ae6577ec
Omni: f26003ccd4a265e51f18219eeecae106454adc08
Land Expansions: 2fd677b0a9651d348d71adf9f128af171b949339
No Rush: a3bacb2d5726e1d0cf3723d1cd6eac7d6aa20101

**Comment by Nojoke185** [comment]
checked all the above and working ok here
