### ISSUE TITLE
Units Manager show incorrect production stat for Presets SACUs

### ISSUE THREAD

**Issue by PerfectWay** [FAForever/fa#1204]
Units Manager and in-game tooltips show incorrect stats for preset SACUs when compared to their basic SACUs:
- [ ] same production stats as SACU without upgrades. e.g. RAS Preset produces 10 M and 1000 E, but show 0M and 20E.
- [ ] same built rate as SACU without upgrades, e.g. SERA Engineer Preset
- [ ] same shields/HP as SACU without upgrades,  e.g. SERA Rambo Preset
- [ ] all weapons are visible even for SACU without weapon upgrades, e.g. SERA Engineer Preset
- [ ] weapons damage/rate is not updated for SACUs with weapon upgrades, e.g. CYRBAN Rambo Preset

**Comment by aeoncleanse** [comment]
No way around that for now. It's because the changes are applied as upgrades.

**Comment by HUSSAR-mtrela** [comment]
we could update production stats for preset SACUs the same way we are changing cost of these units they are loaded and modified by the Blueprint.lua

**Comment by aeoncleanse** [comment]
We will. Setting it to 3653.

**Comment by MrRowey** [comment]
@Garanas
