### ISSUE TITLE
Target Painters

### ISSUE THREAD

**Issue by aeoncleanse** [FAForever/fa#1205]
I know this is possible because Domino has done it in the past. Painter function for Attack and Assist would be an enormous leap forward toward the goal of minimizing UI interference with player intention. It would be primarily used for Split Attack. 

I have left Reclaim off the list. While I'd personally love it, I recognise it is far more controversial than the Attack and Assist would be.

**Comment by shalkya** [comment]
unit targetting is fix in #2672
an additional ui mod is provided for advance targetting option.
