### ISSUE TITLE
Restriction system does not restrict any of SACUs and some other units

### ISSUE THREAD

**Issue by HUSSAR-mtrela** [FAForever/fa#1208]
The latest change (https://github.com/FAForever/fa/commit/410607930ef0b9c45a004dbde6a5ccde344cf577#diff-8f15a3675c02cf9bbf80d174fcbedb6e) in Game.lua limits restrictions to a half or all units. Using bp.Categories is not fully reliable way to find all valid/build-able units in the __blueprints table. Also, AFIK there is no set of categories that could be used to find these units unless one would go through all blueprints. Even if we find a set of categories then we would need to maintain it and there might not be a good way to enforcing this set of categories onto modded units. 

 Compare attached list of blueprints:
- [bps.now.txt](https://github.com/FAForever/fa/files/229187/bps.now.txt) 333 units
- [bps.correct.txt](https://github.com/FAForever/fa/files/229186/bps.correct.txt) 622 units

Also, the Game.GetUnitsUpgradable() does not returns only upgradable units but rather all units.

**Comment by aeoncleanse** [comment]
OK well I merged it, but I don't think this is the solution either. Please note that most of those units on your list are totally irrelevant. They are civilian structures, effect drones etc. How many units are found on your restrictions table? That's how many we want to have.

**Comment by HUSSAR-mtrela** [comment]
Yes, there are civilian structures in the bps.ids table and there should not be any effects bp nor any projectile bp. I will filter civilian units and check again for irrelevant units.
In the Units Manager, I'm showing only 507 blueprints (including enhancements) . So there are about 100 civilian units since there are 622 units in total.

**Comment by aeoncleanse** [comment]
That's why I decided on a positive reinforcement check. All things we want available CAN be checked by cats. I need to add COMMAND and SUPPORTCOMMANDER and SATELLITE, but beyond that I think we're good.

**Comment by aeoncleanse** [comment]
OK we're just gonna grab the table made by the unit manager.

**Comment by HUSSAR-mtrela** [comment]
Verified that change   https://github.com/FAForever/fa/pull/1209/commits/fc8c6a4ae5a416a725d806a9c7bfd98ee591643a fixed this issue
