### ISSUE TITLE
Add Rift Support Structure as Seraphim Experimental Unit

### ISSUE THREAD

**Issue by HUSSAR-mtrela** [FAForever/fa#1211]
Most factions have 4 experimental units but Seraphim has only 3 units:
- experimental  bomber (Ahwassa)
- experimental assault bot (Ythotha)
- experimental missile launcher (Yolona Oss)

I propose adding "hidden" Rift Support Structure as experimental unit to Seraphim faction in order to even number of experimental units. This unit already exists in FA game and is used only by AI in the last campaign mission.

Name: Seraphim Rift Support Structures
Specs: /units/xsc2201/xsc2201_unit.bp
Purpose: experimental "factory" that spawns multiple units at the same time for much cheaper costs producing them by T3 factories

TODO: decide what should be the cost for building this experimental unit.

**Comment by aeoncleanse** [comment]
No. It is a policy of FAF not to add units to the game unless _absolutely_ necessary. This is the kind of thing which belongs in mods, and has indeed been done several times. The only reason T3 MAA were added is because they were deemed necessary for gameplay.
