### ISSUE TITLE
Cannot deselect Mods in 3652 code

### ISSUE THREAD

**Issue by Nojoke185** [FAForever/fa#1219]
Problem = Cannot deselect Mods in 3652 code

to recreate...

fetch latest 3652 github code
load 3652 game code
enter Lan lobby/skirmish
select options
select mods
deselect some active mods (I tested this with UI mods)
select ok
select mods (to re-enter mods view)
mod(s) you just disabled remain active

alternative steps...(this sometimes works and sometimes fails for me)

fetch latest 3652 github code
exit FA game if loaded/running
Disable some FA UI mod(s) via the FAF client mods vault "manage UI mods" option
load 3652 game code
enter Lan lobby/skirmish
select options
select mods
mod(s) you just disabled (in FAF client) remain active

(checked the same scenarios in 3650 and its working ok there)

**Comment by Crotalus** [comment]
Thx!

**Comment by Nojoke185** [comment]
tested and fix works for me - quick service here!
