### ISSUE TITLE
Unit restrictions issue – mex upgrade

### ISSUE THREAD

**Issue by Nojoke185** [FAForever/fa#1223]
Unit restrictions issue – mex upgrade

With T2 tech disabled in unit restrictions all T2 tech is removed – except for T2 Factory upgrade (expected behavior)

If you build a T1 mex and try to upgrade it the upgrade chain shows only a direct path to T3 mex (T2 mex is not allowed and not shown)
When the upgrade is started the below error is seen and the upgrade cancels

WARNING: Unit.OnStartBuild() Army 1 cannot build restricted unit: <LOC urb1202_desc>Mass Extractor

Either allow the upgrade direct to T3 mex (from T1) or the upgrade chain should be updated to show no valid upgrades for the T1 mex

(Note you can directly build a T3 mex ok from T3 engi or T3 ACU)

**Comment by aeoncleanse** [comment]
@HUSSAR-mtrela We need to look at how the upgrade path UI handles this. It shouldn't be skipping things.

**Comment by aeoncleanse** [comment]
22c0360902e4f5b9b8c06dc42f1df067d5c4b13e
