### ISSUE TITLE
T2 Static Arty Blows Itself Up

### ISSUE THREAD

**Issue by HUSSAR-mtrela** [FAForever/fa#1227]
Reported by @piratep2r on forum: http://forums.faforever.com/viewtopic.php?f=2&t=12335

### Actual 
> Place your T2 static arty in a high place (you know, a place that would logically be suited for artillery), when an enemy gets close, your artillery will carefully sight down at the ground underneath itself (to lead the lower close target), and then blow itself and anything nearby up. Shield generators and TMD are particularly vulnerable to this.

### Expected - Potential Fixes

> 1. @piratep2r A simple solution would be to reduce their minimum fire angle to zero (or near zero) rather than negative. This is a less drastic change than simply making their firing arc much higher (like t3 arty).

> 2. @ZLO_RD: only fix i see is to make arty not shoot at all if it is going to hit terrain, witch is probably not easy to implement, or make it shoot higher arc in cases when turret attempts to fire at angle that is below 0 degrees from ground, or make it change muzzle velocity and always shoot at relatively high arc, and decrese muzzle velocity as target gets closer 

> 3. @angus000: other solutions are increasing min range or deactivating friendly fire

> 4. @Exotic_Retard: friendly fire off seems like the most obvious choice here.

### Replay

I reproduced this issue in latest FAF Beta (not a regression) and you can see it in a replay ID 4700942 (see FAF vault)

**Comment by HUSSAR-mtrela** [comment]
@Crotalus didn't you fix something similar in T3 mobile arty? Also, maybe T2 static arty should have similar firing arc as T3 mobile arty to fix this issue.

**Comment by Crotalus** [comment]
The t3 mobile arty bug I digged in was due to wrong muzzle velocity so not really related to this one.

I would say MinRadius sounds reasonable and maybe change pitch range so it cannot shoot into the ground at least. 

Friendly fire or not is a mess, should be some policy what should damage friendly units. Arty feels like a category that should damage friendly stuff.

**Comment by aeoncleanse** [comment]
The solution to this is not building Arty in dumbass spots.

**Comment by aeoncleanse** [comment]
@Zockyzock Final verdict please.

**Comment by Exotic-Retard** [comment]
(balance terrorists invading) friendly fire off combined with muzzle velocity reduce distance so it keeps a higher firing arc. added benefit of being of similar spread on lower distances and not being fucked due to the way low firing arcs work.

**Comment by aeoncleanse** [comment]
Friendly Fire off is dumb and lazy IMO. It's artillery. It goes BOOM. It should hurt things. The real solution for this issue is "Don't build Arty in dumb places". MuzzleVelocityReduceDistance is worth a look for sure though.

**Comment by Exotic-Retard** [comment]
well, it works xD
from what we discovered is that in most cases where the arty fires on friendliness it shoots itself as well; however units cant seem to damage themselves so you end up with this strange scenario where the arty survives but not everything around it. with it off you keep it consistent.

FF is a strange thing anyway. haven't discovered any rule for units with it disabled other than "if its cancer, turn it off" it applies to everything and anything and no one notices i.e. t1 arty, tml, fatty, t2pd, and more. then there are countless more units that dont collide with friendly.

btw i would also add strats and t1 bombers to that list, or stop them killing themselves with their own bombs somehow.

**Comment by Zockyzock** [comment]
If you change pitch you need to care that it can still shoot down from hills in not-dumb spots.

A reasonable minrange is fine. Friendly fire needs to stay, friendly fire off for artys only can be discussed but its messy and should not be needed with minrange. If too much minrange is needed however
Don't build Arty in dumb places" is an acceptable solution too.

**Comment by aeoncleanse** [comment]
pretty sure consensus is don't build in dumb places.

**Comment by Exotic-Retard** [comment]
i still strongly recommend MuzzleVelocityReduceDistance though. makes the unit much nicer at short ranges and helps with this issue too.
