### ISSUE TITLE
Saving templates dont save the correct IconName with modded units.

### ISSUE THREAD

**Issue by Uveso** [FAForever/fa#1228]
This Error only appears with modded units.

Saving build-templates don't use a correct uniticon, if the first unit inside the templatearray is not an original (unmodded) unit.

Example:
First build a modded unit like 'brnt1hpd' (total mayhem UEF T1 Powerdefence)
Second build a powerenerator like 'ueb1101' (UEF T1 Pgen)
Now select both buildings and klick "save template".

Inside game.prefs, this will be saved:
```
                    templateData = {
                        4,
                        2,
                        {
                            'brnt1hpd',
                            84,
                            0,
                            0
                        },
                        {
                            'ueb1101',
                            447,
                            2,
                            0
                        }
                    },
                    name = '<LOC brnt1hpd_desc>brnt1hpd',
                    icon = false
```
As u can see, it is saving "icon=false". This causes some problems inside construction.lua

Some lines from construction lua starting at line 786: (last beta build)
```LUA
        elseif type == 'templates' then
            control:DisableOverride()
            SetIconTextures(control, control.Data.template.icon)
            control:SetNewTextures(GetBackgroundTextures(control.Data.template.icon))
            control.Height:Set(48)
            control.Width:Set(48)
            if control.Data.template.icon then
                control.Icon:SetTexture(UIUtil.UIFile('/icons/units/' .. control.Data.template.icon .. '_icon.dds', true))
            else
                control.Icon:SetTexture('/textures/ui/common/icons/units/default_icon.dds')
            end
            control.Icon.Height:Set(48)
            control.Icon.Width:Set(48)
```
SetIconTextures(control, control.Data.template.icon) will fail, because "control.Data.template.icon" is "false" and not a string/UnitID/IconName

To solve the problem we need to change the function GetInitialIcon(template) inside build_templates.lua.
This is the original function:
```LUA
function GetInitialIcon(template)
    for _, entry in template do
        if type(entry) != 'table' then continue end
        if DiskGetFileInfo('/textures/ui/common/icons/units/'..entry[1]..'_icon.dds') then
            return entry[1]
        else
            return false
        end
    end
end
```
First of all the function is only looping over the first element of the template array. (after the first table is found)
Then, if the icon from the first unit inside the array is not found, it is returning "false"
Even if there are more units inside the Template, they will not checked for valid names.

This is a corrected version of GetInitialIcon:
(need to import a function from uiutil.lua, if the first Unit is not an original unit.)
```LUA
function GetInitialIcon(template)
    for _, entry in template do
        if type(entry) != 'table' then continue end
        if DiskGetFileInfo('/textures/ui/common/icons/units/'..entry[1]..'_icon.dds') then
            return entry[1] -- Original unit found
        else
            local UIUtil = import('/lua/ui/uiutil.lua')
            if UIUtil.UIFile('/icons/units/' .. entry[1] .. '_icon.dds', true) then
                return entry[1] -- Modded unit found.
            end
        end
    end
    return 'default' -- If we don't find a valid IconName; return string 'default'
end
```
This way, all elements of the array will searched for valid names, and only if nothing is found we return the text 'default'

But this will still cause an error in construction.lua.
We now have to change the function GetBackgroundTextures(unitID)
Because the unitID is in our case not an ID. It's the text 'default'
And 'default' is not a unit, so it has has no Blueprint. But GetBackgroundTextures use the blueprint to store the bp.General.Icon. (not uniticon!)

The new function should look like this:
```LUA
function GetBackgroundTextures(unitID)
    local bp = __blueprints[unitID]
    local validIcons = { land = true, air = true, sea = true, amph = true }
    local icon = "land"
    if unitID and unitID ~= 'default' then
		if not validIcons[bp.General.Icon] then
			if bp.General.Icon then WARN(debug.traceback(nil, "Invalid icon" .. bp.General.Icon .. " for unit " .. tostring(unitID))) end
			bp.General.Icon = "land"
		else
			icon = bp.General.Icon
		end
    end
    return UIUtil.UIFile('/icons/units/' .. icon .. '_up.dds'),
           UIUtil.UIFile('/icons/units/' .. icon .. '_down.dds'),
           UIUtil.UIFile('/icons/units/' .. icon .. '_over.dds'),
           UIUtil.UIFile('/icons/units/' .. icon .. '_up.dds')
end
```

And the last change is just cosmetic.
Changing the Warning in Uiutil.lua line 425:
```LUA
WARN(debug.traceback(nil, "Warning: Unable to find file: " .. origPath .. filespec))
```
to a Debug Text:
```LUA
SPEW('[uiutil.lua, function UIFile()] - Unable to find file:'.. origPath .. filespec)
```

---

And another smal template bug:
The Buildtemplate is named after the first unit inside the Array.
The name is from UnitDescription and has mostly the "\<LOC xyz_desc\>" inside the string.
We could filter the name to make it look better!
I would suggest this change to the GetInitialName function: (build_templates.lua)

```LUA
function GetInitialName(template)
    for _, entry in template do
        if type(entry) != 'table' then continue end
		return (string.gsub(__blueprints[entry[1]].Description, '^<[^>]*>', '')) -- removes <LOC xyz_desc> from name
    end
end
```
This way, the new template not always show the name "\<LOC"

**Comment by Uveso** [comment]
[Edit]: removed placeholder with 'default' and add a change to construction.lua. This way it isnt a workaround, now its a bugfix :)

**Comment by aeoncleanse** [comment]
11ae2d776650accbc12d467661c9b13ea9f2e772
