### ISSUE TITLE
3652 Survival maps bug

### ISSUE THREAD

**Issue by Kempior** [FAForever/fa#1230]
With beta patch additional civilian armies used by survival maps ignore setting Ally/Enemy with player in map script.
When looby setting is set to enemy civilians all additional armies are hostile to player, when set to neutral civilians all armies are neutral to player.
Most likely either lobby option is overwriting set civilian army alliances with players or function to set alliance in script is ignored.
With current patch it is not happening only in 3652 beta.

**Comment by aeoncleanse** [comment]
I've tried it but, not being a Survival player... I thought the default setting was Enemy, and that on Survival maps, all the AI were Enemy anyway...

**Comment by Kempior** [comment]
There are maps with Ally AI where you have to defend a unit or building for example:
-Survival Run
-Survival Escape
-Desert Swarm
With beta patch when civilian are set to Enemy the unit/building you are supposed to be allied with and defend is enemy and in turn your units/defenses are trying to kill it.

**Comment by aeoncleanse** [comment]
Error appears with f9b65192

**Comment by aeoncleanse** [comment]
@Crotalus

**Comment by Crotalus** [comment]
f949722f0eaa97e0070317764e04890e8041c4c1

With the above fix, in desert swarm, the perimeter system in middle is allied and the units rushing in from edge of map is enemy.
