### ISSUE TITLE
Unused folder

### ISSUE THREAD

**Issue by HardlySoftly** [FAForever/fa#1231]
lua/AI/CustomAITooltips/

**Comment by Sheeo** [comment]
Please provide additional description of the issue and request reopening.

**Comment by speed2CZ** [comment]
Doesn't look unused https://github.com/FAForever/fa/blob/release/3652/lua/AI/CustomAITooltips/SorianTooltips.lua

**Comment by HardlySoftly** [comment]
All the Sorian Tooltips are defined in the regular tooltips file, see: https://github.com/FAForever/fa/blob/develop/lua/ui/help/tooltips.lua#L972

The contents of this folder are not loaded anywhere in the code, which forms the basis for my "unused" classification.

**Comment by Sheeo** [comment]
Original diff is so enormous (https://github.com/FAForever/fa/commit/2c799fbf29c143b9571cac656c31d99554acf789) that it's hard to tell what kind of code used to use this.

If it's entirely unused now: cleanse.

**Comment by Sheeo** [comment]
@HardlySoftly I invite you to provide a PR for this, since you're the filer of the issue :)

**Comment by Uveso** [comment]
As i can see, the only location where the tooltips where loaded was in the old version of "EnhancedLobby.lua" (function GetCustomTooltips()).
This was part of the 03_lobbyenhancement.scd shipped with the original sorian_ai_pack_2.1.2 download.

Now all tooltips are included inside tooltips.lua
Also the function GetCustomTooltips() no longer exist inside "EnhancedLobby.lua".
The CustomAITooltips folder is no longer in use and can be deleted.

**Comment by Uveso** [comment]
fixed, please close.
