### ISSUE TITLE
Cancelling the download of a game file update should cancel the whole update process and not launch the game.

### ISSUE THREAD

**Issue by GuyGuyGuy** [FAForever/fa#1236]
As per the title.
Currently if you are not running the latest (or relevant version, in the case of an old replay) then a download dialog spawns for each of the game files for the required version. If you click the **Cancel** button on any of these dialogs, _only that specific download is cancelled_ but the process continues, immediately launching another dialog to download the update for the next file. The game also then attempts to launch FA anyway, without the updated file that you cancelled. Surely that doesn't make sense.
Ideally there should be one file download dialog box that remains on screen during the whole download process, regardless of the number of files involved. If the user clicks **Cancel **then the whole download and launch process should stop without any changes being made.

**Comment by Sheeo** [comment]
Moved to FAForever/client
