### ISSUE TITLE
Slots closed in lobby not visible as such to newly joining players

### ISSUE THREAD

**Issue by aeoncleanse** [FAForever/fa#1237]
http://forums.faforever.com/viewtopic.php?f=3&t=12353

Not a 3652 regression.

**Comment by Crotalus** [comment]
For reference, this line is the culprit resetting ClosedSlots for someone just joining:

https://github.com/FAForever/fa/blob/develop/lua/ui/lobby/lobby.lua#L1491

When someone joins their game state is reset with UpdateAvailableSlots() and ClosedSlots is reset before it even can be rendered correctly in UI.

**Comment by aeoncleanse** [comment]
Moving this back into the limelight. @Justify87  - What happened with this? Did your fix work?

**Comment by Uveso** [comment]
I think we have a fix for it now: #1567

**Comment by aeoncleanse** [comment]
1d98cf18ef15be8ee3c22d5fa16eb573704e11cd
