### ISSUE TITLE
ACU + Engineer + Reclaim Building = Stuck

### ISSUE THREAD

**Issue by aeoncleanse** [FAForever/fa#1240]
http://forums.faforever.com/viewtopic.php?f=3&t=12357 explains what is going on. @Crotalus I'd like you to investigate this, you're our best bughunter.

**Comment by Crotalus** [comment]
Tested <3652 and seems like the bug was there as well

**Comment by zlo-faf** [comment]
that happens all the time,
it is just engyneer's task not getting updated when ACU decideds to do something else
i mean you could start t3 pgen and walk away and t1 engies that assist will finish building and that is fine
but if you replace "walk away" with "reclaim that same building" then you get stuck ofc...

this "stuck" thing happens any time when you order one unit to reclaim a building while other unit is still tryes to build it
i guess there is more than one possible solution, but i just hope fix for it will not break anything
