### ISSUE TITLE
Free intel on upgraded structures.

### ISSUE THREAD

**Issue by CodingSquirrel** [FAForever/fa#1245]
I'm basing this off of watching my own replay from my opponent's perspective.

After gaining initial intel on my structures my opponent was able to see every time I upgraded a structure. Not just the darkened out icon, full view as if they had scouted. They saw mexes and factories. Not only that but they were able to see the upgraded factories working, all of the animations running, the unit in production, and see the first second or so as the unit came off the pad.

I wasn't able to see much going the other way, since my opponent didn't upgrade much. Except he got a t3 mex (all t1 stuff but a t3 mex, go figure) and I was able to watch it animate and spin when I had no vision on it.

Even if it's fixed so that the animations and such don't play, I think it's worth having a community discussion whether we want this new "full intel" on upgraded structures or the old way that they went dark. I personally don't like the new way because at least the old way had the chance that the building was destroyed instead, and you couldn't tell if it was still t2 or t3 if you didn't scout again. Now you can see it go from t1 all the way to t3 without ever scouting past the first minute.

**Comment by aeoncleanse** [comment]
The new intel was meant to be an instant flash if I remember, not visible because it should happen inside a single tick... @Crotalus I think this is your handiwork, care to elaborate?

**Comment by JJ173** [comment]
I did some testing and it does more than just animate, apparently it gives brief intel of nearby units and structures. I can also see what's being built by upgraded factories. I used an Easy AI to test the problem. Scouted at the start of the game as you would a normal game. When the AI completed an upgrade, the intel became available, I could see units moving around the upgraded Mex's as well as being able to see what is being built by an upgraded factory. Bare in mind I only scouted the once when all of those structures were at Tech 1. 

https://i.gyazo.com/6b425858d45c8f78068ef15bfb34e26e.png

https://i.gyazo.com/8734fe8a7bbb3de40f12bef678b9b7d1.png

**Comment by Crotalus** [comment]
Hmm, yeah, the problem with the "dark" intel blips is that they are completely untargetable, if the engine was clever they would reference to the upgraded building when right-clicked.

We could flash with 'Radar' vision instead, that would reset blip but make the actual uit invisible from   "vision" recon. This will result in the factory having icon but being invisible until scouted, like battleships only on sonar.

**Comment by aeoncleanse** [comment]
Well, @Crotalus my problem is why is the intel blip so big? I mean, it's giving pretty serious vision for a noticeable length of time, why is it not just for one tick for a tiny, 1 radius area???

**Comment by Crotalus** [comment]
God(GPG) works in mysterious ways.... the noticeable vision length is due to the always present lag to the intel system. And without radius 2 it didn't refresh the blip for some reason, maybe it's some weird requirement of unit size % within sight or similar.

**Comment by Exotic-Retard** [comment]
looking at your fix @Crotalus, does that affect normal-dead buildings? if so that's undesired behavior.
im not exactly sure on what the best course of action would be, but things like moving blips away after some time (not immediately), differentiating between upgraded structure and dead structure, might help

**Comment by aeoncleanse** [comment]
Code is here: https://github.com/FAForever/fa/pull/425/files

Presently it appears to rely on the blip being destroyed naturally at the next intel update. Has anyone tried manually insta-refreshing, or manually flashing it without that delay?

**Comment by aeoncleanse** [comment]
I also don't understand how this refreshes the blip anyway, seeing as it's using optical vision not radar (Which the blip is, as it only applies to unscouted stuff)... Also, the blip is moved THEN revealed... So how it that going to work?

We need a new approach.

**Comment by Crotalus** [comment]
You don't understand how an expired optical blip is destroyed when re-scouted? Hmm, when was the last time you played the game? That's a basic game mechanic.

So what approach do you suggest?

**Comment by aeoncleanse** [comment]
Well thats the thing mate, it doesn't work half the time. Lots of playtesting last night and we get variable results with it. The trouble is that sometimes, for some reason, the optical reveal does NOT vanish. I can only assume it's because the blip doesn't vanish...

**Comment by Crotalus** [comment]
Ok now I'm on the same page, thought we were talking about the brief flash of intel but if it's permanent then yes

**Comment by Crotalus** [comment]
Blip probably survives to to the weird intel <-> size thing, the new blip is put on the old when getting vision without the old dying, increasing radius kills it though.

So solutions could be:

1. Increase radius depending on underlying unit size, would have to be tested so nothing around it like mass storages are revealed
2. WaitSeconds X after intel and just disable it that way
3. Add trigger to brain:OnIntelChange and remove vision at the instant the brain gets the new intel blip

3 is maybe the cleanest solution, don't know if it's the most efficient one though. In theory we would only need one vision per team though instead of one per army as it is now. Another optimization could be to just add one turn off trigger even if X blips are flashed, I guess they all get vision at the same tick so a function could just loop all blips that was flashed.

**Comment by Crotalus** [comment]
Made a PR which manually resets vision if it for some reason survives after 5 ticks, tested with 4v4 AI, if someone is bored feel free to test it.

**Comment by CodingSquirrel** [comment]
Does that still give Intel from t1 all the way to t3? I still think this needs more conversation of whether this is better than what we had before. Maybe instead of vision reveal give a radar blip instead?

**Comment by Crotalus** [comment]
Can't use radar blip, structures disappear unless under constant radar coverage :/ Would have to have perma-radar on every upgraded building for every team then :/

**Comment by Crotalus** [comment]
Found a better way of solving perma-vision though, the blip of the upgraded building inherited the builder's vision, that's why it got permanent

https://github.com/FAForever/fa/commit/fa764a2c4ff7aeab3d76741240f209a89a93f8bb

**Comment by Crotalus** [comment]
Bah, didn't help either, wtf is this... very weird

**Comment by CodingSquirrel** [comment]
What's wrong with perma-radar?

**Comment by Crotalus** [comment]
Problem with permaradar is that you would see units around the building / factory / mex or similar

**Comment by CodingSquirrel** [comment]
You sure there's no way to apply it directly to the unit instead of using a small radius?

We were able to give direct vision to beam weapons that are firing from outside of vision, without revealing everything nearby, no?

**Comment by Crotalus** [comment]
The beam vision stuff uses a vision radius of 2, anything less just make the unit blind :/

**Comment by aeoncleanse** [comment]
Yeah I went though most of this crap last night. It's not an easy fix! I'd like to ship the hotpatch, and recommend reverting to old behaviour until we get this sorted.

**Comment by JJ173** [comment]
What about the UEF artillery shell that's fired from T1 mobile artillery? It gives off a small Intel radius when the projectile disperses and disabled when it's destroyed, could that not be manipulated to fix this issue?

**Comment by JJ173** [comment]
Main problem I had last night is I was getting Intel for 2 buildings on the same position of the first upgraded unit. It was naturally showing a Tech 2 unit icon after finishing the upgrade but if you hovered over it with your mouse, the old blip for the T1 unit appeared, which was darkened and untargetable.

**Comment by Crotalus** [comment]
Tested minimum radar range required, it has to be radius >= 4 on an entity (tested on mex) to even give off a radar blip of itself. So if we want "grey radar blip" for upgraded units we probably can't avoid also showing off radar blips of units in the immediate vicinity (assisting engies etc).

**Comment by JJ173** [comment]
Problem is even if you disabled the intel straight away, we'd still the new upgrade. Whether that can be a temporary fix to avoid "free intel" problem, might be a way to go?

**Comment by aeoncleanse** [comment]
No. We cannot fix the free intel part of this. I know of no way to have NO CHANGE of blip or visuals. Given that, I think @Crotalus is right to try to kill the 'Can't be targeted' part.

**Comment by aeoncleanse** [comment]
@Crotalus  -  Even your latest version of this code has _not_ fixed the issue. I am ruling that we are reverting the change for the time being until we can get it properly figured out.

**Comment by Crotalus** [comment]
Yuuup, tested now with 4v4 AI and blips seem to still be "darked out",. I guess that's what you mean with not working? Or is it still permasight?

Maybe the intel discovery lag depends on how many players / blips there are on the map... probably setting vision on the dead blip is a dead-end, it's getting destroyed too fast.

**Comment by aeoncleanse** [comment]
Permasight still. I've reverted it for now. This may be impossible, unless we find a new approach.

**Comment by aeoncleanse** [comment]
Moving to 3656

**Comment by aeoncleanse** [comment]
f7ac782a6825d53ebac51494a946e42ac1a65ef4
