### ISSUE TITLE
civilians not always being revealed on map start.

### ISSUE THREAD

**Issue by Exotic-Retard** [FAForever/fa#1251]
pretty much what it says. civilians not shown on vya-3. 
here is the replay in question - neither player gets civilians revealed: #4719933
however upon testing they were revealed in a sandbox :| might be sth to do with ladder. 

so not super easy to reproduce i guess but here you go anyway

**Comment by Zockyzock** [comment]
likely the option is just not enabled for ladder?

**Comment by Crotalus** [comment]
Yeah that was the issue, fixed in next patch.
