### ISSUE TITLE
Aeon TMD possibly too slow.

### ISSUE THREAD

**Issue by JJ173** [FAForever/fa#1252]
So it was brought to my attention that certain TML missiles can be fired over Aeon TMD. I'm not sure if this is a problem or not but I did some testing and there are certain units that can fire over Aeon TMD and some that cannot. I tested with Aeon TML which was able to fire over the TMD and wasn't countered. I then tested Seraphim ACU TML which was caught by the TMD projectile and destroyed. I guess it depends on how high the TML projectile is. I thought I'd report this as a precautionary measure.

**Comment by speed2CZ** [comment]
This is known thing that Aeon TMD is shit, it cant be used like other TMDs where you place few in front of your base and you're good since TML can easily fly over and kill all mexes in the back. Fixed in you know where as @Exotic-Retard would say.

**Comment by Exotic-Retard** [comment]
a height difference is often enough to abuse this. put your tml on a hill and you can quite often ignore aeon tmd if its close enough, and far enough from the thing youre trying to tml. but this is a balance issue so not up to anyone i guess (and yes fixed in you know where xD)

**Comment by duk3luk3** [comment]
Aeon TMD fires slowly, has low range, and can be flown over by some missiles. However, it needs only one shot to kill infinity missiles and is essentially barrage proof unless someone expends a lot of micro to exhaust the TMD with a bait missile and then get barrage to pass TMD while it is reloading.

IMHO this does not need to be changed. Don't play Aeon if you don't like the trade-offs its TMD has.

**Comment by JJ173** [comment]
If you had read my post, this was brought to my attention by another player who wasn't happy about it so I did some testing. I don't have a problem with playing Aeon, I put it on here as a precautionary measure. :)

**Comment by aeoncleanse** [comment]
Fixed by using the triplet projectile
