### ISSUE TITLE
deciever intel effect doesnt get cleaned up.

### ISSUE THREAD

**Issue by Exotic-Retard** [FAForever/fa#1254]
pretty much what it says on the tin. observe pretty pictures - made by toggling deciever stealth.
http://puu.sh/oJxna/88812cb0c6.jpg
http://puu.sh/oJxti/4553b7cc26.jpg

could be abused to give everyone cancer i guess xD

im not really sure whats going on here to be honest. on the first toggle it seems the effects go away, but afterwards it ends up enabling more than one, and it just gets worse from there.
looks like somewhere there is another enable intel effect code which

**Comment by JJ173** [comment]
Looks like a loop in the FX, did you reproduce this bug several times?

**Comment by JJ173** [comment]
This could cause Sim Speed problems in the long run :-1:
