### ISSUE TITLE
Walking ACU when guarding something

### ISSUE THREAD

**Issue by Crotalus** [FAForever/fa#1256]
An assisting unit with offensive abilities like ACU thinks it's a good idea walking towards an enemy unit within GuardScanRadius instead of assisting the actual structure.

http://forums.faforever.com/viewtopic.php?f=3&t=12379

**Comment by Exotic-Retard** [comment]
maybe you could try a workaround by reducing its GuardScanRadius.

however this has side-effects with patrol and attackmove reducing the radius of reclaimed things. would require nice testing to see if this works properly and doesn't ruin something else.

**Comment by Justify87** [comment]
The ACU starts walking even if no enemy is in range. Like miles away. 
It also always starts walking to the north of the map. Afaik it only happens with the cybran ACU and then only if it has the t2 suite.

I will try to reproduce when I have time.
