### ISSUE TITLE
Give transport stealth range ring if deceiver is loaded

### ISSUE THREAD

**Issue by Zockyzock** [FAForever/fa#1257]
to make it more clear that it works in transports, and that it'll stealth other transports too

**Comment by JJ173** [comment]
I think the Deceiver script needs some TLC, I've seen multiple errors posted here recently about that specific unit. If I can find it when I have time, I will take a look.

**Comment by Uveso** [comment]
URL0306_unit.bp
UnitName = '<LOC url0306_name>Deceiver',
Description = '<LOC url0306_desc>Mobile Stealth Field System',

**Comment by JJ173** [comment]
I'll take a look at applying this today Zock, I tend to speed read through OP's. I thought this was a problem instead of a request :). I'm going to patch up the deciever, and I'll apply this to the transport :).

**Comment by aeoncleanse** [comment]
Just a warning, this is not going to be a simple change. The objective is to get the _transport_ to display the range ring when selected. The only way I can think of to do this is to give all transport units a dummy stealth field which only turns on when a Deceiver is loaded...

**Comment by Zockyzock** [comment]
Wouldn't this add the tooltip "stealth" to the transport?

**Comment by aeoncleanse** [comment]
Not if we didn't put that ability line in, no. Tooltips are controlled separate from what a unit can actually do.

**Comment by Uveso** [comment]
While reading game lua files i found something that might help here.
Inside BuffField.lua i found this:
```LUA
    -- these 2 are a bit weird. they are supposed to disable the enabled fields when on a transport and re-enable the
    -- fields that were enabled and leave the disabled fields off.

    DisableInTransport = function(Owner, Transport)
        for k, field in Owner.BuffFields do
            if not field.DisabledForTransporting then
                local Enabled = field:IsEnabled()
                field.WasEnabledBeforeTransporting = Enabled
                if Enabled then
                    field:Disable()
                end
                field.DisabledForTransporting = true -- to make sure the above is done once even if we have 2 fields or more
            end
        end
    end,

    EnableOutTransport = function(Owner, Transport)
        for k, field in Owner.BuffFields do
            if field.DisabledForTransporting then
                if field.WasEnabledBeforeTransporting then
                    field:Enable()
                end
                field.DisabledForTransporting = false
            end
        end
    end,

```
if i understand this right, this is the point where buffFields from Units will be disabled on loading to the Transporter.
Maybe this is the right point to Buff the Transporter with range rings ?
Just a thought...

**Comment by aeoncleanse** [comment]
Thing is you can't buff a transporter with a range ring. To have the ring, it has to have the ability (off) at all times. This would probably be the right place to trigger it, but _boy_ is that an ugly hack...

**Comment by Uveso** [comment]
You are right. At this moment i dont really see a chance to add this ability to transporters.
Creating a dummy cloak field is maybe possible, but what if we transport another stealthed unit like the commander or a modded unit with different Range rings.

I don't see a clean way to change the transporter.
What about not disabling the rangering from the deciever while loaded on a transport ?

**Comment by Crotalus** [comment]
Range ring isn't disabled for the deceiver while in a transport, it's just that the unit isn't selected when you select the transport. If you enable permanent counter-intelligence range rings you will see the deceiver range.

A solution could be to enable permanent counter-intelligence range rings while you have a transport with deceiver selected. Otherwise we probably have to resort to the ugly "range ring texture hack" (which the old build range used).

As a side note we probably should make the stealth range ring a bit thicker and change color from dirt, purple seems to be stealth-color in this game.

**Comment by aeoncleanse** [comment]
No real solution. Just use the permanent rings option.
