### ISSUE TITLE
walking while building

### ISSUE THREAD

**Issue by shalkya** [FAForever/fa#1258]
We finally found a way to reproduce the bug.
Give a move order, OC yourself (for an acu) or repair a full health building (works for acu/engie), build something in the range (no reclaim under).

I will put logs and replay later

**Comment by shalkya** [comment]
https://faforever.slack.com/files/keyser/F15RB1PLP/4718172-keyser.fafreplay
https://faforever.slack.com/files/keyser/F15RG60CR/replay.log
https://files.slack.com/files-pri/T02T320UA-F15PVPQSF/download/forever.log

https://faforever.slack.com/files/keyser/F15RNEUGN/4718308-keyser.fafreplay
https://faforever.slack.com/files/keyser/F15RW6AVD/replay.log
https://files.slack.com/files-pri/T02T320UA-F15RW6HU7/download/forever.log

**Comment by HUSSAR-mtrela** [comment]
@shalkya @aeoncleanse I think this issue is related to #1015 and probably we need to add additional checks for state of an unit before performing a new task

**Comment by aeoncleanse** [comment]
Confirmed, both methods for reproducing this work.

**Comment by aeoncleanse** [comment]
More info - self:IsUnitState('Moving) returns false during this stupidity. Both commands are also engine functions, so it seems the engine doesn't tell the unit that it's moving again, rather than carrying out the failed command, once it fails.

**Comment by aeoncleanse** [comment]
OK so the story here is that I fixed it by forcing units not to move, but this broke units being able to move out of the way while building when another builder placed a new building under them. So I had to revert it :(
