### ISSUE TITLE
fix ythota deathball not spawning if it gets reclaimed instead of being killed 

### ISSUE THREAD

**Issue by Zockyzock** [FAForever/fa#1260]
people often get rid of the ball by reclaiming ythota when it is almost dead

**Comment by zlo-faf** [comment]
Is this even a bad thing?
Practically this deathball is part of deathweapon, when chicken dies it deals 10k damage + releases deathball
So you propose to still releace deathball even if deathweapon did't fire?
Or deathweapon should fire anyway with deathball, cause then chicken will be exeption compared to other things like GC, t3 pgen, nuke, not sure about para

**Comment by zlo-faf** [comment]
I mean, it is considered being normal, that when things are reclaimed, they don't explode

**Comment by aeoncleanse** [comment]
This has long been considered a feature, though I've always been hesitant over that. Has the decision been made to have it always spawn the ball?

**Comment by speed2CZ** [comment]
you can ctrl k it if you dont want your opponent to reclaim it

**Comment by Zockyzock** [comment]
I'd enable death weapon when reclaimed for all units (not buildings) if in doubt, but keeping death weapon off for everything, just spawning the ball without the death weapon would be consistent and fine with me too. 

Only for finished units though, reclaiming unfinished exp should not cause the death weapon.

**Comment by Uveso** [comment]
The deathball (spiritUnit) is not a DeathWeapon. Its created inside the DeathThread of the unit.
This is the code from Ythotha (xsl0401)
```LUA
        # Spawn an engineer (temp energy being)
        local position = self:GetPosition()
        local spiritUnit = CreateUnitHPR('XSL0402', self:GetArmy(), position[1], position[2], position[3], 0, 0, 0)
        
        # Create effects for spawning of energy being
		for k, v in self.SpawnEffects do
			CreateAttachedEmitter(spiritUnit, -1, self:GetArmy(), v )
		end	
```
If you want to spawn the spiritUnit on reclaim, you have to clone the code to a OnReclaimed function or similar. (in every mod/unit that's using the spirit)
Or like speed2CZ said, [CTRL]+[K] it. :)

**Comment by HUSSAR-mtrela** [comment]
I think we should leave it as is and just add speed2CZ tip about [CTRL]+[K] to a gameplay guide so that other players know how to deal with Ythotha being reclaimed by opponents.

**Comment by aeoncleanse** [comment]
Not our decision, this is up to Zock as balance councillor.

**Comment by HUSSAR-mtrela** [comment]
I was just trying to influence Zock's decisions by raising my opinion on this "bug" :)

**Comment by Bra1nwash3d** [comment]
imo it should definitely not spawn the lightning ball when own units are reclaiming this unit (to allow reclaiming pretty much dead ones to get mass back, without inconveniences). i doubt it's possible/feasible to check who actually reclaimed, so i suggest to keep this "feature" as long as the ythota does not have a switch whether to spawn a ball or not

**Comment by aeoncleanse** [comment]
3bb99dec24eb1ec7d056f006037964d0e042b07b Fixed in balance/3655

**Comment by Uveso** [comment]
fixed, please close.
