### ISSUE TITLE
"Shield dome toggle" for mixed active/disabled shields

### ISSUE THREAD

**Issue by bartvh87** [FAForever/fa#1262]
Select multiple shield buildings (any faction / tech level) including both active and disabled shields, then use the [Shield dome toggle] button in the UI, or hotkey such as [Toggle all abilities]. All shields will be disabled.

This is undesirable because a second toggle action requires the shields to slowly recharge, while e.g. a fire base may have been suddenly exposed. If toggle actions attempted to activate every shield, this would be avoided, and disabling shields would still be practical by using toggle twice.

Cheers,
Zappa

**Comment by duk3luk3** [comment]
Please check out #1267, does that work?

**Comment by aeoncleanse** [comment]
ca1736e9a0b9ab86ec1826884cd703ff07fc8adb
