### ISSUE TITLE
ladder match scoring bug

### ISSUE THREAD

**Issue by duk3luk3** [FAForever/fa#1263]
Server logs: https://gist.githubusercontent.com/duk3luk3/fed79035c6a75fe4c16eeffb25ccc4ad/raw/08609cc2de3e4bb24bca0d1bcb014bdcb1fa6ecd/gistfile1.txt

There is obviously quite a bit of screwiness going on. Army IDs are mixed up.

~~I think this is happening: [Commit accef017 in the server code](https://github.com/FAForever/server/commit/accef017) changed army IDs to 2/3 instead of 1/2 but client isn't reporting them that way.~~

EDIT: Or rather, Army IDs are default to 2/3 but client isn't updating them as it should...

**Comment by Sheeo** [comment]
87ce384f77a9b3d83d2f5c6cbe1c60029116ac1d addresses and most likely fixes this. Needs verification.

**Comment by Sheeo** [comment]
Fixed.
