### ISSUE TITLE
ACU OCing while building

### ISSUE THREAD

**Issue by speed2CZ** [FAForever/fa#1266]
content.faforever.com/faf/vault/replay_vault/replay.php?id=4748337

min 14:30 my ACU is building factory and OCing at the same time AutoOC enabled

**Comment by aeoncleanse** [comment]
Grrrrr. I ruddy fixed this!!!!

**Comment by aeoncleanse** [comment]
https://github.com/FAForever/fa/commit/0e62c07cab025a170a87275afde864ee49c0406b

Seriously, how the heck did it get past that?!

**Comment by Crotalus** [comment]
Hmm, the "control flow" of which weapon / buildarm to enable / disable seems a bit broken, when overcharge weapon is disabled it assumes it can enable the normal weapon which isn't the case if the ACU is building.

Best would probably to move the enable / disabling of weapon to the unit code instead, it's the parent who knows the state of itself best.

**Comment by aeoncleanse** [comment]
Yeah, while working on Blackops I was forced to come up with a method of properly locking all weaponry while building. We should probably use that here too.

**Comment by aeoncleanse** [comment]
@Crotalus that comment above would explain normal fire while building, but not OC fire.

**Comment by aeoncleanse** [comment]
https://github.com/FAForever/fa/pull/1527
