### ISSUE TITLE
bug chrono dampner

### ISSUE THREAD

**Issue by shalkya** [FAForever/fa#1271]
game is 4755438

https://gist.github.com/shalkya/e318cc53baa8c23b5b4bdcf85a6664c8

it is running on the balance patch, but we didn't change anything to chrono dampner.
1st chrono fired, then no more.

**Comment by aeoncleanse** [comment]
Hmmm...  I tested chrono in 3654 and with blackops, working fine both times...

**Comment by shalkya** [comment]
yes i did sandbox too and couldn't replicate..
but i still wanted to post the bug.

**Comment by shalkya** [comment]
OK i found the bug. OC messed up with the chrono dampner.
(reset of count down at each OC ?)

https://gist.github.com/shalkya/3b80265725db390bf8084a26de7cf353
4755513

test done in normal faf.

**Comment by aeoncleanse** [comment]
I'll look closer another time, but I do know that OC temporarily disables all other weapons, which would indeed disrupt chrono fire.

**Comment by aeoncleanse** [comment]
Hmm. Upon inspection, OC only disables the primary gun...

**Comment by aeoncleanse** [comment]
Logging confirms that OC messes with the chrono sequence for some reason :/
