### ISSUE TITLE
put back the slot highlighting from all those years ago!

### ISSUE THREAD

**Issue by Exotic-Retard** [FAForever/fa#1286]
when you mouse over a slot it highlights the map spot but not the other way around.
put that functionality back. how do i know it was there before?
1. my amazing memory
2. http://puu.sh/oVy0z/bf6c77f756.jpg it works in 3599

should be kinda simple i guesssssssss but dunno with code its always hard to tell xD

**Comment by Crotalus** [comment]
Seems like b5f4bb9ebbc835345d81f837127d3e9e68209c75 broke it, I'll take a look

**Comment by Crotalus** [comment]
:wrench:
