### ISSUE TITLE
move order split

### ISSUE THREAD

**Issue by shalkya** [FAForever/fa#1289]
some strange behavior :
1- if you give a move order to 2 units (for exemple). then drag the move order. then press g. There will be 2 move order to the FIRST emplacement

2- give 2 move order (A to B, then B to C). press g. wait for unit to reach C. press g again. Units will have their own move order : C to B, then B to C

3- give 2 move order (A to B, then B to C). press g. press g again between B to C (while unit are still in movement). unit will comeback to B then go to C again.

http://forums.faforever.com/viewtopic.php?f=2&t=9713 (replay is attached, test to actual beta, and same thing happening)

**Comment by CodingSquirrel** [comment]
Same issue as #1177

**Comment by aeoncleanse** [comment]
Closed because duplicate
