### ISSUE TITLE
GPGNet TeamkillReport: include player's ids

### ISSUE THREAD

**Issue by Brutus5000** [FAForever/fa#1291]
After a quick talk with sheeo we would like to have the GPGNetSend for Teamkill enriched with the teamkiller's and the victim's player id (id from the server).
Nicknames shall be kept for debug reasons when looking into logs.

`GpgNetSend('TeamkillReport', killTime, victimId, victimName, killerId, killerName)`
[original call here (line 59)](https://github.com/FAForever/fa/blob/develop/lua/ui/dialogs/teamkill.lua)

This makes server handling far easier.

Unfortunately I have no idea how to catch the player-ids.

**Comment by Crotalus** [comment]
Take a look at #1291
