### ISSUE TITLE
uea0203(Stinger) is missing Categories.TRANSPORTFOCUS and Categories.uea0203

### ISSUE THREAD

**Issue by Uveso** [FAForever/fa#1292]
Every Transport unit has category TRANSPORTATION and category TRANSPORTFOCUS. But the Stinger is missing TRANSPORTFOCUS. 
So there is no Transport-Icon, if the mouse is hovering over a unit while the stinger is selected.
Maybe intentional ?

And there is a EntityCategoryContains() command with "categories.TRANSPORTATION - categories.uea0203" parameter inside "aiutilities.lua.GetTransports()" function.
```LUA
[...]
        if not unit.Dead and EntityCategoryContains( categories.TRANSPORTATION - categories.uea0203, unit ) and not unit:IsUnitState('Busy') and not unit:IsUnitState('TransportLoading') and table.getn(unit:GetCargo()) < 1 and unit:GetFractionComplete() == 1 then
[...]
```
But this won't work, because unit uea0203 don't has the Category "uea0203". Without this the AI is using the stinger as normal Transporter.
I dont know, maybe the Category was removed by mistake ?

**Comment by Uveso** [comment]
Just i case someone is adding the TRANSPORTFOCUS then the General.SelectionPriority inside unit uea0203 should be changed from "1" to "2".

**Comment by Crotalus** [comment]
I guess it doesn't have TRANSPORTFOCUS due to "colliding" with assist but on the other hand, how often do you want it to assist really. So probably a good idea to add that category.

The `categories.uea0203` check will work though, all units automatically get their blueprint id as a category.

**Comment by Uveso** [comment]
Assist will still work if u klick the assist button or pressing "i". But without the Transport icon no one knows, that the stinger can transport units. Shame on me, i didnt know it until know :) 

And you are right. I testet the categories with this:
```LUA
		if unit:GetBlueprint().BlueprintId == 'uea0203' then
			LOG('Found Unit uea0203')
			if EntityCategoryContains( categories.uea0203, unit ) then
				LOG('categories.uea0203 == true')
			else
				LOG('categories.uea0203 == false')
			end
			LOG('categories Array:', repr(unit:GetBlueprint().Categories),'')
		end
```
and here the result:
```
INFO: Found Unit uea0203
INFO: categories.uea0203 == true
INFO: categories Array:\000{
INFO:   "PRODUCTSC1",
INFO:   "SELECTABLE",
INFO:   "BUILTBYTIER2FACTORY",
INFO:   "BUILTBYTIER3FACTORY",
INFO:   "UEF",
INFO:   "MOBILE",
INFO:   "AIR",
INFO:   "TECH2",
INFO:   "GROUNDATTACK",
INFO:   "TRANSPORTATION",
INFO:   "VISIBLETORECON",
INFO:   "RECLAIMABLE",
INFO:   "OVERLAYDIRECTFIRE",
INFO:   "SORTOTHER"
INFO: }\000
```
EntityCategoryContains( categories.uea0203, unit ) is true, but if i take a look inside the Blueprint, there is no uea0203 inside categories.

But as you said, the check will work :)

**Comment by Uveso** [comment]
If i understand this right;
The patch is already gone live, so i can close this issue, right ?

**Comment by aeoncleanse** [comment]
Not live, but yes it's been merged with develop. :)
