### ISSUE TITLE
AI sometimes doesn't die

### ISSUE THREAD

**Issue by aeoncleanse** [FAForever/fa#1294]
http://forums.faforever.com/viewtopic.php?f=3&t=12470

**Comment by Uveso** [comment]
Verified.
I wrote a simplified explanation in the forum.
A not ending game is mostly a aftereffect from a "Game object has been destroyed" Error, if you are using the "Assassination"  victory setting.

If this occours you can see a dead unit on the Map that don't has a wreck.
Console Commands like "Destroyall" or "Killall" dont work here to delete the last unit.

**Comment by Uveso** [comment]
I'ts merged into develop. Do we close this then ?

**Comment by Crotalus** [comment]
Yeah, good work!
