### ISSUE TITLE
PDs and AA Tower get adjacency from pgs

### ISSUE THREAD

**Issue by Zockyzock** [FAForever/fa#1306]
PGs increase rate of fire. Confirmed for t1 pd, t2 PD, t1 AA and SAM 

This must be a fairly new and undocumented change. When did this happen?

**Comment by Nojoke185** [comment]
could it be linked to issue 1185?

**Comment by Crotalus** [comment]
Regression when cleaning up the adjacency code here 49fa472d46c2d5611c0cee892a4e5ae827aafa59

**Comment by Exotic-Retard** [comment]
if im understanding this correctly, does that mean that t2 artillery (size 1 structure) adjacency doesnt work anymore? if so, it should : |

**Comment by aeoncleanse** [comment]
Arty does. PD, Flak etc don't.
