### ISSUE TITLE
subs issue

### ISSUE THREAD

**Issue by shalkya** [FAForever/fa#1312]
when i check a replay last time i saw 2 bugs : 
- sub nuke bone structure must be broken (torpedo has difficulty to kill them) https://youtu.be/Lr7oVHhAoUs?t=40m32s
- T2 subs prefers to kill engie than torpedo defense. Leading to 8 T2 subs dying to a single T2 torp def because of a move order (when attack move on torpedo defense should be use) https://youtu.be/Lr7oVHhAoUs?t=37m08s then you can watch on his mini map until 37m50 (at bottom of the map)

**Comment by Uveso** [comment]
Solved, please close.

**Comment by Uveso** [comment]
I am sorry, but we have to reopen this.
I tested it and its not solved :(

Torpedos passing the target and are cycling around it without hitting:
![suptar1](https://cloud.githubusercontent.com/assets/17804547/17751407/404a2794-64c7-11e6-8cbb-df5be125f332.png)

And Torpedo is hitting land before it can reach the target (engineer problem):
![suptar2](https://cloud.githubusercontent.com/assets/17804547/17751481/982f0f56-64c7-11e6-91cb-1ee7621e84d1.png)

Torpedo-spheres and sub-hitbox are colliding, but no hit is detected. So this need further investigation.

**Comment by aeoncleanse** [comment]
Can you check if there are any bones below the water surface? I bet there aren't.

**Comment by Uveso** [comment]
Your bet is right, this is the problem with the engineer, Layer says its in water, but all bones are over the water surface. It's more a map design issue, nothing we can do in lua, right ?

**Comment by aeoncleanse** [comment]
No. Needs a new model.

**Comment by Uveso** [comment]
Well, if i see the picture, the torpedo shouldn have fired at this target in fist place.
Torpedo is hitting the ground, before it can reach the target. 
The water is simply not deep enough for a torpedo.
Even if the game says, that the engineer is in water, its more like weet ground then deep water.
So the torpedo can't reach the target without learning to fly over the water.

But how can we prevent the targeting of the engineer in this case ? Is choosing the target inside lua or game.exe ?

**Comment by aeoncleanse** [comment]
We can't. Only thing to do is introduce a submerged bone that the torp can hit, and perhaps lower the hitbox a little.

**Comment by Uveso** [comment]
A submerged bone wont help here, the torpedo explodes before he can reach the target.
It not good to see, but the torpedo hit the ground here:
![suptar2b](https://cloud.githubusercontent.com/assets/17804547/17775299/e8a3bbe0-6557-11e6-95d2-18e2a27ee4fb.png)

**Comment by aeoncleanse** [comment]
There are more situations than this. In this case, I don't think anything can be done.

**Comment by shalkya** [comment]
What about making subs and torpedo launcher priorities over engie for subs ? doesn't solve the issue overall, but allow situation like this to not happen again.

And what about making subs change target when hitting ground faster ? also not the best solution...

**Comment by Uveso** [comment]
These are the targetpriorities of the xrs0204 (barracuda cybran tech2) Sub:
```LUA
            TargetPriorities = {
                'SPECIALHIGHPRI',
                'MOBILE',
                'STRUCTURE DEFENSE',
                'SPECIALLOWPRI',
                'ALLUNITS',
            },
MOBILE = Engineer and all naval and amphibic Units.
STRUCTURE DEFENSE = Torpedo defense.
```

So what happened with the engineer will also happen to all mobile units with amphibian abilities.
And changing the priority will affect also naval units like enemy subs. You wont ignore them until the defense is down.

**Comment by shalkya** [comment]
well this can be link to the issue that your sub prioritize a frigate, and then an opponent sub come into range, you sub will still fire at the frigate. Maybe some change in priorities is needed for all subs... (to fix this issue and the one i just said)

**Comment by aeoncleanse** [comment]
Changes are needed to ALL priorities really, but nobody has the time to go through so many changes
