### ISSUE TITLE
Cybran ACU starts walking while assisting mex

### ISSUE THREAD

**Issue by Totaltuna** [FAForever/fa#1318]
Cybran ACU starts walking when you tell it to assist a mex, not sure if it's exclusive to cybran but only had it happen with cybran ACU

**Comment by Justify87** [comment]
It also starts walking while assisting a shield upgrade. 
There is also a bug with a successfull assistance on a shield upgrade. If I cue more than one upgrade the acus progress bar remains full when the second upgrade starts. Mass and energy ist used but the upgrade doesn't get faster.

**Comment by aeoncleanse** [comment]
Duplicate of #1256
