### ISSUE TITLE
Sera sniper incorrect attack move behaviour

### ISSUE THREAD

**Issue by JaggedAppliance** [FAForever/fa#1319]
Sera snipers in sniper mode do not stop walking when attack move is used, they just continue walking towards the enemy rather than stopping when they get into range of an enemy. Attack move works correctly when they are in their default mode.

**Comment by aeoncleanse** [comment]
It's because the primary weapon is disabled. There is no fix currently, but I have a _potential_ method of addressing this with a bit of a hack currently being tested in BlackOps with the Aeon ACU...

**Comment by Exotic-Retard** [comment]
is it using a dummy weapon to be primary? : D
can confirm this method works on mobile shields at least

**Comment by aeoncleanse** [comment]
It miiiiiiigggghhhhttt be :)
