### ISSUE TITLE
Implement Self Destruct confirmation

### ISSUE THREAD

**Issue by speed2CZ** [FAForever/fa#1341]
Discussion here: http://forums.faforever.com/viewtopic.php?f=42&t=12537

Mod that does this is called Suicide Confirmation V3

Would be nice to have this optional. Enable/disable in options.

**Comment by zlo-faf** [comment]
If somebody ever do this: make sure it only asks for confirmation when you ctrl+k ACU or transport with ACU, and NOT ask about every little thing that you ctrl+k
Alternatively/addictionaly make it toggleable to ask for confirmation  of every ctrl+k/instant ctrl+k

**Comment by speed2CZ** [comment]
Enabled / enabled only for ACU / disabled

**Comment by robotcatt** [comment]
Quite often I see “unsuccessful” rebuild of mex on streams.
i cant find confirmation options instant ctrl+k for ACU (is it still in game ?) 
can we implement the mod
name = "ACU Self Destruct Confirm"
uid = "30f147ac-c422-4f97-92db-799596e3ea02"
if work fine.
