### ISSUE TITLE
Can't resize chat window

### ISSUE THREAD

**Issue by JaggedAppliance** [FAForever/fa#1345]
As the title states. The chat borders don't react at all when i mouse over them.

**Comment by Uveso** [comment]
Tested it with newes version here from github, and its working fine here.
I now there was a bug, but seems to be fixed.

**Comment by aeoncleanse** [comment]
Which chat window?

**Comment by speed2CZ** [comment]
@icecreamer afaik there is only one chat window in the game

**Comment by Uveso** [comment]
Well, i was testing the ingame chat, while playing.
This was the only "resizeable" chat window i know.
I hope, this was right!

**Comment by JaggedAppliance** [comment]
So I've realised that this is solved by changing the ui skin using alt+right as with the other ui bug where the whole ui looks messed up. In this case only resizing the chat window was a problem so i didn't think to change the skin initially.
