### ISSUE TITLE
Option are greyed out and unavailable for the host, if host is an observer and opens&closes the options dialog

### ISSUE THREAD

**Issue by Justify87** [FAForever/fa#1346]
1. host a game
2. make yourself an observer
3. open the options dailog
4. close the dialog
5. ability to change the game options is not available anymore for the host

**Comment by Justify87** [comment]
GetPlayersNotReady() doesn't return any players, if all slots are empty. So the system thinks the game is ready to launch. I added an if clause that checks if host is an observer.

**Comment by aeoncleanse** [comment]
88f470e732bcf68443434e4e4ae02e2f5f0c43fc
