### ISSUE TITLE
Rating label on map preview, error when switching maps

### ISSUE THREAD

**Issue by Justify87** [FAForever/fa#1347]
@aeoncleanse 
I didn't know where to put it, so I put it here.

On the ice branch
if someone changes the map there appears to be an error with this line:
https://github.com/FAForever/fa/blob/develop/lua/ui/lobby/lobby.lua#L959
" attempt to call method `Hide' (a nil value)"

EDIT:
It appears if you switch between maps that have different number of players

**Comment by aeoncleanse** [comment]
It's because that line assumes slotlabel cannot be nil, which it will be in the case of, for example, a player in slot 3 or 4 of a 4 slot map changing to a 2 slot map. This can be fixed with a simple if clause.
