### ISSUE TITLE
When the host is switching a player that is ready, a warning appears in the log and the loop to set player option is exited early

### ISSUE THREAD

**Issue by Justify87** [FAForever/fa#1348]
"WARNING: Attempt to set option on unowned slot."

This is a bug present in the current release.
https://github.com/FAForever/fa/blob/master/lua/ui/lobby/lobby.lua#L3529

SenderID and HostID are not equal.
SenderID = 1
HostID = 0
in my case

SenderID always seems to be 1 and is not changeable(?)
I tried to set/add it here, but failed:
https://github.com/FAForever/fa/blob/master/lua/ui/lobby/lobby.lua#L3936

Not sure what to do next.

**Comment by Justify87** [comment]
I misinterpreted that. Seems like a second broadcast gets triggered in the non-host players, after receiving a broadcast from the host to change the player options  (e.g. move a player to a different slot). Not sure where, yet.

**Comment by Garanas** [comment]
Issue is stale - I think the lobby works fine at the moment.
