### ISSUE TITLE
Sending a private message in the lobby with the slot dropdown menu makes the slot highlight get stuck

### ISSUE THREAD

**Issue by ChrisKitching** [FAForever/fa#1349]
The blue circle around the ACUButton on the map preview remains active until you mouse-over it again.

STR:

Enter lobby.
Click the dropdown on another player and select "Private message"

The map preview now has a pulsing blue highlight on that player, even though your mouse is not on them. It stays until you mouse over that player again.

**Comment by aeoncleanse** [comment]
@Justify87 think you can look at this?

**Comment by Justify87** [comment]
The problem is: exiting the dropdown menu of the slot to the site where the scrollbar is, doesn't trigger the MouseExit behaviour.

**Comment by Justify87** [comment]
This is a mess. There are multiple issue with the mouse events. The first time leaving the dropdown menu doesn't trigger the MouseExit even, the second time does.
MouseEvents get triggered multiple times, when moving over the top entry and top border of the dropdown menu.

**Comment by Justify87** [comment]
No event is recognized when clicking on any of the options in the drop down menu. ButtonPress or Release get recognized on opening the slot menu only. ButtonRelease gets triggered twice though.

So we can't do: OnButtonPress = Indicator.Stop() or something like that

**Comment by Justify87** [comment]
This will get it working when clicking on something in the dop down menu, doesn't solve the issue with the scrollbar, though. I think the scrollbar is handeld in the Group Class (?)

https://github.com/FAForever/fa/blob/develop/lua/ui/lobby/lobby.lua#L2124
```
        nameLabel.OnClick = function(self, index, text)
            DoSlotBehavior(curRow, self.slotKeys[index], text)
            local associatedMarker = GUI.mapView.startPositions[curRow]
            associatedMarker.indicator:Stop()
        end
```

Also: confusing naming of a combo (nameLabel). Wasted time thinking it is just the title of a column of the table of players.

@aeoncleanse will you add that to the ice branch?

**Comment by aeoncleanse** [comment]
I took a look. The best way to do this IMO is to make it drop the indicator in OnHide(), but for some reason hooking into that has proven troublesome.
