### ISSUE TITLE
I think non-factory structure wrecks should sink in water

### ISSUE THREAD

**Issue by aeoncleanse** [FAForever/fa#1353]
Title. Currently they don't.

**Comment by Uveso** [comment]
Oh yes, i like the idea.
Actually i am working on xtremewars, and there are many waterstructures.
Would be verry nice to see them sink :)

**Comment by speed2CZ** [comment]
that would make them harder or pretty much impossible to rebuild

**Comment by aeoncleanse** [comment]
Oh yeah. Damn. That's irritating :(

**Comment by JaggedAppliance** [comment]
Maybe I'm crazy but i thought at least torp launchers used to sink. And yes they were really difficult to rebuild. They also took really long to sink which was very annoying at times.

**Comment by aeoncleanse** [comment]
Yeah this was a dumb idea. Closing.
