### ISSUE TITLE
Engineer assist bug

### ISSUE THREAD

**Issue by speed2CZ** [FAForever/fa#1354]
When building with ACU and engie is set to assist the ACU, if you click on the assist order the engie will start new building on the place where ACU is standing instetad of assisting the one ACU is building.

Short video of it: https://youtu.be/0zgYErpTaiA

It's a regression since I was always using this to refresh order in case when engineer was out of range, if I clicked on the assist order when engie got just in range of being able to build, it started to build instead of going all the way close to the building that ACU was building.

**Comment by Crotalus** [comment]
Regression since when? Tried to drag-move assist order like you did in video with 3603 and it still acted the same way, ACU moved aside and engineer started to build :)

**Comment by speed2CZ** [comment]
I've been using this my whole FAF carrer to make engie assist faster... I blame one of the last patches.

**Comment by aeoncleanse** [comment]
This has been checked by myself and NoJoke on 3603 and 3599. This behaviour has always been the case.
