### ISSUE TITLE
What happened with spread attack on buildings etc?

### ISSUE THREAD

**Issue by aeoncleanse** [FAForever/fa#1355]
There's been some renewed interest about this, someone trying to make a mod. I told him I thought it was main game, checked for him, and found that it had been committed then reverted. Can anyone remember why? https://github.com/FAForever/fa/commit/e9fb03b6f1558235334bb114a763109771021532

http://forums.faforever.com/viewtopic.php?f=42&t=12567

**Comment by micheljung** [comment]
Maybe @Crotalus ?

**Comment by MrRowey** [comment]
@Garanas Can be Closed Spread Attack is Intergraded in faf
