### ISSUE TITLE
I can't easily select all support commanders if I built them with presets from the quantum gate

### ISSUE THREAD

**Issue by Justify87** [FAForever/fa#1357]
They seem to be different units. When I build a standard SCU and upgrade them manually, I can select all of them at once. 

Played as cybran, not sure if this happens with the other factions as well.

**Comment by aeoncleanse** [comment]
Yup, this is a thing. They are separate units.

**Comment by Uveso** [comment]
I have the same problem sometimes, and i use the following workaround:

Select the quantumgate and press [CTRL]+[1].

If you now build some SubCommander with different Upgrades, you can simply select them all by pressing [1].

**Comment by Justify87** [comment]
Yes, I used that too. But I think this feature also has a problem. Because, as soon as I realized that I can't select them all, I assigned group 1 to the quantum gate, but none of newly produced SCU would be assinged to the gate. Pressing 1 just centered the view on the gate. I also can't add any existing SCU to the group.

**Comment by aeoncleanse** [comment]
I've advocated for a new way of doing SCU upgrades for a long, long time.

**Comment by Uveso** [comment]
Just select the quantum gate first (and only the quantum gate) and press [CTRL]+[1].
All new build subcoms will be in group 1. then.

@aeoncleanse 
Yeah, why not just build a "normal" subcommander and activate the necessary enhancement.
Maybe someone with excellent ACU knowledge can do this :))))))))

**Comment by Justify87** [comment]
I did that, it did not work.

**Comment by Uveso** [comment]
Well tested it with gameversion 3599, 3652 (only one subcom type) and development version.
Quantumgates and normal factories are working like this.

Could you try to build a landfactory, select it and press [CTRL] + [1].
The landfactory should show the number "1" now. and if you press the [1] on the keyboard, the factory should be selected.

Now build some units and press againn [1]. Now all builded units (not the factory) should be selected.

Quantumgate should have the same function.

**Comment by Justify87** [comment]
I guess the problem was/is, that the SCU already under construction doesn't get that group number assigned. The one after that one does. I just tested it. It takes a long time for rambo SCU to be produced and my quantum gate got destroyed during production of the second one.

**Comment by aeoncleanse** [comment]
Yup
We need a new way of doing scu presets, completely.

**Comment by Justify87** [comment]
I would add to that, that SCU presets don't get used often. Mostly just the RAS preset or something like that. In 400 games I played, I've rarely seen any combat SCU.

**Comment by aeoncleanse** [comment]
Lol. Combat SCU is by far the most common I've seen, especially UEF and Sera.

**Comment by Uveso** [comment]
@Justify87 
Yes you are right, the groupnumber is assigned on buildstart.
@aeoncleanse 
On the other side, its working for now. So maybe only a "nice to have" in my eyes.

**Comment by zlo-faf** [comment]
1)after nerf ras scus used alot more often compared to combat
2)why need new way of doing scu presets?
It is cool that I can select different presets separately by just double click...not sure if I ever need to use select all scus. I could select all combat or all non combat.
If somebody need to have way to select all scus then assigning gateway to controll group seems good idea, hope it will work.. or create a custom hotkey

**Comment by Uveso** [comment]
Using the "normal" SCU upgrade methode, instead of using diiferent units has some benefits.
1. less memory usage.
2. better AI handling
3. faster scrip execution

Or in one word: Optimized.

**Comment by HUSSAR-mtrela** [comment]
I completely agree with @zlo-faf and I think we can close this "issue"

**Comment by speed2CZ** [comment]
I agree
