### ISSUE TITLE
Suggestion: Autoboot dead players when connection issue arrise.

### ISSUE THREAD

**Issue by Androish** [FAForever/fa#1358]
http://i.imgur.com/lsjfswi.png

Problem(senario): Sometimes only 2 players loose connection to each other in a game, If one of them is a dead afk player the game will stop until one can get a mod to kick. or the alive player disconnects. Same applies if the Dead player is a douche and won't leave.

Is it possible to code in an autoboot from the game of the Dead player in that case? Maybe just autoboot any dead player whenever there is a connection issue in the game at all. I know it would suck to be booted from the game beacuse of it but the players that are alive should take precedence.

**Comment by Justify87** [comment]
I guess it could be possible to give the timer a auto eject function after 4-5 minutes or something like that. It should also be possible to change the timer for the eject button from 50 seconds to 2 minutes, because that is how long people wait before kicking anyway.

**Comment by MrRowey** [comment]
Already a Autoboot playes
