### ISSUE TITLE
sera t2 bot ilshavoh has minimum range

### ISSUE THREAD

**Issue by Exotic-Retard** [FAForever/fa#1359]
it cant shoot targets right next to it.
http://puu.sh/ptJR2/16c7621e03.jpg
it can be fixed pretty easy.
1. in blueprint: TurretPitchRange = 90,  --from 60
2. in unit script put in SetupTurret function from weapon.lua and put:
self.AimRight:SetFiringArc(turretyawmin/6, turretyawmax/6, turretyawspeed, turretpitchmin, turretpitchmax, turretpitchspeed)
for both AimRight and AimLeft, replacing the original lines.

i didnt make a pr because the way i was gonna do it would give IceCreamer extreme <s>cancer</s> disappointing
should look like this after its done: http://puu.sh/ptILa/ce98373791.jpg
enjoy.
# BalanceTerrorism #FixedInEquilbrium #BlameSock

**Comment by speed2CZ** [comment]
Since no one is complaining about it, we let @Zockyzock decide if he want this "fixed"

**Comment by aeoncleanse** [comment]
Yeah this is probably fine. @Exotic-Retard PR plz :p

**Comment by Zockyzock** [comment]
no need

**Comment by aeoncleanse** [comment]
No need? Please elaborate.

**Comment by aeoncleanse** [comment]
Closing at request of Jagged
