### ISSUE TITLE
Queued SCU starts at 50% after rebuild of Quantum Gate

### ISSUE THREAD

**Issue by Justify87** [FAForever/fa#1366]
Not sure if this is true for presets only.
I was playing as cybran

1. Build a quantum gate
2. Build RAS SCU preset
3. Quantum gate got destroyed during build of SCU
4. Rebuild quantum gate on top of wreck
5. Queue RAS SCUs
6. Build will start at a discounted price of 50% mass and energy. ^^

There is actually a wreck of the SCU standing in the quantum gate. I guess this is the reason it gets the 50% bonus. All following SCUs will also start at 50% as long as the wreck remains in the quantum gate.

![before build](https://cloud.githubusercontent.com/assets/10554299/16286204/407b77ee-38db-11e6-9a09-3401e0abdc7c.jpg)

![after build](https://cloud.githubusercontent.com/assets/10554299/16286218/5629320c-38db-11e6-92b7-27c9ff3d8b97.jpg)

Replay ID: 4863652
(Water of isis)

**Comment by Uveso** [comment]
I tried to reproduce the error, but i failed.

I can create the wreck of the Qgate and SACU, but if i rebuild the Qgate, the SACU will be reclaimed before the rebuild of the Qgate starts.

**Comment by Justify87** [comment]
I rebuild it with my commander, not sure if this matters.

**Comment by Crotalus** [comment]
To replicate:
* Make sure building unit > 50% done
* Kill gw / factory (not with insta-ctrl-k though because it kills the unit in progress as well)
* Rebuild at same spot
* Start same type of unit in factory

You get progress of newly built unit for free

**Comment by Uveso** [comment]
@Crotalus 
Thanks, now i got it.
