### ISSUE TITLE
Auto-overcharge sometimes doesn't start firing

### ISSUE THREAD

**Issue by Justify87** [FAForever/fa#1369]
I can't say for sure what stops the auto-overcharge from doing its thing. All I know is, that after it was in use in a fight and I don't fight for a while after (5-10mins), if I get into a fight again, it won't start firing unless I disable it and reenable it again.

I had a e-storage and enough energy.

**Comment by Justify87** [comment]
It also fires at the unit that is nearby instead the one that the ACU/SACU is aiming & firing at

**Comment by speed2CZ** [comment]
Replays and logs would be usefull

**Comment by Justify87** [comment]
About that bug, where Auto-OC fires at random units instead of the target that the ACU is firing at. It's the only recent replay I could find: 5052012
Right at the end, when I kill FastPlanet my ACU is standing right next to his com, but it still fires an OC at something else far away.


About auto-OC not firing despite being enabled:
I have read somewhere that this happens, when one does an ACU upgrade while auto OC is still enabled. After the upgrade you need to disable and enable auto-OC again. Maybe @Crotalus can shed some light on this?

I haven't followed up on this issue. I'll try to have an eye on it in my games.

**Comment by aeoncleanse** [comment]
d8d35c71958ebc0eacbcfb312aabdb3b267e4ad3
