### ISSUE TITLE
Unit stats are populated with destroyed units

### ISSUE THREAD

**Issue by HUSSAR-mtrela** [FAForever/fa#1377]
Unit stats ( ArmyScore[index].units[unitId] ) are populated with info about destroyed units (wreckage that are placed on some maps, e.g. middle of Seton) when the game is loading. In other words, all players should have zeros for unit stats after the game finished loading a map but that is not the case for some players in the score data.
this issue is related to issue #1363

Proposed Fix:
Add a boolean that will prevent updating unit stats until a map is fully loaded and unit wreckages are placed on the map.

**Comment by micheljung** [comment]
To which army do such wrecks belong to?

**Comment by aeoncleanse** [comment]
Should be civ or civ army. But if they are interfering, army 1? All armies? Ot could this have been a side effect of that table being initiated outside of the class?

**Comment by micheljung** [comment]
oooh yes, of course. When everybody shared the same unit stats, they also shared the stats with the civ army :-) I'll close this then. Please reopen if it should still be a thing.
