### ISSUE TITLE
Unknow ACCESS_VIOLATION (for Stuntaneous)

### ISSUE THREAD

**Issue by Uveso** [FAForever/fa#1381]
http://pastebin.com/7AE6E99Z
http://pastebin.com/6RLUFqvu
@Stuntaneous
Can you post your full game log after gamecrash?
Your log is located in:
`C:\ProgramData\FAForever\logs\game.log`

**Comment by Stuntaneous** [comment]
Yep, here it is:
http://pastebin.com/3bxChrCG

**Comment by Uveso** [comment]
ok, gamelog shows some errors inside the soundbank, this should not be the case.
(I guess you did already checked the gamefiles with steam? if not, do it now!)

Please try to start the game without sound and see if it still crash.

Make a desktop-shortcut from the file:
```
C:\ProgramData\FAForever\bin\ForgedAlliance.exe
```
(Rightclick the file and select "Send to" -> Desktop Shortcut")

Open the shortcut and change the Command line (target):
from:
```
C:\ProgramData\FAForever\bin\ForgedAlliance.exe
```
to:
```
C:\ProgramData\FAForever\bin\ForgedAlliance.exe /init init_faf /nosound
```
Now start and test the game without sound.

**Comment by Stuntaneous** [comment]
Yep, Steam successfully verified the files between the two games. 

Instant crash:
http://pastebin.com/WuvqQsnT

"init_faf.lua" is there and can be read. I just made a copy of it sans file extension and it ran this time.

**Comment by Stuntaneous** [comment]
Same conditions as the second crash log, no problems after 35 minutes. Awkwardly I've managed to lose.. I'm going to claim the lack of sound as an excuse, haha. I'll give it another whirl.

**Comment by Stuntaneous** [comment]
Went for an hour and no crash. But, I was having an intermittent stuttering issue. I don't think it was present in the previous game. Increasing in frequency, occasionally my music out of game would blur / stutter together for half a second or so and similar stuff happening in-game. I assume it's something to do with the Sorian AI. Years ago I was getting frustrated with the eventual slowdown associated with it and ended up having to play with small unit caps and the cheating variant of the AI to get the most out of them.

**Comment by Stuntaneous** [comment]
Interestingly, just tabbing back into the game which I left at 'game over' and the still scene of the map at that moment, I almost instantly had another stutter.

**Comment by Stuntaneous** [comment]
And yet there's more - on the same frozen map, I notice moving around the map when zoomed out, as the map scrolls over an area previously unseen, there's a half second delay to strategic icons appearing. It reminds of the 'unknown_icon' mentions, I think it was, in various logs.

**Comment by Uveso** [comment]
oops sorry, the command line should look like this:
`
C:\ProgramData\FAForever\bin\ForgedAlliance.exe /init init_faf.lua /nosound
`
Thats why he can't find "init_faf"...

Well, I play both AI's normal and sorian. Sorian is way faster in endgame.
Dont know what CPU you are using, an intel Quadcore with 2.5 GHz should manage about 1600 Units (825 you, and 825 for the AI)
An I7 cpu @ 4Ghz can handle about 2200 units.
This also depends on how fast is you memory. Your pc can handle about 200 units more if you are using DDR4 Ram instead of DDR3.

Ok back to the sound (ignore the stutter for a moment). If you run the game without sound, you dont crash and with sound you can't play a full game, right ?

**Comment by Uveso** [comment]
Well, i dont know it, but i guess this is solved because there is no new message since a week.
