### ISSUE TITLE
Tech 3 engineering suite does not have drones

### ISSUE THREAD

**Issue by sab24** [FAForever/fa#1387]
When building a UEF tech 3 Engineering suite no drones appear in version 3654. Logs show 

WARNING: Unit.OnStopBeingBuilt() Army 1 cannot create restricted unit: <LOC xea3204_desc>Engineering Drone 

The engineering drone XEA3204 is also not listed in the unit restrictions menu. Could this prevent the drones from spawning?

**Comment by aeoncleanse** [comment]
I take it you're talking about the T3 Engineering Station structure?

**Comment by sab24** [comment]
Yes, the T3 Engineering station, XEB0204 in the FAF units database.

**Comment by Uveso** [comment]
Hello sab24,
i tested XEB0204 right now, and its working.
Maybe you have set an unitrestriction inside the Unitmanager like "no air" or something else ?
Or you are playing on a map with scenario restrictions ?

**Comment by sab24** [comment]
Ah, yes. The maps restricts the air units. Sorry about that. Still I think the drones should not be considered air units but land units. Else Cybran is allowed to create engineering stations and UEF not with the same restrictions.

**Comment by aeoncleanse** [comment]
Fact of the matter is that Cybran and UEF do their engineering in different ways. It's part of factional diversity. Something to just bear in mind on a map with built-in restrictions. Really, this should be adjusted by the map author.
