### ISSUE TITLE
Vision radius represented incorrectly

### ISSUE THREAD

**Issue by JaggedAppliance** [FAForever/fa#1389]
This has been around forever, units which look as though they should be in vision radius are not seen. This can have a large impact on units with slow turret turning speeds especially. The vision radius shown ingame appears to be too large, I have also heard a theory from Zlo that it is a problem with vision refreshing too slowly so units can be in range before the game recognises this. Mostly though i am ignorant of the technical aspects of this issue and would like any info i can get. Here's a thread i posted a while ago on this topic.
http://forums.faforever.com/viewtopic.php?f=3&t=11215

**Comment by aeoncleanse** [comment]
It's the intel only refreshing every 5 ticks. AFAIK there's nothing at all we can do about it.

**Comment by CookieNoob** [comment]
@aeoncleanse put a label: enginebug and close as it's unfixable

**Comment by MrRowey** [comment]
@Garanas can have that new engine unfixable tag
