### ISSUE TITLE
Factory Build Queue Templates not  creatable

### ISSUE THREAD

**Issue by Rikaisupcom** [FAForever/fa#139]
Hi. IceDreamer sent me here to report this bug:
See this video documentation on the bug. Easy to reproduce: Just do what everyone tells you to do.
https://www.youtube.com/watch?v=Xg1m9CNhqVo
 Yes, I have gaz-ui's feature on, which enables this feature.
 Yes, I have tried just clicking the infinite build button.
 Yes, I have tried to pause/unpause it, or pause before queuing or after.
 Yes, I have tried the step by step guide in this thread: http://forums.faforever.com/forums//v...
 It failed at the "-You should now see the Save Template button"-Part

I had some chats with people on FAF about it. Sometimes they see the button and get a crash, when clicking it, and sometimes they don't see the button. I can't reproduce the crash, since I never had one, but what you see in the video is what I see each and every time. Nobody that I chatted with, was able to create a template.

**Comment by mankinskin** [comment]
Seems like it doesn't work anymore, even when paused the template doesn't create.

I tested it without mods in a t3 uef land factory with a t3 land unit queue.
