### ISSUE TITLE
Swapping player in the lobby also swaps their designated team with them, thus overriding the auto team setting

### ISSUE THREAD

**Issue by Justify87** [FAForever/fa#1403]
It doesn't matter how you swap them (via map preview or "move player to slot x"), the team will always move with the player to the new slot. Could be a result of the change in the player swapping function: #1376

**Comment by aeoncleanse** [comment]
Please check non-beta and see if move player to slot does this. I suspect it will.

**Comment by Justify87** [comment]
Just tested it. Works in non-beta.

**Comment by aeoncleanse** [comment]
Works meaning it's broken or not broken?

**Comment by Justify87** [comment]
It is not broken in non-beta

**Comment by Justify87** [comment]
In the old swapping function, temporary moving the player ot the observer list seems to have reset the players team.

**Comment by aeoncleanse** [comment]
Oh. Gonna have to deal with that then.
