### ISSUE TITLE
Rating on random spot

### ISSUE THREAD

**Issue by Crotalus** [FAForever/fa#1406]
Rating number is shown on minimap when using random spot

**Comment by aeoncleanse** [comment]
@HUSSAR-mtrela 

This bug is still intact. I'm moving it up in priority. Do you think you could look into this for me please?

**Comment by Justify87** [comment]
I have a fix. I just can't create a branch/PR for it because of issues with the github windows app or my repo.

**Comment by aeoncleanse** [comment]
3c071d0b9f7132cd3086d537e404dad42e48227a
