### ISSUE TITLE
Sometime GameOptions.Quality is saved as -1#INF in Game.Prefs which make it corrupt

### ISSUE THREAD

**Issue by JaggedAppliance** [FAForever/fa#1418]
When it loaded up it was in the minimum res, 1024. It was fullscreen even though i use windowed mode. It didn't have any of my ui mods active and I couldn't even use the ctrl+shift command to show reclaim.

[logs.zip](https://github.com/FAForever/fa/files/397944/logs.zip)

**Comment by JaggedAppliance** [comment]
I hosted a lobby and it had the "what's new in lobby" window. The window said it was patch 3636.

**Comment by Crotalus** [comment]
Seems like your Game.prefs got corrupted somehow and renamed to `Seems like your Game.prefs got corrupted somehow and renamed to `C:\Users\Admin\AppData\Local\Gas Powered Games\Supreme Commander Forged Alliance\Game.prefs.bad`. Could be interesting to see exactly what caused it, line 547 in that file, something with BuildMult.

```
Warning: Loading "C:\Users\Admin\AppData\Local\Gas Powered Games\Supreme Commander Forged Alliance\Game.prefs" failed: ...ata\Local\Gas Powered Games\Supreme Commander Forged Alliance\Game.prefs(561): `}' expected (to close `{' at line 547) near `BuildMult'
warning: Unable to load your preferences (corrupt or out-of-date file.)  Current file will be renamed: [C:\Users\Admin\AppData\Local\Gas Powered Games\Supreme Commander Forged Alliance\Game.prefs.bad]
warning: Can't open lua file "C:\ProgramData\FAForever\bin\..\Installed.Prefs"
warning: unable to load Installed.Prefs; using empty initial prefs
```

**Comment by JaggedAppliance** [comment]
[logs.zip](https://github.com/FAForever/fa/files/397968/logs.zip)
Here's the 2 gameprefs

**Comment by Crotalus** [comment]
Yikes, GameOptions table at line 547 contains among other things:
```
...
FogOfWar = 'explored',
Quality = -1.#IND,
BuildMult = '2.0',
...
```

Quality is undefined and that syntax is not correct lua `inf` or `nil` would have been better at least.

If you want your old settings just nuke that Quality line completely (line 560).

Lets keep this issue open to investigate why Quality was even saved in this state.

**Comment by JaggedAppliance** [comment]
Great, thanks for the help crotalus.

**Comment by speed2CZ** [comment]
I'll close this, another investigation can be done in #1468 as icedreamer asks
