### ISSUE TITLE
Game don't end in Assassination or Supremacy mode

### ISSUE THREAD

**Issue by Uveso** [FAForever/fa#1437]
Some errors who also can lead to "gamobject has been destroyed" are causing the game to not end, if all units are dead. (This is not only related to AI games)
http://forums.faforever.com/viewtopic.php?f=3&t=12470

**Comment by aeoncleanse** [comment]
I'm sure there's been an issue and fix for this in the past... I'd have to search the issue history to be sure.

**Comment by Uveso** [comment]
I was reading all issues, maybe i missed this. I'll look again.

**Comment by Uveso** [comment]
Here it is: `AI sometimes doesn't die` #1294
Then i close this and link the PR to #1294

Thank you icedreamer.
