### ISSUE TITLE
Ladder replays save wrong team information

### ISSUE THREAD

**Issue by yorick-ne** [FAForever/fa#1439]
http://forums.faforever.com/viewtopic.php?f=3&t=11611&start=310#p133220
Both player appear in the same team. Appears to only happen for ladder games. Saw this in both local and replay vault replays, in the replay vault it seems to affect every replay, atleast the display in the (python) replay vault suggests this.
This might be related to some rating problems.

**Comment by GrotheFAF** [comment]
someone could write a script to fix all the ladder replays in vault since feb.
{if replay=ladder: if not '], ''2'': [' in 'teams' : replace(', ','], ''2'': [') }
easy ;-)

**Comment by Crotalus** [comment]
What do you mean with write a script to change replays? This isn't a problem with the actual replay files, it's a problem with the python client not handling teams correctly.

Try with `develop` version of the client, it has some new replay vault code.

**Comment by yorick-ne** [comment]
`{"featured_mod_versions": {"11": 3656, "13": 3656, "12": 3656, "15": 3656, "14": 3656, "17": 3656, "19": 3656, "18": 3656, "22": 3656, "20": 3656, "1": 3656, "3": 3634, "2": 3640, "5": 1, "4": 1, "6": 1, "9": 1, "8": 1, "21": 3656}, "num_players": 2, "game_end": 1471618029.603, "uid": 5061550, "title": "yorick Vs The_Witcher", "max_players": 2, "password_protected": false, "sim_mods": {}, "host": "yorick", "map_file_path": "maps/scmp_007.zip", "teams": {"1": ["The_Witcher", "yorick"]}, "mapname": "scmp_007", "state": "playing", "command": "game_info", "visibility": "public", "featured_mod": "ladder1v1", "recorder": "yorick", "launched_at": 1471615883.719488, "complete": true}`
this is the header of my last ladder game replay ( from my disk, not vault). 
This part `"teams": {"1": ["The_Witcher", "yorick"]}` puts us on the same team or not ? 
Or is team 1 the ffa team i.e. no team ?

**Comment by Crotalus** [comment]
Yup, Team 1 is the FFA team ("-" in lobby).

**Comment by GrotheFAF** [comment]
does it make any sense to but both ladderplayers in one team?
(I think the ladder replayfiles are bugged... since feb)

**Comment by yorick-ne** [comment]
good to know this isnt an issue with the replays itself, but rather the display going wrong
i have been using the develop version i think, i'll have a look at the client issues if this is already described there
