### ISSUE TITLE
[Beta Bug] Gift of Chicken results in electrocution

### ISSUE THREAD

**Issue by snufflesAU** [FAForever/fa#1443]
> Gameplay
> 
> The Ythotha now spawns the energy being no matter the method used to kill it
> The Ythotha energy being only spawns for a completed unit

Gifting a player a live chicken results in the chicken changing ownership, but an energy being is also spawned (owned by the gifting member).
Replay for proof to come

**Comment by aeoncleanse** [comment]
Haha, no need, you're absolutely right. 

Well... Crap. How did nobody see this despite the extensive testing? I'll take a look at the code to see if there's a way to prevent this.

**Comment by micheljung** [comment]
Lol. I never would've thought about testing this, and probably neither did anyone else ;)

**Comment by aeoncleanse** [comment]
Should be fixed here 810ffcc30af98701374bd2588fbdc61d911a605b
