### ISSUE TITLE
Auto team button broken

### ISSUE THREAD

**Issue by micheljung** [FAForever/fa#1454]
![image](https://cloud.githubusercontent.com/assets/1864183/18070994/50994e74-6e52-11e6-824c-8f89f73c13c6.png)

as far as I read the chat, the host did use the button.. but nothing changed. No errors in log.

**Comment by Justify87** [comment]
There is this issue: #1403 Maybe it is related?

**Comment by aeoncleanse** [comment]
@Justify87 You want to handle this?

**Comment by Justify87** [comment]
Yeah, but I think one of my latest PRs already handled this. I will do additional tests tomorrow.

**Comment by aeoncleanse** [comment]
Ah, it might be fixed in develop then. Okies.

**Comment by Justify87** [comment]
This is fixed in the latest beta (3659). Just tested it. If someone could confirm, this issue can be closed.
