### ISSUE TITLE
Carriers building aircraft take damage from anti-air units

### ISSUE THREAD

**Issue by Viba** [FAForever/fa#1456]
http://recordit.co/ouYanzW7Wo http://recordit.co/Mi45HnbDiw

**Comment by aeoncleanse** [comment]
Confirmed, also confirmed for older versions pre-3658. I suspect this caused it: https://github.com/FAForever/fa/commit/351144be26e75a72624d0764484d928e211b8ea0

Why units aren't set to non-targetable inside carriers I don't know.
