### ISSUE TITLE
Cybran Cruiser groundgun sometimes not firing

### ISSUE THREAD

**Issue by JaggedAppliance** [FAForever/fa#1458]
After shooting at air targets the cruiser's secondary groundgun sometimes doesn't shoot at ground targets. Haven't worked out how to reproduce this.
[logs.zip](https://github.com/FAForever/fa/files/444892/logs.zip)

**Comment by aeoncleanse** [comment]
Hmm, nothing in those logs.

**Comment by Uveso** [comment]
I am almost sure, this is fixed. #1570
