### ISSUE TITLE
Markers in the lobby map preview are not displayed correctly

### ISSUE THREAD

**Issue by speed2CZ** [FAForever/fa#1460]
The mex and starting locations previews are enot placed properly on the map. It makes a bigger difference on hilly maps.

Some examples:
https://puu.sh/qTREH/c96f279025.png
https://puu.sh/qTRVk/96a9e32368.png

**Comment by Justify87** [comment]
Seems like the image used is not big/accurate enough

**Comment by MrRowey** [comment]
@Garanas Didnt they get fixed not so long ago ?

**Comment by Garanas** [comment]
I fixed something similar in LOUD, but I'm not sure if the same applies here. The images no longer work for me - can't see the issue.

**Comment by MrRowey** [comment]
@speed2CZ any chance you have the images ?

**Comment by speed2CZ** [comment]
Probably these
![ForgedAlliance_2016-08-30_16-12-15](https://user-images.githubusercontent.com/10947024/171602805-8a8c9536-f8b2-4e56-90e0-5a11b9bbb1b1.png)
![ForgedAlliance_2016-08-30_16-17-39](https://user-images.githubusercontent.com/10947024/171602825-4a49c219-946e-46e8-9071-82a17af41275.png)

**Comment by MrRowey** [comment]
@Garanas Images have been re added

**Comment by Garanas** [comment]
This is more an issue with the previews not being rendered in orthographic mode, then an issue with the markers. I don't think we can do anything about this.

**Comment by Garanas** [comment]
Closing this issue accordingly.
