### ISSUE TITLE
New approach to Selens

### ISSUE THREAD

**Issue by aeoncleanse** [FAForever/fa#1462]
Needing to rethink some approach, I find myself re-visiting a wall I ran into a month ago. So my question is this:

How can I get self.HiddenSelen set inside a unit script to show up as non-nil in gamemain.lua, and accessible as part of the following function:

`-- Function to remove hidden selens from a selection which includes units other than hidden selens
function DeselectSelens(selection)
    local hiddenSelens = false
    local otherUnits = false

    -- Find any selens with the hidden flag
    for id, unit in selection do
        -- Stupid-ass UnitData table uses string numbers as keys. Because reasons?
        if unit:IsInCategory("xsl0101") and unit:IsIdle() and GetFireState({unit}) == 1 then -- Is Unit an activated Selen?
            WARN('Selected a selen')
            WARN(unit.HiddenSelen)
            hiddenSelens = true
        else
            if not otherUnits then otherUnits = {} end -- Ugly hack to make later logic easier
            table.insert(otherUnits, unit)
        end
    end

    -- Return original selection with no-change key if nothing has changed
    if (otherUnits and not hiddenSelens) or (not otherUnits and hiddenSelens) then
        return selection, false
    end

    return otherUnits, true
end`

I know there's some way to do some things and make this value sync from sim into user, but what. @Crotalus @duk3luk3 @Uveso any ideas?

**Comment by Uveso** [comment]
Only workaround i see is adding a energyconsumption to the cloak.
Add inside the unitbluprint, where the self.Cloaked is:
```
self.Cloaked = true
self:SetConsumptionPerSecondEnergy(1)
self:SetConsumptionActive(true)
```
```
self.Cloaked = false
self:SetConsumptionPerSecondEnergy(0)
self:SetConsumptionActive(false)
```

then you can ask inside the selection:
`
if unit:GetEconData().energyRequested = 1 then
--we are cloaked
end
`

Sorry, i dont see another way :/

**Comment by aeoncleanse** [comment]
There's a way you can add unit values to the sync tables. I just can't remember how to  do it :p

**Comment by Exotic-Retard** [comment]
i totally dont know what im doing but did you try (something like) this:
```
local hiddenSelen = false
table.insert(Sync , hiddenSelen)
```

**Comment by aeoncleanse** [comment]
Several variants, yes :(

**Comment by Crotalus** [comment]
Sim side:
`self.Sync.isHidden = true`

User side:
`if(UnitData[id].isHidden)`

**Comment by aeoncleanse** [comment]
@Crotalus 
I tried that after you posted, and several other variations, and I still simply cannot get it to go through. 

https://github.com/aeoncleanse/fa/commits/fix/SelenToggle

What am I doing wrong?

**Comment by Crotalus** [comment]
Try:
```
WARN(UnitData[unit:GetEntityId()].HiddenSelen)
```

GetUnitId() returns the bp-id white GetEntityId() gets the unique id for the unit

**Comment by aeoncleanse** [comment]
Bingo! You're a genius, thanks mate.
