### ISSUE TITLE
FA-Menu (F10) in left corner no click reaction & crash report (develop)

### ISSUE THREAD

**Issue by GrotheFAF** [FAForever/fa#1463]
Opening the FA (middle) Menu (during game), it apears at the left and does not react to clicks, or going away. Leaving over click on 'score', 'esc' ... I sometimes see a FA crash report.
(I run FAFclient 0.11.60-44-g6c0277c develop branch out of PyCharm)

![faf-fa-menu-prbl](https://cloud.githubusercontent.com/assets/19195504/18158132/980f9b02-7021-11e6-8e42-03047165a0e2.jpg)

[game.log.txt](https://github.com/FAForever/fa/files/449301/game.log.txt)
[FA-crash_report.txt](https://github.com/FAForever/fa/files/451572/FA-crash_report.txt)

**Comment by Uveso** [comment]
Looks like the same error here:
http://forums.faforever.com/viewtopic.php?f=3&t=13023

**Comment by aeoncleanse** [comment]
#1517 duplicated this. We'll keep the new one.
