### ISSUE TITLE
Investigate the cause of the team balance string corruption

### ISSUE THREAD

**Issue by aeoncleanse** [FAForever/fa#1468]
Spawned from #1449 

While that PR forms an end-of-line measure to stop the error making it to the display, it was pointed out the cause was unknown. It was theorised that it could have something to do with the Phantom custom game-mode. I'm going to merge the PR's fix, as it also covers any other possibility for corruption in the string, but we also need to see if we can find the cause and fix that.

**Comment by duk3luk3** [comment]
Speculation based on not reading any code at all follows -

It seems pretty obvious that "all players are on the same team" would make the game quality calculation screw up if that wasn't taken into account. So there's probably a very simple fix for that.

Open questions:
* Why is game quality stored into preferences in the first place? What exactly is stored, game quality of last game played?
* Do we just set game quality to 0 for every case where it doesn't make sense to have a game quality? The correct[TM] value is of course `NaN` ;)

**Comment by Uveso** [comment]
got this error right now.
i directly looked into trueskill lua and the check is there:
`    if not result >= 0 and not result <= 100 then return 0 end`
So this is not working.

Btw, i started a skirmish game with one AI.

**Comment by Uveso** [comment]
Fixed, can be closed.
