### ISSUE TITLE
FAF should use an open translation platform

### ISSUE THREAD

**Issue by Crotalus** [FAForever/fa#147]
We could have use of one of the translation platforms to keep track of the translation and updating new strings that we create in the game.

Does anyone have any experience with one of these?

One example is Transifex: https://www.transifex.com/

**Comment by MrRowey** [comment]
@Garanas Thoght on this as a posibility ?

**Comment by Garanas** [comment]
We do need translations for various languages as a lot of features that are added have no proper translations to other languages. I am keeping this one open, but I'm not sure when we have time to work on this.

**Comment by MrRowey** [comment]
@Garanas only issuse with this is the Repo dose not have a licence so being able to automate this would require a paid for version or add a licence

**Comment by Garanas** [comment]
We can't add a license. I'm fond of the idea of having auto-translations, but we likely do not have the funds for it. I am closing it.
