### ISSUE TITLE
Option "Share Unit Cap at Death" not working correctly

### ISSUE THREAD

**Issue by Uveso** [FAForever/fa#1481]
Share unitcap is taking neutral armies into account while splitting the unitcap after player/Ai dead.

Played a map with 5 player and 2 neutral armies with a unitcap of 500 for all players.

After one player died, 500 units should be evenly distributed to the 4 players.
Makes 625units for the remaining 4 players.

But the game only give 583 units.
83 = 500 units are divided through 6.
The 4 players and the 2 civilian armies.

**Comment by Uveso** [comment]
I planed to fix this next week, so you can assign this to me.

**Comment by Uveso** [comment]
PR ist up

**Comment by aeoncleanse** [comment]
We'll keep this open until merged in.

**Comment by aeoncleanse** [comment]
5e91a56402deb9f00f823b729b50314dffe80763
