### ISSUE TITLE
Increase reclaim time of wrecks

### ISSUE THREAD

**Issue by Crotalus** [FAForever/fa#1484]
With reclaim values being quite high (81% for stuff on land) a major increase of the time in takes to reclaim the fields of battle to mitigate the negative effect of a failed attack.

Maybe also introduce a way to reclaim faster by either moving in a "reclaimer unit" (high reclaim rate but slow/weak) or put down some kind of mass extractor building which then automatically reclaims wreck in a radius while it is active.

**Comment by JaggedAppliance** [comment]
Reducing the speed of reclaim is definitely an idea I can get behind, a single t1 engy reclaims 50 mass/s which is an insane amount.

**Comment by speed2CZ** [comment]
Yeah currently the engineers reclaim speed depends on it's build power. But it should depend on what it's reclaiming.
iirc balance terrorists were working on this @Exotic-Retard did you solve this?

**Comment by Zockyzock** [comment]
Its planned for a later balance patch

**Comment by Exotic-Retard** [comment]
/me frolics in here to say fixed in equilibrium; you want to look in here:
[https://github.com/FAForever/fa/blob/develop/lua/sim/Unit.lua#L1422](url)
simply add a *2 to the end of that to double the reclaim time.
