### ISSUE TITLE
DISABLED button inside Mod-manager is not working.

### ISSUE THREAD

**Issue by Uveso** [FAForever/fa#1502]
I can't figure out, what the `DISABLED` filter button is doing.

In my eyes its not working at all.

**Comment by aeoncleanse** [comment]
I literally just came to the same conclusion today. Even when I have some mods set as disabled, it gets rid of them, but then won't bring them back, like a one-way toggle.

**Comment by Uveso** [comment]
We should ask @HUSSAR-mtrela :)

**Comment by HUSSAR-mtrela** [comment]
The DISABLED filter button is toggling hiding/showing mods that are blacklisted by FAF (in blacklist.lua) 
I have just tried toggling this button in the current FAF patch and it works as expected. 
@aeoncleanse Did you notice the "one-way toggle" in FAF beta?

**Comment by Uveso** [comment]
Ah ok, i don't have blacklisted mods :) 

I will write this inside the Tooltip text, then its not so confusing. :)

**Comment by Uveso** [comment]
Tested this with an blacklisted mod and it worked like expected.
I also don't have any problems with other mods disappearing.
