### ISSUE TITLE
Load button for Skirmish games is misplaced.

### ISSUE THREAD

**Issue by Uveso** [FAForever/fa#1505]
The Load button for "Load a previously saved skirmish game" inside the Skirmish lobby is misplaced:

![loadskirmish](https://cloud.githubusercontent.com/assets/17804547/18576773/df12519c-7be4-11e6-9ea2-02f881133675.png)

**Comment by aeoncleanse** [comment]
Doesn't matter. Skirmish mode is never used.

**Comment by speed2CZ** [comment]
It does matter if you decide to play offline. I don't see a reason why someone couldn't fix it

**Comment by aeoncleanse** [comment]
Because there's other shit broken in the skirmish tab. It's never been intended for faf use, when I'm offline I just launch via multiplayer menu because that's how FAF does.

**Comment by speed2CZ** [comment]
I use it all the time for offline testing and I haven't found "other shit broken" there.

**Comment by aeoncleanse** [comment]
11dd1c8376033a233cca5db95d743189233639f3
