### ISSUE TITLE
Harb attack move behaviour

### ISSUE THREAD

**Issue by JaggedAppliance** [FAForever/fa#1512]
Harbs can't attack and reclaim anymore and they reclaim on attack and patrol moves. This means they will get caught reclaiming and take lots of fire while reclaiming without shooting back. 

They should behave like acus so they don't reclaim on attack move, only on patrol orders.

**Comment by Exotic-Retard** [comment]
i kinda dont see why it was made so they dont fire and reclaim at the same time, that solves the issue too
#justequilibriumthings

**Comment by aeoncleanse** [comment]
#1632 tracking this
