### ISSUE TITLE
preset SCUs' enhancements have no description

### ISSUE THREAD

**Issue by JaggedAppliance** [FAForever/fa#1514]
As stated in the title. The non preset SCUs have descriptions for their upgrades.

**Comment by Uveso** [comment]
Do you mean the description while hovering the mouse over a build preset inside the Quantumgate ?
I checked all gates and all presets. Tooltips with description is working.
(tested in develop version)

![presets](https://cloud.githubusercontent.com/assets/17804547/18774467/d185af5e-8159-11e6-9756-9675eddc00b1.png)

**Comment by speed2CZ** [comment]
He means upgrades of those sacus, build some and then check if it has tooltips for its upgrades

**Comment by aeoncleanse** [comment]
Confirmed. Error "WARNING: No description found for unit: \000uel0301_Engineer\000 enhancement: \000sgf"

**Comment by Uveso** [comment]
I see. Thanks for the explanation!

**Comment by aeoncleanse** [comment]
26bd190249d4812366835762af81bd92769ab28e

**Comment by Exotic-Retard** [comment]
nice work - means i dont have to update the localization with a ton of duplicate descriptions )
