### ISSUE TITLE
Menu blocking top left corner in ladder games

### ISSUE THREAD

**Issue by arkitect-dev** [FAForever/fa#1517]
http://forums.faforever.com/viewtopic.php?f=3&t=13023&start=10

While in game the drop down menu in the middle of the screen from the top is shifted to the top left corner and all the buttons are on top of each other. These cannot be clicked, but can be navigated using keyboard. This does not happen while watching a replay, only during an online game.

**Comment by aeoncleanse** [comment]
@Crotalus @duk3luk3 @Uveso @HUSSAR-mtrela  Can any of you spare the time to investigate this?

**Comment by Uveso** [comment]
I was involved in the posted thread. All i can say is;
This error is surely from the game itself and not from mods etc.

Because its need to start a ladder game to reproduce the error i can't have a look at it.

**Comment by Uveso** [comment]
Fix is up: #1540

**Comment by aeoncleanse** [comment]
d6c5d426e768f792b817482dae3a4bd93ccb4ac7
