### ISSUE TITLE
Map / Name-Filter-Text-Box is invisible

### ISSUE THREAD

**Issue by Uveso** [FAForever/fa#1526]
Inside options the textbox for the Map name Filter is not visible:

![namefilter1](https://cloud.githubusercontent.com/assets/17804547/18687598/267f649e-7f81-11e6-9cf7-26b916650385.png)

After 10 years playing i found this out:

![namefilter2](https://cloud.githubusercontent.com/assets/17804547/18687613/37888342-7f81-11e6-967c-3d1613adfe80.png)

Would be nice, if we could make the backgroundcolor of the textfield different from the normal background.

**Comment by aeoncleanse** [comment]
Nice work you two :)

**Comment by aeoncleanse** [comment]
72c09f9e0ca6dd08d2587e645c8de519bf4456b7
