### ISSUE TITLE
ML laser FX continues while death animation plays

### ISSUE THREAD

**Issue by aeoncleanse** [FAForever/fa#1544]
Can we kill it earlier?

**Comment by Uveso** [comment]
Sure we can :)

**Comment by Crotalus** [comment]
We should probably do generic weapon / beam cleanup within unit.OnKilled. Currently Colossus does this in its own script for instance.

**Comment by Uveso** [comment]
hmm this only occurs when a unit has a `BeamWeapon` AND the `DeathThread` is delayed with `WaitSeconds(x)` commands. How many units have this ?

**Comment by Crotalus** [comment]
No idea, not many is my guess. 

Maybe should look at letting the weapon itself adding it to some kind of effect trashbag when it's initialized, so that the effects are destroyed at the same time other unit effects are.

**Comment by Uveso** [comment]
Only the 2 units, ual0401 (Galactic Colossus) and url0402 (Monkeylord) have an delayed DeathThread and BeamWeapons. (I also checked all other units with delayed DeathThread but no beam Weapon.)

They are all working exept the Monkeylord.

**Comment by Exotic-Retard** [comment]
in the interest of mod support it might make sense to do what crotalus suggestion to make this for all units just in case

**Comment by Uveso** [comment]
In my opinion, if a modder decides to make a destructive hook, and delay the deathThread, then he has to deal with the fact, that he needs to take care of the beams.

The problem is not the weapon, its the delayed DeathThread.

You know, i always support mods whenever i can. But not in this case :)

**Comment by aeoncleanse** [comment]
828816be84d84cc697f9eec930e703fc1ab00e10

**Comment by Exotic-Retard** [comment]
just noticed that a very related bug exists - neptunes while firing and sinking at the same time seem to also not kill the beam. i expect this to also apply to sera destroyers.

**Comment by Uveso** [comment]
yup i have already a fix for it, im testing this on a LAN session right now :)
Also an issue, the sound don't stop for the beam laser. I fixed this too.
PR will be up in the next 24 hours.

**Comment by Uveso** [comment]
Fix for the monkeylord and neptunes is up.
