### ISSUE TITLE
Investigate death of all beam-wielding units

### ISSUE THREAD

**Issue by aeoncleanse** [FAForever/fa#1555]
Spawned from #1544. We need to find out how many beams have this issue, and choose to fix case by case or globally based on that number.

**Comment by Uveso** [comment]
These are all units with an custom DeathThread:

URL0402 MonkeyLord CDFHeavyMicrowaveLaserGenerator (Beam Weapon fixed)
UAL0401 Colossus ADFPhasonLaser (Beam Weapon fixed)

URS0201 CDFProtonCannonWeapon (no Beam Weapon)
XRL0403 Megalith CDFHvyProtonCannonWeapon (no Beam Weapon)
XSL0401 Ythotha SDFExperimentalPhasonProj (no Beam Weapon)

XRC2201 CCivilianStructureUnit (no Weapon)
XRB3301 Soothsayer (no weapon)

**Comment by Uveso** [comment]
Fix for the Monkey is here: https://github.com/FAForever/fa/pull/1557
Monkey Beams are now disabled inside the OnKilled function like colossus does.

Fix for the Neptune is here: https://github.com/FAForever/fa/pull/1558
This was a different error. Just a bracket on the wrong place.

Monkey and Colossus are the only units with DeathThread and Beam Weapons.
And The Neptune beam failed on a different error and don't count here.

So i don't expect more beam issues.
