### ISSUE TITLE
Double-check all aspects of #1279 in multiplayer non-local play

### ISSUE THREAD

**Issue by aeoncleanse** [FAForever/fa#1560]
Need to be certain this is not causing problems.

**Comment by aeoncleanse** [comment]
https://github.com/FAForever/fa/pull/1279

**Comment by aeoncleanse** [comment]
Confirmed online with keyser and others, function is working nicely. 

Clashes with Supreme Score Board. @HUSSAR-mtrela You'll probably want to check that out.

**Comment by HUSSAR-mtrela** [comment]
@aeoncleanse @Crotalus why/how is the PR #1279 is clashes with the Supreme Score Board? Was there some kind of breaking change in transferring units?

**Comment by aeoncleanse** [comment]
I've not personally tested the two together mate. This does make some changes to the transfer code. If you're hooking it for some reason, you'll maybe need to adapt. I suggest you check out develop and see what happens with your mod.

**Comment by HUSSAR-mtrela** [comment]
ok thanks for head up... I will test is with my mod.
