### ISSUE TITLE
beta: spider doesn't die properly when killed

### ISSUE THREAD

**Issue by JaggedAppliance** [FAForever/fa#1562]
[game.zip](https://github.com/FAForever/fa/files/500493/game.zip)
https://www.youtube.com/watch?v=TrVGtOW_698&feature=youtu.be

**Comment by aeoncleanse** [comment]
```warning: Error running lua script: Invalid weapon index 1; must be between 1 and 0 (inclusive)
         stack traceback:
         	[C]: in function `GetWeapon'
         	...\gamedata\units.nx4\units\url0402\url0402_script.lua(183): in function <...\gamedata\units.nx4\units\url0402\url0402_script.lua:182>```

**Comment by aeoncleanse** [comment]
I've not been able to reproduce this locally in balance/3660. Will try in beta.

**Comment by aeoncleanse** [comment]
OK, managed to reproduce. It doesn't work for ctrl-k. Fixed by the latest spider beam changes in develop.
