### ISSUE TITLE
GameResults not reported

### ISSUE THREAD

**Issue by micheljung** [FAForever/fa#1582]
Long story short: The game does not always report game results. I observed for the JsonStats, too.

Interestingly it seems to affect ALL players. For more details, see FAForever/server#209

This is most likely the root cause of all rating issues.

**Comment by Crotalus** [comment]
Ok, one obvious flaw is that if everyone gets same score (-1) in this case, it will still sort the teams on score and then give one of the team the win. At least it should be counted as a draw.

**Comment by micheljung** [comment]
The ultimate ugly query to count how many games are affected, and which one was the last:

# CAVEAT: EXECUTION TIME IS ~45s

```
SELECT count(*), min(startTime), max(startTime), max(gameId)
FROM (SELECT
        gameId,
        min(startTime) as startTime
      FROM game_player_stats t
        JOIN game_stats s ON t.gameId = s.id
      WHERE t.gameId NOT IN (SELECT gameId
                             FROM game_player_stats
                             WHERE score != -1 OR (after_mean IS NULL AND after_deviation IS NULL)
                             GROUP BY gameId) AND s.validity = 0 AND s.gameMod IN (0, 6)
      GROUP BY gameId) AS broken_games;

```

**Comment by aeoncleanse** [comment]
has this been impacted by our score system adjustments in 3660?

**Comment by micheljung** [comment]
score system adjustemt?

**Comment by aeoncleanse** [comment]
All the messing with stat reporting we just did? :p

**Comment by micheljung** [comment]
GameResult works disconnected from JsonStats.

While I could imagine that it's not FA not sending GameResults after all, but that the server didn't process it due to FAForever/server#229, I found games that had the same problem before JsonStats were even a thing. But, maybe there was just another problem back then.
Also we've never been able to reproduce this so I'd close it as "invalid" for now. And I'd remove it from any milestone.
