### ISSUE TITLE
Split-attack crashes with too many splits. Why?

### ISSUE THREAD

**Issue by aeoncleanse** [FAForever/fa#1583]
It shouldn't be hard to make this work properly.

**Comment by aeoncleanse** [comment]
@Crotalus

**Comment by Crotalus** [comment]
Tried to replicate this with 1000 bombers attacking a bunch of units and then split the orders. Is there an easy way to get the crash?

**Comment by aeoncleanse** [comment]
A crowd of asfs attacking a group of gunships is brnks example of choice. The number of attackers is less important thab number of targets. Try 200 asf vs 50 gunships and split that

**Comment by aeoncleanse** [comment]
Hmm. Well, I have now tested this extensively. 500 ASF split against 200 gunships, a worst-case scenario, causes the game to lag for a bit, but goes through. Interestingly, the severe slowdown seems to be cause by the rendering of all the attack patterns, not the actual giving of the command, as pressing shift once this order had been split tanked my FPS.
