### ISSUE TITLE
Kill a player's walls when they die

### ISSUE THREAD

**Issue by JaggedAppliance** [FAForever/fa#1588]
A player's walls don't get killed when they die unlike every other structure or unit in the game. I don't see any reason for this and it's pretty annoying in some scenarios.

**Comment by aeoncleanse** [comment]
I also always wondered. @Zockyzock is there a reason for this?

**Comment by Uveso** [comment]
aibrain.lua inside function OnDefeat() line 668:
```
            -- Kill all units left over
            local tokill = self:GetListOfUnits(categories.ALLUNITS - categories.WALL, false)
            if tokill and table.getn(tokill) > 0 then
                for index, unit in tokill do
                    unit:Kill()
                end
            end

```
Walls are excuded from player dead also in vanilla game version.

And as you can see, its easy to change if we want this.

**Comment by Exotic-Retard** [comment]
i think its pretty cool that they stay

also how is your wall art supposed to sruvive without them?

**Comment by JaggedAppliance** [comment]
I remember a badlands game where one player had walled the side, he dies and his teammate wanted to attack with loyas or something but the only way to get rid of the walls is reclaiming them, very annoying.

**Comment by Uveso** [comment]
I remember a game where my teammate dies and i only survived because i got his units and all PDs where covered with walls. Without the walls i had lose the game.

**Comment by JaggedAppliance** [comment]
Well if it's full share then they shouldn't die ofc

**Comment by JaggedAppliance** [comment]
I just remembered walls don't get transferred to anyone when you die either and they can't be selected en masse using double click or ctrl click. Those features would also be nice.

**Comment by Uveso** [comment]
Yes, walls are not destroyed because they where explicitly excluded from destroying.
And you can mass select walls with holding left mousebutton and moving the select-square over all walls.

Btw, changes are already done:  #1590

**Comment by shalkya** [comment]
i would argue in favor of killing walls too.
it can lean to an unfair advantage. (harder to cancel the reclaim of a dead base when there is walls slowing down your attack)
