### ISSUE TITLE
Add option to change the language

### ISSUE THREAD

**Issue by speed2CZ** [FAForever/fa#1591]

**Comment by Uveso** [comment]
This is not so easy. I already worked on it, but i can't build the option menu with an unknown language.
(I need to read the HDD loc/ folder for any language that is in there)
I need this for a language that is not known from FAF like .SZ

Mabye if i do a custom menu inside the main menu. But i am not able to do this at the moment.

If there is someone able to make a custom menu like profile loading, i can make the code for the language stuff.

**Comment by speed2CZ** [comment]
What if we collect all existing languages? :)
http://forums.faforever.com/viewtopic.php?f=2&t=13280

**Comment by Uveso** [comment]
Even if we collect all "known" languages, what if someone starts to make a new one ? 

I have already an idea how to do this. 

But i have a cold at the moment, so this can take 2-3 days :)

**Comment by speed2CZ** [comment]
If someone's make a new one, we can add it no?

**Comment by Uveso** [comment]
Yes we could, but i already have a automatic version.
It's scans for languages inside /loc/ folder and provide it inside the selection menu.

#1598

**Comment by aeoncleanse** [comment]
2d86715d94fca514a4ed8a85039af23353255b97
