### ISSUE TITLE
"Host has left the game" error when trying to join a lobby

### ISSUE THREAD

**Issue by JaggedAppliance** [FAForever/fa#1592]
[forever.zip](https://github.com/FAForever/fa/files/517790/forever.zip)

**Comment by JaggedAppliance** [comment]
Happened again.
[forever.zip](https://github.com/FAForever/fa/files/670022/forever.zip)

**Comment by speed2CZ** [comment]
This has nothing to do with game

**Comment by JaggedAppliance** [comment]
No idea why I put this here originally. https://github.com/FAForever/client/issues/540
