### ISSUE TITLE
LOG when someone loses connection

### ISSUE THREAD

**Issue by speed2CZ** [FAForever/fa#1599]
Is is possible to log when someone loses connection?
So when the disconnect window appears.

Purpose for this is that if someone is lagging the game on a purpose there is pretty much no way to find out from the replay. (reconnecting before can be kicked by other, etc...)

**Comment by Uveso** [comment]
And on every support post the same question: What gamerversion are you running ? .. aahhhhh...

Could we please also log the actual game version, like:
`Starting Supreme Commander Forged Alliance V 1.5.3660` ?

This would be a dream :D

**Comment by speed2CZ** [comment]
Here's the code, find out where to put it :D
```LUA
LOG('Starting Supreme Commander: Forged Alliance V ' .. GetVersion())
```
