### ISSUE TITLE
"Rehost" only works for current host

### ISSUE THREAD

**Issue by micheljung** [FAForever/fa#1609]
... but it should work for any player (maybe the host got dropped, someone else wants to rehost instead)

**Comment by aeoncleanse** [comment]
b11a0ff526265e3407c0382b26b93f492ac2ede4

**Comment by micheljung** [comment]
The issue would've gotten closed automatically as soon as it's merged into develop, since I wrote `Fix #1609` into the commit message - so the reference was already there too :)
