### ISSUE TITLE
Loading presets don't store the data inside the option window

### ISSUE THREAD

**Issue by Uveso** [FAForever/fa#1610]
If you load a preset inside multiplayer lobby you can see the new settings from the preset on the right side of the screen. 
(If you now start the game, all options from the loaded preset are in use. So this works.)

But if you open the option window, you will not see the options from the preset.
You will still see the old options.

**Comment by HUSSAR-mtrela** [comment]
it looks like that we do not update options when loading a preset or the option window does not load options from lobby but rather it keeps it own set of old options.

**Comment by MrRowey** [comment]
@Garanas Does anyone actually use the Lobby Presets ? could this just be something that is removed so it's less hassle ?

**Comment by Garanas** [comment]
I'm surely not one of those people. What would a hypothetical use case be for the lobby presets?

**Comment by MrRowey** [comment]
if you wanted to save X setting but tbh IDK how many people even know what the presets are / How to use them

**Comment by Garanas** [comment]
![image](https://user-images.githubusercontent.com/15778155/140663174-f949d8d1-a76d-46f4-be3a-990880fb2415.png)

Where do you set or select presets?

**Comment by MrRowey** [comment]
Huh also seem to be busted and you cant even create new presets anymore

**Comment by Uveso** [comment]
I bet not a single player is using presets since they don't work for at least 6 years.
I would outcomment the button for the next patch. 

Lets see if anyone is missing the button.

**Comment by Garanas** [comment]
Sounds like a good suggestion. I'll make a PR accordingly.
