### ISSUE TITLE
cybran tmd is targeting wrong rockets

### ISSUE THREAD

**Issue by OCGDFS** [FAForever/fa#1613]
replay ID 5299340, minute ~14 Giem front.
his tmds shot down his own rockets several times instead ov incoming enemy rockets

**Comment by Exotic-Retard** [comment]
i dont have much time here, but cyb tmd has collidefriendly = false and damagefriendly is not present. might be worth putting it in as false and seeing if that solves the issue (i think its false by default but not sure.)

ideally it would never collide but if we can at least not make it able to damage then that would be cool too.

also based on the unit bp i would have trouble believing this if not for the replay, really shouldn't happen, ever, and not heard of it happen before either.

very strange indeed.

**Comment by OCGDFS** [comment]
its not only that allied missiles are in the way.. it appears like the tmd react to incoming missiles, but is firing on the wrong missile, and wrong direction. sometimes as soon as they are launched
