### ISSUE TITLE
Connection messages are logged twice

### ISSUE THREAD

**Issue by micheljung** [FAForever/fa#1623]
```
Connection to ..... established.
Connection to ..... established.

Lost connection to ....
Lost connection to ....
```

**Comment by aeoncleanse** [comment]
Wonder when this started...

**Comment by aeoncleanse** [comment]
The latter is called in lobbyComm.DataReceived = function(self,data), so it could be multiple messages being sent that's the cause. The former is in function SetSlotInfo(slotNum, playerInfo).

**Comment by aeoncleanse** [comment]
OK I did a test with Voodoo, Jackherer, and Jitsu. The "Connection to _ established" message only appeared once. The "Lost connection to _" message appeared only once for me when Voodoo was asked to DC (I was host), but it appeared twice for each other player.

**Comment by Garanas** [comment]
This is trashing the logs, but it is not a critical issue. Closing as not planned.
