### ISSUE TITLE
pause bug

### ISSUE THREAD

**Issue by shalkya** [FAForever/fa#1624]
not sure if intended or not (i don't think so)
if you selection a factory, and deselect it, you can still pause and unpause it by using the hotkey.
which is weird for me.

(also had a bug which was that i was using the pause hotkey, and i was seeing the pause button getting pause and unpause, but it wasn't actually pausing the facto; i was able to do it several time in a row, but doesn't seems that i can reproduce it atm.)

**Comment by aeoncleanse** [comment]
Confirmed and verified as a vanilla bug not a regression. Present back to at least 3610. Also happens on ACU or anything else with pause.
