### ISSUE TITLE
Replays desync due to pings, pings also sometimes visible to enemy

### ISSUE THREAD

**Issue by Viba** [FAForever/fa#1626]
replay.log:

> info: playable area coordinates are { 0, 0, 1024, 1024 }
> info: Offmapareas are {
> info:   { x0=-100, x1=1124, y0=-100, y1=0 },
> info:   { x0=-100, x1=1124, y0=1024, y1=1124 },
> info:   { x0=-100, x1=0, y0=0, y1=1024 },
> info:   { x0=1024, x1=1124, y0=0, y1=1024 }
> info: }
> debug: Loading module '\000/lua/ui/game/scoreaccum.lua\000'
> info: Hooked /lua/ui/game/scoreaccum.lua with /mods/em/hook/lua/ui/game/scoreaccum.lua
> info: Hooked /lua/ui/game/scoreaccum.lua with /mods/common/hook/lua/ui/game/scoreaccum.lua
> debug: Loading module '\000/effects/entities/unitteleport01/unitteleport01_script.lua\000'
> debug: Loading module '\000/lua/sim/defaultprojectiles.lua\000'
> debug: Loading module '\000/lua/sim/projectile.lua\000'
> debug: Loading module '\000/lua/simping.lua\000'
> info: syncing max ping markers: \00015
> debug: Loading module '\000/lua/simcallbacks.lua\000'
> debug: Loading module '\000/lua/selfdestruct.lua\000'
> debug: Loading module '\000/lua/simcameramarkers.lua\000'
> debug: Loading module '\000/lua/simdialogue.lua\000'
> debug: Loading module '\000/lua/simdiplomacy.lua\000'
> debug: Loading module '\000/lua/spreadattack.lua\000'
> warning: Checksum for beat 50 mismatched: 3af76dfed12f215030e2d8fad3a9518c (sim) != e886967b776e72552cae306227d2120b (Hzale).
> debug: Loading module '\000/units/uab0101/uab0101_script.lua\000'
> debug: Loading module '\000/lua/aeonunits.lua\000'
> debug: Loading module '\000/lua/tarmacs.lua\000'
> debug: Loading module '\000/units/urb0101/urb0101_script.lua\000'
> debug: Loading module '\000/units/ura0001/ura0001_script.lua\000'
> debug: Loading module '\000/units/ueb0101/ueb0101_script.lua\000'
> debug: Loading module '\000/effects/entities/aeonbuildeffect/aeonbuildeffect01_script.lua\000'
> debug: Loading module '\000/effects/entities/uefbuildeffect/uefbuildeffect02_script.lua\000'
> debug: Loading module '\000/effects/entities/uefbuild/uefbuild01_script.lua\000'
> debug: Loading module '\000/lua/formations.lua\000'
> warning: Checksum for beat 50 mismatched: 3af76dfed12f215030e2d8fad3a9518c (sim) != e886967b776e72552cae306227d2120b (Mr_J).
> warning: Checksum for beat 50 mismatched: 3af76dfed12f215030e2d8fad3a9518c (sim) != e886967b776e72552cae306227d2120b (Haiskoahanta-_-).
> warning: Checksum for beat 50 mismatched: 3af76dfed12f215030e2d8fad3a9518c (sim) != e886967b776e72552cae306227d2120b (Styrbjorn).
> warning: Checksum for beat 50 mismatched: 3af76dfed12f215030e2d8fad3a9518c (sim) != e886967b776e72552cae306227d2120b (PhilipJFry).
> debug: Loading module '\000/effects/entities/uefbuildeffect/uefbuildeffect03_script.lua\000'
> warning: Checksum for beat 50 mismatched: 3af76dfed12f215030e2d8fad3a9518c (sim) != e886967b776e72552cae306227d2120b (Giebmasse).
> warning: Checksum for beat 50 mismatched: 3af76dfed12f215030e2d8fad3a9518c (sim) != e886967b776e72552cae306227d2120b (Ban_ki_Moon).
> warning: Checksum for beat 50 mismatched: 3af76dfed12f215030e2d8fad3a9518c (sim) != e886967b776e72552cae306227d2120b (BIT_Chess).
> debug: Loading module '\000/lua/ui/dialogs/desync.lua\000'
> debug: Loading module '\000/lua/ui/controls/textarea.lua\000'
> warning: Desync at beat 53 tick 5.4245104789734
> info: creating high fidelity terrain
> info: creating high fidelity water
> warning: Desync at beat 55 tick 5.6011056900024
> warning: Desync at beat 56 tick 5.713050365448
> warning: Checksum for beat 100 mismatched: 07f441ba2ec016af3feb3920ef41e478 (sim) != e55d93a2791cba84673f8aaddf161128 (BIT_Chess).
> warning: Checksum for beat 100 mismatched: 07f441ba2ec016af3feb3920ef41e478 (sim) != e55d93a2791cba84673f8aaddf161128 (Haiskoahanta-_-).
> warning: Checksum for beat 100 mismatched: 07f441ba2ec016af3feb3920ef41e478 (sim) != e55d93a2791cba84673f8aaddf161128 (Ban_ki_Moon).
> warning: Checksum for beat 100 mismatched: 07f441ba2ec016af3feb3920ef41e478 (sim) != e55d93a2791cba84673f8aaddf161128 (PhilipJFry).
> warning: Checksum for beat 100 mismatched: 07f441ba2ec016af3feb3920ef41e478 (sim) != e55d93a2791cba84673f8aaddf161128 (Mr_J).
> warning: Checksum for beat 100 mismatched: 07f441ba2ec016af3feb3920ef41e478 (sim) != e55d93a2791cba84673f8aaddf161128 (Giebmasse).
> warning: Checksum for beat 100 mismatched: 07f441ba2ec016af3feb3920ef41e478 (sim) != e55d93a2791cba84673f8aaddf161128 (Styrbjorn).
> warning: Checksum for beat 100 mismatched: 07f441ba2ec016af3feb3920ef41e478 (sim) != e55d93a2791cba84673f8aaddf161128 (Hzale).
> warning: Desync at beat 102 tick 10.305038452148
> warning: Desync at beat 105 tick 10.605430603027
> warning: Desync at beat 106 tick 10.705580711365
> warning: Desync at beat 107 tick 10.805648803711
> warning: Checksum for beat 150 mismatched: 77feeb2f7865f97fc4755b7e9e4ae910 (sim) != a630b95e6346eec5f0262c7f2ab784f7 (BIT_Chess).
> warning: Checksum for beat 150 mismatched: 77feeb2f7865f97fc4755b7e9e4ae910 (sim) != a630b95e6346eec5f0262c7f2ab784f7 (Hzale).
> warning: Checksum for beat 150 mismatched: 77feeb2f7865f97fc4755b7e9e4ae910 (sim) != a630b95e6346eec5f0262c7f2ab784f7 (Mr_J).
> warning: Checksum for beat 150 mismatched: 77feeb2f7865f97fc4755b7e9e4ae910 (sim) != a630b95e6346eec5f0262c7f2ab784f7 (Haiskoahanta-_-).
> warning: Checksum for beat 150 mismatched: 77feeb2f7865f97fc4755b7e9e4ae910 (sim) != a630b95e6346eec5f0262c7f2ab784f7 (Ban_ki_Moon).
> warning: Checksum for beat 150 mismatched: 77feeb2f7865f97fc4755b7e9e4ae910 (sim) != a630b95e6346eec5f0262c7f2ab784f7 (Giebmasse).
> warning: Checksum for beat 150 mismatched: 77feeb2f7865f97fc4755b7e9e4ae910 (sim) != a630b95e6346eec5f0262c7f2ab784f7 (Styrbjorn).
> warning: Checksum for beat 150 mismatched: 77feeb2f7865f97fc4755b7e9e4ae910 (sim) != a630b95e6346eec5f0262c7f2ab784f7 (PhilipJFry).
> warning: Desync at beat 152 tick 15.30154132843
> warning: Desync at beat 154 tick 15.501729011536
> warning: Desync at beat 155 tick 15.601872444153
> warning: Desync at beat 156 tick 15.701950073242
> debug: Loading module '\000/lua/ui/dialogs/keybindings.lua\000'
> debug: Loading module '\000/lua/keymap/keydescriptions.lua\000'
> debug: Loading module '\000/lua/keymap/properkeynames.lua\000'
> debug: Loading module '\000/lua/keymap/keycategories.lua\000'
> warning: Checksum for beat 200 mismatched: d55a22993dc16d5a536793fb2133fea2 (sim) != 7687fe3ae1a42e582f43007aa37cf2db (BIT_Chess).
> warning: Checksum for beat 200 mismatched: d55a22993dc16d5a536793fb2133fea2 (sim) != 7687fe3ae1a42e582f43007aa37cf2db (Hzale).
> warning: Checksum for beat 200 mismatched: d55a22993dc16d5a536793fb2133fea2 (sim) != 7687fe3ae1a42e582f43007aa37cf2db (Haiskoahanta-_-).
> warning: Checksum for beat 200 mismatched: d55a22993dc16d5a536793fb2133fea2 (sim) != 7687fe3ae1a42e582f43007aa37cf2db (Giebmasse).
> warning: Checksum for beat 200 mismatched: d55a22993dc16d5a536793fb2133fea2 (sim) != 7687fe3ae1a42e582f43007aa37cf2db (Styrbjorn).
> warning: Checksum for beat 200 mismatched: d55a22993dc16d5a536793fb2133fea2 (sim) != 7687fe3ae1a42e582f43007aa37cf2db (Ban_ki_Moon).
> warning: Checksum for beat 200 mismatched: d55a22993dc16d5a536793fb2133fea2 (sim) != 7687fe3ae1a42e582f43007aa37cf2db (PhilipJFry).
> warning: Checksum for beat 200 mismatched: d55a22993dc16d5a536793fb2133fea2 (sim) != 7687fe3ae1a42e582f43007aa37cf2db (Mr_J).
> warning: Desync at beat 202 tick 20.307081222534
> warning: Desync at beat 203 tick 20.407186508179
> info: Popup.OnClosed
> info: Error popping escape handler, stack is empty
> info: "stack traceback:\
> info:         ...rever\gamedata\lua.nx2\lua\ui\dialogs\eschandler.lua(48): in function `PopEscapeHandler'\
> info:         ...er\\gamedata\\lua.nx2\\lua\\ui\\controls\\popups\\popup.lua(80): in function`OnClosed'\
> info:         ...er\gamedata\lua.nx2\lua\ui\controls\popups\popup.lua(63): in function `Close'\
> info:         ...ramdata\\faforever\\gamedata\\lua.nx2\\lua\\ui\\uiutil.lua(860): in function`OnClick'\
> info:         ...mdata\faforever\gamedata\lua.nx2\lua\maui\button.lua(85): in function <...mdata\faforever\gamedata\lua.nx2\lua\maui\button.lua:78>"
> warning: Desync at beat 205 tick 20.52720451355
> warning: Desync at beat 206 tick 20.62720489502
> debug: Loading module '\000/lua/ui/game/rallypoint.lua\000'
> debug: Loading module '\000/lua/ui/controls/worldmesh.lua\000'
> info: Run time: 0h00m34s

**Comment by aeoncleanse** [comment]
This player's game, or their enemy's, much not have downloaded the latest patch properly. Ping code is at 3659 state: No changes.

**Comment by Uveso** [comment]
"desync due to pings" should be already fixed.

"pings also sometimes visible to enemy" caused by mod "EcoManager".

**Comment by aeoncleanse** [comment]
The pings to enemy in EM mod was only due to changes made in 3660, changes now removed.

**Comment by CookieNoob** [comment]
@aeoncleanse is this still an issue?

**Comment by aeoncleanse** [comment]
Yeah we hotfixed this ages ago.
