### ISSUE TITLE
Reclaim view unreliable and slow

### ISSUE THREAD

**Issue by Viba** [FAForever/fa#1628]
I often see reclaim numbers for wrecks that aren't there, or then I don't see reclaim numbers for wrecks that are there. Likewise the numbers "jump" around depending on zoom level and what part of map I look at. Before the optimizations you could rely on the numbers, now you have to zoom and fiddle around a while before they show correct values. I got used to using the feature alot but now it got degraded quite badly.

**Comment by aeoncleanse** [comment]
@Crotalus I can't reproduce this my side. Could the performance depend on PC specs?

**Comment by Crotalus** [comment]
Weird, sounds exactly like the problem I managed to replicate with the old implementation. Current version should move their position every frame if needed. You also see labels for wrecks that's been reclaimed?

Make sure you're not running any UI mods that's messing with lua/ui/game/reclaim.lua.

Windowed or Full screen? Does it happen even when wreck numbers are small (<1000)? First step is trying to replicate it.

**Comment by aeoncleanse** [comment]
http://recordit.co/xwUbA0oHRd

**Comment by aeoncleanse** [comment]
From giebmasse

**Comment by Viba** [comment]
A crappy vid: http://recordit.co/xwUbA0oHRd
It happens 4-5min into the game as well as late game.
I'm using windowed mode with gamecompanion turning it into fullscreen.
Didn't find any UI mods with reclaim.lua.

**Comment by aeoncleanse** [comment]
Finally managed to get it to show me a reclaim blip that I can see fully zoomed out, but zooming in makes it vanish. Something's definitely not right.

**Comment by Crotalus** [comment]
Would be great if you could try put this file into one of your UI mods, (need to be in `hook/lua/ui/game/` directory of a mod)

https://raw.githubusercontent.com/Crotalus/fa/reclaimlabels-test/lua/ui/game/reclaim.lua

I removed all camera / zoom checks to see if they causes it. The other performance improvements is still in there.

**Comment by Viba** [comment]
Replay worked a bit better with that^

Zoom popping still happens, reclaim numbers for wrecks that aren't there and vice versa. http://recordit.co/87KrMjUYDv
Felt a bit better, now other/all numbers didn't just disappear from time to time.

**Comment by Crotalus** [comment]
Viba has a test version he'll try in a real game, lets see if that works better. Can be "soft-patched" without breaking current 3660(1) thanks to being UI side.

**Comment by Viba** [comment]
Well first game with the test version and I didn't see any problems.

**Comment by Viba** [comment]
Ok played another game, now I had multiple reclaim numbers for wrecks that weren't there. Like probably over 100.

**Comment by aeoncleanse** [comment]
So you're saying with that last one that markers are working when they exist? Right place, right value, not shifting on pan or zoom, smooth, with the exception that some are not vanishing when they should?

**Comment by Viba** [comment]
Pretty much, yes.

**Comment by aeoncleanse** [comment]
Is it just me who is noticing some reclaim labels with values <20? If not, this could be a hint of what's wrong. Minimum label should be 20...

@Crotalus - We are checking min_mass in SyncMassLabel in Prop.lua, and only propagating mass = 0 in the case of self:BeenDestroyed(). This seems like a hole to me. What about the cases in between? Could this be where the mystery of the extra labels comes from, this check stopping the BeenDestroyed check even coming through, so the label never vanishes?

**Comment by Viba** [comment]
Yes I saw reclaim values with less than 20.

**Comment by Crotalus** [comment]
Hmm, the check for value always checks the original max value of a reclaim wreck (`if self.MaxMassReclaim >= RECLAIMLABEL_MIN_MASS then...`) so it should never have been propagaded to UI-side in the firstplace.

I'll open up a PR with the current fixes and take it from there.

**Comment by aeoncleanse** [comment]
Any progress @Crotalus ?

**Comment by Crotalus** [comment]
The PR at https://github.com/FAForever/fa/pull/1630 fixes the jumparound, haven't been able to reproduce lingering labels with that version though. @Viba, how was the latest version working for you?

**Comment by aeoncleanse** [comment]
Put 4 Sorian AI vs each other on a 10k map and you'll see it eventually.

**Comment by Viba** [comment]
Still ok, besides the "dead labels" lingering around.

**Comment by aeoncleanse** [comment]
@Crotalus any passing thoughts about what's causing the lingering labels, and the labels with <filter mass?

**Comment by TheKeyBlue** [comment]
Well labels with <filter mass, are mostly from reclaim that used to have more mass. 
So reclaim that has damaged or has been partly reclaimed. (this is one of the causes, don't know if others exist)
Reclaim with >filter mass gets added to the Reclaim list. Apparantly they only check for MaxMassReclaim of a prop and not actual remaining reclaim.
https://github.com/FAForever/fa/blob/287276db8ef4db691da8f54ba477e77583666695/lua/sim/Prop.lua#L122

**Comment by aeoncleanse** [comment]
How does the UI update itself to know what the reclaim value is after damage/partial reclaim? I thought that the code you linked there was the only place the sim communicates with the UI. :/

**Comment by TheKeyBlue** [comment]
So the function of the link i gave you: SyncMassLabel. Is indirectly called on prop creation , OnDamage and OnDestroy. That function checks if the MaxMassReclaim of the prop (so reclaim at prop creation) has enough mass to pass through the filter. If so then the new data is added to Sync.Reclaim.

So the new reclaim value is also sent through Sync.Reclaim.
But because we only check for the original mass value of the prop to decide if we need a label for it, we get labels with below filter values.

Now i'm wondering how Sync.Reclaim gets emptied? (i barely know much about how exactly Sync works)
Because if it doesn't happen. Then you would have old data in this Sync.Reclaim list, which could be an issue, because : 

See these 2 pieces of code: 
https://github.com/FAForever/fa/blob/1d234e5351b1b35ad1bcea202b3d4db0ca09c6f8/lua/UserSync.lua#L61
https://github.com/FAForever/fa/blob/develop/lua/ui/game/reclaim.lua#L11

So if Sync.Reclaim doesn't provide the data in the correct order in the for loop (link 1) then it could be that old data overrides new data(link2). (no idea yet if such a thing is possible at all)

**Comment by aeoncleanse** [comment]
Perhaps we should consider storing all this data using EntityID as the key? That way, when OnDestroy is called, we can do Sync.Reclaim[UID] = nil if it's killed or < limiter.

**Comment by TheKeyBlue** [comment]
Nvm all the talk about old data. Sync.Reclaim only has the data for one OnSync() call. 
So that theory doesn't hold at all.

**Comment by aeoncleanse** [comment]
OK. So, where are the UI labels held? Must be a cumulative pool. How is it emptied?

**Comment by Viba** [comment]
https://github.com/FAForever/fa/blob/develop/lua/ui/game/reclaim.lua#L103-L104

**Comment by aeoncleanse** [comment]
OK so that suggests the affected labels are there because the entity they note is not being removed from the Reclaim global table.

**Comment by Exotic-Retard** [comment]
i would also look at the zoom level affecting reclaim labels. it seems to me that if sths not showing zooming in or out helps, but i cant really prove it :/

**Comment by Viba** [comment]
That was for previous versions. Now the problem is only reclaim labels that are staying even for wrecks that have been reclaimed.

**Comment by Exotic-Retard** [comment]
no im talking about a bug with the latest version: when sth dies be zoomed in, press crtl shift and reclaim view doesnt appear for it, then zoom out and it does, somehow.
https://puu.sh/sBvNw/920a600b3f.jpg
http://puu.sh/sBvNN/51fcc3b682.jpg

after which zooming in again to the max doesnt make it go away.

likewise it seems that a wreck wont appear on the list until we zoom in if we are zoomed out, at least sometimes.

**Comment by aeoncleanse** [comment]
We'll deal with the fake labels first as those are the bigger issue.

**Comment by Crotalus** [comment]
A bit busy atm so haven't kept tabs on FAF development the last weeks but lingering labels are still unsolved? I'll take a quick look

**Comment by aeoncleanse** [comment]
If  you're looking, take a close look at deploy/fafdevelop to see what's been tried/attempted

As you can see, this PR attempts the issue with more hammer than scalpel, just rewriting the whole sync comms approach. If the same error happens here, then I know it's the UI-side screenview code at fault, but I have no clue how one might fix that.
