### ISSUE TITLE
Battleship, cruiser patrol / scan radius

### ISSUE THREAD

**Issue by speed2CZ** [FAForever/fa#1629]
I've seen with Cybran and Sera battleship, if something gets close to their range when they are on a patrol, they persuade the target way beyond the patrol route.

Same goes for Sera curiser, it had same patrol as the battleship

Some example:
https://puu.sh/rW0AG/b2f00f4b61.png

**Comment by zlo-faf** [comment]
Are you sure it does not just chase something?
It could even be an air unit

**Comment by MrRowey** [comment]
@Tagada14 Please close if not something that needs looking into :)

**Comment by speed2CZ** [comment]
If it hasnt been fixed, it needs looking into, other units don't do that. I still got the screenshot.
![ForgedAlliance_2016-10-26_09-54-16](https://user-images.githubusercontent.com/10947024/141366610-7d8b4b58-13ad-479b-960d-e962b1eed4bc.png)

**Comment by MrRowey** [comment]
> 
> 
> If it hasn't been fixed, it needs looking into, other units don't do that. I still got the screenshot. ![ForgedAlliance_2016-10-26_09-54-16](https://user-images.githubusercontent.com/10947024/141366610-7d8b4b58-13ad-479b-960d-e962b1eed4bc.png)

Ok nice the image link above was broken so nice to have this image to show the issues

**Comment by MrRowey** [comment]
@Garanas can this be close with recent changes ?

**Comment by Garanas** [comment]
No, the issue is still there. I'm not sure how the guard return radius is adjusted, but it feels like the weapon range is added to the return radius. And that makes it a very, very large return radius. We'd need to experiment with it, maybe even try making it negative.
