### ISSUE TITLE
Investigate 'Pose Update' logs

### ISSUE THREAD

**Issue by aeoncleanse** [FAForever/fa#163]
INFO: CWldSession::DoBeat() unknown entity id (0x2ff00bb4) supplied in a pose update.

This message with different ids pops up in logs constantly. It is found as a string inside ForgedAlliance.exe but I'd like to know what it means, why it happens, whether it's important, and if we can stop it spamming the logs.

**Comment by Sheeo** [comment]
Resolved with #497
