### ISSUE TITLE
Cluster reclaim labels

### ISSUE THREAD

**Issue by micheljung** [FAForever/fa#1631]
I propose that we cluster reclaim labels. In the current implementation, when zoomed out, the whole map is just laced with labels. There's no chance you can tell where the real big chunks are.

For it to work we need to know the current zoom level and the visible area. We then build an internal grid whose cell size depends on the zoom level and merge reclaimable mass within that cell. Even cooler would be if the label's size reflected the amount of mass in each grid.

I'm not yet sure how this affects performance; building the grid would surely cost some, but then there would be way less rendering to be done.

And it would make the reclaim labels much more readable.

**Comment by Crotalus** [comment]
Anyone grabbing this issue can use this as reference, clustering of labels with k-means algorithm, in this case they were clustered in circles.

https://github.com/FAForever/fa/commit/3ab0a8ab3cc726e10b786b0b5199fa029b45c859

Should be relatively straightforward to change to squares / boxes instead using a quadtree.

**Comment by aeoncleanse** [comment]
Is it possible to just use the pixel grid as your grid? Then just say if any two labels would overlap by >0.5 icon size, merge them?

**Comment by micheljung** [comment]
While that would still be better than the current situation, it'd still be a jungle.
Let me poorly illustrate:
![image](https://cloud.githubusercontent.com/assets/1864183/19729477/6666effa-9b97-11e6-9c28-f9c6d85f3778.png)

**Comment by aeoncleanse** [comment]
For me, the trick would be making this smooth. It would have to slowly split out the most distant tag in a smooth, non-stepped manner as you zoomed in.

**Comment by MrRowey** [comment]
@Garanas Either this can Be looked at / just Integrate the Advanced Reclaim Info mod ?

**Comment by MrRowey** [comment]
@Garanas The Advanced Reclaim Info Ui mod is one of the most Downloaded Ui mods is a Must-have. The Mod Adds a Box next to the Income Pannle that shows how much mass/Reclaim is in View of the Camera,
 and it makes Higher mass Value Large and a different colour and makes the 10 mass smaller so it is easy to see 
 
![Untitled-2](https://user-images.githubusercontent.com/20344151/141365199-68bb6763-eab0-42de-896b-329ff59d2df0.png)

**Comment by Garanas** [comment]
I can integrate that.

**Comment by MrRowey** [comment]
@Garanas cant you add one of them link thing to close this when the other thing is intergrated

**Comment by Garanas** [comment]
I'm going to experiment with the clustering code of Crotalus.

**Comment by Garanas** [comment]
Closing this in favor of #4085 , where I'll be writing up a draft for a new implementation for reclaim labels all together.
