### ISSUE TITLE
Harbinger reclaiming on patrol behaviour

### ISSUE THREAD

**Issue by Zockyzock** [FAForever/fa#1632]
Can we please make them behave like SCU/ACU when on patrol/attackmove?

Prioritize enemies, only reclaim if no enemies are there. Planned for next balance patch.

**Comment by aeoncleanse** [comment]
Tested. It, along with Sparky, already behaves the same way an ACU does.

**Comment by speed2CZ** [comment]
Why would we want this on a sparky?

**Comment by aeoncleanse** [comment]
Just an observation. It's either that, or it ignores enemies completely...

**Comment by Exotic-Retard** [comment]
i would suggest sparky prioritize reclaiming over trying to fight something with its dinky gun
