### ISSUE TITLE
Mercies circle very long before landing

### ISSUE THREAD

**Issue by Zockyzock** [FAForever/fa#1633]
Please just make them behave like other planes when it comes to landing. Planned for next balance patch.

**Comment by Exotic-Retard** [comment]
a most trivial change:
`        MinAirspeed = 0,`
(from 10)
#BalanceTerroristsInvadingAgain
#WhatWouldYouDoWithoutUs

**Comment by aeoncleanse** [comment]
PR?

**Comment by aeoncleanse** [comment]
Blaugh, that's really... Not right.
