### ISSUE TITLE
Trees immune to aoe

### ISSUE THREAD

**Issue by CookieNoob** [FAForever/fa#1635]
trees dont get destroyed by 
chicken groundfire
t3 bomber (cybran)
t3 arty (sera)
ahwassa
Billy Nuke
...
why was that introduced??

t3 UEF arty and Mavor destroy trees still, so something is bugged.

**Comment by aeoncleanse** [comment]
It wasn't introduced. If there is a difference from before, I have no idea what could be causing it.

**Comment by CookieNoob** [comment]
I will post a replay in the evening.

It was like this not only since this patch, I am not 100% sure when it started unfortunately.

**Comment by Crotalus** [comment]
This is probably something that's always been this way, especially Seraphim stuff is a bit sloppy due to being the expansion race. 

Unless the weapon also is issuing a DamageArea with 'Force' type, trees won't get touched.

(the usual case of blaming everything broken on the latest patch ;) )

**Comment by CookieNoob** [comment]
I am sure that the trees got destroyed by cybran strats and ahwassa before... I am not sure when it broke, but it was not always like this. I cant test it atm but I will try with the original game when I am back home and check it there.

> (the usual case of blaming everything broken on the latest patch :) )

I didnt do that :)
> It was like this not only since this patch, I am not 100% sure when it started unfortunately.

**Comment by CookieNoob** [comment]
I tested it again and I could not reproduce everything for some reason...
5336248
All units kill the trees if they only fire long enough on them. Sera arty, Ahwassa, all death explosions dont kill trees (except acu nuke). Cybran strat was able to kill the trees (even though the range was quite small). I also tested the ahwassa in the original game and it didnt kill trees, so I guess you're right and it is because of the sloppy expansion race stuff.

**Comment by aeoncleanse** [comment]
Since the only way to fix this would be to add an expensive lua overwrite of the AOE code, like we do for Nukes, I'm closing this issue.

**Comment by Exotic-Retard** [comment]
is it the force property that knocks trees over?
`
            DamageArea( self, pos, self.DamageData.DamageRadius - 1, 1, 'Force', true )`

**Comment by aeoncleanse** [comment]
@Exotic-Retard Where do you propose we add this, and what example?

**Comment by Exotic-Retard** [comment]
there are a few. for some reason its listed twice in here: https://github.com/FAForever/fa/blob/develop/lua/terranprojectiles.lua#L101
but just mashing these into seraphimprojectiles OnImpact should do.

**Comment by aeoncleanse** [comment]
Ah I see. So simply adding this into any projectile that does AOE that we want to be hitting trees should have this added?

**Comment by aeoncleanse** [comment]
@JaggedAppliance @CookieNoob I'd like a list of bombs which should blow trees to matchsticks but don't. Even better, a PR making the fix as ER describes.

**Comment by CookieNoob** [comment]
looks like the entire OnImpact() function is missing for sera projectiles, so we need to add more than just this line... more like the entire function.

**Comment by aeoncleanse** [comment]
That's not possible... They must have the function, because they must inherit it, surely???

**Comment by CookieNoob** [comment]
yes but they dont have it in the projectile file as the UEF projectiles.

**Comment by CookieNoob** [comment]
weaons which still need fixing are:
seraphim t4 nuke
seraphim ahwassa bomb
seraphim ahwassa air crash
UEF billy nuke
cybran soulripper aircrash
cybran t2 arty
aeon czar air crash

**Comment by Exotic-Retard** [comment]
tiny request would be on the sera t4 nuke is to apply the force damage at the same time the actual damage of that radius is applied so it spreads with the explosion! please.

**Comment by MrRowey** [comment]
@Garanas I don't think they will be immune to AoE much longer after your Chat

**Comment by MrRowey** [comment]
@Garanas didnt you make it so tree were affected by aoe ?

**Comment by Garanas** [comment]
Yes - this is fixed.
