### ISSUE TITLE
"hide old maps" button not working

### ISSUE THREAD

**Issue by CookieNoob** [FAForever/fa#1640]
when you host a game and have the checkbox "hide old map versions" (or whatever it is called) in the map selection window checked, it does exactly nothing. This is not only since the last patch like this.

**Comment by Uveso** [comment]
Old Maps are identified by a fixed blacklist.
You can add old maps here:
https://github.com/FAForever/fa/blob/develop/etc/faf/mapblacklist.lua

**Comment by CookieNoob** [comment]
are you kidding me???

I will add the maps but wtf

**Comment by speed2CZ** [comment]
no, but once you mix it we can call it a gg :D
