### ISSUE TITLE
Handle map and mod blacklisting server-side

### ISSUE THREAD

**Issue by aeoncleanse** [FAForever/fa#1642]
Using manually updated files is daft. We could really use a way for mods to block maps and mods for all users. I'm thinking pass the lists into lobby somehow, if possible?

**Comment by CookieNoob** [comment]
would be sufficient to make the game lobby check if there is a map with the same name and then check the version, if it is old (i.e. there is a map with the same name and a higher version), hide the map.

**Comment by speed2CZ** [comment]
having it server side would require the server to detect that there is a new version in  the vault and offer downloading it when hosting, else you could end up with your map "magically" disappearing from the list

**Comment by speed2CZ** [comment]
or even better, automatically check all your maps and suggest update

**Comment by CookieNoob** [comment]
I already suggested that https://github.com/FAForever/client/issues/418 got more or less ignored

**Comment by MrRowey** [comment]
@Justify87 Doesn't this already happen now ?

**Comment by Sheikah45** [comment]
No there is no map or mod blacklist low side. The only thing the server does is hide maps from vault searches. This has nothing to do with the game refusing to load the map or mods.

Basically you can still play with hidden maps and mods if you already have them downloaded.

**Comment by Garanas** [comment]
I do not think this is something we'd want to have. We should only blacklist mods / maps that somehow interfere with the eco system of FAF. As an example, blacklisting the Nvidia fix after we added it to the base game repository. 

I'm closing this for now.
