### ISSUE TITLE
reclaiming opponent building being build

### ISSUE THREAD

**Issue by shalkya** [FAForever/fa#1645]
how to proceed : 
- opponent start a building
- opponent either takes all engie building and make them assist 1 engie already building; or takes all engie but one (that we will call "lead engie"), and makes them assist the "lead engie" then makes "lead engie" stop building.
- order engineer to reclaim the building, or send an attack move (patrol move might work too)

if the reclaim is stronger than the build speed, the building will have 0 hp, but will still be build and reclaim. This is effective way of draining opponent economy into your.

https://gist.github.com/shalkya/295e8ffe38f2e85578f46ea7e95d2472
replay is : 5339688

also you can assist an opponent building, this require lot of energy, it looks like when you try to convert something into your. there is a bar filling up (and restarting when full) but nothing happens. (apart of wasting lot of energy)

**Comment by HUSSAR-mtrela** [comment]
I noticed something similar when a few Cybran hives are reclaiming own building and other Cybran hives are trying to repair it. This causes a lot of wasted resources and the building is flickering between 0 and 1 HP.
