### ISSUE TITLE
caption of "do you want to download map" window wrong

### ISSUE THREAD

**Issue by CookieNoob** [FAForever/fa#1648]
The window is named "Do you want to download the mod" instead of "map"...

**Comment by micheljung** [comment]
What's that window anyway? Does it close the close the game and restart it?

**Comment by CookieNoob** [comment]
I will post a screenshot
![wrong_caption](https://cloud.githubusercontent.com/assets/21953792/19825459/becfe6ea-9d79-11e6-9b80-938f3d7b42c6.PNG)

it should be "Downloading Map" instead of "Downloading Mod"

**Comment by micheljung** [comment]
ah, wrong repository then, `fa` is for game code, this is `client`

**Comment by CookieNoob** [comment]
well no one reads that there xD

**Comment by micheljung** [comment]
And no one fixes it here :D

**Comment by CookieNoob** [comment]
xD well at least someone saw it
