### ISSUE TITLE
incorrect implementation of aeon tmd fix

### ISSUE THREAD

**Issue by Exotic-Retard** [FAForever/fa#1650]
so whoever put it in clearly only decided that the aeon tmd was worth changing.

since the update contains changes to the projectile, notably adding gravity to it, the aeon cruiser and battleship have now got useless tmd.
honestly i am quite surprised no one bothered testing those.

put in correct tmd blueprint values into those two as well.

also this would apply to any aeon tmd weapon, but i think thats those 3 are the only ones that have it.
any modded units with aeon tmd also have this issue.

**Comment by aeoncleanse** [comment]
https://github.com/FAForever/fa/pull/1651
