### ISSUE TITLE
Lobby - Ping/CPU

### ISSUE THREAD

**Issue by speed2CZ** [FAForever/fa#1652]
Currently the ping bar is shown only if the ping is above 500ms, but the desciption above says `Ping/CPU`.
https://puu.sh/s0A8r/bbec25f4de.png
People especially newbies under 1000 ratings  often think that the shown CPU bar is player's ping and kick them for no reason.

Can we have this seperate, there should be enough space in the lobby for that. Or any other solution?

**Comment by aeoncleanse** [comment]
We could make the str dynamic so it only mentions ping when over 500?

**Comment by TheKeyBlue** [comment]
I'll try to make something for this. (and try to fix Ping while i'm at it too then)

**Comment by aeoncleanse** [comment]
Just make it dynamic str, it's a 5 minute fix.

**Comment by aeoncleanse** [comment]
Split into two columns as of 3680
