### ISSUE TITLE
Auto-Overcharge toggles from on to off without notifying player (Stops working)

### ISSUE THREAD

**Issue by aeoncleanse** [FAForever/fa#1655]
When:
- One builds a PStorage
- The ACU is given any upgrade

**Comment by shalkya** [comment]
just did some test, i couldn't reproduce the bugs.
(both after e storage and upgrade)

**Comment by speed2CZ** [comment]
Then it is something else, but this bug exists, keep it open

**Comment by Justify87** [comment]
#1369

**Comment by aeoncleanse** [comment]
d8d35c71958ebc0eacbcfb312aabdb3b267e4ad3
