### ISSUE TITLE
advanced Lobby option are carried over when swiching the map

### ISSUE THREAD

**Issue by CookieNoob** [FAForever/fa#1666]
The options that are set in the lobby are kept even though the new map doesnt support the option. I.e. hosting flooded tabula rasa with civilians, then swich to an ultimate map without civs will make the script think that civilians are wanted on the map (and thus crash it).

**Comment by TheKeyBlue** [comment]
Is this desired behaviour or not? (the saving of chosen options)
Do we want to lose all our set up options when switching map that doesn't use those options?
Or do we want them to be saved like now so they'll be the same when we switch back?
Do we want to keep the same settings when a new map uses similar options or do they need to be set to default again?

Btw you can probably avoid the crashing by using different names for similar options.
i.e. automex -> automexHilly etc. 
And the set options will be map specific.
Or simply having a table with each map that says which feature is supported and then use the table to skip not available options without checking the (should be non-existant) option.

But even if you can avoid it, this is a good moment to decide the preferred lobby behaviour. (which I will try to code when decided upon)

**Comment by CookieNoob** [comment]
> Is this desired behaviour or not? (the saving of chosen options)
I think the options cause different things on different maps, thus they should not be saved when you swich to another map.

> Do we want to lose all our set up options when switching map that doesn't use those options?
I would reset all advanced options to the defaults

> Do we want to keep the same settings when a new map uses similar options or do they need to be set to default again?
The problem here is that the map options vary (i.e. map 1 has 3 options to adjust reclaim, map 2 has 4) and by going out of the expected range there, some stuff is called with wrong arguments. I can put a check for the validity in the script (i.e. check if the value satisfies min <= X <= max) that would solve that.
The other thing with similar options is: reclaim option 1 can be 2 t1 tanks on one map and 3 experimentals on the next one...

> Btw you can probably avoid the crashing by using different names for similar options.
i.e. automex -> automexHilly etc. 
yea I could just remove the unused part of the script of the maps and add the validity checks, that would definetly do the trick

> But even if you can avoid it, this is a good moment to decide the preferred lobby behaviour. (which I will try to code when decided upon)
I would make it non-persistent when you change the map (only the advanced options though)

**Comment by duk3luk3** [comment]
Clearely what we need is a standardized set of default advanced options (lol) that all map scripts are required to support or ignore without crashing and per-map advanced advanced options that don't show up in the map scripts of any other maps.

> swich to an ultimate map without civs will make the script think that civilians are wanted on the map (and thus crash it).

Isn't this strictly speaking a bug in the ultimate map script?

**Comment by CookieNoob** [comment]
I can add a check if the options are supported on the map and ignore those that arent. But even if an option is supported, when you swich the map, the option will keep its value even if this value is outside of the supported range. I.e. you set civs on option 4 and then swich to a map with only 2 options. The value is not reset to the maximum value of the option.

Adding this, or making it ignore the unused options isnt a big problem, since I am reviewing all ultimate maps atm anyway. However I think the advanced options (besides regrowing trees, dynamic spawns* and mirror mex) should not be persistent since they are different from map to map.
*even this is different for the presets...

**Comment by duk3luk3** [comment]
Yeah, options need to be reset to a default value if they are outside the supported values of the map.

**Comment by CookieNoob** [comment]
I think the options that are not there should be reset entirely then too :)

**Comment by duk3luk3** [comment]
I'd say they shouldn't be sent to the map script if the map is launched, but a user would expect them to still be set to the same value if they go back to the map they had selected it on or another map where the option is available.

**Comment by CookieNoob** [comment]
yea I agree

**Comment by aeoncleanse** [comment]
We only want to stop persisting options if the 'Advanced' stuff you're on about is unique to the adaptive maps.

**Comment by TheKeyBlue** [comment]
I'm with aeoncleanse. 
All 'Advanced' map specific options should be erased when you change the map.
That seems to be the cleanest option to me. And will not create any confusion for anyone.
