### ISSUE TITLE
Reveal civilians not working for all players

### ISSUE THREAD

**Issue by CookieNoob** [FAForever/fa#1667]
[5378209-CookieNoob.zip](https://github.com/FAForever/fa/files/573579/5378209-CookieNoob.zip)

to see what I mean: open the cheat menu and swich through the different players. Some will see the civs in the middle and some dont.
Able to see them: 3, 4, 5, 6, 7, 8, 13, 14, 15 
Not able to see them: 1, 2, 16

**Comment by aeoncleanse** [comment]
@Crotalus any clues?
