### ISSUE TITLE
Increase the timer for kick in case of DC

### ISSUE THREAD

**Issue by speed2CZ** [FAForever/fa#1669]
Some people kick after 50 seconds but it usually takes a bit longer to restart router, your connection, whatever. So you might find yourself in a situation where you would successfully reconncted into the game, but someone already kicked you.

**Comment by Crotalus** [comment]
An idea would be to change kick into a "vote to kick" instead in these cases. And when enough players (50-75%) have voted yes, the player is kicked by all.

**Comment by Justify87** [comment]
Should an observer participate in the voting?

**Comment by aeoncleanse** [comment]
no

**Comment by Exotic-Retard** [comment]
do dead people start counting as obs? if not, do we let them vote anyway? i kinda think that they shouldnt vote but eh

**Comment by aeoncleanse** [comment]
Dead should = no vote
