### ISSUE TITLE
Problem by rating delayed until last player leaves game

### ISSUE THREAD

**Issue by GrotheFAF** [FAForever/fa#1673]
Example: in a ladder game #5392494 my oponent was afk and was still showing as ingame long after the game ended... so no counting, no points. I played a 2nd ladder after that (I lost) ... after that the first game was finally closed. The points of the 2nd lost game are overwritten by the late acounting of the first (613 -> 605 -> 624) ... admitted a rather rare case.

Shouldn't games be counted and reported wenn fa anounced 'game over' ? (and not when last one left fa)

**Comment by MrRowey** [comment]
@Garanas i would assume this has more to do with the server than the FA repose as it's about reporting game completion ?

**Comment by Garanas** [comment]
@Askaholic is there something we can do to fix this?

**Comment by Askaholic** [comment]
The server will rate the game as soon as the `GameEnded` gpgnet command is received from all players in the game. So if the game wasn’t rated then it is because the server didn’t receive that message.

**Comment by Askaholic** [comment]
Oh lol this is a super old issue. I think both of the issues described here are already fixed on the server.

**Comment by MrRowey** [comment]
@Askaholic So i can go ahead and close this issues then pretty much if they are fix on the server
