### ISSUE TITLE
ML, UEF T2 Radar (and maybe more) visual bug

### ISSUE THREAD

**Issue by speed2CZ** [FAForever/fa#1674]
So this happened to monkey lord
https://puu.sh/sdA4S/da418f2ea8.png

current develop version

**Comment by aeoncleanse** [comment]
I checked all intel myself... Looking at the game now, Spiderbot doesn't show this at all :/ How did you make it happen?

**Comment by aeoncleanse** [comment]
Scratch that... lol. So it happens as a flicker, and only when you're out of power. Well now, that's a new one...

**Comment by shalkya** [comment]
had cloack appear on cybran t1 radar (but maybe already fix then ?)

**Comment by aeoncleanse** [comment]
Yup, same as this. Need to decide if this is worth a hotfix, or just leave it as it's a minor visual glitch

**Comment by shalkya** [comment]
i would be for fixing it's kind of weird in game
