### ISSUE TITLE
Wrong ACU regen for observers

### ISSUE THREAD

**Issue by speed2CZ** [FAForever/fa#1676]
explained with pictures here: http://forums.faforever.com/viewtopic.php?f=3&t=13462

**Comment by aeoncleanse** [comment]
Right, so logging in the UI creation part I find that the problem is here: local regen = UnitData[info.entityId].regen or bp.Defense.RegenRate

In observers, the UnitData[info.entityId].regen is nil, where is it kept up to date for other players.

**Comment by aeoncleanse** [comment]
So, UnitData table, filled by self.Sync.regen, appears to be on a per-army basis... It doesn't get filled for observers... :/

**Comment by aeoncleanse** [comment]
Correction. Each army gets their own, even AIs and civilians.

**Comment by aeoncleanse** [comment]
In this area, most of the things reported in the UI are reported in 'info', where info = GetRolloverInfo(). This returns the following table structure:

```
INFO: {
INFO:   armyIndex=0,
INFO:   blueprintId="uel0001",
INFO:   customName="FAF_IceDreamer",
INFO:   energyConsumed=0,
INFO:   energyProduced=20,
INFO:   energyRequested=0,
INFO:   entityId="0",
INFO:   fuelRatio=-1,
INFO:   health=12000,
INFO:   massConsumed=0,
INFO:   massProduced=1,
INFO:   massRequested=0,
INFO:   maxHealth=12000,
INFO:   nukeSiloBuildCount=0,
INFO:   nukeSiloMaxStorageCount=1,
INFO:   nukeSiloStorageCount=0,
INFO:   shieldRatio=0,
INFO:   tacticalSiloBuildCount=0,
INFO:   tacticalSiloMaxStorageCount=1,
INFO:   tacticalSiloStorageCount=0,
INFO:   userUnit={ <metatable=table: 163C03E8>
INFO:     _c_object=userdata: CScriptObject* at 11B1AA9C = [CScriptObject at 0x205DE400]
INFO:   },
INFO:   workProgress=0
INFO: }
```

So the information generally passed to all players for UI use is controlled by the engine. The regen overlay was added at a later date by FAF, and uses the Sync tables, but that information is only available on a per-army basis, almost certainly to prevent the kind of cheating that would be possible if the UI layer had access to all player's Sync data. This idea is reinforced in that it's per army, not per team (An ally doesn't get data on all their allies from Sync).

**Comment by CookieNoob** [comment]
@aeoncleanse another issue to close
