### ISSUE TITLE
cloaking frigates

### ISSUE THREAD

**Issue by CookieNoob** [FAForever/fa#1678]
![cloak_on_frigates](https://cloud.githubusercontent.com/assets/21953792/20231531/df263fb8-a862-11e6-8ca0-8196984ad4e2.PNG)

was a ladder match, id: 5402224

I thought this animation was for cloaking units, not for jamming...

**Comment by aeoncleanse** [comment]
It is. This bug seems to be caused by the low-power state cycling all forms of intel and accidentally triggering it. I have a fix in the works, but I need a little more time :/

**Comment by aeoncleanse** [comment]
Fixed with 3663
