### ISSUE TITLE
Mass storages can be build inside of upgraded factories

### ISSUE THREAD

**Issue by CookieNoob** [FAForever/fa#1679]
using the "auto-caping" function, it is possible to build mass storages on those sides of mexes where upgraded factories are linked for adjecency.
![hq_factory_storage_adjecency](https://cloud.githubusercontent.com/assets/21953792/20237092/f89e3b56-a8c8-11e6-9402-03135ea81ec8.PNG)
![support_factory_storage_adjecency](https://cloud.githubusercontent.com/assets/21953792/20237093/fa3622ee-a8c8-11e6-9550-6ec0fd87cc7c.PNG)

works for both, HQ and support factories.
ID: 5404143

**Comment by Crotalus** [comment]
Oh, that's interesting. Seems weird that engine would allow build orders on already built tiles.

**Comment by aeoncleanse** [comment]
I cannot reproduce this. Getting it to place the order is easy, but in all my tests it never ia able to build the conflcted storage.

**Comment by CookieNoob** [comment]
well I posted the id of the replay where exactly this happens... try it with an upgraded factory which is adjecent to a mex (it has to be upgraded I think, Tokyto did the testing, maybe ask him)

**Comment by aeoncleanse** [comment]
Tried with T2/T3 HQ, nothing :/

**Comment by Viba** [comment]
Could not reproduce on setons, but I could do it on same map as in the replay, Hilly plateau ultimate.
![image](https://cloud.githubusercontent.com/assets/3510353/20346309/0388abbc-ac04-11e6-864a-f0bd2f561661.png)

**Comment by aeoncleanse** [comment]
In all cases the factory was completed before you queued the storage?

**Comment by Viba** [comment]
Yes, factory first, storages later.

**Comment by Viba** [comment]
Managed to replicate bug with all faction HQ:s. Replay: http://content.faforever.com/faf/vault/replay_vault/replay.php?id=5422002

**Comment by aeoncleanse** [comment]
I have no clue what this is... @Crotalus

**Comment by speed2CZ** [comment]
Well, it's not just storages, pgen as well https://puu.sh/stmdo/8c50260505.png

**Comment by aeoncleanse** [comment]
OK so... we very much have a deeper issue here...

**Comment by speed2CZ** [comment]
replay replay.faforever.com/5456222
Tokyto_'s (who else's :D ) base at min7+-

**Comment by duk3luk3** [comment]
Does this also happen with *built* T2 facs, as opposed to *upgraded* ones?

**Comment by aeoncleanse** [comment]
Good question. Very good question.

**Comment by TheKeyBlue** [comment]
So apparantly AI is abusing this a lot too.
http://forums.faforever.com/viewtopic.php?f=3&t=14170#p145058

I guess this means we atleast broke something?

**Comment by aeoncleanse** [comment]
7cfebbfad59e98e0c54a547b76f44cfa554876e9
