### ISSUE TITLE
Auto-storages creates performance problem

### ISSUE THREAD

**Issue by anihilnine** [FAForever/fa#1684]
Select 300 engies 
Holding shift, double rightclick a t2 mex to auto create storage
Every time you release and press shift it will chug (a lot)

The problem also happens on smaller amounts of engies in normal game situations

**Comment by Crotalus** [comment]
Yes, each engineers create 4 orders so with 300 engineers you will have 1200 orders. CommandGraph is lagging when showing these amounts of orders. Same effect as the lag when doing split attack / move with hundreds of scouts.

For some reason IssueBuildMobile doesn't like an array of units as an argument, they doesn't group up as expected :/

**Comment by duk3luk3** [comment]
would this not happen if you selected 300 engies and gave them a command to build storages from a template?

**Comment by aeoncleanse** [comment]
@Crotalus - How easy would it be to only issue the command to unit #1, and have subsequent units be assigned to assist that?

**Comment by anihilnine** [comment]
@duk3luk3 - no you dont get the lag if you queue it up manually. It's actually impossible for you to manually assign multiple engies to build the same thing at the same place, and not have it as a grouped order.

**Comment by duk3luk3** [comment]
OK so hopefully there's a way to make it a grouped order...

**Comment by aeoncleanse** [comment]
```    Rebuild = function(self, units)
        local rebuilders = {}
        local assisters = {}
        local bpid = self.AssociatedBP

        for _, u in units do
            if u:CanBuild(bpid) then
                table.insert(rebuilders, u)
            else
                table.insert(assisters, u)
            end
        end

        if not rebuilders[1] then return end
        local pos = self:GetPosition()
        IssueBuildMobile(rebuilders, pos, bpid, {})
        if assisters[1] then
            IssueGuard(assisters, pos)
        end
    end,```

@Crotalus - This code is used to rebuild wrecks. It seems the build command should take an array, no?

**Comment by aeoncleanse** [comment]
OK so this works in some ways: 

`Callbacks.CapMex = function(data, units)
    local units = EntityCategoryFilterDown(categories.ENGINEER, SecureUnits(units))
    if not units[1] then return end
    local mex = GetEntityById(data.target)
    if not mex or not EntityCategoryContains(categories.MASSEXTRACTION * categories.STRUCTURE, mex) then return end
    if mex:GetCurrentLayer() == 'Seabed' then return end

    local pos = mex:GetPosition()
    local cappers = {}
    local assisters = {}
    local msid = LetterArray[units[1]:GetBlueprint().General.FactionName]..'b1106' -- The identity of the storage we'll build
    for _, u in units do
        if u:CanBuild(msid) then
            table.insert(cappers, u)
        else
            table.insert(assisters, u)
        end
    end
    
    if not cappers[1] then return end
    
    IssueBuildMobile(cappers, Vector(pos.x, pos.y, pos.z-2), msid, {})
    IssueBuildMobile(cappers, Vector(pos.x+2, pos.y, pos.z), msid, {})
    IssueBuildMobile(cappers, Vector(pos.x, pos.y, pos.z+2), msid, {})
    IssueBuildMobile(cappers, Vector(pos.x-2, pos.y, pos.z), msid, {})
    IssueGuard(assisters, cappers[1])
end`

However, for some reason it doesn't issue the same orders to all the cappers. Instead of them all constructing one at a time, it issues storage 1 to capper 1, 2 to 2, etc
