### ISSUE TITLE
Display mean in rank hover

### ISSUE THREAD

**Issue by muellni** [FAForever/fa#1687]
Isn't the hover on the rank supposed to show your mean score? It shows `Your rating is rank +/- variance` instead of  `Your rating is mean +/- variance` (see screenshot).
![screenshot from 2016-11-15 16-43-40](https://cloud.githubusercontent.com/assets/569476/20312267/2365d9d4-ab53-11e6-80fd-efb0819c57ba.png)

**Comment by duk3luk3** [comment]
https://github.com/FAForever/fa/blob/3de785a9523ba4b048e0ee7061c14dffb4abdb3f/lua/ui/lobby/lobby.lua#L875

Change `PL` to `MEAN`

**Comment by Exotic-Retard** [comment]
while this is all good that we are showing your actual rating in the description, most people dont know what that mean is so it could be confusing. do we need to show that info at all?

**Comment by micheljung** [comment]
People can be educated

**Comment by TheKeyBlue** [comment]
Maybe specifically mentioning Trueskill will help with that?
So people can find out what the numbers mean, without having to ask someone.

**Comment by duk3luk3** [comment]
Fix'd
