### ISSUE TITLE
assassination game starts with all players in one team

### ISSUE THREAD

**Issue by CookieNoob** [FAForever/fa#1692]
settings were optimal balance and manual autoteams, game launched and all players were allied.
[5435303.zip](https://github.com/FAForever/fa/files/601806/5435303.zip)
http://fafafaf.bitbucket.org/#5435303

**Comment by TheKeyBlue** [comment]
my guess is that it has something to do with this '_Evil autoteams voodoo_' :
https://github.com/FAForever/fa/blob/develop/lua/ui/lobby/lobby.lua#L3354
Haven't tested why it is even there and why it sets to 2 (team1) instead of 1 (team -).
