### ISSUE TITLE
Round the new Trueskill mean rating shown in lobby tooltip

### ISSUE THREAD

**Issue by aeoncleanse** [FAForever/fa#1698]
Probably we want it to be INT

**Comment by duk3luk3** [comment]
Did someone merge my PR without testing it?

**Comment by Justify87** [comment]
There is no math.round() and there is only one data type for numbers in lua. Only option is to truncate all trailing numbers with a custom function. Or just use math.ceil() like I did.

**Comment by duk3luk3** [comment]
what's wrong with ```math.floor(thenumber + 0.5)```? Or the more general

```lua
function round(num)
    if num >= 0 then
        return math.floor(thenumber + 0.5)
    else
        return math.ceil(thenumber - 0.5)
    end
end
```

which we'd probably want since rating can be negative.

**Comment by aeoncleanse** [comment]
merged it into an experimental test branch, yes. Only way to test it (Made sure it didn't crash offline, but that just loads all trueskill stats == 0) was to push this branch to live testing.


Probably about time to add math.round into the lua... @duk3luk3 how do we go about adding a fundamental function like that that can be used anywhere?

**Comment by Justify87** [comment]
Best way would be to get the databse to round the value. A calculated column or a view should do the trick,

**Comment by aeoncleanse** [comment]
harder to make that happen than a game update.

**Comment by Justify87** [comment]
Why? Does mysql not allow to simply add the column? I just googled. The term is "Generated Columns" for mysql. And the point the player.MEAN value to that column.

**Comment by duk3luk3** [comment]
There's really no need to do that in the database.

@aeoncleanse just call the function `math.round`. Monkey-patching is magic. See also https://github.com/FAForever/fa/blob/develop/lua/system/utils.lua

**Comment by duk3luk3** [comment]
Oh lol, it's already in there. I rest my case.

**Comment by aeoncleanse** [comment]
Indeed. We shall just use that then! Justify, duk3, anyone fancy a PR? ;)

**Comment by Justify87** [comment]
duke was faster, also I'm currently migrating my OS ^^

**Comment by aeoncleanse** [comment]
Duk3 handled this.
