### ISSUE TITLE
lots of spam in game.log

### ISSUE THREAD

**Issue by CookieNoob** [FAForever/fa#1701]
the game log contains a lot of useless lines, i.e. 
info: ura0102 = false (857 times)
info: url0105 = false (915 times)

info: --OnSelectionChanged
info: notmixed (2833 times)

[game.zip](https://github.com/FAForever/fa/files/614940/game.zip)

game was unmodded, replay desyncs after 10 min maybe its related.
replay id: 5469332

**Comment by aeoncleanse** [comment]
A quick grep for some of those terms doesn't turn anything up. Sure you don't have locally edited files somewhere?

**Comment by CookieNoob** [comment]
yes, I also searched for that in the FA repo and didnt come up with anything (or there would be a PR already). The list of UI mods is in the game.log but they usually dont spam like this. I only edit the maps (that game is on seraphim glaciers, so an original map) and the santa mod (which wasnt active that game). So all files are original files.

**Comment by aeoncleanse** [comment]
Well, one of the UI mods is what caused this. Not much we can do here...

**Comment by CookieNoob** [comment]
ok

**Comment by CookieNoob** [comment]
I grep'd my mod folder and the "on selection" stuff comes from Selection Deprioritizer...
