### ISSUE TITLE
Renaming Random to Random - Unbalanced

### ISSUE THREAD

**Issue by TheKeyBlue** [FAForever/fa#1714]
According to PC Tokyto there are some people who think `Random` will balance their game.
So he suggested to change it to `Random - Unbalanced`

PC Tokyto wrote: 
> I have a little suggestion, how about renaming Random balance to Random - Unbalanced? it's kinda confusing now... ppl picking it thinking it will balance.

**Comment by micheljung** [comment]
Yes, but. I'm sure that nobody ever wants a random, unbalanced game. So instead of renaming it, wouldn't it be smarter to actually implement balancing?
Otherwise wer are just providing a useless button, and may as well just remove it.

**Comment by TheKeyBlue** [comment]
We have Optimal Balance and Flexible balance for that now.
And its not really a useless option. It will probably not be used much, but thats not the same as being useless.
