### ISSUE TITLE
Hotbuild keys as default for new profiles

### ISSUE THREAD

**Issue by speed2CZ** [FAForever/fa#1722]
So as from the last dev call we've decided to truely enable hotbuild by setting keys for it's layout.

In addition to that it would be good to get rid of most of the debug keys since casual players don't need them, and move the important ones somewhere where they can't be hit by an accident (like log window).

**Comment by CookieNoob** [comment]
it would be nice to also integrate the keybinding overlay mod of washy at the same time, so that players actually see which button is linked to which key

**Comment by Exotic-Retard** [comment]
already planned! it was discussed in the dev conf

**Comment by CookieNoob** [comment]
awesome! It wasnt uploaded when I posted this

**Comment by speed2CZ** [comment]
well I'm not gonna do that, I'll just change the keys
