### ISSUE TITLE
Lobby: RandomMap is OddvsEven instead of None or Manual

### ISSUE THREAD

**Issue by TheKeyBlue** [FAForever/fa#1723]
When playing on a random map, the lobby uses OddvsEven whenever you choose either None or Manuel for AutoTeams.
Which is a little strange.

https://github.com/FAForever/fa/blob/develop/lua/ui/lobby/lobby.lua#L1451

**Comment by MrRowey** [comment]
Closing as not planned as this is a small Use case of using the in lobby random map button. Can be reopened if someone wants to tackle it.
