### ISSUE TITLE
share until death is full share instead and changes back to share until death again

### ISSUE THREAD

**Issue by CookieNoob** [FAForever/fa#1734]
the game 5549900 was set as share until death in the lobby and supreme scoreboard shows share until death. However when a player dies, his base got transfered like in a full share game.

no errors in the log when the first player dies

later there is one
```
WARNING: Error running lua script: ...rogramdata\faforever\gamedata\lua.nx2\lua\shield.lua(225): Game object has been destroyed
         stack traceback:
         	[C]: in function `GetArmy'
         	...rogramdata\faforever\gamedata\lua.nx2\lua\shield.lua(225): in function <...rogramdata\faforever\gamedata\lua.nx2\lua\shield.lua:224>
```

later on it seems that the game became share until death again xD

[5549900-Heaven.zip](https://github.com/FAForever/fa/files/659705/5549900-Heaven.zip)

**Comment by TheKeyBlue** [comment]
Well the replay for that game is unavailable..
http://content.faforever.com/faf/vault/replay_vault/replay.php?id=5549900

**Comment by CookieNoob** [comment]
I uploaded it here @TheKeyBlue

**Comment by aeoncleanse** [comment]
This is incredibly dubious... Sounds like someone's abusing a UI mod, this is known to be possible in this scenario...

**Comment by TheKeyBlue** [comment]
Maybe has something todo with this one aswell: FAForever/faf-phantomx#12

Haven't really looked into it too much, myself.

**Comment by TheKeyBlue** [comment]
So this is a shit game that takes ages cause my computer can't handle it...
The main points are that first 2 players (in opposite spots Army 5 and 6) get killed sequentially and their bases are full shared. (so its not 1 player but 2 from different teams, Heaven and Lexus_of_Reality) 
Don't think a UI mod from 1 player can do this. (maybe they both have the same?) 

Other dead players' bases do get destroyed in what looks like true Share Until Death fashion. (Don't know about donated units)

I did notice that the walls of all dead players hadn't been destroyed. 
So they were still alive even after acu death, like how it used to be.

**Comment by Exotic-Retard** [comment]
well game settings are share until death so if someone managed to fullshare thats a pretty nice abuse they have there

or apparently it is, looking in the scenario it has a blank field there but looking at my ui mods it says share until death. i dunno, this whole thing is strange xD

**Comment by TheKeyBlue** [comment]
Okay so if the share options are blank. 
That means the workaround to avoid auto-give from Ecomanager will not be used.
https://github.com/FAForever/fa/blob/develop/lua/aibrain.lua#L686
(investigate if they were the only players using it?)

So I see a couple of possible solutions:
- We make it so nil-value for shareOption is treated the same as ShareUntilDeath, everywhere the share settings are checked/used in the code.
- We make the lobby auto fill in the default values of non-set options at launch.
(atm using default options can give you nil values instead of the real default value)

I'm in favour of trying the 2nd solution. As it will also avoid map/mod scripts having to account for  nil valued options.

**Comment by CookieNoob** [comment]
I would also favor the second suggestion, it makes sense to set all unset options to their default and thus send a complete set of options.

**Comment by TheKeyBlue** [comment]
Okay I asked both players whose bases got fullshared about their setups.
Heaven uses ecomanager, so his base got auto-gifted.
Lexus had manually gifted his base to someone before he died. (no ui mods used)

Heaven (host) also provided his Game.prefs and that contained a non existant share option:
`GameOptions = {
                        Share = 'yes',`
Maybe that was a valid option value in the old share implementation?
Whatever it was, i think we can fix it by checking in the lobby just before game launch if all options are correctly set. (so not nil and a valid value)
