### ISSUE TITLE
land factory having plane into the queue (bug assist factory)

### ISSUE THREAD

**Issue by shalkya** [FAForever/fa#1736]
https://cdn.discordapp.com/attachments/113788948362297346/260183116373557248/bug.jpg

this is a screenshot of that is a bit old.

but there is some bug related to assist between factory, having some unit added to queue without ordering them.

**Comment by CookieNoob** [comment]
this can happen to other types of factories too. I saw a navy factory with t1 arty in the queue and idling because it was unable to build it. That was a while ago so I doubt that the replay easy to find for that.

**Comment by Garanas** [comment]
Issue is quite rare, I have nothing to reproduce it with. Closing it accordingly.
