### ISSUE TITLE
change mass storage icons to be generic structure instead

### ISSUE THREAD

**Issue by Exotic-Retard** [FAForever/fa#1738]
make it look like this: http://puu.sh/sUFsk/1168847a23.jpg

this is a balance-ish suggestion tbh but who cares right

you simply need to change the storage icon, and one dds texture, which i have already done so you can use that.
then make the blueprint change (its a one character change!):
    StrategicIconName = 'icon_structure_mass',
the thing is that when i tried to make a pr i couldn't get it to work nicely. in eq we add an entirely new strategic icon and set it to that. but icecreamer wouldn't allow such a dirty hack im sure

relevant commit: https://github.com/Ithilis/Equilibrium/commit/e7d526e7df3ca39bb9eb2dd4d4bc28f137775180

#CantStopTheBalanceTerrorists
#KeepUpWithEquilibrium

**Comment by speed2CZ** [comment]
That's breaking consistency of icons, it's T1 and should look like that.

**Comment by Exotic-Retard** [comment]
whats up with energy storage then

**Comment by JaggedAppliance** [comment]
I like it, it's annoying when the lines from storages make mexes look t3 instead of t2 at certain zoom levels.

**Comment by speed2CZ** [comment]
if e storage doesnt have it then yeah fine, I can live with that
