### ISSUE TITLE
Pause button is not enabled on Enhancement tab

### ISSUE THREAD

**Issue by HUSSAR-mtrela** [FAForever/fa#1739]
The Pause button should be enabled and functional on Enhancement tab of an ACU/SCU as it is for other tabs: Construction/Selection

![image](https://cloud.githubusercontent.com/assets/11665978/21329275/d986051e-c605-11e6-8cd7-6ac93ae16972.png)

**Comment by HUSSAR-mtrela** [comment]
@Uveso I think you fixed similar issue for sub nukes which were missing the Pause button in previous FAF patches so maybe you can fix this bug as well.

**Comment by aeoncleanse** [comment]
Enabling functionality is done in Construction.lua easily enough, but I couldn't get it to show the pause texture...

**Comment by aeoncleanse** [comment]
e21557a2cbce63c9345ab297247e0db124f61576
