### ISSUE TITLE
tml having issue firing

### ISSUE THREAD

**Issue by shalkya** [FAForever/fa#1740]
https://gist.github.com/shalkya/98000e97d3d4b859feb3be0f75373d49 : this replay 
from 9min to 11min30, i've missile in the clip, and i give target, and for an unknown reason it doesn't want to fire. I need to re-set the attack order so it fire, and enqueuing attack order wasn't working.

i've tried to replicate in a test, but wasn't able (used adjacency to T1/T2 mexx)

**Comment by aeoncleanse** [comment]
Determined to be the fact that it was directly targeting a dead (upgraded) blip. As the fix for that has been abandoned, nothing we can do here.
