### ISSUE TITLE
Using Home or End to manipulate camera causes error in reclaim overlay

### ISSUE THREAD

**Issue by aeoncleanse** [FAForever/fa#1741]
Not a huge issue, but needs resolving

**Comment by aeoncleanse** [comment]
Solution is probably to set LabelPool = {} when those buttons are pressed. They appear to renew the entire UI view, destroying all label elements in the process. @Crotalus any ideas?

**Comment by MrRowey** [comment]
@Garanas as i know you have been looking at the reclaim labels not sure if this might be something you want to check

**Comment by 4z0t** [comment]
Afaik it works fine now
