### ISSUE TITLE
False positives in mod dependency warning

### ISSUE THREAD

**Issue by aeoncleanse** [FAForever/fa#1742]
Notified by Softly. Perhaps linked to #909?

**Comment by HUSSAR-mtrela** [comment]
We should not accept any issues that do not have steps to reproduce or at least detailed description with logs. Otherwise, how can we even start to fix this kind of issues.

**Comment by Uveso** [comment]
fixed: https://github.com/FAForever/fa/commit/39d2564258b6f6b52e78ad9d33ff10cf5773438d#diff-27fd02128c9ee2ff18ab92aed036704e
Can be closed!
