### ISSUE TITLE
Integrate Hotbuild into and redesign Options menu

### ISSUE THREAD

**Issue by aeoncleanse** [FAForever/fa#1745]
So this went wrong first time. This time we're going to get it right. This issue is to track the primary feature of the next patch: A redesigned Options menu.

- Transform it from GPG styling to FAF styling, same as almost all of the rest of the game
- The options available to players will be re-examined. If something is wanting to be off by default, it shouldn't have been integrated. Such things will be removed or default to on.
- A new tab will be introduced called FAF Additions. This will contain all our custom options
- A new tab will be introduced called Hotkeys. This will be the current F1 menu with changes. F1 will still open Options at this tab by default.
- Top of the tab will be a search bar allowing people to find A: Which thing a key is bound to and B: Available options for binding. Switching between the two modes can either be intelligent or via two checkboxes
- The binding system will be reworked if possible to allow two key-combinations to be bound to any given action. This will allow the binding of, for example, "H" and "Shift-H" for Hydros for much smoother gameplay interaction.
- There will be three buttons at the bottom: "Defaults", "Hotbuild" and "Clear All". Each will have a confirmation dialogue to go through to guard against accidental resets.

@HUSSAR-mtrela @Crotalus @Uveso - Any volunteers?

**Comment by HUSSAR-mtrela** [comment]
@aeoncleanse yes, I'm interested in working on this UI enhancement but first I would like to finish PR#1420 and integrate SupremeScoreBoard mod.

**Comment by HUSSAR-mtrela** [comment]
@aeoncleanse do you mean something like this for the item about Transforming options from GPG styling to FAF styling? Note option tabs are temporary missing.

![image](https://cloud.githubusercontent.com/assets/11665978/21582821/4de95c60-d035-11e6-8024-b0ba43d57893.png)

**Comment by aeoncleanse** [comment]
Sort of. I mean we need to use the same visual style as the rest of the lobby, the existing F1 menu, etc. Remember the styling tools you used for Unit Manager, for the popup window and big buttons etc? That stuff.

**Comment by HUSSAR-mtrela** [comment]
Oh the styling from lobby... hmm most of UI element in the game use skinable bitmaps that are based on selected faction instead of black/gray popup window with just colored border so I think the options window should also use the same skinable bitmaps otherwise it would not look as part of rest of game UI.

**Comment by MrRowey** [comment]
@Garanas Hotbuild  is integrated years ago using f1 in game can could be closed

**Comment by HUSSAR-mtrela** [comment]
@MrRowey  yes, most of these features were implemented in my PR#1907
