### ISSUE TITLE
Can not repair restricted units

### ISSUE THREAD

**Issue by speed2CZ** [FAForever/fa#1753]
```WARNING: Unit.OnStartBuild() Army 1 cannot build restricted unit: <LOC uab1104_desc>Mass Fabricator```
This happens when you try to repair a restricted unit, it also cancels all other commands on that unit.
@HUSSAR-mtrela do you know what could be done?

**Comment by HUSSAR-mtrela** [comment]
@speed2CZ first of all, how is there a damaged unit that was restricted? I mean first, someone must have built that restricted unit which should not be possible if was restricted. Was this unit already built when a map was loaded? In other words, I need some more info before we should try to fix this because it looks like expected behavior unless I'm missing something.

**Comment by speed2CZ** [comment]
Where I go, coop follows me like a shadow :D
Yes, it's a case in missions where you either have few units already spawned, or you are given them, but can't build them yet. 
This example is from Aeon mission 3, you have few T2 mass fabs in your base (base starting damaged) and you can't repair them because of the restriction.

**Comment by HUSSAR-mtrela** [comment]
oh i see... we can fix this by excluding repair command from restriction system. I wonder if we added a handling of capturing restricted units. I'm not sure what should have happen then. @aeoncleanse should we allow capturing of restricted units or should they blow up when capturing is finished?

**Comment by speed2CZ** [comment]
Good that you mentioned it :D the game deletes them :| which is not the best especially for campaign where enemy often has some advantage, for example in form of more units unlocked, and if you capture some, then just disappear.

**Comment by aeoncleanse** [comment]
IMO if you choose to restrict a unit, that should be _it_. No exceptions. Restricted units spawned by the map should immediately be destroyed leaving no reclaim.

**Comment by duk3luk3** [comment]
@aeoncleanse only in competitive games.

**Comment by duk3luk3** [comment]
This is about campaign and coop, where you will have restricted units that you have to work with...

**Comment by aeoncleanse** [comment]
Oh. Does the campaign "You can't use this yet" use the same system as the lobby "We don't want this ever" ?

**Comment by HUSSAR-mtrela** [comment]
@speed2CZ for co-op missions you can adjust restrictions in scenarios scripts based on human and/or AI players such the enemy AI has advantage over human player, for example

```
for _, player in ScenarioInfo.HumanPlayers do
     ScenarioFramework.AddRestriction(player,categories.xas0204)  -- Aeon Submarine Hunter
end
```
IMO, a player (either AI or human) should never get access to units (if they were restricted for that player) by capturing these units from other player or getting them via diplomacy transfer. That's the whole point of restriction system.

**Comment by speed2CZ** [comment]
Well that's not how the campaign was designed, it was always meant for player to not be able to build those units himself, but if given or captured, he could use them.
So for campaign I need player to be able to control units that are restricted.

**Comment by HUSSAR-mtrela** [comment]
@speed2CZ can you tell me in which mission, a player is given a restricted unit at some point after starting the game?

**Comment by speed2CZ** [comment]
Fastest one for testing would be SCCA_Coop_A03 - Aeon Mission 3 - High Tide
Right at the start you're given damanged base. Mass fabs are restricted so you can't repair them

**Comment by speed2CZ** [comment]
Fixed by https://github.com/FAForever/fa/commit/309f0fd376d8068bbb9691bd5d439022ed107537
