### ISSUE TITLE
reclaiming while shooting with ACU

### ISSUE THREAD

**Issue by shalkya** [FAForever/fa#1754]
replay : 5590367

sera acu : http://imgur.com/8RgTTcd

**Comment by HUSSAR-mtrela** [comment]
we should fix this by disabling primary weapon if an unit is reclaiming something in addition to checking if units is building and repairing. Also I think that we should keep secondary weapons such as AA on Cybran SCUs enabled all the time even if the unit is reclaiming, building, and repairing. @aeoncleanse do you agree?

**Comment by Exotic-Retard** [comment]
interestingly, the acu apparently already does this for building: 
```
    OnPrepareArmToBuild = function(self)
        WalkingLandUnit.OnPrepareArmToBuild(self)
        if self:BeenDestroyed() then return end

        self:BuildManipulatorSetEnabled(true)
        self.BuildArmManipulator:SetPrecedence(20)
        self:SetWeaponEnabledByLabel(self.rightGunLabel, false)
        self.BuildArmManipulator:SetHeadingPitch(self:GetWeaponManipulatorByLabel(self.rightGunLabel):GetHeadingPitch())
    end,
```
im not sure if its called for reclaiming but i would guess not, we could move this function into something like PrepareBuildArm and then call that for OnStartReclaim OnStartCapture OnStartBuild ect.
also overcharge and autoovercharge should be affected, and currently only normal acu gun is.

**Comment by aeoncleanse** [comment]
There is a total fix for all these issues in BlackOps ACUs. Building, reclaiming, OCing... All of it. Someone just needs to go in and port the code.

**Comment by duk3luk3** [comment]
Where is that code?

**Comment by aeoncleanse** [comment]
Should be hooked into defaultunits acu or command class

**Comment by aeoncleanse** [comment]
OK, not for ALL of them. It should fix most of the "Shooting while doing" things.

**Comment by aeoncleanse** [comment]
5823fdaa162ed96afa253e85add301a1e69a2dda
