### ISSUE TITLE
Auto-OC is too strong

### ISSUE THREAD

**Issue by aeoncleanse** [FAForever/fa#1761]
Forum discussion here: http://forums.faforever.com/viewtopic.php?f=67&t=13504

Consensus is that it's a bit too good, and needs a bigger differentiation from manual OC. I suggested a RoF nerf which was well received.

**Comment by JaggedAppliance** [comment]
It's under discussion, pr coming soon™

**Comment by CookieNoob** [comment]
so what happens when you just fired an auto OC and then disable the auto function to manually overcharge? Will it be 3.3 sec reload or 5 sec? And which one is the desired behavior?

**Comment by aeoncleanse** [comment]
I'm not sure. And I think 3.3, since at that point you're definitely doing very manual things :)
