### ISSUE TITLE
Rename bones in Novax

### ISSUE THREAD

**Issue by aeoncleanse** [FAForever/fa#1770]
The Base unit has two bones named with a typo (missing "r"):
- ConstuctBeam01 and ConstuctBeam02
Correct names are:
- ConstructBeam01 and ConstructBeam02

I'd like this to be corrected in the model.

**Comment by supcomBlackMaster** [comment]
solved

**Comment by aeoncleanse** [comment]
Nice, I'll make a PR soon with the model.
