### ISSUE TITLE
fix firebeetle hitbox

### ISSUE THREAD

**Issue by CookieNoob** [FAForever/fa#1775]
t1 pds and other units have a really hard time hitting them. In a game yesterday a beetle ran through two sera t1 pds which were missing 100% of the shots (no micro involved). I will add a replay where this is reproduced later.

**Comment by Exotic-Retard** [comment]
can we have the replay (and minute too) where this is not reproduced as well please

**Comment by CookieNoob** [comment]
ups sorry I forgot that yesterday... I will upload it when I am back home (in ~9 hours)

**Comment by CookieNoob** [comment]
http://content.faforever.com/faf/vault/replay_vault/replay.php?id=5649313
test with sera pd is from min 2 on. On another attempt this wasnt reproducable, so it doesnt always happen that the pd misses.

It also happened in a real game (Soviets beetles in UnicornNoobs' base at the end of the game):
http://content.faforever.com/faf/vault/replay_vault/replay.php?id=5637319

**Comment by Tokyto** [comment]
If you want to reproduce it, try gunships, they do tend to miss a lot of shots.

**Comment by CookieNoob** [comment]
its not a nerf, its a bug fix @Tokyto.
