### ISSUE TITLE
Error with T3 Loyalist stuns

### ISSUE THREAD

**Issue by PerfectWay** [FAForever/fa#1778]
Destruction T3 Cybran bots Loyalist puts stun on air units. Tested on T3 bombers and scouts.

**Comment by Exotic-Retard** [comment]
duplicate bug report; fixed in https://github.com/FAForever/fa/pull/1764

**Comment by Exotic-Retard** [comment]
apparently the issue is still present in current develop version, dunno whats up with that tbh.

**Comment by aeoncleanse** [comment]
Dunno if it's IN develop. FAFdevelop?

**Comment by PerfectWay** [comment]
All current version (FAF, FAF beta & FAF develop) has this issue

**Comment by aeoncleanse** [comment]
Right. As of present, it should only be in fafbeta. It is. It works.
