### ISSUE TITLE
Implement "DisconnectPeer"

### ISSUE THREAD

**Issue by micheljung** [FAForever/fa#1781]
Currently, admins can close a player's game. This only works if a player's client implements this functionality - which is quite easy to remove.
The "right" way to do this is to tell all other players to drop the connection to a specific player.

The game should therefore accept a new "DisconnectPeer" message and drop the connection to the specified peer.
Right now, we are not able to implement our own incoming messages. Let's see if we can use an existing message, or otherwise use this hacky thing that uses the chat command as a trojan horse.

**Comment by Sheeo** [comment]
This [already exists](https://github.com/FAForever/fa/blob/develop/lua/ui/lobby/lobby.lua#L653), it will accept a GPGnet message of the usual format.

Regardless; it's not actually relevant whether this is implemented in the game or not -- the key point is just that other peers should be told to disconnect from the peer being kicked. Therefore; this should just be implemented at the level of the ICE-adapter, if it isn't already. I suggest we move this issue there.

**Comment by Garanas** [comment]
This feature is quite niche - doesn't seem to be worth the effort. Closing as not planned.
