### ISSUE TITLE
T1 arty (zthuees) wont fire at targets

### ISSUE THREAD

**Issue by Viba** [FAForever/fa#1782]
Not sure if limited to zthuees or applicable to other factions as well, I've seen it happen twice now with zthuees.

The zthuees are in range of targets but don't start firing, they don't start firing even if they are given a manual command to fire at the targets, they just stand still.

Happened for me with a T2 mex, in the replay 5687044 it happens around min 7-8 at south air base.

Could be something from the recent ground fire changes or the attack move changes that prevent arty from running into PD?

**Comment by Garanas** [comment]
The replay has aged but I suspect what happened is that the Zthuee was at an angle it could physically not fire from (e.g., the barrel can not make the required arc). This is known for all artillery (especially t1 artillery on ramps) and for t2 artillery on Dual Gap (when someone builds artillery in the valley to shoot back onto the hills).

@Tagada14 I suspect the reasoning above is the intended balance, if so - please close this issue. 
@Viba If this the problem still persists then please make a new issue with a more recent replay ID that is still available to investigate further.

**Comment by Tagada14** [comment]
It's partially because of balance (eg. you don't want the arties to be able to shot up on very high cliffs) but also perhaps engine limitations? I am not sure tbh.

**Comment by Garanas** [comment]
That is a physical limitation - the engine can not compute an angle (which is constrained) in combination with the velocity of the projectile (which is constrained).

**Comment by MrRowey** [comment]
Closing for Now Balance Team Can reopen if needed
