### ISSUE TITLE
Resizing window problem with small screen resolution

### ISSUE THREAD

**Issue by speed2CZ** [FAForever/fa#1784]
If you have screen resolution like 1366x768 and have the game running in windowed mode, there's this glitch where everything is shifted a bit:
![TeamViewer_2017-01-24_13-45-45](https://user-images.githubusercontent.com/10947024/171603742-c8a27357-3852-4896-a807-41052446c4bb.png)

Cursor is cleary not over the ACU icon and the minimap is glitched as well, all reclam labels missplaces. This also prevents you from seeing build qeue.

I found there are these console commands available from supcom wiki http://supcom.wikia.com/wiki/Console_commands
```
wnd_DefaultCreateHeight Minimum initial window height
wnd_DefaultCreateWidth Minimum initial window width
wnd_MinCmdLineHeight Minimum command line height
wnd_MinCmdLineWidth Minimum command line width
wnd_MinDragHeight Minimum drag-resize height
wnd_MinDragWidth Minimum drag-resize width 
```
and setting `wnd_MinDragHeight` to say 600 (by default it's 768) solves this problem when you resize the window

**Comment by Garanas** [comment]
are there consequences to setting that value to 600?

**Comment by speed2CZ** [comment]
I havent encountered any back then

**Comment by MrRowey** [comment]
@Garanas is this something we still need or can it be closed off ?
