### ISSUE TITLE
Yotha spawns energy storm on transfer

### ISSUE THREAD

**Issue by speed2CZ** [FAForever/fa#1789]
Using this function https://github.com/FAForever/fa/blob/develop/lua/ScenarioFramework.lua#L219-L234
to give yotha causes it to spawn energy storm. It is used in missions.

Can you solve it @aeoncleanse since you've made the last change to it so you know what it does and needs

**Comment by aeoncleanse** [comment]
6f262ffb94f92a0bb10ef22a26ee998b6ce171d4
