### ISSUE TITLE
PDs not firing while in range of target

### ISSUE THREAD

**Issue by Justify87** [FAForever/fa#1790]
Youtube comment of a player: "targeting under FoW is broken, for example T2 arty not firing at Fatboy even not with manual targeting (had to ground fire) , same for corsair not targeting T2 mex under FoW, it is just terrible﻿"

Video evidence:
https://youtu.be/ZDvpQL7HLvU?t=15m

Will add replay ID later

**Comment by speed2CZ** [comment]
This is caused by targed priorities, the PD is locked on the unit, since it rotates towards its targed before the targed as actually in range, so it can start firing as soon as possible.

Units have higher priority than buildings

**Comment by aeoncleanse** [comment]
Having now investigated myself, speed2 is correct. This is a quirk of the targeting system. Manually retargeting fixes it.
