### ISSUE TITLE
Infinite Error loop when spawning Engineer for Civ AI

### ISSUE THREAD

**Issue by aeoncleanse** [FAForever/fa#180]
WARNING: Error running '/lua/ui/game/gamemain.lua:OnBeat': c:\github\fa\lua\ui\uiutil.lua(358): attempt to concatenate local `filespec' (a nil value)
         stack traceback:
         	c:\github\fa\lua\ui\uiutil.lua(358): in function `UIFile'
         	c:\github\fa\lua\ui\game\avatars.lua(284): in function `Update'
         	c:\github\fa\lua\ui\game\avatars.lua(780): in function `v'
         	c:\github\fa\lua\ui\game\gamemain.lua(494): in function <c:\github\fa\lua\ui\game\gamemain.lua:492>

**Comment by ChrisKitching** [comment]
Can't reproduce.

**Comment by aeoncleanse** [comment]
Go on strip mine or any other map with civs.  Spawn that team an engie.

**Comment by aeoncleanse** [comment]
This is the error:

WARNING: Error running '/lua/ui/game/gamemain.lua:OnBeat': e:\github\fa\lua\ui\uiutil.lua(338): attempt to concatenate local `filespec' (a nil value)
         stack traceback:
         	e:\github\fa\lua\ui\uiutil.lua(338): in function `UIFile'
         	e:\github\fa\lua\ui\game\avatars.lua(284): in function `Update'
         	e:\github\fa\lua\ui\game\avatars.lua(780): in function `v'
         	e:\github\fa\lua\ui\game\gamemain.lua(519): in function <e:\github\fa\lua\ui\game\gamemain.lua:517>

That was from the most recent build of release/3641. Clearly it's moved, but it's still here!

**Comment by Sheeo** [comment]
Reproduced successfully from documented STR

**Comment by speed2CZ** [comment]
Fixed long time ago ^^ closing
