### ISSUE TITLE
Suggestion: A way to remove AFK hosted games

### ISSUE THREAD

**Issue by Androish** [FAForever/fa#1801]
Problem: People hosting games and going afk "forever", "louring" people into the game until full before they realize host is afk. This can happen to new people after the first batch has left.

I suggest we have a button inside a hosted lobby that pings the Host in the client with a sound. Maybe a sound a minute for 5 minutes, and if he does not Say anything in the game lobby in those 5 minutes game gets dehosted.(or some other action) Also suggest that the button is not possible to press if the host has spoken in the lobby x minutes ago. (to prevent abuse)

That way the first group of people can easily and without mod intervention make sure it does not happen to anyone else.  (yes this just happened to me)

**Comment by Garanas** [comment]
This problem is still present, but I do not see a reason to add a feature to combat it either. I know of no other game that does this - you can foe the host and not join his / her game in the future.
