### ISSUE TITLE
EXCEPTION_ACCESS_VIOLATION at address 0x0213d267

### ISSUE THREAD

**Issue by aeoncleanse** [FAForever/fa#1803]
EXCEPTION_ACCESS_VIOLATION (0xc0000005) at address 0x0213d267
attempted to read memory at 0xfed48cd4

Program : C:\ProgramData\FAForever\bin\ForgedAlliance.exe
Cmd line arguments : /mean 1472.02 /deviation 174.531 /country US /init init_faf.lua /numgames 27 /log C:\ProgramData\FAForever\logs\game.log /nobugreport /savereplay gpgnet://localhost/5746485/lineranch.SCFAreplay /gpgnet 127.0.0.1:50342

Callstack:
Unknown symbol (address 0x0213d267)
Unknown symbol (address 0x0213d5fb)
Unknown symbol (address 0x0213d660)
Unknown symbol (address 0x0213de5d)
Unknown symbol (address 0x0212e001)
BaseThreadInitThunk + 31 bytes ((Unknown)(0) + 0 bytes)
RtlSubscribeWnfStateChangeNotification + 1076 bytes ((Unknown)(0) + 0 bytes)
RtlSubscribeWnfStateChangeNotification + 1023 bytes ((Unknown)(0) + 0 bytes)

Last 100 lines of log...

info: Can't find texture "" -- trying fallback.
warning: GetResource: Invalid name ""
info: Can't find texture "" -- trying fallback.
debug: Loading module '\000/lua/ui/game/strategicicons.lua\000'
debug: Loading module '\000/lua/ui/dialogs/disconnect.lua\000'
info: playable area coordinates are { 4, 56, 252, 200 }
info: Offmapareas are {
info: { x0=-96, x1=352, y0=-44, y1=56 },
info: { x0=-96, x1=352, y0=200, y1=300 },
info: { x0=-96, x1=4, y0=56, y1=200 },
info: { x0=252, x1=352, y0=56, y1=200 }
info: }
debug: Loading module '\000/lua/ui/game/scoreaccum.lua\000'
info: playable area coordinates are { 4, 56, 252, 200 }
info: Offmapareas are {
info: { x0=-96, x1=352, y0=-44, y1=56 },
info: { x0=-96, x1=352, y0=200, y1=300 },
info: { x0=-96, x1=4, y0=56, y1=200 },
info: { x0=252, x1=352, y0=56, y1=200 }
info: }
debug: Loading module '\000/lua/renderselectparams.lua\000'
debug: Loading module '\000/effects/entities/unitteleport01/unitteleport01_script.lua\000'
debug: Loading module '\000/lua/sim/defaultprojectiles.lua\000'
debug: Loading module '\000/lua/sim/projectile.lua\000'
debug: Loading module '\000/lua/defaultantiprojectile.lua\000'
info: Hooked /lua/defaultantiprojectile.lua with /schook/lua/defaultantiprojectile.lua
debug: Loading module '\000/lua/ui/game/rallypoint.lua\000'
debug: Loading module '\000/lua/ui/controls/worldmesh.lua\000'
debug: Loading module '\000/units/ueb0101/ueb0101_script.lua\000'
debug: Loading module '\000/lua/terranunits.lua\000'
debug: Loading module '\000/lua/tarmacs.lua\000'
debug: Loading module '\000/effects/entities/uefbuildeffect/uefbuildeffect02_script.lua\000'
debug: Loading module '\000/effects/entities/uefbuild/uefbuild01_script.lua\000'
debug: Loading module '\000/effects/entities/uefbuildeffect/uefbuildeffect03_script.lua\000'
debug: Loading module '\000/lua/spreadattack.lua\000'
debug: Loading module '\000/units/uab0101/uab0101_script.lua\000'
debug: Loading module '\000/lua/aeonunits.lua\000'
debug: Loading module '\000/effects/entities/aeonbuildeffect/aeonbuildeffect01_script.lua\000'
debug: Loading module '\000/lua/formations.lua\000'
debug: Loading module '\000/lua/ui/game/commandgraphparams.lua\000'
debug: Loading module '\000/lua/ui/game/commandwaypoint.lua\000'
debug: Loading module '\000/lua/ui/game/commandgraph.lua\000'
info: Hooked /lua/ui/game/commandgraph.lua with /schook/lua/ui/game/commandgraph.lua
debug: Loading module '\000/units/uel0105/uel0105_script.lua\000'
debug: Loading module '\000/units/ueb1101/ueb1101_script.lua\000'
debug: Loading module '\000/units/ual0105/ual0105_script.lua\000'
debug: Loading module '\000/units/uab1101/uab1101_script.lua\000'
debug: Loading module '\000/lua/simcallbacks.lua\000'
debug: Loading module '\000/lua/simping.lua\000'
debug: Loading module '\000/lua/selfdestruct.lua\000'
debug: Loading module '\000/lua/simcameramarkers.lua\000'
debug: Loading module '\000/lua/simdialogue.lua\000'
debug: Loading module '\000/lua/simdiplomacy.lua\000'
debug: Loading module '\000/lua/spreadattack.lua\000'
debug: Loading module '\000/units/ueb1103/ueb1103_script.lua\000'
debug: Loading module '\000/units/uel0106/uel0106_script.lua\000'
debug: Loading module '\000/units/uab1103/uab1103_script.lua\000'
debug: Loading module '\000/units/uel0101/uel0101_script.lua\000'
debug: Loading module '\000/lua/sim/blip.lua\000'
debug: Loading module '\000/projectiles/tdfmachinegun01/tdfmachinegun01_script.lua\000'
debug: Loading module '\000/lua/terranprojectiles.lua\000'
debug: Loading module '\000/units/uel0201/uel0201_script.lua\000'
debug: Loading module '\000/effects/entities/debrismisc04/debrismisc04_script.lua\000'
debug: Loading module '\000/lua/genericdebris.lua\000'
debug: Loading module '\000/projectiles/adfquantumdisruptor01/adfquantumdisruptor01_script.lua\000'
debug: Loading module '\000/lua/aeonprojectiles.lua\000'
debug: Loading module '\000/effects/entities/debrismisc09/debrismisc09_script.lua\000'
debug: Loading module '\000/units/uab0102/uab0102_script.lua\000'
debug: Loading module '\000/units/ual0101/ual0101_script.lua\000'
debug: Loading module '\000/lua/formations.lua\000'
debug: Loading module '\000/units/uab1102/uab1102_script.lua\000'
debug: Loading module '\000/units/uaa0101/uaa0101_script.lua\000'
debug: Loading module '\000/units/ueb0102/ueb0102_script.lua\000'
debug: Loading module '\000/units/uab2101/uab2101_script.lua\000'
debug: Loading module '\000/projectiles/adflaserlight02/adflaserlight02_script.lua\000'
debug: Loading module '\000/units/ueb1102/ueb1102_script.lua\000'
debug: Loading module '\000/projectiles/tdfgauss01/tdfgauss01_script.lua\000'
debug: Loading module '\000/projectiles/laserbotterran01/laserbotterran01_script.lua\000'
debug: Loading module '\000/units/ueb2104/ueb2104_script.lua\000'
debug: Loading module '\000/units/uea0102/uea0102_script.lua\000'
debug: Loading module '\000/units/uaa0103/uaa0103_script.lua\000'
debug: Loading module '\000/units/ueb3101/ueb3101_script.lua\000'
debug: Loading module '\000/projectiles/adfgraviton01/adfgraviton01_script.lua\000'
debug: Loading module '\000/units/ueb1105/ueb1105_script.lua\000'
debug: Loading module '\000/units/uab1202/uab1202_script.lua\000'
debug: Loading module '\000/projectiles/aifbombgraviton01/aifbombgraviton01_script.lua\000'
debug: Loading module '\000/units/ueb2101/ueb2101_script.lua\000'
debug: Loading module '\000/projectiles/taarailgun01/taarailgun01_script.lua\000'
debug: Loading module '\000/units/uaa0102/uaa0102_script.lua\000'
debug: Loading module '\000/units/uab2104/uab2104_script.lua\000'
debug: Loading module '\000/projectiles/tdfovercharge01/tdfovercharge01_script.lua\000'
debug: Loading module '\000/units/uea0103/uea0103_script.lua\000'
debug: Loading module '\000/units/ueb5101/ueb5101_script.lua\000'
debug: Loading module '\000/units/ual0201/ual0201_script.lua\000'
debug: Loading module '\000/units/ueb1202/ueb1202_script.lua\000'
debug: Loading module '\000/projectiles/tdfplasma01/tdfplasma01_script.lua\000'
debug: Loading module '\000/projectiles/tifnapalmcarpetbomb01/tifnapalmcarpetbomb01_script.lua\000'
debug: Loading module '\000/projectiles/aaasonicpulse01/aaasonicpulse01_script.lua\000'
debug: Loading module '\000/projectiles/aaasonicpulse02/aaasonicpulse02_script.lua\000'
debug: Loading module '\000/units/ueb0201/ueb0201_script.lua\000'

**Comment by Garanas** [comment]
Lets use #2045 to track this, closing it accordingly.
