### ISSUE TITLE
Sync.FloatingEntityText not working

### ISSUE THREAD

**Issue by aeoncleanse** [FAForever/fa#1806]
The Sync table is meant to take things from the Sim layer and make them accessible in the User layer. For some reason, the FloatingEntityText Sync isn't working. Calling the function in sim works (It's defined in schook/lua/SimSync.lua and adds it successfully to the Sync table that end, but for some reason it never shows up in schook/lua/UserSync.lua. It's especially odd given that the Sync.StartCountdown works fine (For ctrl-k countdown) using exactly the same setup, and that it's possible to just add new things to the Sync table (For example, Sync.Reclaim which we invented for the reclaim overlay, so it is not a case of the engine only syncing a predefined list of entries...

**Comment by aeoncleanse** [comment]
@Crotalus ??? Any ideas?

**Comment by speed2CZ** [comment]
Well adding something to the Sync table can be done from anywhere in Sim layer. If it is in the table then you just need to add to the UserSync.lua what UI function it should call.

**Comment by aeoncleanse** [comment]
Fixed in BlackOps, was an issue that end.
