### ISSUE TITLE
Suggestion/feature: Connectivity overview

### ISSUE THREAD

**Issue by muellni** [FAForever/fa#1820]
Currently you can see your ping to other players using [F11], but often other players get disconnected to each other, the game stops and people are guessing whats going on.

With the upcoming ICE adapter handling P2P connectivity we could exchange information about who is connected to whom using the server, and the client+ice-adapter relay this information to the game. 
IDK if new in-game-UIs and new GPGNetMessages are possible to create, but I'd find this kind of overview very helpful. I came up with some really great UI ideas for that:
![conn1](https://cloud.githubusercontent.com/assets/569476/22752807/2aef9ae4-ee3a-11e6-8e9b-163f2c85fa54.png)
and 
![conn2](https://cloud.githubusercontent.com/assets/569476/22752814/2f9c5b90-ee3a-11e6-9e31-edaed75dda46.png)

**Comment by micheljung** [comment]
Doesn't the connection overview already do this? If not as nice, but using numbers.

**Comment by aeoncleanse** [comment]
Yes, it does.

**Comment by muellni** [comment]
Is there a connection overview who is connected to whom? Which key?

**Comment by aeoncleanse** [comment]
F11. It shows the shownetworkstats overlay top-right.

**Comment by muellni** [comment]
Thx, I'll have a closer look at that.

**Comment by muellni** [comment]
Taking a very close look with my magnifying glass revealed the connectivity matrix indeed. It's very hard to understand for average Joe I think. 
The columns are the player numbers and the entries are packages "in-the-air" I guess.
