### ISSUE TITLE
Unit manager doesn't show all units

### ISSUE THREAD

**Issue by Geosearchef** [FAForever/fa#1824]
![missingunits](https://cloud.githubusercontent.com/assets/5748922/22760568/552c7be8-ee57-11e6-9aab-51a122adb014.PNG)
This happens on a 1920x1080 resolution.

**Comment by Geosearchef** [comment]
Just updated, now I see the t4 sattelite but not the fatboy.

**Comment by Nojoke185** [comment]
they are there - just need to scroll with mouse wheel or the scroll bar to the right
