### ISSUE TITLE
Adjacency problem with missiles

### ISSUE THREAD

**Issue by JaggedAppliance** [FAForever/fa#1843]
Adjacency bonuses for SML, SMD and TML are only applied if the building that gives an adjacency bonus is completed before the missile begins construction. So, if I build a T3 PGen beside a nuke I will only get the adjacency bonus for the next missile that's constructed, the cost of the one currently building will not be affected. This also means that buildings giving adjacency bonuses can be destroyed or reclaimed and still give an adjacency bonus until the current missile is finished.

**Comment by aeoncleanse** [comment]
There is, AFAIK, no way around this, as you cannot reduce the cost of an existing missile build order. It sucks.

**Comment by Exotic-Retard** [comment]
depends on how much hack you are willing to make :D 
you could create an economy production on the silo to act as a virtual adjacency bonus but sounds like dangerous stuff tbh

**Comment by MrRowey** [comment]
close as Duplicate Issue use #3641
