### ISSUE TITLE
unit problems

### ISSUE THREAD

**Issue by blorg123** [FAForever/fa#1844]
there is a problem with units that are modded in FAF.
One of the pros for FAF(for me) is that the AI uses modded units themselves, you don't need to spawn them in for them.
however, certain types of modded units(usually tanks and mechs) don't have animation or firing rates(tank turret does not turn, walker moves even though it's legs aren't, walker can't fire because upper body won't turn, ect.)
vanilla units are not affected, as well as modded in boats and buildings and some other units.
also, unique problem i found while playing my own solo game on the FAF client:
any AI of any type does not appear move past tech 1.
at all.
their factories will upgrade, and the ACU can build T1-3 units/structures, sure, but the names will still say "Tech 1 Land Factory" or something like that.
and finally, units that are changed in the retail ver. of the game with mods(say, you are using experimental wars or total mayhem) will not appear in the FAF ver. of the game.
please note all of this only happens if you use a mod that is not in the "custom game" slot (i.e. BREWlan, total mayhem, etc.)

bai

**Comment by aeoncleanse** [comment]
This happens when the mod has been poorly constructed and not maintained. The unit script crashes when the unit spawns, and everything breaks. You will need to use an updated version of the mod that works with FAF (Example would be BlackOps-FAF V12) or fix the bugs yourself.

**Comment by blorg123** [comment]
o.
