### ISSUE TITLE
aeon tmd diverts friendly missiles

### ISSUE THREAD

**Issue by CookieNoob** [FAForever/fa#1846]
when aeon tmd is under fire from enemy tac missiles and friendly missiles fly over it, these missiles will be diverted as well.

**Comment by aeoncleanse** [comment]
Need confirmation. Code looks like this:

```
if EntityCategoryContains(ParseEntityCategory(self.RedirectCat), other) and myArmy != otherArmy and IsAlly(myArmy, otherArmy) == false then
```

So it's been fixed in FAF in the past...

**Comment by CookieNoob** [comment]
ok yea couldnt reproduce it, strange...
