### ISSUE TITLE
attack order turn into ground fire

### ISSUE THREAD

**Issue by shalkya** [FAForever/fa#1848]
as you can see on this replay, i asked my bomber to attack the engie at the very last moment, right after i don't have radar over the engie anymore. So the attack order on the engie turn into a ground fire order. Previously when it was "return fire" my bomber wouldn't take the attack order into account, and i would realize it. Now my bomber act like it got the attack order, so it's harder to realize that i need to set it to attack another unit.
here is the replay : 5863020 ; it's my first bomber, and it's about its first drop.

**Comment by Garanas** [comment]
The behavior of this has been changed a while back - issue is dated.
