### ISSUE TITLE
hotkey labels don't work on a fresh install

### ISSUE THREAD

**Issue by PhilipJFryFAF** [FAForever/fa#1850]
as long as you have a new game.prefs file without touching the keybinds the hotkey labels won't be displayed

how to reproduce: make a backup of your game.prefs, remove them from your folder, start the game locally and create a new profile and start a game.

no clue how to fix

**Comment by HUSSAR-mtrela** [comment]
@aeoncleanse Is this issue related to your changes to keybinding system or did you ready fixed it in the newkeybindings branch?

**Comment by aeoncleanse** [comment]
Unless I fixed by accident, it's still a problem

**Comment by aeoncleanse** [comment]
@HUSSAR-mtrela as of patch 3680 is this still a problem?

**Comment by HUSSAR-mtrela** [comment]
Well, default game.prefs does not set hotkey bindings because that was added later by FAF. So we can either add hotbuild preset or keep using default preset when creating a new profile.

**Comment by aeoncleanse** [comment]
So hotkey labels ONLY displays for the hotbuild bindings? That makes sense from my observations... 

How hard would it be to have the labels activate for the default bindings too?

**Comment by MrRowey** [comment]
Dated Issue closing for now
