### ISSUE TITLE
Navy HQ bug

### ISSUE THREAD

**Issue by Farmsletje** [FAForever/fa#1860]
Gave my navy HQ to an ally, he gave it back but my support factory couldn't produce t2 or t3 anymore whilest my hq could continue building.

Replay: https://www.dropbox.com/s/6b76g5bkobpn0vu/5884366-Farmsletje.fafreplay?dl=0

Log: https://www.dropbox.com/s/wht8rwx4cfjc4je/forever.log.1?dl=0

**Comment by aeoncleanse** [comment]
dcb5359b6d9ea9ccc00440145eaa4529620fc343
