### ISSUE TITLE
Quick faction choosing

### ISSUE THREAD

**Issue by OCGDFS** [FAForever/fa#1866]
if u join a game (not hosting), u cant choose the faction on top of the ingame lobby anymore. it works after u changed the faction to the right of ur name
![xx](https://cloud.githubusercontent.com/assets/7430874/23612722/c481791a-027c-11e7-96b3-2ca530a5fb6c.png)

**Comment by TheKeyBlue** [comment]
should be fixed in fafdevelop, is it not?
https://github.com/FAForever/fa/issues/1825
