### ISSUE TITLE
Removing units from factory queue cancels progress with 1 left

### ISSUE THREAD

**Issue by aeoncleanse** [FAForever/fa#187]
This is not a problem with 3637, it's been around a long time.

Again from jcv: 
Say you have a buildqueue of 3 resto and 5 asfs, then delete 2 resto from the list to leave 1. The half-built one is canceled, then the build starts again from scratch, rather than just continuing.

I have to say I've not noticed this... If it's true, I think it COULD be a new issue, if not 3636/7, then 3634

**Comment by aeoncleanse** [comment]
I can't replicate this either. Are bugs caused by mods which shouldn't really be being used in the first place meant to be issues here?

**Comment by Sheeo** [comment]
Closing because we never received logs here.
