### ISSUE TITLE
Cybran land factory rolloff bug

### ISSUE THREAD

**Issue by PhilipJFryFAF** [FAForever/fa#1881]
replay id: 5931296
Andyrooooooooos t1 land fac couldn't rolloff engis after the 2nd engi was made
error from the ingame debug window:
```
WARNING: Error running OnStopBuild script in Entity urb0101 at 25f23b08: attempt to use as number a nil value
         stack traceback:
            [C]: in function `VDist2'
            ...data\faforever\gamedata\lua.nx2\lua\defaultunits.lua(840): in function `CalculateRollOffPoint'
            ...data\faforever\gamedata\lua.nx2\lua\defaultunits.lua(828): in function `RollOffUnit'
            ...data\faforever\gamedata\lua.nx2\lua\defaultunits.lua(776): in function `DoStopBuild'
            ...data\faforever\gamedata\lua.nx2\lua\defaultunits.lua(754): in function <...data\faforever\gamedata\lua.nx2\lua\defaultunits.lua:749>
```

no clue how to reproduce or fix it

**Comment by CookieNoob** [comment]
looking at the code that causes the error: https://github.com/FAForever/fa/blob/develop/lua/defaultunits.lua#L840

```
distance = VDist2(vectorObj[1], vectorObj[3], v.X + px, v.Z + pz)
```

where
`vectorObj` is the rally point (the move/whatever order of the factory)
`v.X` is the X component of the roll off point
`px` is the X coordinate of the factory
the only thing that can be nil there is the command (i.e. `vectorObj`)

the values of the rolloff points are properly defined in the blueprint:
https://github.com/FAForever/fa/blob/develop/units/URB0101/URB0101_unit.bp#L342

**Comment by aeoncleanse** [comment]
I bet you any money at all he was running mods.

**Comment by CookieNoob** [comment]
probably some UI mods...

he changed the rally point of the factory in the very same moment when the engy finished though.
