### ISSUE TITLE
Feature: put connectivity window on left side

### ISSUE THREAD

**Issue by b2ag** [FAForever/fa#1889]
Hi,

maybe we should put the connectivity window on the left side of the screen. This way it shouldn't block the main menu (and the exit option).

Br,
b2ag

**Comment by MrRowey** [comment]
@Garanas Close as it Duplicate for #908

**Comment by Garanas** [comment]
I'll close it and keep a tab on the other issue. I think if we'd move it to the bottom of the screen then we have two birds in one catch.
