### ISSUE TITLE
Chronodampener doesn't affect air units

### ISSUE THREAD

**Issue by PhilipJFryFAF** [FAForever/fa#1895]
Not sure since when but in the current faf version the chronodampener on the aeon acu doesn't stun air units anymore.

**Comment by aeoncleanse** [comment]
Correct. This is deliberate, it never made any sense anyway. I let Jagged know this would happen, he was fine with it

**Comment by PhilipJFryFAF** [comment]
Ok then. Was just confused cause it was never mentioned in any changelog.

**Comment by speed2CZ** [comment]
Maybe you just need to read the description and it would start making sense to you :)
https://github.com/FAForever/fa/blob/287276db8ef4db691da8f54ba477e77583666695/lua/ui/help/unitdescription.lua#L328
It is suppose to stun air units as well.

**Comment by aeoncleanse** [comment]
https://github.com/FAForever/fa/blob/develop/changelog.md#balance-2

Uh huh.

**Comment by PhilipJFryFAF** [comment]
nvm then i just used ctrl+f and looked for chrono...

**Comment by Exotic-Retard** [comment]
sphere? why the fuck would you apply it as a sphere? everyone and their dog knows that ranges only make sense as cylinders. this just means units on hills get and advantage for no reason and can be inside the range circle (which is cylindrical) and not be affected
