### ISSUE TITLE
SACU Mass Value

### ISSUE THREAD

**Issue by PhilipJFryFAF** [FAForever/fa#1896]
When using the sacrifice ability of the aeon SACU the mass value that is being used for the sacrifice depends on the unit cost without consideration for added/scrapped upgrades.
Same issue for wrecks left behind after the death of any SACU.

The issue is fixed in EQ if anyone wants to steal some code from there.

**Comment by MrRowey** [comment]
@Tagada14 is this something that is being looked at for the SACU rebalance ?
