### ISSUE TITLE
EXCEPTION_ACCESS_VIOLATION at address 0x00598eec

### ISSUE THREAD

**Issue by JaggedAppliance** [FAForever/fa#1900]
EXCEPTION_ACCESS_VIOLATION (0xc0000005) at address 0x00598eec
    attempted to read memory at 0x000000e4

Program : C:\ProgramData

\FAForever\bin\ForgedAlliance.exe
Cmd line arguments : /cybran /mean 2150.06150056 /deviation 65.7062970066 /players 2 /team 1 

/clan e /init init_ladder1v1.lua /numgames 676 /log C:\ProgramData\FAForever\logs\game.log /nobugreport /savereplay 

gpgnet://localhost/6034034/JaggedAppliance.SCFAreplay /gpgnet 127.0.0.1:49255

Callstack:
	Unknown symbol (address 0x00598eec)
	Unknown symbol (address 0x00409243)
	Unknown symbol (address 0x00409b2b)
	Unknown symbol (address 0x0074a110)

Last 100 lines of log...

info: creating high fidelity terrain
info: creating high fidelity water
info: creating high fidelity 

terrain
info: creating high fidelity water
info: creating high fidelity terrain
info: creating high fidelity water
info: creating high 

fidelity terrain
info: creating high fidelity water
info: creating high fidelity terrain
info: creating high fidelity water
info: 

creating high fidelity terrain
info: creating high fidelity water
info: creating high fidelity terrain
info: creating high fidelity 

water
info: creating high fidelity terrain
info: creating high fidelity water
info: creating high fidelity terrain
info: creating high 

fidelity water
debug: Loading module '\000/projectiles/adfgraviton01/adfgraviton01_script.lua\000'
debug: Loading module 

'\000/projectiles/cdfcannonmolecular01/cdfcannonmolecular01_script.lua\000'
info: creating high fidelity terrain
info: creating high 

fidelity water
info: creating high fidelity terrain
info: creating high fidelity water
info: creating high fidelity terrain
info: 

creating high fidelity water
info: creating high fidelity terrain
info: creating high fidelity water
info: creating high fidelity 

terrain
info: creating high fidelity water
debug: Loading module '\000/units/urb0201/urb0201_script.lua\000'
warning: Error running 

OnRelease script in <deleted object>: ...mdata\faforever\gamedata\lua.nx2\lua\maui\button.lua(84): Game object has been destroyed
  

       stack traceback:
         	[C]: in function `Play'
         	...mdata\faforever\gamedata\lua.nx2\lua\maui

\button.lua(84): in function <...mdata\faforever\gamedata\lua.nx2\lua\maui\button.lua:78>
info: creating high fidelity terrain
info: 

creating high fidelity water
info: creating high fidelity terrain
info: creating high fidelity water
info: creating high fidelity 

terrain
info: creating high fidelity water
info: creating high fidelity terrain
info: creating high fidelity water
info: creating high 

fidelity terrain
info: creating high fidelity water
info: creating high fidelity terrain
info: creating high fidelity water
info: 

creating high fidelity terrain
info: creating high fidelity water
info: creating high fidelity terrain
info: creating high fidelity 

water
info: creating high fidelity terrain
info: creating high fidelity water
info: creating high fidelity terrain
info: creating high 

fidelity water
debug: Loading module '\000/units/urb5101/urb5101_script.lua\000'
info: creating high fidelity terrain
info: creating 

high fidelity water
info: creating high fidelity terrain
info: creating high fidelity water
info: creating high fidelity terrain
info: 

creating high fidelity water
debug: [uiutil.lua, function UIFile()] - Unable to find 

file:/textures/ui/uef/icons/units/unknown_icon.dds
debug: Loading module '\000/units/url0208/url0208_script.lua\000'
info: creating 

high fidelity terrain
info: creating high fidelity water
info: creating high fidelity terrain
info: creating high fidelity water
info: 

creating high fidelity terrain
info: creating high fidelity water
info: creating high fidelity terrain
info: creating high fidelity 

water
info: creating high fidelity terrain
info: creating high fidelity water
info: creating high fidelity terrain
info: creating high 

fidelity water
info: creating high fidelity terrain
info: creating high fidelity water
info: creating high fidelity terrain
info: 

creating high fidelity water
info: creating high fidelity terrain
info: creating high fidelity water
debug: Loading module 

'\000/units/zrb9501/zrb9501_script.lua\000'
info: creating high fidelity terrain
info: creating high fidelity water
info: creating 

high fidelity terrain
info: creating high fidelity water
info: "StealthGenerator"
debug: Loading module 

'\000/lua/sim/tasks/enhancetask.lua\000'
debug: Loading module '\000/lua/sim/scripttask.lua\000'
debug: Loading module 

'\000/lua/ui/lobby/restrictedunitsdata.lua\000'
info: creating high fidelity terrain
info: creating high fidelity water
info: 

creating high fidelity terrain
info: creating high fidelity water
info: creating high fidelity terrain
info: creating high fidelity 

water
info: creating high fidelity terrain
info: creating high fidelity water
info: creating high fidelity terrain
info: creating high 

fidelity water
info: creating high fidelity terrain
info: creating high fidelity water

**Comment by JaggedAppliance** [comment]
[6034034-JaggedAppliance.zip](https://github.com/FAForever/fa/files/906821/6034034-JaggedAppliance.zip)
Here's the replay, i get the same exception when i watch.

**Comment by Uveso** [comment]
Same exception:
http://forums.faforever.com/viewtopic.php?f=3&t=14883

**Comment by Garanas** [comment]
Closing this, lets keep track in #2045 if it happens again.
