### ISSUE TITLE
ASF hitting Carriers

### ISSUE THREAD

**Issue by PhilipJFryFAF** [FAForever/fa#1901]
You can still attack Carriers with air units as long as you have a target that is about to dock on the carrier.

**Comment by aeoncleanse** [comment]
The bullets should definitely be able to impact, but if once it docks the asf drop target, its working as intended

**Comment by PhilipJFryFAF** [comment]
they do not lose target that is the issue

**Comment by MrRowey** [comment]
Closing issues for now Balance Team Can Re Open if they intend to fix
