### ISSUE TITLE
Aeon Shield missing animation

### ISSUE THREAD

**Issue by PhilipJFryFAF** [FAForever/fa#1902]
The static aeon t2/t3 shield generator is missing an animation that is present in the steam version of the game
i assume this is not intended
[steam version](https://puu.sh/veJRg/61ba067cc4.gif)
[faf version](https://puu.sh/veJSb/a69b81c97f.gif)

**Comment by speed2CZ** [comment]
THe problem is that the function return because of no open animations https://github.com/FAForever/fa/blob/develop/lua/aeonunits.lua#L194
But as those animations dont exist, the code should be cleasned and just set rotators
