### ISSUE TITLE
Remove Nomads-specific code from FAF until it's ready for full integration (Should we decide to)

### ISSUE THREAD

**Issue by aeoncleanse** [FAForever/fa#1906]
From #1894

There's lots of code that is nomads-only from the Zep era. Until such time as Nomads is completely finished to a fully-integral state, and the Council takes a decision on making it part of the game, all that code should be removed to simplify things. 

This should be deployed in such a way as to cause 0 Nomads downtime (Push the patch and a Nomads patch at the same time)

**Comment by MrRowey** [comment]
@Garanas Is this something we still want to do ?

**Comment by Garanas** [comment]
No - probably not. I am closing this. If we'd remove the shader code we'd just break the mod.
