### ISSUE TITLE
Hotbuild keybinds not working

### ISSUE THREAD

**Issue by snufflesAU** [FAForever/fa#1913]
Hi,

I've gone straight from FAF to FAFDEVELOP and have found that although my hotbuild keys are bound, they are not working - not for building, at any rate. Everything else does.

Any ideas? What do you need done for troubleshooting on this end?

Cheers,
Snuff

**Comment by snufflesAU** [comment]
Tested under a fresh profile as well. None of the bindings under the "Hotbuilding" section of the controls work. Everything else does, if it's to do with an order eg. reclaim, patrol.

**Comment by aeoncleanse** [comment]
@HUSSAR-mtrela

**Comment by HUSSAR-mtrela** [comment]
@snufflesAU to troubleshoot this issue, I need:
- your Game.prefs file located in:
C:\Users\USER_NAME\AppData\Local\Gas Powered Games\Supreme Commander Forged Alliance
- list of actions that you made before this issue stared occuring, e.g. did you reset your bindings to default/hotbuild  preset

**Comment by aeoncleanse** [comment]
Confirmed it works perfectly my end, switching from one binding set to another, and preserving action :/

**Comment by snufflesAU** [comment]
Thanks boys, working on your reply

**Comment by aeoncleanse** [comment]
aaa3b6cfc643a03ec80f17d03d8d18cb290314a8
