### ISSUE TITLE
Hotbuild Labels do not update in construction menu when they are re-assigned 

### ISSUE THREAD

**Issue by HUSSAR-mtrela** [FAForever/fa#1915]
Steps to Reproduce:

1. open keybinding UI 
2. reset to hotbuild keybindings
3. close keybinding UI 
4. select t1 engineer 
5. observe that W is displayed over factories in construction menu
6. press W key and building of a factory is triggered
7. open keybinding UI 
8. assign C key to action: **build builders (factories, quantum gate & t1 engineers)**
9. close keybinding UI 
10. press C key and building of a factory is triggered

Issues:
- observe that W is still displayed over factories in construction menu
- press W key and building of a factory is still triggered even though W key was re-assigned by C key

**Comment by Bra1nwash3d** [comment]
A possible issue is that both keys are now assigned to build builders, might want to check game.prefs if that's the case. If yes, it's no bug as the labels were designed to display only one key (which ofc might be considered a bug/issue).

**Comment by HUSSAR-mtrela** [comment]
I checked my Game.prefs and there was only one key assigned to build builders which means that the game is not clearing old key binding when assigning a new key for that action and causing this issue. However, restarting the game clears old key binding

**Comment by aeoncleanse** [comment]
aaa3b6cfc643a03ec80f17d03d8d18cb290314a8
