### ISSUE TITLE
game doesnt end after all enemy acus are killed

### ISSUE THREAD

**Issue by CookieNoob** [FAForever/fa#1919]
replay ID: 6077324
content.faforever.com/faf/vault/replay_vault/replay.php?id=6077324

no errors in the log.

the game sends the game results for Peplomord after he disconnected, not when he died (~2 minutes difference) and he wasnt counted as dead. Victory conditions were "assasination". For a while Chosen was entirely alone on the map.

[replay.txt](https://github.com/FAForever/fa/files/924490/replay.txt)

**Comment by aeoncleanse** [comment]
Default FAF, 3676, for reference

**Comment by Uveso** [comment]
I think this can be closed.
I did not hear anything about this error again in the last 2 years,
and i rewrote the victory condition right now. https://github.com/FAForever/fa/pull/2719

Maybe i did it wrong and generate a new error, but this one should be gone :)
