### ISSUE TITLE
Keybinding Feature - Auto assign shift_actions

### ISSUE THREAD

**Issue by HUSSAR-mtrela** [FAForever/fa#1924]
Keybinding UI should auto assign shift_action when an action is mapped to a new key, for example:
When a user assigns the A key to Attack action then shift version of Attack action should be assigned with Shift + A key binding.

![image](https://cloud.githubusercontent.com/assets/11665978/25111244/c2a3e130-23b7-11e7-8246-5e36348f7ea8.png)

This should work similar way to hotbuild actions are mapped.

Complete list of shift actions:

- shift_transport
- shift_repair
- shift_guard
- shift_ferry
- shift_launch_tactical
- shift_spreadattack
- shift_move
- shift_dive
- shift_patrol
- shift_attack
- shift_capture
- shift_nuke
- shift_overcharge
- shift_stop
- shift_reclaim

**Comment by aeoncleanse** [comment]
a3e271f5b72b5ad26a77de939da9b0d1c69646dc
