### ISSUE TITLE
Keybinding allows an action to have 2 key bindings

### ISSUE THREAD

**Issue by HUSSAR-mtrela** [FAForever/fa#1925]
Steps to reproduce:

- open Keybinding UI  
- assign C key to Capture action
- assign A key to Attack action
- close Keybinding UI  
- select ACU
- press C key and mouse cursor changes to Capture as expected
- press A key and mouse cursor changes to Attack as expected

now fun part

- open Keybinding UI 
- clear binding for Capture action
- clear binding for Attack action
- assign C key to Attack action
- close Keybinding UI    
- select ACU
- press C key and mouse cursor changes to Attack as expected
- press A key and mouse cursor changes to Attack! (binding preserver in internal key map)

**Comment by aeoncleanse** [comment]
b835134eadcdde8cf0a8b30e8cecb45a796eeb1f
