### ISSUE TITLE
Keybinding is showing text outside of some of dialogs

### ISSUE THREAD

**Issue by HUSSAR-mtrela** [FAForever/fa#1926]
![image](https://cloud.githubusercontent.com/assets/11665978/25158493/e0594890-2476-11e7-879c-85fb02f37aaa.png)

**Comment by aeoncleanse** [comment]
That's quite a funny one lol. No text wrapping! There's definitely a function for that thankfully :)

**Comment by HUSSAR-mtrela** [comment]
Yes, there is but it complicated to use so I created UIUtil function that uses creates wrapped text.

![image](https://cloud.githubusercontent.com/assets/11665978/25160647/3d36fd10-2485-11e7-90de-8248f8d8028c.png)

**Comment by aeoncleanse** [comment]
I'm fairly sure we should just use the existing text wrapper... It's in one of the utils files somewhere. Seems pointless to re-make what we already have.

**Comment by speed2CZ** [comment]
`MultiLineText` should do the trick?

**Comment by HUSSAR-mtrela** [comment]
thanks @aeoncleanse and @speed2CZ 
I replaced my custom WrappedText with existing MultiLineText

**Comment by aeoncleanse** [comment]
afb98b232a61ce7be6b500c2314cc7cfad41937d
