### ISSUE TITLE
Keybinding Feature - Add keybinding button to In-game menu

### ISSUE THREAD

**Issue by HUSSAR-mtrela** [FAForever/fa#1930]
Add Key Binding button to In-game menu (F10) in case a user un-assigns F1 key for action that opens Keybinding dialog, which would prevent further assignments of keys and opening Keybinding dialog.

@aeoncleanse this is a temporary enhancement until we integrate Keybinding UI with the Options dialog. Also, it is much easier to implement.

**Comment by HUSSAR-mtrela** [comment]
![image](https://cloud.githubusercontent.com/assets/11665978/25306905/70bd8036-2765-11e7-8106-ab313d5dfc6e.png)

**Comment by aeoncleanse** [comment]
Yes, definitely do this.
