### ISSUE TITLE
Game needs 2 restarts to change the language

### ISSUE THREAD

**Issue by speed2CZ** [FAForever/fa#1934]
Changing language and clicking on Apply shows https://puu.sh/vuwMV/13eb2360eb.png
which closes the game but doesnt change the language yet.
It sets the language into profile table
```LUA
profile = {
    profiles = {
        {
            options = {
                selectedlanguage = 'CZ',
            },
        },
    },
}
```
After starting the game again, the language option is showing `CZ` as selected but the game is still in english.
Another restart does the job by setting:
```LUA
options_overrides = {
    language = 'CZ',
}
```

**Comment by Uveso** [comment]
Looks like a job for me :)

**Comment by aeoncleanse** [comment]
2d302b15c7a33a46edd54d0b7a0ff3e5402beab9
