### ISSUE TITLE
Don't abuse log level 'warning' (and clean up other logs)

### ISSUE THREAD

**Issue by micheljung** [FAForever/fa#1950]
Developers often abuse the `warning` log level just because it's printed in a different color and presumably helps them finding their log messages a little bit. They then often forget to remove the warning logs or to change it to a decent level (or they aren't even aware of log levels).

However, **'warning' should only be used when something happened that should not happen, does not cause failures in the application but should be noticed (and fixed).**

Correct usages of `warning`:
* `warning: Attempt to set option on unowned slot`
* `warning: Shift-A is already bind` (**bound** btw.)
* `warning: GetResource: Invalid name ""`

Don't use `warning` for:
* `warning: Connection dialogue opening due to disconnection by players:` (Don't use `:` either)
* `warning:  NUM PROPS = 4610`
* `warning: ACU kill detected. Rating for ranked games is now enforced.`

Additionally, `warning` should be used for:
* `info: Can't find texture "" -- trying fallback.` 
* `info: Error popping escape handler, stack is empty`

And while we're at it, never log things without context like this:
* `info: "AdvancedEngineering"`
* `info: "StealthGenerator"`

A log file isn't a dumpster, please be more delicate about it.

**Comment by speed2CZ** [comment]
`warning: NUM PROPS = 4610`
`info: Can't find texture "" -- trying fallback.`
Is from engine so we cant change that.

`info: "AdvancedEngineering"`
`info: "StealthGenerator"`
looks like a notify mod

**Comment by Garanas** [comment]
Turned this issue into a [wiki entry](https://github.com/FAForever/fa/wiki/Correct-usage-of-log-levels), closing this issue accordingly.
