### ISSUE TITLE
A way to determine when the game is over

### ISSUE THREAD

**Issue by Wesmania** [FAForever/fa#1956]
Right now the server has a simple way of determining when the game is over - when all the connections are over. This is inaccurate, since players can spend a lot of time on score screens, or on kick messages, or similar places. At the same time there doesn't seem to be an easy way of determining when the sim itself is over.
It would be amazing to have a way to figure out when the game is concluded or / and when the player is no longer participating in the game (by quitting to the score screen or getting the kick message, for example), and to send this info to the server.

**Comment by Uveso** [comment]
Info for myself:
Maybe usable:
Sim.lua line 276
```
function EndGame()
end
```

**Comment by MrRowey** [comment]
@Garanas @Askaholic is this something the server does or is there something in the fa code that need to be altered?

**Comment by Wesmania** [comment]
Huh, this issue really deserves to be closed for inactivity at this point, I have no idea if the lobby server still behaves like this.

**Comment by Garanas** [comment]
I'm closing it then.

**Comment by Askaholic** [comment]
For the record this was fixed in https://github.com/FAForever/server/pull/511
