### ISSUE TITLE
Show for which team the game is balanced in favor of

### ISSUE THREAD

**Issue by CookieNoob** [FAForever/fa#1967]
https://feedback.userreport.com/7a3715db-9cd2-49ec-bebd-b5cfd752647b/#idea/131426

not my suggestion, but I like it.

**Comment by CookieNoob** [comment]
https://github.com/FAForever/fa/blob/fdaecabdc9317df5fb914f24b4fddf9e1ef21403/lua/ui/lobby/lobby.lua#L2124

**Comment by CookieNoob** [comment]
https://github.com/FAForever/fa/blob/deploy/fafdevelop/lua/ui/lobby/lobby.lua#L2115

**Comment by MrRowey** [comment]
Closing as it now shows the total ranks of each team in the Observers box
