### ISSUE TITLE
unit given doesn't die when prior owner die

### ISSUE THREAD

**Issue by shalkya** [FAForever/fa#1968]
6181478
dave1 gave 2 T3 mexx and mass storage to me (keyser) at 14:40 minute
and then dave1 dies at 17:20.
the T3 mexx + storage doesn't die.

**Comment by Uveso** [comment]
In case the shareoption was "ShareUntilDeath" this is the corresponding line inside aibrain.lua:
https://github.com/FAForever/fa/blob/develop/lua/aibrain.lua#L683

KillSharedUnits is called there to kill the shared units. :)  You can find the function here:
https://github.com/FAForever/fa/blob/develop/lua/SimUtils.lua#L48

I tested both functions with some testgames and its working like expected.

I really don't know how this could happen.

**Comment by shalkya** [comment]
Yes it was "ShareUntilDeath", i should have post log.
But this is reproducable, and it is link to some UI mods. We just couldn't figure out which one. (maybe it is required that both player has the same ui mods or there is interaction between 2 or more mods.)

**Comment by aeoncleanse** [comment]
If people are running a mod which overwrites the file that runs this stuff, there's really nothing to be done.

**Comment by CookieNoob** [comment]
well this function is a SIM function, you cant overwrite it with an UI mod. Even if you did, it shouldnt work for the other players as their function isnt overwritten (same for the replay). Destroying units is not the same as giving orders to them (like massfabs turn on/off).

**Comment by aeoncleanse** [comment]
This function is passed parameters by UI code which some annoying mods DO overwrite.  Change what is sent, and these functions won't work as expected.

Basically, if a bug is only a bug when a mod is involved, it's not a bug. Modder needs to fix it.

**Comment by TheKeyBlue** [comment]
We need to figure out which mod though.
Can't have people running around with mods that give such a big advantage.
Need to make a firm statement that the mod is not allowed until its fixed.

**Comment by shalkya** [comment]
I'm pretty sure it's the fault of ui mods since we did change only this parameter (having ui mods or not) and the result was different (or we did bad testing)
we tested SSB and EM didn't seems to induce the bug. (still need to figure out which one since i had 10 ui mods running in order to have the bug occuring)
