### ISSUE TITLE
Stability Test (3676)

### ISSUE THREAD

**Issue by Uveso** [FAForever/fa#1969]
Test for version 3676

Tested on 3 x Windows7, 1 x Windows 10.
Normal and Sorian AIx
Default settings, except unit limit and gamespeed.
No mods enabled.

I7-4790K Win7
Saltrock Colony 5xAI 57min. OK
Saltrock Colony 5xAI 38min. OK
Saltrock Colony 5xAI 40min. OK
Saltrock Colony 5xAI 60min. OK
Saltrock Colony 5xAI 41min. OK
Saltrock Colony 5xAI 37min. OK
Saltrock Colony 5xAI 32min. OK
Saltrock Colony 5xAI 39min. OK
Saltrock Colony 5xAI 49min. OK
Saltrock Colony 5xAI 41min. OK
Saltrock Colony 5xAI 41min. OK
Saltrock Colony 5xAI 43min. OK
Saltrock Colony 5xAI 59min. OK
Saltrock Colony 5xAI 58min. OK
Saltrock Colony 5xAI 31min. OK
Saltrock Colony 5xAI 39min. OK
Saltrock Colony 5xAI 36min. OK
Saltrock Colony 5xAI 61min. OK
Saltrock Colony 5xAI 37min. OK
Saltrock Colony 5xAI 34min. OK

I7-6700 Win10
Planet Shmal 7xAI 30min. OK
Planet Shmal 7xAI 59min. OK
Planet Shmal 7xAI 29min. OK
Planet Shmal 7xAI 42min. OK
Planet Shmal 7xAI 45min. OK
Planet Shmal 7xAI 39min. OK
Planet Shmal 7xAI 36min. OK
Planet Shmal 7xAI 34min. OK
Planet Shmal 7xAI 35min. OK
Planet Shmal 7xAI 29min. OK
Planet Shmal 7xAI 32min. OK
Planet Shmal 7xAI 52min. OK
Planet Shmal 7xAI 45min. OK
Planet Shmal 7xAI 39min. OK
Planet Shmal 7xAI 27min. OK
Planet Shmal 7xAI 35min. OK
Planet Shmal 7xAI 30min. OK
Planet Shmal 7xAI 45min. OK
Planet Shmal 7xAI 31min. OK
Planet Shmal 7xAI 48min. OK

FX-8150 Win7
Rush me More 4xAI 54min. OK
Rush me More 4xAI 39min. OK
Rush me More 4xAI 26min. OK
Rush me More 4xAI 24min. OK
Rush me More 4xAI 42min. OK
Rush me More 4xAI 36min. OK
Rush me More 4xAI 32min. OK
Rush me More 4xAI 32min. OK
Rush me More 4xAI 63min. OK
Rush me More 4xAI 30min. OK
Rush me More 4xAI 37min. OK
Rush me More 4xAI 20min. OK
Rush me More 4xAI 32min. OK
Rush me More 4xAI 32min. OK
Rush me More 4xAI 23min. OK
Rush me More 4xAI 39min. OK
Rush me More 4xAI 31min. OK
Rush me More 4xAI 29min. OK

Q8400 Win7
Blasted Rock 15xAI 186min. OK (6 hours realtime)

**Comment by aeoncleanse** [comment]
This version has been up for a while now with no crashes overwhelmingly reported.
