### ISSUE TITLE
Stability Test FAForever/deploy/faf (3677)

### ISSUE THREAD

**Issue by Uveso** [FAForever/fa#1971]
Test for version FAForever/deploy/faf (3677)

Tested on 3 x Windows7, 1 x Windows 10.
Normal and Sorian AIx
Default settings, except unit limit and gamespeed.
No mods enabled.

I7-4790K Win7
Saltrock Colony 5xAI 49min. OK
Saltrock Colony 5xAI 55min. OK
Saltrock Colony 5xAI 48min. OK
Saltrock Colony 5xAI 49min. OK
Saltrock Colony 5xAI 20min. OK
Saltrock Colony 5xAI 37min. OK
Saltrock Colony 5xAI 41min. OK
Saltrock Colony 5xAI 42min. OK
Saltrock Colony 5xAI 38min. OK
Saltrock Colony 5xAI 42min. OK
Saltrock Colony 5xAI 49min. OK
Saltrock Colony 5xAI 41min. OK
Saltrock Colony 5xAI 40min. OK
Saltrock Colony 5xAI 38min. OK
Saltrock Colony 5xAI 35min. OK
Saltrock Colony 5xAI 33min. OK
Saltrock Colony 5xAI 45min. OK
Saltrock Colony 5xAI 41min. OK
Saltrock Colony 5xAI 46min. OK
Saltrock Colony 5xAI 35min. OK
Saltrock Colony 5xAI 40min. OK
Saltrock Colony 5xAI 34min. OK
Saltrock Colony 5xAI 31min. OK
Saltrock Colony 5xAI 43min. OK
Saltrock Colony 5xAI 48min. OK
Saltrock Colony 5xAI 31min. OK
Saltrock Colony 5xAI 49min. OK

I7-6700 Win10
Planet Shmal 7xAI 30min. OK
Planet Shmal 7xAI 31min. OK
Planet Shmal 7xAI 27min. OK
Planet Shmal 7xAI 28min. OK
Planet Shmal 7xAI 29min. OK
Planet Shmal 7xAI 24min. OK
Planet Shmal 7xAI 26min. OK
Planet Shmal 7xAI 27min. OK
Planet Shmal 7xAI 28min. OK
Planet Shmal 7xAI 35min. OK
Planet Shmal 7xAI 40min. OK
Planet Shmal 7xAI 39min. OK
Planet Shmal 7xAI 29min. OK
Planet Shmal 7xAI 25min. OK
Planet Shmal 7xAI 33min. OK
Planet Shmal 7xAI 50min. OK
Planet Shmal 7xAI 55min. OK
Planet Shmal 7xAI 30min. OK
Planet Shmal 7xAI 25min. OK
Planet Shmal 7xAI 29min. OK
Planet Shmal 7xAI 24min. OK
Planet Shmal 7xAI 27min. OK
Planet Shmal 7xAI 30min. OK
Planet Shmal 7xAI 28min. OK
Planet Shmal 7xAI 31min. OK
Planet Shmal 7xAI 48min. OK

FX-8150 Win7
Rush me More 4xAI 18min. OK
Rush me More 4xAI 20min. OK
Rush me More 4xAI 50min. OK
Rush me More 4xAI 55min. OK
Rush me More 4xAI 33min. OK
Rush me More 4xAI 24min. OK
Rush me More 4xAI 32min. OK
Rush me More 4xAI 44min. OK
Rush me More 4xAI 20min. OK
Rush me More 4xAI 24min. OK
Rush me More 4xAI 27min. OK
Rush me More 4xAI 15min. OK
Rush me More 4xAI 25min. OK
Rush me More 4xAI 39min. OK
Rush me More 4xAI 34min. OK
Rush me More 4xAI 18min. OK
Rush me More 4xAI 10min. OK
Rush me More 4xAI 31min. OK
Rush me More 4xAI 40min. OK
Rush me More 4xAI 4min. OK (no typo, 4 minutes^^)
Rush me More 4xAI 46min. OK
Rush me More 4xAI 34min. OK
Rush me More 4xAI 39min. OK

Q8400 Win7
Blasted Rock 15xAI 52min. OK
Blasted Rock 15xAI 24min. OK
Blasted Rock 15xAI 30min. OK
Blasted Rock 15xAI 24min. OK
Blasted Rock 15xAI 28min. OK
Blasted Rock 15xAI 21min. OK
Blasted Rock 15xAI 42min. OK
Blasted Rock 15xAI 30min. OK
Blasted Rock 15xAI 61min. OK
Blasted Rock 15xAI 21min. OK
Blasted Rock 15xAI 18min. FREEZE (Not the loop we are looking for...)
Blasted Rock 15xAI 27min. OK
Blasted Rock 15xAI 28min. OK
Blasted Rock 15xAI 17min. OK
Blasted Rock 15xAI 19min. OK
Blasted Rock 15xAI 32min. OK
Blasted Rock 15xAI 20min. OK
Blasted Rock 15xAI 23min. OK
Blasted Rock 15xAI 34min. OK
Blasted Rock 15xAI 35min. OK
Blasted Rock 15xAI 19min. OK

**Comment by aeoncleanse** [comment]
This version has been up for a while now with no crashes overwhelmingly reported.
