### ISSUE TITLE
black screen in Phantom-x and Nomads lobbies

### ISSUE THREAD

**Issue by PhilipJFryFAF** [FAForever/fa#1972]
Hosting a Phantom-x or Nomads game as a featured game mode results in a black screen in the lobby. People can see the lobby in FAF and try to join but also get the black screen.
[logs.zip](https://github.com/FAForever/fa/files/995358/logs.zip)

**Comment by CookieNoob** [comment]
as I understand it, a new version of nomads and other mods that are broken in this update were supposed to be released simultaneously with the FA patch...

**Comment by aeoncleanse** [comment]
duk3 pushed, this is good now
