### ISSUE TITLE
No templates

### ISSUE THREAD

**Issue by PhilipJFryFAF** [FAForever/fa#1974]
Since the 3680 patch the button for templates is grayed out even though there are templates saved and can be accessed by using a hotkey.
[logs.zip](https://github.com/FAForever/fa/files/997370/logs.zip)

![forgedalliance_2017-05-12_18-28-43](https://cloud.githubusercontent.com/assets/24656673/26007827/772d2a38-3742-11e7-8a46-2f576779bdc8.png)

**Comment by aeoncleanse** [comment]
98adeb4ef9313db14a1134a04317191fa0ebbe5c
