### ISSUE TITLE
make colored faction text optional in the lobby

### ISSUE THREAD

**Issue by CookieNoob** [FAForever/fa#1976]
I couldnt care less about the colors of the text, but there is a huge debate ongoing that wants white colored text instead of faction color.

Solution: Add a checkbox to the lobby options to have white colors instead of factional ones.

**Comment by aeoncleanse** [comment]
Reverted for now. Will come back as an option in the future.

**Comment by badbwoi** [comment]
hey guys, i really like the new colored fraction text. to fruther improve it, i suggest switching the colors. default setting gets "fraction color", so that not default is highlighted/easier to read

**Comment by aeoncleanse** [comment]
Done in 3686
