### ISSUE TITLE
Unit Manager restricts Fatboy when No Air preset is enabled

### ISSUE THREAD

**Issue by HUSSAR-mtrela** [FAForever/fa#1981]
Reported by Masyaka
http://forums.faforever.com/viewtopic.php?f=2&t=14550

No Air preset should exclude (LAND * AIRSTAGINGPLATFORM) units

**Comment by MrNukealizer** [comment]
Also check Cybran cruiser, Atlantis, and possibly carriers.

**Comment by MrNukealizer** [comment]
I looked at some of the restriction presets and it seems the problems are a lot more extensive than just this. It seems like the the restriction category system could use some work. Some examples:
* Restricting amphibious units doesn't affect Fatboy or Scathis and does restrict Harbinger Mark IV.
* Restricting air does restrict the Fatboy as noted, but it's inconsistent in other ways too. It restricts the Cybran T3 mobile AA which can attack air and land, but not the Seraphim version which can also attack air and land. It also allows the Shard while restricting all other AA only units.
* Restricting stealth aircraft only affects the Cybran spy plane, not the ASF or strategic bomber.
* Restricting stealth boats affects UEF and Cybran frigates but not the actual stealth naval units like the Mermaid, Baracuda, and Plan B.
* Restricting mobile stealth affects Rhino, Fire Beetle, Loyalist, and Brick. The description also seems to apply only to stealth fields but it affects personal stealth.
* Restricting air snipe units affects T2 torpedo bombers but not T3. and T2/T3 gunships but not T1.
* Restricting AA navy affects the Cooper, Mermaid, and Cybran frigate.
* Restricting torpedo boats affects Aeon and Seraphim frigates, does not affect Cooper, affects only the Cybran destroyer, and does not affect the Cybran attack sub.
* Restricting torpedo land units does literally nothing even though Fatboy, Megalith, Monkeylord, and Brick are land units with torpedoes. 
* Direct fire land includes the Seraphim T3 mobile AA but not the Cybran version.
* Restricting mass extractors also restricts mass storage for some reason.

**Comment by HUSSAR-mtrela** [comment]
I added my comment above (in bold text). Note that restriction system could be improved by checking type of weapon units have because categories in blueprints are not always reliable to determine that. Although, I think that blueprints of these units should be corrected because the game engine is also using them for other reason.

**Comment by MrNukealizer** [comment]
A lot of the comments make sense, but a couple don't.
* The Cooper and Mermaid do NOT have AA. The Cybran frigate has better AA than other frigates but it seems weird to restrict it and not the Seraphim frigate or all the UEF ships that have little AA guns. The restriction seems to be only for naval units that have AA as a significant role, and IMO the Cybran frigate isn't exceptional enough for that to be the case.
* Restricting mass storage with the extractors seems a bit odd since fabricators are separate. It seems reasonable that someone would host a game without mass extractors and still want to allow storage to hold reclaim or boost the output of fabricators.

**Comment by aeoncleanse** [comment]
The intention shod be for hybrid role units to be excluded. So no air should NOT exclude the hybrid mobile aa units. It should remove all fliers, and all pure dedicated aa for convenience

**Comment by aeoncleanse** [comment]
Also most of these problems are probably wrong categories in bp rather than bad filtering, so we fix that first.
