### ISSUE TITLE
Pings are inconsistent and unreliable and possibly abusable

### ISSUE THREAD

**Issue by TheKeyBlue** [FAForever/fa#1982]
I've heard about people not being able to ping or their pingmarkers not appearing on the map during games.
This is obviously annoying as you don't want to spend time trying to write the same marker multiple times.

It happened in giebs stream:
https://www.twitch.tv/videos/142915443 at 03:08:08

I'm thinking the Ping lock could have something to do with it.
https://github.com/FAForever/fa/blob/eb7c51f0ff647dbed415c61d4fd6e90f9ae6e985/lua/SimPing.lua#L21
It even blocks pings of your opponents I think. (since its called from a Simcallback every player gets it)
So in theory you could block your opponents pinging possibility by spamming pings yourself.
(needs verification though)

(sim and ui since its based on SimCallbacks and UserSyncs)

**Comment by TheKeyBlue** [comment]
Okay I just did some ingame test with somebody spamming pings.
If both are spamming it looks like its quite random who's ping actually happens. 

This is especially bad for markers since they require substantial time investment.
I suggest we just make a cooldown for each player individually instead. 
So you can ping without getting fucked by ally or enemy pinging aswell.

**Comment by aeoncleanse** [comment]
That seems sensible. A per-player cooldown, 2 seconds?

**Comment by Exotic-Retard** [comment]
if possible can it be something like you get 3 pings every 15 seconds because sometimes you want to ping twice for two places or for sth very important

**Comment by MrNukealizer** [comment]
I have a PR in that changes the limit to 3 pings every 15 seconds plus one additional marker, also with a cooldown. My first impression is that 15 seconds feels a bit long when spamming pings, but I'm sure the player's allies would be glad the limit is lower than one a second...
