### ISSUE TITLE
Integrate Notify

### ISSUE THREAD

**Issue by aeoncleanse** [FAForever/fa#1983]
The plan is to do this right. Nice and polished, and in a way people won't get upset, won't regret it happening. So there are a number of things I want to see as part of this:

- Part of Notify is the ability to queue ACU upgrades. This needs to happen, and for SCUs too, long overdue
- There needs to be a way to disable the Notifications in the chat box. Keep /disablenotify in place along with the other commands, but also I'd like a button there which does the same thing, with a tooltip. This would be temporary, for that session. A main options menu toggle would enable/disable the Notify function completely
- We need a "Notify Customisation" section in the options menu, or possible accessed from Lobby. From this, players will be able to see all the possible messages and customise them.
- We need a way to easily import the message section from an old mod into the new game version. My initial thoughts on how to do this are if we have the messages stored in the prefs file, and in the same structure as in the old mod, so people can simply copy-paste that bit into their prefs file and have it work.

@Uveso @TheKeyBlue @CookieNoob - I'd like input from you guys if I've missed something. Also, you three are the ones I think most capable to make this happen. Any volunteers?

**Comment by aeoncleanse** [comment]
https://github.com/FAForever/fa/commits/feature/notify

**Comment by MrNukealizer** [comment]
One more thing that needs to be done is fix Hotbuild so it can cycle through tech levels of a building when the ACU is upgrading. For example, if the ACU is upgrading to T3 or has it queued and you use the Hotbuild key for a shield, it will only select the T3 shield. No matter how many times you press the key, it won't select the T2 shield or stealth generator until the upgrade is complete.

There's another bug where certain mod units can be queued after an ACU upgrade even if the ACU couldn't build them with only the queued upgrade. It's not uncommon to start the T2 upgrade and see some T3 or experimental stuff in the build menu until it's done.

Finally, it might be a BlackOps issue  rather than a Notify issue, but it has some trouble with the third upgrade of any path in the BlackOps ACU mod. I'm thinking Notify assumes upgrades can only go two levels deep because that's the default.

**Comment by TheKeyBlue** [comment]
Maybe tell us which mods they are, so it can be tested if its the mods fault or not.

**Comment by aeoncleanse** [comment]
@MrNukealizer if you want to help me out on this one you're more than welcome. Your skillset is way beyond my own, and testing your spread command code has left me very impressed.

Both of these seem likely to be errors with the way notify handles the "Allow upgrade queuing" part of the mod.

**Comment by MrNukealizer** [comment]
Sure, I'll help out. I'm not good with UI stuff but I can work on the backend code.

@TheKeyBlue: I can't remember most of the affected mods, but one is T3 Engineering Stations FAF v6. It seems the blueprints have BUILTBYCOMMANDER as well as BUILTBYTIER3COMMANDER and that's what's throwing it off.

**Comment by aeoncleanse** [comment]
Regarding the mod, that's not our problem. The mod is broken and will not perform as expected.

**Comment by CookieNoob** [comment]
You integrated the chat command toggles for it already, but you forgot to mention the notify overlay. This shows the eta and percentage during an upgrade.

![grafik](https://cloud.githubusercontent.com/assets/21953792/26031729/2b048510-387e-11e7-85f4-0114b18340b3.png)

I totally agree with adding a checkbox to the chat window (or the chat window options) that toggles the notify functions.

**Comment by aeoncleanse** [comment]
Progress so far:

Command messages
Notify messages themselves
Overlay and progress

**Comment by aeoncleanse** [comment]
Anihilnine suggested allowing notify to message on starting exp, nuke, T3 arty, tech upgrade etc. Definitely think this is a good idea.

**Comment by CookieNoob** [comment]
exp, t3 arty and nuke yea, but for tech upgrades?

**Comment by aeoncleanse** [comment]
Why not? We can make it so you can turn on/off different message categories

**Comment by CookieNoob** [comment]
ok if it has a toggle for every message (you get, not send), sure. I would still set the default for a factory tech upgrade to false. Just imagine a 6v6 game, or some game where one player upgrades multiple factories to HQs... I just think that most of the notifications wont be read anymore when there are tons of "player A started upgrading a land HQ" notifications.

starting an arty, exp or a nuke on the other hand is a late game thing, where most of the notifications from acu upgrades dont show up anyway, and these units are very costly, so having some notifications to the team is really nice.

**Comment by aeoncleanse** [comment]
I don't think we can stop receiving something :/

**Comment by CookieNoob** [comment]
but you can add a check for the different messagetypes if it should be displayed in chat

**Comment by CookieNoob** [comment]
everyone should always send all messages, so that its customizable which type of message you want to see.

**Comment by aeoncleanse** [comment]
Done in 3686
