### ISSUE TITLE
Dead air units that bounce into water sink forever

### ISSUE THREAD

**Issue by MrNukealizer** [FAForever/fa#1985]
It seems that when air units die and bounce off shields into water, they don't stop sinking properly. They sink through the seafloor and down to infinity.

**Comment by aeoncleanse** [comment]
Oh COME ON TEST TEAM! This should not have got through.  Last I checked this was working

**Comment by aeoncleanse** [comment]
Tested with many air units vs UEF shield boat, they sink and wreck properly on the bottom.

**Comment by MrNukealizer** [comment]
Turns out it was a terrain problem that just happened to be demonstrated by the air units bouncing into a certain area.
