### ISSUE TITLE
Stability Test FAForever/deploy/beta (3678)

### ISSUE THREAD

**Issue by Uveso** [FAForever/fa#1991]
Test for version FAForever/deploy/beta (3678) 

Tested on 3 x Windows7, 1 x Windows 10.
Normal and Sorian AIx
Default settings, except unit limit and gamespeed.
No mods enabled.

I7-4790K Win7
Saltrock Colony 5xAI 36min. OK
Saltrock Colony 5xAI 39min. OK
Saltrock Colony 5xAI 30min. OK
Saltrock Colony 5xAI 24min. OK
Saltrock Colony 5xAI 76min. OK
Saltrock Colony 5xAI 52min. OK
Saltrock Colony 5xAI 36min. OK
Saltrock Colony 5xAI 32min. OK
Saltrock Colony 5xAI 36min. OK
Saltrock Colony 5xAI 39min. OK
Saltrock Colony 5xAI 31min. OK
Saltrock Colony 5xAI 33min. OK
Saltrock Colony 5xAI 51min. OK
Saltrock Colony 5xAI 34min. OK
Saltrock Colony 5xAI 42min. OK
Saltrock Colony 5xAI 45min. OK
Saltrock Colony 5xAI 45min. OK
Saltrock Colony 5xAI 40min. OK
Saltrock Colony 5xAI 37min. OK
Saltrock Colony 5xAI 44min. OK
Saltrock Colony 5xAI 39min. OK
Saltrock Colony 5xAI 52min. OK
Saltrock Colony 5xAI 68min. OK
Saltrock Colony 5xAI 44min. OK
Saltrock Colony 5xAI 40min. OK
Saltrock Colony 5xAI 52min. OK
Saltrock Colony 5xAI 54min. OK
Saltrock Colony 5xAI 45min. OK
Saltrock Colony 5xAI 50min. OK
Saltrock Colony 5xAI 34min. OK
Saltrock Colony 5xAI 44min. OK
Saltrock Colony 5xAI 25min. DEADLOOP
Saltrock Colony 5xAI 42min. DEADLOOP
Saltrock Colony 5xAI 43min. OK
Saltrock Colony 5xAI 66min. OK
Saltrock Colony 5xAI 56min. OK
Saltrock Colony 5xAI 40min. OK
Saltrock Colony 5xAI 31min. OK
Saltrock Colony 5xAI 42min. OK
Saltrock Colony 5xAI 62min. OK
Saltrock Colony 5xAI 97min. OK

I7-6700 Win10
Planet Shmal 7xAI 29min. OK
Planet Shmal 7xAI 35min. OK
Planet Shmal 7xAI 36min. OK
Planet Shmal 7xAI 31min. OK
Planet Shmal 7xAI 51min. OK
Planet Shmal 7xAI 33min. OK
Planet Shmal 7xAI 41min. OK
Planet Shmal 7xAI 51min. OK
Planet Shmal 7xAI 31min. OK
Planet Shmal 7xAI 27min. OK
Planet Shmal 7xAI 75min. OK
Planet Shmal 7xAI 22min. DEADLOOP
Planet Shmal 7xAI 34min. DEADLOOP
Planet Shmal 7xAI 14min. DEADLOOP
Planet Shmal 7xAI 69min. OK
Planet Shmal 7xAI 38min. DEADLOOP
Planet Shmal 7xAI 48min. OK
Planet Shmal 7xAI 102min. OK
Planet Shmal 7xAI 13min. DEADLOOP
Planet Shmal 7xAI 68min. OK
Planet Shmal 7xAI 57min. OK
Planet Shmal 7xAI 89min. OK
Planet Shmal 7xAI 35min. OK
Planet Shmal 7xAI 22min. DEADLOOP
Planet Shmal 7xAI 44min. OK
Planet Shmal 7xAI 53min. OK
Planet Shmal 7xAI 75min. OK
Planet Shmal 7xAI 38min. OK
Planet Shmal 7xAI 56min. DEADLOOP
Planet Shmal 7xAI 90min. OK

FX-8150 Win7
Rush me More 4xAI 40min. OK
Rush me More 4xAI 14min. OK
Rush me More 4xAI 27min. OK
Rush me More 4xAI 29min. OK
Rush me More 4xAI 22min. OK
Rush me More 4xAI 41min. OK
Rush me More 4xAI 41min. OK
Rush me More 4xAI 32min. DEADLOOP
Rush me More 4xAI 34min. OK
Rush me More 4xAI 25min. DEADLOOP
Rush me More 4xAI 66min. OK
Rush me More 4xAI 56min. OK
Rush me More 4xAI 79min. OK
Rush me More 4xAI 34min. OK
Rush me More 4xAI 22min. OK
Rush me More 4xAI 66min. OK
Rush me More 4xAI 44min. OK
Rush me More 4xAI 29min. OK
Rush me More 4xAI 40min. OK
Rush me More 4xAI 44min. OK
Rush me More 4xAI 33min. OK
Rush me More 4xAI 53min. OK
Rush me More 4xAI 32min. OK
Rush me More 4xAI 40min. OK
Rush me More 4xAI 38min. OK
Rush me More 4xAI 29min. DEADLOOP
Rush me More 4xAI 24min. OK

Q8400 Win7
Blasted Rock 15xAI 28min. OK
Blasted Rock 15xAI 23min. OK
Blasted Rock 15xAI 18min. OK
Blasted Rock 15xAI 31min. OK
Blasted Rock 15xAI 20min. OK
Blasted Rock 15xAI 23min. OK
Blasted Rock 15xAI 42min. OK
Blasted Rock 15xAI 20min. OK
Blasted Rock 15xAI 51min. OK
Blasted Rock 15xAI 15min. OK
Blasted Rock 15xAI 32min. OK
Blasted Rock 15xAI 24min. OK
Blasted Rock 15xAI 27min. OK
Blasted Rock 15xAI 22min. OK
Blasted Rock 15xAI 18min. OK
Blasted Rock 15xAI 33min. OK
Blasted Rock 15xAI 17min. OK
Blasted Rock 15xAI 21min. OK
Blasted Rock 15xAI 38min. OK
Blasted Rock 15xAI 23min. OK
Blasted Rock 15xAI 25min. OK
Blasted Rock 15xAI 27min. OK
Blasted Rock 15xAI 17min. OK
Blasted Rock 15xAI 33min. OK
Blasted Rock 15xAI 23min. OK
Blasted Rock 15xAI 29min. OK
Blasted Rock 15xAI 21min. OK
Blasted Rock 15xAI 20min. OK
Blasted Rock 15xAI 22min. OK
Blasted Rock 15xAI 37min. OK
Blasted Rock 15xAI 33min. OK
Blasted Rock 15xAI 28min. OK
Blasted Rock 15xAI 19min. OK
Blasted Rock 15xAI 21min. OK
Blasted Rock 15xAI 33min. OK
Blasted Rock 15xAI 41min. OK

**Comment by MrNukealizer** [comment]
So if I understand this correctly we should be looking for the source of the deadloop between 3676 and 3677?

**Comment by Uveso** [comment]
@MrNukealizer 
I forgot to write the right version number. This was a test for Beta version 3678.
(Beta is at the moment version 3681)

Version 3676 was ok:
https://github.com/FAForever/fa/issues/1969

Version 3677 (FAForever/deploy/faf) also ok:
https://github.com/FAForever/fa/issues/1971

So we are looking for an loop between 3677 (faf) and 3678+ (beta).

**Comment by aeoncleanse** [comment]
So I think this will have been after the launch of the patch, with beta rebased on top.

**Comment by aeoncleanse** [comment]
Some reports of deadloops in release are now coming in.

**Comment by aeoncleanse** [comment]
Solved with the finding root -tv number fix
