### ISSUE TITLE
Sim freezes from shield bounce possibly still around

### ISSUE THREAD

**Issue by duk3luk3** [FAForever/fa#1998]
Need to check if ShieldCollider and Sinker every happen to be active at the same time.

**Comment by MrNukealizer** [comment]
I found the cause: https://github.com/FAForever/fa/blob/develop/projectiles/ShieldCollider/ShieldCollider_script.lua#L140
When a dead aircraft is moving upwards and hits the inside top of a shield, `vy` can be positive enough to make `math.sqrt(wx * wx + wy * vy + wz * wz)` try to get the square root of a negative number. I'm not sure how to fix the math, but it seems like the vector calculation doesn't consider the possibility of hitting the inside of the shield.
