### ISSUE TITLE
different patrol order for acu

### ISSUE THREAD

**Issue by shalkya** [FAForever/fa#1999]
when you do patrol order with acu it goes chase down unit that are very far.
usually you want to use patrol on acu to avoid tactical missile or to reclaim.

is it possible to have 1 patrol order that ignore the reclaim near by, and which doesn't chase down near by unit.
And another patrol order only for the acu to reclaim.

I understand this change are controversial, still think that would be better.

**Comment by aeoncleanse** [comment]
Probably not. We can thing about it.

**Comment by MrRowey** [comment]
@Garanas Close this a i dont see this being a thing just adds more complexity to the game

**Comment by Garanas** [comment]
And it is not possible - we can't change the behavior of patrol.
