### ISSUE TITLE
Stability Test master (3682)

### ISSUE THREAD

**Issue by Uveso** [FAForever/fa#2001]
Stability Test master (3682)

Tested on 3 x Windows7, 1 x Windows 10.
Normal and Sorian AIx
Default settings, except unit limit and gamespeed.
No mods enabled.

I7-4790K Win7
Planet Shmal 7xAI 27min. OK (Crashed on restart)
Planet Shmal 7xAI 42min. OK
Planet Shmal 7xAI 27min. OK
Planet Shmal 7xAI 78min. OK
Planet Shmal 7xAI 41min. OK
Planet Shmal 7xAI 60min. OK
Planet Shmal 7xAI 31min. OK
Planet Shmal 7xAI 61min. OK
Planet Shmal 7xAI 35min. OK
Planet Shmal 7xAI 30min. OK
Planet Shmal 7xAI 27min. OK
Planet Shmal 7xAI 38min. OK
Planet Shmal 7xAI 52min. OK
Planet Shmal 7xAI 34min. OK
Planet Shmal 7xAI 30min. OK
Planet Shmal 7xAI 30min. OK
Planet Shmal 7xAI 34min. OK
Planet Shmal 7xAI 79min. OK
Planet Shmal 7xAI 34min. OK
Planet Shmal 7xAI 35min. OK
Planet Shmal 7xAI 38min. OK
Planet Shmal 7xAI 57min. OK
Planet Shmal 7xAI 31min. OK
Planet Shmal 7xAI 40min. OK
Planet Shmal 7xAI 31min. OK
Planet Shmal 7xAI 100min. OK
Planet Shmal 7xAI 68min. OK
Planet Shmal 7xAI 34min. OK

I7-6700 Win10
Planet Shmal 7xAI 48min. OK
Planet Shmal 7xAI 67min. OK
Planet Shmal 7xAI 54min. OK
Planet Shmal 7xAI 48min. OK
Planet Shmal 7xAI 39min. OK
Planet Shmal 7xAI 37min. OK
Planet Shmal 7xAI 34min. OK
Planet Shmal 7xAI 38min. OK
Planet Shmal 7xAI 65min. OK
Planet Shmal 7xAI 42min. OK
Planet Shmal 7xAI 43min. OK
Planet Shmal 7xAI 32min. OK
Planet Shmal 7xAI 32min. OK
Planet Shmal 7xAI 33min. OK
Planet Shmal 7xAI 30min. OK
Planet Shmal 7xAI 39min. OK
Planet Shmal 7xAI 33min. OK
Planet Shmal 7xAI 30min. OK
Planet Shmal 7xAI 49min. OK
Planet Shmal 7xAI 33min. OK
Planet Shmal 7xAI 44min. OK
Planet Shmal 7xAI 62min. OK
Planet Shmal 7xAI 50min. OK
Planet Shmal 7xAI 46min. OK

FX-8150 Win7
Rush me More 7xAI 35min. OK
Rush me More 7xAI 46min. OK
Rush me More 7xAI 37min. OK (Crashed on restart)
Rush me More 7xAI 49min. OK
Rush me More 7xAI 64min. OK
Rush me More 7xAI 30min. OK
Rush me More 7xAI 47min. OK
Rush me More 7xAI 48min. OK (Crash; see `1)`)
Rush me More 7xAI 39min. OK (Crash; see `1)`)
Rush me More 7xAI 35min. OK
Rush me More 7xAI 22min. OK
Rush me More 7xAI 31min. OK
Rush me More 7xAI 34min. OK
Rush me More 7xAI 59min. OK
Rush me More 7xAI 55min. OK
Rush me More 7xAI 37min. OK
Rush me More 7xAI 59min. OK
Rush me More 7xAI 33min. OK
Rush me More 7xAI 49min. OK

Q8400 Win7
Rush me More 7xAI 74min. OK
Rush me More 7xAI 61min. OK
Rush me More 7xAI 25min. OK
Rush me More 7xAI 37min. OK
Rush me More 7xAI 75min. OK
Rush me More 7xAI 35min. OK
Rush me More 7xAI 87min. OK
Rush me More 7xAI 34min. OK
Rush me More 7xAI 33min. OK
Rush me More 7xAI 46min. OK (Crash; see `1)`)
Rush me More 7xAI 33min. OK
Rush me More 7xAI 52min. OK
Rush me More 7xAI 30min. OK
Rush me More 7xAI 28min. OK
Rush me More 7xAI 31min. OK
Rush me More 7xAI 35min. OK
Rush me More 7xAI 25min. OK
Rush me More 7xAI 37min. OK
Rush me More 7xAI 24min. OK
Rush me More 7xAI 33min. OK

`1)`
Crash c0000005 @ 0x0050ad86
Crashed after game ended
Last logline: `INFO: GAMERESULT : \000victory 10`
(No stats sended.)

**Comment by aeoncleanse** [comment]
This version has been up for a while now with no crashes overwhelmingly reported.
