### ISSUE TITLE
switching from player to observer lose data (veterancy) 

### ISSUE THREAD

**Issue by shalkya** [FAForever/fa#2003]
there is a lose of UI data, when switching from player to observer while looking at a replay.
here it is veterancy : wrong regen is showing + wrong number of stars
https://files.slack.com/files-pri/T02T320UA-F5FFETUAF/image.png
https://files.slack.com/files-pri/T02T320UA-F5FK1GN3W/image.png

**Comment by aeoncleanse** [comment]
Fixed in #2004
