### ISSUE TITLE
Mouse buttons not recognised when trying to assign hotkeys

### ISSUE THREAD

**Issue by JaggedAppliance** [FAForever/fa#2007]
You cannot set hotkeys to mouse buttons directly, you have to first set the mouse buttons to keys.

**Comment by speed2CZ** [comment]
I've tried to add the keys into `keynames.lua` but the game doesnt seem to accept them. So either it has to be included somewhere else in lua or the engine doesn't accept them. Im afraid that the engine will be the answer here.
```LUA
-- Contains the localized friendly names of key codes used in the game
-- Key codes must be in hex and match the Windows VK codes

keyNames = {
    ['01'] = 'LeftMouse',
    ['02'] = 'RightMouse',
    ['03'] = 'Cancel',
    ['04'] = 'MiddleMouse',
    ['05'] = 'X1Mouse',
    ['06'] = 'X2Mouse',
    ['08'] = 'Backspace',
    ['09'] = 'Tab',
    ...
```

**Comment by MrRowey** [comment]
@Garanas Tryed changing this my self and dose not seem to work so looks like an Engine Limitation
