### ISSUE TITLE
Get rid of all GPG-copyrighted code, use hooks/rewrites instead

### ISSUE THREAD

**Issue by Sheeo** [FAForever/fa#201]
Will keep this issue updated with status.

**Comment by CookieNoob** [comment]
https://github.com/FAForever/fa/search?p=1&q=Copyright&type=&utf8=%E2%9C%93

currently the approach seems to be to upload the original file and then make modifications to the functions... while this is nice for developing stuff, the amount of copyrighted code is increasing a lot. Do we still want to get rid of this code or did this get dropped now? @aeoncleanse

**Comment by Sheeo** [comment]
@CookieNoob our policy isn't changing on this. That being said; it's not a top priority.

**Comment by MrRowey** [comment]
#3930

**Comment by Garanas** [comment]
Safe to say: the policy has changed as per the board meeting of end of May.
