### ISSUE TITLE
Cybran SACU projectile lifetime too short with range upgrade

### ISSUE THREAD

**Issue by MrNukealizer** [FAForever/fa#2020]
Currently the Cybran SACU can't hit targets at the very edge of its upgraded range. Theoretically the projectile should last long enough to hit a stationary target (range is 35, lifetime 1.5 * 1.3 * speed 18 = 35.1). Unfortunately it seems projectile lifetime is rounded down to the next lowest tenth of a second resulting in 1.5 * 1.3 = 1.95, rounded to 1.9 * 18 = 34.2 projectile range. That's not enough to hit even stationary targets at range 35, let alone something moving away from the unit.

The reason I brought this up without providing a fix is because I'm not sure why the projectile's lifetime is so short or what it should be changed to. For reference, to hit a unit moving directly away at a speed of 8 (Shard, fastest possible target), the multiplier would need to be changed to 2.4, for 1.5 * 2.4 * 18 = 64.8 projectile range.

**Comment by Exotic-Retard** [comment]
umm are you sure this is the case? since the weapon range is adjusted on gun upgrade it might not matter.

i cant replicate the issue in tests. putting a unit at the edge of the upgraded acus range and then teleporting it to make projectiles miss shows them going well outside max range :|

**Comment by MrNukealizer** [comment]
I can't tell if you forgot the S in SACU or if you tested the wrong thing. In any case, [This](http://i.imgur.com/NqIo0se.png) is what I'm talking about. The shot disappears before hitting the target because its lifetime is too short. I got the EMP upgrade to make it easier to see in the picture, but the same thing happens without.
