### ISSUE TITLE
Game: The pause button color doesn't change when you switch faction UI layout

### ISSUE THREAD

**Issue by TheKeyBlue** [FAForever/fa#2031]
![pause](https://cloud.githubusercontent.com/assets/20644178/26499202/04df8c78-4232-11e7-909b-f30a5c52c968.png)
So when you switch faction ui layout in game the two vertical lines don't chane colour.

**Comment by ChrisKitching** [comment]
Pretty sure [this](https://github.com/FAForever/fa/blob/develop/lua/ui/game/construction.lua#L288) is the offending code.

That's original GPG stuff. You need to switch that to using SkinnableFile. It will then resolve the file path relative to `textures/ui/<FACTION_NAME>` and then, if that fails, `textures/ui/common`. You then create a `game/construct-sm_btn/pause_on.dds` and `game/construct-sm_btn/pause_of.dds` for each faction, and you're done.

**Comment by ChrisKitching** [comment]
Note that `pause_on.dds` is not in this repo: we haven't modded it, so it's left out, and being loaded directly from the game. The procedure described above will allow you to override it.
