### ISSUE TITLE
can't see how much a nuke or a tml can store because of shortcut

### ISSUE THREAD

**Issue by shalkya** [FAForever/fa#2033]
http://imgur.com/4ltmhk7
http://imgur.com/ZwzK6zt

here are the screenshot, you can still see this in different way, but i guess it's not how we wanted that to happen.

**Comment by TheKeyBlue** [comment]
So we move the numbers so they are above the hotkeylabel?
Or what do you suggest?

**Comment by TheKeyBlue** [comment]
just needed to change one line :)
