### ISSUE TITLE
Introduce a button to show changelogs

### ISSUE THREAD

**Issue by JaggedAppliance** [FAForever/fa#2036]
The changelog shows up once when you join/host a game the first time after an update. After that you can't access it. It would be nice to have some way of accessing the changelog in the lobby.

**Comment by TheKeyBlue** [comment]
That should be easy enough.
Any idea where would be a good spot to put it?

**Comment by JaggedAppliance** [comment]
Maybe to the left or right of the faction symbols at the top

**Comment by aeoncleanse** [comment]
Inside the lobby settings menu please

**Comment by TheKeyBlue** [comment]
In the settings menu? 
That is most unintuitive, is it not?

**Comment by aeoncleanse** [comment]
Hmm, a button to show something normally found under "Help - About" in most programs. Something very few will ever use, on one of our most cluttered interfaces...

Put it in the Lobby menu. _Lobby_ menu

**Comment by TheKeyBlue** [comment]
say what?
Lobby menu? pics or lua file?

**Comment by aeoncleanse** [comment]
There is a small popup menu in the lobby which controls the background picture etc

**Comment by MrNukealizer** [comment]
Why not make it show if you click the version in the top left?

**Comment by TheKeyBlue** [comment]
icedreamer, so you still mean the lobby settings menu?
mrnuke : i think that would be a little too hidden :/ (we could have it there too though)

**Comment by aeoncleanse** [comment]
That is where such a thing belongs.

**Comment by TheKeyBlue** [comment]
Just have the entire changelog with all of the changes since 3636 patch?
Or only last x patches ?

Currently it is ordered oldest patch first. Better have it  newest first?
If so would it be fine to also have newest first when you see the changelog on startup?

**Comment by aeoncleanse** [comment]
Just display most recent section I think. If you're feeling brave, could copy the key binder and have it expandable sections i guess

**Comment by ChrisKitching** [comment]
> Why not make it show if you click the version icon/number in the top left?

This seems like a reasonably good approach.

Don't forget to add a hover effect to the text/logo so it's discoverable.

Once you've done this, it may also be of value to add a tickbox to lobby settings to stop showing the changelog on each new version launch. Some people (myself included) may find that irritating.

**Comment by shalkya** [comment]
fixed in #2628
