### ISSUE TITLE
preset can't change back build restriction (neither does default setting button)

### ISSUE THREAD

**Issue by shalkya** [FAForever/fa#2041]
put paragon off, then use preset with paragon on, it won't make it on
default setting button doesn't put paragon on, when it is off.

though preset with paragon off, does put paragon off.

**Comment by TheKeyBlue** [comment]
I did some test and noticed that Team Options (Spawn,Team,..) are also not reset when you click the default settings button.
I guess we would want those to reset to default too?

**Comment by HUSSAR-mtrela** [comment]
@aeoncleanse did you forget to test/close this issue after creating/merging PR #2046 made by @TheKeyBlue

**Comment by HUSSAR-mtrela** [comment]
@shalkya can you check if this is still an issue because it looks like it was fixed in PR 2046
