### ISSUE TITLE
Stability Test (3676) part II

### ISSUE THREAD

**Issue by Uveso** [FAForever/fa#2044]
Test for version 3676 part II
(part I: #1969)

Tested on 3 x Windows7, 1 x Windows 10.
Normal and Sorian AIx
Default settings, except unit limit and gamespeed.
No mods enabled.

I7-4790K Win7 Sorian AIx
Planet Shmal 7xAI 29min. OK
Planet Shmal 7xAI  0min. ERROR1 (Freeze on restart)
Planet Shmal 7xAI 78min. OK
Planet Shmal 7xAI 34min. OK
Planet Shmal 7xAI 52min. OK
Planet Shmal 7xAI 38min. OK
Planet Shmal 7xAI 39min. OK
Planet Shmal 7xAI 41min. OK
Planet Shmal 7xAI 42min. OK
Planet Shmal 7xAI 35min. OK
Planet Shmal 7xAI 62min. OK
(10 hours pause)
Planet Shmal 7xAI 39min. OK
Planet Shmal 7xAI 46min. OK
Planet Shmal 7xAI 55min. OK
Planet Shmal 7xAI 35min. OK
Planet Shmal 7xAI 37min. OK
Planet Shmal 7xAI 32min. OK
Planet Shmal 7xAI 50min. OK
Planet Shmal 7xAI 64min. OK
Planet Shmal 7xAI 49min. OK
Planet Shmal 7xAI 47min. OK
Planet Shmal 7xAI 33min. OK
Planet Shmal 7xAI 43min. ERROR3 (While ACU is exploding)
Planet Shmal 7xAI 93min. OK

I7-6700 Win10 Sorian AIx
Planet Shmal 7xAI 38min. OK
Planet Shmal 7xAI 33min. OK
Planet Shmal 7xAI 36min. OK
Planet Shmal 7xAI 37min. OK
Planet Shmal 7xAI 32min. OK
Planet Shmal 7xAI  0min. ERROR2 (CTD on Restart)
Planet Shmal 7xAI 36min. OK
Planet Shmal 7xAI 35min. OK
Planet Shmal 7xAI 58min. OK
Planet Shmal 7xAI 31min. OK
Planet Shmal 7xAI 33min. OK
Planet Shmal 7xAI 45min. OK
Planet Shmal 7xAI 26min. OK
(10 hours pause)
Planet Shmal 7xAI 80min. OK
Planet Shmal 7xAI 93min. OK
Planet Shmal 7xAI 39min. OK
Planet Shmal 7xAI  0min. ERROR2 (CTD on Restart)
Planet Shmal 7xAI 34min. OK
Planet Shmal 7xAI 36min. OK
Planet Shmal 7xAI 51min. OK
Planet Shmal 7xAI 91min. OK
Planet Shmal 7xAI 38min. OK
Planet Shmal 7xAI 81min. OK

FX-8150 Win7 Normal AIx
Rush me More 7xAI 50min. OK
Rush me More 7xAI 43min. OK
Rush me More 7xAI 33min. OK
Rush me More 7xAI 26min. OK
Rush me More 7xAI 44min. OK
Rush me More 7xAI 14min. OK
Rush me More 7xAI 47min. OK
Rush me More 7xAI 12min. OK
Rush me More 7xAI 11min. OK
Rush me More 7xAI 39min. OK
Rush me More 7xAI 12min. OK
(10 hours pause)
Rush me More 7xAI 14min. OK
Rush me More 7xAI 22min. OK
Rush me More 7xAI 60min. OK
Rush me More 7xAI 18min. OK
Rush me More 7xAI 14min. OK
Rush me More 7xAI 31min. OK
Rush me More 7xAI 18min. OK
Rush me More 7xAI 41min. OK
Rush me More 7xAI 36min. OK
Rush me More 7xAI 32min. OK
Rush me More 7xAI 29min. OK
Rush me More 7xAI 26min. OK
Rush me More 7xAI 48min. OK

Q8400 Win7 Normal AIx
Rush me More 7xAI 33min. OK
Rush me More 7xAI 37min. OK
Rush me More 7xAI 14min. OK
Rush me More 7xAI 23min. OK
Rush me More 7xAI 19min. OK
Rush me More 7xAI 10min. OK
Rush me More 7xAI 19min. OK
Rush me More 7xAI 13min. OK
Rush me More 7xAI 18min. OK
Rush me More 7xAI 31min. OK
(10 hours pause)
Rush me More 7xAI 32min. OK
Rush me More 7xAI 34min. OK
Rush me More 7xAI  0min. ERROR1 (Freeze on restart)
Rush me More 7xAI 34min. OK
Rush me More 7xAI 13min. OK
Rush me More 7xAI 19min. OK
Rush me More 7xAI 19min. OK
Rush me More 7xAI 11min. OK
Rush me More 7xAI 22min. OK
Rush me More 7xAI 23min. OK
Rush me More 7xAI 21min. OK
Rush me More 7xAI 24min. OK
Rush me More 7xAI 13min. OK
Rush me More 7xAI 19min. OK
Rush me More 7xAI 20min. OK
Rush me More 7xAI 30min. OK

ERROR1
Freeze after transition screen while zooming to CDR.
(Transition screen is half on the way to fade out. ~50% alpha)

ERROR2
Crash to desktop while initiating Archetype for Sorian AI
Last logline: `info: *AI DEBUG: ARMY \0004\000: Initiating Archetype using SorianMainTurtle`

ERROR3
Game Frozen after ACU kill.
Last logline: `warning: ACU kill detected. Rating for ranked games is now enforced.`

**Comment by aeoncleanse** [comment]
This version has been up for a while now with no crashes overwhelmingly reported.
