### ISSUE TITLE
equalize the hitbox of different T2 pgen for balance purpose

### ISSUE THREAD

**Issue by shalkya** [FAForever/fa#2047]
![image](https://cloud.githubusercontent.com/assets/11618427/26581537/4de08720-453d-11e7-9aea-9ef8747a3f84.png)
in order for janus to kill sera and cybran T2 pgen in 3 passes all the time, like aeon, we need to increase their hitbox since we don't want to increase the damage of the janus or lower T2 pgen's HP.

uef still being kill in 4 passes isn't an issue

**Comment by speed2CZ** [comment]
hitboxes are set according to the unit model, you cant just make the same hitbox for everything so it's hit the same way

**Comment by aeoncleanse** [comment]
Can resize model to fit new box, will be fine

**Comment by Exotic-Retard** [comment]
yeah you know when you have to have a fix for the fix of your fix...

**Comment by CookieNoob** [comment]
![image](https://user-images.githubusercontent.com/21953792/26923267-e11b2530-4c41-11e7-8757-c9389f1e5c22.png)

since the model for sera cant be just enlarged (it's close to the border of the 3x3 rectangle on one side) you would need to adjust the footprint as well if you just make it bigger (which leads to other problems with adjacency for example)...

**Comment by MrRowey** [comment]
@Tagada14 if this is a balance issue I'm sure it can be fixed easily If not i suggested it get closed off as it is not a huge game-changer @Garanas

**Comment by Garanas** [comment]
If this is a big issue you (Tagada) can ask Madmax, but in my opinion we just end up with stretched meshes for minimal balance issues.

**Comment by Tagada14** [comment]
Not really a balance issue, Corsairs and Nothas have no problems, if you target T2 pgens with Janus you should stop micro them so the bombs don't spread anyways and kill 2 pgens in 2 passes. We can close this.
