### ISSUE TITLE
make submerge unit not able to see unit on land

### ISSUE THREAD

**Issue by shalkya** [FAForever/fa#2056]
this is more a balance issue.
as unit on land can't see submerge unit, would be great that submerge unit can't see unit on land.
would remove some unit shooting at other while the other one can't fight back.
that won't really change anything to ACU since theyhave omni anyway.
http://content.faforever.com/faf/vault/replay_vault/replay.php?id=6317487

**Comment by aeoncleanse** [comment]
@JaggedAppliance Do we want this? I'm thinking it will not be easy :/

**Comment by Exotic-Retard** [comment]
its very easy to implement, simply look at the layer change code for air units, also there is already similar code in eq but it does sth different not disable vision

**Comment by shalkya** [comment]
what does it do in EQ ? allow land unit to have water vision ?

**Comment by snufflesAU** [comment]
Wait! Submarines have periscopes! Modern ones even have uplinks to satellites for orbital imagery. They can observe things above water without being observed themselves. 

I don't think it's a fair assumption to say that submersibles in the extreme far future are so poorly designed they cannot spot things above water.

**Comment by shalkya** [comment]
well you can take submarine out of that if you want. Issue still stand for amphibious unit.

**Comment by JaggedAppliance** [comment]
I think this is a good idea for Percies, Othuums, Bricks and Wagners. @Exotic-Retard tell us what the similar code in EQ does please.

**Comment by shalkya** [comment]
![image](https://user-images.githubusercontent.com/11618427/29692262-624776ac-892f-11e7-9865-fd4ddca8316d.png)
![image](https://user-images.githubusercontent.com/11618427/29692304-91516232-892f-11e7-93aa-0ba92d69639d.png)
amphibious unit still can see over the water in develop

**Comment by CookieNoob** [comment]
when it can shoot its main weapon it is not submerged

**Comment by shalkya** [comment]
ok that's fuck up, and i'm not sure that's what jagged wanted. 
Anyways there is percy at top, wagner in middle, and othuum at bottom that were submerged (cannot shoot) and were still able to spot unit and give vision on land.

**Comment by shalkya** [comment]
so now it can't see the opponent unit even if it has the weapon over the water.
