### ISSUE TITLE
can't queue up several OC

### ISSUE THREAD

**Issue by shalkya** [FAForever/fa#2057]
since now auto OC is 5 sec, and normal one is 3.3 sec; we would expect queuing OC would allow to to shoot at every 3.3 sec (more or less). 
But despite having the order queued up, the ACU fire only 1 shoot.

**Comment by aeoncleanse** [comment]
@MrNukealizer or @Uveso think either of you can tackle this?

**Comment by shalkya** [comment]
http://content.faforever.com/faf/vault/replay_vault/replay.php?id=6319332
