### ISSUE TITLE
Stability Test deploy/fafdevelop (3684)

### ISSUE THREAD

**Issue by Uveso** [FAForever/fa#2061]
Test for version deploy/fafdevelop (3684)

Tested on 3 x Windows7, 1 x Windows 10.
Normal and Sorian AIx
Default settings, except unit limit and gamespeed.
No mods enabled.

I7-4790K Win7 Sorian AIx
Planet Shmal 7xAI 62min. OK
Planet Shmal 7xAI 40min. OK
Planet Shmal 7xAI 52min. OK
Planet Shmal 7xAI 32min. OK
Planet Shmal 7xAI 38min. OK
Planet Shmal 7xAI 40min. OK
Planet Shmal 7xAI 30min. OK
Planet Shmal 7xAI 85min. OK
Planet Shmal 7xAI 30min. OK
Planet Shmal 7xAI 40min. OK
Planet Shmal 7xAI 42min. OK
Planet Shmal 7xAI 47min. OK
Planet Shmal 7xAI 36min. OK
Planet Shmal 7xAI 127min. OK
Planet Shmal 7xAI 36min. OK
Planet Shmal 7xAI 35min. OK
Planet Shmal 7xAI 42min. OK
Planet Shmal 7xAI 45min. OK
Planet Shmal 7xAI 45min. OK
Planet Shmal 7xAI 34min. OK

I7-6700 Win10 Sorian AIx
Planet Shmal 7xAI 29min. OK
Planet Shmal 7xAI 58min. OK
Planet Shmal 7xAI 30min. OK
Planet Shmal 7xAI 36min. OK
Planet Shmal 7xAI 39min. OK
Planet Shmal 7xAI 43min. OK
Planet Shmal 7xAI 52min. OK
Planet Shmal 7xAI 41min. OK
Planet Shmal 7xAI 40min. OK
Planet Shmal 7xAI 32min. OK
Planet Shmal 7xAI 37min. OK
Planet Shmal 7xAI 55min. OK
Planet Shmal 7xAI 31min. OK
Planet Shmal 7xAI 29min. OK
Planet Shmal 7xAI 32min. OK
Planet Shmal 7xAI 29min. OK
Planet Shmal 7xAI 31min. OK
Planet Shmal 7xAI 35min. OK
Planet Shmal 7xAI 34min. OK
Planet Shmal 7xAI 30min. OK
Planet Shmal 7xAI 34min. OK

FX-8150 Win7 Normal AIx
Rush me More 2xAI 41min. OK
Rush me More 2xAI 0min. ERROR1 (Freeze on restart)
Rush me More 2xAI 47min. OK
Rush me More 2xAI 40min. OK
Rush me More 2xAI 44min. OK
Rush me More 2xAI 48min. OK
Rush me More 2xAI 31min. OK
Rush me More 2xAI 48min. OK
Rush me More 2xAI 50min. OK
Rush me More 2xAI 47min. OK
Rush me More 2xAI 34min. OK
Rush me More 2xAI 28min. OK
Rush me More 2xAI 38min. OK
Rush me More 2xAI 37min. OK

Q8400 Win7 Normal AIx
Rush me More 2xAI 21min. OK
Rush me More 2xAI 82min. OK
Rush me More 2xAI 48min. OK
Rush me More 2xAI 40min. OK
Rush me More 2xAI 26min. OK
Rush me More 2xAI 36min. OK
Rush me More 2xAI 55min. OK
Rush me More 2xAI 29min. OK
Rush me More 2xAI 41min. OK
Rush me More 2xAI 31min. OK

ERROR1 (Freeze on restart)
Freeze after transition screen while zooming to CDR.
(Transition screen is half on the way to fade out. ~50% alpha)

**Comment by aeoncleanse** [comment]
This version has been up for a while now with no crashes overwhelmingly reported.
