### ISSUE TITLE
New map filter hides maps it shouldn't

### ISSUE THREAD

**Issue by speed2CZ** [FAForever/fa#2087]
So I have 3 version of first Aeon mission in my map folder
first one you see is my dev version with `map_version = 3,` in the scenario file, others are v8 and 9 but the game isn't showing any
![forgedalliance_2017-06-26_12-48-32](https://user-images.githubusercontent.com/10947024/27536090-eadaf64c-5a6d-11e7-86e4-9f999f75067e.png)

And same applies for FA mission 1 and 5, also not showing

![explorer_2017-06-26_12-50-58](https://user-images.githubusercontent.com/10947024/27536159-3eaf2aae-5a6e-11e7-9979-bf6d298dc11c.png)

**Comment by CookieNoob** [comment]
this is not a bug, these maps are blacklisted.
https://github.com/FAForever/fa/blob/develop/etc/faf/mapblacklist.lua#L900

If these are not supposed to be blacklisted, then I suggest to remove them from the blacklist.
