### ISSUE TITLE
AIx crash FAF latest

### ISSUE THREAD

**Issue by virtualized** [FAForever/fa#2108]
`EXCEPTION_ACCESS_VIOLATION (0xc0000005) at address 0x0090ad86
    attempted to read memory at 0xf3ddec7d

Program : C:\ProgramData\FAForever\bin\ForgedAlliance.exe
Cmd line arguments : /mean 1525.4 /deviation 314.714 /country GB /init init_faf.lua /numgames 4 /log C:\ProgramData\FAForever\logs\game.log /nobugreport /savereplay gpgnet://localhost/6466752/***.SCFAreplay /gpgnet 127.0.0.1:50318

Callstack:
	Unknown symbol (address 0x0090ad86)
	Unknown symbol (address 0x00914412)
	Unknown symbol (address 0x129d9c7b)`

See replays: 6466752

Crash seems specific to AI Aeon only (not 100% sure).

**Comment by virtualized** [comment]
Another crash different user replay: 6497614

**Comment by MrRowey** [comment]
Dated Issue and no information provide on how to replicate
