### ISSUE TITLE
hives doesn't reclaim building 

### ISSUE THREAD

**Issue by shalkya** [FAForever/fa#2113]
when they are assisting an ACU/engie that is reclaiming a building.
http://content.faforever.com/faf/vault/replay_vault/replay.php?id=6478799
logs : https://gist.github.com/shalkya/a735e9a099fe3adf162d0d1488168085

**Comment by Uveso** [comment]
#1375 
Maybe its beause we removed the hive from EngineerBuildAI plan ?

**Comment by MrNukealizer** [comment]
I don't think that's it. This also affects Kennel drones, yet ACU drones act like normal engineers. I'm thinking it's something with the auto-assist system but I can't track it down.

**Comment by Uveso** [comment]
Ah ok. I was a litte bit afraid that #1375 wrecked it :)

**Comment by MrRowey** [comment]
Duplicated
