### ISSUE TITLE
t2 hq factory can upgrade to t2 support factory

### ISSUE THREAD

**Issue by CookieNoob** [FAForever/fa#2119]
I dont really know why this happens, my suspicion is that the player used a factory template which contained an upgrade to a t2 support factory.

The t2 hq factory upgraded to a t2 support factory while draining no mass nor power using approximately the buildtime of a t2 support factory. It was using the t2hq->t3hq upgrade animation.

No errors in the log.

content.faforever.com/faf/vault/replay_vault/replay.php?id=6536304
it happens at minute 10 for the red player (the t2 land hq)

reported here: http://forums.faforever.com/viewtopic.php?f=3&t=14909#p152396

**Comment by 4z0t** [comment]
Any confirmations?

**Comment by Garanas** [comment]
Doesn't happen anymore.
