### ISSUE TITLE
sera destro miss T1 cybran torpedo launcher

### ISSUE THREAD

**Issue by shalkya** [FAForever/fa#2120]
i thought that was already reported, but can't find the issue.

![image](https://user-images.githubusercontent.com/11618427/28525773-a64a553a-7085-11e7-9173-2f4d0967ab45.png)

it's possible to hit the torpedo launcher, but you kind need to find the good spot. I would say if you give a attack order chance are you won't hit the torpedo launcher at all.

**Comment by shalkya** [comment]
replay : content.faforever.com/faf/vault/replay_vault/replay.php?id=6543136
log : https://gist.github.com/shalkya/b9c15ee9496ded525e9dfb670131386b

**Comment by CookieNoob** [comment]
can you check the position of the target bone and the hitbox of the model? (there are debug keys for that)

**Comment by shalkya** [comment]
not sure if that's what you wanted 
![image](https://user-images.githubusercontent.com/11618427/29456555-7b59809a-8416-11e7-9df4-db710aa2d94c.png)

**Comment by CookieNoob** [comment]
yea thats the hitbox of the launcher. It looks like it is exactly how it should be.

can you post another picture of the bones? I think the debug key for that is alt+v or alt+b. (I am currently in a train and dont have sup com here xD )

**Comment by shalkya** [comment]
![image](https://user-images.githubusercontent.com/11618427/29458109-ceecc9c2-841d-11e7-94ea-1ba4fc918695.png)
should be that hopefully

**Comment by CookieNoob** [comment]
I added the overwater targetbone to the blueprint, let's hope it fixes that...

I'll make a PR when I am back home and did some testing.

**Comment by CookieNoob** [comment]
yea fix works
![grafik](https://user-images.githubusercontent.com/21953792/29464722-05cce288-8437-11e7-96b6-b66e6ea1d425.png)
