### ISSUE TITLE
System messages get localised at the sender, not the receiver

### ISSUE THREAD

**Issue by ChrisKitching** [FAForever/fa#214]
As a result, messages sent from clients with different language options don't appear in my language.

The system should really send the string identifier and parameters over the network and call the appropriate LOC/LOCF function at the receiver, so system messages are always in a language you can understand.

**Comment by aeoncleanse** [comment]
Is this done as of 3641 or lobby 2.7?

**Comment by Sheeo** [comment]
Negative, but it shouldn't be a big deal.

**Comment by duk3luk3** [comment]
I think something went wrong with this. See #861 and http://i.imgur.com/qjB82PW.png
