### ISSUE TITLE
weird behaviour of bomber

### ISSUE THREAD

**Issue by shalkya** [FAForever/fa#2140]
known old bug, with bomber acting retard, related to elevation change. hard to reproduce.

http://content.faforever.com/faf/vault/replay_vault/replay.php?id=6597230
you can watch recent occurrence on this replay, bomber at the top from 3:35 to 4:05

it is annoying one (though it is rare), but i'm not sure if this bug is fixable.

**Comment by CookieNoob** [comment]
I dont think this is fixable, maybe it can be reduced by tweaking the parameters of the bomber. Thats really difficult though, since the bug itself is so hard to reproduce. Thus you cant be sure if the potential fix really worked or not

**Comment by zlo-faf** [comment]
While bomber is turning one direction (e.g. clockwise) tell it to turn ~100-180 degree other direction ( counter clockwise) telling it to do 180 degree turns does work, but i think anything that is more than 90 degree also makes it derp around (i think). The amount of time that bomber spends spinning around feels random to me, tho i have only spent like 5 minutes testing.
[LastGame.zip](https://github.com/FAForever/fa/files/1204244/LastGame.zip)
sorry for not having fafreplay file, i may upload it later. FA version in replay is 3684

**Comment by MrRowey** [comment]
Dated issuse
