### ISSUE TITLE
change symbols of subs when they are submerged/emerged

### ISSUE THREAD

**Issue by shalkya** [FAForever/fa#2146]
This would help greatly to be able to notice if the subs is either submerged/emerged when you are not zooming in.
Especially for the seraphim destroyer. But also T1, T2, T3 subs, atlantis and tempest.
here some ideas for seraphim destroyer : 
submerged : 
![test](https://user-images.githubusercontent.com/11618427/29291589-526d6b8a-8144-11e7-9330-bc6701d84f4e.png)

emerged : 
![test](https://user-images.githubusercontent.com/11618427/29291609-6a2b677c-8144-11e7-8aa6-8770a147434b.png)

btw if we do something like that, would be nice to keep some regularity. Like (for exemple) making all submerged subs with grey color, and all emerged with black one.

**Comment by MrNukealizer** [comment]
I don't think a unit's icon can be changed on the fly like that. I think it's a blueprint value.

**Comment by speed2CZ** [comment]
Yeah, I also think this can't be done

**Comment by MrRowey** [comment]
@Garanas don't see this being something that needed / can even be done with the strategic over lay as it defined in the bp file
