### ISSUE TITLE
depth charge can spot stealth acu

### ISSUE THREAD

**Issue by shalkya** [FAForever/fa#2148]
this lead T2 aeon torpedo bomber, T3 aeon torpedo bomber and CZAR the possibility to spot stealth acu by ground fire in the area, and then target it manually. 
moreover the time the acu is visible is quite long, and i think the area the depth charge can spot the acu is quite big. Lastly depth charge don't need to go into water, eg : you ground fire in water, but there is a mountain stopping depth charge, it will still make acu visible.
replay : content.faforever.com/faf/vault/replay_vault/replay.php?id=6634841
log : https://gist.github.com/shalkya/509d210be758d238302c4453c6669142

**Comment by CookieNoob** [comment]
this seems to be intentional... there is code specifically to make the area around the impact visible:
https://github.com/FAForever/fa/blob/develop/projectiles/AANDepthCharge03/AANDepthCharge03_script.lua#L66

So do we want to remove that code or just leave it as it is? I think this is a balance issue, so maybe @JaggedAppliance can say something about that?

```
    OnImpact = function(self, TargetType, TargetEntity)
        #LOG('Projectile impacted with: ' .. TargetType)
        self.HasImpacted = true
        local pos = self:GetPosition()
        local spec = {
            X = pos[1],
            Z = pos[3],
            Radius = 30,
            LifeTime = 10,
            Omni = false,
            Vision = false,
            Army = self:GetArmy(),
        }
        local vizEntity = VizMarker(spec)
        ADepthChargeProjectile.OnImpact(self, TargetType, TargetEntity)
    end,
```

**Comment by CookieNoob** [comment]
the radius and the duration could be reduced as well instead of removing it

**Comment by JaggedAppliance** [comment]
It shouldn't be removed but I may consider changing the values.

**Comment by CookieNoob** [comment]
ok then the issue can be closed. @aeoncleanse :)

**Comment by shalkya** [comment]
After thinking about it the aeon is the only faction that don't have amphibious tank to spot an stealth acu in a pound even at t3.
The only way (apart from depth charge) are using acu, scu, gc, building something to get water vision, t3 scout and omni
