### ISSUE TITLE
hotbuild extra keys shift bug

### ISSUE THREAD

**Issue by PhilipJFryFAF** [FAForever/fa#2155]
when holding down shift you can't use hotbuild extra keys
no errors in the log

**Comment by Bra1nwash3d** [comment]
Only default hotbuilding keys are granted a shift-version by default:
https://github.com/FAForever/fa/blob/develop/lua/keymap/keymapper.lua#L256

**Comment by MrNukealizer** [comment]
Actually I think the problem is here: https://github.com/FAForever/fa/blob/develop/lua/keymap/hotbuild.lua#L176
HotBuild seems to have some hard-coded behavior involving shift that doesn't play well with the hotkey setup.
