### ISSUE TITLE
split move order

### ISSUE THREAD

**Issue by shalkya** [FAForever/fa#2165]
would it be possible to have a split move order ?
we have on shift g : split attack order + split move only for 1 move order

i think would be nice to shift give several move order, and to press a key that make all unit split in groups of the same size to reach the different places selected by the different move order.

so this would be a split move order that work like a attack order (though unit won't travel to the other places afterward)

**Comment by MrNukealizer** [comment]
Check out the Spread Move mod. That should do what you're talking about. It would be trivial to integrate if that's the way we want to go.

**Comment by shalkya** [comment]
Thanks for the tip ! 
Yeah might consider integrate it at some point

**Comment by shalkya** [comment]
so i tested it, but units are still going to other rally point afterward, maybe this would be better that they stay after reaching 1st rally point; what do you think ?
is it doable ?

**Comment by MrNukealizer** [comment]
Yes it is. I originally designed it for someone who specifically asked for the same behavior as spread attack so I didn't change anything except the orders affected. I need to look over the spread attack code again anyway so I'll see about integrating a move version if @aeoncleanse agrees.

**Comment by MrRowey** [comment]
@Garanas this can be closed if you don see this getting added any time soon as it exists as a Ui mod for people who want ti at this moment in time
