### ISSUE TITLE
cybran build drones dont activate idle state when target is destroyed

### ISSUE THREAD

**Issue by CookieNoob** [FAForever/fa#2167]
warning: Error running lua script from destroyed thread: IssueMoveOffFactory: Passed in an invalid target point.
         stack traceback:
         	[C]: in function `IssueGuard'
         	...\gamedata\units.nx2\units\ura0001\ura0001_script.lua(111): in function <...\gamedata\units.nx2\units\ura0001\ura0001_script.lua:103>

**Comment by speed2CZ** [comment]
maybe smth like this? check if the focused unit is dead
```LUA
    BuildState = State {
        Main = function(self)
            local focus = self.spawnedBy:GetFocusUnit()

            if not focus or focus.Dead then
                ChangeState(self, self.IdleState)
            end

            IssueClearCommands({self})
            IssueGuard({self}, focus)
        end,
    },
```
