### ISSUE TITLE
log gametime every 30 seconds

### ISSUE THREAD

**Issue by CookieNoob** [FAForever/fa#2169]
this would be quite helpful to identify the time when something happened in the log

**Comment by MrNukealizer** [comment]
It might also be possible to override the sim warning function to include the time in the messages themselves.

**Comment by CookieNoob** [comment]
that would be even better

**Comment by MrNukealizer** [comment]
That can be hooked. Unfortunately it seems the warnings when there's an actual error do indeed come from an engine function. Since those are the most important messages, it seems adding a timestamp to the messages themselves is impossible.
