### ISSUE TITLE
Arty drains resources for loading before it's finished

### ISSUE THREAD

**Issue by speed2CZ** [FAForever/fa#2172]
Start any arty structure or UEF T3 PD (or whatever needs energy to shoot) and you get this:

![obrazek](https://user-images.githubusercontent.com/10947024/29486541-9f0d2550-84e8-11e7-8764-5a2e9bb4b782.png)

No error in the log

**Comment by aeoncleanse** [comment]
Wow. This bug goes right back all the way to 3606. It's a base game bug! Nicely found! @CookieNoob fancy squishing this?
