### ISSUE TITLE
make sniper stabilize before shooting in attack move

### ISSUE THREAD

**Issue by shalkya** [FAForever/fa#2179]
if you give attack move, there is super high chance the sniper with just miss at his max range (even against static unit). Making attack not really useful at least for the first shot.

**Comment by MrRowey** [comment]
@Tagada14 If this is still something that doesn't need looking into can you close please :)

**Comment by MrRowey** [comment]
Closing for not Balance team can Reopen if needed

**Comment by Tagada14** [comment]
We are planning on rebalancing the snipers either for July patch or one after it so there is a high chance this will be addressed in some way. Can Keep it closed for now.
