### ISSUE TITLE
torpedo com in attack move don't stop at max range in water

### ISSUE THREAD

**Issue by shalkya** [FAForever/fa#2180]
it will go to the gun upgrade (even the none upgraded gun upgrade ones !)

i guess it will check if there is a weapon upgrade and automatically stop at gun upgrade range (even if there is no gun upgrade) or something, would be nice to stop at max torpedo range.

**Comment by CookieNoob** [comment]
this is already fixed in #2163 
can be closed @aeoncleanse or @shalkya

**Comment by shalkya** [comment]
this isn't fix.

**Comment by MrNukealizer** [comment]
So you're saying you encountered this in FAF Develop after today's changes?

**Comment by shalkya** [comment]
yes there are the report we are doing of faf develop : https://docs.google.com/spreadsheets/d/1gArLgziCWwc5ZMRNtEdVHa_cfVkQ3vWnqMSi7g5dS5I/edit#gid=0

**Comment by CookieNoob** [comment]
thats really strange... the fix for the targeting is exactly the same as the fix for the attack move

**Comment by MrNukealizer** [comment]
But did it increase GuardScanRange?

**Comment by CookieNoob** [comment]
uhm xD yea I think I didnt do that

**Comment by MrNukealizer** [comment]
Speaking of which, I don't know if it affects ACUs or only engineers, but increasing GuardScanRange seems to affect reclaim range too.

**Comment by shalkya** [comment]
here is a fresh replay of it in develop : http://content.faforever.com/faf/vault/replay_vault/replay.php?id=6659455
and logs : https://gist.github.com/shalkya/8097efea04555ae722efa2dccb97987d

**Comment by shalkya** [comment]
this has not been i fixed, but are we even gonna fix it since of the issue of com wandering away if it assist an unit ?

**Comment by aeoncleanse** [comment]
We're gonna try :) Test it thoroughly, it should behave quite nicely

**Comment by CookieNoob** [comment]
![grafik](https://user-images.githubusercontent.com/21953792/29691187-72c37274-892a-11e7-85e6-4707e012089c.png)

in my tests it worked nicely...

the wandering off shouldnt be a problem as there is a different bp value that controls it (hopefully)

**Comment by shalkya** [comment]
it doesn't work when the com didn't go land.
eg, you upgrade in water, and don't go on land afterward. then it get into gun range like before.

**Comment by CookieNoob** [comment]
ok I'll fix that (would have been helpful to mention that :P)

**Comment by shalkya** [comment]
didn't have found it before, just reported the fact it wasn't working, and was trying to understand why.
