### ISSUE TITLE
OC while being in no fire

### ISSUE THREAD

**Issue by shalkya** [FAForever/fa#2182]
You can OC while being in no fire. Not sure if that's intended, i'm just warning people here.

**Comment by MrNukealizer** [comment]
That definitely seems intended. It's a targeted order that's largely independent of automatic attacking.

**Comment by CookieNoob** [comment]
yea I agree, this is definetely intended

**Comment by shalkya** [comment]
ok so just to be clear (maybe i was the only one not aware of it); a cybran cloack ACU can fire OC while being in no fire at some exp. Which mean it's harder to localize it and ground fire it when you don't have omni nearby. Just showing how this can be abuse/use in game.

**Comment by MrNukealizer** [comment]
Or you could just set it to fire, overcharge, then hold fire again before it can fire a second shot.

**Comment by shalkya** [comment]
yes but this would take "much" more micro (i'm not saying it's op or else)
at least it's more convenient in this situation for the player using cloack ACU

**Comment by aeoncleanse** [comment]
Given how weak cloak is this is so not an issue.
