### ISSUE TITLE
properly cleanup shield threads after death

### ISSUE THREAD

**Issue by CookieNoob** [FAForever/fa#2183]
WARNING: Error running lua script: ...rogramdata\faforever\gamedata\lua.nx2\lua\shield.lua(218): Game object has been destroyed
         stack traceback:
         	[C]: in function `GetArmy'
         	...rogramdata\faforever\gamedata\lua.nx2\lua\shield.lua(218): in function <...rogramdata\faforever\gamedata\lua.nx2\lua\shield.lua:217>

The script needs a few checks if the shield is still alive

**Comment by speed2CZ** [comment]
Or maybe this thread just needs to be added into trash https://github.com/FAForever/fa/blob/develop/lua/shield.lua#L181
