### ISSUE TITLE
Lobby map version check incorrectly says map is outdated

### ISSUE THREAD

**Issue by MrNukealizer** [FAForever/fa#2194]
Something is wrong with the map version check when leaving the options screen. I just reproduced it with FA mission 5 in coop. I downloaded version 16 when creating the game, went to the options, clicked OK, and the game said `The currently selected map is outdated and/or unbalanced. Please download the latest version from the map vault.` I have versions 13 and 16 on my computer and in the options it clearly said version 16 was selected.

**Comment by CookieNoob** [comment]
https://github.com/FAForever/fa/blob/develop/etc/faf/mapblacklist.lua#L1663

it's on the map blacklist

**Comment by MrNukealizer** [comment]
Well that's lovely. Now to get to the bottom of why new coop maps are being published with versions that were blacklisted 2 years ago...

**Comment by CookieNoob** [comment]
actually in the coop map repo the map is stored as version 3:
https://github.com/FAForever/faf-coop-maps/blob/master/X1CA_Coop_005/X1CA_Coop_005_scenario.lua#L9
maybe @speed2CZ knows more about this

related (duplicate issue): https://github.com/FAForever/fa/issues/2087

**Comment by MrNukealizer** [comment]
[Here](https://github.com/FAForever/fa/commit/312c231f516a98144f5da36f82c918fa02514ac4#diff-88ea9b2f24e91c955400419ebcb4a99cR1630) is where that line was added. It seems there was a problem 2 years ago and the version still hasn't increased past that.

**Comment by CookieNoob** [comment]
ok so remove these maps from the blacklist I guess

**Comment by speed2CZ** [comment]
well the missions's version is increasing properly. With some db check we could find the current versions of all missions and adjust the blacklist.
