### ISSUE TITLE
lack of target bones above water for aeon/uef nuke subs and sera T3 subs

### ISSUE THREAD

**Issue by shalkya** [FAForever/fa#2196]
![image](https://user-images.githubusercontent.com/11618427/29566558-8be29078-874a-11e7-9540-e79215da923c.png)
sera T3 sub
![image](https://user-images.githubusercontent.com/11618427/29566575-962c2706-874a-11e7-80ab-35b6f280105b.png)
aeon nuke sub
![image](https://user-images.githubusercontent.com/11618427/29566583-9c1d834e-874a-11e7-9e1a-ff77e3ea4c20.png)
uef nuke sub

no issue for cybran nuke sub

**Comment by CookieNoob** [comment]
it looks like there are some of the bones above the surface, can you enable the bone names and post the pictures again?

**Comment by shalkya** [comment]
![image](https://user-images.githubusercontent.com/11618427/29566996-1f9e7a88-874c-11e7-8b05-a316f9c9b52f.png)
aeon
![image](https://user-images.githubusercontent.com/11618427/29567010-2b2f51f6-874c-11e7-95c0-2b20fb9249a5.png)
uef
![image](https://user-images.githubusercontent.com/11618427/29567047-5090904a-874c-11e7-9255-24524b67f157.png)
sera

**Comment by CookieNoob** [comment]
thx, I'll make a PR with the fixes when I'm back home

**Comment by shalkya** [comment]
![image](https://user-images.githubusercontent.com/11618427/29691117-2242f7ca-892a-11e7-814d-dd2c8327b4e3.png)
not fixed for uef T3 sub

**Comment by CookieNoob** [comment]
![grafik](https://user-images.githubusercontent.com/21953792/29691382-21b35358-892b-11e7-9f45-4c614d5a53b7.png)

is that at max range? it is working fine for me...

**Comment by CookieNoob** [comment]
ok the hitbox was a bit too small, I'll fix it in a new PR
