### ISSUE TITLE
cybran nuke subs shows wrong ui e consumtion when e stall

### ISSUE THREAD

**Issue by shalkya** [FAForever/fa#2197]
it drains -200, but when you reach e stall it show -20 e on the cybran nuke although it does drain -200 still
![image](https://user-images.githubusercontent.com/11618427/29566775-4332b4ba-874b-11e7-8c5d-d32fdf2e801b.png)

**Comment by CookieNoob** [comment]
this will most likely be fixed with #2192

**Comment by MrNukealizer** [comment]
Agreed, if that happened on FAF Develop. That looks like exactly what's wrong with using the consumed number instead of requested.

**Comment by CookieNoob** [comment]
![grafik](https://user-images.githubusercontent.com/21953792/29584091-ea1d8b6a-8782-11e7-9fb2-dd8eaf78c3ec.png)

yea with the PR it's working properly

**Comment by shalkya** [comment]
ok several thing i want to say before testing up your fix : 
first i can have same screenshot as you (building nuke + stealth on)
![image](https://user-images.githubusercontent.com/11618427/29589393-6241763a-8795-11e7-81d2-f1c0bda91e2e.png)
the 2nd screenshot is too show that aeon has the same UI consumption as cybran (at least UI wise, while cybran should pump 200 more e for stealth)
![image](https://user-images.githubusercontent.com/11618427/29589393-6241763a-8795-11e7-81d2-f1c0bda91e2e.png)
![image](https://user-images.githubusercontent.com/11618427/29589572-070caf22-8796-11e7-8673-174bf0720f2c.png)
another screenshot to show that when you stop building UI doesn't show -200 e from stealth (even if it is still draining)

also i noticed several bug, when you build the nuke, it goes -4500, and then the e consumption drop until 0 and then start again at -4500. this is crazy. + pausing/canceling the nuke doesn't stop the e consumption until it reach 0 and then it's fine.

there is some seriously fuck up thing right there and not only UI wise.

and it does the fucking same with mass going from -40 to 0 and jumping back to -40; when you are in overflow of e.

replay : http://content.faforever.com/faf/vault/replay_vault/replay.php?id=6674567
logs : https://gist.github.com/shalkya/bafe91ed080cd1f89433335258d95321

**Comment by MrNukealizer** [comment]
Oh yeah, building missiles is really buggy when stalling, as noted in #711. It's odd that the stealth consumption doesn't show. I see in the resource panel you're still at -3124 energy, so something is up.

**Comment by CookieNoob** [comment]
I explain how missiles are build in this comment here: https://github.com/FAForever/fa/issues/711#issuecomment-303080789

**Comment by shalkya** [comment]
yeah didn't saw that before cookie, it makes sense now. But it still doesn't explain how this shit still drains e after pausing or stopping the construction of the nuke. (or i didn't see it in explanation)
also, MrNukealizer about the third pic, don't take in count the -3124, that linked to fuck up building of nuke, if i waited a little bit, it will have drop to -180.
actually i will update previous post with better pic, 2nd is same as 1st (when it should show an aeon sub) and i will take screenshot of 3rd when it reach -180

**Comment by CookieNoob** [comment]
`But it still doesn't explain how this shit still drains e after pausing or stopping the construction of the nuke.`

well it still finishes the segment of the missile that it started to build even after canceling the missile (which costs 4k power, so until that is paid, it will drain energy)

**Comment by shalkya** [comment]
yeah i thought about that afterwards, but seems like it's another issue on top of the weird stage-like building of the missile.

**Comment by shalkya** [comment]
it's better now, there is less issue between stealth and consumption of nuke being build.
so there is one still on going : 
![image](https://user-images.githubusercontent.com/11618427/29690536-af6dd852-8927-11e7-947f-421d2072df01.png)
that only happen during the stage, when the stage is finished, then it update correctly. This is triggered by activating/desactivating stealth, which remove the UI cost of the building stage.
also if you activate the stealth while power stalling during the construction of the nuke, it pause the construction of the nuke at the end of the stage.
and the issue of stopping the construction of the nuke doesn't stop the drain of resource until the stage is finish still exist, but i guess i should maybe do another thread about that ?

**Comment by CookieNoob** [comment]
yea its a different issue, make a new one for that

**Comment by MrNukealizer** [comment]
I think the stopping is an example of what was described in #711. When building missiles the consumption for a segment goes down and down and down, so near the end it gets far less than its fair share of resources.

**Comment by shalkya** [comment]
> In each case nuke is building, but doesn't show ui wise.
that only happen during the segment of the nuke, when the segment of the nuke is finished, then it update correctly. This is triggered by activating/desactivating stealth, which remove the UI cost of the building segment of the nuke.

this hasn't been solved, but it has been decided it was of minor importance, since it refresh well at the end of the segment, and there is 300 segments in a nuke.
