### ISSUE TITLE
missile loading at 99% on automatic launching unit

### ISSUE THREAD

**Issue by shalkya** [FAForever/fa#2198]
![image](https://user-images.githubusercontent.com/11618427/29567490-b136a154-874d-11e7-9d31-8fafd3f56dfc.png)
would it be better than missile unit finish their loading cycle. Right now it needs to activate the firing cycle to finish the loading cycle (which stay at 99%).

**Comment by MrNukealizer** [comment]
I think this is an EcoManager issue. The progress bar seems to be at 100% as expected. It wouldn't make sense to reset the progress once the weapon is loaded.

**Comment by shalkya** [comment]
i'm not talking about the 99% showing from EQ, but at the orange reload bar under the green life bar. Feels weird to stop the loading cycle at 99%

**Comment by CookieNoob** [comment]
![grafik](https://user-images.githubusercontent.com/21953792/29590358-b20dd40c-8799-11e7-80df-82ab9541a685.png)

there are actually 2 problems involved in this:
1) the rendering thread stops when the clocktime is 0, thus the last rendering step isnt executed leaving the bar at approx 97%
2) the precision of the clocktime variable. In each iteration of the thread, the clocktime is reduced by 0.1. How it looks in practise is this:
```
2                                                        - 0.1
1.8999999761581                             - 0.1
1.7999999523163                             - 0.1
1.6999999284744                             - 0.1
```
so just adding a `>=` is not sufficient to solve this

**Comment by shalkya** [comment]
not fixed, we are closer to 100% than we ever had but the orange bar is still there.
![image](https://user-images.githubusercontent.com/11618427/29691033-d2dd1134-8929-11e7-9883-49d6560bcd5d.png)

**Comment by CookieNoob** [comment]
yes why would the orange bar vanish?

**Comment by shalkya** [comment]
well when the unit spawn there is not bar, so i would thought that when the load is finish the bar is removed. 
As "no more orange bar" = "ready to fire"
But that may be personal POV, and we can conclude this is solved if you think the bar need to stay.
