### ISSUE TITLE
T2 sera pd reveal upon firing

### ISSUE THREAD

**Issue by shalkya** [FAForever/fa#2203]
T2 sera pd appear to opponent while firing. While being unscouted or even without radar. Though having radar allow to keep the unit as "scouted". 
i think this bug was introduce when we decided to make sera T2 pd lazer visible (since before you could only notice impact of lazer on your unit, and not the whole lazer).
But the current situation isn't bearable either.

log : https://gist.github.com/shalkya/c6c6e5738953120aee33b531bf655f7d
replay : http://content.faforever.com/faf/vault/replay_vault/replay.php?id=6679193

**Comment by duk3luk3** [comment]
As far as I know, we only get one choice here - if we don't reveal the PD, the lazer will stay invisible.

Maybe there is a workaround  by spawning a second lazer effect that originates from the target instead of from the PD, or spawning some particle effects.

**Comment by ChrisKitching** [comment]
I did that older work - and at the time it didn't reveal the unit, but allowed the monkeylord, GC and the t2 sera pd's lasers to be visible.

The trick was to give the unit intel of type vision, for the victim, of size zero. That seemed to be enough to make the renderer show the laser, but not actually the unit. You can still ground-fire at its source, of course, but that's very different.

Soooo yeah. Somewhere in the last 2.5 years someone broke it.

_have fun_ :D

**Comment by Garanas** [comment]
Has been like this for a long time, it is fine to me.
