### ISSUE TITLE
changing factions in lobby removes ]

### ISSUE THREAD

**Issue by CookieNoob** [FAForever/fa#2204]
when the faction is changed, all occurences of `]` in the chat are removed (for example from the names)
`[CookieNoob] blabla `
becomes
`[CookieNoob blabla `

regression from adding the UTF support

**Comment by MrNukealizer** [comment]
There seems to be something more to it than that. It's like the last character of any "word" starting with `[` is removed. For example my FA profile name is Mr Nukealizer so it changes from `[Mr Nukealizer]` to `[M Nukealizer]`.

**Comment by CookieNoob** [comment]
I checked the commits before the UTF stuff and after it and 
574bc20f3fa562675f5a9dc75e1f2f441972e8bd
is broken while
814ef9f427f81f01871c1c34731d564a8c4ffdf1
is working fine

my guess is that some str.length stuff got a -1 too much or something like that. dunno and I'm too lazy too debug it myself

**Comment by MrNukealizer** [comment]
https://github.com/FAForever/fa/blob/develop/lua/maui/text.lua is FUBAR. WrapText is using byte and character counts interchangeably as well as some questionable math and problems identifying line breaks in the text itself. I'm working on it but the fix will need some testing.

**Comment by MrNukealizer** [comment]
Turns out it wasn't as bad as I thought. It just used the UTF8 character-based functions together with the byte-based string.find function.
