### ISSUE TITLE
cancel or pause doesn't affect the segment of the nuke being build

### ISSUE THREAD

**Issue by shalkya** [FAForever/fa#2207]
there is a whole thread about nuke construction and explaining how it works #711 

So here is an issue about stopping or cancelling the construction of the nuke. I will still consume resource until the segment of the nuke is complete. 

a bit more info here : #2197

**Comment by Garanas** [comment]
This is just engine behavior and it is not something that I think we should spent effort on fixing. It's just the way it is, up to the player to work around it.
