### ISSUE TITLE
Random spawns not working

### ISSUE THREAD

**Issue by Sir-Prize** [FAForever/fa#221]
I've hosted some local skirmish games to practice build orders, and I've noted that the order you appear in in the list of players in a lobby dictates which starting location you get even if you have turned  on random spawn. I don't know what I should post to supplement this, but I would imagine if you start a load of games on a team game map with random spawns switched on you'll notice yourself in position 1 every time.

**Comment by Sheeo** [comment]
We got this sorted?

**Comment by Crotalus** [comment]
Yes, seems to be working now
