### ISSUE TITLE
Possible PhantomX change with latest patch?

### ISSUE THREAD

**Issue by aeoncleanse** [FAForever/fa#2211]
`Hey. Local  Phantom junkie reporting. I found that the Default values has changed with the patch for some settings. Only one I am sure of atm is the Bonus Multiplier
It changed from default 100% to default 90% when JeroenDeDauw Added more values to it
He changed the order and default is based on a number`

**Comment by speed2CZ** [comment]
isnt smth like this for the phantom repo?
that sounds like inside hooked lobbyOptions.lua or w/e the file's called.

**Comment by CookieNoob** [comment]
wrong repo @aeoncleanse you should know that!

**Comment by aeoncleanse** [comment]
True. Less likely I forget it here :P
