### ISSUE TITLE
cybran acu can't fire torpedo while building/capturing/assisting/reclaiming unit

### ISSUE THREAD

**Issue by shalkya** [FAForever/fa#2213]
This quite an issue, since often people get T2 with acu to spam aa/torpedo or reclaim/capture an opponent unit.
Also torpedo can fire everywhere around acu while the acu don't need to face the unit he is targeting. This mean that not fire while shooting with gun or lazer (for example) which is not an issue, become a real one here.
this was only reported for reclaiming unit here : #1090 (so little duplicate)

moreover you can actually reclaim wreck and fire torpedo at the same time

_it can't also fire lazer while building/capturing/assisting/reclaiming unit. But this isn't really important since lazer can only fire in front, so this is just annoying if you want to reclaim opponent unit while firing lazer to increase dps (but dps done by reclaiming is so low in comparaison to lazer that it doesn't really mater).
Fun fact though, ACU need to get the order to stop firing lazer, which doesn't happen when you order it to reclaim an unit (so a bug fix another bug, kinda)._

here a replay in faf develop : http://content.faforever.com/faf/vault/replay_vault/replay.php?id=6688056

**Comment by CookieNoob** [comment]
duplicate, so close either this one or the other

**Comment by MrRowey** [comment]
@Garanas surly this make sense that it cant shoot torps when building as it the same as if on land if your doing the said about you cant shoot so I'm going to close this issue.
