### ISSUE TITLE
amphibious unit shooting with main canon while in water won't make shooting sound

### ISSUE THREAD

**Issue by shalkya** [FAForever/fa#2235]
![image](https://user-images.githubusercontent.com/11618427/29946770-eaffec82-8ea6-11e7-9bf8-97120b6dc1d1.png)
![image](https://user-images.githubusercontent.com/11618427/29946809-15894048-8ea7-11e7-8512-8e5fd2420f4f.png)
![image](https://user-images.githubusercontent.com/11618427/29946946-a2e8ab18-8ea7-11e7-85a5-4b162e843ebd.png)

they are actually shooting, we can't see the animation, can't hear the noice from shooting either, and we can't see the bullet while zoomed in, from the point of view of the player having the amphibious unit.

and from the point of view of the player having the unit getting shoot at, we can hear sound of bullet impacting the unit, and we can see the bullet. 

most likely introduced by this #2056

**Comment by shalkya** [comment]
This bug is in the develop version of the game.
Though the issue of not having the shooting sound already exist in the current game. 
so develop only introduce : not having the animation of firing unit + not being able to see the shot from the player owning the unit firing.

**Comment by shalkya** [comment]
the bug that was in develop isn't here anymore, there is still the sound issue. ie, no sound when firing.

**Comment by Garanas** [comment]
As far as I am aware units that are underwater do not play any sounds. This appears to be on purpose by the engine. It appears to have four aspects:

- (1) Whether a unit produces sound and/or is visible intel-wise depends on the layer. Units that are underwater produce no sound.
- (2) Whether a unit renders or not depends on your vision. There's also 'water vision' which is invisible to the user but it affects underwater units.
- (3) Whether a weapon can fire or not depends on the location of the weapon in relation to the water surface. Weapons have a flag that indicates it can fire from underwater. The moment the weapon emerges it can fire, but that may not align with (1) and (2)
- (4) Whether a unit can be targeted depends on the layer and whether the unit in question can target that layer. This again may not align with (1), (2) or (3)

Even though this is annoying, it is just how the engine works.
