### ISSUE TITLE
quantum gateway and engies stations doesn't appear in the idle list

### ISSUE THREAD

**Issue by shalkya** [FAForever/fa#2237]
![image](https://user-images.githubusercontent.com/11618427/29996518-813654a2-9000-11e7-8804-188d5a010735.png)
there is no icon for idle quantum gateway and engies stations on the top right list of idle unit. There is for sacu, engie, facto, acu, but not for quantum gateway and engies stations.

**Comment by Exotic-Retard** [comment]
im not sure engie stations should appear tbh. they autoassist everything anyway and just adding that button there for the one in a million case where you build them then turn auto assist off or mess something up some other way is a bit much for cluttering up the ui.

quantum gates are alright i guessss. but still borderline imo

both this and the show engies per faction would benefit from a ui that only shows these buttons when applicable tbh.
