### ISSUE TITLE
Crash using brewlan on FAF

### ISSUE THREAD

**Issue by Pop000100** [FAForever/fa#2243]
using the latest version of BrewLan from the Moddb 0.7.5.5
i am using Develop branch of FAF LUA since it fixes another crash from BrewLan 0.7.5.5
vanilla FA didn't seem to crash 
it was a coop lan game

Contains Logs and the replay it crashes at the end
[Crash.zip](https://github.com/FAForever/fa/files/1273605/Crash.zip)

edit: i forgot to mention Seraphim sorian ai don't seem to cause it to happen seems to just be UEF and Cybran we don't like to face Aeon so i am unsure about them

tell me if you need anything else

**Comment by MrRowey** [comment]
@Garanas Close due to this a Mod Related and Balthazar even closed the issue on the BrewLan GitHub page
