### ISSUE TITLE
attack move UI button always disabled

### ISSUE THREAD

**Issue by PhilipJFryFAF** [FAForever/fa#2244]
the new UI button for attack move is disabled all the time in 3686
works fine in 3684
![image](https://user-images.githubusercontent.com/24656673/30101111-69be95a8-92eb-11e7-9d9d-b621e5d6f723.png)

**Comment by aeoncleanse** [comment]
Guilty: https://github.com/FAForever/fa/commit/8b83de6076bc6dfd5e71c649927829afb9d8ac35
