### ISSUE TITLE
negative nuke sub missile count

### ISSUE THREAD

**Issue by PhilipJFryFAF** [FAForever/fa#2251]
somehow a player managed to fire 2 nukes from a nuke sub with one loaded missile in 6773677 (around min 42) which bugs out the sub and lets you shoot missiles despite having none (or rather less than none) loaded

**Comment by PhilipJFryFAF** [comment]
[6773677-LordPunska.zip](https://github.com/FAForever/fa/files/1306716/6773677-LordPunska.zip)
local replay file of the user who reported the bug (replay on the vault appears to be corrupted)
(replay log)[replay_nukespam.zip](https://github.com/FAForever/fa/files/1306718/replay_nukespam.zip)

**Comment by MrRowey** [comment]
dated issue. not steps on hot to reporduce
