### ISSUE TITLE
tml acu keeps moving after stop command

### ISSUE THREAD

**Issue by PhilipJFryFAF** [FAForever/fa#2252]
when giving a stop command to an acu with an tml command out of range (so it has to walk closer) it will walk all the way to the attack command destination when using the stop command
[replay](6792840)
[forum thread](http://forums.faforever.com/viewtopic.php?f=2&t=15155)

**Comment by shalkya** [comment]
replay link doesn't work

**Comment by MrRowey** [comment]
Dated Issuse
