### ISSUE TITLE
sat stuck in novax

### ISSUE THREAD

**Issue by shalkya** [FAForever/fa#2256]
not sure what happen during this test, i put replay and log.
replay : content.faforever.com/faf/vault/replay_vault/replay.php?id=6811085
game log : https://gist.github.com/shalkya/7cdaf3cbc04a573a9b805af0a3d07d83
forever log : https://gist.github.com/shalkya/e4bd005c17db20a3c0577844e5d970aa

it starts building the sat at 8:30 and start to release but fail at 9:15.
it's the second novax started from right.

**Comment by HUSSAR-mtrela** [comment]
this is most likely caused by an issue with queuing multiple satellites. Novax center does not work like a factory which support queuing units. Script for Novax center should inherit from factory/construction class

**Comment by MrRowey** [comment]
Dated issue. not steps to reproduce or had another complaints about it
