### ISSUE TITLE
Missing texture on a tree

### ISSUE THREAD

**Issue by speed2CZ** [FAForever/fa#2258]
```INFO: Can't find texture "/env/lava/props/trees/xDead01_s1_normalsTS.dds" -- trying fallback```
These trees are on Haven's Reef (X1MP_004)

The game is complaining but I don't see anything bad with them on the first look.

**Comment by badbwoi** [comment]
that dds is indeed missing but the file is linked in the blueprint.
Each lava tree should have one "..._s1_normalsTS.dds" file, but only one is present.

Dead01_s1_normalsTS.dds (present)
LV_Dead01_s1_normalsTS.dds (missing)
XDead01_s1_normalsTS.dds (missing, but tree only differs in color from "Dead01_s1" and not in shape)

I replaced the missing friles with the "Dead01_s1_normalsTS.dds", but no visible change could be detected.

**Comment by MrRowey** [comment]
![image](https://user-images.githubusercontent.com/20344151/130026191-d0c3e436-19b3-432f-97b0-c55828b859a0.png)
Still and Issue With Original Version and FAF Version of the Map
