### ISSUE TITLE
Observers can change armyview

### ISSUE THREAD

**Issue by PhilipJFryFAF** [FAForever/fa#2259]
Observers can use the "setarmyview" command to go from obs to an army view and then write messages and set map markers
that should not be possible since observers can see the entire map and thus can give vital information that might not be available otherwise

**Comment by speed2CZ** [comment]
Each time when you send message or set marker in different army view the game says you're trying to cheat but doesn't stop it.

**Comment by aeoncleanse** [comment]
Phil, could this be a side effect of sharedarmies exe hack?

**Comment by PhilipJFryFAF** [comment]
not sure
speed2 doesn't have that exe but i do
gonna test again with the regular exe

**Comment by PhilipJFryFAF** [comment]
tested again and same issue
doesn't seem to be related to the exe

**Comment by aeoncleanse** [comment]
I can't find a command called setarmyview. Sure you don't mean SetFocusArmy?

**Comment by speed2CZ** [comment]
yeah that one

**Comment by shalkya** [comment]
just need to use the cheat panel and get into the player view. Then you can ping, and use ping (with writing).
it's not related to sharearmy.exe
