### ISSUE TITLE
Calling WaitTicks waits one tick less than requested

### ISSUE THREAD

**Issue by MrNukealizer** [FAForever/fa#2268]
I first noticed this when working on #2267. It seems `WaitTicks(2)` only waits one tick, and calling `WaitSeconds(1)` only waits 9 ticks. I'm not sure what problems this might cause besides incorrect shield regen, but if the timing for every sim-side wait of more than 1 tick is off, there could be other symptoms we haven't noticed.

**Comment by aeoncleanse** [comment]
For the next bugfix patch we'll go through and correct all waitticks and waitseconds >1 or >0.1 respectively

**Comment by Exotic-Retard** [comment]
the thing is that in a lot of cases 0.1 actually does work.
i think its rather a question of being inconsistent in the waiting rather than always waiting less than needed.

**Comment by aeoncleanse** [comment]
0.1 works. It's only non-1-tick values that have any issue.

**Comment by MrNukealizer** [comment]
For what it's worth, it would be quite possible to change the function itself to check the value and add 1 if it's greater than 1. Currently WaitTicks is just an alias for coroutine.yield but it could easily be made a proper function. Of course the performance impact could be a concern. If nothing else, we could at least fix WaitSeconds since that's already a lua function that multiplies by 10 and calls WaitTicks.
