### ISSUE TITLE
Dummy weapons on shields and AA causing problems for AI

### ISSUE THREAD

**Issue by speed2CZ** [FAForever/fa#2277]
AI moves around units in formation, before the shields and AA sticked in the formation, protecting what they should have, when other units stopped to shoot, the shields stopped with them and then continues to move together.

Now they stop long before that exposing all units they should be protecting.

I guess with AA it doesnt hurt that much if they stay behind, but shields are a problem.

**Comment by MrRowey** [comment]
@Garanas Close has a Merged PR and everyone seemed to be happy to with the changes with the merge
