### ISSUE TITLE
engies repair ACU instead of assisting it

### ISSUE THREAD

**Issue by PhilipJFryFAF** [FAForever/fa#2279]
assisting a damaged ACU with engies will result in them repairing the ACU instead of supporting whatever the ACU currently does when assisting a structure that is doing an upgrade or when using a repair command on a structure that hasn't been finished yet
reproduced the bugs in [sandbox](replay.faforever.com/6866249)
assist structure upgrade bug in a [real game](replay.faforever.com/6859035)  (happens to bottom air player after getting hit by a Janus early in the game, also check out the strat killing 8 ASF later on over mid)
repair command on unfinished structure in a [real game](replay.faforever.com/6863814) (happens to top rock around 13:30 or so)
special thanks to yolo and farms for reporting the bug

**Comment by MrRowey** [comment]
Dated Issuse

**Comment by Garanas** [comment]
I'd say this isn't a bug - this is choice the engine made: repairing the builder has a higher priority than assisting the unit it is building.
