### ISSUE TITLE
Adjacency with massfabs on mex upgrade

### ISSUE THREAD

**Issue by tobias-strenger** [FAForever/fa#2281]
If you surround a mex with massfabs, the upgrade does only profit from the bonus if you built them before you started the upgrade.
![xx](https://user-images.githubusercontent.com/7430874/31422691-c39f8238-ae4f-11e7-939d-bcdd7e32a2aa.png)

**Comment by speed2CZ** [comment]
That's gotta be the same issue like here https://github.com/FAForever/fa/issues/1843

**Comment by OCGDFS** [comment]
I was aware of that issue, but it works for pgens somehow, wich isnt the case in #1843.

**Comment by MrRowey** [comment]
@Garanas is this something we can fix with a engine patch or do we closes as unfixable ?

**Comment by MrRowey** [comment]
@4z0t do you know if this is possible ?

**Comment by Garanas** [comment]
It's very unlikely to happen as it is ten times better to surround the extractor with storages. It may be a bug, but not one that is worth fixing in my opinion
