### ISSUE TITLE
power storage icon bug

### ISSUE THREAD

**Issue by PhilipJFryFAF** [FAForever/fa#2293]
when you mouse over an energy storage icon then it becomes a power generator icon
short [sandbox](http://replay.faforever.com/6964833) with power storage

**Comment by CookieNoob** [comment]
> when you mouse over an energy storage icon then it becomes a power storage icon

what's the difference between a powerstorage icon and an energystorage icon?? xD

**Comment by PhilipJFryFAF** [comment]
![image](https://user-images.githubusercontent.com/24656673/32105647-7df9cd42-bb29-11e7-90c8-bdfbc8bb1e44.png)

**Comment by CookieNoob** [comment]
well the problem is this:
![grafik](https://user-images.githubusercontent.com/21953792/32132103-880b0096-bbbd-11e7-95eb-3ce815be9f37.png)

the icons for the other cases (except for not selected, not moused over) are icons for pgens xD

**Comment by speed2CZ** [comment]
Let me offer my ideal solution which is bit more work. There are many icons in the base game that are not used. Each icon is usually for no tech, tech 1, tech 2, tech 3. Its same for the pgens.

So I would change this one icon to be the same as the pgen icon (to have it consistent)
Then I'd make a new icon for E storage (and all versions from no tech to tech 3)

I know we don't have tech 3 storages in the base game, but as I said there are more unused icons ready for mods and stuff. And if someone is making the new icon set for storages it shouldnt be two hard to make all techs.
