### ISSUE TITLE
Units with SILO ability should have a new command: Clear/Cancel

### ISSUE THREAD

**Issue by HUSSAR-mtrela** [FAForever/fa#2296]
This issue applies to units with SILO ability:
- TML (Tactical Missile Launcher)
- SML (Strategic Missile Launcher)
- SMD (Strategic Missile Defense)
- T3 Nuke Submarines
- T3 Nuke Battleships (SERA)

Consider this scenario:
- SML has 1 nuke in silo and is 90% done building 2nd nuke
- a player queues NUKE launch at wrong target
- a player clicks on the STOP button to cancel the NUKE launch
- SML stops the NUKE launch but it also stops building 2nd nuke which was almost done

Units with SILO ability should have new command called Clear/Cancel such that it can be used to cancel the last order in the queue.

Expected scenario:
- SML has 1 nuke in silo and is 90% done building 2nd nuke
- a player queues NUKE launch at wrong target
- a player clicks on the CANCEL button to cancel the NUKE launch
- SML cancels the NUKE launch but it does not stop building 2nd nuke

Alternatively, the STOP command should stop order of the launching nuke and stop building nuke missile only if there was no order to launch a nuke.

**Comment by aeoncleanse** [comment]
Player is an idiot. The cancel command function exists to do _exactly_ this. Don't hit stop. You don't want the unit to stop. You want to undo the command. So, like every other unit in the game, you need to go and kill the command.

**Comment by HUSSAR-mtrela** [comment]
I still think it would be nice to have a button in Unit View to cancel the last order instead of CTRL+right clicking on the order in map.

**Comment by speed2CZ** [comment]
The soft stop does the job
