### ISSUE TITLE
aggression range of Cybran ACU

### ISSUE THREAD

**Issue by PhilipJFryFAF** [FAForever/fa#2299]
the range at which a Cybran ACU will engage enemy units while assisting seems to be the torpedo weapon range in the 3690 patch (currently FAF develop)
[sandbox](replay.faforever.com/6998336) game showing the issue
i assume this is being caused by #2188

**Comment by Garanas** [comment]
@Tagada14 I recall you fixed this recently - is that correct? If so, you can close this issue.

**Comment by Tagada14** [comment]
No, I haven't. I changed the sonar's range (for some reason it had a huge radius by default) and I moved the sonar range increase to the Torpedo upgrade.

**Comment by MrRowey** [comment]
Closing for now Balance Team Can Re open if needed
