### ISSUE TITLE
fuel bar hide shield bar on T3 transport

### ISSUE THREAD

**Issue by shalkya** [FAForever/fa#2312]
this is the current situation : 
![image](https://user-images.githubusercontent.com/11618427/32704386-6f81c5ca-c804-11e7-9889-2153391fd087.png)
![image](https://user-images.githubusercontent.com/11618427/32704539-22de60b8-c807-11e7-82eb-50830c62976d.png)

and the fix would end up giving something similar to this : 
![image](https://user-images.githubusercontent.com/11618427/32704546-5f653dae-c807-11e7-8ed0-9887ca9d5d59.png)

PS : you need to look at bottom left

**Comment by PhilipJFryFAF** [comment]
fixed with #2345
