### ISSUE TITLE
unit can survive after death in "share until death" by giving transport with unit inside

### ISSUE THREAD

**Issue by shalkya** [FAForever/fa#2314]
player A give a transport with unit inside to player B
player B un-load the transport
player A die, transport die, unit survive

linked to #2313

bug reproduced here : content.faforever.com/faf/vault/replay_vault/replay.php?id=7048510
logs : https://gist.github.com/shalkya/05865f39b971a671b5538957fc290e53

**Comment by MrRowey** [comment]
duplicate
