### ISSUE TITLE
remove reclaims/repairs labels on sera engies and sparky

### ISSUE THREAD

**Issue by shalkya** [FAForever/fa#2315]
sera T1/T2/T3 engies and the sparky : have the reclaims/repairs label/ability in UI
![image](https://user-images.githubusercontent.com/11618427/32741691-6b558902-c8a7-11e7-9adb-7262fa952cb3.png)
cybran/aeon/uef T1/T2/T3 engies doesn't have this label.
![image](https://user-images.githubusercontent.com/11618427/32741750-9927e73a-c8a7-11e7-9439-a4d36f00cc1a.png)
also reclaims/repairs is missing on all ACU/sACU

**Comment by speed2CZ** [comment]
shouldn't we remove it from sera? Engineering Suite should be enough

Reclaims Repairs is better for mantis/harb who cant do other engie stuff

**Comment by shalkya** [comment]
yeah that would work too, just trying to achieve some consistency.
would need remove of repairs/reclaims sera engies and sparky

**Comment by aeoncleanse** [comment]
I agree with speed2. We should use Suite to describe when a unit can do it all, reserving the single descriptions for units with special cases. Can someone make a PR?

**Comment by speed2CZ** [comment]
I'll do it tomorrow

**Comment by shalkya** [comment]
As uveso said, still missing the change on hives and sparky

**Comment by aeoncleanse** [comment]
I added it directly. It's done
