### ISSUE TITLE
Missing AI Scripts for mobile land T3 AA

### ISSUE THREAD

**Issue by Uveso** [FAForever/fa#2317]
T3 mobile land AA where implemented on 27 Jul 2014 (v1.5.3634) 
( https://github.com/FAForever/fa/commit/016db6d56cc86cf5b25b55bda7c911892069555c#diff-3df097f14555ebc0ddbcf4a5f917681e )

But there are no AI scripts (buildplatoons etc) for mobile T3 AA units.
Means, the AI can't build and use them.

Affected units:
drlk001
delk002
dalk003
dslk004
drlk005

**Comment by speed2CZ** [comment]
It would be also nice if the unit id followed the set format
But I guess that would also require changes to the models to rename the bones and what not

**Comment by Uveso** [comment]
Renaming a unit only needs some changes to the .lua and .bp file.
Also those files needs to be renamed.
That's all, we don't need to change bones or anything like that.

And we sould not forget these game files:
BasicLandAttack_save.lua
unitkeygroups.lua
unitdescription.lua

**Comment by CookieNoob** [comment]
all units have a central bone which is called like the unit id, that should be renamed as well.
