### ISSUE TITLE
Bug: Cheat AI does not build intel units if omni cheat is disabled.

### ISSUE THREAD

**Issue by Uveso** [FAForever/fa#2325]
A cheating AIx normaly don't need intel units or structures because it has Omni-View.

But if the option "AIx Omni Setting" is disabled, the AIx has no Omni-View AND is not building intel Units.

This way we have a chating but weak AIx.

**Comment by MrRowey** [comment]
@Uveso Do you know if this Bug is fixed or not ?

**Comment by MrRowey** [comment]
@Azraeel you know if this is still a bug ?

**Comment by Garanas** [comment]
This is likely still a bug. I'll look into it for the patch of January.

**Comment by Uveso** [comment]
I fixed this on  11 Jun 2018
https://github.com/FAForever/fa/commit/b9a348b881c74e86f74bbab51c7d9e0a6c94898a

AIs are now always building NonCheatBuilders
