### ISSUE TITLE
All supcoms of all players in a team game crashed simultanously

### ISSUE THREAD

**Issue by Justify87** [FAForever/fa#2332]
[7152320-EmptySlot.zip](https://github.com/FAForever/fa/files/1537109/7152320-EmptySlot.zip)
[game.log](https://github.com/FAForever/fa/files/1537111/game.log)

Stack trace:   

 EXCEPTION_ACCESS_VIOLATION (0xc0000005) at address 0x00598eec
    attempted to read memory at 0x000000e4

Program : C:\ProgramData\FAForever\bin\ForgedAlliance.exe
Cmd line arguments : /mean 1866.719386247361 /deviation 96.92132895673214 /country DE /clan N /init init_faf.lua /numgames 1125 /log C:\ProgramData\FAForever\logs\game.log /nobugreport /savereplay gpgnet://localhost/7152320/EmptySlot.SCFAreplay /gpgnet 127.0.0.1:58516

Callstack:
	Unknown symbol (address 0x00598eec)
	Unknown symbol (address 0x00409243)
	Unknown symbol (address 0x00409b2b)
	Unknown symbol (address 0x0074a110)

Last 100 lines of log...

debug: Loading module '\000/units/ueb1301/ueb1301_script.lua\000'
debug: Loading module '\000/projectiles/caaautocannon01/caaautocannon01_script.lua\000'
debug: Loading module '\000/units/url0205/url0205_script.lua\000'
debug: Current gametime: 00:11:00
debug: Loading module '\000/units/uel0205/uel0205_script.lua\000'
debug: Loading module '\000/units/zsb9501/zsb9501_script.lua\000'
debug: Loading module '\000/projectiles/siflaansetacticalmissilecdr/siflaansetacticalmissilecdr_script.lua\000'
debug: Loading module '\000/units/urb4202/urb4202_script.lua\000'
warning: Error running HandleEvent script in CScriptObject at 1bc03700: ...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua(910): attempt to call method `GetArmy' (a nil value)
         stack traceback:
         	...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua(910): in function <...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua:863>
warning: Error running HandleEvent script in CScriptObject at 1bc03700: ...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua(910): attempt to call method `GetArmy' (a nil value)
         stack traceback:
         	...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua(910): in function <...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua:863>
warning: Error running HandleEvent script in CScriptObject at 1bc03700: ...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua(910): attempt to call method `GetArmy' (a nil value)
         stack traceback:
         	...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua(910): in function <...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua:863>
debug: Loading module '\000/units/ueb4202/ueb4202_script.lua\000'
debug: Loading module '\000/units/uaa0303/uaa0303_script.lua\000'
debug: Current gametime: 00:11:30
debug: Loading module '\000/projectiles/sboothetacticalbomb02/sboothetacticalbomb02_script.lua\000'
debug: Loading module '\000/units/zab9502/zab9502_script.lua\000'
debug: Loading module '\000/units/uab1302/uab1302_script.lua\000'
debug: Loading module '\000/projectiles/tifmissilecruise01/tifmissilecruise01_script.lua\000'
warning: Error running HandleEvent script in CScriptObject at 1bc03700: ...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua(910): attempt to call method `GetArmy' (a nil value)
         stack traceback:
         	...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua(910): in function <...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua:863>
warning: Error running HandleEvent script in CScriptObject at 1bc03700: ...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua(910): attempt to call method `GetArmy' (a nil value)
         stack traceback:
         	...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua(910): in function <...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua:863>
warning: Error running HandleEvent script in CScriptObject at 1bc03700: ...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua(910): attempt to call method `GetArmy' (a nil value)
         stack traceback:
         	...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua(910): in function <...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua:863>
warning: Error running HandleEvent script in CScriptObject at 1bc03700: ...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua(910): attempt to call method `GetArmy' (a nil value)
         stack traceback:
         	...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua(910): in function <...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua:863>
warning: Error running HandleEvent script in CScriptObject at 1bc03700: ...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua(910): attempt to call method `GetArmy' (a nil value)
         stack traceback:
         	...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua(910): in function <...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua:863>
warning: Error running HandleEvent script in CScriptObject at 1bc03700: ...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua(910): attempt to call method `GetArmy' (a nil value)
         stack traceback:
         	...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua(910): in function <...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua:863>
warning: Error running HandleEvent script in CScriptObject at 1bc03700: ...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua(910): attempt to call method `GetArmy' (a nil value)
         stack traceback:
         	...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua(910): in function <...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua:863>
warning: Error running HandleEvent script in CScriptObject at 1bc03700: ...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua(910): attempt to call method `GetArmy' (a nil value)
         stack traceback:
         	...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua(910): in function <...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua:863>
warning: Error running HandleEvent script in CScriptObject at 1bc03700: ...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua(910): attempt to call method `GetArmy' (a nil value)
         stack traceback:
         	...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua(910): in function <...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua:863>
warning: Error running HandleEvent script in CScriptObject at 1bc03700: ...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua(910): attempt to call method `GetArmy' (a nil value)
         stack traceback:
         	...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua(910): in function <...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua:863>
warning: Error running HandleEvent script in CScriptObject at 1bc03700: ...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua(910): attempt to call method `GetArmy' (a nil value)
         stack traceback:
         	...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua(910): in function <...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua:863>
warning: Error running HandleEvent script in CScriptObject at 1bc03700: ...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua(910): attempt to call method `GetArmy' (a nil value)
         stack traceback:
         	...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua(910): in function <...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua:863>
warning: Error running HandleEvent script in CScriptObject at 1bc03700: ...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua(910): attempt to call method `GetArmy' (a nil value)
         stack traceback:
         	...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua(910): in function <...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua:863>
debug: Loading module '\000/units/uaa0302/uaa0302_script.lua\000'
debug: Loading module '\000/units/xsb0301/xsb0301_script.lua\000'
debug: Loading module '\000/projectiles/caaburstcloud01/caaburstcloud01_script.lua\000'
debug: Loading module '\000/units/uea0303/uea0303_script.lua\000'
debug: Current gametime: 00:12:00
debug: Loading module '\000/units/xsb4202/xsb4202_script.lua\000'
debug: Loading module '\000/projectiles/saashleoaagatlinggun03/saashleoaagatlinggun03_script.lua\000'
warning: Error running HandleEvent script in CScriptObject at 1bc03700: ...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua(910): attempt to call method `GetArmy' (a nil value)
         stack traceback:
         	...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua(910): in function <...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua:863>
warning: Error running HandleEvent script in CScriptObject at 1bc03700: ...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua(910): attempt to call method `GetArmy' (a nil value)
         stack traceback:
         	...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua(910): in function <...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua:863>
warning: Error running HandleEvent script in CScriptObject at 1bc03700: ...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua(910): attempt to call method `GetArmy' (a nil value)
         stack traceback:
         	...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua(910): in function <...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua:863>
warning: Error running HandleEvent script in CScriptObject at 1bc03700: ...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua(910): attempt to call method `GetArmy' (a nil value)
         stack traceback:
         	...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua(910): in function <...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua:863>
warning: Error running HandleEvent script in CScriptObject at 1bc03700: ...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua(910): attempt to call method `GetArmy' (a nil value)
         stack traceback:
         	...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua(910): in function <...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua:863>
warning: Error running HandleEvent script in CScriptObject at 1bc03700: ...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua(910): attempt to call method `GetArmy' (a nil value)
         stack traceback:
         	...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua(910): in function <...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua:863>
warning: Error running HandleEvent script in CScriptObject at 1bc03700: ...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua(910): attempt to call method `GetArmy' (a nil value)
         stack traceback:
         	...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua(910): in function <...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua:863>
debug: Loading module '\000/projectiles/saaolarisaaartillery02/saaolarisaaartillery02_script.lua\000'
debug: Loading module '\000/projectiles/sdfaireaubolter01/sdfaireaubolter01_script.lua\000'
warning: Error running HandleEvent script in CScriptObject at 1bc03700: ...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua(910): attempt to call method `GetArmy' (a nil value)
         stack traceback:
         	...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua(910): in function <...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua:863>
warning: Error running HandleEvent script in CScriptObject at 1bc03700: ...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua(910): attempt to call method `GetArmy' (a nil value)
         stack traceback:
         	...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua(910): in function <...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua:863>
warning: Error running HandleEvent script in CScriptObject at 1bc03700: ...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua(910): attempt to call method `GetArmy' (a nil value)
         stack traceback:
         	...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua(910): in function <...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua:863>
warning: Error running HandleEvent script in CScriptObject at 1bc03700: ...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua(910): attempt to call method `GetArmy' (a nil value)
         stack traceback:
         	...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua(910): in function <...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua:863>
warning: Error running HandleEvent script in CScriptObject at 1bc03700: ...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua(910): attempt to call method `GetArmy' (a nil value)
         stack traceback:
         	...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua(910): in function <...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua:863>
warning: Error running HandleEvent script in CScriptObject at 1bc03700: ...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua(910): attempt to call method `GetArmy' (a nil value)
         stack traceback:
         	...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua(910): in function <...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua:863>
warning: Error running HandleEvent script in CScriptObject at 1bc03700: ...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua(910): attempt to call method `GetArmy' (a nil value)
         stack traceback:
         	...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua(910): in function <...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua:863>
warning: Error running HandleEvent script in CScriptObject at 1bc03700: ...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua(910): attempt to call method `GetArmy' (a nil value)
         stack traceback:
         	...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua(910): in function <...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua:863>
debug: Loading module '\000/units/urb0301/urb0301_script.lua\000'
debug: Current gametime: 00:12:30
warning: Error running HandleEvent script in CScriptObject at 1bc03700: ...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua(910): attempt to call method `GetArmy' (a nil value)
         stack traceback:
         	...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua(910): in function <...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua:863>
warning: Error running HandleEvent script in CScriptObject at 1bc03700: ...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua(910): attempt to call method `GetArmy' (a nil value)
         stack traceback:
         	...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua(910): in function <...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua:863>
warning: Error running HandleEvent script in CScriptObject at 1bc03700: ...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua(910): attempt to call method `GetArmy' (a nil value)
         stack traceback:
         	...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua(910): in function <...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua:863>
warning: Error running HandleEvent script in CScriptObject at 1bc03700: ...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua(910): attempt to call method `GetArmy' (a nil value)
         stack traceback:
         	...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua(910): in function <...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua:863>
warning: Error running HandleEvent script in CScriptObject at 1bc03700: ...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua(910): attempt to call method `GetArmy' (a nil value)
         stack traceback:
         	...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua(910): in function <...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua:863>
warning: Error running HandleEvent script in CScriptObject at 1bc03700: ...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua(910): attempt to call method `GetArmy' (a nil value)
         stack traceback:
         	...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua(910): in function <...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua:863>
warning: Error running HandleEvent script in CScriptObject at 1bc03700: ...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua(910): attempt to call method `GetArmy' (a nil value)
         stack traceback:
         	...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua(910): in function <...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua:863>
warning: Error running HandleEvent script in CScriptObject at 1bc03700: ...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua(910): attempt to call method `GetArmy' (a nil value)
         stack traceback:
         	...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua(910): in function <...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua:863>
warning: Error running HandleEvent script in CScriptObject at 1bc03700: ...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua(910): attempt to call method `GetArmy' (a nil value)
         stack traceback:
         	...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua(910): in function <...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua:863>
warning: Error running HandleEvent script in CScriptObject at 1bc03700: ...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua(910): attempt to call method `GetArmy' (a nil value)
         stack traceback:
         	...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua(910): in function <...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua:863>
warning: Error running HandleEvent script in CScriptObject at 1bc03700: ...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua(910): attempt to call method `GetArmy' (a nil value)
         stack traceback:
         	...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua(910): in function <...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua:863>
warning: Error running HandleEvent script in CScriptObject at 1bc03700: ...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua(910): attempt to call method `GetArmy' (a nil value)
         stack traceback:
         	...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua(910): in function <...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua:863>
warning: Error running HandleEvent script in CScriptObject at 1bc03700: ...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua(910): attempt to call method `GetArmy' (a nil value)
         stack traceback:
         	...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua(910): in function <...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua:863>
warning: Error running HandleEvent script in CScriptObject at 1bc03700: ...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua(910): attempt to call method `GetArmy' (a nil value)
         stack traceback:
         	...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua(910): in function <...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua:863>
debug: Loading module '\000/units/xsb2204/xsb2204_script.lua\000'
debug: Loading module '\000/units/urb2301/urb2301_script.lua\000'
warning: Error running HandleEvent script in CScriptObject at 1bc03700: ...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua(910): attempt to call method `GetArmy' (a nil value)
         stack traceback:
         	...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua(910): in function <...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua:863>
warning: Error running HandleEvent script in CScriptObject at 1bc03700: ...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua(910): attempt to call method `GetArmy' (a nil value)
         stack traceback:
         	...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua(910): in function <...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua:863>
warning: Error running HandleEvent script in CScriptObject at 1bc03700: ...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua(910): attempt to call method `GetArmy' (a nil value)
         stack traceback:
         	...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua(910): in function <...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua:863>
warning: Error running HandleEvent script in CScriptObject at 1bc03700: ...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua(910): attempt to call method `GetArmy' (a nil value)
         stack traceback:
         	...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua(910): in function <...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua:863>
warning: Error running HandleEvent script in CScriptObject at 1bc03700: ...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua(910): attempt to call method `GetArmy' (a nil value)
         stack traceback:
         	...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua(910): in function <...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua:863>
warning: Error running HandleEvent script in CScriptObject at 1bc03700: ...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua(910): attempt to call method `GetArmy' (a nil value)
         stack traceback:
         	...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua(910): in function <...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua:863>
warning: Error running HandleEvent script in CScriptObject at 1bc03700: ...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua(910): attempt to call method `GetArmy' (a nil value)
         stack traceback:
         	...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua(910): in function <...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua:863>
warning: Error running HandleEvent script in CScriptObject at 1bc03700: ...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua(910): attempt to call method `GetArmy' (a nil value)
         stack traceback:
         	...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua(910): in function <...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua:863>
warning: Error running HandleEvent script in CScriptObject at 1bc03700: ...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua(910): attempt to call method `GetArmy' (a nil value)
         stack traceback:
         	...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua(910): in function <...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua:863>
debug: Current gametime: 00:13:00
debug: Loading module '\000/projectiles/tdfginsu01/tdfginsu01_script.lua\000'
debug: Loading module '\000/projectiles/aaaautocannonquantum01/aaaautocannonquantum01_script.lua\000'
debug: Current gametime: 00:13:30
debug: Loading module '\000/units/xsl0303/xsl0303_script.lua\000'
warning: Error running HandleEvent script in CScriptObject at 1bc03700: ...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua(910): attempt to call method `GetArmy' (a nil value)
         stack traceback:
         	...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua(910): in function <...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua:863>
warning: Error running HandleEvent script in CScriptObject at 1bc03700: ...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua(910): attempt to call method `GetArmy' (a nil value)
         stack traceback:
         	...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua(910): in function <...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua:863>
warning: Error running HandleEvent script in CScriptObject at 1bc03700: ...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua(910): attempt to call method `GetArmy' (a nil value)
         stack traceback:
         	...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua(910): in function <...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua:863>
warning: Error running HandleEvent script in CScriptObject at 1bc03700: ...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua(910): attempt to call method `GetArmy' (a nil value)
         stack traceback:
         	...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua(910): in function <...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua:863>
warning: Error running HandleEvent script in CScriptObject at 1bc03700: ...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua(910): attempt to call method `GetArmy' (a nil value)
         stack traceback:
         	...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua(910): in function <...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua:863>
warning: Error running HandleEvent script in CScriptObject at 1bc03700: ...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua(910): attempt to call method `GetArmy' (a nil value)
         stack traceback:
         	...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua(910): in function <...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua:863>
warning: Error running HandleEvent script in CScriptObject at 1bc03700: ...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua(910): attempt to call method `GetArmy' (a nil value)
         stack traceback:
         	...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua(910): in function <...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua:863>
warning: Error running HandleEvent script in CScriptObject at 1bc03700: ...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua(910): attempt to call method `GetArmy' (a nil value)
         stack traceback:
         	...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua(910): in function <...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua:863>
warning: Error running HandleEvent script in CScriptObject at 1bc03700: ...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua(910): attempt to call method `GetArmy' (a nil value)
         stack traceback:
         	...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua(910): in function <...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua:863>
warning: Error running HandleEvent script in CScriptObject at 1bc03700: ...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua(910): attempt to call method `GetArmy' (a nil value)
         stack traceback:
         	...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua(910): in function <...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua:863>
warning: Error running HandleEvent script in CScriptObject at 1bc03700: ...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua(910): attempt to call method `GetArmy' (a nil value)
         stack traceback:
         	...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua(910): in function <...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua:863>
warning: Error running HandleEvent script in CScriptObject at 1bc03700: ...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua(910): attempt to call method `GetArmy' (a nil value)
         stack traceback:
         	...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua(910): in function <...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua:863>
warning: Error running HandleEvent script in CScriptObject at 1bc03700: ...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua(910): attempt to call method `GetArmy' (a nil value)
         stack traceback:
         	...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua(910): in function <...rever\gamedata\lua.nx2\lua\ui\controls\worldview.lua:863>

**Comment by Garanas** [comment]
Issue dated, likely due to memory.
