### ISSUE TITLE
Billy nuke - turnrate by distance

### ISSUE THREAD

**Issue by CookieNoob** [FAForever/fa#2336]
https://github.com/FAForever/fa/blob/develop/projectiles/TIFMissileNukeCDR/TIFMissileNukeCDR_Script.lua#L53

obviously, the second case in the function is never called, and the others only for distances < 50. This seems to be wrong and not working as intended.

**Comment by Garanas** [comment]
All missiles have this issue: in the original game (not FA) the missiles tracked their target homing into the target as they get closer. In FA, they no longer did. See also this PR: https://github.com/FAForever/fa/pull/3392
