### ISSUE TITLE
Novax beam firing cycle resets when it stops shooting

### ISSUE THREAD

**Issue by JaggedAppliance** [FAForever/fa#2339]
The novax has to reload when it stops shooting including when you change targets, this can lead to it wasting lots of dps.

**Comment by PhilipJFryFAF** [comment]
[replay](replay.faforever.com/7232793) to showcase the issue

**Comment by aeoncleanse** [comment]
This isn't an 'issue' unless you plan to completely redesign the unit's weapon. That's just how it works if you have a long-term non-continuous beam weapon. Or anything else for that matter, it happens with Ravagers sometimes too.

**Comment by shalkya** [comment]
fixed in 2578
