### ISSUE TITLE
GC tractor claw errors

### ISSUE THREAD

**Issue by speed2CZ** [FAForever/fa#2342]
```
WARNING: Error running lua script: Failed to attach entity url0303 to ual0401 on bone 21
         stack traceback:
         	[C]: in function `AttachBoneTo'
         	...\users\odstr\documents\github\fa\lua\aeonweapons.lua(132): in function <...\users\odstr\documents\github\fa\lua\aeonweapons.lua:112>
```
Seems like multiple GCs trying to steal each other's units that are being sucked. Sometimes they target the unit with beam as well.

Fastest way to reproduce is to spawn counple of GCs and some T3 units and still errors will slowly start popping out.

**Comment by FAETHER** [comment]
Is that why GC's sometimes refuse to use their magnets? Or that bug has been already fixed?
