### ISSUE TITLE
DRL0204 (Hoplite) TechLevel set to RULEUTL_Basic

### ISSUE THREAD

**Issue by spooky** [FAForever/fa#2348]
Seems that the hoplite has[ TechLevel set to RULEUTL_Basic in General section](https://github.com/FAForever/fa/blob/develop/units/DRL0204/DRL0204_unit.bp#L165).

The file wasn't modified for a while so I'm not sure if this is an intended value or a leftover.

**Comment by speed2CZ** [comment]
What do you want to change it to? The game is not using this anywhere, so no suprise some are not what you would expect them to be. Especially when the bps are copy pasta.

**Comment by spooky** [comment]
Well, I'd like it to be TECH2 but if the game is not using this, then.. I shouldn't be using it as well ;) what should I be using? look for tech item categories?

**Comment by MrRowey** [comment]
@Garanas https://github.com/FAForever/fa/commit/2d40a2e7d7dd276595acb01e28f707d8a7db6e2c See Commit for the TechLevel Change

**Comment by Garanas** [comment]
Closed as this is fixed.
