### ISSUE TITLE
Loyalist Missile Deflection

### ISSUE THREAD

**Issue by OCGDFS** [FAForever/fa#2351]
Im not sure if this feature is intended like it is at the moment. However, if the deflected missile should target the unit which fired the missile, it doesnt work. Though the missile flies into the opposite direction, it ends up on an unspecified point.

**Comment by JaggedAppliance** [comment]
Can you post a replay of this? As far as I know the missile travels directly towards where the missile was shot from with no arc, so if it was a cruiser missile for example it will often hit the ground on the way back and if not the cruiser will likely have moved since shooting anyway.

**Comment by OCGDFS** [comment]
I tested it with com tml (uef). It doesnt work here. I cant say somethin about other missiles.

**Comment by OCGDFS** [comment]
I've tested it with a tml com. The missile flies back somewhere behind the com, so there was no targeting. I'm not sure behind the intention behind that feature though, but i think i remember that it worked in the past, vanilla maybe.

**Comment by FAETHER** [comment]
Proof please.

**Comment by FAETHER** [comment]
![123](https://user-images.githubusercontent.com/33268383/34652926-dc395db6-f3b2-11e7-9b5a-2dedecec47a8.png)

Yes, every tactical missle after being deflecled looses its collision with any units; in pic it goes through the shields. It has only collision  with the mapheight.

**Comment by speed2CZ** [comment]
This should be fixed already
