### ISSUE TITLE
SMD Targetting Bug

### ISSUE THREAD

**Issue by JonnoHR31** [FAForever/fa#2353]
I experienced... write here what happened to you or what the current behaviour is.
A long game with many nukes and SMD's grouped together. Upon being mass nuked (15 at once) approximately 20 SMDs were fired with several double ups and missed targets, resulting in 1 nuke getting through despite countless more SMDs being loaded.

how to reproduce if explanation is needed to reproduce the problem, add it here
Long standing problem that's been around as long as I can remember. Build multiple SMDs within range of each other and fire 10+ nukes at them, sometimes they work, sometimes they don't.

I expected... write here what you think the best behaviour should be
SMD's to work the same with multiple nukes as they do with only 1 or 2. As far as I'm aware, anti nukes should never miss a target that is in range.

Where the bug is / What should be done if you have a suggestion for fixing the issue, add it here.
Engine issue? Perhaps some tweaking of the anti nuke missile properties to increase its accuracy?

The very end of replay 7301967 is a recent example of this bug.

**Comment by KaukaHan** [comment]
i thing this is not a bad thing. antinukes are cheaper  and faster to build. that makes it difficould to use mass nukes as a gameending move. without this behavior phantom games or other long running games would have a gameenging option less.

**Comment by Garanas** [comment]
I understand both ends - an SMD should not miss in general. And in practice it never does. In these somewhat extreme scenario's it can show up - which is okay in my opinion. As you let the opponent make that many nukes / you decided to bunker in. And it took them tons of resources to get you out of that bunker. I am closing this issue.
