### ISSUE TITLE
Yolona Missile Bug

### ISSUE THREAD

**Issue by ThePlasmaWolf** [FAForever/fa#2359]
After launch and taking the initial curve to fly horizontally to its target, it drops in height over time. The Yolona missile will essentially hit the ground directly on the far side of a 40x40 map, and anything over 40km away on an 80x80 map, instead of flying at nuke height and making a curve downwards when it reaches its target. I.e. it behaves like a tactical missile.

On 20x20 maps the difference is already noticeable and this will probably result in more than 2 anti-missiles being needed to kill the Yolo missile, as the anti-missiles will go to the full height of where nukes fly, and then find out they have to drop because the Yolo is actually lower than expected. On these larger maps it's now very easy to edge nuke, or even hit an SMD directly.

The missile behaviour is also present on 10x10 and 5x5 maps, but it's barely noticable there. I have attached a replay on Drake's Ravine (20x20). Switch the free camera on and look at the largest possible distance to see the path clearly.

[7325866-Plasma_Wolf.zip](https://github.com/FAForever/fa/files/1626631/7325866-Plasma_Wolf.zip)

**Comment by FAETHER** [comment]
That is how every nuke behaves. Can't do anything about it (engine). Besides, does this cause any problems with nuke reaching the target? Most likely not.

**Comment by CookieNoob** [comment]
> Can't do anything about it (engine)

thats not true, the missile behaviour is determined by the missile projectile code
https://github.com/FAForever/fa/blob/develop/lua/sim/DefaultProjectiles.lua#L78
this is the part where the missile is turned towards the target, reducing the amount of time where it turns will probably fix this (or reducing the turnrate to 45 instead of 47.36).

**Comment by FAETHER** [comment]
Excuse me, then.

**Comment by FAETHER** [comment]
@CookieNoob Will you look into this? Maybe some tweaking?

**Comment by CookieNoob** [comment]
I'm pretty short on time atm, so if you want to make a fix, go ahead :)
