### ISSUE TITLE
ML beam target tracking bug

### ISSUE THREAD

**Issue by Petricpwnz** [FAForever/fa#2362]
Tracking is when a unit aims its weapon at an enemy before they enter it's range. 
Currently ML laser has no tracking outside of its laser range which in some situations is extremely unfair and infuriating, especially if you are trying to micro (dodging chicken death balls for example).
But if you add tracking stuff happens. Here I made a beautiful presentation https://www.dropbox.com/s/s96dsv5u31phldc/epic%20presentation.mp4?dl=0
Before you say we remove continuous beam and just make ml shoot from  target to target pls no, that sucks :( veryplsfixthx

**Comment by shalkya** [comment]
fixed in #2432
