### ISSUE TITLE
Miscellaneous blueprints issues and units errors

### ISSUE THREAD

**Issue by Rackover** [FAForever/fa#2363]
Hi,

I'm working on the unit database and by automatizing, I encounter problems related to blueprint misuse or  bad units categorization. They are small, misc but very annoying errors, and could easily be fixed before the next patch.
Here they are : 

- [XAC2101](https://github.com/FAForever/fa/blob/develop/units/XAC2101/XAC2101_unit.bp
) has wrong faction name (AEON instead of Aeon)
- [XEC9001,XEC9002,XEC9003,XEC9004,XEC9005,XEC9006,XEC9007,XEC9008,XEC9009,XEC9010,XEC9011](https://github.com/FAForever/fa/blob/develop/units/XEC9001/XEC9001_unit.bp) are campaign units and therefore should have the `OPERATION ` or  `CIVILIAN ` label.
- [UXL0021](https://github.com/FAForever/fa/blob/develop/units/UXL0021/UXL0021_unit.bp),  [UEA0001](https://github.com/FAForever/fa/blob/develop/units/UEA0001/UEA0001_unit.bp) are debug units and should have a proper category for it.
- [XRB0304](https://github.com/FAForever/fa/blob/develop/units/XRB0304/XRB0304_unit.bp),  [UEL0307](https://github.com/FAForever/fa/blob/develop/units/UEL0307/UEL0307_unit.bp)  have wrong unit ID case (folder is written lowercase instead of uppercase). Issue not present in the steam version, only in the FAF version.

That's all for now, maybe i'll add more as I'm working.
Regards,

**Comment by speed2CZ** [comment]
UEA0001 is a UEF ACU drone

**Comment by speed2CZ** [comment]
you want to add DEBUG category for UXL0021 ?

**Comment by Rackover** [comment]
Yes, "DEBUG" category or any other that would allow me to distinguish it from the rest. This would be very appreciated.

**Comment by speed2CZ** [comment]
```XRB0304, UEL0307 have wrong unit ID case (folder is written lowercase instead of uppercase). Issue not present in the steam version, only in the FAF version.```
They are in uppercase on git

**Comment by speed2CZ** [comment]
PR with fixes is up

**Comment by Rackover** [comment]
will this be included to beta patch ?
