### ISSUE TITLE
games get stuck and then crash with this error log

### ISSUE THREAD

**Issue by jacky3362** [FAForever/fa#2369]
`EXCEPTION_ACCESS_VIOLATION (0xc0000005) at address 0x06b1d264
    attempted to read memory at 0x00000014

Program : C:\ProgramData\FAForever\bin\ForgedAlliance.exe
Cmd line arguments : /mean 1500.0 /deviation 500.0 /country IL /init init_xtremewars.lua /numgames 0 /log C:\ProgramData\FAForever\logs\game.log /nobugreport /savereplay gpgnet://localhost/7398038/EpsilonWild.SCFAreplay /gpgnet 127.0.0.1:29482

Callstack:
    Unknown symbol (address 0x06b1d264)
    Unknown symbol (address 0x06b1d5fb)
    Unknown symbol (address 0x06b1d660)
    Unknown symbol (address 0x06b1de5d)
    Unknown symbol (address 0x06b0e001)
    BaseThreadInitThunk + 31 bytes ((Unknown)(0) + 0 bytes)
    RtlGetAppContainerNamedObjectPath + 306 bytes ((Unknown)(0) + 0 bytes)
    RtlGetAppContainerNamedObjectPath + 258 bytes ((Unknown)(0) + 0 bytes)
Last 100 lines of log...

info: Can't find texture "" -- trying fallback.
warning: GetResource: Invalid name ""
info: Can't find texture "" -- trying fallback.
warning: GetResource: Invalid name ""
info: Can't find texture "" -- trying fallback.
warning: GetResource: Invalid name ""
info: Can't find texture "" -- trying fallback.
debug: Loading module '\000/lua/ui/game/strategicicons.lua\000'
debug: Loading module '\000/lua/ui/dialogs/disconnect.lua\000'
debug: Loading module '\000/lua/keymap/hotbuild.lua\000'
debug: Loading module '\000/lua/keymap/upgradetab.lua\000'
debug: Loading module '\000/lua/usermusic.lua\000'
info: /savereplay
debug: Loading module '\000/lua/ui/game/layouts/score_mini.lua\000'
debug: Loading module '\000/lua/ui/game/layouts/missiontext_mini.lua\000'
debug: Loading module '\000/lua/ui/game/layouts/chat_layout.lua\000'
warning: Checksum for beat 0 mismatched: decfac44f9ebf8465aef830cf14aea48 (sim) != 72ad458514e74c4c2d5aa358b68ee8c5 (jacky3362).
debug: Current gametime: 00:00:00
info: playable area coordinates are { 4, 1000, 4088, 3184 }
info: Offmapareas are {
info:   { x0=-96, x1=4188, y0=900, y1=1000 },
info:   { x0=-96, x1=4188, y0=3184, y1=3284 },
info:   { x0=-96, x1=4, y0=1000, y1=3184 },
info:   { x0=4088, x1=4188, y0=1000, y1=3184 }
info: }
debug: Loading module '\000/lua/ui/dialogs/desync.lua\000'
debug: Loading module '\000/lua/ui/controls/textarea.lua\000'
warning: Desync at beat 1 tick 0.20000000298023
info: Unable to load texture from file: /icons/units/eel0001_icon.dds
info: playable area coordinates are { 4, 1000, 4088, 3184 }
info: Offmapareas are {
info:   { x0=-96, x1=4188, y0=900, y1=1000 },
info:   { x0=-96, x1=4188, y0=`

**Comment by speed2CZ** [comment]
```/init init_xtremewars.lua```
This is a mod problem, I tried extreme wars not so long ago and it worked, so my bet is combination of mods crashing the game. The featured version is not the latest, try this one https://forums.faforever.com/viewtopic.php?f=30&t=12675 Uveso is updating it.

And for the future, this is a place to report game bugs, not mod bugs.
