### ISSUE TITLE
corsair display ground attack range while other f/b doesn't

### ISSUE THREAD

**Issue by shalkya** [FAForever/fa#2371]
![image](https://user-images.githubusercontent.com/11618427/35483584-a792f50c-048f-11e8-8413-199f1761ec9a.png)
also corsair does attack on patrol the land unit nearby (though its radius for attacking an unit is really tiny, and it doesn't pursue units), while other f/b doesn't attack land unit on patrol. (didn't test if corsair attack air unit on patrol)
this 2 observations might be related or not. I can split in 2 issue if necessary, can also close the issue, if we decide to do nothing.

**Comment by speed2CZ** [comment]
The corsair shoot ahead, so it makes sense to have the range on it. Other FBs drop the bombs belowe them, so it would not make sense for them to have the range shown.

**Comment by shalkya** [comment]
i don't get the logic here.
For example the notha drop his bomb pretty at the same range as the corsair fire his missile.
The fact that their ballistic is different shouldn't impact the range displayed, or I am missing your point ?

**Comment by speed2CZ** [comment]
So what units do you want to display the attack range?

**Comment by speed2CZ** [comment]
You need to add `RangeCategory = 'UWRC_DirectFire',` into the weapon table inside unit's bp
But then janus and notha range is much bigger than it actually uses.
So then you gotta play with `MaxRadius = 60,`
which I don't want to do, to not fuck up bomb drops

**Comment by shalkya** [comment]
well i'm not quite sure tbh, in general range ui doesn't serve a lot of purpose for air units. Only for newbies to grasp the general idea of the range of asf/inte at the beginning, or for hover bombing for T4 bomber for example.
The real use is restorer as a "slow" and big range unit.
If we want to be accurate we could even display the aa range ui only in front of fighters.

as for your comment, i guess for now fighter/bomber are mainly used as bombers, so displaying the air to ground range seems better.

**Comment by MrRowey** [comment]
@Tagada14 What you think about this ?

**Comment by Tagada14** [comment]
I don't see why bombers that drop bombs should have an attack radius, I also don't see a point in corsairs having one tbh.

**Comment by Garanas** [comment]
In contradiction to other bombers, corsairs do not 'drop' a bomb. They fire missiles in a 'direct fire' manner, and hence they have an attack radius. Closing this as solved, as I don't consider it to be a bug - if anything, just odd.
