### ISSUE TITLE
damaged shield recharge is reduced by energy stall

### ISSUE THREAD

**Issue by shalkya** [FAForever/fa#2372]
when you e stall (while regening shield or at full health shield) your shield reset, and you get to recharge it. This reset-recharge rate is super fast when you don't e stall anymore, and it is a bit slower when you keep e stall.
when you are recharging from losing shield to damage and then you powerstall, the recharge rate is going to be really low. (even slower than usual recharge from e stall, because the % speed reduction that apply to the reset-recharge will also apply to the recharge from damage)
I think this is a bug, e stall shouldn't affect the recharge speed, but only the reset-recharge.
(didn't see if this slow down does apply to the regen, would be a nice investigation.)

**Comment by shalkya** [comment]
[game.log](https://github.com/FAForever/fa/files/1755743/game.log)
content.faforever.com/faf/vault/replay_vault/replay.php?id=7543206

that should help you understand the bug

**Comment by Garanas** [comment]
No longer relevant with the new shield implementation.
