### ISSUE TITLE
rework LOD for rocks and zoom depending reclaim

### ISSUE THREAD

**Issue by badbwoi** [FAForever/fa#2374]
Hey guys,

here is some stuff I noticed while looking for the best fitting rock props for my maps. 

Current LOD for rocks:
The LOD difference (100-1000)  between rock props is huge - even if the mass amount/size is similar - and only 3 rocks have LOD >=500. Smaller rocks from crystalline, tropical and evergreen (all LOD 100) can only be seen when zoomed very far in, compared to smaller desert rocks (LOD 250). It leads to some rocks being displayed while others - right next to it- of the same size and mass amount are not. I made a nice video for you: https://goo.gl/zsvJLM (needs to be downloaded sry)

Current zoom depending reclaim icon (change not possible due to engine):
~~But at the same time you are only able to reclaim between LOD  0-150, which forces you to zoom in, even if you can see some rocks already. On the other hand you get the reclaim ability (LOD 150) before seeing all rocks (LOD 100-1000) - didn't make sense. Other options like e.g. repair are working on every zoom level. Another awesome video: https://goo.gl/FxDFXt (needs to be downloaded too)~~

New LOD for rocks ~~and reclaim icon~~:
It would be nice if we could change the LOD to consistent form, since people are already playing desert maps with many 250 LOD rocks and no performance problems. I can rework the LOD in all 106 "rock_prop.bp's" + 2 "log_props.bp's" and fix some bugs (some rocks have weird mass values (e.g. large rock with only 10 mass, should have at least 75 mass) and tiny crystal are blocking an area of factory size). Here is my idea of a mass value based rework:

-3 consistent steps, instead of current 6: https://ibb.co/c3xewH
LOD 750: rocks with >=100 mass
LOD 500: rocks with 75 mass
LOD 250: rocks <=50 mass

~~But at the same time, it would be nice to enable reclaim from at least 250 LOD, better the full map scale like "repair", if that is possible. That's something I can't do.~~

Even without adjusting zoom depending reclaim, we could fix 2 out of 3 things:
1)Being able to reclaim without seeing the rocks/props
2)Make rock props dis-/appear more consistent
After change we will always see all rocks before we are able to reclaim them + theta bridge will always be seen on theta ;)

What do you think about it?
And are there more limitations I could not think of?

regards

**Comment by Exotic-Retard** [comment]
i havent taken too much time to look at this but i would suggest setting the LOD so reclaimable things appear exactly at the level when you can click to reclaim them, and unreclaimable things can appear whenever is appropriate for the complexity of the prop in question

**Comment by badbwoi** [comment]
Thx for the reply.
I rather go with better visibility. This way we could find reclaim easy (even if we could not reclaim it in upper zoom level) + we make maps better looking when zoomed out. The trees have already good LOD up to 700/750, which i approve.
Here a pic of LOD level and prop count before and after change: https://ibb.co/c3xewH

To my knowledge there are only 40 from 335 props (12 from 127 rocks) unreclaimable.
With your suggestion we would limit us to 150 LOD which will lead to constant zooming and ctrl-shift abuse to find reclaim + all maps will look naked up to that point prop-wise. Thats exactly the opposite of what I had in mind ;)

**Comment by Exotic-Retard** [comment]
theres ui mods to increase lod of reclaimables already if you want that, and i guess no mods that do it consistently the other way around. i dunno theres always the option of leaving it how it is and making a ui mod with the changes you want.

**Comment by badbwoi** [comment]
yeah a mod that can be tested (performance, visibility) and adapted (before eventual integration) is probably the best solution, since the deeper I get into it, the more I have the urge to change rock mass values according to rock size. with that all rock themes will have same variation of mass values and not just 10 or 300. I will finish .bp's first. Can I ask you for help to get mod rollin?
