### ISSUE TITLE
units killed under construction don't give wreck if they didn't reach 50% of their life

### ISSUE THREAD

**Issue by shalkya** [FAForever/fa#2375]
can be found in this replay : http://content.faforever.com/faf/vault/replay_vault/replay.php?id=7467924

**Comment by Exotic-Retard** [comment]
95% sure thats not a bug and is a special intended feature

**Comment by shalkya** [comment]
but what would be the point of it ? i don't get it

**Comment by speed2CZ** [comment]
That's by design. Before, the unit that was being built got always destroyed. Then it was added that if it's more than halfway done, it will create a wreckage.

**Comment by shalkya** [comment]
but couldn't we do something like :
if the construction reached 10%, if the unit is killed, you can still get a 10% wreck ?
do it every 10%. (so you don't have have wreck that's worth 1% of the unit)
plus it allow to discriminate between a 50% done unit and a 90% done unit.

**Comment by MrRowey** [comment]
@Garanas this could be a simple fix but assume balance might need to com in on this one

**Comment by Garanas** [comment]
@Tagada14 what is your opinion?

**Comment by Hdt80bro** [comment]
Huh, I just refactored the code responsible for this. The relevant line is at https://github.com/FAForever/fa/blob/deploy/fafdevelop/lua/SimUtils.lua#L448

**Comment by MrRowey** [comment]
Discussed this with the team and it seems the general consensus if something is not fully built it is to leave no wreck
