### ISSUE TITLE
Auto OC not working

### ISSUE THREAD

**Issue by shalkya** [FAForever/fa#2379]
auto OC sometimes doesn't work.
even if you have the energy for it, it won't fire.
It get fix by disabling auto OC, and enable it again.
Might be triggered by upgrade on ACU.

**Comment by shalkya** [comment]
succeed to reproduce it once, but it is hard to reproduce.
[game.log](https://github.com/FAForever/fa/files/1740339/game.log)
http://content.faforever.com/faf/vault/replay_vault/replay.php?id=7518961

it was trigger by the lose of e storage, then building it again didn't allow auto to work back, i needed to disable and enable auto oc again. (BTW can't reproduce it easily)

in a previous game i played, it was triggered by adding more e storage (in beta) to increase the power of my OC while in fight.

**Comment by Garanas** [comment]
This also happens when it is toggled and you start an upgrade.

**Comment by lL1l1** [comment]
Fixed by #5854?
