### ISSUE TITLE
show the % of completion of the unit

### ISSUE THREAD

**Issue by shalkya** [FAForever/fa#2384]
![image](https://user-images.githubusercontent.com/11618427/36631008-511438f2-19bc-11e8-83c0-94340ed71b8f.png)
here a damaged unit will show a reduced % of completion because i think this is calculated on his life/max life. 
This is wrong (imo) it should displayed the % of completion. (without taking into account the damage taken)
(in the example it show 19% instead of 80% or so)
[game.log](https://github.com/FAForever/fa/files/1754412/game.log)
http://content.faforever.com/faf/vault/replay_vault/replay.php?id=7538250

**Comment by speed2CZ** [comment]
That info is not available.
The UI uses a engine function `GetRolloverInfo()`
and that contrains only current/max health. Which is used to calculate the %

Example of a engie under construction
```
INFO: {
INFO:   armyIndex=0,
INFO:   blueprintId="url0105",
INFO:   energyConsumed=0,
INFO:   energyProduced=0,
INFO:   energyRequested=0,
INFO:   entityId="2",
INFO:   fuelRatio=-1,
INFO:   health=124.80778503418,
INFO:   kills=0,
INFO:   massConsumed=0,
INFO:   massProduced=0,
INFO:   massRequested=0,
INFO:   maxHealth=145,
INFO:   nukeSiloBuildCount=0,
INFO:   nukeSiloMaxStorageCount=0,
INFO:   nukeSiloStorageCount=0,
INFO:   shieldRatio=0,
INFO:   tacticalSiloBuildCount=0,
INFO:   tacticalSiloMaxStorageCount=0,
INFO:   tacticalSiloStorageCount=0,
INFO:   userUnit={ <metatable=table: 219184B0>
INFO:     _c_object=userdata: CScriptObject* at 1A491B78 = [CScriptObject at 0x1DC4BC00]
INFO:   },
INFO:   workProgress=0
INFO: }
```

**Comment by shalkya** [comment]
the construction bar does take some informations into account.
We could re-use these informations to change the % ?

**Comment by speed2CZ** [comment]
I't directly from the engine
