### ISSUE TITLE
remove the build beam when factory is paused

### ISSUE THREAD

**Issue by shalkya** [FAForever/fa#2387]
when factory is paused, it still displays the build beam as if you were still building. it should be turn off, so opponent can see your factory is paused.
![image](https://user-images.githubusercontent.com/11618427/36631666-07865f56-19c8-11e8-9a4d-f3e1602a0c1b.png)
![image](https://user-images.githubusercontent.com/11618427/36631669-0b4d15d0-19c8-11e8-9af6-87b8dc8c8356.png)
![image](https://user-images.githubusercontent.com/11618427/36631670-0f07cefe-19c8-11e8-9ae0-2bf52d6b3934.png)
![image](https://user-images.githubusercontent.com/11618427/36631677-331a56c2-19c8-11e8-99eb-552b446fcde4.png)

[game.log](https://github.com/FAForever/fa/files/1754413/game.log)
http://content.faforever.com/faf/vault/replay_vault/replay.php?id=7538250

**Comment by MrRowey** [comment]
@Garanas Close as PR Merged to Fix this
