### ISSUE TITLE
ACU retargeting bug

### ISSUE THREAD

**Issue by JaggedAppliance** [FAForever/fa#2390]
[7550053-JaggedAppliance.zip](https://github.com/FAForever/fa/files/1758879/7550053-JaggedAppliance.zip)
[game.log](https://github.com/FAForever/fa/files/1758881/game.log)
In this replay at 7:30 my acu is targeting the enemy acu. It continues targeting the acu as it should until I Overcharge him. Directly after overcharge my commander turns and targets a tank without any order given from me. I then click the enemy acu and my acu ignores the command. A few seconds later my acu targets the enemy ACU, shoots once, and then starts attacking a nearby tank.

Once an ACU is targeting another ACU it should not retarget to any other unit without an explicit order. The retargeting seems to have been triggered by Overcharge.

**Comment by shalkya** [comment]
#integratetargetpainter
[DMS_Lite.zip](https://github.com/FAForever/fa/files/1761752/DMS_Lite.zip)
[target_painter.zip](https://github.com/FAForever/fa/files/1761753/target_painter.zip)

**Comment by shalkya** [comment]
fix in #2672
