### ISSUE TITLE
fighter/bomber doesn't attack ground units

### ISSUE THREAD

**Issue by PhilipJFryFAF** [FAForever/fa#2391]
when using attack move or patrol commands then the UEF and Seraphim t2 F/B will not attack ground units at all
the cybran t2fb will attack ground units but only if they are incredibly close to the attack move/patrol order

**Comment by shalkya** [comment]
yeah was mentioned in #2371

**Comment by MrRowey** [comment]
@Garanas Close as Duplicate Issue as Keyser Mentioned
