### ISSUE TITLE
mega not being targeted correctly while being built

### ISSUE THREAD

**Issue by shalkya** [FAForever/fa#2397]
![image](https://user-images.githubusercontent.com/11618427/36892213-c2c198c2-1e4f-11e8-9a91-33b92a6b4c0d.png)
17min until the end (40 min or so)
lot of unit can't target it correctly; they can on some angle, or if you press "s" (and target another bone, i guess ?)
http://content.faforever.com/faf/vault/replay_vault/replay.php?id=7566540
[game.uid.7566540.log](https://github.com/FAForever/fa/files/1774504/game.uid.7566540.log)

**Comment by MrRowey** [comment]
@jip / @MadMaxFAF  ?

**Comment by Garanas** [comment]
![image](https://user-images.githubusercontent.com/15778155/176954794-b5d73ee1-0f73-4859-ac38-4cbc8cc703a7.png)

We can adjust the collision box while it is being constructed. At the moment, the animation causes the entire unit to 'sit', while the collision box is still up there.
