### ISSUE TITLE
"ghost atlantis/tempest bug"

### ISSUE THREAD

**Issue by shalkya** [FAForever/fa#2398]
![image](https://user-images.githubusercontent.com/11618427/36894881-9f86b6b8-1e58-11e8-8942-917350004b6e.png)

triggered if you ctrl k the atlantis/tempest, under 50% construction and you finish the construction before the end of death animation (which doesn't really exist since you don't trigger it by killing unit before 50% completion)
you need 50 hives, maybe less; a paragon or lot of ressource; ctrl k atlantis/tempest before 50% completion.
http://content.faforever.com/faf/vault/replay_vault/replay.php?id=7566744
[game.uid.7566744.log](https://github.com/FAForever/fa/files/1774673/game.uid.7566744.log)

It is a rare bug.

PS : you can also note the bug where unit are wasting resource during the death animation of the unit they are building.  #2401

**Comment by CookieNoob** [comment]
this kinda sounds like a non-issue to me... 50 hives and paragon and you need to ctrl+k it at the correct time... this doesnt even sound remotely like a real game situation
