### ISSUE TITLE
units getting stuck

### ISSUE THREAD

**Issue by shalkya** [FAForever/fa#2400]
![image](https://user-images.githubusercontent.com/11618427/36895415-8538be44-1e5a-11e8-9360-2bcdb67a86b0.png)

4 ilshy being stuck (1 into the walls, and 1 get unstuck after struggling for quite some time)

i don't have the game.log of this game anymore
http://content.faforever.com/faf/vault/replay_vault/replay.php?id=7553714

I also remember ML to be easily stuck, which is even more annoying.

**Comment by CookieNoob** [comment]
pathfinding is all inside the engine so we cant do anything about that
the only "solution" I could think of is to check regularly if a unit didnt change its position even though it has a move order and then give it a new order again (or move it in some other direction first). This is quite performance heavy though (and I dont think it is trivial to implement, especially for groups of units that move) and not really a good solution

a log file for this isnt needed (no error from the lua part of the game)

**Comment by shalkya** [comment]
and since it's only few unit, would be reworking them i some way (bones or whatever) without creating more bug, be a valid way to solve this issue ?
on top of my head i would say mantis, ilshy, ML

**Comment by MrRowey** [comment]
@Garanas Close as pathfinding is engine limited and noting we can do about it ?
