### ISSUE TITLE
wrong mass/e drain displayed by assisted tml

### ISSUE THREAD

**Issue by shalkya** [FAForever/fa#2402]
![image](https://user-images.githubusercontent.com/11618427/36941509-7eac4a60-1fa8-11e8-87b1-777263a37eb4.png)
the classic drain (without adjacency) displayed is -6 mass and -120 e. I goes up to -12 mass and -240 e when you assist it. It alternate between -6 and -12 mass all the time while being assisted. The more engie assisting, the longer -12/-240 is being displayed.
it is only an UI issue, since i've tested => there is no greater consumption with assisting engie.
http://content.faforever.com/faf/vault/replay_vault/replay.php?id=7577243
[game.uid.7577243.log](https://github.com/FAForever/fa/files/1778115/game.uid.7577243.log)

**Comment by shalkya** [comment]
update : 
assisted by harm it shows higher consumption, i guess it's just UI side to show how much income is used on this tml.
![image](https://user-images.githubusercontent.com/11618427/50832220-d779bd00-134d-11e9-8d90-e8b4e04efd9c.png)

**Comment by HUSSAR-mtrela** [comment]
I will try to fix it in my PR that is adding more accurate stats for all units

**Comment by Garanas** [comment]
This is how silo's work - closing this issue.
