### ISSUE TITLE
removing the vet bar from beetle/mercy/tmd/antinuke

### ISSUE THREAD

**Issue by shalkya** [FAForever/fa#2417]
![image](https://user-images.githubusercontent.com/11618427/37600712-d03a9210-2bd3-11e8-981f-207afbe9e018.png)
![image](https://user-images.githubusercontent.com/11618427/37600755-f6b729bc-2bd3-11e8-8d12-9f9de965049f.png)

beetle/mercy can't vet up since they are suicide unit.
i think we should remove the vet bar, to behave like engies.

http://content.faforever.com/faf/vault/replay_vault/replay.php?id=7651720
[game.uid.7651720.log](https://github.com/FAForever/fa/files/1825310/game.uid.7651720.log)

**Comment by Exotic-Retard** [comment]
also applies to antinukes and tmd btw

**Comment by HUSSAR-mtrela** [comment]
I would keep vet bar for antinukes and tmd since we can add vetting or if mod enable vetting of this buildings.

**Comment by speed2CZ** [comment]
I agree with hussar
it doesnt do any harm there

**Comment by shalkya** [comment]
fixed in #2939
