### ISSUE TITLE
Code duplication - aibrain:BaseMonitorPlatoonDistressThread

### ISSUE THREAD

**Issue by HardlySoftly** [FAForever/fa#2418]
Duplicate functions:
https://github.com/FAForever/fa/blob/develop/lua/aibrain.lua#L2823
https://github.com/FAForever/fa/blob/develop/lua/aibrain.lua#L2854

I notice however that the code is slightly different in each.

**Comment by Uveso** [comment]
Thank's for reporting :)

I will fix that.

**Comment by speed2CZ** [comment]
This is fixed
