### ISSUE TITLE
personal shield unit doesn't get damage to their health while recovering shield from dropping

### ISSUE THREAD

**Issue by shalkya** [FAForever/fa#2440]
when you drop, you need some sec to be able to recharge the shield. When the unit are attacked during this period, it still affect the shield, and not the HP of the unit.
[game.uid.7733753.log](https://github.com/FAForever/fa/files/1880613/game.uid.7733753.log)
http://content.faforever.com/faf/vault/replay_vault/replay.php?id=7733753

**Comment by shalkya** [comment]
it's all personal shield unit, as you can see in the replay : ACUs, SCUs, Titan, Harb, Obsidian

**Comment by aeoncleanse** [comment]
Approved. Nicely done.
