### ISSUE TITLE
Observer abuse

### ISSUE THREAD

**Issue by Apofenas** [FAForever/fa#2447]
Hello

If observers are on you can switch your view to any army. This lets you spot pretty much everything for your team. Amount of resources, nuke location, teleport ect.

Though this will not prevent the abuse, but still make it harder by making observers unable to switch armies.

**Comment by shalkya** [comment]
it is a useful tool for observer and caster, to be able to get into player's view and see their income/reclaim and other stuff. (especially in 1v1)
removing this would be more annoying than useful.
Not allowing observer at first is the best way to prevent the "cheating". 
Best solution, would be to make dead players something else than an observers, and thus making them unable to get into opponent team view.

**Comment by PhilipJFryFAF** [comment]
maybe dead ppl should stay the same regardless of observers being enabled or not?

that way ppl who are actual observers would still be able to see stuff while dead players would not
