### ISSUE TITLE
Restriction UI shows Novax Center twice

### ISSUE THREAD

**Issue by HUSSAR-mtrela** [FAForever/fa#2451]
this is caused by recent addition of FACTORY category to the blueprint of Novax Center because they can build Defense Satellites. 

![image](https://user-images.githubusercontent.com/11665978/39666554-7736b5c6-5073-11e8-9880-907d3eb342b6.png)

**Comment by ChrisKitching** [comment]
And yet the fatboy is not affected...?

**Comment by HUSSAR-mtrela** [comment]
that's because the fatboy has FACTORY category but it not a building. I will fix it soon by adjusting grouping of units in the Unit Manager.

**Comment by MrRowey** [comment]
This is not a huge issues and if someone wants to invest the time to fix this can be reopened
