### ISSUE TITLE
In a game with many players chat settings window get cut off at the bottom

### ISSUE THREAD

**Issue by Wesmania** [FAForever/fa#2462]
In a game with 17 players, opening a chat options window causes it to be cut off, so it's impossible to apply any options. I tried any way I could to move the window, but it appears to be impossible to move. It would be nice if either we could move the window or the list of players to silence was smaller and scrollable.

**Comment by ChrisKitching** [comment]
The lobby UI also does not have enough vertical space for >16 player slots to be rendered.

**Comment by Wesmania** [comment]
It's not problem with maximum of 16 army-controlling players, but games with >16 chatters are possible since observers count in.

**Comment by HUSSAR-mtrela** [comment]
@Wesmania please provide screenshot(s) for this issue

**Comment by Wesmania** [comment]
I'll make sure to get you one once I hunt down a large enough game.

**Comment by Garanas** [comment]
We do not support more than 16 players - and we barely support that in practice. Closing this issue.
