### ISSUE TITLE
harms aren't targeted by surface weapon while being built

### ISSUE THREAD

**Issue by shalkya** [FAForever/fa#2472]

**Comment by PhilipJFryFAF** [comment]
fix for this issue is still needed and would be greatly appreciated (since Strogos attempt didn't work out)

**Comment by shalkya** [comment]
faether did make an exe that allow harms to get targeted while being build, while not using 'exp' marker. Last time i checked harms was not targeted while settling at the bottom, and they was targetting only land unit (or being considered as a land unit, can't remember).
