### ISSUE TITLE
Trading a Hive makes it inoperable

### ISSUE THREAD

**Issue by tekrog** [FAForever/fa#2475]
If you trade a Cybran Hive to an ally, all of its "drones" are destroyed, and there is no way to rebuild them. Once it is traded, it shows the disabled icon that normally only shows up when you disable the auto-assist function. If you disable or enable the auto-assist function, it still shows that icon, and no drones are built.

**Comment by CookieNoob** [comment]
did you try unpausing it?

Some players used the auto assist function to (silently) give a hive to an ally and drain eco from that player to build stuff like a nuke or arty

**Comment by tekrog** [comment]
Yes. Even though the auto assist function is enabled, it still shows the disabled icon over the structure because there aren't any drones. Toggling back and forth between enabled and disabled does not help either.

Are you sue you aren't thinking of the UEF Engineering Stations? Those have the option to rebuild their drones. I watched all the Hive drones explode as soon as I traded it. I do see how it could be used for nefarious purposes like that, but my ally had a Paragon, so I was giving him my Hives so he could build another Paragon.

**Comment by CookieNoob** [comment]
I am not talking about the auto assist function, but the pause function (the button below the "repeat" button)

**Comment by tekrog** [comment]
Oh, sorry. Yes, I tried the pause button.

**Comment by PhilipJFryFAF** [comment]
they work fine after gifting
the hive is just paused after being gifted cause people made hives in teamgames and gave them to teammates without asking and without them knowing about it to drain their resources

**Comment by tekrog** [comment]
I just double checked, you are correct, clicking the Pause button fixed it. I did try that the first time, so I'm not sure why it didn't work then. Sorry about that.
