### ISSUE TITLE
Kyro's lobby causing desync since 3696 patch release

### ISSUE THREAD

**Issue by MrBlastman** [FAForever/fa#2477]
Kyro's was fine before the patch.  Since the patch, however, game desync's within a minute or two of starting.  Solution is to remove Kyro's but... playing faforever without Kyro's is  :(

Any solutions?

**Comment by shalkya** [comment]
i guess you need to tell that to Kyro here : https://groups.google.com/forum/#!forum/kyros-lobby
and hope he can fix it.

**Comment by speed2CZ** [comment]
the solution is to not make it a hack mod that over writes faf files and locks them from updating, no wonder it desyncs if you have outdated files

anyway, that's not a game issue

**Comment by ChrisKitching** [comment]
Some of those features sound pretty neat. Why not submit them as a PR to FAF? :D

**Comment by MrBlastman** [comment]
I didn't make the mod, but if I could, how do we submit it?

**Comment by ChrisKitching** [comment]
> I didn't make the mod, but if I could, how do we submit it?

Pull request.

**Comment by PhilipJFryFAF** [comment]
i got Kyro on slack a few months back
he wanted to refactor the game lobby code and add nice features
sadly he doesn't seem to have time to do it properly

**Comment by BlackburnUTG** [comment]
why can't Kyro's lobby be as official part of FAF?
