### ISSUE TITLE
Personal shields buggy after unloading from transports

### ISSUE THREAD

**Issue by ThomasHiatt** [FAForever/fa#2478]
If a unit with a personal shield loses its shield and then gets into a transport, then when it unloads from the transport the health bar for the shield will disappear and the shield graphics will reappear on the unit. When they take damage in this state it will damage the units hp directly and not the shield. Toggling the shield or getting into a transport and unloading again makes the shield health bar come back and start regenerating and make the shield graphic appear on the unit again, but I think it is actually still off and in the recharge period (sorry I forgot to test that part). I noticed this in game 7999251 around min 21, and then did some further testing in a sandox game 8001478. I notice a line in the patch notes for 3696 saying "Units with personal shields that are unloading from transports will now take damage on their shield when hit. " and would expect whatever those changes were to be the culprit.

**Comment by Strogoo** [comment]
Same bug in 3695.

Also found a few more interesting things:
1. Recharge progress doesn't saved. If you turn off shield during the recharge process, shield will be up and will have 0 hp after turning on.
2. It is possible to make shielded transport, if you pick up mobile shield while it's charging.

https://youtu.be/VGbRVGssODg

I'm working on a fix atm.

**Comment by PhilipJFryFAF** [comment]
fixed with #2483
