### ISSUE TITLE
Improving the sim CPU performance

### ISSUE THREAD

**Issue by munnybearz** [FAForever/fa#2498]
Hi guys. I'm interested in what attempts / plans have been thought of to improve the sim performance in FA, and to what extent it is needed?

Is the current sim speed a barrier for many players who get kicked from games due to poor CPU scores? Would the community really want to have huge games / 20k+ units at 0 sim speed? If so perhaps I can try to optimize the engine.

From a brief analysis possible routes could be:

- Replacing LuaPlus with LuaJIT
    - If necessary using the FFI library for more targeted optimization
- Profiling the code (https://github.com/FAForever/fa_profiler) and:
    - Optimizing the Lua code, or
    - Rewriting the heaviest Lua functions in a C++ library that is called instead
- Multiple threads for the sim (number of cores minus 1 for the rendering thread)

How feasible are these and what challenges would they bring? Are there any other options? And relative to the community demand is it worth pursuing?

**Comment by Sheeo** [comment]
Points 1 and 2 are feasible in reverse order.

Point 3 is completely infeasible without a significant reverse engineering of the game source code. I do suggest you go ahead with helping out on the above linked project :)
