### ISSUE TITLE
Feature: Engineer Stats

### ISSUE THREAD

**Issue by JaggedAppliance** [FAForever/fa#2500]
I think it would be very cool if we could see how much an engineer has reclaimed and maybe also how many resources they have used in total while building.

**Comment by HUSSAR-mtrela** [comment]
@JaggedAppliance how would you like to display this kind of info? Using a new text layer over engineers or this play it in a new window or at end of game?

**Comment by JaggedAppliance** [comment]
I think it should be displayed in the info panel where you see their build power and where the veterancy bar would be displayed.

**Comment by JaggedAppliance** [comment]
Woah great news!

**Comment by Garanas** [comment]
@JaggedAppliance Would it be an issue if the reclaim statistics is not 100% accurate? It appears that the time spent reclaiming is not in sync with the engine callbacks that we have, because of that our computations always over estimate it by 1 or 2 ticks worth of reclaiming.
