### ISSUE TITLE
vet BP of ACU are wrong

### ISSUE THREAD

**Issue by shalkya** [FAForever/fa#2502]
the script took over the BP in order to tell how the regen from vet behave.
It does mess up with the unit database information that are being taken from BP.

**Comment by shalkya** [comment]
the game use the information given here : 
```
            -- Regen values by tech level and veterancy level
            local regenBuffs = {
                {1,  2,  3,  4,  5}, -- T1
                {3,  6,  9,  12, 15}, -- T2
                {6,  12, 18, 24, 30}, -- T3 / ACU
                {9,  18, 27, 36, 45}, -- SACU
                {25, 50, 75, 100,125}, -- Experimental
            }
```
in here : fa\lua\sim\Unit.lua

and the database use the Blueprint of the unit (which hasn't been updated)
Would be great to set database to track this file, since if we update the BP, i might once again change in the unit.lua; and we will have same issue.

**Comment by speed2CZ** [comment]
Make an issue in the unit db repo? Not much we can do in the game code about that.
