### ISSUE TITLE
ythota's thighs positionning while being built

### ISSUE THREAD

**Issue by shalkya** [FAForever/fa#2504]
![image](https://user-images.githubusercontent.com/11618427/42287778-07cdc0d4-7fb8-11e8-8f52-01e4fd1c3530.png)
the thighs are weirdly placed, leading to position themself randomly depending of the terrain.
When the exp gets bigger everything get back into order.

**Comment by MrRowey** [comment]
@Garanas build animation / model need looking at here

**Comment by Garanas** [comment]
No longer an issue.
