### ISSUE TITLE
X in lobby bug when being moved

### ISSUE THREAD

**Issue by FlyingThunder** [FAForever/fa#2511]
Whats happening:

- i press x
- host moves me (probably very close after i pressed x)
- i am unable to un-x after being moved - there is no more mouseover/buttonclick reaction on the x-box itself. i need to rejoin the game OR be moved into observers by the host to fix this.

**Comment by Garanas** [comment]
Just tried reproducing this - the x is removed the moment someone is moved. Therefore this issue is no longer relevant as the steps to reproduce no longer exist.
