### ISSUE TITLE
No Stealth restrictions include wrong units

### ISSUE THREAD

**Issue by HUSSAR-mtrela** [FAForever/fa#2512]
- No Stealth Air restriction (missing Cybran T3 fighter and T3 bomber units)
- No Stealth Navy restriction (missing Cybran  T2 stealth boat)
- No Stealth Land restriction (too many Cybran units and 1 Aeon unit):
![image](https://user-images.githubusercontent.com/11665978/42483236-5257d1de-83ba-11e8-94c5-44637b665d32.png)

**Comment by shalkya** [comment]
![image](https://user-images.githubusercontent.com/11618427/42507852-e37a4908-8446-11e8-99c4-fab613955f4e.png)
no stealth structure also remove the harms (should we allow this ?) if we agree on that, we should remove T2 torpedo defense that also have stealth.
![image](https://user-images.githubusercontent.com/11618427/42507946-30b7d9c4-8447-11e8-8df9-71d4ad1db480.png)
no stealth boat remove 2 frigates (in case you missed that)

**Comment by HUSSAR-mtrela** [comment]
@shalkya good catch and I fixed both of these issues by excluding frigates and all torp def because they have personal stealth and not stealth fields.

**Comment by shalkya** [comment]
i can post all this report in an other issue if you want : 

![image](https://user-images.githubusercontent.com/11618427/42525172-c3352114-8472-11e8-8419-64460d4b9a96.png)
no TECH 3 units : shouldn't remove T3 factories and quantum gateway
![image](https://user-images.githubusercontent.com/11618427/42525684-165ae5b2-8474-11e8-8604-2bf6ec838c44.png)
no land units : should remove sacu
![image](https://user-images.githubusercontent.com/11618427/42526102-2c890fde-8475-11e8-942d-549175bd368d.png)
no land shield : should remove the fatboy
![image](https://user-images.githubusercontent.com/11618427/42526164-5e10ec5c-8475-11e8-9fa9-0346da7d27da.png)
no air snipes : should remove the transport to prevent GGs as well as Ahwassa, SR and CZAR.
![image](https://user-images.githubusercontent.com/11618427/42526398-fc210b84-8475-11e8-916f-cbee579113b5.png)
no anti-air navy : shouldn't remove T1 cyb frig, T1 cyb sub, mermaid
![image](https://user-images.githubusercontent.com/11618427/42526462-2b82de5c-8476-11e8-8e3b-09e3958d6191.png)
no anti-air land unit : should remove the aa upgrade on scu
![image](https://user-images.githubusercontent.com/11618427/42526893-73b3bbaa-8477-11e8-9932-01f8c5669814.png)
no torpedo bombers : should remove CZAR (following to the description)
![image](https://user-images.githubusercontent.com/11618427/42526506-4ad6b56c-8476-11e8-950a-bb47a47b3b93.png)
No torpedo boats : should remove sera/uef/aeon destro, BC, cyb BS, T1 cyb sub, T2 cyb sub, torpedo boat, T3 uef/cyb/aeon subs, T4 subs, tempest
shoudn't remove : sera/aeon frigate
![image](https://user-images.githubusercontent.com/11618427/42526965-9a5004ee-8477-11e8-937a-3729db10450c.png)
no torpedo land unit : should remove wagner, brick, othuums, cyb torpedo upgrade, ML, fatboy, megalith
![image](https://user-images.githubusercontent.com/11618427/42527052-e0503f72-8477-11e8-9e10-b958b10c08b3.png)
no direct fire bomber : should remove ahwassa
![image](https://user-images.githubusercontent.com/11618427/42527149-27cdbdf2-8478-11e8-9af6-a3da78c8b79a.png)
no direct fire navy : should remove tempest 
![image](https://user-images.githubusercontent.com/11618427/42527194-3edccf2e-8478-11e8-9c5e-b01fa2cf742f.png)
no direct fire land : should remove selen, ythota, cyb T3 (T1 ?) maa, ML, mega, GC
![image](https://user-images.githubusercontent.com/11618427/42527267-72e68346-8478-11e8-9649-5b4e324f507a.png)
no direct fire gunship : should remove SR
![image](https://user-images.githubusercontent.com/11618427/42524958-4e661cee-8472-11e8-9127-e91ec4d075f2.png)
no direct-firebots : should remove selen, T4 assault bot (ythota), T3 cyb maa

**Comment by HUSSAR-mtrela** [comment]
@shalkya yes, please submit a new issue for each of above comments because it will be easier to track and fix. Some might not be issues and we can discuss them under each reported issue.
