### ISSUE TITLE
Unit Manager shows Cybran torpedo in wrong order

### ISSUE THREAD

**Issue by HUSSAR-mtrela** [FAForever/fa#2515]
This issue was found by @shalkya 

The order of cybran torpedo defense sorting is not correct. 
Should be `T1, T2, T3` instead of `T3, T2, T1` torpedo defense

![image](https://user-images.githubusercontent.com/11665978/42539834-4a4ed4a0-846a-11e8-945a-d8213e4936fc.png)

**Comment by shalkya** [comment]
note that this bug is introduced by your pr, but is normal otherwise.
