### ISSUE TITLE
add load time bar

### ISSUE THREAD

**Issue by shalkya** [FAForever/fa#2527]
that could be limited to percy, bombers, neptune, destro, bs...
this would behave like T2 mobile arty, mml or cruiser
http://forums.faforever.com/viewtopic.php?f=42&t=16440

**Comment by MrRowey** [comment]
Ive managed to get the Percy working with the load time bar for the reload time of the shot but not sure how to go about the other ones EG

Air is allready using the bar to display the fuel of the aircraft
Neptue,Destroyers & BS Most have more than 1 weapon that tend to not be synced so having the load bar would jsut make things more confusing

**Comment by Garanas** [comment]
The summit already has a reload bar and is not synced either (with regard to the various turrets). I think it helps a lot, as typically they all fire in sequence anyhow.

**Comment by MrRowey** [comment]
Oh intresting, Is the summit the only BS that has the reload bar

**Comment by MrRowey** [comment]
See #3347 for changes

**Comment by Garanas** [comment]
As far as I know - yes.

**Comment by Garanas** [comment]
Closed as the #3347 has been merged. Note that the percy was denied a loading bar by the balance team.
