### ISSUE TITLE
"no air" preset isnt working properly

### ISSUE THREAD

**Issue by FlyingThunder** [FAForever/fa#2529]
What i expected:
"No air" restriction preset disables all air units and units related to air.

What i got:
For some reason, the restriction disables the UEF Cooper (T2 torp ship, nothing to do with air) as well as the Cybran Mermaid (T2 stealth ship, also no air relation).

It also disables the Aeon T2 Cruiser and the Aeon T1 AA boat (that makes sense) and disables the carries (makes sense too), but it does **not** disable the UEF/Cybran/Seraphim T2 cruiser.

> NOTE for FAF-Testers, the correct expectation is to disable all air units (expect drones), air factories, and air staging

![screenshot 61](https://user-images.githubusercontent.com/39583733/43022665-43e6ff88-8c68-11e8-903c-4a40224519ec.png)

**Comment by shalkya** [comment]
fixed here #2513
