### ISSUE TITLE
Lobby launcher duplicates mods/maps

### ISSUE THREAD

**Issue by BRNKoINSANITY** [FAForever/fa#2536]
I recently purged my maps and mods folders, as there were duplicate and triplicate listings of basically everything in them, and that purge showed the bug that caused the duplicates.

If you download a mod then double click on the FAF launcher, you can select that mod from the menu, and there is only one. 

If you then download a second mod and open phantom, there will be a duplicate of the first mod and a single listing of the new mod. 

Opening a third game in a new featured mod makes another new copy of each one.

Any further mod downloads only appear in the bottom duplicate of the mods list. Each list is complete 1-Z, then starts anew 1-Z. 

TL:DR launching from featured mods duplicates your map and mod lists, resulting in literally hundreds of confusing entries in your lists.

**Comment by PhilipJFryFAF** [comment]
This is an issue with the client code.
Please make an issue for it (unless there is none for it at the moment) on the client repo at github.com/faforever/client
