### ISSUE TITLE
Replacement for CPU benchmark

### ISSUE THREAD

**Issue by Sheeo** [FAForever/fa#254]
This may need to go to the lobby repository, but we need a suitable replacement for the CPU benchmark that adresses the following concerns:

1. Current CPU benchmark helps lock up the UI
2. It's not very representative of in-game performance

**Comment by aeoncleanse** [comment]
It would be great if we could shift things while we're still using this benchmark so that the benchmark runs while the player is launching/connecting, and the lobby doesn't materialise until it's finished.

**Comment by ChrisKitching** [comment]
That's a truly terrible idea: this would leave the user on a blank screen
for about 5 more seconds. While the UI lag the bench creates is pretty
annoying, it's far preferable to having no UI at all.

One thing that would almost make sense is to bench from the Python code,
but really the whole notion of the benchmark is deeply flawed and needs to
go away.

**Comment by aeoncleanse** [comment]
Why would it? Seriously, the user has to connect, and even on the fastest machines where both players have epic internet that still takes time. Minimum 5 seconds in my experience, usually longer. Have the benchmark running while it's connecting, which uses next-to-nothing in the way of CPU resources, and then it will be done, it won't be trying to create and operate UI in the background so it will be more accurate, and as soon as you connect you get a non-laggy UI ready and waiting.

**Comment by Sheeo** [comment]
This has become more relevant with latest update. I've spawned an issue at https://github.com/FAForever/client/issues/203 to deal with this.
