### ISSUE TITLE
no direct fire restriction doesn't remove Soul Ripper

### ISSUE THREAD

**Issue by shalkya** [FAForever/fa#2557]
no direct fire gunship : should remove Soul Ripper
![image](https://user-images.githubusercontent.com/11618427/42527267-72e68346-8478-11e8-9649-5b4e324f507a.png)

**Comment by HUSSAR-mtrela** [comment]
@shalkya does "SR" stand for Soul Ripper?

**Comment by shalkya** [comment]
yes, i am going to edit
