### ISSUE TITLE
Score screen metal error

### ISSUE THREAD

**Issue by Shiwanabe** [FAForever/fa#2567]
After playing a short game with the AI [Replay id: 8370609] the AI's total metal gained showed as '-1.#IND'.

This shows on both the 'General' tab as well as the 'Resources' tab.

Further investigation of the replay shows that the Graph for 'Metal In' is missing data for the time after the AI's ACU was destroyed.

**Comment by Garanas** [comment]
Closed as I can no longer find the replay and the issue has aged.
