### ISSUE TITLE
aeon tmd deflect nuke

### ISSUE THREAD

**Issue by shalkya** [FAForever/fa#2575]
https://www.twitch.tv/videos/300117917?t=02h14m38s

known issue from long time, seems there were no issue made on github

**Comment by FAETHER** [comment]
Actually, Nuke collides with aeon antiprojectiles that it fires in the air. And nuke gets distracted by smd because its clasified as 'MISSILE' in the blueprint.

**Comment by FAETHER** [comment]
![hack](https://user-images.githubusercontent.com/33268383/44618741-c8d0b480-a849-11e8-9ab6-95a84341d12e.PNG)

As you can see when I have removed all MISSILE keywords, the nuke is no longer dragged in.

**Comment by FAETHER** [comment]
![read](https://user-images.githubusercontent.com/33268383/44618787-d470ab00-a84a-11e8-8aee-8064a26f0efc.PNG)

Here is the current situation, nuke gets dragged in.

![bug](https://user-images.githubusercontent.com/33268383/44618790-e7837b00-a84a-11e8-9ad4-c9302146ec30.PNG)

And then either disappears with no explosion or explodes in the air. In both situations the gamage is still dealt.

**Comment by shalkya** [comment]
does the nuke still get stopped by smd if it lose the missile label ?

**Comment by FAETHER** [comment]
Here are the possible points of interest: 
https://github.com/FAForever/fa/blob/3b73337e27608d094fba5ed20c772833c9e21d1f/lua/sim/defaultweapons.lua#L100-L127
https://github.com/FAForever/fa/blob/3b73337e27608d094fba5ed20c772833c9e21d1f/lua/sim/Projectile.lua#L449-L472
https://github.com/FAForever/fa/blob/develop/lua/defaultantiprojectile.lua#L20-L50

**Comment by FAETHER** [comment]
Yep, collision still applies even without missile keyword. Though damage is dealt in most cases. I had it once not deal damage at all, but im not confident enough to claim that its real and not just my messing around with code.

**Comment by Strogoo** [comment]
Forgot to mention issue number in my PR. I fixed it without removing any category(this can potentially cause some problems). As for collission, this is fixable by DoNotCollideList. Should I add it to pr or we let nuke to collide with these spheres?
