### ISSUE TITLE
Auto load required mods for a replay

### ISSUE THREAD

**Issue by OCGDFS** [FAForever/fa#2587]
I had some trouble watching replays of games which had been played with balance mods.
As far as i know there are two problems:

1. If you have already installed the mods, you have to set them active somehow. Eg hosting a game with these mods enabled before watching the replay ... -.-

2. If you don't have installed the mods (you probably don't even know which mods/version you need), it wont load them automatically like if you wanna join a modded game. That means: load the mods manually, then goto 1.

The replay will desync otherwise.

edit: maybe a client issue. i dont know how its handled

**Comment by PhilipJFryFAF** [comment]
if i watch a replay then the mods are loaded properly

downloading them in case they are missing is client side stuff

can you provide a log of a watched replay where you had the mod installed but it didn't get loaded?

**Comment by PhilipJFryFAF** [comment]
that's exactly what i meant before - as long as you have the mods it will work
but downloading the mods is not the business of the game -> it's supposed to be done by the client

**Comment by OCGDFS** [comment]
Sorry it isn't about downloading the mods. i have them all actually. It is about to set them active, which is usually done by the client, modifying the game.prefs. 
Now talking about downloading i was never refering the game itself. I just compared the client behaviour of joining a game and watching a replay, where the client doesnt download balance mods automatically.
