### ISSUE TITLE
harms can't be auto rebuild by the auto rebuild feature

### ISSUE THREAD

**Issue by shalkya** [FAForever/fa#2590]
this is due to the sinking animation.
a way of solving the issue would be to remove the sinking animation.

**Comment by speed2CZ** [comment]
![ForgedAlliance_2019-07-14_13-23-55](https://user-images.githubusercontent.com/10947024/61182930-aa7acf80-a63a-11e9-9c70-50ea43981cd1.png)

Ctrl-K
Click Repair on the wreck with sACU
Starts building half way done

**Comment by shalkya** [comment]
yeah but that doesn't solve the issue of auto rebuild when sacu are assisting the harm

actually i did a test, if you ctrl k your harm while an scu is assisting it (without repairing it), the scu will rebuild it.
if the assisting scu was repairing the harm, and the harm died (ctrl k or being killed) then it won't rebuild the harm on its own.
