### ISSUE TITLE
EXCEPTION_ACCESS_VIOLATION (0xc0000005) at address 0x00957dd4

### ISSUE THREAD

**Issue by Eonfge** [FAForever/fa#2609]
Another occurrence of an ACCESS_VIOLATION somewhere deep inside the code. The only saving graze of this exception, is that is happens at the score-board.

[0x00957dd4_log.txt](https://github.com/FAForever/fa/files/2447918/0x00957dd4_log.txt)

[hardinfo_report.txt](https://github.com/FAForever/fa/files/2447919/hardinfo_report.txt)

**Comment by KionX** [comment]
SSB was used.
The game was launched on Ubuntu.
It is not possible to reproduce it.
I didn't find any similar issues.
2 years have passed.
Can be closed.
