### ISSUE TITLE
Allow Fatboys to build while moving

### ISSUE THREAD

**Issue by JeroenDeDauw** [FAForever/fa#2618]
Problem: At present it is almost impossible to make use of the construction capabilities of Fatboys. When giving them a command the unit under construction is cancelled and the construction queue is emptied. This means that in most non-noob games, you never get to use the construction capabilities, which is sad.

Desired solution: giving commands to fatboys does not interfere with construction. A partial solution such as retaining the construction queue is already helpful.

Idea: (I was given to understand that a Fatboy can only do one command at a time, and that construction is a command.) Perhaps construction should not be cancelled when a move order is given and the move order instead put into the command queue. People can cancel the construction if they want to move right away. This way they have a choice. And if they want to be able to insta-move, they can just not build anything with the factory, which is what happens now anyway.

The same applies to carriers

**Comment by shalkya** [comment]
fixed in EQ iirc

**Comment by JeroenDeDauw** [comment]
On discord someone told me that the approach taken in EQ is a hack that causes a number of issues and that this is not good enough for merging into FAF.

**Comment by shalkya** [comment]
yeah that's kind of why we never merged it, but at least some people tried to work on that. I guess exotic_retard didn't find any proper way of implementing this fix.

**Comment by KaukaHan** [comment]
maybe boosting the buildpower massivly makes the feature more usefull. This way the fatboy would be more usefull as a forward factory to quikly create a support force.

**Comment by Garanas** [comment]
It may help alleviate the issue, but it won't fix it. Perhaps having a dummy unit as part of the fatboy that does the actual construction (and is attached to the Fatboy) is a solution here. When https://github.com/FAForever/fa/pull/3441 is merged we could look into what the possibilities are.

**Comment by speed2CZ** [comment]
Exactly like that. Just take it from eq repo if you want to integrate it.

**Comment by MrRowey** [comment]
Balance Team Can Reopen if this is a feature they want to add

**Comment by JeroenDeDauw** [comment]
I think this was misclassified as a balance issue. It is a usability issue, and arguably a bug.

**Comment by MrRowey** [comment]
> I think this was misclassified as a balance issue. It is a usability issue, and arguably a bug.

you could say the same to the Czar, and Air craft carriers and with it being like this since the game came out id classify it more as a balance deciding than a bug. @Garanas thoughts

**Comment by Garanas** [comment]
I'd consider it a bug, but we're so used to it that it may the balance is constructed around the idea that these units do one or the other.

I've tried solving it myself, but to no avail.
