### ISSUE TITLE
Units in transports are not counted as kills

### ISSUE THREAD

**Issue by JeroenDeDauw** [FAForever/fa#2619]
Issue: When killing a transport with a bunch of units in it, only the transport is registered as killed by the unit/player that made the kill.

I noticed this because my map has an "automatic reclaim" feature where players get a fraction of the mass value of the units they kill. This code looks at the "mass killed by player" stat, and this stat is not updated when the units in the transport die.

**Comment by JeroenDeDauw** [comment]
That makes sense. Though only means to not assign the kill the the unit that shot down the transport, or otherwise not have it count towards vet level. Assigning the kills to the *player* should still be possible no?

**Comment by shalkya** [comment]
I only remember that zock made the decision, balance wise that it won't be counted for vet level.
i don't know the coding details about how to assign the kill without making unit vet out of it. Some other dev might help you.

**Comment by speed2CZ** [comment]
Could balance team discuss it again? I doubt couple of vetted inties or ASFs would kill the balance.

**Comment by JeroenDeDauw** [comment]
Keep in mind that this likely can be fixed even without affecting the balance (though this might be a bit more difficult to do)

**Comment by MrRowey** [comment]
@Tagada14 If this is still something that doesn't need looking into can you close please :)

**Comment by JeroenDeDauw** [comment]
This defect has a noticeable impact on the gameplay in Survival Versus. Would be nice to have it fixed.

**Comment by Garanas** [comment]
You (Tagada) can put it on milestone 3727 if you want this addressed.

**Comment by Tagada14** [comment]
There is already a cap of getting a maximum of one vet level per 1 unit kill (IIRC) so this wouldn't be a problem. If someone can pick this up it would be a nice QoL change.

**Comment by clyfordv** [comment]
https://github.com/FAForever/fa/pull/6091
