### ISSUE TITLE
Restricting upgradable units does not restricts their upgrades

### ISSUE THREAD

**Issue by HUSSAR-mtrela** [FAForever/fa#2630]
Restricting some units does not restricts corresponding upgrades:

Radar structures
- T1 Radar can upgrade when T2 Radar structure is restricted
- T2 Radar can upgrade when T3 Omni structure is restricted

Sonar structures
- T1 Sonar can upgrade when T2 Sonar structure is restricted
- T2 Sonar can upgrade when T3 Sonar structure is restricted

Mass Extractors 
- T1 Mass Extractor can upgrade when T2 Mass Extractor structure is restricted
- T2 Mass Extractor can upgrade when T3 Mass Extractor structure is restricted

Shield structure 
- T2 Shield structure can upgrade when T3 Shield structure structure is restricted

**Comment by HUSSAR-mtrela** [comment]
I will fix this issue soon

**Comment by MrRowey** [comment]
Closing this Issues After testing 

- Restrictions are working for Radar structures

- Restrictions are working for Sonar structures

- Restrictions are working for Mass Extractors

- Restrictions are working for Shield Structures
