### ISSUE TITLE
Kennel upgrade gives a free building

### ISSUE THREAD

**Issue by PhilipJFryFAF** [FAForever/fa#2632]
game patch version 3700 - when upgrading the kennel you get another kennel building (both are stacked so the other one is hard to see)

you can kill the other useless kennel building for free mass which is easy to abuse
bug is being caused by 14c74ef9c67a54ceb83b57171038634b8a233401

**Comment by shalkya** [comment]
this happen in case you order the upgrade of the building before the construction is finished.

**Comment by PhilipJFryFAF** [comment]
fixed with #2634
