### ISSUE TITLE
Unbinding Keys

### ISSUE THREAD

**Issue by Kalvirox** [FAForever/fa#264]
Is there a way to unbind a key in the F1 menu? because I cannot find it.. someone asked about this in aeolus today, and after systematically smashing every key on the keyboard I couldn't find one.

If there isn't one this should definitely be a thing.

**Comment by Sheeo** [comment]
I suggest we split off enhancement of hotbuild integration into a new issue and keep this as a bugfix-reminder for making the F1 menu able to unbind keys.

**Comment by Kalvirox** [comment]
I agree with the above.
Bump!... Is that even still a thing.

**Comment by quark036** [comment]
Done in PR  #678

**Comment by quark036** [comment]
Close this issue?
