### ISSUE TITLE
lobby ai color bug

### ISSUE THREAD

**Issue by PhilipJFryFAF** [FAForever/fa#2658]
when using user colors in the in game lobby the host will use the color of the first AI player in the slot list if that ai is above the host in the slot list

example of farms discovering the bug
https://puu.sh/C71v4/5d977383e0.jpg

example of me reproducing 
https://i.imgur.com/hXUt2Z8.png

**Comment by shalkya** [comment]
![image](https://user-images.githubusercontent.com/11618427/53307303-4a57dc80-3897-11e9-9285-4fa93c093b23.png)
using kyro's lobby modification by yolo
