### ISSUE TITLE
Some units have wrong background bp.General.Icon

### ISSUE THREAD

**Issue by HUSSAR-mtrela** [FAForever/fa#2664]
Blueprint Verification (upcoming feature) is reporting this warnings and we should correct them:

```
WARNING: LOW bp.General.Icon is "amph" instead of "land" in xrl0002_unit.bp (T3 Crab Egg (Engineer)) 
WARNING: LOW bp.General.Icon is "land" instead of "air" in xeb2402_unit.bp (T4 Experimental Satellite System) 
```
Explanation:
- T4 Experimental Satellite can build only air/orbital satellite so it should have "air" background icon as the Air factory does.
- T3 Crab Egg **(Engineer)** can be built only on "land" and it cannot built on water ("amph") Note that other crab eggs can be build on water and they have correct background icon.

**Comment by Uveso** [comment]
Factories should have the icon of the units they can build.
The crab egg (engineer) is also a factory and can build "amph" units. So it should have the amph icon!

**Comment by speed2CZ** [comment]
T4 Sat has the Air icon now
And Crab Egg engie is apmh as it should be.
