### ISSUE TITLE
Brick classification

### ISSUE THREAD

**Issue by spooky** [FAForever/fa#2674]
Looks like there's just one unit that has a classification value 'RULEUMT_Amphibious' - the brick (XRL0305). This most likely should be set to 'RULEUC_MilitaryVehicle'.
No idea if it has impact on the game - spotted during work on the unit db.

Also, crab eggs are classified as 'RULEUC_Factory' - that also seems weird.

**Comment by spooky** [comment]
ok, thx.

**Comment by speed2CZ** [comment]
Do you need them to change for the db?
