### ISSUE TITLE
Issue in SetWeaponPriorities

### ISSUE THREAD

**Issue by Crotalus** [FAForever/fa#2675]
ofbuscated by Retard so no one gets any funny ideas in the meantime

**Comment by Exotic-Retard** [comment]
https://github.com/Ithilis/Equilibrium/commit/b54e9876b5fa288357a4208217eb154d5ed3b9bb

**Comment by Exotic-Retard** [comment]
you should also obfuscate this bug report

**Comment by shalkya** [comment]
fixed in https://github.com/FAForever/fa/commit/5bc27567ef4f0fcec957f64466557c667d58e0c3
