### ISSUE TITLE
Old Cybran logo on some units

### ISSUE THREAD

**Issue by speed2CZ** [FAForever/fa#2680]
So I noticed that Cybran T2 land units have old version of the logo on their textures.

Now you won't be able to unsee it.
![forgedalliance_2019-01-05_21-38-59](https://user-images.githubusercontent.com/10947024/50729037-50e99380-1133-11e9-9800-ddda025b2f6f.png)
![forgedalliance_2019-01-05_21-32-28](https://user-images.githubusercontent.com/10947024/50729038-50e99380-1133-11e9-96b4-5f5115175ad6.png)
![forgedalliance_2019-01-05_21-36-53](https://user-images.githubusercontent.com/10947024/50729039-51822a00-1133-11e9-9a9c-56543d680aba.png)
![forgedalliance_2019-01-05_21-38-03](https://user-images.githubusercontent.com/10947024/50729040-51822a00-1133-11e9-8f6e-cf10a87927b4.png)

if you compare it to cruiser for example....
![forgedalliance_2019-01-05_21-47-08](https://user-images.githubusercontent.com/10947024/50729058-7f676e80-1133-11e9-9b5a-0b708f33f768.png)

That deserves to be fixed but not by me of couse!

**Comment by speed2CZ** [comment]
and sACU
![2019-01-10_22-33-26](https://user-images.githubusercontent.com/10947024/50998499-dc926400-1527-11e9-8a68-5084a65dc8b4.png)

**Comment by MrRowey** [comment]
@Garanas could be closed as 98% of people would never notice this unless we have someone who can / want to do this quickly

**Comment by Garanas** [comment]
I'm not going to ask Madmax to fix this - closing it.
