### ISSUE TITLE
Cybran T3 Engineer cannot build the last upgrade of Shield Generator

### ISSUE THREAD

**Issue by HUSSAR-mtrela** [FAForever/fa#2683]
can someone explain why @JaggedAppliance made this [commit](https://github.com/FAForever/fa/commit/a74813286292a464b49161ded185b3dcc9451f09) for Cybran T3 Engineer to build 3rd upgrade (ED4 - URB4206) of Shield Generator:

**Current:**
- 3rd upgrade (ED4 - URB4206) of Shield Generator  

**Expected:**
- 4th upgrade (ED5 - URB4207) of Shield Generator 

![image](https://user-images.githubusercontent.com/11665978/50740580-7e2f5380-11be-11e9-943b-241750ad0e4d.png)

**Reason:**
As result of this change, T3 Engineers in other factions can build the last upgrades of T2 Shield Generators but Cyrban cannot build last Shield Generator upgrade (ED5 - URB4207) but rather one upgrade (ED4 - URB4206) before the last Shield Generator upgrade.

Here is upgrades chain of Cyrban T2 Shield Generators: 
![image](https://user-images.githubusercontent.com/11665978/50740621-11688900-11bf-11e9-8592-12b190558414.png)

**Comment by JaggedAppliance** [comment]
This is intended. An ED4 shield is more comparable in cost to other T3 shields so you can build that one straight from T3 but you have to upgrade it to get the final shield. Before this you had to upgrade shields from ED1 all the way up.
