### ISSUE TITLE
Aeon T2 Shield Generator is not upgradable to T3

### ISSUE THREAD

**Issue by HUSSAR-mtrela** [FAForever/fa#2684]
**Current:**
Aeon T2 Shield Generator (uab4202) is not upgradable to T3 Shield Generator (uab4301)
**Expected:**
Aeon T2 Shield Generator (uab4202) is upgradable to T3 Shield Generator (uab4301)
**Reason:**
Other factions can upgrade their T2 Shield Generator to T3 Shield Generator 

**EDIT**
In addition, uab4202 blueprint has the following values set which indicate an upgradable structure:
- General.CommandCaps.RULEUCC_Pause = true
- Economy.BuildRate = 13.66,
- Economy.RebuildBonusIds = { 'uab4202',  'uab4301', }

**Comment by speed2CZ** [comment]
That kinda a faction feature, it was never upgradable.

**Comment by HUSSAR-mtrela** [comment]
I would not call it a feature but rather disadvantage. Also, we made this [fix ](https://github.com/FAForever/fa/commit/a74813286292a464b49161ded185b3dcc9451f09) for Cybran so why not making the same change for Aeon shields.

**Comment by HUSSAR-mtrela** [comment]
I look like developers forgot to make this T2 shield upgradable to T3 because I see that the uab4202 blueprint has the following values set which indicate an upgradable structure:
- uab4202 has General.CommandCaps.RULEUCC_Pause = true
- uab4202 has Economy.BuildRate = 13.66,
- uab4202 has Economy.RebuildBonusIds = { 'uab4202',  'uab4301', }

**Comment by speed2CZ** [comment]
I would not look at those, since most of the BPs were copy pasta and contained a lot of unused values. But if you look at other things it doesn't show as upgradable in abilities. The upgrade animation also doesn't exist.

**Comment by HUSSAR-mtrela** [comment]
it's good enough explanation for me and I'm closing this issue.
