### ISSUE TITLE
SupCom:FA - FAF modded Bugreport 10-01(Jan)-19 (With lotsamods)

### ISSUE THREAD

**Issue by STREALOK** [FAForever/fa#2696]
eyo first bugreport for faf here hope it isn't too bad
was quite happily playing skrimish against 2 easy ai on the map with 90+% water (Debris) on the Nomads game type for about 5-10 minutes when it crashed out of nowhere 

used mods are: (and yes i know i am pushing it with this lot but it was mainly a test ;p :) )
Downloaded from the faf vault same day this topic is posted, picked the most recent dl's:
BlackOps FAF: ACUs
BlackOps FAF: EXUnits
BlackOps FAF: Unleashed

These are downloaded from here: http://forums.faforever.com/viewtopic.php?f=41&t=12416
Ninja Reclaim Drones v15
http://faforever.uveso.de/NinjaReclaimDrones(AllGameVersions)-V15.zip
Nuclear Repulsor Shields v17
http://faforever.uveso.de/NuclearRepulsorShields(AllGameVersions)-V17.zip
Orbital Wars v1.35
http://faforever.uveso.de/OrbitalWars(AllGameVersions)-v1.35.zip
Quantum Resource Generators v15
http://faforever.uveso.de/QuantumResourceGenerators(AllGameVersions)-V15.zip
Smart Tactical Missiles v19
http://faforever.uveso.de/SmartTacticalMissiles(AllGameVersions)-V19.zip
Total Mayhem v1.36
http://faforever.uveso.de/TotalMayhem(AllGameVersions)-v1.36.rar

and this was downloaded from their main page on moddb and installed right into my steam game before i started trying out faf (i did try starting out with some of the quirky stuff from brewlan like random crates, monuments and added ai support from brewlan so gonna try without all that stuff, just bog standard mods)
BrewLAN v085

also some of the mod unit and building icons do not light up in the edges when moused over. this a known issue? if so can it be fixed? really bugs me so any help would be appreciated

Error Message:

EXCEPTION_ACCESS_VIOLATION (0xc0000005) at address 0x009274d4
    attempted to read memory at 0x00000009

Program : C:\ProgramData\FAForever\bin\ForgedAlliance.exe
Cmd line arguments : /init init.lua /nobugreport /log C:\ProgramData\FAForever\logs\game.log /gpgnet 127.0.0.1:56837 /mean 1500.0 /deviation 500.0 /savereplay gpgnet://127.0.0.1:56838/9102110/STREALOK.SCFAreplay /country NO /numgames 0

Callstack:
	Unknown symbol (address 0x009274d4)
	Unknown symbol (address 0x00914412)
	Unknown symbol (address 0x5aabf3bb)

Last 100 lines of log...

debug: Loading module '\000/units/inb1101/inb1101_script.lua\000'
debug: Loading module '\000/lua/editor/economybuildconditions.lua\000'
debug: Current gametime: 00:01:00
debug: Loading module '\000/units/inb1102/inb1102_script.lua\000'
debug: Loading module '\000/mods/totalmayhem/units/brmat1intc/brmat1intc_script.lua\000'
debug: Loading module '\000/units/inb1105/inb1105_script.lua\000'
debug: Current gametime: 00:01:30
debug: Loading module '\000/units/urb1103/urb1103_script.lua\000'
debug: Loading module '\000/lua/ui/game/commandgraphparams.lua\000'
debug: Loading module '\000/lua/ui/game/commandwaypoint.lua\000'
debug: Loading module '\000/lua/ui/game/commandgraph.lua\000'
info: Hooked /lua/ui/game/commandgraph.lua with /schook/lua/ui/game/commandgraph.lua
debug: Loading module '\000/units/urb1101/urb1101_script.lua\000'
debug: Current gametime: 00:02:00
debug: Loading module '\000/units/inu1002/inu1002_script.lua\000'
debug: Loading module '\000/lua/ui/game/zoomslider.lua\000'
debug: Loading module '\000/units/inu1008/inu1008_script.lua\000'
debug: Loading module '\000/units/inb0102/inb0102_script.lua\000'
debug: Current gametime: 00:02:30
info: Minimized true
debug: Loading module '\000/units/inu1004/inu1004_script.lua\000'
debug: Loading module '\000/units/ina1005/ina1005_script.lua\000'
debug: Current gametime: 00:03:00
debug: Loading module '\000/units/inu1007/inu1007_script.lua\000'
warning: GetResource: Invalid name ""
info: Can't find texture "" -- trying fallback.
warning: GetResource: Invalid name ""
info: Can't find texture "" -- trying fallback.
warning: GetResource: Invalid name ""
info: Can't find texture "" -- trying fallback.
info: Minimized false
debug: Nuclear Repulsor Shields: Injecting BuilderGroup "NuclearRepulsorShields"
debug: Current gametime: 00:03:30
debug: Loading module '\000/lua/ui/dialogs/score.lua\000'
debug: Loading module '\000/lua/ui/dialogs/hotstats.lua\000'
debug: Loading module '\000/lua/ui/dialogs/myeffecthelpers.lua\000'
debug: Loading module '\000/lua/ui/dialogs/options.lua\000'
debug: Loading module '\000/lua/ui/menus/menucommon.lua\000'
debug: Loading module '\000/lua/options/options.lua\000'
info: Hooked /lua/options/options.lua with /nomadhook/lua/options/options.lua
debug: Loading module '\000/textures/ui/common/dialogs/options-02/options-02_layout.lua\000'
info: Minimized true
warning: GetResource: Invalid name ""
info: Can't find texture "" -- trying fallback.
warning: GetResource: Invalid name ""
info: Can't find texture "" -- trying fallback.
warning: GetResource: Invalid name ""
info: Can't find texture "" -- trying fallback.
info: Minimized false
debug: Loading module '\000/units/urb0101/urb0101_script.lua\000'
debug: Loading module '\000/units/inb0103/inb0103_script.lua\000'
debug: Loading module '\000/units/urb1202/urb1202_script.lua\000'
debug: Current gametime: 00:04:00
debug: Loading module '\000/lua/editor/sorianinstantbuildconditions.lua\000'
debug: Current gametime: 00:04:30
debug: Loading module '\000/lua/formations.lua\000'
debug: Loading module '\000/units/url0105/url0105_script.lua\000'
info: Hooked /units/url0105/url0105_script.lua with /mods/brewlan/hook/units/url0105/url0105_script.lua
debug: Loading module '\000/mods/brewlan/lua/fieldengineers.lua\000'
debug: Loading module '\000/units/urb1106/urb1106_script.lua\000'
debug: Current gametime: 00:05:00
debug: Loading module '\000/units/urb0201/urb0201_script.lua\000'
debug: Loading module '\000/lua/simcallbacks.lua\000'
info: Hooked /lua/simcallbacks.lua with /nomadhook/lua/simcallbacks.lua
info: Hooked /lua/simcallbacks.lua with /mods/blackopsfaf-unleashed/hook/lua/simcallbacks.lua
debug: Loading module '\000/lua/simping.lua\000'
debug: Loading module '\000/lua/selfdestruct.lua\000'
debug: Loading module '\000/lua/simcameramarkers.lua\000'
debug: Loading module '\000/lua/simdialogue.lua\000'
debug: Loading module '\000/lua/simdiplomacy.lua\000'
debug: Loading module '\000/lua/spreadattack.lua\000'
debug: Loading module '\000/lua/weaponpriorities.lua\000'
debug: Current gametime: 00:05:30
debug: Loading module '\000/units/urb3101/urb3101_script.lua\000'
debug: Loading module '\000/units/ina1001/ina1001_script.lua\000'
warning: Error running OnStopBuild script in Entity inb0103 at 89c17408: ...r\gamedata\lua.nx2\lua\sim\factorybuildermanager.lua(307): *AI ERROR: Invalid platoon template named - T3SubKiller
         stack traceback:
         	[C]: in function `error'
         	...r\gamedata\lua.nx2\lua\sim\factorybuildermanager.lua(307): in function `GetFactoryTemplate'
         	...r\gamedata\lua.nx2\lua\sim\factorybuildermanager.lua(435): in function `BuilderParamCheck'
         	...aforever\gamedata\lua.nx2\lua\sim\buildermanager.lua(258): in function `GetHighestBuilder'
         	...r\gamedata\lua.nx2\lua\sim\factorybuildermanager.lua(388): in function `AssignBuildOrder'
         	...r\gamedata\lua.nx2\lua\sim\factorybuildermanager.lua(429): in function `FactoryFinishBuilding'
         	...r\gamedata\lua.nx2\lua\sim\factorybuildermanager.lua(227): in function `cb'
         	...gramdata\faforever\gamedata\lua.nx2\lua\sim\unit.lua(3754): in function `DoOnUnitBuiltCallbacks'
         	...gramdata\faforever\gamedata\lua.nx2\lua\sim\unit.lua(2543): in function <...gramdata\faforever\gamedata\lua.nx2\lua\sim\unit.lua:2540>
         	(tail call): ?
         	...data\faforever\gamedata\lua.nx2\lua\defaultunits.lua(758): in function `DoStopBuild'
         	...data\faforever\gamedata\lua.nx2\lua\defaultunits.lua(740): in function <...data\faforever\gamedata\lua.nx2\lua\defaultunits.lua:735>
debug: Current gametime: 00:06:00
debug: Loading module '\000/mods/totalmayhem/units/brmat1advfig/brmat1advfig_script.lua\000'
debug: Nuclear Repulsor Shields: Injecting BuilderGroup "NuclearRepulsorShields"
debug: Current gametime: 00:06:30
debug: Loading module '\000/units/inb3101/inb3101_script.lua\000'
debug: Loading module '\000/units/ina1004/ina1004_script.lua\000'
debug: Current gametime: 00:07:00
debug: Loading module '\000/lua/sim/tasks/enhancetask.lua\000'
debug: Loading module '\000/lua/sim/scripttask.lua\000'
info: Hooked /lua/sim/scripttask.lua with /nomadhook/lua/sim/scripttask.lua
debug: Loading module '\000/units/urb2104/urb2104_script.lua\000'
debug: Loading module '\000/units/ina1003/ina1003_script.lua\000'
debug: Current gametime: 00:07:30
debug: Loading module '\000/units/ina1002/ina1002_script.lua\000'
debug: Current gametime: 00:08:00
debug: Current gametime: 00:08:30
debug: Loading module '\000/mods/totalmayhem/projectiles/nullweapon/nullweapon_script.lua\000'
debug: Loading module '\000/mods/totalmayhem/lua/tmprojectiles.lua\000'
debug: Loading module '\000/mods/totalmayhem/lua/tmeffecttemplates.lua\000'
debug: Loading module '\000/projectiles/caaautocannon02/caaautocannon02_script.lua\000'
debug: Loading module '\000/lua/cybranprojectiles.lua\000'
debug: Loading module '\000/projectiles/shieldcollider/shieldcollider_script.lua\000'
debug: Loading module '\000/effects/entities/debrismisc09/debrismisc09_script.lua\000'
debug: Loading module '\000/lua/genericdebris.lua\000'

**Comment by speed2CZ** [comment]
Hey, this doesn't belong here as this bug is caused by one or more of these mods or a combination of those. This repository contains only game code modified by FAF so it can't be fixed here.

You can try disabling some mods to find out which one is causing the crash and then either report it to the author or reporting it in the mods section of the faf forums.
Its not really possible to tell from the log which one causes the crash.
