### ISSUE TITLE
Get ally economy info back in

### ISSUE THREAD

**Issue by Sheeo** [FAForever/fa#271]
[This commit](https://github.com/FAForever/fa/commit/7da75c30e9da3b6b54505ec0fab568aba8f68fe2) reverts a lot of good work from @Crotalus because of a couple of issues we need fixed before 3639:

- Game quality would always show (This should be part of the UI option to turn the feature off)
- Game quality meter would show a weird string when game quality was not present

**Comment by Crotalus** [comment]
#354
