### ISSUE TITLE
Active Auto-Overcharge interfers with fire on ground for ACUs / SACUs

### ISSUE THREAD

**Issue by Justify87** [FAForever/fa#2717]
If I first activate auto-overcharge and then tell the unit to attack the ground, it simply moves to the attack point destination and does nothing. Tested with Sera SACU and Sera ACU.  

This is especially annoying since ground attack is the default behaviour nowadays.

For example replay ID: 9237036 at around minute 30-40 (its a sandbox game)

**Comment by shalkya** [comment]
although there is no occasion i can think of where you would ground fire with an ACU/sACU
