### ISSUE TITLE
Lobby rehosting bugs

### ISSUE THREAD

**Issue by Askaholic** [FAForever/fa#2724]
A few things I noticed:

Using java client 0.9.3-beta Windows 10

1. When starting a (coop) game with 1 mod enabled and rehosting, the mod will not show up as being active on the main lobby screen unless you click "Options" -> "Mods" -> "Ok". The mods screen still shows it as enabled, but you just don't get the notification in the game options window right underneath the map.

2. When the rehost happens the game also sends a bad `GameMods` packet to the server. Normally (AFAIK) it is supposed to send a packet with the string `activated` and then the number of active mods. It is then also supposed to send another packet with the string `uids` followed by a list of mod uuids (which are actual uuids so they look something like `ffffffff-ffff-ffff...`). However, when the rehost happens the `activated` packet is incorrectly named `uids` instead causing the server to think the client has requested the mod with uid `1` which isn't valid. Here are some server logs:

```
# The first time the game is launched
DEBUG    server.db.logging_cursor.LoggingCursor Executing query: SELECT `uid`, `name` from `table_mod` WHERE `uid` in %s with args: (['f018d977-ac53-495a-8d5f-48e5665e63bd'],)

# After the rehost
DEBUG    server.db.logging_cursor.LoggingCursor Executing query: SELECT `uid`, `name` from `table_mod` WHERE `uid` in %s with args: (['f018d977-ac53-495a-8d5f-48e5665e63bd'],)
DEBUG    server.db.logging_cursor.LoggingCursor Executing query: SELECT `uid`, `name` from `table_mod` WHERE `uid` in %s with args: (['1'],)
DEBUG    server.db.logging_cursor.LoggingCursor Executing query: SELECT `uid`, `name` from `table_mod` WHERE `uid` in %s with args: (['f018d977-ac53-495a-8d5f-48e5665e63bd'],)
```

Looks like after the rehost, the lobby sent 3 `uid` packets one of which was a dupe, and one of which should have been the `activated` packet instead.

**Comment by bukajsytlos** [comment]
Also rehosting password protected game, results in public game

**Comment by MrRowey** [comment]
@Garanas cant this be closed as rehost was disabled
