### ISSUE TITLE
Ctrl K for Draw in Global games registering as a win

### ISSUE THREAD

**Issue by DBazer** [FAForever/fa#2737]
In custom/global 1v1 games, if a player self destructs their acu to achieve mutual K.O with the opponent's acu when they're under 2500hp, the replay vault then shows the player who ctrl k'd as the winner of the match, whereas in reality the game is a draw.
Score in the replay preview says +1 for the "winner" (ctrl k guy) and -10 (used to be 0 prior to recent changes) to the poor victim of a last ditch ctrl k to draw move.
Normally in a legitimately won game, score says +10 for the winner.
This has been happening consistently for at least a year.

Example: ![Untitled](https://user-images.githubusercontent.com/48331623/54825540-89baf280-4cb6-11e9-8a73-f7c403dbeee1.jpg)

Problem with that is obvious, a draw is a draw and the score preview should reflect the true result.
This doesn't happen with ladder games for example, only with custom 1v1s.

Not a new issue, has been this way for as long as I can remember, simply only bothering with asking for a fix now. Enough with the travesties.

Thanks.

**Comment by axel1200** [comment]
@Brutus5000 it might actually correct in this repo right? Becuase the server probably only writes the values the game sends into the database...

**Comment by Askaholic** [comment]
@axel1200 The server has to merge all players reported results into a single result to put in the database so it’s possible that the results in this particular situation are reported differently by both players and the server isn’t recognizing it as a draw.

Interesting that it doesn’t happen in ladder games. 

Should be pretty easy to test on the test server.

**Comment by axel1200** [comment]
I know but I assume that the server simply writes into the "scores" column what was sent from the game as score. So if the game sent -1 and 10 as score it would be a problem within the game but yeah idk what the game sent in this case and how the server processes it. So yeah probably testing that on the test server would be good. Also a game log would help, game probably writes down what it reports as a result to the server

**Comment by Askaholic** [comment]
Yes the server uses scores from the client (except for ladder games, it forces ladder scores to be 1, 0 or -1), but remember that both players report scores for each other, so if Player1 says that he had a score of +10, but Player2 says that Player1 had a score of +5, then the server has to decide who to believe. Currently the server takes the most frequently occurring score, or the highest score if there is an even split of votes. 

The game results would appear in the server log, but i'm not sure if those logs are kept around very long. Maybe the clients have a log of this somewhere too?

**Comment by axel1200** [comment]
ok but in case it is a draw and both ppl send 10 for both players the server would enter 10 for each what would be the way it should be i think or -1 for both(not sure what it is gonna be).  So if it is the way you describe it would be ok and for it to enter the result of the screenshot the game would have needed to send some strange result. Thats why i meant it might be game bug. The server is running in a docker-container which keeps logs pretty long, however it is really hard to search in those...

**Comment by Askaholic** [comment]
Yes it definitely could be a game bug. I'm just saying it's *possible* that the server is involved somehow too.

**Comment by Askaholic** [comment]
Did a test game. Askaholic did the ctrl-k, here are the results:
```
INFO     CustomGame.8571557             Player(Askaholic, 166198, (1495.86, 98.7115), (99.0659, 14.1666)) reported result for army 1: score 1
INFO     CustomGame.8571557             Player(keyser, 58789, (2178.69, 77.7956), (1500.26, 10.047)) reported result for army 1: score 1
INFO     CustomGame.8571557             Player(keyser, 58789, (2178.69, 77.7956), (1500.26, 10.047)) reported result for army 1: defeat -10
INFO     CustomGame.8571557             Removed game connection GameConnection(Player(keyser, 58789, (2178.69, 77.7956), (1500.26, 10.047)), Game(8571557,Askaholic,maps/scmp_013.zip,2))
DEBUG    server.gameconnection.GameConnection GameConnection(Player(keyser, 58789, (2178.69, 77.7956), (1500.26, 10.047)), Game(8571557,Askaholic,maps/scmp_013.zip,2)).abort()
INFO     CustomGame.8571557             Player(Askaholic, 166198, (1495.86, 98.7115), (99.0659, 14.1666)) reported result for army 2: defeat -10
INFO     aiomysql                       UPDATE game_stats SET endTime = NOW() WHERE id = 8571557
INFO     aiomysql                       (8571557,)
INFO     CustomGame.8571557             Removed game connection GameConnection(Player(Askaholic, 166198, (1495.86, 98.7115), (99.0659, 14.1666)), Game(8571557,Askaholic,maps/scmp_013.zip,2))
INFO     CustomGame.8571557             Game finished normally
DEBUG    CustomGame.8571557             Saving scores from game 8571557
INFO     CustomGame.8571557             Result for army 2, player: Player(keyser, 58789, (2178.69, 77.7956), (1500.26, 10.047)): -10
INFO     CustomGame.8571557             Conflicting scores (Counter({1: 2, -10: 1})) reported for game Game(8571557,Askaholic,maps/scmp_013.zip,2)
INFO     CustomGame.8571557             Result for army 1, player: Player(Askaholic, 166198, (1495.86, 98.7115), (99.0659, 14.1666)): 1
INFO     CustomGame.8571557             Score for player Player(keyser, 58789, (2178.69, 77.7956), (1500.26, 10.047)): -10
INFO     CustomGame.8571557             Score for player Player(Askaholic, 166198, (1495.86, 98.7115), (99.0659, 14.1666)): 1
```

Here my client reported a score of 1 for my army and a score of -10 for Keyser's. But Keyser's client also only reported scores for my army. So as a result, my army (the ctrl-k) has 3 results which are conflicting and get resolved to the highest score, while the other army only has the 1 defeat result.

So it looks like it's primarily a client issue.

**Comment by axel1200** [comment]
You mean client as in the game client because as far as i am concerned the client itself has nothing to do with it. Well it might not forward the message correctly but i dont think that is the case.

**Comment by Askaholic** [comment]
Fixed by https://github.com/FAForever/server/pull/496
