### ISSUE TITLE
Large map preview won't close

### ISSUE THREAD

**Issue by aeoncleanse** [FAForever/fa#277]

**Comment by ChrisKitching** [comment]
Whoops. I'll submit a PR in the morning ;)

**Comment by ChrisKitching** [comment]
Looks it it is closeable, but you can click the open button more than once, producing a "stack" of large map previews. Only the newest one is at any time closeable, so if you accidentally click the button twice... you're fucked.
Let's fix that. While we're here we might as well improve the UI for closing the dialog: it'd be nice if the escape key closed it as well.
