### ISSUE TITLE
lobby should display info about a game being ranked or not

### ISSUE THREAD

**Issue by LCR22222** [FAForever/fa#2780]
Multiplayer game is not telling when game is ranked. It's continuous debate in multiplayer games. Not a bug, feature request. Make game tell when it's ranked.

**Comment by HUSSAR-mtrela** [comment]
FAF lobby can implement this feature by copying logic from Supreme Score Board mod which displays rated/unrated games

**Comment by shalkya** [comment]
iirc, we used to have lobby display if game was rated or not. Zepilot decided to remove this, to make people focus less on rating, ie : people shouldn't worry if game is rated or not.
Furthermore he considered unrated games as damaging the accuracy of the rating, thus he didn't want to promote unrated games by displaying "unrated game" when certain option were enable.
This change was implement along rounding of rating for example. Overall idea is to have rating to help player balance game, but he didn't want rating to work as a reward function.

**Comment by Garanas** [comment]
This is not possible as the lobby (the game) is not aware of what maps are and are not ranked.
