### ISSUE TITLE
Supreme Commander Original Campaigns Voiceovers Playing Over Eachother

### ISSUE THREAD

**Issue by squirrelkiller** [FAForever/fa#2788]
When playing the original Supreme Commander Campaigns as a client rather than host the following issue is observed:

Whenever a voice over sequence with dialog takes place, such as receiving new objectives mid mission, the communications window will open in the upper Left of the Screen, but will not have subtitles nor will a character portrait appear. Instead it will simply show a faction icon before immediately closing once finishing the "opening" animation followed by all the voice clips for that section playing over top of each other resulting in near unintelligible noise.

The host player does not appear to ever experience this problem. This does not happen with the Forged Alliance Campaign. This can be confirmed, without a doubt, to be the case for the Aeon and Cybran campaigns, untested for UEF at this point.

**Comment by speed2CZ** [comment]
Its a client issue and already reported in the correct repo.
Use this for now https://forums.faforever.com/viewtopic.php?f=78&t=16674&p=167547&hilit=unpack#p167547

**Comment by expipiplus1** [comment]
@speed2CZ I couldn't find such an issue in any of the FAForever repos. Would you mind linking it, and then I can close my duplicate here: https://github.com/FAForever/downlords-faf-client/issues/1493

**Comment by speed2CZ** [comment]
https://github.com/FAForever/downlords-faf-client/issues/1156

but you have superior description, so your call which one should stay
