### ISSUE TITLE
Feature: Re-balance T1-T3 Engineers

### ISSUE THREAD

**Issue by HUSSAR-mtrela** [FAForever/fa#2791]
**Current:**
All engineers (except Sparky) have ratio of build rate to mass cost equal to 0.096 
```
- T1 Engineer has 05.0 build rate / 052 mass costs = 0.096 ratio
- T2 Engineer has 12.5 build rate / 130 mass costs = 0.096 ratio
- T3 Engineer has 30.0 build rate / 312 mass costs = 0.096 ratio
- T2 Sparky   has 18.0 build rate / 225 mass costs = 0.08 ratio
```
As result of that, most players (in air/navy slots) build a lot of T1 engineers because it is faster to build them and T2-T3 engineers are not cost efficient to increase build power. Aslo, T1 engineers cause a lot of path finding issues in bases and decrease sim performance. 

**Expected:**
All engineers should have different ratio of build rate to mass cost so higher tech engineers are less costly to build to gain more build rate. 
```
- T1 Engineer should have 05.0 build rate / 052 mass costs = 0.096 ratio (unchanged)
- T2 Engineer should have 15.5 build rate / 130 mass costs = 0.120 ratio (+25% increase)
- T3 Engineer should have 45.5 build rate / 312 mass costs = 0.145 ratio (+50% increase)
- T2 Sparky   should have 22.5 build rate / 225 mass costs = 0.100 ratio (+25% increase)
```
With these changes players will not have to build so many T1 engineers and thus improve sim performance.

Alternatively/Additionally, higher tech engineers should have larger build range so they can assist factories from larger range and thus they can operate more efficiently in bases than T1 Engineers.

```
- T1 Engineer should have 05.0 build range (unchanged)
- T2 Engineer should have 07.0 build range (+2 increase)
- T2 Sparky   should have 07.0 build range (+2 increase)
- T3 Engineer should have 09.0 build range (+4 increase)
- T3 SCUs     should have 15.0 build range (+5 increase)
```

**Comment by rjy7wb** [comment]
so instead of a flat mass->build ratio, a linear increase in mass -> build power efficiency.
makes sense.

**Comment by TobiasJacob** [comment]
I agree on that, I think this is a good idea.

**Comment by MrRowey** [comment]
@Tagada14 Close this if balance team dose not see this to be changed

**Comment by Garanas** [comment]
I'd like to add to it that changing this in favor of t2 / t3 engineers is a reasonable performance gain.

**Comment by Tagada14** [comment]
There was a discussion about a similar proposition in the balance team when I first joined and the consensus was that it's not something we want to implement. Instead, we buffed the build range of higher-tech engineers. I will see what the rest of the Balance team thinks about it now.

**Comment by Tagada14** [comment]
We have discussed this again and the higher-tech engineers will get a bit more BP
