### ISSUE TITLE
Error when killing ACU

### ISSUE THREAD

**Issue by speed2CZ** [FAForever/fa#2792]
```
warning: Error running OnKilled script in Entity uel0001 at 2c1add08: ...data\faforever\gamedata\lua.nx2\lua\defaultunits.lua(2437): attempt to perform arithmetic on local `massKilled' (a nil value)
         stack traceback:
         	...data\faforever\gamedata\lua.nx2\lua\defaultunits.lua(2437): in function `OnKilledUnit'
         	...faforever\gamedata\lua.nx2\lua\scenarioframework.lua(211): in function <...faforever\gamedata\lua.nx2\lua\scenarioframework.lua:172>
         	[C]: in function `Kill'
         	...faforever\gamedata\lua.nx2\lua\scenarioframework.lua(169): in function <...faforever\gamedata\lua.nx2\lua\scenarioframework.lua:165>
```
`massKilled` seems to be `nil` for some reason 
https://github.com/FAForever/fa/blob/develop/lua/defaultunits.lua#L2437

It leads me to this:
https://github.com/FAForever/fa/blob/develop/lua/sim/Unit.lua#L1318
`unit:OnKilledUnit(self, massKilled)`
Shouldn't `massKilled` be third parameter? To make this work?
`OnKilledUnit = function(self, unitKilled, massKilled)`

**Comment by aeoncleanse** [comment]
No. `unit` is passed through as arg1 to self, `self` is passed through to arg2 as the unit that's been killed, the mass as arg3. Remember this line is called from the point of view of the unit which dealt the damage.
