### ISSUE TITLE
dds images have lost some transparency information

### ISSUE THREAD

**Issue by ChrisKitching** [FAForever/fa#281]
Seems the conversion to dds caused a UI regression:

Before:
http://i.imgur.com/t2Fx1Ji.png

After:
http://i.imgur.com/vjph38C.png

It should be possible to emit fixed dds images, otherwise we can revert to PNGs (and use the nifty "AppendFileExtension" function GPG provide to avoid re-introducing the code complexity)

**Comment by aeoncleanse** [comment]
There's no transparency difference here that I can see, but a slight tint difference probably caused by fundamental differences between the ways that .dds and .png record and store colours. Looking at those two screenshots, I can see the difference, but frankly I don't think it matters.

**Comment by ChrisKitching** [comment]
I think it's a mixture: You're right, some colour data as also been discarded.

In any case, it's probably due to my having used imagemagick with default settings to do the transcoding. There'll be a brief interlude while I look up the appropriate magic spell to make it not do that any more :P

**Comment by aeoncleanse** [comment]
It's called "Use Photoshop for everything - It's better" ;)

**Comment by ChrisKitching** [comment]
Except that it costs money and can't do batch processing :P

**Comment by Sheeo** [comment]
Actually it's able to do batch processing -- albeit through an awkward interface

**Comment by aeoncleanse** [comment]
We think we cracked this now, waiting on the results
