### ISSUE TITLE
LOD1 models issues

### ISSUE THREAD

**Issue by speed2CZ** [FAForever/fa#2833]
These mobile units are either missing LOD1 models or they don't have them specified in their bp:
Aeon:
- [ ] uaa0203 - T2 gunship
- [ ] ual0001 - ACU
- [ ] dalk003 - T3 MAA
- [ ] xal0305 - Sniper Bot (model exists but its legs are sinken in the gound)

Cybran:
- [ ] 
- [ ] 
- [ ] 
- [ ] 

UEF:
- [ ] uea0101 - T1 scout
- [ ] uel0001 - ACU
- [ ] delk002 - T3 MAA
- [ ] ues0302 - Battleship
- [ ] ues0401 - Atlantis
- [ ] xes0307 - Battlecruiser

Seraphim:

**Comment by HUSSAR-mtrela** [comment]
@speed2CZ did you forget to include Cybran units in above empty list?

**Comment by speed2CZ** [comment]
Hmm, the list was complete the last time I checked, no idea where it has gone. But I won't redo it again

**Comment by HUSSAR-mtrela** [comment]
@speed2CZ that's alright, my blueprint verification tool/feature will detect this kind of issues

**Comment by MrRowey** [comment]
@Garanas Close this issue in favour for the more Complete list on #2834
