### ISSUE TITLE
Second Shift+G on same group caused game crash in multiplayer

### ISSUE THREAD

**Issue by Arkemlar** [FAForever/fa#2846]
Air fight... I attack-clicked like 7 enemy inties and pressed shift+g, then I attack-clicked like 6 more and pressed shift+g again, game freezed. By another screen I opened Process manager, it said process not responding (and consumed like 15-17% of CPU time and also I had a lot of free memory left). By the time, in main screen game remained in last moment, I took photo of the screen (attached). When I clicked on the game in windows' task bar it showed an exception window (attached). I repeated once again, and another exception window occured with same exception, and so on. So I had to kill the game's process.

![errors](https://user-images.githubusercontent.com/19671202/63122387-4cca0200-bfaf-11e9-9892-ea249529c52d.png)
```
Failed to setup initial search path.

Program : C:\ProgramData\FAForever\bin\ForgedAlliance.exe
Cmd line arguments : 

Callstack:
	Unknown symbol (address 0x008cef50)

Last 100 lines of log...

warning: Running "C:\ProgramData\FAForever\bin\SupComDataPath.lua" failed: cannot read init_faf.lua: No such file or directory
         stack traceback:
         	[C]: in function `dofile'
         	C:\ProgramData\FAForever\bin\SupComDataPath.lua(2): in main chunk
```

![IMG_20190815_222655](https://user-images.githubusercontent.com/19671202/63122491-90247080-bfaf-11e9-9220-cf6dbb6032ee.jpg)
(I used phone to take this screenshot because afraid that standard screenshot technique wont work in crushed game and were right, there were no picture in the buffer)

**Comment by HUSSAR-mtrela** [comment]
@aeoncleanse, @speed2CZ, @shalkya, @Petricpwnz 
to fix this issue we need to first decide on what should the game do with targets that were queued in previous and new Shift+G command. Here are some options:

1. Redistribute attack on combine targets from previous and new Shift+G command
2. Remove attack on targets from previous  Shift+G and set attack only on targets the new Shift+G command 

Additionally, the Shift+G command could be improved for performance by limiting number of attack commands one target can get.

**Comment by Arkemlar** [comment]
I like option 1 and dont like option 2. Also limiting number of attack commands is good idea. I think 3 is enough. About option 1: I think first it needs to get the list of all targets both shift-Ged already and new ones, cancel all orders and then reassign orders like it normally does.

**Comment by HUSSAR-mtrela** [comment]
yes, option 1 will be very close to what you said

**Comment by KionX** [comment]
The game probably froze due to file access problems.
Shift+G has nothing to do with this.
I didn't find any other issues mentioning Shift+G and froze.
This was most likely caused by a third-party application or hardware failure.
Need close.

**Comment by shalkya** [comment]
i heard that it happened in other cases (visionik reported it once iirc)

**Comment by Arkemlar** [comment]
During my entire game history it happened twice, both in the way described in head: when pressed second time shift-g on already spread attacked group of targets with additional units. Now Im afraid to do so with big target numbers.
