### ISSUE TITLE
Sound issue in game

### ISSUE THREAD

**Issue by Gandalf2k15** [FAForever/fa#2848]
So for some reason in game sounds are no longer working correctly. For instance when you are supposed to hear dulled sounds after zooming out, everything on the map creates an ungodly amount of noise instead of staying quiet. It's like the sound engine or something is borked. I can pretty much guarantee the thing that broke it was the latest windows update. Not sure if it's just me with this problem or not.

**Comment by speed2CZ** [comment]
Sound driver issue, windows do like to update them and fuck up things.
https://forums.faforever.com/viewtopic.php?f=3&t=13963#sound

Also always use stereo fro this game.
