### ISSUE TITLE
allow max tech building of selected mixed tech engies

### ISSUE THREAD

**Issue by shalkya** [FAForever/fa#2857]
http://forums.faforever.com/viewtopic.php?f=42&t=18211

when you have selected engies from several tech level, you can only build structures of the lowest tech.

Proposed change : allow to build structure of the max tech level of selected engies and when ordering a structure of high tech level make the tech level engies assist the high tech level ones.

**Comment by MrRowey** [comment]
As Far as im aware this is not possible to do
