### ISSUE TITLE
E storage icon displayed incorrectly

### ISSUE THREAD

**Issue by BlackYps** [FAForever/fa#2888]
when using bigger icons for the build menus (ingame option), the icon is still the old one. Except for seraphim, there it displays the little icon.

Also the storage icon is slightly different to the icon for the power generator rotated by 90°. Is this intentional?

![e-storage](https://user-images.githubusercontent.com/52536103/67151412-3f3e3a80-f2c6-11e9-9786-02a7142f646b.png)

**Comment by shalkya** [comment]
@speed2CZ will know better i guess

**Comment by speed2CZ** [comment]
might be because the icon got renamed or the bigger version doesnt exist. I won't investigate it
