### ISSUE TITLE
I fixed a bug in the hack ArmyGetHandicap and added sim SetFocusArmy

### ISSUE THREAD

**Issue by KionX** [FAForever/fa#2894]
How can I add this to the patch?

**Comment by shalkya** [comment]
i don't get the issue, can't you make a pr ?

**Comment by KionX** [comment]
This is the patch for ForgedAlliance.exe
Did not find a suitable repo.

**Comment by shalkya** [comment]
Then you can post it there : https://github.com/FAForever/FAPatch
but i think @FAETHER work most of the time here : https://github.com/FAETHER/FA-Binary-Patches

worth while to check these stuffs too : https://github.com/FAETHER/FA_Patcher
https://github.com/FAETHER/Supreme-Commander-FA-patch
