### ISSUE TITLE
Error on game launch

### ISSUE THREAD

**Issue by aeoncleanse** [FAForever/fa#292]
WARNING: Error running lua script: c:\github\fa\lua\ui\lobby\lobby.lua(5311): attempt to call method `Enable' (a nil value)
         stack traceback:
         	c:\github\fa\lua\ui\lobby\lobby.lua(5311): in function `StressCPU'
         	c:\github\fa\lua\ui\lobby\lobby.lua(3774): in function <c:\github\fa\lua\ui\lobby\lobby.lua:3774>

**Comment by ChrisKitching** [comment]
This is harmless, but stupid. It's the CPU benchmark trying to output its results to the UI after it's finshed runnning.. while you were in the game.

It shouldn't be running then at all. (Or ever, if we're brutally honest, but let's make it marginally less terrible first)
