### ISSUE TITLE
Othuum Buff?

### ISSUE THREAD

**Issue by Azraeel** [FAForever/fa#2967]
Can we get some kind of Othuum buff. Their designation as a Seige tank is actually extremely false. Not only do they have one of the lowest healths in T3 Unit, Their Damage isnt that impressive at all. Their pretty much non-existance on the battlefield too. Their outranged and outgunned and out healthed by most t3 main battle units. They are also so fucking slow.

**Comment by vinyl117** [comment]
Get rid of t3 arty and give it to the othuum in a siege mode. Hell add an MML that works like a shield disruption and increase the cost by 50%, GG EZ.

**Comment by shalkya** [comment]
https://github.com/FAForever/fa/pull/2962

**Comment by PhilipJFryFAF** [comment]
if you want to have a discussion then make a post on the forum
issues should be used for game bugs and not your opinion on the game balance
