### ISSUE TITLE
Can you tell me the correct way to install it?

### ISSUE THREAD

**Issue by ZeroCiel** [FAForever/fa#2974]
Can you tell me how I should install it?
I can't find the fa_path file..
The download directory also failed to find it.

**Comment by ZeroCiel** [comment]
And the game say：
warning: Running "E:\My Game\steamapps\common\Supreme Commander Forged Alliance\bin\SupComDataPath.lua" failed: cannot read E:\My Game\steamapps\common\Supreme Commander Forged Alliance\bin..\repo\faf\init.lua: No such file or directory

I don't quite understand how I should install it. Can someone help me?

**Comment by shalkya** [comment]
install what ? if it's the game you need to buy ans install it through steam, if it's the faf client you need to get it here : https://www.faforever.com/
This repository is only for developers. You don't need to download the github repository.

**Comment by ZeroCiel** [comment]
OK!Thankyou!I thought it was a MOD,Thank you very much for your advice!
