### ISSUE TITLE
pls dear god save us from dual gap replays

### ISSUE THREAD

**Issue by PhilipJFryFAF** [FAForever/fa#2991]
someone pls revert the teamkill report feature
it's drowning the moderation team in cancer reports - half of which are from games against the AI/survival games or other meme games that aren't worth watching.
The other half are 50+ mins dual gap/astro crater games that are making my eyes bleed.
If someone wants to report another user for teamkilling they can do so manually.
thx in advance @speed2CZ

**Comment by speed2CZ** [comment]
Last time I was promised 1TB SSD, what do you offer now?

**Comment by MrRowey** [comment]
@Garanas i would say this could be closed if this is more to do with the server side
