### ISSUE TITLE
no adjacency bonuses on underwater mass extractor: naval storage please

### ISSUE THREAD

**Issue by mirddes** [FAForever/fa#2999]
underwater metal extractors were cool!

i was so excited when i finally got my hands on supreme commander beta2.

underwater mass extractors!!! woooo!!!!!!

sadly no adjACENCY 
![CORUWMEX](https://user-images.githubusercontent.com/13982888/74892205-d38fe980-53ed-11ea-967c-f65635ca26cb.png)
BONUSES :(

**Comment by speed2CZ** [comment]
Report it to the mod author. It's not part of the original game so it can't be fixed here.

**Comment by mirddes** [comment]
Ok I'll use full sentences this time.

It should be base game. It was stupid 10 years ago not being base game. It probably affects 3% of matches. It's a good change. It's no where near as drastic as suggesting upgradable storage be base game... that affects 100% of matches.

So its got nothing to do with mods.

**Comment by speed2CZ** [comment]
I doubt that such change will ever get implemented, that's what mods are exactly for.
