### ISSUE TITLE
about language（CN）

### ISSUE THREAD

**Issue by ZeroCiel** [FAForever/fa#3010]
If I want to push the Chinese language to you, who should I send it to?

HMM, I simply processed the traditional Chinese text, and I want to push the simplified Chinese to you.

**Comment by ZeroCiel** [comment]
lobui_0397="Show System Message"
lobui_0398="Display error logging in the chat window"
lobui_0399="Lobby Developers"
lobui_0400="Stretch Background"
lobui_0401="Stretch background to fill screen."
lobui_0402="Windowed Mode"
lobui_0403="Lobby is windowed until launch"
lobui_0404="Chat Font Size:"
lobui_0405="Lobby Background"
lobui_0411="Faction Font Color"
lobui_0460="Player color in chat"

397~411 line
Attempts to translate this paragraph are invalid.

**Comment by shalkya** [comment]
you can just make a pull request with your modification, we will review (as best as we can) and then merge it

**Comment by ZeroCiel** [comment]
ok，I check the file first, it seems that the TW file format is not written in order, I didn't notice where the new code was behind the file....I will upload it when I finish.by tomorrow at the latest

**Comment by speed2CZ** [comment]
I dont think there's any "order", EN file isnt complete, and has different strings order than other files. Actually it's kinda messy. The order doesn't really matter for the game, so as long as there's no syntax error in the file, you should be good.

Meanwhile @shalkya will prolly learn Chinese to review your changed :D

**Comment by ZeroCiel** [comment]
$ git add . && git commit -m "Add CN" && git push
warning: LF will be replaced by CRLF in loc/CN/strings_db.lua.
The file will have its original line endings in your working directory
[develop 6efc4819] Add CN
 1 file changed, 8430 insertions(+)
 create mode 100644 loc/CN/strings_db.lua
remote: Permission to FAForever/fa.git denied to ZeroCiel.
fatal: unable to access 'https://github.com/FAForever/fa.git/': The requested URL returned error: 403

I don't know how to solve it.
and,Can I find you through steam or email?

I have noticed that some English is still missing.
 If possible, please help me to add this part of the code so that I can complete the translation.

**Comment by ZeroCiel** [comment]
> I dont think there's any "order", EN file isnt complete, and has different strings order than other files. Actually it's kinda messy. The order doesn't really matter for the game, so as long as there's no syntax error in the file, you should be good.
> Meanwhile @shalkya will prolly learn Chinese to review your changed :D

If possible, please contact me as soon as possible
