### ISSUE TITLE
fatal: Authentication failed for 'https://github.com/FAForever/fa/'

### ISSUE THREAD

**Issue by ZeroCiel** [FAForever/fa#3014]
$ git add . && git commit -m "Add CN/增加 简体中文" && git push
warning: LF will be replaced by CRLF in loc/CN/strings_db.lua.
The file will have its original line endings in your working directory
[develop 734fa6c6] Add CN/增加 简体中文
 1 file changed, 8710 insertions(+)
 create mode 100644 loc/CN/strings_db.lua
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/FAForever/fa/'

So can you give me your contact information？
Steam or email,please！

**Comment by ZeroCiel** [comment]
or

remote: Permission to FAForever/fa.git denied to ZeroCiel.
fatal: unable to access 'https://github.com/FAForever/fa/': The requested URL returned error: 403

I've been waiting here for days

**Comment by KionX** [comment]
Commit to your repository https://github.com/ZeroCiel/fa.git
Then click pull request.

**Comment by ZeroCiel** [comment]
> Commit to your repository https://github.com/ZeroCiel/fa.git
> Then click 'pull request' and choose deploy/fafdevelop.

Well, does it need to be modified there? To be honest, I don't know much about how GitHub works

**Comment by shalkya** [comment]
to explain github : 
there is a repository called FAForever/fa that everyone can see, and only few person can modify it. When you want to contribute you need to fork the repository and make changes on your fork. When ready you create a pull request from your repo against FAForever/fa. If you need to change anything in your PR, you just need to update the branch on your repo; the PR will autoupdate.

**Comment by ZeroCiel** [comment]
> to explain github :
> there is a repository called FAForever/fa that everyone can see, and only few person can modify it. When you want to contribute you need to fork the repository and make changes on your fork. When ready you create a pull request from your repo against FAForever/fa. If you need to change anything in your PR, you just need to update the branch on your repo; the PR will autoupdate.
> When people with access to the main repo have time, they will review/merge your changes.

You mean wait for them to go through the code, at right?
Then I'll wait for the announcement.

**Comment by shalkya** [comment]
i already told you something to change in the PR, i have contacted chinese speaking person for reviews.
