### ISSUE TITLE
'Exit to FAF' causes incorrect game results (and therefore rating issues)

### ISSUE THREAD

**Issue by Askaholic** [FAForever/fa#3031]
While investigating the rating issues I noticed a strange pattern. Games which were not rated correctly seemed to always have a player who randomly quit before their ACU died. 

As it turns out exiting the game via the `Exit to FAF` causes the game to send a `defeat` result for every player in the game except yourself. This really messes with the rating code!

## To reproduce
1. Load up a game with at least 2 players
2. Build some buildings/unit (It seems like if you don't build anything then it does not send incorrect results)
3. One player hits `Exit to FAF`
Now if that player checks their game.log they will see that they did not report any results for themselves, but reported `defeat` for the other players in the game.

I've been trying to debug this and I haven't found the root cause of the issue. At first I though it was caused by the checks in `victory.lua` somehow determining that all players had lost due to faulty logic. However, when I add some debug log statements, it seems that this code is not what is triggering the game results. So it seems to me like `SessionEndGame()` must be setting the results of other players to `defeat` internally which is then being picked up by UserSync.lua.

Then again I don't have any experience with the lua code or the game internals so I imagine someone else will be able to debug this quicker than me.

**Comment by Askaholic** [comment]
From my investigation, it seems like our best option would be to set some sort of global flag in `SafeQuit` signaling that the game is exiting, which then gets checked in `UserSync.lua` and any results that are reported after the exiting flag is set just get ignored.

**Comment by Strogoo** [comment]
The only thing I don't like about flag in `SafeQuit` is that it's an Ui function and it's triggered only by player who is leaving the game (means we can't secure it with reports from other players too).

Mmm, can we somehow ignore such reports using only server-side checks? For example if one player sends multiple "defeats" for others, then we wait 5-10 secs for any reports about these defeats from other players and only then mark them as valid and save for further calculations.

**Comment by Askaholic** [comment]
Well the issue only exists for the player who leaves via `Exit to faf`. Other players in the game send the correct game results.
