### ISSUE TITLE
cybran shield + hyves - bad eco bug

### ISSUE THREAD

**Issue by adminxp** [FAForever/fa#3042]
replay 34+ min https://content.faforever.com/faf/vault/replay_vault/replay.php?id=11372599
recorded video of issue: https://www.youtube.com/watch?v=Ph8BpAL7sDc&feature=youtu.be
description: hyves started to assist shield - doing nothing, shield was not upgraded by them nor healed, just a lot of build power with huge mass consumption for nothing.
If I had no paragon that would exhuast my eco in few seconds.

**Comment by Garanas** [comment]
It appears this happens when the shield has taken damage, you start upgrading (clicking the button) but the hives start assisting between you clicking the button and the upgrade actually happening.

**Comment by Garanas** [comment]
No, it is different. You can reproduce it by:

- Shield of structure takes damage
- Set engineers to assist the structure, healing the shield
- Upgrade the structure during while the shield is being healed
- Bug as described

Now, what can we do about it 😄
