### ISSUE TITLE
Old underlying texture persists under underlying texture of a new building.

### ISSUE THREAD

**Issue by MerryPanda** [FAForever/fa#3043]
Hello

When you build a new building on a spot of previously destroyed building, the new underlying texture is added on top of underlying texture of previously destroyed building, that looks crappy.

Thanks

**Comment by speed2CZ** [comment]
The old one disappears after 5min or so

**Comment by MerryPanda** [comment]
> 
> 
> The old one disappears after 5min or so

hmm... are you sure? i will check

**Comment by speed2CZ** [comment]
Pretty sure
https://github.com/FAForever/fa/blob/develop/lua/defaultunits.lua#L424-L432

**Comment by MerryPanda** [comment]
> 
> 
> Pretty sure
> https://github.com/FAForever/fa/blob/develop/lua/defaultunits.lua#L424-L432

Thank you for such a thorough answer, thought i don't understand the code :)

**Comment by MerryPanda** [comment]
> "The old one disappears after 5min"

yes yes, it was not sarcasm. I really appreciate the code reference. Thank you
