### ISSUE TITLE
Suggestion: Limited wreckage lifetime

### ISSUE THREAD

**Issue by MerryPanda** [FAForever/fa#3062]
I think wreckage needs a decay timeout. It might lose half of its value every ~15 mins, and disappear completely on timeout tick if the value is less than 100 mass, eg.

I think it will reduce lag as well :)

**Comment by KionX** [comment]
https://github.com/FAForever/fa/pull/2895 No effect was seen on lag.

**Comment by MerryPanda** [comment]
> 
> 
> #2895 No effect was seen on lag.

well, for me it mostly to remove this small wrecks all over the map and my base... it just irritates and looks ugly

**Comment by KionX** [comment]
I can publish this as a mod. Or, if you want it to be integrated into the FAF, ask the JaggedAppliance for this.

**Comment by MerryPanda** [comment]
> 
> 
> I can publish this as a mod. Or, if you want it to be integrated into the FAF, ask the @JaggedAppliance for this.

well i think the feature is good as part of vanilla :)
@JaggedAppliance may we have limited wreckage lifetime nonetheless? It is good for aesthetics as well :D

**Comment by MrRowey** [comment]
@Tagada14 this can be closes if you don't see wrecks having a time limit on them

**Comment by Garanas** [comment]
There are no performance complaints either - they're just props. You'd need tens of thousands of them to affect the game noticeably - looking at Forest Nothing.

**Comment by KionX** [comment]
A lot of wrecks can affect graphics performance. Is there a problem with that?

**Comment by Garanas** [comment]
Not that I am aware of.
