### ISSUE TITLE
Suggestion: Increase shield building HP

### ISSUE THREAD

**Issue by MerryPanda** [FAForever/fa#3070]
Stationary shields seem too fragile. As it is a strategic building, i think it is strange that it almost can't handle a shot.

I suggest to increase HP:
T2 -> 2000
T3 -> 4000

What do you think?

**Comment by FemtoZetta** [comment]
Well it provides a shield, that is the upside. The downside is that once the shield is down or units got in range, the shield generator dies fast. Would be dumb to change this, and would make shields too strong and would make gameplay worse.

I think this should be closed.

**Comment by MrRowey** [comment]
@Tagada14 i don't see this being a issues with the current balance and could be closed
