### ISSUE TITLE
BALANCE: Seraphims can't live without a base, but others can

### ISSUE THREAD

**Issue by MerryPanda** [FAForever/fa#3071]
With SACU resource providers, other races can live without a base, but Seraphims can't, as they won't have resources.

It looks like Seraphims are base-dependent, but actually have no robust defense and their shields are merely slightly better than other's.

In order to compensate, their shields should be buffed as their defense capabilities with a new T3 turret. May be a T3 Stealth Field Generator should be granted as well.

What do you think?

**Comment by shalkya** [comment]
what is a Students-generators again?

**Comment by MerryPanda** [comment]
> 
> 
> what is a Students-generators again?

hi, i meant SACU with resource providing upgrade :D

**Comment by shalkya** [comment]
https://github.com/FAForever/fa/pull/2866
you can close if this solves your issue
