### ISSUE TITLE
Suggestion: Factories Attack Command

### ISSUE THREAD

**Issue by MrRowey** [FAForever/fa#3081]
I feel that this could be a nice add-on to the Factory's. The Button in the Ui is already there, but being able to have this button actually work will give new Plays the ability to attack move engineers more easily if they are unaware of the Hotkey combination. This would a small change that could have a positive impact on what the factory's can do.

**Comment by Garanas** [comment]
The current functionality of the attack button on a factory is that any unit that spawns from that factory will have the same attack command. E.g., change it to 'ground attack' or to 'no attack' and all units that spawn from that moment on wards will have their attack command set as such. 

I agree that it would be nice to have the engineer 'feature' more clearly marked as an option somehow, but I don't think this is the way to do it.
