### ISSUE TITLE
Suggestion: Upgradable Engineers

### ISSUE THREAD

**Issue by MerryPanda** [FAForever/fa#3082]
Let's make Engineers upgradable in order to get rid of useless units. It will perfectly work with  #2791

**Comment by Rowey121** [comment]
Idea's Like this can been simple bee made in to mod if you want this ahvign Engies upgrabble is kinda pointless for the amout of time it take to jsut build one.

**Comment by MerryPanda** [comment]
> 
> 
> Idea's Like this can been simple bee made in to mod if you want this ahvign Engies upgrabble is kinda pointless for the amout of time it take to jsut build one.

it should be costly... the only alternative is to CTR+K them right now...

**Comment by MrRowey** [comment]
@Tagada14 this can be closed as i don't see this being added at any point
