### ISSUE TITLE
Suggestion: Share Paragon output with teammates

### ISSUE THREAD

**Issue by MerryPanda** [FAForever/fa#3084]
Hello, me and a friend who preferred to stay incognito, would like to propose that diplomacy window had a toggle to turn on sharing Paragon outcome among teammates.

So if outcome is shared, all teammates acquire equal part.

For example, if you have 4 team members and Paragon provides you with 10k mass and 100k energy, every team member gets 2.5k mass and 25k energy.

It is useful because there is a tendency to transfer all production facilities to a Paragon owner, which is not very convenient.

Thanks. What do you think?

**Comment by KionX** [comment]
The balance team will not agree to this change.
I can do this as a mod, if you need integration, then you know who to write to=)

**Comment by MerryPanda** [comment]
> 
> 
> The balance team will not agree to this change.
> I can do this as a mod, if you need integration, then you know who to write=)

hello, why is the team against, it sounds logical? :D

**Comment by KionX** [comment]
A premonition based on experience)

**Comment by MerryPanda** [comment]
> 
> 
> A premonition based on experience)

But they transfer their factories to a Paragon owner, what's the difference? :)

**Comment by HellFAF** [comment]
Just gift your mass and energy generation units to the team or ask them to give you engineers / engineering towers to assist builds.

**Comment by MrRowey** [comment]
@Tagada14 can this be closed if you don't see this being added by balance team
