### ISSUE TITLE
Add hotkey to Select same units on screen (as opposite to entire map which is already implemented)

### ISSUE THREAD

**Issue by Arkemlar** [FAForever/fa#3088]
There are hotkeys for selecting same units on entire map, or select air/land/naval only units, but there are no hotkey for selecting same units (as in selection set) on screen (visible part of the map). This feature is common for RTS games and SCFA definitely needs it.

**Comment by RecklessCharger** [comment]
See https://forums.faforever.com/viewtopic.php?f=40&t=8230&hilit=Custom+keys
You need to use the +in view tag
Alternatively double left click will select all units of same type on screen

**Comment by MrRowey** [comment]
@Garanas thoughts ?

**Comment by Arkemlar** [comment]
@RecklessCharger Double click is not good when your units moving. And also not good when one wants to improve APM because hotkeys are faster.
