### ISSUE TITLE
Bug: Bigger Strategic Build Icons Not Displaying Correctly

### ISSUE THREAD

**Issue by MrRowey** [FAForever/fa#3090]
So i was trying to look in to Issuse  #2888 as it is still open for to then notice when i switch to teh Bigger icons & Bigger icons with TechMarker they seem to get Verry small to teh point were they are not evern readable. i am running a 2560 x 1440p display but this should still work if im correct ?
i am running my UI at 100% if this help too.

Bigger Icons with TechMarker
![image](https://user-images.githubusercontent.com/20344151/80845605-a76cc200-8c01-11ea-8872-a86e6e8701c6.png)

Bigger Icons
![image](https://user-images.githubusercontent.com/20344151/80845756-1cd89280-8c02-11ea-97a8-b2d22a6720f8.png)

Default Icons
![image](https://user-images.githubusercontent.com/20344151/80845818-5a3d2000-8c02-11ea-9b22-27d484e98954.png)

**Comment by shalkya** [comment]
fixed by #3065
