### ISSUE TITLE
Suggestion: Vote for karma

### ISSUE THREAD

**Issue by burner-** [FAForever/fa#3092]
Rating is nice way to know something about player skills. Some times it would be good if users can give up&down votes for team mates after game. This probably improve team play. One way to do that is that each player get 1  point of game by default if they do not disconnect before they die or suicide commander (is this possible to check automatically from replay data?). Each member at team can give 1 negative or positive point after game at vault for each team member. If it is possible to get lot of information from replay data maybe there can have automatic penalisation for wery shitty moves like suiciding commander so that teammate lost lot of mass. I have seen too many times when someone lost hope of winning they run their commander to another base at own team and blow it up.

**Comment by shalkya** [comment]
you would make this like-meter impact rating or be a 2nd evaluation measure to gauge someone ability to play in a team ?

**Comment by burner-** [comment]
2nd evaluation. I think it mesh up too many things if we touch to rating system. 
Also at implementation pahse its probably safer to implement it firs as private value so that we will see all issues what it brigs before people start kick players from lobby because of karma :) But I like to see at future that host can set minumum karma to game. How to do that so that it will not cause too much problems for noobs who are not done any good or bad is good question.

**Comment by KionX** [comment]
I'm against it. This is too slippery a path.

**Comment by burner-** [comment]
I see risks. But another hand current situation is that there is lot of players who do dirty tricks like left middle of game, explode own commander in own team base, flood with markers so long that others leave, alt+tab out from game and put computer do something heavy so that others cannot play neither. So we need some kind way to ged rid of that kind players. That why I also suggest that default +1 points from each game. So basically 5 neutral games will still allow to make nasty things at one 5 player game without losting to much karma. But it will cut of those players who mostly cause problems.

**Comment by MrRowey** [comment]
@Garanas i can see this just being abused too much to recommend that we just close this
