### ISSUE TITLE
wreck half built unit

### ISSUE THREAD

**Issue by shalkya** [FAForever/fa#3095]
after 50% completion, a building will leave a wreck if you ctrl k it. If it get killed while being built, the unit will automatically rebuild it.

But there is several issues :
1st : if there is no one constructing the building, then when it get kill it won't leave any wreck.
2nd : if a unit rebuild on top of a wreck of an unfinished building, whatever the amount of mass left in the wreck you will rebuild it at 50% (if you didn't reclaim part of the wreck)

Expected behaviour : 
1st : it should spawn a wreck
2nd : the new building, should be at 50% of the completion state of the old building. If the wreck took damage, the new building completion state should be lowered proportionally, the same way it works when you rebuild on a half reclaimed wreck.

**Comment by Farmsletje** [comment]
One of the worst bugs currently in the game i'd say. Can spawn 100k mass out of thin air after you snipe a 50% complete mavor and they instantly rebuild it on 50%.

**Comment by shalkya** [comment]
well to be accurate you only create 56k mass from thin air. Since you should start rebuilding the mavor at 25% already (not 0%).

**Comment by shalkya** [comment]
only partially fixed, we still need someone to be building the structure while it get killed to create the wreck

**Comment by MrRowey** [comment]
closing this issues balance team decided that factory and experimental need to be completed and not leave mass behind if not
