### ISSUE TITLE
All units except buildings randomly die

### ISSUE THREAD

**Issue by jkstpierre** [FAForever/fa#3097]
During games sometimes all my units except for buildings randomly die as if I ctrl+k'd them. Needless to say, I never press ctrl+k any of the times this happens.

**Comment by shalkya** [comment]
can you give a replay to watch ?

**Comment by jkstpierre** [comment]
Sure, it happened in my most recent game (I am SkepticSpecter in the match).

Replay ID is 11679327

**Comment by jkstpierre** [comment]
It happens near the 20 minute mark

**Comment by shalkya** [comment]
i'm curious, does it happen that you press ctrl-l to select all land unit ?

**Comment by jkstpierre** [comment]
Hmm, it’s possible. I do use that shortcut a lot, maybe my finger slips and hits the k right after I hit the ctrl+l

**Comment by jkstpierre** [comment]
I definitely don’t ctrl+l and then ctrl+k that’s for sure

**Comment by shalkya** [comment]
well i already saw people killing all their land units by mistake because these 2 hotkeys are nearby. "cheat" weren't on, so there is high chances, that's what happened.

**Comment by speed2CZ** [comment]
Just change it to ctrl D, that way you have it right next to air units A, naval units S
and accidents wont happen
