### ISSUE TITLE
Wreck hitbox

### ISSUE THREAD

**Issue by shalkya** [FAForever/fa#3101]
![image](https://user-images.githubusercontent.com/11618427/81501771-5da76a00-92da-11ea-9b2b-d2f8975e25d6.png)
Once of the most obvious issue is with the GC. The hitbox doesn't change its position after the GC fall down.

**Comment by Garanas** [comment]
I'd like to investigate this further but cannot find the console command to show those bounding boxes. What console commander did you use for it?

**Comment by shalkya** [comment]
if you use the default preset for hotkey it's ctrl-shift-alt-C (Toggle collision debug info).

**Comment by Garanas** [comment]
Well, I would've never found that. Thank you for sharing!

I think I solved it:
[image]<a href="https://ibb.co/kqxNDs9"><img src="https://i.ibb.co/HGV5Pfx/collision-fix-screenshot.png" alt="collision-fix-screenshot" border="0"></a>[!image]

In the death thread of the unit the collision box needs to be adjusted! I'll make a pull request, any other units that needs these kind of fixes? I can think of the Seraphin t2 Assault Bot from the top of my head.

**Comment by shalkya** [comment]
nicely done, you changed it in the unit script ?
i think it would be better to change the main death thread, so it applies for all units. So we don't change 1 by 1 the script for all relevant units.

**Comment by Garanas** [comment]
I changed this in the unit script, see also: https://github.com/FAForever/fa/pull/3139

That being said, I don't know how to dynamically compute the bounding box of a unit. I tweaked this bounding box manually until it fit right in, can we access the mesh (vertex) information somehow?

Lets continue the discussion in the pull request :).
