### ISSUE TITLE
Problems with smoke and omni

### ISSUE THREAD

**Issue by KionX** [FAForever/fa#3104]
![Problem](https://user-images.githubusercontent.com/5648030/81506061-4cc41c00-930d-11ea-9158-835de3d30df5.png)
Firebeetle and spiders work on firewood?

**Comment by shalkya** [comment]
![image](https://user-images.githubusercontent.com/11618427/81506610-db2da300-92f7-11ea-89e7-1480b95d6645.png)
smoke is intended to be possible to spot them visualy
here you can see beetle and cloak scu in range of omni and still not visible.
The omni ring is too big. when you enter the gun range, the omni works.

**Comment by KionX** [comment]
```smoke is intended to be possible to spot them visualy``` Ok.
I found that detection problems from engine.
