### ISSUE TITLE
Incorrect Description for UEF T3 Mass Fabricator Power Consumption & Yield

### ISSUE THREAD

**Issue by ugandarowanda** [FAForever/fa#3110]
The description for the UEF T3 Mass Fabricator says it consumes 3,500 energy per second. However, its Yield says -1,500 energy per second.

These should be aligned, so that the description says it consumes 1,500 energy per second.

Image is uploaded.

![image](https://user-images.githubusercontent.com/65465038/82131793-ea946c80-978d-11ea-80a1-078f9ba7dac5.png)

**Comment by ugandarowanda** [comment]
I submitted Pull Request #3111 to fix this issue for all T3 Mass Fabs and an additional minor typo I found along the way. I intended to put that on the /faf/develop branch. If that didn't work out as I planned please let me know.
https://github.com/FAForever/fa/pull/3111

**Comment by MrRowey** [comment]
@Garanas Can be Closed #3111 was Merged
