### ISSUE TITLE
Lower mass of ras on SACU

### ISSUE THREAD

**Issue by geojak** [FAForever/fa#3121]
HI, I would like to suggest a balance change. Lower the mass output of sacu ras to something like +3 and increase the energy output to offset the nerf by a reasonable amount. 

Currently in the rating range I play at nobody goes for mass fabricators like ever. The meta I see is going mass sacu with ras since they are mobile, easier defensible, have a gun, produce energy instead of using it, can build, take much less space... Generally just so much more convenient that going for the maybe more mass efficient fabs is not worth it.

**Comment by shalkya** [comment]
a rework of the ras has already been made : https://github.com/FAForever/fa/pull/2866
