### ISSUE TITLE
KyrO’s Lobby mod friendly Ru localization

### ISSUE THREAD

**Issue by Kazbek** [FAForever/fa#3123]
When using KyrO’s Lobby mod in Russian, the player’s move command(and AI too) does not fit into the drop-down lists (the slot number is not visible, as shown in the screenshot).
![image](https://user-images.githubusercontent.com/15718432/83982173-14742580-a92d-11ea-8969-af10dc8762e0.png)

Can we someshow change https://github.com/FAForever/fa/blob/develop/loc/RU/strings_db.lua#L8405
`lobui_0596="Переместить игрока в слот %s"`
to
`lobui_0596="Переместить в %s слот"`

And https://github.com/FAForever/fa/blob/develop/loc/RU/strings_db.lua#L8416
`lobui_0607="Переместить ИИ в слот %s"`
to
`lobui_0607="Переместить в %s слот"`

From the point of view of the Russian language, these phrases are correct.

At the beginning of the file, something is said about auto-generation. Therefore, I do not know exactly where it is necessary to change this.

**Comment by zwei-und-vierzig** [comment]
Yep, it is not correct translation.
