### ISSUE TITLE
SMD adjacency bonus

### ISSUE THREAD

**Issue by betacentauri** [FAForever/fa#3126]
When you first build a SMD and then T1 PGens around it, then it still consumes 1500 power. So no adjacency bonus.
When you first build 4 T1 PG and then the SMD, the SMD consumes 1312 power. When you then destroy the PGens, the SMD still consumes 1312 and not 1500 power.
Replay: https://content.faforever.com/faf/vault/replay_vault/replay.php?id=12041372

**Comment by shalkya** [comment]
duplicate : https://github.com/FAForever/fa/issues/1843

**Comment by betacentauri** [comment]
Ok, thanks for the info and good to know.
