### ISSUE TITLE
Air units refuse to target unidentified upgraded structures

### ISSUE THREAD

**Issue by andrew-vant** [FAForever/fa#3128]
Air units refuse to target unidentified (grey blip) upgraded structures. They still fire if in range. In most cases anything in range becomes identified (via vision), but there's a few edge cases, e.g. torpedo bombers flying over underwater mass extractors.

We reproduced the problem with mexes and factories as targets, and bombers, torp bombers, and gunships as attackers. Land and naval units appear unaffected.

**Versions**:

* Patch: 3714
* Game type: FAF
* Map: Adaptive Adrastea

**Reproduction**:

1. (Player 1): Build an upgradable structure.
2. (Player 2): Build a radar station or sonar buoy in range of the structure. The structure should appear as a grey map blip.
3. (Player 1): Upgrade the structure.
3. (Player 2): Build an air unit, select it, and right-click the structure on radar.

**Expected behavior**: The attacker should go kill the target.

**Actual behavior**: A targeting line appears momentarily, then disappears. The unit either doesn't start an attack run, or gives up immediately.

**Comment by Garanas** [comment]
Does any other dev know where to start looking for this issue? I'd be happy to investigate it, but as of writing have no idea where to start.

**Comment by shalkya** [comment]
I didn't look thoroughly but I think this topics should help you understand the issue : 
https://github.com/FAForever/fa/issues/1245
https://github.com/FAForever/fa/pull/1248
https://github.com/FAForever/fa/commit/fa764a2c4ff7aeab3d76741240f209a89a93f8bb
https://github.com/FAForever/fa/commit/f7ac782a6825d53ebac51494a946e42ac1a65ef4
