### ISSUE TITLE
vision radius bug

### ISSUE THREAD

**Issue by shalkya** [FAForever/fa#3129]
![image](https://user-images.githubusercontent.com/11618427/85956067-494f2780-b983-11ea-8f5d-4fb867b12e86.png)
![image](https://user-images.githubusercontent.com/11618427/85956069-4eac7200-b983-11ea-9915-a24cdacada08.png)

one unit can see the other one, while the other can't see the first one.

related ? : https://github.com/FAForever/fa/issues/1389
this wasn't link to intel refresh though, since the unit wasn't able to see the other one consistently (ie even after 5 sec)

**Comment by MrRowey** [comment]
@Garanas close as it this is engine related and unfixable ?

**Comment by Garanas** [comment]
Not closing it yet - I think this is related to why stealth fields have an offset. I would not be surprised if vision has a similar offset.

**Comment by MrRowey** [comment]
chaning the offset didnt seem to do much on my end last time I look but could be wrong

**Comment by Garanas** [comment]
I know - but I want to link the issues first / find where that discussion was.

**Comment by Garanas** [comment]
This issue is niche and usually not relevant during a game. Intel (visually) doesn't appear to be updating at the same frequency / timestamps, not sure how that works internally.
