### ISSUE TITLE
Toggle selected unit info hotkey does not work

### ISSUE THREAD

**Issue by JaggedAppliance** [FAForever/fa#3130]
This hotkey is supposed to bring up a window with many of that selected units statistics and attributes but the hotkey does not bring up the window. This stopped working at least some months ago although I'm not sure when exactly, I thought it was a problem on my end at the time. 

This was a very useful hotkey for testing, the window could even be used to adjust some unit stats on the fly.
After a very quick search this commit may have something to do with:
https://github.com/FAForever/fa/commit/b083eb747a05137c5906d0d93acd4d9d608f21f1#diff-829695f54b302bf2ee839f3f65246ff2

**Comment by MrRowey** [comment]
@JaggedAppliance is this functionality still desired ?

**Comment by Garanas** [comment]
I think he's referring to the entity dialog. It was patched so that you need cheats to be enabled, beyond that it works as usual

![image](https://user-images.githubusercontent.com/15778155/217783661-156a9440-a955-41f1-a348-c8b43a8e466f.png)
