### ISSUE TITLE
Check Ping in Lobby

### ISSUE THREAD

**Issue by TobiasJacob** [FAForever/fa#3132]
Too many supcom games have to get rehosted because there is a single high-ping player. There should be a possibility to check the ping of each player in the lobby before the game starts.

**Comment by shalkya** [comment]
the ping is displayed only if it is over 500 ms

**Comment by TobiasJacob** [comment]
In my opinion, we should always display the ping. Then people can decide by themselves how high the ping is they tolerate.

**Comment by speed2CZ** [comment]
Yeah we had that and aussies with 400 ping got kicked all the time. Thats why it's hidden

**Comment by TobiasJacob** [comment]
But it's impossible to have a nice game experience with players that have 400 ping, or isn't it? For all, even for those with bad ping. If the game launches and get's rehosted because of lag, they didn't profit of it. It's just very frustrating for everybody.

I don't know if ping is a reliable measurement for the lag, but if not, we should try to come up with one.

**Comment by speed2CZ** [comment]
There's 500ms built in delay to all commands, so only anything above that lags the game. Or packet loss but you won't find that out from ping.

**Comment by TobiasJacob** [comment]
So what about simulating some of the network traffic of a typical game in the lobby and calculating a measurement of how much a person causes lag to the game? This measurement could include a mixture of ping, packet loss, and maybe some more features. I am new to the faf dev community, so I don't know how to do this exactly but I think the idea is not bad

**Comment by speed2CZ** [comment]
No is against some better tests. But FAF never lacked good idea, just man power. I dont know how to do that either. There even might be an issue for that already. If it's not, you can create a new one.
But Im closing this one as displaying ping is fine as it is right now.

**Comment by Kazbek** [comment]
@TobiasJacob I can help you. Please PM me in discord Kazbek#9427

**Comment by RobertAcksel** [comment]
Is there at least a load test which simulates the net load of the count of players in the lobby?
I think this should be possible besides the cpu test. Probably there should be a bar which also shows the network health and capabilities. like cpu test kinda does.
Pls point us to the code location which may/does contain all this.
