### ISSUE TITLE
Wrong tooltip for Selen stealth

### ISSUE THREAD

**Issue by micheljung** [FAForever/fa#3133]
![image](https://user-images.githubusercontent.com/1864183/87234518-f12c1280-c3d1-11ea-9755-6587ba532c6a.png)

**Comment by JaggedAppliance** [comment]
This tooltip is accurate. The button does toggle the selection priority of the selen preventing it from being selected with other units. It doesn't turn on stealth, that only happens when the selen is stationary and not firing.
