### ISSUE TITLE
Stinger Cannot Prioritize ACU

### ISSUE THREAD

**Issue by ThomasHiatt1** [FAForever/fa#3141]
The Stinger cannot prioritize the ACU with snipemode because it lacks the SNIPEMODE category. It is the only gunship which lacks this category.

**Comment by shalkya** [comment]
already fixed in https://github.com/FAForever/fa/pull/3072/commits/24fd0c8e4c6af1196a5a8e5542cb782c8ee2e5a7#diff-1613ac87235a7379e0f84f667c5bc5b1
