### ISSUE TITLE
cheat menu sorting unit by product

### ISSUE THREAD

**Issue by shalkya** [FAForever/fa#3149]
Some units aren't in any of the product category, eg : guided missile (mercy)

available product category right now : 
SC
SC-FA
Mods
Operation
Civilian

if you type in search "guided  missile" and select any of the product category you won't be able to spawn it (doesn't appear)

**Comment by KionX** [comment]
The product category is defined by the first letter of the blueprint name.

**Comment by Garanas** [comment]
Closed, after the overhaul of Balthazar this issue has aged.
