### ISSUE TITLE
Issues from E8400-CV Game.log

### ISSUE THREAD

**Issue by aeoncleanse** [FAForever/fa#315]
warning: Error running OnRelease script in <deleted object>: ...orever\gamedata\lua.nx2\lua\ui\game\construction.lua(1137): Game object has been destroyed
         stack traceback:
         	[C]: in function `SetAlpha'
         	...orever\gamedata\lua.nx2\lua\ui\game\construction.lua(1137): in function `OnRolloverEvent'
         	...d alliance\gamedata\mohodata.scd\lua\maui\button.lua(131): in function <...d alliance\gamedata\mohodata.scd\lua\maui\button.lua:122>
            
warning: Error running OnPaused script in Entity urb0103 at 290a3208: ...\gamedata\units.scd\units\urb0103\urb0103_script.lua(37): attempt to call method `SetGoal' (a nil value)
         stack traceback:
         	...\gamedata\units.scd\units\urb0103\urb0103_script.lua(37): in function `StopArmsMoving'
         	...mdata\faforever\gamedata\lua.nx2\lua\cybranunits.lua(253): in function <...mdata\faforever\gamedata\lua.nx2\lua\cybranunits.lua:251>

**Comment by aeoncleanse** [comment]
Some of the causes of these may have been fixed in the hotfix, I was watching Murdoch and not keeping up ^^

**Comment by Sheeo** [comment]
I think we need to be able to reproduce these errors before we can do anything about them.
