### ISSUE TITLE
Seraphim T3 MAA Lightning Tank Shoots Through Shields

### ISSUE THREAD

**Issue by ThomasHiatt1** [FAForever/fa#3153]
Like the title says, the Seraphim T3 MAA "Uyanah" Lightning Tank shoots land units through shields unimpeded. I'm pretty sure this is unintended and is quite overpowered. It was reported by BlackKiwi89 on the FAF discord and I verified it myself by testing in a sandbox game.

**Comment by MrRowey** [comment]
@Garanas this is still an issue, just did some testing the shield bubble is taking from what looks to be about 5% of the damage and the rest is let through the shield to its intended target and just zap it. Also, notice while I had the log open every times it fired it spams this warning in the log

![image](https://user-images.githubusercontent.com/20344151/145051021-f8e39977-29f7-4f2d-aa0c-8d8afde4f13a.png)

**Comment by Garanas** [comment]
Good find - I'll see if I can fix this before the 20th.

**Comment by MrRowey** [comment]
Tested on Update version of FAF Develop -  Waring dose not show :) but still kills units though shield

**Comment by Garanas** [comment]
I found out why this happens - they hacked in how the damage works. Because of that it bypasses any logic, in fact you can make it do double damage (damage an intermediate target and the target you're aiming for).
