### ISSUE TITLE
direct-fire projectiles going through t1 pd when at certain angles and only if there's a wall behind the pd

### ISSUE THREAD

**Issue by ghost** [FAForever/fa#3156]
Title says it all, specific example is a civilian cybran t1 pd on saltrock colony at the northwest part of the center civilian base. Direct-fire projectiles go right through the turret and hit the wall behind it at certain angles. If the wall behind the turret is destroyed, then the turret can be damaged from angles where it previously couldn't be. This only happens when there is a wall behind the turret, relative to a direct-fire unit's position, when that unit is at that 'weird spot', meaning the turret can be hit if the d-f unit is at a wider angle and if at that new wide angle, there is no wall behind the turret relative to the d-f unit's position. Remember that this is only at CERTAIN ANGLES, so a d-f unit can still hit a turret if the unit is not at some 'weird spot' angle where the projectile goes through the turret. No I didn't test t1 static aa. This apparently has been patched according to https://github.com/FAForever/fa/blob/develop/changelog.md, at Patch 3641 (July 12, 2015) in the physics section.
This is not only for saltrock colony, this happens in-game on probably? every map. The pd on Saltrock is just one example.
location of specific pd on saltrock colony*
![aaaloc](https://user-images.githubusercontent.com/49421634/90305238-5792cd80-de75-11ea-850a-6848ec032bdd.png)
example of acu shot going through*
![aaaexa](https://user-images.githubusercontent.com/49421634/90305249-7002e800-de75-11ea-899e-348c3e92b894.png)
example of acu shot hitting when walls behind are destroyed*
![aaaexa2](https://user-images.githubusercontent.com/49421634/90305257-8d37b680-de75-11ea-9841-18cc5c123809.png)
example of acu shot hitting when at a different angle where no wall is behind pd relative to acu*
![aaadiff2](https://user-images.githubusercontent.com/49421634/90305268-bd7f5500-de75-11ea-9ab4-3abf00ce93db.png)
example of pillar shot hitting when not at a 'weird spot' angle*
![aaadiff](https://user-images.githubusercontent.com/49421634/90305274-d6880600-de75-11ea-8223-6fcbe937ec9a.png)

**Comment by MrRowey** [comment]
#3415 @Garanas i assume this is fixed with that PR| ?

**Comment by Garanas** [comment]
Fixed is a big word - the behavior is now the same for all factions. Leaving this one open.

**Comment by Tagada14** [comment]
The only way to fix it would be to make the hitbox even bigger and that would also make T1 PD's very unbalanced

**Comment by Garanas** [comment]
Closing this issue - changes are not desirable. It is also an engine bug.
