### ISSUE TITLE
All games are unrated since automatic installation of newest FA patch

### ISSUE THREAD

**Issue by jkstpierre** [FAForever/fa#3165]
I played 2 dual gaps today (Replay IDs #12630755 and #12629071) after installing the latest FA version through Downlord's client that should have been rated (no mods, no unit restrictions or settings changes except for 1500 unit cap and left vs. right auto teams). Supreme scoreboard in game says the games should be rated but looking at the replays in the vault, the FAF client says both matches were unranked and no one lost or gained any rating points. Not sure if this is a bug with FA or Downlord's client but its not just me that this bug is happening to.

**Comment by relent0r** [comment]
I'm seeing errors in relation to the scoring on game start.
```
warning: Error running lua script: ...ramdata\faforever\gamedata\lua.nx2\lua\sim\score.lua(262): bad argument #1 to `insert' (table expected, got nil)
         stack traceback:
         	[C]: in function `insert'
         	...ramdata\faforever\gamedata\lua.nx2\lua\sim\score.lua(262): in function <...ramdata\faforever\gamedata\lua.nx2\lua\sim\score.lua:259>
```

**Comment by Draiget** [comment]
Have the same with games #12619316, #12626515, #12628111, #12640662 but no error in game logs.

**Comment by Askaholic** [comment]
@shalkya I think this can be closed
