### ISSUE TITLE
DeSync after new Update

### ISSUE THREAD

**Issue by SageTheWizard** [FAForever/fa#3167]
After new update, desync is very common

**Comment by CTOverton** [comment]
agreed

**Comment by RobertAcksel** [comment]
at least seen 2 times after v3718 in one week

**Comment by shalkya** [comment]
i will keep monitoring if people are getting more desync.

**Comment by Garanas** [comment]
I think this issue has aged and it no longer happens, or we would've heard about it. Closing it - if it still happens frequently then make a new issue.
