### ISSUE TITLE
Vision markers are broken

### ISSUE THREAD

**Issue by speed2CZ** [FAForever/fa#3172]
This commit broke it https://github.com/FAForever/fa/commit/ca16b123abb89655ff0f38a63ed1c1607d623654

Especially this part: `if self.WaterVision != false then` and  `if self.WaterVision then` are not the same thing (well all those ifs that got changed.)
The original code created all the visions unless it was specifid not to. New code creates only visions if they are specified.

This breaks all visions markers in all coop missions and I dare to say even some more, since it's significant change of how the vision markers work.

Please revert this change and just keep the optimization of how the Eye works. Thanks in advance!

**Comment by Garanas** [comment]
Also breaks the vision markers in Rainmakers!

**Comment by shalkya** [comment]
Thanks, last time i tried a mission, i coudn't see opponent unit during the cinematic, is it related ?
I will try to push a patch faster than previous one, to alleviate these issue.

**Comment by speed2CZ** [comment]
Yes, that's exactly this issue

**Comment by KionX** [comment]
You can reverse it. I'll fix it.
