### ISSUE TITLE
This line is wrong... pretty sure

### ISSUE THREAD

**Issue by 1-alex98** [FAForever/fa#3176]
https://github.com/FAForever/fa/blob/c03958dacbec35e92ee7050a3c21314ed687c632/lua/ui/dialogs/score.lua#L566

This if won't works because the client copies the currently executed init file into the init.lua and does not keep the _ladder postfix. I am not sure if that "if" not working has negative consequences but it should definitely be deleted.

**Comment by axel1200** [comment]
GetCommandLineArg('/init', 1)[1] will in 100% of cases return "init.lua"

**Comment by speed2CZ** [comment]
When did this got changed?

**Comment by axel1200** [comment]
Java client always had this behavior

**Comment by MrRowey** [comment]
@Garanas idk what to make of this just know you were talking in zulip about the init files :)

**Comment by Garanas** [comment]
This is not part of the init file though. It is wrong - but I'm not sure if we want it to work.

**Comment by Garanas** [comment]
Closing this issue - it has aged. Everything works as intended at the moment.

**Comment by 1-alex98** [comment]
https://github.com/FAForever/fa/blob/c03958dacbec35e92ee7050a3c21314ed687c632/lua/ui/dialogs/score.lua#L566
just makes the code more complex
