### ISSUE TITLE
Some Cybran and UEF Air facs still have slow roll off 

### ISSUE THREAD

**Issue by Yolo-11** [FAForever/fa#3183]
In some recent patch Cybran and UEF air fac roll off times were drastically shortened. However that only applies to the T1 and UEF T2 facs, as you can see in the short video:
[https://www.youtube.com/watch?v=KMgne_ZFP14&feature=youtu.be](https://www.youtube.com/watch?v=KMgne_ZFP14&feature=youtu.be])

Air facs that still have slow roll off time:
Cybran T2 + T3 Air fac & HQ
UEF T3 Air fac & HQ

**Comment by MrRowey** [comment]
@Garanas Merged PR fixed this in a recent update
