### ISSUE TITLE
increase performance of ReverseString, StringJoin (and possibly other functions in this util file)

### ISSUE THREAD

**Issue by Divran** [FAForever/fa#3185]
This issue is related to my pull request here https://github.com/FAForever/fa/pull/3184

I'm not sure which version of Lua added `string.reverse` and which version of Lua is being used in FAF, so I wasn't sure if I could change this. It's possible `string.reverse` has always been in Lua since the beginning, I wasn't able to find that out after some quick googling.

So, what we could do is change this:
```
function StringReverse(str)
    local tbl =  {}
    str:gsub(".",function(c) table.insert(tbl,c) end)
    tbl = table.reverse(tbl)
    return table.concat(tbl)
end
```

... into this:

```
StringReverse = string.reverse
```
Since this is the first time I make pull requests to FAF I'm also not sure what the proper way to test things in this game/engine is.
For this reason, created an issue about it instead of including it in my PR.

If a developer finds this you can either make this super simple change yourself, or let me know and I can include it in my PR linked above.

**Comment by Divran** [comment]
We can also change `StringJoin` from the following
```
function StringJoin(items, delimiter)
    local str = "";
    for k,v in items do
        str = str .. v .. delimiter
    end
    return str
end
```

into this
```
StringJoin = table.concat
```

however, these will behave slightly differently, since `StringJoin` will append the delimiter to the end of the string as well, whereas `table.concat` will not. For this reason, this was also not included in my PR. Other than that, using `table.concat` will be quite literally millions of times faster. The reason for this is that concatenating strings is a very expensive operation in lua.

**Comment by Divran** [comment]
I'd also like to leave a mention here to this implementation of `string.Explode` <https://github.com/Facepunch/garrysmod/blob/master/garrysmod/lua/includes/extensions/string.lua#L80>
which has been worked on by myself and others in the gmod community. This current implementation of the explode function is by far the fastest one we've able to come up with.

Here are some quick comparisons.
Test code used:
```
local amount = 10000
local s = ("this is a very long test string"):rep(100000)

local t = os.clock()
for i=1,amount do
    string.Explode(s," ")
end
print("string.Explode over " .. #s .. " character long string, with " .. #string.Explode(" ",s) .. " separations and " .. amount .. " iterations",(os.clock()-t) ..  " seconds")

local t = os.clock()
amount = 1
for i=1,amount do
    StringSplit(s," ")
end
print("StringSplit over " .. #s .. " character long string, with " .. #StringSplit(s," ") .. " separations and " .. amount .. " iterations",(os.clock()-t) ..  " seconds")
```
Test results:
```
string.Explode over 3100000 character long string, with 600001 separations and 10000 iterations	0.093 seconds
StringSplit over 3100000 character long string, with 600001 separations and 1 iterations	0.325 seconds
```
As you can see, gmod's explode function does 10k iterations over thirty times faster than your current explode function can do a single iteration.

**Comment by Divran** [comment]
FA is my favorite RTS of all time, and I suspect that the reason the game suffers from many slowdowns (especially versus AIs) is due to the combination of all of these very inefficient (and other mildly inefficient) functions, that seem harmless alone, but cause some serious performance hits together. I would love if time could be spent improving the performance of code such as this to the point where we can play against 8 cheating AIs at +0 rather than -10. I'm not sure if I will have the time to do this, though.

**Comment by falk-stefan** [comment]
Good catch! :) I am currently trying to find out how we could potentially profile the SC-LUA code. If you have some ideas just join the discussion if you want: https://github.com/FAForever/fa/issues/3188

**Comment by KionX** [comment]
Version of Lua is being used in FAF is 5.1
But under the hood something between 5.0 and 5.1

**Comment by KionX** [comment]
Fast search by:
https://github.com/FAForever/fa/search?q=StringReverse
https://github.com/FAForever/fa/search?q=StringJoin
gives the result 2 and 2. Nothing important.

**Comment by HUSSAR-mtrela** [comment]
@KionX FA game is using Lua version 5.0.1 and it differs in a few important ways as we discovered one example in PR #3184
Namely, the ^ operator is not the same as math.pow() function. Also, there are more differences like that so it is a mistake to   use Lua 5.1 API/docs as reference for developing improvements in FA game.

@Divran, you should follow this guide for setting up DEV init file and running the game against your changes:
https://github.com/FAForever/fa#running-the-game-with-your-changes
https://github.com/FAForever/fa#setting-up-a-development-init-file

**Comment by HUSSAR-mtrela** [comment]
@Divran you will discover when running FA game from source, that you will not going to have access to any of OS functions (e.g. os.clock) and you will need to use custom FA functions, e.g. CurrentTime() or use CreateTimer() https://github.com/FAForever/fa/blob/develop/lua/system/utils.lua#L648

**Comment by Divran** [comment]
Next time I have time available to run some tests for this project I will be sure to read up on those guides.

**Comment by Garanas** [comment]
Closing this issue - it has dated.
