### ISSUE TITLE
Death weapon being fired for unfinished T4

### ISSUE THREAD

**Issue by satoraresatohi** [FAForever/fa#3191]
https://youtu.be/rnP5oKz-Xo4
If you good at hotkeys, you can place 3-4 experementals near a enemy commander land or underwater doesn't matter, then ctrl+k them to cause fast damage, each unit deal 4k dmg, Thats means you can made tele saku and just snipe any unit/build for few seconds w/o spent any resource
(Tested on GC, ML,  Megalith, Ythotha all of them deal wreck damage)

**Comment by MrRowey** [comment]
@Garanas can be closed ? with pr merged

**Comment by satoraresatohi** [comment]
I guess yes, if you already fixed it. Thanks! @Garanas
