### ISSUE TITLE
possible incorrect usage of the ^ operator

### ISSUE THREAD

**Issue by Divran** [FAForever/fa#3199]
It was brought to our attention in the PR here https://github.com/FAForever/fa/pull/3184/files#r519483132 that the `^` operator in FAF is actually not the same as `math.pow`. It's probably an `XOR` operator (or similar). That said, I took a few minutes to glance through the code and found these occurrences of the operator which look suspect. They might need to be replaced with `math.pow`, but I'm not entirely familiar with the source code, so they could be using the operator intentionally. I've given my thoughts on how likely it is to be incorrect below.

Unsure about this one, but should be looked at since it's in the simulator.
<https://github.com/FAForever/fa/blob/develop/lua/sim/defaultweapons.lua#L643>

100% likely to be incorrect. Not important, it's in the UI section, but should be fixed eventually.
<https://github.com/FAForever/fa/blob/develop/lua/ui/lobby/lobby.lua#L5253>

Definitely wrong. Anything using this function will be given incorrect values. Should be fixed asap. Luckily, I checked and nothing uses this function at the moment.
<https://github.com/FAForever/fa/blob/develop/lua/utilities.lua#L114>

In addition to these three, there's also the four additional occurrences of `math.round` as discussed in the linked pull request.

**Comment by speed2CZ** [comment]
1. is used only by Scathis
2. is in the CPU test, so no harm at all I guess
3. As you say, unused

**Comment by KionX** [comment]
LUA documentation
https://www.lua.org/manual/5.1/manual.html#2.5.1

**Comment by Divran** [comment]
@KionX Our tests in the linked pull request confirms that the `^` operator present in FAF's version of Lua is not the exponent operator.

**Comment by Garanas** [comment]
Closing this issue, the fix has been applied by Divran in #3184.
