### ISSUE TITLE
Score data does not record income rate without reclaim rate

### ISSUE THREAD

**Issue by HUSSAR-mtrela** [FAForever/fa#3202]
Current Behavior:

1. In replay session, the mass income rate fluctuate wildly in score data because FAF does not exclude reclaim rate from income rate like it did [before](https://github.com/FAForever/fa/commit/dd0a1fae63e86584b7db1442ac9d244e70d60bc1?branch=dd0a1fae63e86584b7db1442ac9d244e70d60bc1&diff=split#diff-b0fdd58b5f454c1e0e9f0bd5f12208ba3ccb2803cf78c94297d259a54e0e8418L230). This is a regression issue because previous behavior was implemented on many requests from FA casters (including Gyle). As result of this issue, it is difficult to compare players eco while watching replays because income stats fluctuate wildly while some players are reclaiming and other do not.

2. Also, now storing reclaim values is happening on [separate thread](https://github.com/FAForever/fa/blob/deploy/fafdevelop/lua/sim/score.lua#L47) at 1 second interval while rest of eco stats are recorded at [different interval](https://github.com/FAForever/fa/blob/deploy/fafdevelop/lua/sim/score.lua#L155). As result, it is difficult to even create a UI mod (e.g. SupremeScoreBoard) that could adjust income rate by subtracting reclaim rate.

3. Lastly, the Economy UI (left side) shows small difference between total income (60) and sum of reclaim rate (50) and mass in rate (11) which is 61 and it displayed in score UI (right side).

Expected Behavior:
1. Exclude reclaim rate from income rate in score data OR add a new field in score data that will have reclaim rate excluded from income rate
2. Store reclaim rate and income rate at the same interval 
3. Correct total income in Economy UI by rounding up the sum of reclaim rate (50) and mass income rate (11) 

![image](https://user-images.githubusercontent.com/11665978/99198153-bf063500-2764-11eb-9fc8-e771cb0267dc.png)

**Comment by Sheikah45** [comment]
This can be closed I believe as #3242 was merged

**Comment by Garanas** [comment]
Closed on demand, good spot.
