### ISSUE TITLE
Game crashing: EXCEPTION_ACCESS_VIOLATION (0xc0000005) at address 0x024ade58

### ISSUE THREAD

**Issue by drewswinney** [FAForever/fa#3206]
I have played 3 games now (total newbie) and every single one crashes around the 10 min mark. The game was a 1v1 with a friend. Checking the logs, I can't see anything specific enough to see why it is crashing.

Below is the error log for the last crash I had:

> EXCEPTION_ACCESS_VIOLATION (0xc0000005) at address 0x024ade58
>     attempted to read memory at 0x5f5ef079
> 
> Program : C:\ProgramData\FAForever\bin\ForgedAlliance.exe
> Cmd line arguments : /init init.lua /nobugreport /log C:\ProgramData\FAForever\logs\game_13142561.log /gpgnet 127.0.0.1:6065 /mean 1500.0 /deviation 500.0 /savereplay gpgnet://127.0.0.1:49919/13142561/funkyartichoke.SCFAreplay /country US /numgames 0
> 
> Callstack:
> 	Unknown symbol (address 0x024ade58)
> 	Unknown symbol (address 0x0249e001)
> 	BaseThreadInitThunk + 20 bytes ((Unknown)(0) + 0 bytes)
> 	RtlGetAppContainerNamedObjectPath + 223 bytes ((Unknown)(0) + 0 bytes)
> 	RtlGetAppContainerNamedObjectPath + 175 bytes ((Unknown)(0) + 0 bytes)
> 
> Last 100 lines of log...
> 
> debug: Loading module '\000/lua/keymap/keycategories.lua\000'
> info: UI_Lua import("/lua/ui/uimain.lua").EscapeHandler()
> info: UI_Lua import("/lua/ui/uimain.lua").EscapeHandler()
> info: UI_Lua import("/lua/ui/uimain.lua").EscapeHandler()
> debug: Loading module '\000/lua/ui/dialogs/options.lua\000'
> debug: Loading module '\000/lua/ui/menus/menucommon.lua\000'
> debug: Loading module '\000/lua/options/options.lua\000'
> debug: Loading module '\000/textures/ui/common/dialogs/options-02/options-02_layout.lua\000'
> debug: Current gametime: 00:00:30
> debug: Loading module '\000/units/url0105/url0105_script.lua\000'
> debug: Loading module '\000/units/urb1101/urb1101_script.lua\000'
> info: SC_SecondaryAdapter false
> info: Minimized true
> debug: Loading module '\000/units/urb1103/urb1103_script.lua\000'
> warning: GetResource: Invalid name ""
> info: Can't find texture "" -- trying fallback.
> warning: GetResource: Invalid name ""
> info: Can't find texture "" -- trying fallback.
> warning: GetResource: Invalid name ""
> info: Can't find texture "" -- trying fallback.
> info: Minimized false
> info: Minimized true
> debug: Current gametime: 00:01:00
> warning: GetResource: Invalid name ""
> info: Can't find texture "" -- trying fallback.
> warning: GetResource: Invalid name ""
> info: Can't find texture "" -- trying fallback.
> warning: GetResource: Invalid name ""
> info: Can't find texture "" -- trying fallback.
> info: Minimized false
> debug: Loading module '\000/lua/spreadattack.lua\000'
> debug: Loading module '\000/units/urb1102/urb1102_script.lua\000'
> debug: Loading module '\000/lua/ui/game/commandgraphparams.lua\000'
> debug: Loading module '\000/lua/ui/game/commandwaypoint.lua\000'
> debug: Loading module '\000/lua/ui/game/commandgraph.lua\000'
> info: Hooked /lua/ui/game/commandgraph.lua with /schook/lua/ui/game/commandgraph.lua
> debug: Loading module '\000/units/ueb1103/ueb1103_script.lua\000'
> debug: Loading module '\000/effects/entities/uefbuildeffect/uefbuildeffect02_script.lua\000'
> debug: Loading module '\000/effects/entities/uefbuild/uefbuild01_script.lua\000'
> debug: Loading module '\000/effects/entities/uefbuildeffect/uefbuildeffect03_script.lua\000'
> debug: Current gametime: 00:01:30
> debug: Loading module '\000/units/url0107/url0107_script.lua\000'
> debug: Loading module '\000/units/ueb0101/ueb0101_script.lua\000'
> debug: Current gametime: 00:02:00
> debug: Loading module '\000/units/uel0105/uel0105_script.lua\000'
> debug: Loading module '\000/lua/formations.lua\000'
> debug: Loading module '\000/units/urb0102/urb0102_script.lua\000'
> debug: Current gametime: 00:02:30
> debug: Loading module '\000/units/url0103/url0103_script.lua\000'
> debug: Loading module '\000/units/ura0101/ura0101_script.lua\000'
> debug: Current gametime: 00:03:00
> debug: Loading module '\000/units/urb1202/urb1202_script.lua\000'
> debug: Current gametime: 00:03:30
> debug: Loading module '\000/units/ueb1102/ueb1102_script.lua\000'
> debug: Loading module '\000/units/ueb0102/ueb0102_script.lua\000'
> debug: Current gametime: 00:04:00
> debug: Loading module '\000/lua/simcallbacks.lua\000'
> debug: Loading module '\000/lua/simping.lua\000'
> debug: Loading module '\000/lua/selfdestruct.lua\000'
> debug: Loading module '\000/lua/simcameramarkers.lua\000'
> debug: Loading module '\000/lua/simdialogue.lua\000'
> debug: Loading module '\000/lua/simdiplomacy.lua\000'
> debug: Loading module '\000/lua/spreadattack.lua\000'
> debug: Loading module '\000/lua/weaponpriorities.lua\000'
> debug: Loading module '\000/units/urb1106/urb1106_script.lua\000'
> debug: Current gametime: 00:04:30
> debug: Loading module '\000/units/uea0101/uea0101_script.lua\000'
> debug: Loading module '\000/projectiles/taarailgun01/taarailgun01_script.lua\000'
> debug: Loading module '\000/lua/terranprojectiles.lua\000'
> debug: Loading module '\000/projectiles/shieldcollider/shieldcollider_script.lua\000'
> debug: Loading module '\000/effects/entities/debrismisc09/debrismisc09_script.lua\000'
> debug: Loading module '\000/lua/genericdebris.lua\000'
> debug: Current gametime: 00:05:00
> debug: Current gametime: 00:05:30
> debug: Loading module '\000/units/urb2104/urb2104_script.lua\000'
> debug: Current gametime: 00:06:00
> debug: Loading module '\000/units/urb3101/urb3101_script.lua\000'
> debug: Current gametime: 00:06:30
> debug: Loading module '\000/units/ueb1106/ueb1106_script.lua\000'
> debug: Current gametime: 00:07:00
> debug: Loading module '\000/units/urb0103/urb0103_script.lua\000'
> debug: Loading module '\000/units/uel0201/uel0201_script.lua\000'
> debug: Current gametime: 00:07:30
> debug: Current gametime: 00:08:00
> debug: Loading module '\000/units/urb0201/urb0201_script.lua\000'
> debug: Loading module '\000/units/uel0103/uel0103_script.lua\000'
> debug: Current gametime: 00:08:30
> debug: Loading module '\000/projectiles/cdflaserheavy01/cdflaserheavy01_script.lua\000'
> debug: Loading module '\000/lua/cybranprojectiles.lua\000'
> debug: Loading module '\000/projectiles/cifgrenade01/cifgrenade01_script.lua\000'
> debug: Loading module '\000/effects/entities/debrismisc04/debrismisc04_script.lua\000'
> debug: Current gametime: 00:09:00
> debug: Loading module '\000/units/urs0203/urs0203_script.lua\000'
> debug: Current gametime: 00:09:30
> debug: Current gametime: 00:10:00
> debug: Loading module '\000/units/urs0103/urs0103_script.lua\000'
> debug: Loading module '\000/units/url0208/url0208_script.lua\000'
> debug: Current gametime: 00:10:30
> debug: Loading module '\000/units/urb2101/urb2101_script.lua\000'
> debug: Current gametime: 00:11:00

**Comment by Sheeo** [comment]
For these, it's important you report exactly what settings and mods you're using so others can try to replicate.

In addition, are you using the steam version of the game and have you modified the base game files in any way?

**Comment by drewswinney** [comment]
Sure thing, apologies. So my friend had set up the game and only had the UI mod on.

I am using the steam version of the game and have _not_ modified any of the base game files in any way.

**Comment by drewswinney** [comment]
I also had another crash, this time with the following error log. Same setup as before, though I hosted the game this time.

`EXCEPTION_ACCESS_VIOLATION (0xc0000005) at address 0x0257de58
    attempted to read memory at 0x5f5ef079

Program : C:\ProgramData\FAForever\bin\ForgedAlliance.exe
Cmd line arguments : /init init.lua /nobugreport /log C:\ProgramData\FAForever\logs\game_13158205.log /gpgnet 127.0.0.1:6967 /mean 1243.25 /deviation 408.945 /savereplay gpgnet://127.0.0.1:60917/13158205/funkyartichoke.SCFAreplay /country US /numgames 1

Callstack:
	Unknown symbol (address 0x0257de58)
	Unknown symbol (address 0x0256e001)
	BaseThreadInitThunk + 20 bytes ((Unknown)(0) + 0 bytes)
	RtlGetAppContainerNamedObjectPath + 223 bytes ((Unknown)(0) + 0 bytes)
	RtlGetAppContainerNamedObjectPath + 175 bytes ((Unknown)(0) + 0 bytes)

Last 100 lines of log...

debug: Loading module '\000/lua/simdiplomacy.lua\000'
debug: Loading module '\000/lua/spreadattack.lua\000'
debug: Loading module '\000/lua/weaponpriorities.lua\000'
debug: Current gametime: 00:02:00
debug: Loading module '\000/units/ueb1102/ueb1102_script.lua\000'
debug: Current gametime: 00:02:30
debug: Current gametime: 00:03:00
debug: Loading module '\000/units/uab0101/uab0101_script.lua\000'
info: UI_Lua import("/lua/ui/uimain.lua").EscapeHandler()
info: UI_Lua import("/lua/ui/uimain.lua").EscapeHandler()
debug: Current gametime: 00:03:30
debug: Loading module '\000/units/ual0201/ual0201_script.lua\000'
debug: Loading module '\000/units/uab0103/uab0103_script.lua\000'
debug: Current gametime: 00:04:00
debug: Loading module '\000/lua/ui/lobby/restrictedunitsdata.lua\000'
debug: Loading module '\000/lua/sim/tasks/enhancetask.lua\000'
debug: Loading module '\000/lua/sim/scripttask.lua\000'
debug: Current gametime: 00:04:30
debug: Loading module '\000/units/uas0103/uas0103_script.lua\000'
debug: Loading module '\000/units/ual0104/ual0104_script.lua\000'
debug: Loading module '\000/units/ual0103/ual0103_script.lua\000'
debug: Current gametime: 00:05:00
debug: Current gametime: 00:05:30
debug: Loading module '\000/units/uab0202/uab0202_script.lua\000'
debug: Loading module '\000/units/ueb1105/ueb1105_script.lua\000'
debug: Current gametime: 00:06:00
debug: Loading module '\000/units/uab2101/uab2101_script.lua\000'
debug: Loading module '\000/projectiles/adfquantumcannon01/adfquantumcannon01_script.lua\000'
debug: Loading module '\000/lua/aeonprojectiles.lua\000'
debug: Loading module '\000/effects/entities/debrismisc09/debrismisc09_script.lua\000'
debug: Loading module '\000/lua/genericdebris.lua\000'
debug: Current gametime: 00:06:30
debug: Current gametime: 00:07:00
debug: Current gametime: 00:07:30
info: UI_Lua import("/lua/ui/uimain.lua").EscapeHandler()
debug: Loading module '\000/units/ueb1202/ueb1202_script.lua\000'
debug: Current gametime: 00:08:00
debug: Loading module '\000/units/uab1202/uab1202_script.lua\000'
debug: Loading module '\000/units/uab2104/uab2104_script.lua\000'
debug: Current gametime: 00:08:30
debug: Loading module '\000/units/ueb2204/ueb2204_script.lua\000'
debug: Loading module '\000/units/uab3101/uab3101_script.lua\000'
debug: Loading module '\000/units/ual0208/ual0208_script.lua\000'
debug: Loading module '\000/units/ueb0102/ueb0102_script.lua\000'
debug: Current gametime: 00:09:00
debug: Loading module '\000/units/uas0102/uas0102_script.lua\000'
debug: Loading module '\000/units/ueb1201/ueb1201_script.lua\000'
debug: Loading module '\000/units/uab1106/uab1106_script.lua\000'
debug: Current gametime: 00:09:30
debug: Current gametime: 00:10:00
debug: Loading module '\000/units/xeb0104/xeb0104_script.lua\000'
debug: Current gametime: 00:10:30
debug: Loading module '\000/units/xea3204/xea3204_script.lua\000'
debug: Current gametime: 00:11:00
debug: Loading module '\000/projectiles/adfdisruptor01/adfdisruptor01_script.lua\000'
debug: Loading module '\000/projectiles/aifmortar01/aifmortar01_script.lua\000'
debug: Loading module '\000/effects/entities/debrismisc04/debrismisc04_script.lua\000'
debug: Loading module '\000/units/ueb0201/ueb0201_script.lua\000'
debug: Loading module '\000/units/ueb0202/ueb0202_script.lua\000'
debug: Current gametime: 00:11:30
debug: Current gametime: 00:12:00
debug: Loading module '\000/units/daa0206/daa0206_script.lua\000'
debug: Loading module '\000/units/uel0208/uel0208_script.lua\000'
debug: Current gametime: 00:12:30
debug: Current gametime: 00:13:00
debug: Loading module '\000/units/dea0202/dea0202_script.lua\000'
debug: Current gametime: 00:13:30
info: UI_Lua import("/lua/ui/uimain.lua").EscapeHandler()
info: UI_Lua import("/lua/ui/uimain.lua").EscapeHandler()
debug: Loading module '\000/units/ueb1104/ueb1104_script.lua\000'
debug: Current gametime: 00:14:00
debug: Loading module '\000/units/ueb4201/ueb4201_script.lua\000'
debug: Current gametime: 00:14:30
debug: Loading module '\000/units/uab1201/uab1201_script.lua\000'
debug: Current gametime: 00:15:00
debug: Loading module '\000/units/uaa0101/uaa0101_script.lua\000'
debug: Loading module '\000/units/uel0307/uel0307_script.lua\000'
debug: Current gametime: 00:15:30
debug: Loading module '\000/projectiles/taalightfragmentationshell01/taalightfragmentationshell01_script.lua\000'
debug: Loading module '\000/lua/terranprojectiles.lua\000'
debug: Loading module '\000/projectiles/shieldcollider/shieldcollider_script.lua\000'
debug: Loading module '\000/projectiles/taarailgun03/taarailgun03_script.lua\000'
debug: Loading module '\000/projectiles/sinker/sinker_script.lua\000'
debug: Current gametime: 00:16:00
debug: Loading module '\000/units/uab0203/uab0203_script.lua\000'
debug: Loading module '\000/projectiles/taarailgun01/taarailgun01_script.lua\000'
debug: Loading module '\000/projectiles/tifnapalmcarpetbomb02/tifnapalmcarpetbomb02_script.lua\000'
debug: [uiutil.lua, function UIFile()] - Unable to find file:/textures/ui/uef/icons/units/unknown_icon.dds
debug: Current gametime: 00:16:30
debug: Loading module '\000/projectiles/aifguidedmissile01/aifguidedmissile01_script.lua\000'
debug: Loading module '\000/projectiles/aifguidedmissile02/aifguidedmissile02_script.lua\000'
debug: Loading module '\000/projectiles/aaasonicpulse01/aaasonicpulse01_script.lua\000'
debug: Current gametime: 00:17:00
debug: Current gametime: 00:17:30
debug: Loading module '\000/units/uab1302/uab1302_script.lua\000'
debug: Loading module '\000/units/uea0104/uea0104_script.lua\000'
debug: Current gametime: 00:18:00
debug: Current gametime: 00:18:30
debug: Current gametime: 00:19:00
debug: Loading module '\000/units/xaa0202/xaa0202_script.lua\000'
`

**Comment by Sheeo** [comment]
> only had the UI mod on.

Which particular UI mod, and do you have it as well?

**Comment by drewswinney** [comment]
Apologies again. Both my friend and I are new to FAF and it seems we misread the UI, thinking the “UI” button meant that a mod called “UI” was enabled. In any case, it seems then that we had a vanilla game running in all cases... no mods of any kind (that I can tell... again I am new to this game)

**Comment by KionX** [comment]
The address 0x024ade58 does not exist.
The replays does not show the problem.
