### ISSUE TITLE
Warning SafeQuit

### ISSUE THREAD

**Issue by Xinnony** [FAForever/fa#321]
Not cause a crash but warning in the log :

debug: Loading module '\000/lua/maui/slider.lua\000'
debug: Loading module '\000/lua/ui/dialogs/eschandler.lua\000'
debug: Loading module '\000/lua/system/utils.lua\000'
warning: Problem Don't panic.:
warning: no active session.
warning: stack traceback:
warning:         [C]: in function `SessionEndGame'
warning:         [C]: in function `pcall'
warning:         ...data\faforever\gamedata\lua.nx2\lua\system\utils.lua(30): in function `safecall'
warning:         ...ch3638-texturepack.nxt\lua\ui\dialogs\eschandler.lua(25): in function `SafeQuit'
warning:         ...ch3638-texturepack.nxt\lua\ui\dialogs\eschandler.lua(39): in function <...ch3638-texturepack.nxt\lua\ui\dialogs\eschandler.lua:39>
warning:         ...gamedata\patch3638-texturepack.nxt\lua\ui\uiutil.lua(770): in function `OnClick'
warning:         ...d alliance\gamedata\mohodata.scd\lua\maui\button.lua(133): in function <...d alliance\gamedata\mohodata.scd\lua\maui\button.lua:122>
warning: Problem Don't panic.:
warning: attempt to yield across metamethod/C-call boundary
warning: stack traceback:
warning:         [C]: in function `WaitFrames'
warning:         ...gramdata\faforever\gamedata\lua.nx2\lua\userinit.lua(17): in function `WaitSeconds'
warning:         [C]: in function `pcall'
warning:         ...data\faforever\gamedata\lua.nx2\lua\system\utils.lua(30): in function `safecall'
warning:         ...ch3638-texturepack.nxt\lua\ui\dialogs\eschandler.lua(26): in function `SafeQuit'
warning:         ...ch3638-texturepack.nxt\lua\ui\dialogs\eschandler.lua(39): in function <...ch3638-texturepack.nxt\lua\ui\dialogs\eschandler.lua:39>
warning:         ...gamedata\patch3638-texturepack.nxt\lua\ui\uiutil.lua(770): in function `OnClick'
warning:         ...d alliance\gamedata\mohodata.scd\lua\maui\button.lua(133): in function <...d alliance\gamedata\mohodata.scd\lua\maui\button.lua:122>

**Comment by Sheeo** [comment]
Indeed this is a warning introduced with #248.

**Comment by ChrisKitching** [comment]
Harmless and expected when quitting when not in a game.

Finding a way to muffle this might be nice, but do we really care? We'd
have to reimplement safecall.

**Comment by Sheeo** [comment]
Actually, since ExitGame is called just before the pcalls, I do believe SessionEndGame will always complain about there being no session.

**Comment by ChrisKitching** [comment]
I think I observed the opposite in testing. Try quitting from in a game.
