### ISSUE TITLE
Salem-class is not amphibious

### ISSUE THREAD

**Issue by zeno-desaqqara** [FAForever/fa#3212]
**Describe the bug**
In the base FAF game, Cybran Salem-class destroyers are aquatic instead of amphibious despite having the amphibious icon-background and being described as amphibious in the tooltip.

**To Reproduce**
Begin a game of FAF, attempt to build Cybran T2 destroyer

**Log or error message**
N/A

**Expected behavior**
Cybran T2 Salem-class destroyer should have the amphibious tag instead of the aquatic tag. Should be able to walk on land.

**Screenshots**
N/A

**OS**
Windows

**Wanna have the bug fixed quickly?**
Visit Issue hunt...
[![Issue hunt](https://github.com/BoostIO/issuehunt-materials/raw/master/v1/issuehunt-button-v1.svg?sanitize=true)](https://issuehunt.io/r/FAForever/downlords-faf-client)

**Comment by speed2CZ** [comment]
From the Salem BP:
`Icon = 'amph',`
` Abilities = {
            '<LOC ability_amphibious>Amphibious',`
idk what you mean by aquatic. It is amphibious and it can walk on land, there's toggle button you have to press. Else it prefers to stay in the water.

**Comment by FtXCommando** [comment]
By aquatic he means it cannot go on land. Probably unaware that the ability is toggled off initially and can be turned on.

**Comment by zeno-desaqqara** [comment]
Ah, that would do it. Thanks!
