### ISSUE TITLE
Remove ability for kyros lobby to show spawn location when preview hidden

### ISSUE THREAD

**Issue by Sheikah45** [FAForever/fa#3228]

**Comment by speed2CZ** [comment]
I dont think you can do that, UI can always get to that information.

**Comment by Sheikah45** [comment]
Yes the UI can if someone really wants to mod it do that. This issue is more just that an unintended effect was that as kyros lobby makes its own slots it still played the animation So I guess this is probably more making the blind preview compatible with kyros
