### ISSUE TITLE
Shield/tmd not working on missile deflected by loya

### ISSUE THREAD

**Issue by Farmsletje** [FAForever/fa#3233]
See https://replay.faforever.com/13334887

When a loya deflects an enemy missile it can't be stopped by anything. It completely ignores shields and it gets completely ignored by tmd. 

This issue has existed for as long as i can remember. Not sure if it was deemed unfixable or the right people didn't know about it so i thought i could atleast try and make an issue about it.

**Comment by JaggedAppliance** [comment]
Might be #FixedinEQ

**Comment by speed2CZ** [comment]
So you can integrate yet another part of EQ

**Comment by Garanas** [comment]
This seems more like a feature then an issue. We'd need to replace the projectile to make this work. What does the balance team want?

**Comment by Tagada14** [comment]
We would like the missiles to be stopped by the TMD. Not a high priority but nice to have.

**Comment by MrRowey** [comment]
Fixed with #5790
