### ISSUE TITLE
OC overlay issues

### ISSUE THREAD

**Issue by shalkya** [FAForever/fa#3238]
OC indicator doesn't take into account the personal shield when calculating if there is enough energy to kill the unit.
![untitled](https://user-images.githubusercontent.com/11618427/103173717-1831b000-485d-11eb-8f4e-253ea7d5ff0f.png)

**Comment by shalkya** [comment]
another issue :
overlay is green with 1 e storage when targetting ilshy, even if you need 2 e storages, 1 full e storage leave ilshy on 475 hp.

**Comment by Garanas** [comment]
It is not possible to include the shield ratio. The information is gathered via updating the unit window, which doesn't provide the shield status for hostile units. See also:

```
INFO:  - armyIndex: 1
INFO:  - blueprintId: ual0202
INFO:  - energyConsumed: -1
INFO:  - energyProduced: -1
INFO:  - energyRequested: 0
INFO:  - fuelRatio: -1
INFO:  - health: 1250
INFO:  - kills: 0
INFO:  - massConsumed: -1
INFO:  - massProduced: -1
INFO:  - massRequested: 0
INFO:  - maxHealth: 1250
INFO:  - nukeSiloBuildCount: 0
INFO:  - nukeSiloMaxStorageCount: 0
INFO:  - nukeSiloStorageCount: 0
INFO:  - shieldRatio: -1
INFO:  - tacticalSiloBuildCount: 0
INFO:  - tacticalSiloMaxStorageCount: 0
INFO:  - tacticalSiloStorageCount: 0
INFO:  - teamColor: ffdeb887
INFO:  - workProgress: -1
```

Note that the shieldRatio is set to `-1` , indicating that the value is not available.
