### ISSUE TITLE
Matchmaker & Unit Cap

### ISSUE THREAD

**Issue by FtXCommando** [FAForever/fa#3244]
It will be necessary to implement a few things involving the unit cap for the matchmaker to function a bit better.

The primary one is that we will need to have shared unit cap enabled so that full share can actually, well, function. This will be more and more important as the team sizes increase on the matchmaker. Can't imagine a sentons without it. 

The second one is that we should just push the unit cap max per player to 1500 rather than 1000. It's mainly for the same reason, no real reason not to do it and I'm getting people whining about it every week. 

Also I'm supposed to link this to the TMM project but don't see that available anywhere here.

**Comment by KionX** [comment]
I suggest making unit cap max per player unlimited.
And the income from t2, t3 mex cut in half.

**Comment by MrRowey** [comment]
@Garanas change have been merged
