### ISSUE TITLE
Mod experimental transports unbuildable

### ISSUE THREAD

**Issue by The-Balthazar** [FAForever/fa#3252]
https://github.com/FAForever/fa/blob/f8233b01be4311bfe155361355a798ad28852dc0/lua/ui/game/unitviewDetail.lua#L367

This function makes it impossible for players to build experimental transports added by mods, since it errors the UI when you hover over them.

What would be better is if it pulled from a specifically defined value in the blueprint, or said nothing about the capacity rather than guesstimating.

**Comment by The-Balthazar** [comment]
https://github.com/FAForever/fa/pull/3248

**Comment by KionX** [comment]
`specifically defined value in the blueprint`
I didn't find it. Where is he?

**Comment by The-Balthazar** [comment]
> I didn't find it. Where is it?
It was a suggestion to add a value to the blueprints. One doesn't currently exist, but given that in vanilla it only applies to 9 units, it wouldn't be a lot of work to add.

**Comment by The-Balthazar** [comment]
Having it work, as with the PR I linked to, is the bare minimum that should be expected, but having the numbers shown actually be accurate and definable would be better.

**Comment by KionX** [comment]
At the moment, there are no good ways.
I'll do it as soon as I find a way.

**Comment by The-Balthazar** [comment]
I've wrote up a suggested implementation here: https://github.com/FAForever/fa/pull/3248#issuecomment-770349974

**Comment by Divran** [comment]
A related bug to this is the fact that this function here
https://github.com/FAForever/fa/blob/f8233b01be4311bfe155361355a798ad28852dc0/lua/ui/game/unitviewDetail.lua#L413
breaks the aeon t3 transport which is added by blackops, because this transport has a teleport ability but does not have the value called `bp.General.TeleportDelay` which causes an error due to inserting a nil value into `string.format`

**Comment by speed2CZ** [comment]
They should all have some fallback text so a missing value in the bp doesnt break the UI

**Comment by Divran** [comment]
Yep either that, or, if such a thing is possible in faf, define default values for all the values that these functions expect in the lowermost baseclass which all weapons inherit from.

**Comment by KionX** [comment]
Fixed https://github.com/FAForever/fa/pull/3248

**Comment by Divran** [comment]
@KionX From a glance at that pull request, it doesn't look like this fixes the related issue where aeon t3 teleporting transports suffer a similar error. If it does in fact fix it, then ignore this message.
Although arguably that could be considered a different error, in which case it'd warrant a different github issue thread.

**Comment by KionX** [comment]
This is already fixed in the mod.
