### ISSUE TITLE
Disable autoaim for manual fire commands (TML/SML launch)

### ISSUE THREAD

**Issue by Arkemlar** [FAForever/fa#3256]
Speaking about manual launch of tml/nukes autoaim to closest target like unit or wreck makes no sense and even annoying.

Sometimes when unit (tml, ACU with tml, nuke sub) will fire immediately (when weapon is loaded and target is in range) you have no chance to do usual trick by putting attack point on random free area and move it to desired place with shift drag.

In my case I had TML ACU and I planned to fire tml in the route of enemy ACU, but there are transport wreck close to desired point and it autoaimed to that transport wreck.

So tml/sml launch commands should not aim to units or whrecks, because it makes no sense - wreck are easy target for manual targeting, units usually moving so no reason to fire on moving unit.

**Comment by MrRowey** [comment]
Closing this Issue as is a Duplicate for what is being discussed here #3563
