### ISSUE TITLE
Player in lobby slot and listed as observer simultaneously

### ISSUE THREAD

**Issue by Xinnony** [FAForever/fa#326]
http://i.imgur.com/dLzpsd4.png
Color problem

**Comment by Sheeo** [comment]
What exactly is the problem with colours here?

I see another issue in that screenhost, relating to the state of the UI, where there is an observer who is also in a slot.

**Comment by Xinnony** [comment]
Yes i not see before create this issue the player is Observer and Slot too.

**Comment by Sheeo** [comment]
But what is the problem with colour?

**Comment by Xinnony** [comment]
Is not the color i thinks, the player "Cannabidiol" is Grey and is in slot and observer.

**Comment by Sheeo** [comment]
Thank you. I've renamed the issue appropriately.

**Comment by Xinnony** [comment]
Yes is better :)
