### ISSUE TITLE
in-game Cougar (UEF T3 MAA) says aquatic but it's not

### ISSUE THREAD

**Issue by FemtoZetta** [FAForever/fa#3260]
see title
In-game info needs to be fixed.
![grafik](https://user-images.githubusercontent.com/61892809/109952062-540e4900-7cd6-11eb-9792-db33ab3fd5d7.png)
unit blueprint relevant part:
![grafik](https://user-images.githubusercontent.com/61892809/109953551-1dd1c900-7cd8-11eb-9ce1-c686cf948f8a.png)

**Comment by Garanas** [comment]
This issue is solved by #3276 and has been merged.
