### ISSUE TITLE
Factories (HQ/support) not translated

### ISSUE THREAD

**Issue by mminguez** [FAForever/fa#3264]
I realised that support factories and HQ are not translated in any languages others than CN RU and US.

https://github.com/FAForever/fa/blob/f8233b01be4311bfe155361355a798ad28852dc0/loc/US/strings_db.lua#L1555

As i'm french it would be nice to make it works for other languges than thoses 3. Or make a contributing program for the in game translation as it is for the client.  

Thanks!

**Comment by furyritchie** [comment]
Is it possible that you would be able to provide French translations for a number of the the items in this file?

https://github.com/FAForever/fa/blob/deploy/fafdevelop/loc/FR/strings_db.lua#L7498

Keep in mind the HQ factories are the current factories and we would need new entries for the support factories based on the ID available in the English file.

**Comment by MrRowey** [comment]
@mminguez if you provide me with the translation I can do that :)

**Comment by MrRowey** [comment]
can be reopen if translation provided
