### ISSUE TITLE
Add option to scale LOD

### ISSUE THREAD

**Issue by speed2CZ** [FAForever/fa#3274]
With the UI scaling there also needs to be an option to scale LOD of units, props, everything as you get much more to see with higher resolution, but the models still switch to low poly version even when they are still very visible.
The same applies to the level when they should switch to strategic icon.

Best way to do this is inside Blueprints.lua and modify all units before the bps are registered in the engine. These values are desync safe as they dont affect simulation (tested).

It could use the same value as the UI scaling, but new one would be prolly better.

**Comment by Uveso** [comment]
Its secret but i did a LOD calculator in Black Ops mod:
https://github.com/Uveso/BlackOpsFAF-Unleashed/blob/master/hook/lua/system/Blueprints.lua#L129

Maybe this can be the base of whatever we want to make.

**Comment by KionX** [comment]
Calculating LODCutoff by unit size is good. But should not remove LOD-1.
An alternative is to multiply LODCutoff by 2 for all LODs directly in BPs.

**Comment by Uveso** [comment]
@KionX 

I tested several options to see whats faster / not crashing.

I have done a mod before i implemented this into Black ops:
[AdvancedLOD-v1.zip](https://github.com/FAForever/fa/files/6656281/AdvancedLOD-v1.zip)

you can set the option in Blueprints.lua line 20

`local LODoptions = 1`

-- LODoptions:
-- 0 diabled
-- 1 low / Units will be hide by size if zoomed out. Using High and Low resolution textures and models
-- 2 high / Units hide by size and ony use highres textures and models.
-- 3 full / Units will never hide, and only use highres textures and models.

**Comment by KionX** [comment]
I did what I could. The best I've got:
```
    for _, bp in all_bps.Prop do
        if bp.Display.Mesh.LODs then
            local LODCutoff = math.max(bp.SizeX, bp.SizeZ) * 1000
            local LODs = table.getsize(bp.Display.Mesh.LODs)
            for k, v in bp.Display.Mesh.LODs do
                v.LODCutoff = LODCutoff / math.pow(2, LODs - k)
            end
        end
    end
    for _, bp in all_bps.Unit do
        if bp.Display.Mesh.LODs then
            local LODCutoff = math.max(bp.SizeX, bp.SizeZ) * 200
            local LODs = table.getsize(bp.Display.Mesh.LODs)
            for k, v in bp.Display.Mesh.LODs do
                v.LODCutoff = LODCutoff / math.pow(2, LODs - k)
            end
        end
    end
```
Place at the end of PostModBlueprints.

Also tried "cam_Set LOD WorldCamera 0.x" (less value - more details).

Test it. For best results, I recommend manual editing of the BPs.

**Comment by Garanas** [comment]
The LOD can be extended with the game options by enabling the 'Extended graphics' or 'Experimental graphics' depending on the game patch that you run. We also dynamically compute the LOD size of units now. For the last one, see also:

- https://github.com/FAForever/fa/issues/4675
