### ISSUE TITLE
Pd doesn't retarget and stays idle.

### ISSUE THREAD

**Issue by Auriko** [FAForever/fa#3278]
Game ID 14359316 around min 11.

The pd shoots at some engies (shots are blocked by terrain), some auroras get into range, then come out of range, which causes the pd to stop shooting. Instead of retargetting the engies, it stays idle. 

![pd](https://user-images.githubusercontent.com/64992608/115855209-4ac67080-a42b-11eb-8a1d-9c1c6ed4f929.png)

**Comment by Garanas** [comment]
I looked into this and it appears to be engine-related. There is also this topic on the forums indicating that it doesn't have to do with just engineers:
 - https://forum.faforever.com/topic/2282/fervors-zthuees-and-pds-can-t-shoot-down-hills-lobos-and-medusas-can

**Comment by MrRowey** [comment]
@Garanas cloed with egnine tag
