### ISSUE TITLE
Probably wrong function call which causing wrong spot info sending to server on lobby start.

### ISSUE THREAD

**Issue by Kazbek** [FAForever/fa#3280]
In lobby.lua when if teamSpawn == 'balanced_flex' or teamSpawn == 'balanced_flex_reveal'
https://github.com/FAForever/fa/blob/fa7b14270db1f202f0524722f4a0ea80da91f750/lua/ui/lobby/lobby.lua#L1628
But previously invoking like this
https://github.com/FAForever/fa/blob/fa7b14270db1f202f0524722f4a0ea80da91f750/lua/ui/lobby/lobby.lua#L1585
And in this function data sending due to "data" field.
https://github.com/FAForever/fa/blob/fa7b14270db1f202f0524722f4a0ea80da91f750/lua/ui/lobby/lobby.lua#L1493-L1502
May be invoking it like `rearrangePlayers{setup=best}` or `rearrangePlayers{setup=best, quality=someFakeOrSomeCalculatedQuality}` may resolve problem described [here](https://github.com/FAForever/faf-java-api/issues/462).

**Comment by zlo-faf** [comment]
isn't that something that was added to prevent mods like "reveal position" from knowing where did player spawn?

**Comment by Kazbek** [comment]
Since anyone can modify and use kyrro lobby mod (and make any own logic) for lobby, I guess this is not that place where preventing come from.

**Comment by Garanas** [comment]
Closing this issue - it is dated.

**Comment by Kazbek** [comment]
Is this fixed?

**Comment by Garanas** [comment]
I think ZLO is right - this was done intentionally to prevent UI mods from being able to determine the spawn locations.

**Comment by Kazbek** [comment]
So even in _reveal type of the game?
And why optimal send correct data to the server?
