### ISSUE TITLE
Crashes with balance patch 3720?

### ISSUE THREAD

**Issue by AbominableIntelligence** [FAForever/fa#3287]
Hai,

Ever since the latest balance patch, I've been experiencing regular crashes. I've also heard others complain about crashes, or lag.

I'm wary of blaming the patch, but it's the only thing that's changed.

Any ideas?
LMM

**Comment by Petricpwnz** [comment]
Can you post game logs? In the client click top left menu -> show log folder and upload the game log from the crashed game.

**Comment by AbominableIntelligence** [comment]
The log file is 10mb in size...

[game_14523138.log](https://github.com/FAForever/fa/files/6489588/game_14523138.log)

**Comment by KionX** [comment]
It looks like mods are breaking the game's UI.

**Comment by AbominableIntelligence** [comment]
This is the online replay: https://replay.faforever.com/14520892

I've attached my local replay.
[14520892-LittleMissMurder.zip](https://github.com/FAForever/fa/files/6489906/14520892-LittleMissMurder.zip)

**Comment by AbominableIntelligence** [comment]
Wait a second. I think I uploaded the wrong log file (doh)

[game_14520892.log](https://github.com/FAForever/fa/files/6489939/game_14520892.log)

**Comment by KionX** [comment]
Judging by the log, the crash occurred after the end of the game.
I checked the replay without mods. There was no crash.
So I guess it's not a FAF problem.
