### ISSUE TITLE
STR_Utf8SubString missmeaning

### ISSUE THREAD

**Issue by 4z0t** [FAForever/fa#3307]
https://github.com/FAForever/fa/blob/7542596ea1c16be28615fdc40cc9bf9c8bb5481a/engine/Core.lua#L219
wrong function description: function returns substring from **start** of length **count**

**Comment by MrRowey** [comment]
@4z0t can this be closed off ?

**Comment by Garanas** [comment]
Once he has made an issue to fix it, yes.

**Comment by 4z0t** [comment]
I will correct it in UI annotations PR
