### ISSUE TITLE
teams on minimap not displayed correctly

### ISSUE THREAD

**Issue by spooky** [FAForever/fa#331]
after the latest patch the fa lobby displays wrong teams on the minimap - all players displayed as they were on team 1. Not sure if that's just a display issue or not.

**Comment by ChrisKitching** [comment]
Fairly sure this is resolved by #379.

**Comment by spooky** [comment]
Fairly sure?

**Comment by Sheeo** [comment]
Can you reproduce on develop?

**Comment by spooky** [comment]
can't even reproduce on production - no idea what conditions need to be met for this bug to occur

**Comment by ChrisKitching** [comment]
By "fairly sure" I mean "extremely sure".

**Comment by spooky** [comment]
extremely sure sounds convincing ;)
