### ISSUE TITLE
final rush pro not working after latest update

### ISSUE THREAD

**Issue by spooky** [FAForever/fa#332]
The lobby refactor must have left regression issues - the final rush mod stopped working and there were no updates to it.

Reporting issue so that it's not forgotten. If it should be somewhere else, feel free to close.

**Comment by Sheeo** [comment]
This thing has all the labels. I'd like someone to help out with investigating whether it's still a thing or not -- anyone?

**Comment by spooky** [comment]
I've been able to start an older version of the mod

**Comment by Sheeo** [comment]
Which version specifically?

**Comment by spooky** [comment]
Final Rush Pro 3 version 1

**Comment by spooky** [comment]
Final Rush pro 4 version 1 - still no luck (versioning for this mod is weird :|)

**Comment by Sheeo** [comment]
People have been uploading weird versions of it to try and undo the 3636 GSR change.

Searching in the vault I get Final Rush Pro 3 v1, v2 and Final Rush Pro 4 v1.

How about Final Rush Pro 3 v2?

**Comment by spooky** [comment]
Final Rush Pro 3 v2 - not working

**Comment by ChrisKitching** [comment]
If we could see some more information about the failure than "Not working", we could probably be more helpful.

**Comment by spooky** [comment]
right, what do you need?
The 'not working' part manifests itself by not showing any units that are supposed to be rushing. The mod ui is there, bot there's no data in it (so, only frames and titles are visible).
game.log: http://pastebin.com/spD7RTW6

One thing to note though - wen I started to mess with the mod settings, I was able to force it into cooperation, so now, I'm not sure if this problem is a result of backwards incompatible changes, mod error, defaults error (?!?) or something else.
I suggest to put the issue on hold and close if noone brings it up again
