### ISSUE TITLE
HQs do not have a proper build animations

### ISSUE THREAD

**Issue by Garanas** [FAForever/fa#3320]
When an HQ is done upgrading it suddenly gains the HQ parts. When the mod was made the animations were not adjusted. To verify you can spawn in some hives, a paragon and start upgrading an HQ from t1 to t2 or t2 to t3. When it is finished, suddenly all the extra bits are added.

**Comment by MadMaxFAF** [comment]
can probably close this issue as it's being dealt with in the hq rework
