### ISSUE TITLE
Riptides unable to hit aeon/cybran t1/t2 sonar

### ISSUE THREAD

**Issue by Farmsletje** [FAForever/fa#3326]
https://user-images.githubusercontent.com/26172055/126376756-49e3887d-b871-49a9-9e48-382dcec54918.mp4

See video. The same happens with aeon t2 & cybran t1/t2 sonars.
Sounds like a similar issue as https://github.com/FAForever/fa/issues/new

**Comment by Garanas** [comment]
I've made changes to prevent this from happening. See also the mention. Thank you for reporting the issue!
