### ISSUE TITLE
About autobuild

### ISSUE THREAD

**Issue by Garanas** [FAForever/fa#3336]
There is a performance issue with #3292 . When someone has a large preference file the FPS can drop below 10. It is quite common that people have a large preference file - as a lot of the competitive players store essentially a portion of the game as a whole in that file through dozens of UI mods.

Another user contacted me with bad performance on the develop branch available on the client. He mentioned it happens when moving the mouse. Disabling the autobuild in the options had no effect. After removing his Game.prefs file and starting with the default (from 282 kb to 12kb) the issue was resolved.

I think it has to do with this line:
 - https://github.com/FAForever/fa/pull/3292/files#diff-c868bcf16513e477142439864f64f550326e64645698ac535cebdd61fc5a1490R182

And I think the solution is to cache 'Prefs.GetFromCurrentProfile('options')' in an upvalue, as it remains the same throughout the game.

I wanted to note that the option to autobuild is appreciated and even an additional feature is requested: being able to set the radius of it in the options menu. E.g., default (as it is right now), large and very large. This should make it easier to use in hectic situations.

**Comment by KionX** [comment]
There may be a problem with the driver:
https://faforever.zulipchat.com/#narrow/stream/203478-general/topic/nvidia.20driver.20update/near/219690100
I can't check it.

**Comment by Garanas** [comment]
He doesn't have the same issue in standard FAF. The code is executed on the render thread as far as I am aware (as it runs every frame).

**Comment by KionX** [comment]
If cache the option, then when you change the option, you will have to restart the game.
It seems that the GetPreference engine function is slowing down.
There is an idea to make a trotling based on GetGameTick.

**Comment by Garanas** [comment]
Yes - I suspect the entire prefs table is send over to the lua state. And that is why the FPS drops, sending over 250kb of data every frame (!) hurts. 

Ah, I wasn't ware it would cause a mandatory restart. What if we create a new thread that updates the upvalue every 10 seconds? That thread could run outside of the render thread (not sure if that would work). I'm not a huge fan of these workarounds - as it still involves getting a lot of data and I do not want to cause stutters when it is not required. 

Maybe we should remove the option all together, and put the default on the highest tech option?

**Comment by KionX** [comment]
`Maybe we should remove the option all together, and put the default on the highest tech option?`
At first it was so. But Uveso and keyser wanted an option.

The solution was found:
local options = Prefs.Get Option('automex')

**Comment by KionX** [comment]
`being able to set the radius of it in the options menu.`
There is a problem with this. To check that the deposit is busy, GetRolloverInfo() is used.
It does not allow you to specify the radius and there is nothing to replace it with.

**Comment by KionX** [comment]
GetFromCurrentProfile('options') occurs 27 times at the FAF.
