### ISSUE TITLE
Investigate network settings for potential performance gain

### ISSUE THREAD

**Issue by Crotalus** [FAForever/fa#3346]
The game has some network settings in console that's never been changed, maybe they were optimal in 2007 when the game released. It could be worth investigating if tweaking these can improve the network lag/stutter in the game,

```
net_AckDelay, 25 ms              Number of milliseconds to delay before sending ACKs
net_Lag Lag, 500 ms              Input command lag
net_MaxBacklog, 2048 bytes       Maximum number of bytes to backlog to any one client
net_MaxResendDelay, 1000 ms      Maximum number of milliseconds to delay before resending a packet
net_MaxSendRate, 2048bytes       Maximum number of bytes to send per second to any one client
net_MinResendDelay, 100 ms       Minimum number of milliseconds to delay before resending a packet
net_ResendDelayBias, 25 ms       The resend delay is ping*new_ResendPingMultiplier+net_ResendDelayBias
net_ResendPingMultiplier, 1.00   The resend delay is ping*new_ResendPingMultiplier+net_ResendDelayBias
net_SendDelay, 25 ms             Number of milliseconds to delay before sending Data
```

William (GPG employee at that time) wrote in GPG-forum:
> Also, you report that the connection was typically 32kbps, corresponding to 1kB/peer/sec. Which tells us that most of the time traffic was succesfully getting through and were didn't end up saturating the pipe with reseonds. That is unless one connection was saturated and the others were good. Then 2k+3(.7k) would have averaged out to about 1kB/peer, so that doesn't actually tell us that the pipe to a single peer wasn't saturated.
> 
> The quality of a connection can be measured by three other things in addition to bandwidth: latency (how long does it take a packet to get from end to end), jitter (how much does the latency vary from packet to packet), and reliability (how likely is it that a packet sent will actually make it). Verizon is (now) giving you your 128k in bandwidth. And if you are uploading files at that rate, then TCP can successfully compensate for the other 3 characteristics. But given what you are describing, it looks like SupCom isn't.
> 
> In order to figure out what is going on, there are a couple of things you can try. First off, it is quite easy to measure/control bandwidth. You are already measuring it with that **ren_ShowBandwidthUsage** command. To control it, you can change the **net_MaxSendRate** variable to something other that 2048. In a 5 player game (4 peers) on a 128kbps connection, setting it to 4096 would keep you below the theoritical saturation point. If you set it to something huge, then that effectivly turns on the clamp and you can see the effect of saturating the connection.
> 
> Latency is also easy to measure. That's just the reported ping number minus the current setting of **net_AckDelay** (defaults to 25, in milliseconds).
> 
> Unfortunately, there aren't easy ways to get supcom to tell you about jitter and reliability. I just never got around to adding code to tally them up and display it in a nice graph.
> 
> I do have one idea for an experiment you and your friend could try if you are game, though:
> 
> Setup a 1v1 game w/ your friend with cheats enabled and the game speed set to adjustable. If it is 1v1 then all network is just the two of you and you don't have to worry about how much of the **ren_ShowBandwidthUsage** graph is the connection in question and how much is the good connections.
> 
> Once in game, set **net_MaxSend** to something absurdly huge so that it doesn't come into play.
> 
> Now fire up the **ren_ShowNetworkBandwidth** graph on both you and your friend's machine. Then compare the send bandwidth on the machine of the person spamming commands to the receive bandwidth on the other machine. They should match if everything is going well.
> 
> Now play with the game speed. Run it up to +10. The bandwidth used should increase drastically. Does significant packet loss start showing up someplace? What happens if you slow the game down?
> 
> If just speeding up the game doesn't stress the network enough, you can also create a 1000 or so units and feed 'em lots of commands. The easiest way to do this would be to use the Alt-F2 menu to create one unit. Then select it and hit Ctrl-Shift-C (copy) followed by Ctrl-Shift-V (paste) several times. Now select all those units, Ctrl-Shift-C again followed by Ctrl-Shift-V several more times. Repeat until you have a big pile of units. Select all those units and then spam the right mouse button on various places in the map. The network usage should spike while it is sending those move commands.
> 
> There are also lots of other console variables that control how and when supcom goes about sending packets:
> 
> **net_SendDelay** - how long (ms) to delay once some data is available before sending it out. If too short, we'll waste bandwidth sending lots of small packets. If too large, the percieved latency will be too high.
> 
> **net_AckDelay** - like SendDelay, but for acking incoming packets instead of for sending outgoing data.
> 
> **net_ResendPingMultiplier** and **net_ResendDelayBias** - controls how long we wait before resending a packet that hasen't yet been acked. The exact formula is "(ping*multiplier+bias)*2^try" where "try" is the number of times we've already tried to send this packet already (clamped to 3 so the resend to delay doesn't get too huge).
> 
> **net_MinResendDelay** and **net_MaxResendDelay** - more clamps on the resend time.
> 
> **net_MaxSendRate** - max bytes/sec to send to any one client.
> 
> **net_MaxBacklog** - We can actually briefly exceed the max send rate as long as the amount of data buffered is less than this. Defaults to 2k. This is it model the fact that the router/modem has a buffer in it so it can take a few packets quickly without dropping any of them, but if we are going to keep sending we need to back off to a rate it can sustain.
> 
> Another quite useful command is "**wld_ClientDebugDump**" which dumps out lots state about the network connections to the F9 log. If the eject dialog comes up and you don't know why, this can sometimes lend some insight on what internally has gone wrong with the connection.

**Comment by Garanas** [comment]
This is a good find / suggestion. We should definitely look at these and determine how it impacts the game.

As an example, what data is exactly shared over the network?
 - Data passed from sim -> ui?
 - Data passed from ui -> sim?

I think the replay may help us answer these questions.

**Comment by Crotalus** [comment]
The data sent are essentially the replay command stream (player commands + stuff like increase tick / checkpoint) so ui -> sim would be the most correct way to put it.

Chat messages also get sent over the network but IIRC vanilla FA didn't store the messages in the replay, FAF stores them by adding a command with the message text into the replay command stream.

sim -> ui is sent by the Sync-table but no need to send it over the network thanks to the deterministic simulation.

**Comment by Garanas** [comment]
Good - there is not much ui -> sim communication except for the spread attack. Could you do the initial investigation? I've already got a few things planned for this weekend.

**Comment by Crotalus** [comment]
Played a 4v4 Setons game now and kept an eye on network bandwidth. The graph lines hovered mostly around 4kb sent / received per second with spikes up to 8kb / s.  The game was a lagfest though, one player lost packages continuously.

**Comment by 4z0t** [comment]
@Garanas added a few more options for handling disconnections faster iirc, should it be closed?
