### ISSUE TITLE
Some text in lobby is not shown properly when UI scaling is enabled

### ISSUE THREAD

**Issue by Jaakko-github** [FAForever/fa#3353]
![lobby](https://user-images.githubusercontent.com/64012224/129475437-cfbee682-7a9f-46b5-b107-4df2fd08743b.png)

As shown in the picture, when UI scaling is enabled, part of the last line of chat is not visible. In addition, the drop down menu shows no items.

When the font size is reduced enough using the slider, text fits the chat box. However, this does not fix the drop down menu.

**Comment by speed2CZ** [comment]
Whats your resolution and what scale?

**Comment by Jaakko-github** [comment]
Resolution is 5120x1440 with 200% scaling in Windows. The lobby is in windowed mode, but the problem persists in fullscreen.

**Comment by Garanas** [comment]
@Jaakko-github Did you try scaling the game through the UI scaling options provided by the game, instead of those of Windows?

**Comment by Jaakko-github** [comment]
The UI scale option is the one that breaks the lobby for me. I have set the ingame UI scale to 125%. If it is set to default value 100%, the lobby is normal even with 200% scaling of other Windows items.

**Comment by Garanas** [comment]
Oh - you use both scalings?

**Comment by Jaakko-github** [comment]
Yes, however, I believe the Windows scaling has no effect on the game when it launches. Without scaling the entire UI is very small and in an awkward position. In game, the only scaling that takes effect is the UI scale. This setting also affects the size of the lobby window before a game is launched.

**Comment by MrRowey** [comment]
@Garanas this been fixed in the upcoming game patch ?

**Comment by Garanas** [comment]
I think so, yes - with the changes done by speed2
