### ISSUE TITLE
Pinging appears to be disabled after being defeated

### ISSUE THREAD

**Issue by Garanas** [FAForever/fa#3359]
This happens on the development branch but not in the typical branch. I think it is related to #3240 as it is the only PR that touched the files for the past five years. Once defeated you can no longer ping (of any of the four type of pings) , even though the buttons are still 'active'.

Is this intended side-effect due to https://github.com/FAForever/fa/issues/2259 ?

**Comment by KionX** [comment]
Yes. This is how it should be.

**Comment by Garanas** [comment]
Then the UI needs to represent that accordingly by disabling the buttons. Are you available to make a PR on that matter?

**Comment by KionX** [comment]
Yes.
