### ISSUE TITLE
Auto-toggle mass fabs sim side 

### ISSUE THREAD

**Issue by Crotalus** [FAForever/fa#3364]
At the moment players use UI mods to toggle mass fabs when power stalling. This isn't optimal from a performance perspective, having to send commands to turn on / off the mass fabs constantly.

A better solution would let the sim side handle this and maybe control the overall settings from the UI side instead. Maybe right click on the enable / disable button to enable auto-toggle. And a global settings to change the default of that toggle.

I guess it would make the gameplay more fair between players that don't use those mods and those who use them also.

**Comment by Garanas** [comment]
Do you reckon this affects performance? How would we test that?

**Comment by Crotalus** [comment]
The UI mods cannot get units without actually selecting them in game so periodically they quickly select units, grab their references and then re-selects the units that the user had selected before so you don't notice anything (and units are cached for a while so it doesn't select too often)

Then depending on the eco state they turn on / off fabs by sending multiple pause / unpause commands to the sim.

Not sure how much this will affect performance, I've seen UI stuff affecting sim speed even if they are in a different thread. My guess is that sim <-> ui still is quite interlinked due to the sim -> ui sync every tick etc. (`sim_interlocked 1` in console make them 100% linked)

**Comment by Garanas** [comment]
I see - that isn't quite efficient indeed. This would mean that we would integrate the mod for performance reasons, make it a toggle via options menu.

**Comment by Garanas** [comment]
Closing this issue as this has been tackled with 3736.
