### ISSUE TITLE
selecting Canyon v2 crashes the lobby

### ISSUE THREAD

**Issue by spooky** [FAForever/fa#337]
When I select the map Canyon v2 from the game lobby, it crashes

**Comment by Xinnony** [comment]
:o
Can you send a log file ?

**Comment by spooky** [comment]
Where do you want the log? (though not sure if it will help in any way - can't see any errors there).

Steps to reproduce:
- host a game on a map different than Canyon v2 (FAF as featured mod, no additional mods)
- go to game options
- set the map size filter to '5km'
- select Canyon v2 from filtered list

**Comment by aeoncleanse** [comment]
Confirmed to be happening, it's a hard FA.exe crash, so I get nothing in the log... Problem Event Name - BEX

**Comment by Sheeo** [comment]
Closing as FAForever/server#13 will fix this.
