### ISSUE TITLE
DirectX10

### ISSUE THREAD

**Issue by Garanas** [FAForever/fa#3388]
I was discussing with P4block on Discord and some other person about how broke FA is in practice. The discussion was about what made Holland great and then about DirectX10. Long story short, the effect files contain DirectX10 references all over it, including compatibility files. 

When you start the game with `/d3d10` as program argument it crashes on Windows stating that it crashes on the shader. Has there been work on this previously?

Would it be possible to investigate whether we can enable it through a binary patch somehow? And is the Directx10 dll included in the installation?

[error.txt](https://github.com/FAForever/fa/files/7070771/error.txt)

See also this screenshot that is made by the GPG team on DirectX10:

![image](https://user-images.githubusercontent.com/15778155/131219762-5421136e-79c2-49af-8ce3-01f7b3b1d788.png)

Potential source of DirectX10: 
 - https://github.com/doitsujin/dxvk/releases/download/v1.9.1/dxvk-1.9.1.tar.gz

**Comment by Garanas** [comment]
After sitting down with P4Block about this we got to the point where it compiles the shaders (not sure if it actually renders - but sure) it keeps crashing saying I do not meet the minimum requirements!

![image](https://user-images.githubusercontent.com/15778155/131221890-e7170c19-0f3e-4b62-b474-c9573e0b6a1d.png)

**Comment by p4block** [comment]
A fun behavior I found is that DXVK will run the game without touching the shaders and get you to the "minimum specifications" error, but the normal Microsoft DirectX DLL needs heavy modifications to the .fx files to compile (then arrive to the same error)

**Comment by Garanas** [comment]
And when he says heavy modifications he means: remove everything that is invalid until it works :) .

**Comment by KionX** [comment]
I have been studying this issue. The shaders for DX10 are not completed and therefore compile with errors.
They can be completed. And if there are no other errors...

**Comment by Garanas** [comment]
That isn't the only issue however - we manage to compile all the shaders as is (see also the comment of p4block) but the game just hard-crashes saying we do not have the hardware requirements. Could you find out why it is stating this in the binary?

**Comment by p4block** [comment]
> The shaders for DX10 are not completed and therefore compile with errors.
> They can be completed. And if there are no other errors...
> 
> You need to finish writing d3d10states.compat
> Think I could complete them if there is sufficient motivation.

The thing is that it didn't seem to compile with errors, at least from what we could see and we ended up at the "your pc doesn't meet minimum requirements" message. 

We believe we need to patch the binary to skip the error message, and then we may encounter a completely broken game or not.

**Comment by KionX** [comment]
How did you manage to compile them?

**Comment by Garanas** [comment]
If I recall correct by pasting the DLLs of the original post next to the executable.

**Comment by KionX** [comment]
dxvk As I see it has nothing to do with the FA. This is an emulation of DX via Vulkan.
Since the DX10 shaders are not completed enabling /d3d10 will not help.
To launch the DX9 FAF via VK, it is enough to place d3d9.dll next to the FAF executable file.

**Comment by p4block** [comment]
So we got to the "verify your pc" message in two ways:

- Using DXVK which converts the game from dx9/10/11 to vulkan by providings fancy d3d9, d3d10... dlls.
- Using the normal Microsoft d3d10.dll and editing the d3d10states.compat and the fx files. 

The "verify your pc" message could also not be a check but rather a generic error when something graphicswise fails to initialize, but that something wasn't shader compilation. 

Running the game on dx10 under wine I got two different behaviors too:
Wine dx10->ogl causes "application tried to create more than 1 back buffer, which is unsupported" 
DXVK dx10->vulkan complained something about nested windows being unimplemented and the game crashed because it had no screen buffer to write to.

These two could be foreboding the underlying issue in the game or could just be that DX10 in Linux is fairly untested and have nothing to do with the problem on Windows.

**Comment by KionX** [comment]
There is Wine on Linux. It already emulates DX via VK. Am I wrong?

**Comment by KionX** [comment]
[ForgedAlliance_d3d11.log](https://github.com/FAForever/fa/files/7071044/ForgedAlliance_d3d11.log)
_warn:  D3D11CoreCreateDevice: Adapter is not a DXVK adapter_
It looks like a dxvk error. My video card supports both DX11, DX12 and VK.

**Comment by KionX** [comment]
It is not very easy to look in the engine. It will take time.

**Comment by p4block** [comment]
Well, DXVK is just another thing that can go wrong in this. Although it would be funny to pull a Valve and ship DXVK to everyone running the game, I think that rewriting the shaders is the way to go.

That said I find it amazing that DXVK can do some magic and figure out the incomplete dx10 stuff and not complain much.

The error you had, I didn't experience. Did you also copy dxgi.dll to the exe folder?

**Comment by KionX** [comment]
Yes. I copied everything from x32.

**Comment by KionX** [comment]
I think DX emulation is useless. This only adds a few more API layers.

**Comment by p4block** [comment]
I only mentioned it because it changes the behavior weirdly, with it you don't need to patch the shaders to get to the error message, which I found weird.

I play on linux so I _need_ to use it, but for trying to get things to work it can sure get in the way. That's why I asked @Garanas to run stuff on his windows computer :grin:

**Comment by KionX** [comment]
I also run stuff on windows computer.

**Comment by Garanas** [comment]
Can you retry with just the dx10 dll in the folder, and move all the others out?

**Comment by KionX** [comment]
dx10 dll uses dx11 dll. Not work.

**Comment by p4block** [comment]
That makes sense, similar to the DXUP project, apparently you can map DX10 to 11 pretty well, so the game would actually run in 11 mode. But the game doesn't know that, it should still believe it is running 10.

**Comment by KionX** [comment]
Native DX10 at least comes to compilation. I do not know what will happen next.

**Comment by Garanas** [comment]
Did you get the same error message?

**Comment by KionX** [comment]
![1](https://user-images.githubusercontent.com/5648030/131227124-6392028c-7b4e-45d3-9e8e-07622b53902c.png)

**Comment by Garanas** [comment]
Can you translate the error?

**Comment by KionX** [comment]
The entry point was not found.

**Comment by p4block** [comment]
https://github.com/doitsujin/dxvk/issues/551

Interesting info regarding that function

**Comment by p4block** [comment]
I think there could be a problem with the multi-screen support in the game. Whatever approach they took to create that feature may be what's messing with us now.

**Comment by KionX** [comment]
dxvk d3d9 is already working without problems. d3d10 still won't work without shaders.
I don't want to do any dxvk debugging.

**Comment by Garanas** [comment]
If it doesn't reach the shaders then why did it provide errors on compiling them on my system?

```c
CD3DDeviceResources::DevResInitResources: Unable to load effect file /effects/cartographic.fx

Program : C:\ProgramData\FAForever\bin\ForgedAlliance.exe
Cmd line arguments : /init init-dev.lua /EnableDiskWatch /showlog /nofog /cheat /gameoptions option-value1 option-value2 /d3d10

Callstack:
    unavailable.

Last 100 lines of log...

debug: SND: Loaded SoundBank 'xsa_weapon'
debug: SND: Loaded SoundBank 'xsb'
(...)
debug: Loading module '\000/lua/keymap/keyactions.lua\000'
debug: Loading module '\000/lua/keymap/debugkeyactions.lua\000'
warning: c:\users\jip\documents\supreme commander\fa\effects\cartographic.fx: unable to create effect: c:\users\jip\documents\supreme commander\fa\effects\cartographic.fx reason: (1291): error X3004: undeclared identifier 'FixedFuncVS'
````

When we fixed these errors it got to the point where it gave us the hardware issue.

**Comment by KionX** [comment]
I have a crash.*

**Comment by KionX** [comment]
@Garanas
![image](https://user-images.githubusercontent.com/15778155/131221890-e7170c19-0f3e-4b62-b474-c9573e0b6a1d.png)
This is due to
https://github.com/doitsujin/dxvk/blob/master/src/d3d10/d3d10_main.cpp#L248
How can you compile shaders?

**Comment by p4block** [comment]
I think the error with dxvk is a rfluke, we thought that by reaching the "unable to start" message we'd had passed the problem with the game shaders in dx10 if you do nothing (Unable to load effect file /effects/cartographic.fx) but it seems it's exploding much earlier.

@Garanas can share his patched shaders in a branch or something and we see where that crashes

**Comment by Garanas** [comment]
To rephrase: 'patched shaders' - but I'll share them later today in a PR.

**Comment by Garanas** [comment]
Closing this, it is not viable.
