### ISSUE TITLE
Advanced Strategic Icons [FOR MEXES] do not work on FAF Develop

### ISSUE THREAD

**Issue by Azraeel** [FAForever/fa#3391]

**Comment by Garanas** [comment]
Can you attach a screenshot / log?

**Comment by Azraeel** [comment]
> Can you attach a screenshot / log?

This has been reported in a lot develop games ive been running, i ran the ASI once and yes they are right mex icons are defaulted back ill find the log if i have it

**Comment by Garanas** [comment]
It could be because this is the develop branch and they changed the icons for the regular branch (.nxt5 / nxt2)?

**Comment by Azraeel** [comment]
> 
> 
> It could be because this is the develop branch and they changed the icons for the regular branch (.nxt5 / nxt2)?

probably

**Comment by 4z0t** [comment]
Close?
