### ISSUE TITLE
E-storages are suddenly part of Hotbuild

### ISSUE THREAD

**Issue by Garanas** [FAForever/fa#3395]
People playing on the develop branch in comparison to the default branch experience different results with Hotbuild. On the regular branch the hotkey for power includes pgens and hydro. On the dev branch it also includes the energy storage. It also 'leaked' through to the regular branch - suspecting it has to do with the prefs file somehow.

This is experienced by multiple people.

Any ideas as to why that would be it? I've discussed it with Keyser previously and it doesn't appear to be related to changes that we made.

**Comment by Tagada14** [comment]
If you install Dragun's Hotkey Key mode it includes this without specifying it. Took me about 2 weeks to find the culprit. So perhaps that's the case here? I've played FAF Develop and I didn't notice such issue.
