### ISSUE TITLE
No unit count/cap, or resource cap displaying in Scoreboard in Co-op Campaigns

### ISSUE THREAD

**Issue by Kaitane** [FAForever/fa#3401]
The unit count/cap and player resource count are not showing in the campaign scoreboard during FA and SC campaigns. The clock timer works. The unit count/cap and player resource count does work in skirmish though. I'm not running any mods, after a fresh install of SC, FA and FAF. I have tested in vanilla/steam skirmish and campaign, and it works fine there. Tested in both FAF and vanilla /steam with no mods each time. I don't have a log of the game or a replay ID. Thanks for looking into this

**Comment by Garanas** [comment]
Just to make sure, you're referring to this scoreboard:

![image](https://user-images.githubusercontent.com/15778155/131997721-1d2d8bdc-34e5-47f7-a823-377ef4c8a97d.png)

Where should the resources be displayed there?

**Comment by Kaitane** [comment]
Yes, that's the one.

**Comment by KionX** [comment]
Already fixed #3213

**Comment by Garanas** [comment]
In other words: this is fixed in the upcoming patch.

**Comment by Kaitane** [comment]
Great, thanks guys.

**Comment by Kaitane** [comment]
Hey guys, just so I understand the patch/dev process, is this fix implemented in the next patch, which is currently not available to test? Or based on Kionx's reference of 3213, should it be therefore fixed and available to test in the current  FAF develop download? As I have only been using the FAF Develop lately, the fix is not present, and so remains unchanged. Also, sorry, Garanas (Jip), I missed your comment beneath the screenshot you displayed. The resources gathered, should be displayed under the clock time, and the unit cap to the left of the tank (as per FAF skirmish mode).

**Comment by Garanas** [comment]
As far as I know campaign mode doesn't show resources. It never has.

And yes - the unit count is fixed.

**Comment by Kaitane** [comment]
Actually, you are right, I checked original vanilla steam campaign, and it only has unit count. I suppose it's been so long since I played steam version, and have been used to FAF skirmish, which does contain resource count, that I thought it was missing from campaign as well. Well at least the unit count will be back in the next patch. Thanks for letting me know. Great work.
