### ISSUE TITLE
Unit transfer to ally resets all cooldowns. 

### ISSUE THREAD

**Issue by zlo-faf** [FAForever/fa#3402]
This is a big oppotunity for abuse. 
Here is one example of abuse https://youtu.be/Gtoef8Unn7g
It also may affect TML, SML, SMD, maybe even TMD. Can maybe affect sacu abilities like overcharge or TML.
I don't ask for full solution, just having this for weapons would already be good start.

**Comment by Garanas** [comment]
I think we could put the weapons on cooldown for all units the moment they spawn. When you gift a unit, you make a new unit with the new army. It would prevent this issue all together.

I also recall @KionX working on a way to gift units without making a new unit. Is that stable?

**Comment by KionX** [comment]
_I also recall @KionX working on a way to gift units without making a new unit. Is that stable?_
This is not completed and has not been tested.

**Comment by Garanas** [comment]
Then I think for now starting the weapons on 'reload' mode is a good solution as any. I'll look into it 😄

**Comment by Garanas** [comment]
Looking at the weapon functionality, we may not be able to do that. I'll look into it a bit deeper

**Comment by Tagada14** [comment]
Please don't make the units spawn without having their weapons reloaded. This breaks game balance quite a bit.

**Comment by Garanas** [comment]
I'll look into doing it for only units that are gifted.

**Comment by Garanas** [comment]
Gifted units start with their weapons unloaded since 3732.. That prevents the abuse.
