### ISSUE TITLE
Caching blueprint calls

### ISSUE THREAD

**Issue by Garanas** [FAForever/fa#3404]
This issue is supposed to be a discussion.

LOUD has been applying a pattern with regard to blueprint calls all over their code - and it runs fine. To be specific, they changed `local blueprint = entity:GetBlueprint()` with `local blueprint = __blueprints[entity.BlueprintId]`. During on create they get the blueprint once to get the unit id. Any other call from that moment on uses the __blueprints table instead of doing an engine call.

The speed up is quite significant:
```
-- EngineCall:          199 ms
-- TableRetrieval:      16.1 ms
-- TableRetrievalCheat: 10.2 ms
-- TableRetrievalSafe:  19.3 ms
-- TableStored:         9.25 ms
```

You can find the complete benchmark [here](https://gitlab.com/supreme-commander-forged-alliance/other/profiler/-/blob/main/mods/profiler/modules/benchmarking/benchmarks/blueprints.lua).

Note that the blueprint is being retrieved for the most casual occasions, such as retrieving the do not collide (dnc) lists [when checking whether something collides with a unit](https://github.com/FAForever/fa/blob/deploy/fafdevelop/lua/sim/Unit.lua#L1472). Or when veterancy is [being dispersed](https://github.com/FAForever/fa/blob/deploy/fafdevelop/lua/sim/Unit.lua#L1252). And even when [damage effects](https://github.com/FAForever/fa/blob/deploy/fafdevelop/lua/sim/Unit.lua#L1122) need to be played. This is just for a unit - you can also think about props, projectiles, weapons and shields.

All in all - this is being called a lot. I've proposed changing this before and have shown the benefit of doing so [before and have shown tangible results](https://github.com/FAForever/fa/pull/3340#issuecomment-898877781) as to what we gain.

One drawback @KionX pointed out is that there is some form of inconsistency between the blueprint values and there may be an [alternative approach](https://github.com/FAForever/fa/pull/3340#issuecomment-898799353) to changing blueprint values. Reading the entire [topic](https://github.com/FAForever/fa/pull/3340) will give you a good idea of the arguments.

Now - my opinion is clear. But what is yours, and should we make this change?

**Comment by Garanas** [comment]
Bump.

**Comment by KionX** [comment]
I counted about 5 places in the engine where there is a call to __blueprints
There is also a link to the internal blueprint in the Entity.

**Comment by KionX** [comment]
Entity:GetBlueprint() returns a reference to __blueprints
For UEF ACU
`SimLua WARN(SelectedUnit():GetBlueprint()==__blueprints[3459])` is true
`SimLua WARN(__blueprints[3459]==__blueprints['uel0001'])` is false

**Comment by Garanas** [comment]
What we could do is store a reference to the __blueprints table, and use that reference throughout the code.

In the end - a table reference will always point to the same table. And as long as we do not edit a unit live then this will always hold.

**Comment by KionX** [comment]
I suppose the correct safe way to cache is something like this
```
local blueprints = __blueprints
local blueprint = blueprints[self.BlueprintOrdinal]
```

**Comment by Garanas** [comment]
And what if we'd save the blueprint in the entity itself? E.g., get to the fastest approach?

**Comment by KionX** [comment]
The engine always uses __blueprints[BlueprintOrdinal]
In this case, you can not allow changes to the pointers.

**Comment by Garanas** [comment]
I can live with that - we can follow them in their tracks with this.

**Comment by Garanas** [comment]
Closing this issue.
