### ISSUE TITLE
Horn button

### ISSUE THREAD

**Issue by Xinnony** [FAForever/fa#342]
I had the idea to add some sort of notification for wakeup the AFK players in the FA Lobby.

"retardo" simply suggest a horn button that plays a sound for the AFK players.

For me i prefer send a GPGnet packet to FAF and FAF Show a notification (and sound ?)

And add this : https://github.com/FAForever/lobby/issues/116

Need to discuss some

**Comment by jnorthrup** [comment]
hotkey ^G works for me

**Comment by Sheeo** [comment]
@jnorthrup what action do you have `^G` mapped to?

**Comment by Xinnony** [comment]
@jnorthrup i speak for AFK Player in FA Lobby, not ingame :)

**Comment by ChrisKitching** [comment]
But you can just send them a PM on faf and it makes a sound.
Unclear that a horn button would be much better
