### ISSUE TITLE
Questions about creating threads

### ISSUE THREAD

**Issue by Garanas** [FAForever/fa#3421]
I've been looking through the base code how threads (read: ForkThread) are used. And they're used all throughout the code for the smallest tasks, as a few examples:
 - Enable / disable rocking of individual units (which we fixed)
 - Enable / disable tread marks of individual units (the trail tanks leave behind)
 - Enable / disable footprints
 - Enable tracking on each individual tactical missiles
 - Probably more examples if we'd dive deeper :) 

The aim of this issue is to gather information as to whether threads are expensive or not, and how we can measure that. Specifically:
 - What happens when a new thread is made, what is allocated?
 - What happens when a thread is yielding (waiting)?
 - What happens when a thread is destroyed, what is de-allocated?

I have one [basic benchmark](https://gitlab.com/supreme-commander-forged-alliance/other/profiler/-/blob/main/mods/profiler/modules/benchmarking/benchmarks/function-threads.lua) that shows creating threads has a serious overhead in comparison to just calling a function or just executing the code in general. But I find it hard to argue as to whether it has a large impact on the garbage collector, for example.

**Comment by Garanas** [comment]
Looking through the lua documentation it involves quite a few operations:
 - https://github.com/FAForever/lua-lang/blob/lua-5.0/doc/manual.html#L2586

**Comment by KionX** [comment]
Why look into this? The fastest code is the one that is not executed.
The key idea of ForkThread is a Fork. If do not need a fork, then do not use it.

**Comment by Garanas** [comment]
_Why look into this? The fastest code is the one that is not executed._

I agree - but that is not the point of this issue. A lot of small things create and destroy threads like they're free of charge and I'd like to investigate as to what the impact of that is. Is it it is worth spending time to create a 'manager' that prevents the continuous allocation / de-allocation of threads for certain tasks, such as the creation of thread marks?

An example is the [missile manager](https://github.com/Garanas/fa/blob/7413cddeded3efbe4bf3a19a7b0c650e3d6ca3d3/lua/sim/MissileManager.lua) that was made to manage tactical missiles. Instead of each tactical missile creating their own thread, there is one (or at least - a constant amount of threads between 0 - 10) that manage different type of missile arcs. In turn, the missiles were slightly cheaper on the sim but I was not able to investigate whether it helped the garbage collector.

**Comment by KionX** [comment]
Since there is a benchmark for this, I think we can close it.
