### ISSUE TITLE
Caching engine calls in general

### ISSUE THREAD

**Issue by Garanas** [FAForever/fa#3422]
There's a lot of information in the game that we constantly request from the engine. An [example](https://github.com/FAForever/fa/pull/2963) in the past is the army that a unit or projectile belongs to. Another [example](https://github.com/FAForever/fa/pull/3366) is about retrieving the current layer.

There are more examples:
 - Retrieving the blueprint information of a unit (#3404) (called all over the code).
 - Retrieving the launcher of a projectile.
 - Retrieving the weapons of a unit (called on each horizontal change [here](https://github.com/FAForever/fa/blob/deploy/fafdevelop/lua/sim/Unit.lua#L3172)).
  - Retrieving the bone count of a unit (called for adjusting damage effects [here](https://github.com/FAForever/fa/blob/deploy/fafdevelop/lua/sim/Unit.lua#L1126)).
  - Retrieving the brain of a unit (called all over the code, especially AI-related code).
  
And a [benchmark](https://gitlab.com/supreme-commander-forged-alliance/other/profiler/-/blob/main/mods/profiler/modules/benchmarking/benchmarks/weapons.lua) to see what we have to gain with a chance like this. This will introduce _slightly_ more garbage per unit, but I think that is neglectable in comparison to what we potentially gain performance-wise. 

What are the opinions about this? Are there any drawbacks?

**Comment by KionX** [comment]
There are two drawbacks:
- It is not safe if there is no event.
- Complicates code support.

**Comment by Garanas** [comment]
_It is not safe if there is no event._
What do you mean with this?

_Complicates code support._
Mods can just use the original calls. We're not touching those. We're just replacing the calls in this repository. Or are you referring to something different here?

**Comment by KionX** [comment]
_It is not safe if there is no event._
Similar to OnLayerChange.

_Complicates code support._
This also applies to FAF.

**Comment by Garanas** [comment]
Does retrieving a weapon, launcher and / or a bone count (note that all functions I want to cache have the word 'Get' in them) cause an event of some sort?

Please elaborate as to how this complicates code support.

**Comment by KionX** [comment]
More code means more problems.
Guessing the behavior of the engine is also a problem.
The only question is whether a particular case is justified.
This is my experience. I don't want to argue about it.

**Comment by Garanas** [comment]
This isn't about arguing and apologies if that is how it looks like. I'm learning myself as I go - I can't do that without discussing it in-depth.

**Comment by KionX** [comment]
The most frequently called engine function is 'next'. These are 'for' loops.

**Comment by Garanas** [comment]
Closing this issue - we're slowly but surely caching relevant calls.
