### ISSUE TITLE
Replicated lobby slots after map change

### ISSUE THREAD

**Issue by Sheeo** [FAForever/fa#343]
![screenshot-139](https://cloud.githubusercontent.com/assets/37968/5628912/d2e4ad9e-95ad-11e4-88d5-151eb4e4f76d.jpg)

**Comment by ChrisKitching** [comment]
Do we have STR for this? I can't seem to reproduce it.

**Comment by ChrisKitching** [comment]
This and #387 are all part of the same problem.

When a player is occupying a high-numbered slot when the host switches the game to a map for which that slot is not used, the game does not delete the UI element for the slot that the user was occupying before the map change, causing them to both appear to be in a slot and be an observer at once.
See: http://i.imgur.com/dLzpsd4.png

When the user (who is really an observer) now joins a slot "for real", they are shown to be in both this new slot and the one they were booted out of earlier when the map changed, leading us to get this bug.
