### ISSUE TITLE
Support commanders dust cloud explosion happens when underwater

### ISSUE THREAD

**Issue by Garanas** [FAForever/fa#3433]
![image](https://user-images.githubusercontent.com/15778155/133986033-c982d019-64be-41db-93bf-a133193aac7a.png)

When a support commander dies underwater the dust cloud explosion still happens. This shouldn't be the case.

**Comment by Hdt80bro** [comment]
What should happen when the sACU is in the shoal? Would we need to rework the effects to make it transition from having a smoke ring to not? Otherwise, if it's a hard transition, like if we simply guarded [this](https://github.com/FAForever/fa/blob/deploy/fafdevelop/effects/Entities/SCUDeath01/SCUDeath01_script.lua#L49) when the unit's underwater, it might look funny.

**Comment by MrRowey** [comment]
If the unit is under the water would think that just behaving the unit explosion with out dust cloud makes sense

**Comment by Hdt80bro** [comment]
Sorry, I meant if the unit is only partially underwater. What happens then? When do we stop drawing the smoke ring?

**Comment by MrRowey** [comment]
well unless their a way to having different stages where the unit is fully under the water compared to paddling on the beach I would assumes if in water no smoke ?

**Comment by Hdt80bro** [comment]
Sure, we can try that
![image](https://user-images.githubusercontent.com/37224614/180617563-834a9235-58a7-4ef5-9463-1c81ea96be0e.png)
This look good?
```lua
if position[2] + 2 > GetSurfaceHeight(position[1], position[3]) then
    self:ForkThread(self.CreateOuterRingWaveSmokeRing)
end
```

**Comment by MrRowey** [comment]
Yes this looks pretty good in my option as soon as the SACU head is under the water the make sense for their to be not dust cloud

@Garanas thought with this way of implementing it ?

**Comment by Garanas** [comment]
Looks good to me - in the future we should have a different explosion for when the SACU is below water. My thoughts are something [like this](https://science.howstuffworks.com/explosion-land-water1.htm), in particular the image. We can re-use some of the current naval destruction effects for that, and spawn those effects on the surface.

**Comment by Hdt80bro** [comment]
The image is nice and all, but now I've read the article and want to revamp all explosions to be more destructive underwater...
*ignore the impulse*
I'll put in that change
