### ISSUE TITLE
"SACU's presets needs different EXP"

### ISSUE THREAD

**Issue by Sheikah45** [FAForever/fa#3446]
"SACU's presets need differet exp for veterancy. Maybe it's depends of their mass costs. Can you fix it,please."

From https://github.com/FAForever/downlords-faf-client/issues/2352

@FunnySqirrel

**Comment by Sheikah45** [comment]
I could actually transfer the issue so I did it manually

**Comment by FunnySqirrel** [comment]
oh, Thank you so much.

**Comment by Tagada14** [comment]
I am not quite sure I understand what the issue/bug is here? All units need to kill a certain amount of mass in order to get a vet level, that amount depends on their mass cost and is either x2, x1.5, x1.25 (IIRC) of their cost depending on the specific unit.

**Comment by Garanas** [comment]
I think the issue is that when you'd enhance a barebone SACU to rambo set, or make a Rambo SACU directly then they wouldn't share the same vet requirements.

**Comment by Tagada14** [comment]
Yeah, a known issue, fixed soon tm with the SACU rebalance.

**Comment by MrRowey** [comment]
@Tagada14 is this still being addressed in the current SACU PR ?
