### ISSUE TITLE
Capitalisation consistency in gameplay settings

### ISSUE THREAD

**Issue by FemtoZetta** [FAForever/fa#3448]
A new option was added to the gameplay settings, but its capitalisation is not consistent with the rest:
![grafik](https://user-images.githubusercontent.com/61892809/134646776-a71dcac7-4290-4ffd-8b61-53ce43c60741.png)

Automatic extractor selection --> Automatic Extractor Selection

**Comment by MrRowey** [comment]
@Garanas can be closed with that PR
