### ISSUE TITLE
decals not rendered on far zooming 

### ISSUE THREAD

**Issue by crommcruach** [FAForever/fa#3451]
Since last version i have the problem that Mex and Termal Power decals not rendered properly so i have to zoom in to see mex and thermal build sites. ani fix for this?

**Comment by Garanas** [comment]
There is a fix to it, just wondering what changed. Are all extractor / hydrocarbon points affected?

**Comment by crommcruach** [comment]
Yes all of them. Where to get it?

**Comment by Garanas** [comment]
For my idea, are we talking about these icons:
![image](https://user-images.githubusercontent.com/15778155/135252982-e85793e2-caa4-46aa-b339-96b1f1c60969.png)

Or these decals:
![image](https://user-images.githubusercontent.com/15778155/135253024-376c5bc1-ac3a-4c82-bc20-d7801f4efb14.png)

**Comment by Garanas** [comment]
I can't reproduce the issue and there is no response - if the issue persists try to disable free camera mode (see F1 in-game to find the hotkey). If that doesn't help, please make a new issue with screenshots as to what you are referring to.
