### ISSUE TITLE
Add Cybran cloaking enhancement to unit restriction menu

### ISSUE THREAD

**Issue by Garanas** [FAForever/fa#3462]

**Comment by MrRowey** [comment]
https://github.com/FAForever/fa/blob/deploy/fafdevelop/lua/ui/lobby/UnitsRestrictions.lua#L180 

Just need to add the Enhancement Calls here I assume I will test on my Local Dev when I get time

**Comment by MrRowey** [comment]
after looking into this more I noticed that the Stealth and Cloak for the Cybran ACU is Wrapped up into the Stealth Restriction that all building and enhancements off

**Comment by Garanas** [comment]
Which makes sense - but I think you should also be able to disable those in particular.

**Comment by MrRowey** [comment]
yeh I'm testing this at the moment
