### ISSUE TITLE
Fix Seraphim Sonar being considered a t3 structure by unit restrictions

### ISSUE THREAD

**Issue by Garanas** [FAForever/fa#3463]

**Comment by MrRowey** [comment]
fa/lua/ui/lobby/UnitsRestrictions.lua >

Line 117 for T3 Structure restriction has Mobile Sonar Tag which the T2 Sonar has  
  
    T3_BASE_SPAM  = "(TECH3 * STRUCTURE - FACTORY - MASSEXTRACTION - MASSSTORAGE - MASSFABRICATION - ENERGYPRODUCTION - ENERGYSTORAGE + MOBILESONAR)",
