### ISSUE TITLE
Color indication for overcharge cursor incorrectly indicates units will die

### ISSUE THREAD

**Issue by ThomasHiatt1** [FAForever/fa#3469]
When you mouse over a unit the overcharge cursor is supposed to be green if it will kill a unit, orange if it will not, and grey if it is unknown. Currently, it sometimes shows green when there is not quite enough energy to kill the unit. I suspect this is because the indicator may be using the old energy to damage ratio before it was changed to 3:1. The easiest way to see this is to make a single energy storage and place the overcharge cursor over an ilshavoh. It will turn from orange to green as the storage becomes full, but the overcharge leaves the unit alive with a small amount of health.

**Comment by Garanas** [comment]
I wasn't even aware this indicator existed. I'll look into it.
