### ISSUE TITLE
Unknown sim freeze

### ISSUE THREAD

**Issue by Sheeo** [FAForever/fa#348]
Replay file [here](https://dl.dropboxusercontent.com/u/6523304/2961622-UndeadProphet.fafreplay)

**Comment by Crotalus** [comment]
EXCEPTION_ACCESS_VIOLATION (0xc0000005) at address 0x0047a820
    attempted to write memory at 0x00000000

Program : C:\ProgramData\FAForever\bin\ForgedAlliance.exe
Cmd line arguments : /replay C:/ProgramData/FAForever/cache/temp.scfareplay /init init_faf.lua /nobugreport /log "C:\ProgramData\FAForever\logs\replay.log" /replayid 2961622

Callstack:
	Unknown symbol (address 0x0047a820)
	Unknown symbol (address 0x0041d34d)
	Unknown symbol (address 0x7562653f)
	Unknown symbol (address 0x7562653f)
	Unknown symbol (address 0x1f6040f7)
	Unknown symbol (address 0x1fc298d7)
	Unknown symbol (address 0x1e2260bf)
	Unknown symbol (address 0x1f604fbb)
	Unknown symbol (address 0x1e2260bf)
	Unknown symbol (address 0x1dd5768b)
	Unknown symbol (address 0x1ed881bb)
	Unknown symbol (address 0x1e4a08bb)
	Unknown symbol (address 0x1ed881bb)
	Unknown symbol (address 0x1fc298d7)
	Unknown symbol (address 0x1f604da7)
	Unknown symbol (address 0x1e4a08bb)
	Unknown symbol (address 0x1f604da7)
	Unknown symbol (address 0x1e71e167)
	Unknown symbol (address 0x1eeab6fb)
	Unknown symbol (address 0x1eeab503)
	Unknown symbol (address 0x1eeab6fb)
	Unknown symbol (address 0x1e4a027f)
	Unknown symbol (address 0x1fa54557)
	Unknown symbol (address 0x1eeab503)
	Unknown symbol (address 0x1fa54557)
	Unknown symbol (address 0x1dd5768b)
	Unknown symbol (address 0x1e17abcb)
	Unknown symbol (address 0x1dc7ef13)
	Unknown symbol (address 0x1e17abcb)
	Unknown symbol (address 0x1e4a027f)
	Unknown symbol (address 0x1ed49e4f)
	Unknown symbol (address 0x1facf0a3)
	Unknown symbol (address 0x1ed49e4f)
	Unknown symbol (address 0x1dc7ef13)
	Unknown symbol (address 0x1facf53b)
	Unknown symbol (address 0x1f2c5ebf)
	Unknown symbol (address 0x1facf53b)
	Unknown symbol (address 0x1facf0a3)
	Unknown symbol (address 0x1e58aef7)
	Unknown symbol (address 0x1f2c5ebf)
	Unknown symbol (address 0x1e6e704f)
	Unknown symbol (address 0x1e58aef7)
	Unknown symbol (address 0x1e6e704f)

Last 100 lines of log...

info:   DamageFriendly=false,
info:   DamageRadius=0,
info:   DamageType="Normal"
info: }
info: *ERROR: THERE IS NO INSTIGATOR FOR DAMAGE ON THIS COLLISIONBEAM = \000{
info:   CollideFriendly=false,
info:   DamageAmount=0,
info:   DamageFriendly=false,
info:   DamageRadius=0,
info:   DamageType="Normal"
info: }
info: *ERROR: THERE IS NO INSTIGATOR FOR DAMAGE ON THIS COLLISIONBEAM = \000{
info:   CollideFriendly=false,
info:   DamageAmount=0,
info:   DamageFriendly=false,
info:   DamageRadius=0,
info:   DamageType="Normal"
info: }
info: *ERROR: THERE IS NO INSTIGATOR FOR DAMAGE ON THIS COLLISIONBEAM = \000{
info:   CollideFriendly=false,
info:   DamageAmount=0,
info:   DamageFriendly=false,
info:   DamageRadius=0,
info:   DamageType="Normal"
info: }
info: *ERROR: THERE IS NO INSTIGATOR FOR DAMAGE ON THIS COLLISIONBEAM = \000{
info:   CollideFriendly=false,
info:   DamageAmount=0,
info:   DamageFriendly=false,
info:   DamageRadius=0,
info:   DamageType="Normal"
info: }
info: *ERROR: THERE IS NO INSTIGATOR FOR DAMAGE ON THIS COLLISIONBEAM = \000{
info:   CollideFriendly=false,
info:   DamageAmount=0,
info:   DamageFriendly=false,
info:   DamageRadius=0,
info:   DamageType="Normal"
info: }
info: *ERROR: THERE IS NO INSTIGATOR FOR DAMAGE ON THIS COLLISIONBEAM = \000{
info:   CollideFriendly=false,
info:   DamageAmount=0,
info:   DamageFriendly=false,
info:   DamageRadius=0,
info:   DamageType="Normal"
info: }
info: *ERROR: THERE IS NO INSTIGATOR FOR DAMAGE ON THIS COLLISIONBEAM = \000{
info:   CollideFriendly=false,
info:   DamageAmount=0,
info:   DamageFriendly=false,
info:   DamageRadius=0,
info:   DamageType="Normal"
info: }
info: *ERROR: THERE IS NO INSTIGATOR FOR DAMAGE ON THIS COLLISIONBEAM = \000{
info:   CollideFriendly=false,
info:   DamageAmount=0,
info:   DamageFriendly=false,
info:   DamageRadius=0,
info:   DamageType="Normal"
info: }
info: *ERROR: THERE IS NO INSTIGATOR FOR DAMAGE ON THIS COLLISIONBEAM = \000{
info:   CollideFriendly=false,
info:   DamageAmount=0,
info:   DamageFriendly=false,
info:   DamageRadius=0,
info:   DamageType="Normal"
info: }
info: *ERROR: THERE IS NO INSTIGATOR FOR DAMAGE ON THIS COLLISIONBEAM = \000{
info:   CollideFriendly=false,
info:   DamageAmount=0,
info:   DamageFriendly=false,
info:   DamageRadius=0,
info:   DamageType="Normal"
info: }
info: *ERROR: THERE IS NO INSTIGATOR FOR DAMAGE ON THIS COLLISIONBEAM = \000{
info:   CollideFriendly=false,
info:   DamageAmount=0,
info:   DamageFriendly=false,
info:   DamageRadius=0,
info:   DamageType="Normal"
info: }
info: *ERROR: THERE IS NO INSTIGATOR FOR DAMAGE ON THIS COLLISIONBEAM = \000{
info:   CollideFriendly=false,
info:   DamageAmount=0,
info:   DamageFriendly=false,
info:   DamageRadius=0,
info:   DamageType="Normal"
info: }
info: *ERROR: THERE IS NO INSTIGATOR FOR DAMAGE ON THIS COLLISIONBEAM = \000{
info:   CollideFriendly=false,
info:   DamageAmount=0,
info:   DamageFriendly=false,
info:   DamageRadius=0,
info:   DamageType="Normal"
info: }
debug: Loading module '\000/units/ura0401/ura0401_script.lua\000'
debug: Loading module '\000/units/uab5102/uab5102_script.lua\000'
warning: Error running lua script: Invalid army -1. (Use a 1-based index)
         stack traceback:
         	[C]: in function `IsAlly'
         	...ogramdata\faforever\gamedata\lua.nx2\lua\simping.lua(157): in function <...ogramdata\faforever\gamedata\lua.nx2\lua\simping.lua:155>
debug: Loading module '\000/units/zrb9502/zrb9502_script.lua\000'
debug: Loading module '\000/lua/ui/dialogs/console.lua\000'

**Comment by Crotalus** [comment]
I've analyzed the replay, the commands for the last tick are from player "Looper" (funny coincidence) with 4 ProcessInfoPair('SetRepeatQueue', true). I guess for his 4 factories. 

Can't see that his factories are in an assist loop though so still a bit weird.
