### ISSUE TITLE
Select/Add nearest idle engineers options

### ISSUE THREAD

**Issue by Sutrinc** [FAForever/fa#3482]
Hi!!!

A handy feature has been added recently. Select and add the nearest free engineer to the group. This is an awesome feature.

![1](https://user-images.githubusercontent.com/92538938/137360620-9c313d2d-32ba-49b0-92a6-0dc2163b0d47.png)

But there is a significant drawback.
The function adds an engineer of any level to the group. It is very uncomfortable.
I propose to change the work of the panel of engineers.
If you click on an engineer of the first level, then the nearest engineers of the first level are added to the group.
If T2, then T3.
etc.

![2](https://user-images.githubusercontent.com/92538938/137360674-c0a8de96-d85a-4b41-8988-26ecb023d20e.png)

I think it won't be very difficult.
This will be an awesome feature. Will greatly simplify construction management.

**Comment by Sutrinc** [comment]
the distance from the center of the screen to the engineer can be used.

this is much better than now. now the panel is generally useless.

**Comment by Sutrinc** [comment]
you need to paste code like this. for t3


but this piece doesn't work. and I do not know why.

```
local allIdleEngineerst3={}
for _, unit in allIdleEngineers do
	if unit:IsInCategory("TECH3") then
		table.insert(allIdleEngineerst3,unit);
	end
end
-- Check if current selection contains only idle engineers
local idleEngineers = allIdleEngineerst3
```

and change this 
local mousePos = GetMouseWorldPos()
to center of screen. i cant

```
function AddNearestIdleEngineersSeq_my()
    local allIdleEngineers = GetIdleEngineers() or {}
    local currentSelection = GetSelectedUnits() or {}
	
	local allIdleEngineerst3={}
	for _, unit in allIdleEngineers do
		if unit:IsInCategory("TECH3") then
			table.insert(allIdleEngineerst3,unit);
		end
	end
    -- Check if current selection contains only idle engineers
    local idleEngineers = allIdleEngineerst3
    for _, unit in currentSelection do
        local key = table.find(idleEngineers, unit)
        if key then
            table.remove(idleEngineers, key)
        else
            -- Not an idle engineer, clear selection
            SelectUnits(nil)
            currentSelection = {}
            idleEngineers = allIdleEngineerst3
            break
        end
    end
    if table.empty(idleEngineers) then
        return
    end
    -- Get nearest in list of unselected, idle
    local mousePos = GetMouseWorldPos()
    local nearestIndex = 1
    local nearestDist = GetDistanceBetweenTwoVectors(mousePos, idleEngineers[nearestIndex]:GetPosition())
    for index, unit in idleEngineers do
        local dist = GetDistanceBetweenTwoVectors(mousePos, unit:GetPosition())
        if dist < nearestDist then
            nearestIndex = index
            nearestDist = dist
        end
    end
    AddSelectUnits({idleEngineers[nearestIndex]})
end
```

**Comment by Garanas** [comment]
I am closing this feature request - there has not been sufficient positive responses for the investment.

**Comment by Sutrinc** [comment]
all you had to do was copy the code. Wouldn't get any worse for sure.
you are very strange people.
the game will remain what it is.
