### ISSUE TITLE
Mod units with RULEUCC_Teleport unbuildable if they don't define bp.General.TeleportDelay

### ISSUE THREAD

**Issue by The-Balthazar** [FAForever/fa#3485]
No fallback value for bp.General.TeleportDelay at:
https://github.com/FAForever/fa/blob/7542596ea1c16be28615fdc40cc9bf9c8bb5481a/lua/ui/game/unitviewDetail.lua#L414

**Comment by KionX** [comment]
If there is no parameter, it should not be displayed.
