### ISSUE TITLE
Strange format for teleport ability

### ISSUE THREAD

**Issue by Garanas** [FAForever/fa#3488]
![image](https://user-images.githubusercontent.com/15778155/137622369-9cd0d971-95ba-4679-9282-c04ba437fcec.png)

Not sure where it comes from or what it is supposed to be - but in the list of abilities there is 'ability_teleport' which appears to be out of place. You can find it for the Seraphim Sonar SSS0305 introduced by the Brewlan mod, or an upgraded commander. Branch from the latest develop when you use the sonar to experiment with.

**Comment by KionX** [comment]
Brewlan mod in Vault outdated.
