### ISSUE TITLE
Refactor /modules/ away

### ISSUE THREAD

**Issue by Sheeo** [FAForever/fa#349]
This generic directory introduced in FAF is confusing, since it contains both ui and sim code.

We should seperate the files residing in here into either `/lua/ui` or `/lua/sim`, or perhaps better yet, to avoid future confusion with core game files, create `/faf/ui` and `/faf/sim`.

**Comment by aeoncleanse** [comment]
Well any existing GPG files, the structure there has to stay the same, right? I think we should just put any new files in the appropriate existing area, be it sim or ui, but call any unique FAF-added lua files FAF_filename.lua

**Comment by aeoncleanse** [comment]
I'm going to flag this for 3664 since it's not too tough to do. We'll pull the files into /faf/ui and /faf/sim.
