### ISSUE TITLE
Salvation Adjacency bugged?

### ISSUE THREAD

**Issue by aeoncleanse** [FAForever/fa#350]
http://forums.faforever.com/forums/viewtopic.php?f=3&t=9162&p=90558#p90558

**Comment by Sheeo** [comment]
Moving this to target 3642 since we only have a partial fix.

**Comment by aeoncleanse** [comment]
This issue is fully fixed, just that fixing it revealed a different, related problem. I think this should be merged into 3641, as the energy bar thing is not gameplay-affecting to any real degree, and doesn't matter compared to making the full surround adjacency work instead of nerfing ROF.

**Comment by aeoncleanse** [comment]
OK, I cherry picked the stuff from #352 into my test branch, and can confirm it's all working very nicely.
