### ISSUE TITLE
Map preview bug

### ISSUE THREAD

**Issue by Xinnony** [FAForever/fa#351]
I not have a crash, just warning

info: Pausing background task "Map loader /maps/scmp_019_3v3.v0003/scmp_019_3v3.scmap"
info: Background task "Map loader /maps/scmp_019_3v3.v0003/scmp_019_3v3.scmap" paused.
info: Starting background task "Map loader /maps/x1mp_014/x1mp_014.scmap"
info: Aborting background task "Map loader /maps/scmp_019/scmp_019.scmap"
info: Background task "Map loader /maps/x1mp_014/x1mp_014.scmap" running.
warning: Error in file /lua/RuleInit.lua : Unknown exception
debug: MEM: -31 bytes RULE
info: Background task "Map loader /maps/scmp_019/scmp_019.scmap" aborted.
info: Active game mods for blueprint loading: \000{ }
info: Loading blueprints...
warning: Error running OnKeySelect script in CScriptObject at 11e65580: Unable to find file /maps/SCMP_015.v0001/SCMP_015_save.lua
         stack traceback:
         	[C]: in function `doscript'
         	... forged alliance\gamedata\lua.scd\lua\ui\maputil.lua(125): in function `GetStartPositions'
         	...nxt\lua\ui\dialogs\mapselect.lua(205): in function <...nxt\lua\ui\dialogs\mapselect.lua:191>
         	...nxt\lua\ui\dialogs\mapselect.lua(495): in function `PreloadMap'
         	...nxt\lua\ui\dialogs\mapselect.lua(511): in function <...nxt\lua\ui\dialogs\mapselect.lua:509>

**Comment by aeoncleanse** [comment]
Have you checked that you have that map? Most likely cause of this is that the map is corrupted.

**Comment by Xinnony** [comment]
SCMP_015.v0001 is official no ?

**Comment by Sheeo** [comment]
Maps suffixed by name with the versioning scheme cannot be the official ones, since GPG did not use this versioning.

The map `SCMP_015.v0001` is a community-uploaded version of fields of isis, called "FoI Big".

**Comment by Xinnony** [comment]
Ok :)

Need add check for prevent a Warning if map corrupted.

**Comment by aeoncleanse** [comment]
Why would you not wish to be warned about a corrupted map? That's the point of it no? ;)

**Comment by Sheeo** [comment]
Yes, ideally though, we catch these errors earlier in our toolchain.

It should not be possible to upload a map with garbage data.

**Comment by Xinnony** [comment]
Yes exact

**Comment by Xinnony** [comment]
"has dug" label ?

**Comment by ChrisKitching** [comment]
We probably also want to show the user a popup or something if the map is
broken, instead of just printing a warning they almost certainly won't see.

**Comment by Xinnony** [comment]
Exact, because you cant know if the map is broken and if you launch you get a wonderful desync somtime :)
