### ISSUE TITLE
Problems with merge in my mode

### ISSUE THREAD

**Issue by Ledmal** [FAForever/fa#3510]
Hi, I need help. the mod that worked yesterday "New SupCom Annihilation" after the faf update, the merge of brmt3ava and brnt3doomsday units stopped working. Merging the remaining units works correctly. What could be the problem ? File for Merge at \mods\New SupCom Annihilation\lua\Merge.bp

![Merge](https://user-images.githubusercontent.com/93288492/139139424-ff2eb3b0-cbe1-4a80-92ba-4976624b7569.jpg)

**Comment by Ledmal** [comment]
first of all, I asked Balthazar a question, he sent it here to the forum))

**Comment by KionX** [comment]
Try downloading and testing different versions of the game from github.
