### ISSUE TITLE
Help with script

### ISSUE THREAD

**Issue by Sutrinc** [FAForever/fa#3515]
Hi All

how to make the condition that the unit belongs to? 

u:IsInCategory("Quantum_Gateway")
u:IsInCategory("EXP")

dont work.

**Comment by KionX** [comment]
not table.empty(EntityCategoryFilterDown(categories.GATE, units))
not table.empty(EntityCategoryFilterDown(categories.EXPERIMENTAL, units))

**Comment by Sutrinc** [comment]
thank you very much.

but this dont work to.
if unit:IsInCategory("SUBCOMMANDER")  then

and smd name smd?

i try change mod.
maybe you can see everything right here. 

```
if (not au:IsDead()) then
			if ((au:IsInCategory("ENGINEER")) and engineersOverlay and not(au:IsInCategory("COMMAND")) and not(au:IsInCategory("SUBCOMMANDER")) and not(au:IsInCategory("EXP")))then
				UpdateOverlayEngies(au)
				elseif ((au:IsInCategory("FACTORY")) and factoriesOverlay and not (au:IsInCategory("Quantum_Gateway"))and not(au:IsInCategory("EXP")) ) then
				UpdateOverlayFactories(au)
				elseif ((au:IsInCategory("SUBCOMMANDER")) and supportCommanderOverlay) then
				UpdateOverlaySupportCom(au)
				elseif ((au:IsInCategory("SILO")) and tacticalNukesOverlay) then
				UpdateOverlaySilos(au)
				elseif ((au:IsInCategory("MASSEXTRACTION")) and (au:IsInCategory("STRUCTURE")) and massExtractorsOverlay) then
				UpdateOverlayMex(au)
			end
		end
```

**Comment by KionX** [comment]
au:IsInCategory('GATE')
au:IsInCategory('EXPERIMENTAL')

**Comment by Garanas** [comment]
This repository is not the place for these mod related questions: please go to the FAF Discord (https://discord.gg/jj9yGUP) and give yourself the modder role in #role-selection. Then the #modding-general channel will be available.

And please inform them of the type of mod (ui / sim).
