### ISSUE TITLE
Share unit cap with allies

### ISSUE THREAD

**Issue by BlackYps** [FAForever/fa#3524]
Shared unit cap should be the default in the autolobby file. Especially for the 4v4 matchmakers this will be important, because at the moment unit cap isn't shared.
Duplicate of #3244 
Also, do we want 1500 unit cap on more than just 1v1?

**Comment by Garanas** [comment]
Is there a reason we're not using https://github.com/FAForever/fa/pull/3385 for this?

**Comment by BlackYps** [comment]
I mean, technically we could, but we would want it for all queues anyway, so it makes sense to put it in the defaults.

**Comment by Garanas** [comment]
I'll adjust accordingly. If I change the autolobby.lua it shouldn't affect typical games or am I mistaken here?

**Comment by BlackYps** [comment]
From the name I would guess that autolobby.lua is only for automatches and lobby.lua is for everything else. But I am no expert in engine/lua stuff.

**Comment by MrRowey** [comment]
With the 4v4 Matchmaker the autolobby by default has Fullshare how are you going to define the none full share playlists as I'm pretty sure I saw a 4v4 with and without full share @BlackYps

**Comment by BlackYps** [comment]
The server can send custom options per queue that override the settings in the autolobby file. However if literally every queue should use a specific option it makes the most sense to define it there instead of sending it by the server for every queue.

**Comment by MrRowey** [comment]
Ahh ok so by setting the default in their is one less thing your having to overwrite form the server
