### ISSUE TITLE
Tanks, Fatboy tracks animations.

### ISSUE THREAD

**Issue by ChosenOneV13** [FAForever/fa#3529]
The animations of tracked vehicle is slowing down during the match until it completely stops. 
how to reproduce:
Play game with many units, during mid/lategame track animations will start to degrade eventually stop to be animated at all.

**Comment by ChosenOneV13** [comment]
Could it be just replaced? Like Monkeyking and vehicles with legs do not suffer from this. Could be new elements just replace the tracks and work on code like animated legs?

**Comment by 4z0t** [comment]
I've seen some stuff dedicated to trucks, closing?

**Comment by ChosenOneV13** [comment]
> I've seen some stuff dedicated to trucks, closing?

Can U give some link? I've been quite away from FAF recently.

**Comment by Garanas** [comment]
See also: https://github.com/FAForever/fa/pull/4640

It has gotten better, but not to the degree where it works flawlessly. Closing regardless, because we're not removing all the tracks
