### ISSUE TITLE
disable hive assist after it was given to another player

### ISSUE THREAD

**Issue by spooky** [FAForever/fa#353]
Issue came from here:
http://forums.faforever.com/forums/viewtopic.php?f=42&t=9135&start=20

In short - when hives are given over to another player they continue assisting whatever was assisted before the transfer, making them a perfect tool to screw an allies eco/spam/build.
These should behave like engies (and drones?) - when given over, they should be paused/disabled so that the assist is voluntary.

I'm a strong supporter of the idea - nothing as frustrating as the described situation - happened to me yesterday.

**Comment by Xinnony** [comment]
:+1:

**Comment by aeoncleanse** [comment]
This can be closed, should be working in 3641
