### ISSUE TITLE
Fix the draw bug 

### ISSUE THREAD

**Issue by Garanas** [FAForever/fa#3538]
An annoying bug that has been extensively worked on in the past. It happens when one commander CTRL + Ks and takes the other one with it. Depending on who did it first causes one to win over the other, while they both died and should have resulted in a draw.

**Comment by Hdt80bro** [comment]
Is this the one we were testing?

**Comment by Garanas** [comment]
Yes - this is the one. It is fixed now as far as I am aware. Closing this issue.
