### ISSUE TITLE
Integrate Advanced Reclaim Info 

### ISSUE THREAD

**Issue by Garanas** [FAForever/fa#3539]
A requirement for the optimizations of reclaim labels to function. The mod in question hard-hooks the inefficient function.

**Comment by HUSSAR-mtrela** [comment]
this issue looks like a duplicate of issue #1631 - Cluster reclaim labels

**Comment by 4z0t** [comment]
After refactoring of reclaim labels, do we even need it?

**Comment by Garanas** [comment]
People still want it 😄

**Comment by MrRowey** [comment]
This is different to Reclaim labels allows you at a quick glance to see the total mass visible on the screen

**Comment by MrRowey** [comment]
it been a while since this was removed san people are gotten used to being with out it
