### ISSUE TITLE
Window class TitleGroup scale 

### ISSUE THREAD

**Issue by 4z0t** [FAForever/fa#3540]
Scale Window TitleGroup on higher resolutions through LayoutHelpers (line 220):
self.TitleGroup.Height:Set(30)  --> LayoutHelpers.SetHeight(self.TitleGroup, 30)
[(https://github.com/FAForever/fa/blob/deploy/fafdevelop/lua/maui/window.lua)](url)

**Comment by Garanas** [comment]
Could you make this into a pull request?
