### ISSUE TITLE
Add clustering to economic overlay

### ISSUE THREAD

**Issue by Garanas** [FAForever/fa#3545]
Add clustering to the economic overlay - this would be better for performance and it allows you to identify clumps of activity more easily when zoomed out. This could piggy-back on the clustering algorithm for the reclaim labels once that is implemented.

![image](https://user-images.githubusercontent.com/15778155/141784445-9120a944-bfaa-473c-aab1-5fe9b04ef656.png)
_an example of the economic overlay_

 - [ ] Add ui scaling support 
 - [ ] Add clustering support

**Comment by 4z0t** [comment]
It is an engine provided UI, not possible to change the behaviour. Closing?
