### ISSUE TITLE
Template spacing problem that can result in missing alternating wall-sized structures when a template is created with a combination of wall-sized and larger structures

### ISSUE THREAD

**Issue by Emperor-Penguin1** [FAForever/fa#3549]
When a template is made and it includes t1 pd/wall-sized structures and larger structures, the t1 pd/wall-sized structures get spaced within the template so that alternating ones are seemingly not in the template when they should be.  For example, in this image, you can see a bunch of walls and an SMD on the left and the result on the right when those structures are saved to a template and then placed.
![image](https://user-images.githubusercontent.com/72904368/142636743-4a2ef5be-913d-4434-b7d1-a2a11a09aab5.png)
To reproduce, save a template with densely placed walls or t1 pd and an SMD and save it to a template, then place the template.

**Comment by Garanas** [comment]
I'm glad that I was wrong 😄
