### ISSUE TITLE
ACU Chained Upgrade Assistance - Consumption Bug

### ISSUE THREAD

**Issue by ChessBerry** [FAForever/fa#3592]
**Describe the bug**
If you upgrade your com from t1 straight to t3, some of the engies assisting it wont update their mass and energy spent after the t2 upgrade is done, instead staying at the (higher) t2 upgrade values.

If you pause and unpause the engies, their spending is reset to the normal values for assisting a com upgrading to t3.

The same happens for other chained upgrades. E.g. T2 into shield is bugged in a similar way.

The shown spending is not just a visual bug, it actually drains your eco by the amount shown. 
I didn't test if the 2nd com upgrade actually gets finished faster if the engies are spending more mass/energy.

I was not able to make the bug appear for engies assisting a factory, or anything else, but I didn't exhaustively test it either.

The bug seems to only be in the current FAF Develop, not in the main FAF version of of the game, or at least I wasn't able to find it after a couple tries

**To Reproduce**

Attached is a short clip demonstrating the above from 15869193 (reproduction is super easy though). 

https://user-images.githubusercontent.com/90977374/145178735-e3a4d93b-8a5e-4bf2-927c-482b893d6bb4.mp4

Watch the energy bar in the top left before and after I unpause the engies. The spent energy changes from 648 to 497. 
You can even see which engies failed to update their spending by hovering your mouse over them. Further pausing doesn't seem to affect consumption further (as normally expected).

**Expected behavior**
The spending of engies assisting an ACU shouldn't depend on previous com upgrades they assisted with, and shouldn't change after pausing and unpausing.

**Comment by Garanas** [comment]
This is likely related to #3447 .

**Comment by ChessBerry** [comment]
You can do some interesting stuff with this bug, e.g. getting teleporter on your ACU for only 1.2 million, instead of 1.5 million energy, by building the T2 upgrade first:
![Forged Alliance 08_12_2021 10_11_09 (3)](https://user-images.githubusercontent.com/90977374/145181835-7cb3452b-d42c-4a2e-9644-d79119b76eb1.png)
![Forged Alliance 08_12_2021 10_09_58 (3)](https://user-images.githubusercontent.com/90977374/145181866-a7a14146-86bc-44a9-88be-1257a110f0c1.png)
