### ISSUE TITLE
Factories assist rework

### ISSUE THREAD

**Issue by 4z0t** [FAForever/fa#3608]
Assisting is a good game mechanics saving time and APM, however it has some disadvantages caused by those cases: 
* 1. Upgrading factory accidentally ordered to assist another fac with lower tech level drops its upgrade progress.
* 2. Factory building unit and ordered to assist drops progress too.

**Comment by speed2CZ** [comment]
Easy fix, hold shift to queue up the assist command as you would queue up any other command.

**Comment by Garanas** [comment]
I am closing this issue - speed2 is right.

Next to that, if I am not mistaken then the exact change that is implied by an order (e.g., an assist / guard order in this case) is applied by the engine and we just get informed that it is going to happen (in commandmode.lua). We can not intercept it.
