### ISSUE TITLE
Asymmetrical weapons for no reason?

### ISSUE THREAD

**Issue by aeoncleanse** [FAForever/fa#363]
http://forums.faforever.com/forums/viewtopic.php?f=42&t=9173&p=90822#p90822

**Comment by aeoncleanse** [comment]
Tiny, tiny impacts, let's just 3641 this to get it out of the way

**Comment by Sheeo** [comment]
What [very strange behavior](http://forums.faforever.com/forums/viewtopic.php?f=42&t=9173&p=90822#p90822) did you observe when investigating this?

**Comment by aeoncleanse** [comment]
Just something odd about the Megalith's cannon ingame behaviour not corresponding to the numbers in quite the way I thought it should. It seemed to be reversed, flipped or something. What was clockwise/anticlockwise on one unit was the other on this. I've since learned that it is down to something in the model bones having been set up wrong. It has no consequence ingame, I just flipped the numbers around so that the game behaviour was how we want it.
