### ISSUE TITLE
Dialog to inform of base-giving in full share games

### ISSUE THREAD

**Issue by Sheeo** [FAForever/fa#3638]
Proxy-issue from Ninrai.

His description:

If a teammate dies in a full share game, create a popup info (similar to when a t4 finishes) to notify the player who received the dead ally's units / buildings about the additional base and units in order to avoid confusion/idle buildings and units.

**Comment by Garanas** [comment]
We can do that - what shape should it have? A pop up (that you must interact with) seems undesirable. Would a simple text message / whisper suffice?

**Comment by Sheeo** [comment]
Ninrai's comment

> I think in order to keep it simple, a simple pop up info like with the t4 for the one given the stuff would suffice. nothing with clicking. maybe it should look a little different from the t4, more popping. possibly with a different color (red?) to highlight the urgency for a reaction by the player

I'd add personally I think it should be configurable so experienced players can turn it off if they want :)

**Comment by Garanas** [comment]
Always a toggle 😄

**Comment by 4z0t** [comment]
I would suggest to do a User Sync info about units been given at all, for mod purposes )

**Comment by Garanas** [comment]
Can you clarify on that? To allow a mod to hook it?

**Comment by 4z0t** [comment]
There are no ways no determine whenever you were given a unit on UI level

**Comment by Garanas** [comment]
Ah, I see. What type of UI interaction / callback would you want here?

**Comment by 4z0t** [comment]
an if statement in `UserSync.lua` mb

**Comment by Garanas** [comment]
And then for each unit given, or for all units given at once?

**Comment by 4z0t** [comment]
A way which wont impact on performance, i think. 😁

**Comment by Garanas** [comment]
And do you want the unit IDs too? Or just a content: X gave Y Z units

**Comment by 4z0t** [comment]
The fact that units were given is enough, i think, but i would  appreciate if its possible to provide with  ids too 😊
