### ISSUE TITLE
Clear all newline characters before set game title

### ISSUE THREAD

**Issue by Marc-Spector** [FAForever/fa#3643]
Related to https://github.com/FAForever/downlords-faf-client/issues/2313

**Comment by Garanas** [comment]
I'm not sure if you can set new lines through the game. I tried this text:
```
    // compute water color
    float waterDepth = tex2Dproj(UtilitySamplerC, pixel.mTexWT * TerrainScale).g - 0.15;
    float4 water = tex1D(WaterRampSampler, waterDepth);
    albedo.rgb = lerp(albedo.rgb, water.rgb, water.a);

    return float4(albedo.rgb, 0.01f); //float4(albedo.rgb, 0.01f);
```
And it shows like this:
![image](https://user-images.githubusercontent.com/15778155/148641418-15a2425c-d9f7-4103-9996-c0c2fabf9c8a.png)

The only place I know of where you can change it is here:
![image](https://user-images.githubusercontent.com/15778155/148641432-911ebec3-65f1-4126-9c70-565f44b6406d.png)

What am I missing with his reproduction?
