### ISSUE TITLE
Ping in Lobby is wildly inaccurate, absolutely fine in game. 

### ISSUE THREAD

**Issue by james-lan** [FAForever/fa#3661]
**Describe the bug**
Lobby will show huge pings, like 1.6k, while in game the pings will all be good (<300 US/Russia US/ANZ) especially when there are few players.

Possibly Wine/Linux related?

**To Reproduce**
Open FAF game lobby, see all the green from pings. 

If not kicked for high ping, Game is fine in every game. (Occasional issues others have excluded and one where I messed up on a UI mod that made the UI not show.)

**Expected behavior**
Something *resembling* the in game ping. 

**Additional context**
This is under Kubuntu 21.10, I have tried clients 2021.11.0 to 2022.1.1 with the same results. Computer is a i7, and while it's a bit older (175-ish CPU test) it's still decent in games unless it's something like late survival.

Possibly something to do with buffer queuing? Maybe increasing the size for the pings could alleviate the issue? 

While it's possible it's an update to Wine/Linux, I find it unlikely. Wine for FA on the machine is a separate package which has not updated. There's nothing that would have affected it that I'm aware of from the usual security updates.

Let me know what logs might be helpful, or if there's anything anyone would like to test online, I can setup a session for debugging.

**Comment by Garanas** [comment]
I have not experienced this issue myself and I do not have Linux. The ping is managed by the engine, increasing the size of a ping is therefore not possible. Do you know other people experiencing these issues?

**Comment by james-lan** [comment]
As of the past few days it's gone away so I'm closing this. I'm guessing it was my ISP, because nothing has changed other than occasionally different faf-client versions to try to see if it could be a specific version.
