### ISSUE TITLE
Introduce range rings at mouse from Additional Camera Tools mod

### ISSUE THREAD

**Issue by Garanas** [FAForever/fa#3692]
**Describe the feature**
It allows you to render various range rings at your mouse location, useful to detect if a unit is in range for something at a given location.

**Screenshots**

![image](https://user-images.githubusercontent.com/15778155/157333480-07d14150-b350-413b-ba57-d50aa64f20b1.png)

**Additional context**

Mod is attached. Code appears to be inside `WorldView.lua`. The idea is that a user decal is generated at the mouse position that represents the various rings.

[additionalCameraStuff.zip](https://github.com/FAForever/fa/files/8209905/additionalCameraStuff.zip)

**Comment by MrRowey** [comment]
question dose this intergrated version scale with buildrange modes as the curent one dose

**Comment by Garanas** [comment]
It will once it is implemented

**Comment by MonkAlex** [comment]
Hello.
Now additionalCameraStuff not loaded as deprecated, but i not found, how to show build range over cursor.
It implemented in game?

**Comment by MrRowey** [comment]
@MonkAlex their is a new mod that dose the range ring called build range preview in the vault

**Comment by MonkAlex** [comment]
@MrRowey its counterintuitive when developers ban worked mod and don't implement mod features...
Build Range Preview work, thanks for answer.
