### ISSUE TITLE
mass gain chit??

### ISSUE THREAD

**Issue by Alex835465** [FAForever/fa#3708]
Hello
Id just open one single replay and saw that mass incom of player Mechmaster (1100) at 11:35 minute dont correspond wiht it must be i think
He has just 8 massextr t2 full storageing. In total 8x9=**72** mass per sec he must to take. +1 from Commander. But we see **90**. How it possible? No reclaiming at that moment. 
id 16582299
replay https://replay.faforever.com/16582299

screenshot - https://ibb.co/3MvWMD4

**Comment by 4z0t** [comment]
Please dont make issues like this here, use forum, and be more attentive, this guy had t3 mex.
