### ISSUE TITLE
Refactor weapon prioritization 

### ISSUE THREAD

**Issue by Garanas** [FAForever/fa#3758]
Description
-----------

When weapons are created their priorities are set in Lua code. With thanks to @Strogoo  with commit https://github.com/FAForever/fa/commit/5f44c11d0e806a103024a9fd6cc6807e822a788f some form of caching was already introduced.

But we can go further.

It is important to understand the context. The related functions are:
 - `/lua/sim/weapon.lua` - `SetWeaponPriorities`
 - `/lua/sim/weapon.lua` - `ParsePriorities`

There is more extensive logic related to the categories computations but they're irrelevant for this pull request. We will assume those are good.

The function `SetWeaponPriorities` is called every time a unit is created or when their priorities are changed. Depending on the last argument there are two execution paths:
 - if `priTable` is nil then we retrieve and set the default target priorities. 
 - if `priTable` is not nil then we set the priorities of that table and cache it accordingly.
 
We're interested in the first case when the `priTable` parameter is nil. By default the weapon priorities are set when the unit is created. That means that for every weapon a table called `priorityTable` is allocated, populated and then thrown away. As a few examples, this is what that table is for some units:

```
Unit ID: dal0310 (Aeon t3 Anti-shield unit)
Weapon ID: dal0310-1-MainGun
{ table: 21CC8848 
  userdata: EntityCategory at 1E9FBEF0 = EntityCategory at 0x1E9FBEF0,
  userdata: EntityCategory at 1E9FBF98 = EntityCategory at 0x1E9FBF98,
  userdata: EntityCategory at 1E9E5588 = EntityCategory at 0x1E9E5588,
  userdata: EntityCategory at 1E9FBA20 = EntityCategory at 0x1E9FBA20,
  userdata: EntityCategory at 1E9FB5C0 = EntityCategory at 0x1E9FB5C0,
  userdata: EntityCategory at 1E9FBD30 = EntityCategory at 0x1E9FBD30,
  userdata: EntityCategory at 1E9FBD68 = EntityCategory at 0x1E9FBD68
}

Unit ID: del0204 (UEF T2 Gattling Bot, e.g., Mongoose)
Weapon ID: del0204-1-GatlingCannon
{ table: 202DB208 
  userdata: EntityCategory at 1E9E5588 = EntityCategory at 0x1E9E5588,
  userdata: EntityCategory at 1E8F6C88 = EntityCategory at 0x1E8F6C88,
  userdata: EntityCategory at 1E8F6CC0 = EntityCategory at 0x1E8F6CC0,
  userdata: EntityCategory at 1E9FB400 = EntityCategory at 0x1E9FB400,
  userdata: EntityCategory at 1E9FB5C0 = EntityCategory at 0x1E9FB5C0,
  userdata: EntityCategory at 1E9FBD30 = EntityCategory at 0x1E9FBD30,
  userdata: EntityCategory at 1E9FBD68 = EntityCategory at 0x1E9FBD68
}
Unit ID: del0204 (UEF T2 Gattling Bot, e.g., Mongoose)
Weapon ID: del0204-2-Grenade
{ table: 202C9438 
  userdata: EntityCategory at 1E9E5588 = EntityCategory at 0x1E9E5588,
  userdata: EntityCategory at 1E9FB400 = EntityCategory at 0x1E9FB400,
  userdata: EntityCategory at 1E8F6CC0 = EntityCategory at 0x1E8F6CC0,
  userdata: EntityCategory at 1E8F6C88 = EntityCategory at 0x1E8F6C88,
  userdata: EntityCategory at 1E9FB5C0 = EntityCategory at 0x1E9FB5C0,
  userdata: EntityCategory at 1E9FBD30 = EntityCategory at 0x1E9FBD30,
  userdata: EntityCategory at 1E9FBD68 = EntityCategory at 0x1E9FBD68
}

Unit ID: ual0201 (Aeon T1 Light Tank, e.g. Aurora)
Weapon ID: ual0201-1-MainGun
{ table: 2156AC58 
  userdata: EntityCategory at 1E9E5588 = EntityCategory at 0x1E9E5588,
  userdata: EntityCategory at 1E9FB400 = EntityCategory at 0x1E9FB400,
  userdata: EntityCategory at 1E8F6CC0 = EntityCategory at 0x1E8F6CC0,
  userdata: EntityCategory at 1E8F6C88 = EntityCategory at 0x1E8F6C88,
  userdata: EntityCategory at 1E9FB5C0 = EntityCategory at 0x1E9FB5C0,
  userdata: EntityCategory at 1E9FBD30 = EntityCategory at 0x1E9FBD30,
  userdata: EntityCategory at 1E9FBD68 = EntityCategory at 0x1E9FBD68
}

Unit ID: urs0103 (Cybran T1 frigate, e.g. Trident)
Weapon ID: urs0103-1-ProtonCannon
{ table: 21778C58 
  userdata: EntityCategory at 1E9E5588 = EntityCategory at 0x1E9E5588,
  userdata: EntityCategory at 20434898 = EntityCategory at 0x20434898,
  userdata: EntityCategory at 1E9FBD30 = EntityCategory at 0x1E9FBD30,
  userdata: EntityCategory at 1E9FBD68 = EntityCategory at 0x1E9FBD68
}
Unit ID: urs0103 (Cybran T1 frigate, e.g. Trident)
Weapon ID: urs0103-2-AAGun
{ table: 21778938 
  userdata: EntityCategory at 1E9E5588 = EntityCategory at 0x1E9E5588,
  userdata: EntityCategory at 1E9FB630 = EntityCategory at 0x1E9FB630,
  userdata: EntityCategory at 1E9FB6A0 = EntityCategory at 0x1E9FB6A0,
  userdata: EntityCategory at 1E8F6048 = EntityCategory at 0x1E8F6048,
  userdata: EntityCategory at 1E9FB320 = EntityCategory at 0x1E9FB320,
  userdata: EntityCategory at 1E9FB390 = EntityCategory at 0x1E9FB390,
  userdata: EntityCategory at 1E9FB4A8 = EntityCategory at 0x1E9FB4A8,
  userdata: EntityCategory at 1E9FBD30 = EntityCategory at 0x1E9FBD30,
  userdata: EntityCategory at 1E9FBD68 = EntityCategory at 0x1E9FBD68
}
```

We can make a few observations by inspecting the code and the output:
 - The entries of the tables are cached and re-used, as an example the category stored at `0x1E9FBD30` appears multiple times in the output of various weapons.
 - The tables themselves are not cached, they are unique for each instance of a weapon.
 - The tables are of a reasonable size, ranging from four to nine elements in our example output. That means that internally they have four to sixteen elements allocated due to the resizing of the table internally.

Course of action
----------------

All these tables allocations put pressure on the garbage collector. That would be okay if they weren't created to be thrown away again. But they are 😞 . Therefore we'll try two approaches, of which one I'm not sure if it would work. That is up to us all to confirm that it does (not) work.

### Approach 1: One table to bind them all

We'll first try and re-use one single table. The reasoning for this is that we're bound by memory, therefore we should keep the number of allocated tables as low as possible. Therefore we'll introduce a table that we'll continuously populate and de-populate on demand. We'll do this in five steps:
 - We create a localized table in the outer scope and name it `RecycledPriTable`.
 - We create a local reference to `RecycledPriTable` instead of allocation a new table in `SetWeaponPriorities`.
 - We populate the table by keeping a separate counter, as shown in [the table insertion benchmarks](https://github.com/FAForever/fa/blob/deploy/fafdevelop/lua/benchmarking/benchmarks/table-insert.lua).
 - We feed the table to the engine function
 - After feeding it, we clean up the table by setting each entry to `nil`
 
Note that there's an invariant surrounding `RecycledPriTable` that we should not be broken at any point:
 - When start working with the table `RecycledPriTable` we assume that it is cleaned up
 - When we work with `RecycledPriTable` we assume that there's no yielding
 - When we are done working with `RecycledPriTable` we clean it up again

However: I am not entire confident if the engine accepts a manipulated table such as this one. In particular, whether it tries to process values that we previously set to nil. Initial tests show that it does, but they can only test so much. If this approach doesn't work, then we try again with the second approach.

### Approach 2: A table per weapon type

Instead of populating one common table, we cache the results of each weapon and re-use it whenever we find a new instance of the same weapon. We'll do this in ... steps:
 - We create a localized table in the outer scope and name it `DefaultPrioritiesByWeaponType`. 
 - When we set the default priorities of a weapon, we first check `DefaultPrioritiesByWeaponType` whether we've already done this in the past. We can use the `BlueprintId` of the weapon as introduced by https://github.com/FAForever/fa/pull/3589/files . We can access it using `self.Blueprint.BlueprintId`. 
- If this has been done in the past, re-use the cached results
- If this has not been done in the past, allocate a new table and populate it accordingly. Cache the results by using the weapon blueprint identifier.

This prevents re-allocation of these tables on a per weapon-type basis. Therefore when spawning in two frigates the priority tables should not only have the same content, but also the same memory reference. 

### Other changes

Whether or not we cached the priorities is checked each time:

```
        if not cachedPriorities then
            cachedPriorities = ParsePriorities()
        end
```

We can skip this checking by calling ParsePriorities in the outer scope of the weapon.

Test plan
---------

This issue should be resolved using one pull request. Start with the first approach- it has a significant preference over the second approach. Make sure to create a pull request regardless of whether it works. This allows us to discuss and review the proposed changes. If the first approach doesn't work in practice, then you can try the second approach.

The outcome of priorities table should be exactly the same as before. You can use this to test your implementation.

If you have any questions, please ask them in this issue or on [Discord](https://discord.gg/mXahVSKGVb) in the #game-repository channel. If you do not have write access to that channel you can give yourself the Tester role in the #role-selection channel. 

If you claim this issue then please claim it in the Github UI or state in a reply to this issue that you claimed it.

Learning goals
--------------
Feeling more comfortable with experimenting and making changes that may not work out. This type of workflow is fundamental to programming and your understanding of the context that you're programming in.

**Comment by LilJoe7k4** [comment]
Hello! I submitted PR #3845 for this issue, not sure how to claim an issue through the UI or if I even can, so just replying here to let you know I took a shot at this 😁
