### ISSUE TITLE
Improve player swapping as host

### ISSUE THREAD

**Issue by OCGDFS** [FAForever/fa#376]
The difference between number of selectable spots and the real spots on the map makes it unnecessarily complicated to switch players, pls restore that.

**Comment by ChrisKitching** [comment]
You mean that the dropdown with the "Move player to slot X" options now incorrectly has buttons for all slots, including ones that aren't available for this map?

Or something else..?

**Comment by Sheeo** [comment]
I don't believe this was part of the previous lobby either, and even with a dropdown with limited options it's still unnecessarily complicated to swap players.

I see an easy and a nice solution:

1. Add slot number to the slot list
2. Allow drag&drop of players between slots

**Comment by OCGDFS** [comment]
yes its the "move player to slot X" option. in the last version i had the same number of spots. now there are 12 slots not matter what map it is. Ill give u an example: if i host setons and i want to switch air positions, i know from the last version, that the two highest numbers are the air the air positions. But now, its wrong to switch position 7 to the highest number because it is 12 and there is no position 12 existent. i have to subtract the missing positions, and calculate the right slot to switch the player in. I can live with that, but i cant understand why u changed that.

**Comment by HotFog** [comment]
My request or suggestions : 1. slot numbers next to slot. Could prob be added to template.
Drag and drop is nice but the BEST way to do it would be to be able to drag player name onto map slot (visual drag and drop.)tthayt way you are dragging player onto the slot you want him to occupy without having to look at map, etc as often the slots do not refelect opposing player in name list.

**Comment by aeoncleanse** [comment]
Where do we stand on this? Is it fixed?

**Comment by Sheeo** [comment]
Negative.
