### ISSUE TITLE
Refactor `layouthelpers.lua`

### ISSUE THREAD

**Issue by Garanas** [FAForever/fa#3762]
Description
-----------

Usually when we talk about performance we are referring to the sim side of the equation as that is what matters most in practice. It would be a shame however to forget about the UI side, in particular if there is low hanging fruit. For this issue we limit ourselves to `/lua/maui/layouthelpers.lua`. 

Course of action
----------------

There are a lot of math operations used. We can scope them as an upvalue to prevent the `GETGLOBAL` and the `GETTABLE` calls. Add the locals at the top of the file and replace the calls accordingly.

Test plan
---------

This one is a bit difficult to test and therefore will be checked by reviewing the code changes. By all means, when starting the game there should be no errors related to these changes.

Learning goals
--------------

Feel more comfortable working with the repository and making changes that impact dozens of other files.

**Comment by 4z0t** [comment]
Basically `math.floor` must be replaced with local one  (upvalued function) and `:Set(...)` that sets function replaced with `:SetFunction(...)`

**Comment by Hdt80bro** [comment]
https://github.com/FAForever/fa/pull/3936#issue-1265083181
