### ISSUE TITLE
aeon t2 flak ual0205

### ISSUE THREAD

**Issue by MadMaxFAF** [FAForever/fa#3769]
![ual0205_og](https://user-images.githubusercontent.com/62246181/162030313-de5d504b-3a3e-4517-9f50-ee836aded32b.gif)

the effect and guns clipping need fixing

**Comment by Garanas** [comment]
This is fixed by https://github.com/FAForever/fa/pull/3761.

**Comment by MadMaxFAF** [comment]
#3761 doesn't fix the clipping tho

**Comment by speed2CZ** [comment]
Those effects are suppose to connect in the middle, where the projectile then flies off. Not follow the barrel.

**Comment by Garanas** [comment]
So that is what it is trying to do.
