### ISSUE TITLE
Spots cant be correctly taken by observer

### ISSUE THREAD

**Issue by OCGDFS** [FAForever/fa#377]
the spot by a kicked (or gone (?)) player can not be correctly taken by an observer.

**Comment by ChrisKitching** [comment]
What do you mean by "correctly"? What exactly happens (or doesn't happen)?

**Comment by OCGDFS** [comment]
its a really strange behaviour, if sone tries to switch from observer to player, his name disappears from obs-window and his name appears on the spot, but without flag or rating, and he cannot x or something. I can not start the game. At the moment i refresh the spot by adding an ai and remove it, that seems to help. This behaviour occurs since the update.

**Comment by ChrisKitching** [comment]
Hmm. Perhaps related to #322 .

**Comment by Sheeo** [comment]
From my observations this isn't always the case. It happens when there's a partial connection to the peer.

Somehow I think #322 is related.
