### ISSUE TITLE
set dead is depreciated 

### ISSUE THREAD

**Issue by MadMaxFAF** [FAForever/fa#3770]
WARNING: SetDead is deprecated: use unit.Dead = true instead.
WARNING: Source: nil
WARNING: Stacktrace:"stack traceback:\
WARNING:         d:\\documents_d\\fa-deploy-fafdevelop\\lua\\sim\\unit.lua(4499): in function <d:\\documents_d\\fa-deploy-fafdevelop\\lua\\sim\\unit.lua:4494>"
WARNING: CheckCanBeKilled is deprecated: use unit.CanBeKilled instead.
WARNING: Source: { table: 230CFDE8 
WARNING:   currentline=-1,
WARNING:   func=moho.entity_methods.Kill,
WARNING:   linedefined=-1,
WARNING:   name="Kill",
WARNING:   namewhat="method",
WARNING:   nups=0,
WARNING:   short_src="[C]",
WARNING:   source="=[C]",
WARNING:   what="C"
WARNING: }
WARNING: Stacktrace:"stack traceback:\
WARNING:         d:\\documents_d\\fa-deploy-fafdevelop\\lua\\sim\\unit.lua(4570): in function <d:\\documents_d\\fa-deploy-fafdevelop\\lua\\sim\\unit.lua:4565>\
WARNING:         [C]: in function `Kill'\
WARNING:         ...ocuments_d\\fa-deploy-fafdevelop\\lua\\selfdestruct.lua(22): in function `fn'\
WARNING:         ...ocuments_d\\fa-deploy-fafdevelop\\lua\\simcallbacks.lua(53): in function <...ocuments_d\\fa-deploy-fafdevelop\\lua\\simcallbacks.lua:50>"

this is the error im getting

**Comment by Garanas** [comment]
It is not an error - it is an warning. It is a reminder to future contributors that we have work to do. There are a lot of deprecated functions for various reasons. Some because they are inefficient. Others because they become redundant. Sadly we can never completely remove the function as that would hamper mod compatibility.
