### ISSUE TITLE
Change default coop difficulty to medium

### ISSUE THREAD

**Issue by BlackYps** [FAForever/fa#3778]
**Describe the feature**
The default coop difficulty (lobby option) is "hard", which is way too hard for a casual player that won't play super efficient. The hard difficulty seems to cater to pro players to give them a challenge, but hey are not the typical demographic of coop players. People regularly complain that they find the coop maps too hard.

**Solution**
Change the default difficulty to medium.

**Comment by Garanas** [comment]
Wrong repository I think - but I'll make it happen.

**Comment by speed2CZ** [comment]
Btw. medium difficulty won't show up in the leaderboards. Thats also why hard is the default

**Comment by BlackYps** [comment]
Then we should probably communicate that somewhere. Still, I think for the first try people would prefer medium difficulty

**Comment by speed2CZ** [comment]
Actually, is it possible to get some data on this, rather than guessing?

**Comment by MrRowey** [comment]
that interesting did not know that leaderboard only displayed based on the game being played on hard

**Comment by Garanas** [comment]
I think it is safe to say that the majority of players can not finish campaign missions on hard. In particular the new missions made by ShadowLord are really tough on hard - so tough that I require cheats myself to test it 😄 . 

@Sheikah45 would it be a big change to add text here:

![image](https://user-images.githubusercontent.com/15778155/162592731-b2f2d293-0225-4e0c-8e60-ed59b734d409.png)

That indicates when a game is valid for the leaderboard?

**Comment by Sheikah45** [comment]
That info would have to be sent from the server based on the game options as the in lobby options determine whether it is ranked or not

**Comment by Garanas** [comment]
I mean - a general text message below the leaderboards indicating that only games on hard difficult are part of the leaderboard.

**Comment by BlackYps** [comment]
> Actually, is it possible to get some data on this, rather than guessing?

Not sure what data you would want to see here. As Jip said, we know that most players are pretty bad and from my impression people generally play coop to chill rather than to have a sweaty tryhard session.

**Comment by speed2CZ** [comment]
> I mean - a general text message below the leaderboards indicating that only games on hard difficult are part of the leaderboard.

That solves one of the many options. Right now, you can say it counts only the default option, one of whish is the hard difficulty.

**Comment by speed2CZ** [comment]
> I think it is safe to say that the majority of players can not finish campaign missions on hard. In particular the new missions made by ShadowLord are really tough on hard - so tough that I require cheats myself to test it 😄 .
> 
> @Sheikah45 would it be a big change to add text here:
> 
> ![image](https://user-images.githubusercontent.com/15778155/162592731-b2f2d293-0225-4e0c-8e60-ed59b734d409.png)
> 
> That indicates when a game is valid for the leaderboard?

Yes, all custom missions are harder on hard, but the rest of the original missions really isn't. In the vanilla campaigns  there are sometimes reports of them being broken, cuz nothing happens, but it's only because there's a lot of time to build stuff on easier difficulties. And the times were set for the vanilla balance, which was much slower.

**Comment by BlackYps** [comment]
So your argument is that medium would be too easy?
If we were to set the default difficulty to medium, would that mean that the leaderboards would also change to listing medium games or is that defined somewhere else?

**Comment by Sheikah45** [comment]
The leaderboard requirements are set in the server
