### ISSUE TITLE
Cybran T3 Sub - Tac Missiles Bugged

### ISSUE THREAD

**Issue by Cyrris** [FAForever/fa#3802]
**Describe the bug**
Cybran T3 Sub's tactical missiles have a bug which prevents them from doing damage. They launch just fine but have an issue on impact.

While trying to investigate a new (probably mod-related) crash since the latest patch release, one of my test game log files became filled with the following error message. Before crashing, it produced this error 27,000+ times. 

`warning: Error running OnImpact script in Entity /projectiles/cifmissiletactical02/cifmissiletactical02_proj.bp at 81259180: ...cifmissiletactical02\cifmissiletactical02_script.lua(31): access to nonexistent global variable "radius"
         stack traceback:
         	[C]: in function 'error'
         	...alliance\gamedata\mohodata.scd\lua\system\config.lua(53): in function <...alliance\gamedata\mohodata.scd\lua\system\config.lua:52>
         	...cifmissiletactical02\cifmissiletactical02_script.lua(31): in function <...cifmissiletactical02\cifmissiletactical02_script.lua:30>`

Following the source code, I found the missile logic and offending "radius" variable related to Cybran strategic missile subs in /projectiles/CIFMissileTactical02/CIFMissileTactical02_Script.lua. I was then able to reproduce.

**To Reproduce**
Play a game where your Cybran "Plan B" missile subs are shooting their tactical missiles. Versus land targets they will appear to impact but do no damage. Versus sea targets the missiles will remain swirling above the surface instead of impacting.

**Expected behaviour**
The tactical missiles impact and explode, and my precious game logs aren't filled with error messages.

**Further Comments**
I ran a test game with no mods (aside from Resource Rich) where you can clearly see the missile behaviour. This game's replay and enormous 190 MB game log file are attached: [16864827-Cyrris.zip](https://github.com/FAForever/fa/files/8546453/16864827-Cyrris.zip)

**Comment by Garanas** [comment]
I'll make sure to include it in the fix of tonight - thank you for reporting it.
