### ISSUE TITLE
Migratory patterns of game.prefs

### ISSUE THREAD

**Issue by Sheeo** [FAForever/fa#381]
We need to deal with migrating game.prefs files for users, and most importantly with `lobby 2.6.1` we're loosing saved game options, causing the UI not to render any in the scrollable list.

**Comment by Sheeo** [comment]
As it turns out, the incompatibility mentioned for `2.6.1` may be a different issue. @ChrisKitching is investigating.

There is still a concern here, as we need to ensure a steam-version `game.prefs` file works with our lobby.

**Comment by ChrisKitching** [comment]
> we're loosing saved game options, causing the UI not to render any in the scrollable list.

This issue is resolved in #394.



> There is still a concern here, as we need to ensure a steam-version game.prefs file works with our lobby.

Yes, though the general approach should definitely be "start with nothing and write our stuff on first-run". Avoid relying on the existence of any keys ahead of time.
This is largely what we do so far: there have just been flaws in the execution.

**Comment by ChrisKitching** [comment]
> Yes, though the general approach should definitely be "start with nothing and write our stuff on first-run".

This was largely achieved with 75d84f68625bce2d480b6e0759068ba7179e9291.

**Comment by Sheeo** [comment]
:+1:
