### ISSUE TITLE
Add bug reporting instructions to patchnotes

### ISSUE THREAD

**Issue by MostLostNoob** [FAForever/fa#3812]
**Describe the feature**
My suggestion (or feature request) is to add bug reporting instructions to the the top of the patchnotes that popup from the lobby whenever a new game patch is released. I often see comments & discussions of issues/bugs in several different places such as aeolus or one of the channels on Discord, but there should be a set process for players to report any issues/bugs that they encounter for the development team to review & act upon. I think by adding detailed bug reporting instructions that there will be more & better communication between the players & the development team which will make patch updates & any subsequent hotfixes much easier to handle.

**Expected behavior**
What I envision is a clear set of instructions being provided to the players with a link to the appropriate forum thread &/or specific Discord channel that they should be using to report issues/bugs as well as what info is needed such as replay#, timestamp, details of what was happening when the issue/bug appeared, etc.. These instructions should be big & bold in center alignment underneath "What's new to FAF?" & above the beginning of the patchnotes.

**Screenshots**
![Patchnotes](https://user-images.githubusercontent.com/84600965/164971931-406f9e22-0e05-4a40-9e87-6b6ff6f9e71e.jpg)

**Additional context**
It would probably be a good idea to implement this or something similar for the FAF Develop game type so that feedback during testing will improve too.

**Comment by Garanas** [comment]
I'm in favor of adding this in - I'll make sure it is implemented for the next patch.

**Comment by Garanas** [comment]
@4z0t or @Penguin5 could I somehow persuade either of you to pick this up?

**Comment by Garanas** [comment]
The new changelog has a 'report a bug' button:
![image](https://user-images.githubusercontent.com/15778155/166121641-5181848f-d676-493e-b9ec-761cbb83e10c.png)

That links to this page: https://github.com/FAForever/fa/wiki/Reporting-a-bug

Which is at the moment empty, but I'll add some content there. Great suggestion.
