### ISSUE TITLE
Tempest animations are too fast

### ISSUE THREAD

**Issue by speed2CZ** [FAForever/fa#3821]
Both opening and sinking (when killed).

**Comment by Garanas** [comment]
No idea what causes this, any suggestions?

**Comment by speed2CZ** [comment]
Well the animations got updated, so I assume they got updated wrong?

**Comment by speed2CZ** [comment]
https://github.com/FAForever/fa/commit/2eaea3b36a53aca3de3c60f850f440d092822031 this one, it adds all animations, so it prolly changed
