### ISSUE TITLE
Invincible T3 Ghetto Gunship

### ISSUE THREAD

**Issue by Nizar89** [FAForever/fa#3829]
Hello all,

**Describe the bug**
At the end of a game, a T3 Ghetto Gunship surrounded by SAM, ASF and T1 Fighter did no loose a single HP

**To Reproduce**
Replay: https://replay.faforever.com/16903298
Start around 32min

**Additional context**
I do not think this was intentional.
Player thought it was because the lab destroyed all incoming fire, but it seems unlikely to me based on the absurd amount of fire aimed at it.

**Comment by Garanas** [comment]
I'm on it 😃

**Comment by Garanas** [comment]
Fixed with 3736.
