### ISSUE TITLE
Do not reclaim if the engi is in pausing mode

### ISSUE THREAD

**Issue by Marc-Spector** [FAForever/fa#3832]
The pause in my understanding is the suspension of any active action of a engi or construction for an indefinite time. Why does the engineer ignore the pause mode during the reclaim?

**Comment by Garanas** [comment]
Good question - it pauses construction and / or production. But it does not 'pause' other orders, such as movement, attacking or - reclaiming. Would it be desirable if it did so?

**Comment by Marc-Spector** [comment]
Yes, it is desirable. When I see that the mass is overflowing, and the engineers have a lot of orders to reclaim, I have no desire to give a stop order, and then again give orders to reclaim again.

**Comment by Garanas** [comment]
I'll try and make it work before the release of tomorrow 😄 .

**Comment by 4z0t** [comment]
I think it is an issue for balance team as well

**Comment by Garanas** [comment]
I think it is a feature that is broken - but let us ping @Tagada14

**Comment by Garanas** [comment]
@Strogoo / @KionX do you have an idea how to make this work?

**Comment by Strogoo** [comment]
Try to play with unit:SetBuildRate(). I'm not sure if it affects reclaim rate, have to test that. As I remember, there is a callback in sim.unit for pause/unpause where you can place all logic that is needed. So ideally engie has an active order, active reclaim animation but in fact reclaim is stopped.

**Comment by Tagada14** [comment]
The balance team is in favor of adding this feature
