### ISSUE TITLE
The pause button mysteriously appears in the middle of the game

### ISSUE THREAD

**Issue by ChrisKitching** [FAForever/fa#385]
See:
http://i.imgur.com/99OSXX7.png

No STR available.

**Comment by Crotalus** [comment]
This had something to do with random skin, right? I think we can close this then

**Comment by ChrisKitching** [comment]
Yes.

This was actually the pause button you expect to find in that position for the build UI persisting due to skin brokenness if you were using the defunct "random" skin.
