### ISSUE TITLE
SMD's are targeting but missing nuke's (1.5.3736)

### ISSUE THREAD

**Issue by slinkingant** [FAForever/fa#3854]
**Describe the bug**
While playing FAF-develop v1.5.3736, SMD's are not able to hit incoming nukes

**To Reproduce**
See replay's. Build a Nuke and try to shoot it down.

**Expected behavior**
Nukes being shot down by SMD's

**Screenshots**
![smdmisses](https://user-images.githubusercontent.com/12718976/167707440-5125b068-b600-4fdc-9ee3-9bea31238e84.png)

**Additional context**
Initial game: https://replay.faforever.com/17009268 ( 4 vs 2 AI), 1st nuke launches @ 33 minutes
Reproduced game: https://replay.faforever.com/17009285 (4 minute replay)

**Comment by Garanas** [comment]
Likely related to https://github.com/FAForever/fa/pull/3847 , I am on it 😄
