### ISSUE TITLE
Player swapping needs revamp

### ISSUE THREAD

**Issue by ChrisKitching** [FAForever/fa#386]
Swapping players is currently somewhat arduous, what with needing to know slot numbers in your head and so on.
As an added bonus, the recent patch regressed it to make it even more irritating.

A less irritating UI solution needs to be found, or the regression resolved, before the next release.
See also: #330, #376

**Comment by aeoncleanse** [comment]
So there's a closed PR in here, is it working? Can this be closed?

**Comment by aeoncleanse** [comment]
Massively improved since this was made, with slot numbers shown on minimap, as well as slot-click to swap and other ease-of-use features.
