### ISSUE TITLE
Active silos' adjacency bonuses don't refresh properly

### ISSUE THREAD

**Issue by Penguin5** [FAForever/fa#3864]
I tried looking into #3641  / #1843, but I made this new issue because they seem to mischaracterize the problem a bit.  In my testing, active silos (sml/smd/tml) don't gain or lose adjacency bonuses from new/destroyed pgens/etc until they start building a new missile (ie: they cancel the current missile and restart, or finish it and start building a new missile).  There may be other triggers that cause it to refresh that I did not test.  Regardless, they should refresh or otherwise be adjusted upon adjacent pgen/etc construction/destruction.

I tried tracing the issue, going from OnAdjacentTo in defaultunits.lua - > ApplyBuff in Buff.lua - > UpdateConsumptionValues in Unit.lua.  I tried adjusting the logic in UpdateConsumptionValues to properly handle self:IsUnitState('SiloBuildingAmmo'), and I had it calculate the appropriate energy/mass consumption, but when I tried doing self:SetProductionPerSecondEnergy(energy_rate) & self:SetProductionPerSecondMass(mass_rate), it seemed to add the rates I set rather than setting them to those values...  I also tried subtracting the old consumption rate as well, but that did not work either.  Maybe there is a weird workaround solution involving having the adjacency change trigger an automatic process that would store the progress of the missile, restart missile construction (which would theoretically adjust the consumption values), and adjust the new missile's progress to match where the old missile's progress was before this artificial 'refresh'.

**Comment by Garanas** [comment]
This is a known issue - there was an extremely extensive post on this somewhere. Maybe @Strogoo knows where it is

**Comment by MrRowey** [comment]
#1843
