### ISSUE TITLE
Offline saves of missions don't load correctly

### ISSUE THREAD

**Issue by speed2CZ** [FAForever/fa#3877]
Running the coop missions offline gives the advantage save and load the game later. Most people play online, but few still use it.
Now it's broken that when you load the save, the objective panel is missing and you see the normal skirmish score. Also the AI breaks with some errors and you can't continue the mission.

I did test it on the first aeon mission (Joust)
- start the game offline in skirmish mode, save/load

Some quick testing showed that it used to work on patch [3723](https://github.com/FAForever/fa/releases/tag/3723)
(this might not be the last working patch either)

I didn't have time to track down the exact commit that broke it.

**Comment by Garanas** [comment]
How did you test this exactly?

**Comment by speed2CZ** [comment]
- pick a patch of game repo with git
- start the FA.exe with the coop dev init (merge of faf dev and coop init files)
- select skirmish, pick mission, launch game, save/load

**Comment by Garanas** [comment]
I've looked at loading / saving of skirmish games (with AIs) - those appear to work fine. I'll look co-op later.

**Comment by Garanas** [comment]
The issue is in 9f5f4c36115c858c83022a82d2aee35a6e9aa29d, or https://github.com/FAForever/fa/pull/3502/files#diff-27beb4c4f820b8c51bd22d40ab65b26ead2766eec9d8422c7486f0d70dfbf84c
