### ISSUE TITLE
Consider filtering "system messages"

### ISSUE THREAD

**Issue by ChrisKitching** [FAForever/fa#388]
Do we want to consider resurrecting the duct-taped-to-death "filter system messages" feature from #276, or do we just want to reconsider what messages we actually print?
A notable change since that feature was implemented was that slots now show "Connecting..." while we're establishing a connection to the player. This makes "Connecting to X" and "Connection to X established" messages - which were responsible for much of the spam - redundant.
Without that spam, it's not clear that the feature serves a useful purpose, or are the remaining messages still considered too logspamful?

**Comment by Sheeo** [comment]
Personally I like having the auditlog, but I think we should consider getting it in for when we expand the amount of slots. In a busy 16-player lobby it could be relevant to hide logspam.

**Comment by MrRowey** [comment]
@Garanas This can be closed as I don't here any issues about the Connecting to X in the lobby chat for games as it allows to make sure you have established a connection and it been like that for literally years

**Comment by ChrisKitching** [comment]
> as it allows to make sure you have established a connection and it been like that for literally years

As I noted in the original post: that information is already shown in the slot UI (assuming nobody broke it in the intervening six years). Until your connection to the person is established, it says "connecting..." where their name is.

If it no longer works like that, the behaviour should definitely be restored, because it makes it much more obvious why the game cannot be started. Prior to the addition of this behaviour, if someone wasn't connected, you'd simply never see their ready-box as ticked. If their slot instead shows "Connecting", it's very obvious what's happening (in addition to avoiding logspam in the chat box, which is a secondary concern).

**Comment by Garanas** [comment]
Issue has run stale, I'm not sure what if what Chris describes is still functional. We'll be able to tackle this when we revamp the lobby and integrate Snake into the new version.
