### ISSUE TITLE
Mobile factories don't destroy unit they produce when they die

### ISSUE THREAD

**Issue by speed2CZ** [FAForever/fa#3886]
- spawn mobile factory
- start producing unit
- kill mobile factory

![ForgedAlliance_2022-05-24_13-09-23](https://user-images.githubusercontent.com/10947024/170021479-b5c0ebb6-2492-4049-9b1f-fd1bcd6b61cd.jpg)
![ForgedAlliance_2022-05-24_13-08-38](https://user-images.githubusercontent.com/10947024/170021484-f5a71cf3-ea8c-4647-ac1f-5e8eb41272de.jpg)

**Comment by Garanas** [comment]
I can't reproduce this - the units appear to be removed accordingly.

**Comment by speed2CZ** [comment]
I can reproduce it every time in current fafdevelop

**Comment by Garanas** [comment]
On FAF Develop, see replay: https://replay.faforever.com/17278778
https://user-images.githubusercontent.com/15778155/173329980-b584c956-2fa3-41c3-91ef-8a9b1a1a1320.mp4

Looking at the code the unit is not destroyed separately, but neither does that happen for non-mobile factories. What am I missing that I can't see the lingering health bar?
