### ISSUE TITLE
Shield miscalculations

### ISSUE THREAD

**Issue by Penguin5** [FAForever/fa#3888]
https://replay.faforever.com/17121095
It appears that at 13:14, a com with ~2200 hp fully under an active parashield with 100% shield strength and sufficient energy to maintain the shield, dies when 2 notha shots hit the shield bubble of the parashield.

![image](https://user-images.githubusercontent.com/72904368/170110398-54cf3930-f2a2-4f1f-9910-726274b1cd94.png)
![image](https://user-images.githubusercontent.com/72904368/170111058-c4c6049b-69a9-43da-8ae9-e886bcb9d902.png)

**Comment by Garanas** [comment]
Closing this issue as I consider it to be unfixable, neither from Lua or from an engine patch.
