### ISSUE TITLE
Disconnections are not handled cleanly by lobbyComm

### ISSUE THREAD

**Issue by ChrisKitching** [FAForever/fa#389]
Clients disconnecting don't always do so in a way that is properly detected by lobbyComm, leading to us simply timing out to them.
This rather awkward scenario leads to a variety of strange observable effects:
- Hosts abandoning lobbies sometimes lead to the "Connection to the host timed out" message instead of "Host abandoned lobby".
- Players who disconnect can appear to occupy space in games for a considerable duration after they've really been kicked.

An obvious, if inelegant, solution would be to implement our own explicit disconnection protocol atop the existing one, effectively insulating ourselves from potential bugs in lobbyComm. I'm open to alternative suggestions, but so far haven't been able to find a sane explanation for any of these other than "lobbyComm is stupid". Testing reveals that this behaviour is intermittent, so I'm inclined to claim this is a long-standing weirdness in lobbyComm's implementation rather than a more recent regression.

See also: #377, #378, #322

**Comment by Sheeo** [comment]
Closing #377 and #378 as duplicates of this. Tracking this as a final issue for lobby 2.6.1 here.
