### ISSUE TITLE
Cybran Sub Missles Bug

### ISSUE THREAD

**Issue by Sheikah45** [FAForever/fa#3902]
From Laissez-Fairy

**Describe the bug**
Sorry to bother you with this, but I am too lazy to go through the proper channels: Bug report: cybran sub-missiles currently deal no damage. Checked for static launcher, MML, and nuke sub, true in all cases. Also present in Develop, though I only checked with static launcher to confirm there

**Comment by Garanas** [comment]
I'll look at it.
