### ISSUE TITLE
Observers cannot open the chat window by pushing "enter"

### ISSUE THREAD

**Issue by ChrisKitching** [FAForever/fa#391]
Report from Kalvirox:
"You cannot open chat yourself as an observer, you have to wait until one of the players says something and then double click the message to bring up the chat menu."

**Comment by aeoncleanse** [comment]
This doesn't seem an issue, as Observers could open the chat previously, but not control it or send any messages.

**Comment by ChrisKitching** [comment]
See:
http://forums.faforever.com/forums//viewtopic.php?p=91625

**Comment by ChrisKitching** [comment]
Aren't observers supposed to be able to talk among themselves?

**Comment by VoRGoR** [comment]
Obs can talk to other obs, but are unable to open the chat window without using the people ingame as kalvirox describes.
