### ISSUE TITLE
Autobalance button icon is too big

### ISSUE THREAD

**Issue by speed2CZ** [FAForever/fa#3915]
If you look at the other buttons, they all have same size icons and then there is autobalance
![ForgedAlliance_2022-05-31_20-21-22](https://user-images.githubusercontent.com/10947024/171257820-af65bce8-64dc-473d-a013-ba38302a63d8.png)

**Comment by Garanas** [comment]
@Penguin5 could you pick this one up?

**Comment by MrRowey** [comment]
Fixed with #4731
