### ISSUE TITLE
EXCEPTION_ACCESS_VIOLATION (0xc0000005)

### ISSUE THREAD

**Issue by marvin4ward** [FAForever/fa#3953]
EXCEPTION_ACCESS_VIOLATION (0xc0000005) at address 0x00423190
    attempted to read memory at 0x3c3f7335

Program : C:\ProgramData\FAForever\bin\ForgedAlliance.exe
Cmd line arguments : /init init.lua /nobugreport /log C:\Users\user\AppData\Roaming\Forged Alliance Forever\logs\game_17279995.log /gpgnet 127.0.0.1:58979 /mean 892.581 /deviation 108.167 /savereplay gpgnet://127.0.0.1:58981/17279995/derKoMaNder.SCFAreplay /country RU /numgames 414 /numgames 414

Callstack:
	Unknown symbol (address 0x00423190)
	Unknown symbol (address 0x00801e43)

Last 100 lines of log...

info: Ui_SelectByCategory AIR HIGHALTAIR ANTIAIR 
info: UI_Lua import("/lua/keymap/smartSelection.lua").smartSelect("AIR HIGHALTAIR ANTIAIR -BOMBER -EXPERIMENTAL")
info: Ui_SelectByCategory AIR HIGHALTAIR ANTIAIR 
info: UI_Lua import("/lua/keymap/smartSelection.lua").smartSelect("AIR HIGHALTAIR ANTIAIR -BOMBER -EXPERIMENTAL")
info: CWldSession::DoBeat() unknown entity id (0x2ff00042) supplied in a pose update.
info: CWldSession::DoBeat() unknown entity id (0x2ff00041) supplied in a pose update.
info: CWldSession::DoBeat() unknown entity id (0x2ff001ad) supplied in a pose update.
info: CWldSession::DoBeat() unknown entity id (0x2ff0015c) supplied in a pose update.
info: Ui_SelectByCategory AIR HIGHALTAIR ANTIAIR 
info: UI_Lua import("/lua/keymap/smartSelection.lua").smartSelect("AIR HIGHALTAIR ANTIAIR -BOMBER -EXPERIMENTAL")
info: Ui_SelectByCategory AIR HIGHALTAIR ANTIAIR 
info: UI_Lua import("/lua/keymap/smartSelection.lua").smartSelect("AIR HIGHALTAIR ANTIAIR -BOMBER -EXPERIMENTAL")
debug: Current gametime: 00:31:30
info: Ui_SelectByCategory AIR HIGHALTAIR ANTIAIR 
info: UI_Lua import("/lua/keymap/smartSelection.lua").smartSelect("AIR HIGHALTAIR ANTIAIR -BOMBER -EXPERIMENTAL")
info: UI_Lua import("/lua/ui/game/orders.lua").SoftStop()
info: Ui_SelectByCategory AIR HIGHALTAIR ANTIAIR 
info: UI_Lua import("/lua/keymap/smartSelection.lua").smartSelect("AIR HIGHALTAIR ANTIAIR -BOMBER -EXPERIMENTAL")
debug: [uiutil.lua, function UIFile()] - Unable to find file:/textures/ui/seraphim/icons/units/unknown_icon.dds
debug: Current gametime: 00:32:00
info: UI_SelectByCategory +nearest COMMAND
info: UI_Lua import("/lua/keymap/misckeyactions.lua").ACUSelectCG()
info: Ui_SelectByCategory AIR HIGHALTAIR ANTIAIR 
info: UI_Lua import("/lua/keymap/smartSelection.lua").smartSelect("AIR HIGHALTAIR ANTIAIR -BOMBER -EXPERIMENTAL")
info: Ui_SelectByCategory AIR HIGHALTAIR ANTIAIR 
info: UI_Lua import("/lua/keymap/smartSelection.lua").smartSelect("AIR HIGHALTAIR ANTIAIR -BOMBER -EXPERIMENTAL")
info: StartCommandMode order RULEUCC_Patrol
debug: Current gametime: 00:32:30
info: UI_SelectByCategory +nearest COMMAND
info: UI_Lua import("/lua/keymap/misckeyactions.lua").ACUSelectCG()
warning: ACU kill detected. Rating for ranked games is now enforced.
info: Sending game result: 12 score 1
info: Hooked /lua/ui/game/gameresult.lua with /mods/supremescoreboard/hook/lua/ui/game/gameresult.lua
info: SSB >>> TRACE GameResults: result = score 1, armyID = 12, name = tamus
info: Sending game result: 9 defeat -10
info: SSB >>> TRACE GameResults: result = defeat -10, armyID = 9, name = mont1k
info: SSB >>> TRACE GameResults: mont1k has been defeated by tamus
info: SSB >>> TRACE AnnounceDeath mont1k  has been defeated by  tamus
info: UI_SelectByCategory +nearest COMMAND
info: UI_Lua import("/lua/keymap/misckeyactions.lua").ACUSelectCG()
info: SSB >>> TRACE OnBeat() player has died: mont1k
debug: Current gametime: 00:33:00
info: StartCommandMode order RULEUCC_Reclaim
info: UI_Lua import("/lua/ui/game/gamemain.lua").SmartReclaim()
info: CWldSession::DoBeat() unknown entity id (0x2ff012bd) supplied in a pose update.
info: CWldSession::DoBeat() unknown entity id (0x2ff012db) supplied in a pose update.
info: CWldSession::DoBeat() unknown entity id (0x2ff0172f) supplied in a pose update.
info: StartCommandMode order RULEUCC_Reclaim
info: UI_Lua import("/lua/ui/game/gamemain.lua").SmartReclaim()
info: UI_SelectByCategory +nearest COMMAND
info: UI_Lua import("/lua/keymap/misckeyactions.lua").ACUSelectCG()
debug: Current gametime: 00:33:30
info: Ui_SelectByCategory AIR HIGHALTAIR ANTIAIR 
info: UI_Lua import("/lua/keymap/smartSelection.lua").smartSelect("AIR HIGHALTAIR ANTIAIR -BOMBER -EXPERIMENTAL")
info: Ui_SelectByCategory AIR HIGHALTAIR ANTIAIR 
info: UI_Lua import("/lua/keymap/smartSelection.lua").smartSelect("AIR HIGHALTAIR ANTIAIR -BOMBER -EXPERIMENTAL")
info: StartCommandMode order RULEUCC_Patrol
info: StartCommandMode order RULEUCC_Patrol
info: Ui_SelectByCategory AIR HIGHALTAIR ANTIAIR 
info: UI_Lua import("/lua/keymap/smartSelection.lua").smartSelect("AIR HIGHALTAIR ANTIAIR -BOMBER -EXPERIMENTAL")
debug: Current gametime: 00:34:00
info: CWldSession::DoBeat() unknown entity id (0x2ff00681) supplied in a pose update.
info: Ui_SelectByCategory AIR HIGHALTAIR ANTIAIR 
info: UI_Lua import("/lua/keymap/smartSelection.lua").smartSelect("AIR HIGHALTAIR ANTIAIR -BOMBER -EXPERIMENTAL")
debug: Current gametime: 00:34:30
info: Ui_SelectByCategory AIR HIGHALTAIR ANTIAIR 
info: UI_Lua import("/lua/keymap/smartSelection.lua").smartSelect("AIR HIGHALTAIR ANTIAIR -BOMBER -EXPERIMENTAL")
info: Ui_SelectByCategory AIR HIGHALTAIR ANTIAIR 
info: UI_Lua import("/lua/keymap/smartSelection.lua").smartSelect("AIR HIGHALTAIR ANTIAIR -BOMBER -EXPERIMENTAL")
info: Ui_SelectByCategory AIR HIGHALTAIR ANTIAIR 
info: UI_Lua import("/lua/keymap/smartSelection.lua").smartSelect("AIR HIGHALTAIR ANTIAIR -BOMBER -EXPERIMENTAL")
debug: Current gametime: 00:35:00
debug: Current gametime: 00:35:30
info: Strat Icon Mod Error: updated strat icon required for: \000acuhighlight/icon_commander_generic
info: UI_Lua import("/lua/ui/game/confirmunitdestroy.lua").ConfirmUnitDestruction(true)
debug: Current gametime: 00:36:00
debug: Current gametime: 00:36:30
info: UI_SelectByCategory +nearest COMMAND
info: UI_Lua import("/lua/keymap/misckeyactions.lua").ACUSelectCG()
info: Ui_SelectByCategory AIR HIGHALTAIR ANTIAIR 
info: UI_Lua import("/lua/keymap/smartSelection.lua").smartSelect("AIR HIGHALTAIR ANTIAIR -BOMBER -EXPERIMENTAL")
debug: Current gametime: 00:37:00
info: Ui_SelectByCategory AIR HIGHALTAIR ANTIAIR 
info: UI_Lua import("/lua/keymap/smartSelection.lua").smartSelect("AIR HIGHALTAIR ANTIAIR -BOMBER -EXPERIMENTAL")
info: Ui_SelectByCategory AIR HIGHALTAIR ANTIAIR 
info: UI_Lua import("/lua/keymap/smartSelection.lua").smartSelect("AIR HIGHALTAIR ANTIAIR -BOMBER -EXPERIMENTAL")
info: Ui_SelectByCategory AIR HIGHALTAIR ANTIAIR 
info: UI_Lua import("/lua/keymap/smartSelection.lua").smartSelect("AIR HIGHALTAIR ANTIAIR -BOMBER -EXPERIMENTAL")
debug: Current gametime: 00:37:30
info: StartCommandMode order RULEUCC_Patrol
info: UI_Lua import("/lua/ui/game/orders.lua").CycleRetaliateStateUp()
info: Ui_SelectByCategory AIR HIGHALTAIR ANTIAIR 
info: UI_Lua import("/lua/keymap/smartSelection.lua").smartSelect("AIR HIGHALTAIR ANTIAIR -BOMBER -EXPERIMENTAL")
info: Ui_SelectByCategory AIR HIGHALTAIR ANTIAIR 
info: UI_Lua import("/lua/keymap/smartSelection.lua").smartSelect("AIR HIGHALTAIR ANTIAIR -BOMBER -EXPERIMENTAL")
info: CWldSession::DoBeat() unknown entity id (0x2ff002c5) supplied in a pose update.
debug: Current gametime: 00:38:00
info: Ui_SelectByCategory AIR HIGHALTAIR ANTIAIR 
info: UI_Lua import("/lua/keymap/smartSelection.lua").smartSelect("AIR HIGHALTAIR ANTIAIR -BOMBER -EXPERIMENTAL")
debug: Current gametime: 00:38:30

[game_17279995.log](https://github.com/FAForever/fa/files/8892324/game_17279995.log)

**Comment by MrRowey** [comment]
@marvin4ward Can you please provide a description to what happened when you got the error ?

**Comment by marvin4ward** [comment]
The game just hangs, nothing special happens during the match before the game hangs. Other playes, seems continue the match.

**Comment by KionX** [comment]
Here is the only successful solution to such a problem that I know of: https://github.com/FAForever/fa/issues/3900#issuecomment-1144910285

**Comment by marvin4ward** [comment]
dual Screen - could be the case. I liked that mode for more ways control the situation. 
Thank you for the hint.
