### ISSUE TITLE
Inconsistent transports Attachpoint bones

### ISSUE THREAD

**Issue by speed2CZ** [FAForever/fa#3957]
This bugs affects only AI, and currently the platoon AI for the units that aree to be transported can sometimes softlock because the AI is not able to load the units on the transports.

- I found a problem with at least T2 Aeon transport (uaa0104) and T3 UEF transport (xea0306)

**First some explanation of how transports work:**
Transport table in the bp determines how many T1 slots will T2 and T3 units take
```LUA
Transport = {
    AirClass = true,
    Class1Capacity = 12,  -- Num T1 units it can carry
    Class2AttachSize = 2, -- Class1Capacity / Class2AttachSize = Num T2 units it can carry (6 here)
    Class3AttachSize = 4, -- Class1Capacity / Class3AttachSize = Num T3 units it can carry (3 here)
    TransportClass = 10,
},
```
Transports have these 3 type of attach bones:
```LUA
Attachpoint_Lrg
Attachpoint_Med
Attachpoint
```
T3 units get attached to `Lrg` bone, T2 units to `Med` bone. Now this is combines with how many T1 bones they should take.
So when T3 unit is suppose to be loaded, it will also occupy 4 closest small attach bones (if one of the bones would be already occupied by T2 or T1 unit, then T3 unit can not be attached to this `Lrg` bone)

Now if we look at the bones structure of a working transport UEF T2:
![ForgedAlliance_2022-06-15_10-45-41](https://user-images.githubusercontent.com/10947024/173784582-cb11e22a-e997-43de-bd7d-b67974954184.jpg)
you can see that the `Lrg` bone always have 4 small bones close to it. Evenly spread out.

In comparison to Aeon T2 transport, which is one of the broken ones:
![ForgedAlliance_2022-06-15_10-50-13](https://user-images.githubusercontent.com/10947024/173785390-7f92c2df-563d-4068-b7cd-6a04aa7755b0.jpg)
The two `Lrg` bones on the left are fighting over the same 2 small bones. Cuz remember, it takes the 4 closest small bones.

So Aeon transport, despite of having 3 `Lrg` bones, can carry only 2 T3 units

Code that figures out for the AI how many units can be carried by a transport:
https://github.com/FAForever/fa/blob/deploy/fafdevelop/lua/AI/aiutilities.lua#L1259-L1278
```LUA
function GetNumTransportSlots(unit)
    local bones = {
        Large = 0,
        Medium = 0,
        Small = 0,
    }
    for i = 1, unit:GetBoneCount() do
        if unit:GetBoneName(i) ~= nil then
            if string.find(unit:GetBoneName(i), 'Attachpoint_Lrg') then
                bones.Large = bones.Large + 1
            elseif string.find(unit:GetBoneName(i), 'Attachpoint_Med') then
                bones.Medium = bones.Medium + 1
            elseif string.find(unit:GetBoneName(i), 'Attachpoint') then
                bones.Small = bones.Small + 1
            end
        end
    end

    return bones
end
```
This will find out that the Aeon T2 transport can carry 3 T3 units, even when it can carry only 2, because of the bone structure.

Then when the AI tries to load the units with this call
```LUA
IssueTransportLoad({T3_Unit_1, T3_Unit_2, T3_Unit_3}, {T2_Aeon_Transport})
```
It will not error out, but get stucked forever. The command is issued, but nothing happens.
The AI is waiting until all the units are in Idle state, indicating they got loaded into the transport, before moving out with the transports. But this never happens, because the loading command gets stucked.
![ForgedAlliance_2022-06-15_11-10-00](https://user-images.githubusercontent.com/10947024/173790014-d878c227-d1f8-42a2-8513-70cfa6b53f20.jpg)

My suggested solution is to move the bones in the transport in order for the `Lrg` and `Med` bones not be fighting over the same small bones.

**Comment by Garanas** [comment]
@MadMaxFAF could you pick this up? Seems like a small change that we can include in the release

**Comment by Garanas** [comment]
@speed2CZ if I am correct, then the solution is to move the large attachment bone slightly so that the four nearest small attachment bones are unique over all large attachment bones?

**Comment by Garanas** [comment]
@Sprouto this may interest you too, if you haven't already fixed it for LOUD

**Comment by speed2CZ** [comment]
Yes, it's for both Lrg and Med bones, just make sure they will never fight over the small bones.

**Comment by speed2CZ** [comment]
@MadMaxFAF and the Continental just needs bones cleansing, since it has
12 Lrg bones and 24 Med bones
while it should have just 6 / 12
![ForgedAlliance_2022-06-15_11-28-02](https://user-images.githubusercontent.com/10947024/173794268-8e6bfafd-5850-4ece-b6b4-8148679b5b9e.jpg)

**Comment by The-Balthazar** [comment]
The issue with the Continental is that `GetNumTransportSlots` doesn't take into account `Class3AttachSize` and `Class2AttachSize` from the bp. All you'd be doing by removing the extra bones is removing attach arrangement options, and breaking any mods that mess with the class attach limits.

Floor divide small by the class sizes and then take the smallest number out of the number of bones and that class limit.

For the Aeon one it's not the model, it's the unpack animation.

**Comment by The-Balthazar** [comment]
[UAA0104_Aopen01Fix.zip](https://github.com/FAForever/fa/files/8908404/UAA0104_Aopen01Fix.zip)

**Comment by MadMaxFAF** [comment]
@speed2CZ so what needs doing here if im reading this correctly i just need to make the bones the same as the t2 just times 2 or  do i need to do something else going off of what @The-Balthazar has said

**Comment by Garanas** [comment]
Add the file of Balthazar, I'll do the script part in the pull request you make.
