### ISSUE TITLE
Why are there more teams available to choose from than slots?

### ISSUE THREAD

**Issue by aeoncleanse** [FAForever/fa#398]
I think it may be including non-playable armies in the team count

**Comment by ChrisKitching** [comment]
The number of selectable teams is always exactly six (plus the "no team" team). 
Nothing clever is tried to cut it down to match up with slot count (and doing so seems like it'd be of limited value in any case. Extra complexity without really winning that much for the user)

**Comment by aeoncleanse** [comment]
Errrrm. And if I want to play a game with 7 teams? I can't? This system is dumb, available teams should equal available slots as determined by the map.
