### ISSUE TITLE
"Mercy" Guided Missile targeting issues

### ISSUE THREAD

**Issue by martinpost** [FAForever/fa#3982]
Mercys don´t always deploy when reaching target and fly over intended target, turn back and tray again to only fail again.

**To Reproduce**
Take some mercys and target com or sub com(possibly appears in other instances too but tested with them).

**Expected behavior**
When reaching intended target expect them to deploy, but they don´t.

**Additional context**
Test in sandbox https://replay.faforever.com/17334313 problematic behaviour in around 1:30
In game https://replay.faforever.com/17333872 in 8:20 mark

**Comment by MrRowey** [comment]
Issuse is Know

**Comment by Garanas** [comment]
Yeah, but I thought I fixed it. But apparently I did not.

**Comment by Garanas** [comment]
Fixed in the previous release, forgot to close
