### ISSUE TITLE
UI Shield issues

### ISSUE THREAD

**Issue by speed2CZ** [FAForever/fa#4001]
**Shield shows full when disabled**
![ForgedAlliance_2022-06-25_09-40-02](https://user-images.githubusercontent.com/10947024/175763858-6c55699f-dc60-4120-8de0-b40740d6d956.png)

**To Reproduce**
Turn off the unit shield in the UI

**Can't toggle shields on multiple different units**
Toggling shield on this set of units does nothing
![ForgedAlliance_2022-06-25_09-59-13](https://user-images.githubusercontent.com/10947024/175764372-7dbbc9a4-004b-4682-b7c3-2d975e900719.jpg)

**Comment by Garanas** [comment]
This is fixed with https://github.com/FAForever/fa/pull/4074, closing accordingly.

**Comment by Garanas** [comment]
The other issue is not however,

**Comment by Garanas** [comment]
Ok, so it does work but you need to click a few additional times. The game doesn't understand that some units have no shields at all, and therefore they can not be toggled. But it appears the toggle state is still there, and therefore influencing it as a whole. I'm not sure how to fix this, I also do not consider it to be a critical issue at the moment. Closing as not planned.
