### ISSUE TITLE
Better filtering in mod manager

### ISSUE THREAD

**Issue by aeoncleanse** [FAForever/fa#401]
The display defaults to the UI mod filter, which is annoying when you don't have any. I think the filters should be removed, seeing as each entry already has "UI Mod" or "Game Mod" spelled out right next to it. The filters are redundant.

**Comment by Sheeo** [comment]
When you have many, it's quite useful.

But a better filtering function may well be in order.

**Comment by aeoncleanse** [comment]
Either way, it should at minimum default to showing game mods since those are more common.

**Comment by Sheeo** [comment]
What's your basis for that claim? I believe UI mods are more common

**Comment by aeoncleanse** [comment]
Game mods have always been more common... There are far more of them, and they are used more frequently in a wider variety of games. A single player should never have more than half a dozen UI mods because there are so few which function anyway

**Comment by Sheeo** [comment]
Data or it didin't happen ;)

Anyway; new issue name reflects better what there is to be done here.

**Comment by aeoncleanse** [comment]
Find any one of those mad-as-balls games where the host has 40 mods enabled. All but a handful will be game mods.

Other thing is that UI mods you generally enable once and leave. Game mods you want to be changing on a game-by-game basis, so it's really annoying to have to click the checkbox every time.

**Comment by Sheeo** [comment]
Hence filtering by these categories makes sense -- it's a useful distinction.

Making game mods the default filter is perhaps what we are looking for?

**Comment by HUSSAR-mtrela** [comment]
this issue can be closed when PR #1175 is merged to the release branch
