### ISSUE TITLE
Army HQ restrictions are not properly refreshed when unit:Destroy() is called directly

### ISSUE THREAD

**Issue by speed2CZ** [FAForever/fa#4014]
This code https://github.com/FAForever/fa/blob/deploy/fafdevelop/lua/defaultunits.lua#L692-L708
runs when the unit is killed, but if you call directly unit:Destroy(), it is skipped

I suggest changing the callback to OnDestroy

**Comment by Garanas** [comment]
All of those things shouldn't be callbacks all together 😄 , it needs some refactoring.

**Comment by speed2CZ** [comment]
I thought it is already refactored and that broke it, since this worked before :D
