### ISSUE TITLE
Lobby presets should record/set mods too

### ISSUE THREAD

**Issue by aeoncleanse** [FAForever/fa#402]
Seems like this could be a regression, Xinnony contacted me after seeing this and says that it used to work.

**Comment by ChrisKitching** [comment]
This is definitely not a regression. Here is the part of the "Save preset to disk" routine responsible for saving the currently selected mods:
https://github.com/FAForever/fa/blob/develop/lua/ui/lobby/lobby.lua#L5889

You will notice how it is semantically null ;)
