### ISSUE TITLE
Aeon and Sera strats should have ProjectilesPerOnFire set

### ISSUE THREAD

**Issue by spooky** [FAForever/fa#405]
units UAA0304 and XSA0304 (aeon & sera strats) should probably have the ProjectilesPerOnFire set to 1 like cybran and UEF do. This is just an observation though, came from investigating a bug in unit db, but maybe it's the other way around, maybe cyb and UEF should have that removed...

**Comment by Sheeo** [comment]
Any ideas what this attribute does?

**Comment by aeoncleanse** [comment]
Nothing. This attribute is dead, has always been dead, and should never, ever be used. Use MuzzleSalvoSize instead, which replaced ProjectilesPerOnFire early in the supcom beta.

**Comment by spooky** [comment]
noted. Then it probably should be removed from cybran and uef strats

**Comment by aeoncleanse** [comment]
It probably should, but then it should be removed from every single unit in the game, since it appears on almost all of them.

**Comment by aeoncleanse** [comment]
This issue can be closed

**Comment by ChrisKitching** [comment]
Don't we want to keep it to track the removal of that attribute from everything, ever?

**Comment by aeoncleanse** [comment]
Doing so would require introducing FAF files for a large number of units we're not currently affecting. I say we just make sure people know it's dead.
