### ISSUE TITLE
GC Tractor beam error message

### ISSUE THREAD

**Issue by maudlin27** [FAForever/fa#4075]
**Description**
Got the following error message which I think is due to the GC's tractor beam logic:
```
warning: Error running lua script: Failed to attach entity xsl0105 to ual0401 on bone 23
         stack traceback:
             [C]: in function `AttachBoneTo'
             ...mdata\faforever\gamedata\lua.nx5\lua\aeonweapons.lua(207): in function <...mdata\faforever\gamedata\lua.nx5\lua\aeonweapons.lua:165>

Separately, when GCs fight against lots of T1 seraphim engineers, it gives the following in the log:
info: CWldSession::DoBeat() unknown entity id (0x2ff02be5) supplied in a pose update.
```

**To Reproduce**
Was playing on FAF develop, had updated it on 22/07/22.  Confirmed that it's the version featuring the new GC tractor beam logic that leaves wrecks when units die.

In-game scenario: 2 GCs were near the enemy Seraphim base.

Unclear on precise fact pattern that led to this, and unable to reproduce by just spawning in 100 T1 seraphim engineers.  Jip thought it might be when an engineer is rolling off an air factory.

Was using a WIP version of M27AI (against another AI) so no replay available.

**Comment by Garanas** [comment]
Likely an engineer that was ready, and 'sliding' off the Seraphim air factory.
