### ISSUE TITLE
Solace attack move is bugged

### ISSUE THREAD

**Issue by Sir-Prize** [FAForever/fa#410]
As per the title, it seems the Solace likes to fly over hostile ships when on attack move like it's just been ordered to move. An example can be found in 3024052. Very easy to replicate, just spawn or build a solace and send it on an attack move to a civvie ship, factory attack move and specific attack move both yield the same results.

Edited for hilarious tired typo /me blushes

**Comment by Sheeo** [comment]
Also goes for T3 air bombers.

**Comment by aeoncleanse** [comment]
Air has been excluded from the AM changes because most Air has it manually declared. I will check all the bombers, if they don't, I'll declare it.

**Comment by aeoncleanse** [comment]
T3 Bombers are all fine, the Torp Bomber needs the new data.

**Comment by Sheeo** [comment]
Right, the strats need a tuned value though -- that was my point of the edit :)

**Comment by aeoncleanse** [comment]
The value is 100, just a shade bigger than their range. That's about where it should be.
