### ISSUE TITLE
Spread move makes game to freeze

### ISSUE THREAD

**Issue by Arkemlar** [FAForever/fa#4149]
**Describe the bug**
Just make like 100 asfs, peak some units for attack and press shift+G. I wondering why this stupid bug not fixed for ages. That must be easy to make some pre-check like if unit count too high then deny algorithm call and print ingame message to inform about that? It is anyway better then crash the game!

**To Reproduce**
Make spread attack move for 100+ units on 10+ targets and get crashed.

**Expected behavior**
Spread attack implemented or message telling that unit count too high, not crash.

Log attached.
[game_17800834.log](https://github.com/FAForever/fa/files/9382939/game_17800834.log)

**Comment by Garanas** [comment]
Could you try and sandbox a crash, or a set of steps to reliably reproduce it?

**Comment by KionX** [comment]
There are a huge number of errors probably related to mods in your log. Could it be related?

**Comment by Arkemlar** [comment]
> There are a huge number of errors probably related to mods in your log. Could it be related to Spread move?

I remember I got this bug before times I knew about Spread Move mod. And it activates only by specific hotkey, I highly doubt it can affect built in Spread Attack routine.

**Comment by Arkemlar** [comment]
@Garanas yes, I can try to sandbox it, will do it

**Comment by Arkemlar** [comment]
Strangely enough in sandbox I could not reproduce this bug. Same mods, even grater unit counts in Spread Move but no.

**Comment by Garanas** [comment]
That is the issue I had too. I think there is some correlation, but at the moment it does not have a high priority.

In the end - the way spread attack is setup - it is asking for trouble anyway.

**Comment by MrRowey** [comment]
https://wiki.faforever.com/en/Play/Game/Hotkeys/OrdersQueueManipulation Fix with this new implementation

**Comment by Arkemlar** [comment]
Wow, this is incredible feature! Well done!

вс, 15 окт. 2023 г., 23:17 Josh ***@***.***>:

**Comment by Arkemlar** [comment]
Wow, this is incredible feature! Well done!
