### ISSUE TITLE
UI corruption when watching replays

### ISSUE THREAD

**Issue by ChrisKitching** [FAForever/fa#416]
The UI sometimes goes all splurked when watching replayed.
Reported here:
http://forums.faforever.com/forums/viewtopic.php?f=3&t=9309

And earlier (but without the useful "only when watching replays" caveat) here:
http://forums.faforever.com/forums/viewtopic.php?f=3&t=9236

Could it be that these people are attempting to load the now-defunct "random" skin?

**Comment by ChrisKitching** [comment]
Apparently "ALT + left or right key solves this problém  ;)", so it's definitely caused by them loading the defunct "random" skin.

**Comment by Sheeo** [comment]
Gotcha.

Could we default the defunct skin to UEF somewhere, so even if someone manages to get it they will see something that isn't horribly broken?

On a related note, I think a generic 'FAF' skin suiting the UI feel of lobby is in order. Perhaps @aeoncleanse feels like doing this as part of his look-and-feel update?

**Comment by ChrisKitching** [comment]
30686d5 Should finally squish this one.
