### ISSUE TITLE
Use of extended ASCII characters in lobby chat causes a disconnect

### ISSUE THREAD

**Issue by phongu** [FAForever/fa#4194]
**To Reproduce**
Create or join a lobby, type or paste into the chat "qué?", press enter, get disconnected.

**Additional context**
This bug was probably introduced sometime in June or August 2022

**Comment by Garanas** [comment]
@4z0t any ideas?

**Comment by KionX** [comment]
Couldn't reproduce it.

**Comment by MrRowey** [comment]
![image](https://user-images.githubusercontent.com/20344151/187681102-e12c6672-14cf-40f6-a80a-2350f5862621.png)
 Can confirm it happends

**Comment by phongu** [comment]
KarlHoffman, Ninrai, Babel reproduced it. Everyone I spoke to in CpC clan (french) told me it also happens to them and they knew about the bug before I mentioned it. A_A_A and VonEinzbern (who are Russian) could NOT reproduce the bug, I asked and they told me their game is not in Russian.

**Comment by 4z0t** [comment]
I cant reproduce it either...

**Comment by 4z0t** [comment]
Moved to client issue.

**Comment by MrRowey** [comment]
How is this a client issuse when i happends inside the lobby ?

**Comment by Garanas** [comment]
Because of the ICE adapter.
