### ISSUE TITLE
UEF Navy factory HQ and Aeon Air factory HQ 's Bug

### ISSUE THREAD

**Issue by heibaixyd** [FAForever/fa#4195]
BUG1:  UEF Navy factory HQ has no difference with normal Navy factory.

BUT2:  When the Aeon Air factory HQ has been upgraded to LV3 , it will change to nomal Air factory.

**Comment by MrRowey** [comment]
Please Provide the replay where this happends

**Comment by Garanas** [comment]
![image](https://user-images.githubusercontent.com/15778155/187741344-d6d9a432-0ebf-40c7-a54f-cb181423ec5f.png)

![image](https://user-images.githubusercontent.com/15778155/187741380-fbd83b2a-3299-43fb-a5cf-e74a5795eaa4.png)

He's right, they're the same 😄

**Comment by Garanas** [comment]
@MrRowey guess which one is the HQ

**Comment by MrRowey** [comment]
🤷‍♂️
