### ISSUE TITLE
Titan hitbox prevents beam weapons from hitting it at certain angles.

### ISSUE THREAD

**Issue by Endranii** [FAForever/fa#4213]
**Describe the bug**
Beam weapons tend to miss Titans body.

**To Reproduce**
Have a titan run around a beam weapon. Be it ML or Seraphine T2 pd. At certain angles and distances the titan is just unhittable.

**Expected behavior**
ML will kill the titan in about 1second. Sera t2 PD will deal damage to the unit.

**Screenshots**
https://replay.faforever.com/17987150   Minute 22.30 starts the fight in which the undesirable behaviour can be observed. 22.35 first instance. 22.43 is the second one. Unfortunately can't find the replay in which titan took no damage at all while killing sera t2 pd.

**Comment by Garanas** [comment]
Yes, we're fixing this with https://github.com/FAForever/fa/issues/4067 . But, as you can imagine, going over all units to check their values is quite a bit of work. I'll prioritise the Titan, Loyalist and Harb for the balance patch.

**Comment by Endranii** [comment]
Oh don't worry Jip. I was just looking through Titan mentions in issues and didn't find any regarding the targeting problem so I wasn't sure if it's a known one or not. And considering I saw it happen quite often in the past week I wanted to make sure it's known.

Just didn't come to my mind to look under bone problems or other tags. Just searched for titan.
