### ISSUE TITLE
mod selection ui breaks with UI scaling

### ISSUE THREAD

**Issue by BlackYps** [FAForever/fa#4233]
The new mod selection ui doesn't properly react to UI scaling. Screenshot shows 125% ui scaling. The buttons are not clickable.

![Screenshot 2022-08-24 101919](https://user-images.githubusercontent.com/52536103/191027945-c8d7faf8-3b49-4a41-a008-e21fdaf449f3.png)

**Comment by Garanas** [comment]
@4z0t is working on this if I recall correct

**Comment by 4z0t** [comment]
Shouldn't it be fixed on faf dev?
