### ISSUE TITLE
Add division to score board for matchmaker games

### ISSUE THREAD

**Issue by BlackYps** [FAForever/fa#4258]
The latest client sends the division name of the player to the game if applicable. PR: https://github.com/FAForever/downlords-faf-client/pull/2793

Now the game needs to pick that name up to display it in the score board of the game instead of the rating. We could also or instead display a 20x40px image that petric made that visually represents the division.

The division info should also be saved in the replay. 
Can we even add more data to the replay?

**Comment by Garanas** [comment]
We can add data to the replay by doing a `SimCallback`. Where are the images, I think we should use those

**Comment by BlackYps** [comment]
Would you rather have a link to the server location or the physical files?

**Comment by BlackYps** [comment]
Icons on server are here: https://content.faforever.com/divisions/icons/small/goldI_small.png I can also provide the physical files if that is better

**Comment by Garanas** [comment]
Batching them into a zip would be preferred, I can't properly navigate that link

**Comment by BlackYps** [comment]
[icons.zip](https://github.com/FAForever/fa/files/9758496/icons.zip)
@4z0t was also interested in implementing this

**Comment by 4z0t** [comment]
Closing?

**Comment by BlackYps** [comment]
No?
