### ISSUE TITLE
Seraphim torpedo bombers doing more than 750 damage sometimes

### ISSUE THREAD

**Issue by ChessBerry** [FAForever/fa#4261]
**Describe the bug**
Seraphim torpedo bombers to more damage to some units, depending on the angle/spot at which their torpedos hit.

**To Reproduce**
Spawn an aeon carrier and an enemy sera torp bomber. Have the torp bobmer attack the carrier once from a horizontal direction, with the torpedos hitting the carrier's sides, and it will do 834 damage, about 11% more than it's supposed to:
![Forged Alliance 10 10 2022 20_25_46 (2)](https://user-images.githubusercontent.com/90977374/194931492-a6834edb-f238-43ac-b403-1cf155076b03.png)

If the torpedo approaches the carrier from a vertical direction, hitting it's front or back, it does 750 damage as expected:
![Forged Alliance 10 10 2022 20_26_09 (2)](https://user-images.githubusercontent.com/90977374/194931795-bf444b3b-b6bd-4be3-a369-782e07247034.png)

**Expected behavior**
Regardless of firing angle or hit location, each torpedo bomber salvo should deal a consistent 750 damage.

**Additional context**
2 minute replay exhibiting the bug: 18245313  
No sim mods were active, and at least one other person in discord could reproduce my findings.  
I haven't exhaustively tested all torp bombers, but it the bug seems to be confined to the sera torp bomber and is most easily visible on larger ships. Might work for other ships/targets too though.

**Comment by Garanas** [comment]
It likely has to do with these two lines:
- https://github.com/FAForever/fa/blob/fix/teleport-glitches/projectiles/SANHeavyCavitationTorpedo01/SANHeavyCavitationTorpedo01_script.lua#L34
- https://github.com/FAForever/fa/blob/fix/teleport-glitches/projectiles/SANHeavyCavitationTorpedo01/SANHeavyCavitationTorpedo01_script.lua#L46

Creating a (split second) window where both the original projectile and the split projectiles exists, allowing them both to deal damage. I don't think this is practically viable, but it should be fixed.
