### ISSUE TITLE
Scatis (and probably any other structure/exp) can be build instantly in coop

### ISSUE THREAD

**Issue by K-ETFreeman** [FAForever/fa#4272]
1) Describe the bug
In coop mode, with 2 or more players, any structure (or exp, probably) can be builded with 1hp instantly and (almost) without mass/energy spended

2) To Reproduce
-Launch coop mission with 2nd player (This behavor confirmed on Black Day mission, no guarantee about others)
-Start build scatis, even 5hp is enough
-Give it to your ally
-Your ally recieves full-operational scatis (with 5 hp tho), instead of not-builded

3) Expected behavior
Ally recieves not builded scatis

4) Screenshots
[screenshot](https://i.ibb.co/YfrQ6g2/screen.png)

5) [Replay link](https://replay.faforever.com/18140463) 
    Bug abusing moment at 4:45
    (replay id is 18140463)

**Comment by 4z0t** [comment]
In addition
https://youtu.be/d0xU6q9-5ns

**Comment by Garanas** [comment]
I see, that sounds like an issue 😄

**Comment by Garanas** [comment]
Are we confident that this is limited to co-op?

**Comment by K-ETFreeman** [comment]
> Are we confident that this is limited to co-op?

I tested with a friend in sandbox lobby, it didn't work
not 100% confident, but probably it is

**Comment by 4z0t** [comment]
Fixed here https://github.com/FAForever/fa-coop/pull/104
