### ISSUE TITLE
NavRequest - Return path distance when a path is requested.

### ISSUE THREAD

**Issue by relent0r** [FAForever/fa#4277]
## Return pathing distance when a path is generated

When a path from an origin to a destination is requested, the path will also return the distance of the generated path.

```lua
---@param layer String
---@param origin Vector
---@param destination Vector
---@return boolean
function PathTo(layer, origin, destination)

end
```

returns
true, message, distance
on success

Screenshot attached shows the issue with the current approach. There are two mass points very close to the spawn position. But the actual travel distance is much further than another mass point that while further in radius is less than half the distance to travel to.

As an AI developer I would likely want to cache the pathing distances from the main base on game start so that the builder conditions for mass points would take those into account rather than the VDist3 radius.

![pathdistance](https://user-images.githubusercontent.com/34614077/196526036-cc560f5c-d0e6-41ee-9dd2-3b835c652543.jpg)

**Comment by Garanas** [comment]
This is implemented, see also the return values of `PathTo`: `PathToPath, PathToPathHead - 1, distance`, where:
- `PathToPath`: This is the path
- `PathToPathHead - 1`: This is the number of elements in the path, used for loops
- `distance`: distance of the path

Note that the 1st argument can be nil, if no path was found. In that case the 2nd argument is a string telling you why it happened.
