### ISSUE TITLE
Request for editing Tradition Chinese loc files

### ISSUE THREAD

**Issue by Yuchenjimmy** [FAForever/fa#4278]
Hello, dear developers. Some of the strings for Tradition Chinese are still English, and I want to translate them.

**Comment by MrRowey** [comment]
feel free make a pull request with the changes or if not sure how to use github a document with the corresponding line number would also work

**Comment by Yuchenjimmy** [comment]
Ok, I've added some changes for testing, thanks! But there is still one problem, would you please tell me how to apply changes to my local files? I need to know if I translate correctly.

**Comment by KionX** [comment]
Place the file in this path:
C:\ProgramData\FAForever\DevData\loc\TW\strings_db.lua
and run fafdevelop through the client.

Or read here:
https://github.com/FAForever/fa/blob/deploy/fafdevelop/setup/setup-english.md

**Comment by Yuchenjimmy** [comment]
Sorry, I couldn't find a toggle to execute fafdevelop? Where is it?

**Comment by KionX** [comment]
Then use this cmd:
C:\ProgramData\FAForever\bin\ForgedAlliance.exe /init init_fafdevelop.lua

**Comment by KionX** [comment]
![image](https://user-images.githubusercontent.com/5648030/197117342-f49dc862-0ab9-495c-b372-9ec77e9064d1.png)
