### ISSUE TITLE
Nav mesh - improve testability and performance of the Heap data structure

### ISSUE THREAD

**Issue by Garanas** [FAForever/fa#4295]
Description
-------------

A priority queue is required for path finding. We [implemented](https://github.com/FAForever/fa/blob/deploy/fafdevelop/lua/sim/NavDatastructures.lua#L27) this as a heap. This heap is specifically written to support path finding, it is not a generalized heap. This reduces the overhead of the heap.

If you're unfamiliar with the data structure it is best to read up about it:
- https://www.youtube.com/watch?v=t0Cq6tVNRBA
- https://www.geeksforgeeks.org/introduction-to-heap-data-structure-and-algorithm-tutorials/

Note that we use a min-heap: the smallest element is at the top.

Course of action
----------------

This issue consists of two parts:
- [x] (1) Introduce a test suite for the heap, that is run as part of the build workflow of Github
- [ ] (2) Improve the performance of the heap

For (1) you can use the [existing tests](https://github.com/FAForever/fa/tree/deploy/fafdevelop/tests) as an example. Additional test files are automatically picked up. You'll need to write various tests to proof various properties. As a few examples:
- If you add 10 items, the heap has a size of 10
- If you add 10 items, the items are in the correct order
- If you add 10 items, and then extract 10 items they are in a sorted order from small to large
- (...)

There can be other interesting properties to test. But these three are the most important properties: they help us make sure that the heap operates as expected.

For (2) there are various places where we can easily skip table operations when we efficiently use the `Size` value of the heap. As an example, take this snippet:

```lua
    ---@param self NavPathToHeap
    ---@param index number
    Heapify = function(self, index)
        -- find the left / right child and the parent.
        local parent = index
        local left = self:ToLeftChild(index)
        local right = self:ToRightChild(index)

        -- find the best of the two, we assume the left child is.
        local min = left

        -- if there is a right child, then there always has to be a left child. Hence, we can now assume there's both a right and a left child.
        -- compare the two: if right is smaller, then assign min = right. Else, keep min on left.
        if self.Heap[right] then
            if (self.Heap[right].AcquiredCosts + self.Heap[right].ExpectedCosts) < (self.Heap[left].AcquiredCosts + self.Heap[left].ExpectedCosts) then
                min = right
            end
        end

        -- if there is a child, compare the lowest child (is given due to code above) with our parent. 
        -- If it's smaller, switch the parent and the lowest child.
        if self.Heap[min] then
            if (self.Heap[min].AcquiredCosts + self.Heap[min].ExpectedCosts ) < (self.Heap[parent].AcquiredCosts + self.Heap[parent].ExpectedCosts) then
                -- swap the two values.
                self:Swap(parent, min)

                -- check if the (parent) value that is now at the child position is at the correct position within the Heap.
                self:Heapify(min)
            end
        end
    end,
```

Take `if self.Heap[right] then` and `if self.Heap[min] then` - as an alternative (and faster) check we can compare `right` and `min` with `self.Size` instead. And take `if (self.Heap[min].AcquiredCosts + self.Heap[min].ExpectedCosts ) < (self.Heap[parent].AcquiredCosts + self.Heap[parent].ExpectedCosts) then` - as an alternative we can replace the `ExpectedCosts` field with a `TotalCosts` field, that already includes the `AcquiredCosts`. This would require you to make changes in the [generator](https://github.com/FAForever/fa/blob/deploy/fafdevelop/lua/sim/NavGenerator.lua#L237) and [utility functions](https://github.com/FAForever/fa/blob/deploy/fafdevelop/lua/sim/NavUtils.lua#L162) too. As a result, we'd save on multiple additions each time `Heapify` is called. 

And last - we can store `self.Heap` into a local `local heap = self.Heap` to reduce the number of table allocations.

Test plan
---------

By all means - by using the test suite! Preferably the test suit is created _before_ changes are made to the algorithm. This makes it easier for you to test your changes.

Learning goals
----------------

Learn how to work with existing algorithms and improve their implementation.

**Comment by Zjonn** [comment]
Hey, @Garanas I can take this one If you don't mind.

**Comment by Garanas** [comment]
All yours 😄 !
