### ISSUE TITLE
Query for graph area (UniqueLabel?) at position.

### ISSUE THREAD

**Issue by relent0r** [FAForever/fa#4296]
## Describe the query
I'm not sure on the naming conventions for this. Based on the NavGenerator lua I believe they are called labels so for the sake of readability I'll call them that for the rest of this description.

Function to query which label a position is currently assigned. This query will provide metadata for other objects such as markers or AI objects such a bases. 
For example when an AI creates a naval base it will query the label for the naval position, this will allow it to know if other positions are on the same pond or different ponds and which label is allocated to those ponds. 

```lua
---@param layer String
---@param position Vector
---@return Label
function GetCurrentLabel(layer, position)

end
```

## Visualize the query
This screenshot shows which layer points would have labels. Each of the 9 land masses would have separate labels/grapharea names. The query would return the label/graph for each land mass if a position on them is queried with the layer type of 'Land' or 'Amphibious' or 'Air' is used(not actually sure if Air should be valid as there will always only be one label to my knowledge).

## True / false positives
True will return the label.
If a label cannot be returned a reason may be provided. There are certain situations where a label my not be available such as when the position is out of the map bounds, or when the positions is between two labels such as the side of a mountain. I'm not totally sure how you would handle that. 

I considered requesting a 'closest' parameter that would then provide the closest label to that position if none were available at the position queried.
In my current logic when a position does not return a zone then I would get 8 points around the position and query those to see if one would return a valid zone as a fallback. This situation happens when a platoons position is inside a mountain or another area where no zone/label is defined so while its a niche situation it does happen.

![Label10](https://user-images.githubusercontent.com/34614077/197715398-26e7882f-f526-4aa8-acd9-6f9ffc17be84.JPG)

**Comment by Garanas** [comment]
![image](https://user-images.githubusercontent.com/15778155/197738656-8276f402-4dda-4bce-b5ad-c9e4ca427266.png)

![image](https://user-images.githubusercontent.com/15778155/197738721-cb1c4598-9722-4bc0-9365-49840d577db3.png)

The UI has a button to visualize the labels of the graph. I'm working on the query in #4298

**Comment by Garanas** [comment]
Note that labels are not unique across layers, they are unique within a given layer. Would it be useful if these are unique across all layers?

**Comment by Garanas** [comment]
The pull request (https://github.com/FAForever/fa/pull/4298) is in review state

**Comment by relent0r** [comment]
> 

Historically I haven't used a string search to identify which layer a label belongs to so I don't think having the layer would provide an advantage beyond debugging but you've provided great tools that makes that less relevant anyway. In the current iteration of graph areas they are assigned the same name as the first path marker that is looked at e.g Land_21. 

What I'll likely do is create a table using the layers as keys for the labels and query them like that. My only concern with not using the layer in the return would be that a developer might not use such a method and end up looping through layers checking for a label and end up with duplicate truthyness.


e.g I would use this 
`
if base.Labels.Land == masspoint.Labels.Land then
   do something
end
`

but if you used this you might run into problems
`
local label = NavUtils.GetLabel('Land', pos)
for k, v in layers do
    for c, b in masspoints do
        if b.label == label then
            do something
        end
    end
end
`

**Comment by Garanas** [comment]
Proper annotations could help with this situation. It would tell you that `b.label` likely doesn't exist. Let us discuss this over voice, make a few drawings of the intended usage and then we'll finalize the request.
