### ISSUE TITLE
Get Closest Label Position

### ISSUE THREAD

**Issue by relent0r** [FAForever/fa#4297]
## Describe the query
I'm not sure on the naming conventions for this. Based on the NavGenerator lua I believe they are called labels so for the sake of readability I'll call them that for the rest of this description.

Function to query the closest valid position when given a label and position. This query will provide information that an AI can use to gauge strike distance or validity of a naval pond. The layer String may well not be required if each label for every layer is unique.
I've added an optional radius param. If specified then the position must be as least this radius from the position(e.g can a TML strike this position from this label). This would allow potential firebase locations to be determined.

```lua
---@param layer String
---@param position Vector
---@param label UniqueLabel
---@param size integer
---@param radius integer - optional
---@return Position, Distance
function GetClosestLabelPosition(layer, position, label, size, radius)

end
```

## Visualize the query
The map Alpha7 is used as an example here. There are 5 naval ponds that an AI could select to establish a naval base.
By allowing this the AI can (assuming it already knows which labels are associated with the existing naval expansion markers) query which position is closest to an enemy start position based on a label that it has associated with a naval expansion marker. The AI could then select one that would guarantee to allow pathing for naval units to get within a desired radius for things like missile boats or battleships etc.
The size param would request that a minimum foot print be allowed at that position (the grid square size of the navmesh would define this) 

## True / false positives
True will return the position and distance of the position from the original position queried.
False would like mean an invalid label or layer was used or not position is available for the requested radius / size.

![Alpha7](https://user-images.githubusercontent.com/34614077/197721387-d75d6f48-1608-4f58-aa49-84f563a082a9.JPG)

**Comment by Garanas** [comment]
I'll try and work it out. Does this information need to be computed dynamically, or would a static answer (generated at start, and then just returned) suffice too?

**Comment by relent0r** [comment]
> I'll try and work it out. Does this information need to be computed dynamically, or would a static answer (generated at start, and then just returned) suffice too?

Since map terrain never changes(beyond flattening) I wouldn't see any problems with static, assuming I'm understanding your question correctly.

**Comment by Garanas** [comment]
Yes - because we could compute for each area what the nearest valid area is. That would make this a quick lookup during gameplay.

**Comment by Garanas** [comment]
Implemented with https://github.com/FAForever/fa/pull/5407
