### ISSUE TITLE
T1 Power Generator Simultaneous Explosion Inconsistency

### ISSUE THREAD

**Issue by ChessBerry** [FAForever/fa#4335]
If you ctrl+k a bunch of adjacent t1 power generators, they sometimes deal damage to each other's wrecks, reducing the reclaim they leave behind. While well known, it seems that sera t1 pgens, and only sera t1 pgens are for some reason immune to that:

Aeon:
![Screenshot_3](https://user-images.githubusercontent.com/90977374/200113741-f3e70d39-1a34-4996-8b78-520a3d5c0890.png)

Uef (note the "16" mixed in with the "61"):
![Screenshot_4](https://user-images.githubusercontent.com/90977374/200113786-6495c807-1f86-496b-9fc0-553e7f538f75.png)

Cybran:
![Screenshot_5](https://user-images.githubusercontent.com/90977374/200113788-ac43d9ca-b55d-4640-9ac4-9f9e61b2468d.png)

Sera:
![Screenshot_6](https://user-images.githubusercontent.com/90977374/200113790-4ad4e0c1-7822-49e8-b4c8-24a8cee943ae.png)

Replay ID with these tests, no sim mods enabled: 18435210
This behavior was found by Femto Zetta on the discord.

While the bug report part of this issue is "sera t1 pgens op", this could actually be useful.

Afaik, the "pgens damaging their neighbors wrecks" behavior is effectively random, or at least it doesn't seem to depend on build order or ground geometry. 
If we can figure out why the sera pgens don't do that, we could clone the behavior to the other factions pgens, removing a (minor) annoyance from the game.

From a very cursory examination of the collision boxes, I couldn't figure out any reason _why_ sera t1 pgens behave differently though. In fact their collision box seems to be a duplicate of the UEF one(?), and if you believe the stats their death explosion is the same too:
![Screenshot_7](https://user-images.githubusercontent.com/90977374/200114225-e9e0d720-1d0e-49a4-bf42-71a1bd832797.png)

Well, idk. Here is to another weird oddity in this game of ours :P

**Comment by Garanas** [comment]
![image](https://user-images.githubusercontent.com/15778155/200115404-b6390fba-43fb-4877-918d-689fd840ff2c.png)

Seraphim power generators have a small death animation that is played. Death animations in general have a strange interaction with their wrecks, as they are 'immune' for damage during the animation.

If we'd remove the death animation then we'd end up with floating little orbs:

![image](https://user-images.githubusercontent.com/15778155/200115458-775f1ef4-4222-42ff-b0bf-b92b674a6e77.png)

But that does give us a similar pattern:

![image](https://user-images.githubusercontent.com/15778155/200115475-fe98bb29-c2aa-4502-98d1-154e5776e4d5.png)

**Comment by Garanas** [comment]
This does matter in practice, as people often CTRL + K power generators to reclaim them quicker. This would be a lot more beneficial to do for Seraphim then for other factions.

**Comment by Garanas** [comment]
Thinking about it, death animations on volatile structures should likely be removed - it can cause a lot of weirdness.

**Comment by ChessBerry** [comment]
I'm not sure this really "matters" even on the highest level, on even the most sim-citiest of maps. 
And personally I'd prefer to make the consistent behavior of sera pgens and not the random behavior of the other factions the default, but if that's infeasible of

**Comment by piisawheel** [comment]
From a balance point of view, Sera doesn't get rascoms and must rely on massfabs if the game type requires it.  It *could* be considered balanced from that point of view.  I have a (probably bad) habit of reclaiming live pgens, so this doesn't really affect me, as much as it should be affecting me.

**Comment by MrRowey** [comment]
@Garanas This has been discussed and the comment for this were as follows
```
- If we could make all behave like sera that would be best
- If not, then we’d like them to be as consistent as possible
```

**Comment by Garanas** [comment]
Then I'll make it consistent. We can't have them all behave like the Seraphim pgens.

**Comment by BlackYps** [comment]
I don't really understand the conclusion here. It was mentioned that the seraphim pgens need the death animation to prevent the floating orb. And having the pgens not take damage is the more preferred way by the balance team. So why can't we give all pgens a small death animation?

**Comment by Garanas** [comment]
The correct solution is not to give more structures death animations, but to allow structures to soak (splash) damage when their death animation is running and take that into account with the value of the wreck

**Comment by BlackYps** [comment]
So are we working in that direction or did we settle for removing the death animations? I agree with your take on what the correct solution should be, but earlier in this discussion you argued for removing the death animations. So I am getting some mixed signals here
