### ISSUE TITLE
Activated non-UI mods show up in mod manager when the UI mods filter is activated

### ISSUE THREAD

**Issue by ChrisKitching** [FAForever/fa#434]
STR:

Activate some sim mods.
Ensure the "UI mods" filter is on.
Close mod manager.
Open mod manager.

Notice how the "UI mods" is on, but all your active sim mods are shown.

Modman seems to be a bit of a mess: could use a rework. Anyone bored enough?

**Comment by speed2CZ** [comment]
https://github.com/FAForever/fa/pull/1170
https://github.com/FAForever/fa/pull/1172
Works 10/10 in 3652
