### ISSUE TITLE
Feature Request: Repeat Build is on for new factories toggle.

### ISSUE THREAD

**Issue by RegalEagIe** [FAForever/fa#4346]
Implement the UI party feature that toggles on repeat build on every factory build as an option, like right clicking on T2 mexes and highers automattically rings it with mass storages.

When you build a new factory --> The repeat build will be toggled on by default, it does not change behavior and can be toggled manually off after, but just makes every new factory start with it.

Example of UI party working in game.
![ezgif-2-fabbee3e1c](https://user-images.githubusercontent.com/81800265/200174247-7979b2d4-e981-403d-ae0a-64b8a5cef164.gif)

I've noticed some bugs on my game with UI Party recently and would like to remove it, but this feature is too much important for me to remove it, so I'm hoping for it to no longer be necessary for me.

**Comment by Garanas** [comment]
This sounds like a good candidate for a game option.
