### ISSUE TITLE
Game broken

### ISSUE THREAD

**Issue by mdcobra** [FAForever/fa#4350]
After release 3745 the game is completely broken, the game starts to flicker after a while and freezes up. Playing against Sorian AI.

imgur.com/PuAsfKj

**Comment by Garanas** [comment]
We need logs! 

![image](https://user-images.githubusercontent.com/15778155/200178755-a51ffa18-ea31-41d8-aa83-87f49cdf8deb.png)

'Show log folder', find the log that matches your game id / timestamp

**Comment by mdcobra** [comment]
[game_18454936.log](https://github.com/FAForever/fa/files/9946128/game_18454936.log)

**Comment by Garanas** [comment]
Could you record it?

**Comment by mdcobra** [comment]
No, there is a replay file, but nothing interesting to see there I believe.

**Comment by Garanas** [comment]
This should be fixed now - if it still happens you can create a new issue.
