### ISSUE TITLE
Mobile factories on units that can move and build units

### ISSUE THREAD

**Issue by EvildrewFAF** [FAForever/fa#4356]
**Describe the feature**
Adds a mobile factory onto each unit that is able to move and build units. An interlink like we have on kennels-drones needs adding and a picture to replace the placeholder icon worthy of a mobile factory needs adding too. Didn't have the chance to test the mod but based on past experience it should work. Shift click drag to find the mobile factories is the easiest way. Units are added to the carriers', atlantis' and czars' inventories and pooped out of the tempest&fatboy.

**Expected behavior**
Be able to move the carriers and other units while building at the same time without automatically canceling building units on move order.

**Comment by 4z0t** [comment]
Looks promising! Can you post it as sim, so, we can test it?

**Comment by EvildrewFAF** [comment]
I think I am not the only one whose mods dont work anymore. Something changed in past patches and I am not able to use any of my testing mods anymore. If you can send me an empty shell/template of a mod that will work, I can upload it np :)

**Comment by EvildrewFAF** [comment]
It's in the vault for validation/testing as described in the OP.

**Comment by EvildrewFAF** [comment]
![Unit to mobile_factory toggle icon](https://user-images.githubusercontent.com/46637108/202551131-0dab5dd6-99f0-4c62-8d44-a71b96c5a3a7.png)

**Comment by Strogoo** [comment]
As I remember Equilibrium mod made by Exotic had this feature too. Did you take his implementation as a base and imprvoved/remade it or just made from scratch? If second, then it might be a good idea to look at both implementations and pick the better one (or combine them, taking better parts from both).

Anyway, some of our lua guys as @4z0t or @Garanas should definitely look at this. Long time ago we wanted to add this to main patch, but Exotic wasn't intereseted in making PRs for /fa repo and others were too lazy :)

**Comment by EvildrewFAF** [comment]
> 

Yes I extracted ER's stuff from Equilibrium, then made some little changes and now trying to complete it with the features described above with the help of whoever wants to and can assist really. Garanas/Jip and I are already in discussion, he is busy, but if someone else has the time to assist with the coding part, just hit me up. I have a good idea of what code we need but I am not an IT person who knows much about coding and have failed to get the feature implemented and working myself. I am sure Jip would appreciate it if someone else wants to take over that part. Fichom is making the icons.

**Comment by EvildrewFAF** [comment]
Postponed,...
