### ISSUE TITLE
Game hangs after selecting shield generator for construction

### ISSUE THREAD

**Issue by Jorgen-P** [FAForever/fa#4357]
**Describe the bug**
Crash after selecting T2 shield generator in build menu as UEF (don't remember with which unit). I could select it but less than a second later as I was moving the mouse the game froze. The weird thing is that I was playing with a friend (he played Cybran) who had a very similar crash (also involving building a shield generator), he disconnected and a little while later my game crashed.

**To Reproduce**
Not sure, tried building some shield generators in sandbox but did not get same crash. Tried with T2 and T3 engineer and ACU upgraded with T2 and then T3 building.

**Log or error message**
This is my log file:  
[game_18455984.log](https://github.com/FAForever/downlords-faf-client/files/9946346/game_18455984.log)

**Expected behavior**
Expected an option for placing the shield generator. 

**Screenshots**
Game would not show again after opening task manager but pretty sure was showing some red diagonal lines across the whole screen over the regular image. I wanna say it was moving about? 

**OS**
Windows 10

**Wanna have the bug fixed quickly?**
I already support FAF on Patreon if that makes a difference.

**Comment by Garanas** [comment]
We're fixing this issue with the hot fix that we're releasing in a minute 👍

**Comment by Jorgen-P** [comment]
Great, thanks! I'll go ahead and close this then 👍
