### ISSUE TITLE
RAS SACU + RAS Economy Alignments

### ISSUE THREAD

**Issue by EvildrewFAF** [FAForever/fa#4365]
RAS SACU and other Economy Alignments:

RAS SACUs are overpowered in the current version of FAF because the RAS upgrade itself is too cheap relative to its yield as compared to Mass Fabs. To explain I will show some mathematical analysis to demonstrate this.
First one has to calculate the correct Mass Energy Equivalence (MEE) to be able with this ratio to uniformly compare apples to oranges. As through the tech levels energy becomes cheaper to produce while mass becomes more expensive to produce we have to go use the MEE of Tech 3 mass extractors (Mex) and Power generators (Pgens) to convert the 10 mass and 1000 energy a RAS SACU generates into something meaningful.
The MEE is equal to the energy produced by a Pgen divided by the product of the mass cost of a Pgen divided by the mass cost of a Mex multiplied by the mass income from a Mex, hence F4 = D4/((D2/E2)*E4). One may include the energy cost of running a Mex in the calculation but it doesnt change much in principle. The table below gives us how many units of energy one unit of mass is worth at the different tech levels.
 
![image](https://user-images.githubusercontent.com/46637108/200195918-e18cdf90-6a6f-4181-9fd9-c9600d99cd1e.png)

In all my following calculations I will use however the following values for simplicity.
T1 MEE = 5
T2 MEE = 50
T3 MEE = 200
In the table below one sees immediately that while T3 Mex are slightly more efficient than the RAS upgrade, T3 Mass Fabs are much more inefficient.
 
![image](https://user-images.githubusercontent.com/46637108/200195935-5d3fdb0a-54b2-4b4e-ab3d-76adc5a73834.png)

In conclusion, it should be known that while Mex and Mass Fabs have one main benefit being adjacency, they lack other benefits where RAS SACUs have smaller scale, mobility, health, weapons, Engineering suite advantages. These features are not quantifiable.
In order to bring RAS SACU in line with Mass Fabs the cost of the RAS upgrade would have to be increased by 70% to 8415 MEE. That could translate respecting the current Mass to Energy cost ratio into 7650 Mass + 153000 Energy for the Upgrade or 9750 Mass + 178200 for a RAS SACU.
With this new RAS SACU in a wider context of eco balance one sees that the new RAS SACU is equivalent to the Seraphim SACU, neglecting compounding which would tilt the balance back into Sera SACUs favor.
 
![image](https://user-images.githubusercontent.com/46637108/200195944-12ed87f8-abef-4948-870d-181b2f2b4766.png)

However one has to think in principle about whether a T3 Mass Fab should have half the efficiency of a T3 Mex or if it should be two-thirds. In that case, T3 Mass Fabs would have to be buffed and the cost of the RAS Upgrade on SACUs would need to be raised by less to reach parity. Another solution would be with the higher cost for RAS SACU one could give Quantum Gateways more adjacency bonus than they currently have which is close to nothing. This would penalize purely spamming RAS SACU with all available build power in order to put all eco into more eco. It would create diseconomies of scale and maybe prompt players to actually do something...
In a wider discussion the current values for RAS upgrades on ACU's should also be fitting to align a bit better. The current RAS values resulting from some past "balance" patch should also be addressed ASAP as it creates inconsistencies.
 
![image](https://user-images.githubusercontent.com/46637108/200195950-14a60649-cdc7-47ac-9604-02e217a4e22f.png)

Some better values would be the following all rooted in the MEE established at the beginning of this post. The only question lies in whether the ratio is good around 0.45% or should be higher or lower.
 
![image](https://user-images.githubusercontent.com/46637108/200195954-efbab28e-a0e3-4c37-ad2f-77576c063de1.png)
![image](https://user-images.githubusercontent.com/46637108/200195958-f56717f6-1ac0-43c6-a8d2-ca69fc61f0cb.png)
![image](https://user-images.githubusercontent.com/46637108/200195961-bd60828b-0016-45cc-a0bb-ecb3638aebb9.png)

**Comment by Tagada14** [comment]
I have a couple of issues with those calculations.
First of all, calculating the income of T3 mexes without mass storages is just criminal. A similar is true for mass fabs without their adjacency to T3 pgen. If you calculate the efficiency of a 2 T3 mass fab + 2 T3 Pgen grid you will see that they are more efficient than RAS SACUs. On the other hand, RAS SACUs have BP, are less volatile, can move, don't take space, can fight etc. There will be a mini SACU rework soon TM that will nerf the BP, HP, and fighting capabilities of SACUs without offensive/builder upgrades but I don't see a need for a RAS rework at the moment

**Comment by EvildrewFAF** [comment]
> 

Maybe you didnt get the point, but you do not use the income of T3 mexes with mass storage because the adjacency bonus is a feature, like RAS SACUs ability to move, shoot etc, you compensates one disadvantage by granting a different advantage and thereby indirectly achieve a better balance. When you place T3 Pgens next to a T3 Mass fab you increase your risk of losing it all to one strike for the upside of getting better income, just like you will lose mass storage on a mex that gets strated. It is a trade off between risk and reward. You may have noticed I also did not calculate T3 Pgens with Energy storages around them. Why do people place energy storage all around the back spread out and not on their T3 Pgens on dual gap and other sim city maps? I assume they understand that one of those exploding with take all of the E storage and T3 pgen they surround down, risk-reward... Granted many weaker players place e storage around the hydro which is beyond silly but you cant generalize. 
So assume you place a T3 mass fab on a T3 pgen and risk losing both to one hit, your ratio goes from 0.18% to say 0.21% and you say see it is in line with RAS on SACU but what does the RAS SACU have as a disadvantage, it always produces the same mass and energy, regardless of whether it is safe in the water or standing next to a paragon... This is where your argumentation falls apart, you cant just add in new variable to try and reestablish that you are right or someone else is wrong, you should think about this because to be frank your argumentation in this post as in many others I have seen is extremely weak and does not even express anything of any value.
