### ISSUE TITLE
Seraphim ACU restoration aura doesn't buff air transports

### ISSUE THREAD

**Issue by haifron** [FAForever/fa#4368]
**Describe the bug**
The seraphim ACU's restoration aura upgrades do not affect air transports, either by giving extra HP or extra HP regen. It does however heal other units that carry/transport units, such as even the stinger (UEF t2 gunship that has a slot for carrying units exactly like air transports).

**To Reproduce**
Spawn a seraphim ACU and any air transport. Give the ACU either restoration aura level. Even when the transport is in range of the restoration aura, it is not buffed by it.

**Expected behavior**
The air transport should have its max HP & HP regen buffed by the aura like every other unit in the game (except ACUs).

**Comment by MrRowey** [comment]
@Tagada14 I would put this under the question of the balance team close if not a bug as described

**Comment by MrRowey** [comment]
Regen Should only Buff Unit that are on the round not in the Air Like how Chrono Works

**Comment by Tagada14** [comment]
The regen field already affects all units, land, naval and air. It should also work on transport for consistency.
