### ISSUE TITLE
Aoen T3 torpedo bomber speed too high

### ISSUE THREAD

**Issue by EvildrewFAF** [FAForever/fa#4373]
**Describe the feature**
Some time ago, who knows when, T3 air speeds were nerfed, ASF, Strat, Scout, but T3 torpedo bomber wasnt, and so strategic bombers have a speed of 17, ASF 22, and T3 torp bombers still have it at 20. Should be have been reduced to 17 or 18 in line with the other speed reductions.

**Comment by Tagada14** [comment]
This is intended as the Solaces were pretty bad and therefore didn't need the speed nerf, it also plays well with their strength of going in and killing a single target quickly.

**Comment by EvildrewFAF** [comment]
> 

Fine...
