### ISSUE TITLE
Original Janus bomber fix

### ISSUE THREAD

**Issue by EvildrewFAF** [FAForever/fa#4374]
**Describe the feature**
This mod repeals the Janus bomber that drops bomber from the tip of its wings facing backwards and replaces it with the original Janus bomber which drops the bombs facing the right way and dropping from the right area of the plane. The undershoot issue that was the issue it was "fixed" to what we currently have is also fixed.

**Screenshots**
This is what we currently have.
![image](https://user-images.githubusercontent.com/46637108/200476557-1e852092-784a-4080-a3cb-ea274d1a0d20.png)

Mod including workable files, uploaded as Original Janus Bomber fix in the vault for testing
[Original Janus Bomber fix.zip](https://github.com/FAForever/fa/files/9957638/Original.Janus.Bomber.fix.zip)

This is a video of how it works correctly.
https://user-images.githubusercontent.com/46637108/200476068-fc7fe76d-6501-4409-b0a8-47aa0154303d.mp4

**Comment by Tagada14** [comment]
If it would be just visual effects then I would be okay with it but this change would effectively revert the Janus to its old boring version, being just a better T1 bomber. That is not desired.
