### ISSUE TITLE
Transport crash damage inconsistent across tech levels

### ISSUE THREAD

**Issue by EvildrewFAF** [FAForever/fa#4384]
T2 transports are able to land and crash on t1 units with minor damage, whereas t1 transports do substantially more damage, even killing labs. This makes no sense. Should be addressed.

![image](https://user-images.githubusercontent.com/46637108/201117658-8065943a-7b7a-43c2-96cf-a8f5e6894fdf.png)

**Comment by EvildrewFAF** [comment]
IMO t2 transport was probably a typo when the value was entered and was intended to be 250...

**Comment by Garanas** [comment]
@Tagada14 all yours 😄

**Comment by Tagada14** [comment]
Will fix it, this will also act as a nice nerf to Arty drops
