### ISSUE TITLE
Submersed units need a feature to return to their set elevation in their BP

### ISSUE THREAD

**Issue by EvildrewFAF** [FAForever/fa#4397]
One issue with submersed units is that when they go through shallower water they rise to pass through and then stay at a higher elevation. Maybe someone can script so they seek to go back down to the elevation in the BP once possible without players having to emerge them and then resubmerge them?
As some bombers have an attack elevation, I suppose there is somewhere in some scribble code that has the solution to this issue with subs but I am not the one who has the coding knowledge to find this...

**Comment by Garanas** [comment]
🤔 , I think this is possible but I'm not sure yet. We could have submarines check periodically (say every 5 to 10 seconds) if they are at the correct depth after diving.

**Comment by EvildrewFAF** [comment]
A check every 5 seconds sounds good, we'll just have to make sure they don't follow that code while surfaced or in the process of surfacing.

**Comment by EvildrewFAF** [comment]
Postponed,...
