### ISSUE TITLE
Incorrect `RegenPerSecond` values for Restoration Field enhancements

### ISSUE THREAD

**Issue by Hdt80bro** [FAForever/fa#4439]
**Describe the bug**
The Steam version has the values for the Seraphim commander enhancements
```lua
        RegenAura.RegenPerSecond = 0.0055555555
AdvancedRegenAura.RegenPerSecond = 0.01111111111
```
Sometime in FAF's prehistory, it got changed to
```lua
        RegenAura.RegenPerSecond = 0.02
AdvancedRegenAura.RegenPerSecond = 0.01111111111
```
Where the `RegenPerSecond` value of the Restoration Field is higher than that of the Advanced Restoration Field, meaning it's been stronger for the past decade. This was partially mitigated because tech level ceilings were also introduced, but that still means that units that have a certain maximum health based on the floor and ceiling of the enhancement will have more regen with the regular one. In particular,
 * The unit must have low enough maximum health so that the ceiling of the Restoration Field doesn't clamp the regen value to be smaller than regen value calculated with the smaller scalar of the Advanced Restoration Field.
 * The unit must have enough maximum health so that the regen gained from the Restoration Field is still greater than the floor of the Advanced Restoration Field (15 hp/s for all tech levels).

In practice, the actual value of `RegenPerSecond` doesn't usually matter since most units' maximum health multiplied by the `RegenPerSecond` value is almost always higher than the tech level's ceiling, but there are several units where this isn't true (recall that FAF also changed the enhancement from a `RegenPercent` affect type to a `Regen` type while hardcoding the `Mult` value in that case to scale by the unit's maximum health). For example:
 * The Rhino has 1,900 health. 1,900 * 0.02 = 38, much higher than the T2 ceiling of 15. For the advanced version, 1,900 * 0.0111 = 21.111, which is less than 38, but the T2 ceiling of 50 lets it actually be that value, so the advanced version is stronger in this case.
 * The Suthanus has 925 health. 925 * 0.02 = 18.5 which is less than the T3 ceiling of 25. For the advanced version, 925 * 0.0111 = 10.2777, but the floor is 15. Thus, it has just enough health that the floor of the Advanced Restoration Field don't raise the final result above the Restoration Field, and not enough health to make the ceilings matter.

Note that the restoration fields also increase the maximum health of the unit (by x1.1 for regular and x1.2 for advanced), but the calculation doesn't use this result (if it did, the Advanced Restoration Field *still* wouldn't be stronger, as 0.0111 * 1.2 = 0.01333 < 0.022 = 0.02 * 1.1).

**To Reproduce**
Take a Seraphim commander and give it the Restoration Field.
Now take, say, the Seraphim T3 Mobile Heavy Artillery Suthanus (it meets the criteria above). Should look like this:
![image](https://user-images.githubusercontent.com/37224614/203619681-b4436ca2-acb1-41cd-8e62-140cd40ed984.png)
Upgrade the commander to the Advanced Restoration Field. Should look like this now:
![image](https://user-images.githubusercontent.com/37224614/203619833-6c872ba7-cf47-4cbf-bef7-bbd73d867272.png)
Note the decrease from +18/s to +15/s.

**Expected behavior**
*The Advanced Restoration Field should always be stronger than the Restoration Field*

**Comment by MrRowey** [comment]
@Spikey84

**Comment by MrRowey** [comment]
@Tagada14

**Comment by MrRowey** [comment]
@Hdt80bro can you apply this fix in a PR Seems like a Small bug and can get it added in this balance patch

**Comment by MrRowey** [comment]
So Something like

```
RegenAura.RegenPerSecond = 0.02
AdvancedRegenAura.RegenPerSecond = 0.04
```
