### ISSUE TITLE
Keybind option for "select all navy, not sonar"

### ISSUE THREAD

**Issue by Deribus** [FAForever/fa#4459]
**Describe the feature**
A keybind option for "select all navy, not sonar"

**Expected behavior**
I don't want to send my poor T3 sonar to its death every time I select all navy and forget to deselect sonar. Expected behavior should be pretty clear

**Comment by Garanas** [comment]
@xXEddieXxx This one is a good-first-issue, do you have the time and interest to pick this up?

**Comment by xXEddieXxx** [comment]
@Garanas will Look into it

**Comment by xXEddieXxx** [comment]
@Garanas  is this closed ? :D

**Comment by Garanas** [comment]
Oh, yes 😄

**Comment by Garanas** [comment]
And good job on the pull request 👍
