### ISSUE TITLE
AI - Marker Cache implementation

### ISSUE THREAD

**Issue by relent0r** [FAForever/fa#4467]
**Describe the bug**
Have run into another issue with the marker cache. I should have spotted this when I was testing it before but it wasn't until I started logging all the supporting functions that it popped out.

by marker cache I mean MarkerUtilities.lua

It looks like when the AI gets markers it will build another table and use this format.
`table.insert(markerList, {Position = v.position, Name = k})`

The issue seems to be how it uses the marker key for the Name attribute. In the cache they are just integers where as in the original they are strings.

e.g
`Expansion Area 8` vs `8` or whatever the count was up to.

Initially I didn't think it would matter much but it looks like there are multiple places where the AI is checking those keys against other things.

It would make for some invisible failures in the AI's logic that would be very hard to track down. 
example, this one will compare the markers name to the base name but this could potentially be false due to the key name.
```lua
function AIFindMarkerNeedsEngineer(aiBrain, pos, radius, tMin, tMax, tRings, tType, positions)
    local closest = false
    local retPos, retName
    local positions = AIFilterAlliedBases(aiBrain, positions)
    for _, v in positions do
        if not aiBrain.BuilderManagers[v.Name] then
            if not closest or VDist3(pos, v.Position) < closest then
                closest = VDist3(pos, v.Position)
                retPos = v.Position
                retName = v.Name
            end
        else
            local managers = aiBrain.BuilderManagers[v.Name]
            if managers.EngineerManager:GetNumUnits('Engineers') == 0 and managers.FactoryManager:GetNumFactories() == 0 then
                if not closest or VDist3(pos, v.Position) < closest then
                    closest = VDist3(pos, v.Position)
                    retPos = v.Position
                    retName = v.Name
                end
            end
        end
    end

    return retPos, retName
end
```

It could just be a matter of changing the key to be something like `type ..'  '..count + 1` sort of thing.

**Comment by Garanas** [comment]
@relent0r this would be a drastic API change, where instead of receiving an array-based table and its count, you'd just receive a hash-based table. Is that fine?

**Comment by relent0r** [comment]
> @relent0r this would be a drastic API change, where instead of receiving an array-based table and its count, you'd just receive a hash-based table. Is that fine?

If its less effort can we do what the default AIGetMarkerLocations function does (which I think is the same as what you did with armies) where the .name property is added to all marker cache entries with the original key? That way we would still have the correct data required

e.g
```
function AIGetMarkerLocations(aiBrain, markerType)
    local markerList = {}
    if markerType == 'Start Location' then
        local tempMarkers = AIGetMarkerLocations(aiBrain, 'Blank Marker')
        for k, v in tempMarkers do
            if string.sub(v.Name, 1, 5) == 'ARMY_' then
                table.insert(markerList, {Position = v.Position, Name = v.Name})
            end
        end
    else
        local markers = ScenarioUtils.GetMarkers()
        if markers then
            for k, v in markers do
                if v.type == markerType then
                    table.insert(markerList, {Position = v.position, Name = k})
                end
            end
        end
    end

    return markerList
end
```

**Comment by Garanas** [comment]
I can do that.

**Comment by Garanas** [comment]
Resolved - all markers that go through the marker utilities should now have a `Name` property. See also: https://github.com/FAForever/fa/pull/4569
