### ISSUE TITLE
Automatch popup background

### ISSUE THREAD

**Issue by Sheeo** [FAForever/fa#447]
With the new popup UI, it looks a bit bad with the background:

![automatch screen botched](https://cloud.githubusercontent.com/assets/37968/5986751/1d8ec4fc-a908-11e4-85c4-dc042ede01d1.png)

**Comment by aeoncleanse** [comment]
What resolution is that?

**Comment by Sheeo** [comment]
1280x1440

**Comment by aeoncleanse** [comment]
I just find it odd that the darkener is not applying itself to the entire screen
