### ISSUE TITLE
Galactic colossus under construction hitbox incorrect

### ISSUE THREAD

**Issue by maudlin27** [FAForever/fa#4470]
Summary:
A galactic colossus was given an attack order on an enemy GC that was under construction,  the firing GC's beam went through the under construction GC and hit the ground behind it.  This happened from several angles.  I'm assuming the issue is connected with the hitbox of the GC or the change made a number of months ago for GC and Aeon units being constructed.

Screenshots:
In both the below examples the GC was firing for a number of seconds (with an attack order having been given):
![GC Shot1](https://user-images.githubusercontent.com/95254039/205372619-0c1d5bc6-b724-4b65-84d8-d51221fd63d2.jpg)

![GC shot 2](https://user-images.githubusercontent.com/95254039/205372671-8ed3701b-c94a-4d4a-93b4-2150f7a5786c.jpg)

Other:
Observed in a human vs AI game, not sure on the replay number now but as it was late on in a game that runs at -2 at times (with a good CPU) so I expect it'd be much faster to recreate in sandbox than to view the replay.

**Comment by Garanas** [comment]
![image](https://user-images.githubusercontent.com/15778155/207577472-e4fe92f0-6974-41d9-b198-343a215191a7.png)

Appears this needs a similar fix like we did with the megalith in #4102: we manually adjusted the collision box during construction and then restore it when the unit is complete.

@xXEddieXxx could I encourage you to pick this up? Note that there are two different build animations. The hotkeys you can use are:
- `CTRL + ALT + SHIFT + C`: show collision boxes
- `ALT + V` : show bones
- `ALT + B`: show bone names

The goal would be to have a collision box that fits both build animations from start to finish., initially it will likely extend over the colossus quite a bit - that is fine.
