### ISSUE TITLE
Units in factories are attached to wrong position

### ISSUE THREAD

**Issue by speed2CZ** [FAForever/fa#4478]
I've noticed this bug with UEF and Aeon naval factories so far. T2 and T3
![ForgedAlliance_2022-12-05_12-08-43](https://user-images.githubusercontent.com/10947024/205623210-8a0ad06d-2b2f-4bdc-b102-65cc3da9069e.jpg)

**Comment by Garanas** [comment]
I thought I fixed this, odd. I'll look at it again.

**Comment by speed2CZ** [comment]
At least with the UEF factory, it looks like the unit is spaced correctly if it's facing south when being produced.
If it's facing north, it's in the incorrect position.
