### ISSUE TITLE
Lobby Chat Intersect at High UI Scales

### ISSUE THREAD

**Issue by Deribus** [FAForever/fa#4480]
**Describe the bug**
At high UI scales and/or resolutions lobby chat has insufficient spacing and starts to intersect with the previous message

**To Reproduce**
Screenshot was taken on a 4k screen at 1.75 UI scaling

**Expected behavior**
Some more spacing between lines pls

**Screenshots**
[One screenshot, as requested](https://imgur.com/a/pGobQCb)

**Comment by Garanas** [comment]
Note that you can drag and drop screenshots into the text box 😄
