### ISSUE TITLE
sera t2 sonar erroneously has rebuild bonus

### ISSUE THREAD

**Issue by haifron** [FAForever/fa#4493]
### Issue
Of the 4 mobile sonars (and all non structure units) only seraphim's T2 sonar gets a rebuild bonus, under the `Economy` section of the blueprint:
https://github.com/FAForever/fa/blob/develop/units/XSB3202/XSB3202_unit.bp#L128-L129
compared to 
- [Aeon](https://github.com/FAForever/fa/blob/develop/units/UAS0305/UAS0305_unit.bp#L103-L108)
- [Cybran](https://github.com/FAForever/fa/blob/develop/units/URS0305/URS0305_unit.bp#L125-L130)
- [UEF](https://github.com/FAForever/fa/blob/develop/units/UES0305/UES0305_unit.bp#L123-L128)

### Replicate
Replicate it by building a sera t2 sonar, ctrl k it, then issue a build command for a t2 sera sonar on the exact same location. Wreckage disappears, sonar starts at 45% completion while with other sonars the same process results in the wreck being reclaimed first, like with experimental units.

It's the only non-structure unit (no `STRUCTURE` in `Categories`) that has a rebuild bonus.

### To fix
delete [L128-L130 in the bp](https://github.com/FAForever/fa/blob/develop/units/XSB3202/XSB3202_unit.bp#L128-L130).

**Comment by Garanas** [comment]
@xXEddieXxx Can I interest you to pick this one up? It appears the rebuild bonus was not removed when the sonar was allowed to move around.

**Comment by xXEddieXxx** [comment]
Sure :)

**Comment by haifron** [comment]
Closed by #4502
