### ISSUE TITLE
Error when attacking

### ISSUE THREAD

**Issue by ChrisKitching** [FAForever/fa#452]
STR:

Spawn as UEF ACU.
Set "attack ground"
Press "A" (The attack hotkey).

This happens:

```[C]: in function `SetScale'
         	...users\chris\dropbox\fa\lua\ui\controls\worldview.lua(209): in function <...users\chris\dropbox\fa\lua\ui\controls\worldview.lua:142>
WARNING: Error running OnUpdateCursor script in CScriptObject at 1c658300: attempt to index a nil value
         stack traceback:
         	[C]: in function `SetScale'
         	...users\chris\dropbox\fa\lua\ui\controls\worldview.lua(209): in function <...users\chris\dropbox\fa\lua\ui\controls\worldview.lua:142>
WARNING: Error running OnUpdateCursor script in CScriptObject at 1c658300: attempt to index a nil value
         stack traceback:
         	[C]: in function `SetScale'
         	...users\chris\dropbox\fa\lua\ui\controls\worldview.lua(209): in function <...users\chris\dropbox\fa\lua\ui\controls\worldview.lua:142>
WARNING: Error running OnUpdateCursor script in CScriptObject at 1c658300: attempt to index a nil value
         stack traceback:
         	[C]: in function `SetScale'
         	...users\chris\dropbox\fa\lua\ui\controls\worldview.lua(209): in function <...users\chris\dropbox\fa\lua\ui\controls\worldview.lua:142>
WARNING: Error running OnUpdateCursor script in CScriptObject at 1c658300: attempt to index a nil value```

**Comment by aeoncleanse** [comment]
This is fixed
