### ISSUE TITLE
Invincible 1HP ACUs

### ISSUE THREAD

**Issue by Deribus** [FAForever/fa#4541]
**Describe the bug**
Not too sure how it happens since I've not encountered it myself, just gotten reports about it. ACU gets down to 1 hp but is unable to take any further damage and is hence invincible.

**To Reproduce**
 ¯\_(ツ)_/¯
Here's the first time I'm aware of it happening. To Dolly around the 49 minute mark.
[18846072.zip](https://github.com/FAForever/fa/files/10323740/18846072.zip)
Was also recorded on a stream: https://www.twitch.tv/fartoobaked/clip/SassySavageTurnipMau5-l-rEzLt4L22Zhi_Q

Also happens to Sasuke-Uchiha in this replay which isn't available yet at time of writing: [18867615](https://replay.faforever.com/18867615)
 
**Expected behavior**
[A clear and concise description of what you expected to happen.](https://www.youtube.com/watch?v=t9wmWZbr_wQ)

**Comment by MrRowey** [comment]
@Hdt80bro Seems the Dolly Click recall and the ACU became Invulnerable after click it with being the only player alive on his team. maybe the recall button should be be greyed out if you are the last player or something ?

**Comment by Garanas** [comment]
@Hdt80bro do you have time to look into this? I can do so over the weekend. I'd like to include the fix in the snowflake removal patch.

**Comment by Hdt80bro** [comment]
I'll see if I can

**Comment by magge-faf** [comment]
@Hdt80bro Is there any update on this matter, or is it currently indefinitely on hold? The bug causes an influx of reports, it would be awesome to get rid of the bug in the next patch.
