### ISSUE TITLE
ShowEscapeDialog failing

### ISSUE THREAD

**Issue by aeoncleanse** [FAForever/fa#455]
Happens when I've been into the lobby, then exit that via the back button to the main menu, then try to quit via the top-right X in windowed mode. Gives an error instead of quitting.

WARNING: Lobby escape handler called
WARNING: Error running '/lua/ui/uimain.lua:ShowEscapeDialog': c:\github\fa\lua\ui\lobby\lobby.lua(543): attempt to call method `AbandonFocus' (a nil value)
        stack traceback:
            c:\github\fa\lua\ui\lobby\lobby.lua(543): in function `?'
            c:\github\fa\lua\ui\dialogs\eschandler.lua(57): in function `HandleEsc'
            ...r forged alliance\gamedata\lua.scd\lua\ui\uimain.lua(108): in function <...r forged alliance\gamedata\lua.scd\lua\ui\uimain.lua:107>

**Comment by aeoncleanse** [comment]
This is still a big problem. I've encountered times where, if the lobby build errors due to changes I've made, I'm unable to quit FA except by terminating the process in task manager because the X button doesn't work.

**Comment by ChrisKitching** [comment]
It's been nineteen hours since you first reported it: please don't fill our inboxes unless you have some new information.

**Comment by ChrisKitching** [comment]
Solved in a7d49d8195059d600536f0630a3476291b5bfbbf
