### ISSUE TITLE
Assisted Mexes Showing Progress When Paused

### ISSUE THREAD

**Issue by Spikey84** [FAForever/fa#4551]
**Describe the bug**
When a mexes is paused after the upgrade is started the progress bar will not be filled. This becomes an issue when assisting paused mexes. They will indicate the progress from when they were paused rather than the assisted progress. 

**To Reproduce**
Start a mex upgrade, pause it, assist with an engi, and watch as progress bar does not update.

**Expected behavior**
The progress bar should update along with the assistance regardless of paused status.

**Screenshots**
![image](https://user-images.githubusercontent.com/68761514/210453425-5a6a21b2-3317-4adb-ae5c-2b4a6fd3a507.png)
Notice that the ACU indicates a progress of 50% while the mex shows 0-1%.

**Additional context**
![image](https://user-images.githubusercontent.com/68761514/210453781-672594a9-4d40-45ee-afbc-3349368f4434.png)
The same issue happens when doing the exact same thing with factories. Seems not to be an issue for Tacs/SMD.

I always assumed this could not be fixed. But if it can be it would hugely improve the quality of life when ecoing. Thanks for everyone's work!

**Comment by 4z0t** [comment]
@Garanas is progress bar controlled by the engine? If it is then engine fix required.

**Comment by Spikey84** [comment]
Seems up @KionX's alley.

**Comment by Garanas** [comment]
https://user-images.githubusercontent.com/15778155/210508898-9cad951f-e4cf-4b5c-8aea-5d94612dabdf.mp4

Both - Lua can control it too. I'll leave it up to Kionx to determine whether an engine patch is better. From a Lua perspective it isn't a lot of code, and it doesn't cost us anything either.

**Comment by KionX** [comment]
I'll take a look at this.

**Comment by Garanas** [comment]
@Spikey84 KionX made an engine patch, and that is now deployed. Can you test it, by hosting a game on FAFDevelop via the client?

**Comment by Garanas** [comment]
This is fixed with thanks to the engine patch.
