### ISSUE TITLE
Cybran lazer occasionally not firing

### ISSUE THREAD

**Issue by IndexLibrorumProhibitorum** [FAForever/fa#4553]
**Describe the bug**
The Cybran lazer sometimes refuses to fire. This is a problem because a Cybran telemazer com (teleport upgrade, gun upgrade, lazer upgrade) often requires the veterancy gains to stay alive during telesnipes.

**To Reproduce**
This happens sporadically, and I have not been able to replicate the bug at will.

**Expected behavior**
The laser to not jam.

**Screenshots**
[Replay ID #18787613](https://replay.faforever.com/18787613), at minute 23:20. This is after the second teleport, no issue was experienced during the first teleport a minute prior.

**Comment by IndexLibrorumProhibitorum** [comment]
Issue occurred again. #19427696, around minute 30 mark. Laser did not fire right after teleport. Resulted in a dead com.

**Comment by ChessBerry** [comment]
Added a bug report on the discord: https://discord.com/channels/197033481883222026/1168847788558270494

**Comment by Garanas** [comment]
Alleviated with https://github.com/FAForever/fa/pull/5611
