### ISSUE TITLE
Error in develop

### ISSUE THREAD

**Issue by aeoncleanse** [FAForever/fa#456]
Getting this warning on lobby creation

WARNING: SCR_LuaDoFileConcat: Loading "c:\github\fa\loc\us\strings_db.lua" failed: c:\github\fa\loc\us\strings_db.lua(6733): unfinished string near `"

**Comment by ChrisKitching** [comment]
You sure there's no mod being loaded? That file is only 6677 lines long.

**Comment by aeoncleanse** [comment]
Oops. I do seem to be unable to DISable the mod though...

WARNING: Error running OnRelease script in <deleted object>: c:\github\fa\lua\ui\lobby\lobby.lua(2000): attempt to call method `IsHost' (a nil value)
         stack traceback:
         	c:\github\fa\lua\ui\lobby\lobby.lua(2000): in function `OnModsChanged'
         	c:\github\fa\lua\ui\lobby\modsmanager.lua(186): in function `OnClick'
         	...d alliance\gamedata\mohodata.scd\lua\maui\button.lua(133): in function <...d alliance\gamedata\mohodata.scd\lua\maui\button.lua:122>

**Comment by Sheeo** [comment]
Which mod is this?

**Comment by aeoncleanse** [comment]
It was my balance preview mod

**Comment by aeoncleanse** [comment]
I can't reproduce this now. Seems to have gone.
