### ISSUE TITLE
Cybran T3 Torpedo Launchers are reclaimable when SetReclaimable(false) is used.

### ISSUE THREAD

**Issue by piisawheel** [FAForever/fa#4573]
**Describe the bug**
A clear and concise description of what the bug is. Do not forget to append the game logs.
Spawning in a Cybran t3 torpedo launcher, and then setting the unit to unreclaimable allows it to still be reclaimed.

When tested on t3 seraphim Anti air turret (xsb2304) the unit is unreclaimable as expected.
No other units were tested.

**To Reproduce**
Spawn in a t3 torpedo launcher.  Run the appropriate command to cause unit to be un-reclaimable.  Use something to reclaim it.

My code looks like this:
	local unit = CreateUnitHPR('xrb2308', 'ANGRY_CIVILIAN', posx, GetSurfaceHeight(posx, posz), posz, 0, 0, 0)
	unit:SetCapturable(false) -- this works as expected.
	unit:SetReclaimable(false) --this doesn't work as expected.

**Expected behavior**
Using the reclaim should fail when attempting to reclaim t3 torpedo launcher, the same way it fails on Seraphim t3 aa and other units.

This bug seems to affect Nomads as well (i'm assuming that is the same base codebase and nomads are just added in).

**Comment by Garanas** [comment]
The cybran tech 3 torpedo launcher is nothing but normal 😄 - what secretly happens when you spawn it is that it is replaced with a different unit, one that sinks. This allows you to target it as it is being build - and once finished, it is considered a submarine.

The reason it doesn't work is because you likely set the flag to the structure that you spawn, but not to the structure that actually ends up existing.

**Comment by piisawheel** [comment]
> The cybran tech 3 torpedo launcher is nothing but normal smile - what secretly happens when you spawn it is that it is replaced with a different unit, one that sinks. This allows you to target it as it is being build - and once finished, it is considered a submarine.
> 
> The reason it doesn't work is because you likely set the flag to the structure that you spawn, but not to the structure that actually ends up existing.

That makes perfect sense.  I did not know that.  So I *actually* want to spawn in a different unit, the end product, and set *that* to unreclaimable.  So why does "Set capturable" work as intended?  is that data passed to the end product but set reclaimable is not?  That almost sounds like a different bug...

**Comment by Garanas** [comment]
I have no idea.

**Comment by piisawheel** [comment]
Okay I have tested with unit xrb2309, which is referenced in the unit files of 2308 and now it functions as expected.
So I will close this since it doesn't really apply.

I don't know if xrb2309 *not* inheriting "reclaimable" but *is* inheriting "uncapturable" from xrb2308 should be considered a bug or if it's a big enough deal to care.

**Comment by Garanas** [comment]
It doesn't inherit it - the unit does not have the `CAPTURE` category when it sinks. Therefore it is never capturable.

Long story short: it is a unit with a problem or two.

**Comment by piisawheel** [comment]
That makes a lot of sense behavior wise then.  Before, capture would "Complete" (the bar would fill) but then fail.  SetCapturable to false cause capture to be removed from the order queue when it comes up, so it's not even attempted.
