### ISSUE TITLE
New sound effects

### ISSUE THREAD

**Issue by Blodir** [FAForever/fa#4575]
**Describe the feature**
Add a bunch of new sound effects for gameplay relevant actions:
* t2/t3 mex completed
* t2/t3 land/air/navy completed

**Expected behavior**
An option to enable/disable (or even better, volume slider) for the new sounds would be a good addition.

**Additional context**
Obviously requires some work from sound design perspective. If we can figure that part out though this feature would be extremely useful.

**Comment by Garanas** [comment]
I'm all for sound notifications. I'm just not an audio artist or engineer 😄 . These can be completely custom, and maybe even embedded into notify to some degree

**Comment by Garanas** [comment]
@Blodir suggestions on how to proceed with this?

**Comment by Blodir** [comment]
I suppose the bottleneck is finding a sound designer to create the sound fx? I can technically potentially work on that at some point, but I can't promise anything and can't give a timeline. I guess we could open a forum thread and ask if someone is up for this.

**Comment by Garanas** [comment]
I'm closing this, still open to it but without a sound designer of some kind then we've got nowhere to go. There is this that we could eventually use:

- https://beta.elevenlabs.io/

But none of them sound very supreme commander-isch
