### ISSUE TITLE
Problems with option screen random map

### ISSUE THREAD

**Issue by aeoncleanse** [FAForever/fa#460]
Trying this to destruction, it got destroyed... There are problems applying the button when you've filtered.I tried by map size, and it kept throwing certain maps out that were not the right size. It also refused to select some which were. Eventually, as I kept clicking, the button just outright crashed the game. I'll look into it further but there's some work to do here I think. The main lobby version of tge button crashes the game too, eventually. Event handler labels the crash as BEX, which I've not seen before. Nothing in the log.

**Comment by ChrisKitching** [comment]
I've seen the crashing: it's most probably a bug in the native code behind itemlists that causes them to explode if you very rapidly change their selected item.

Thanks, William.

Here is the two-line implementation of the in-option-menu random map button:
```Lua
randomMapButton.OnClick = function(self, modifiers)
        local randomMapIndex = math.floor(math.random(1, mapList:GetItemCount()))
        mapList:OnClick(randomMapIndex)
 end
```

It literally just calls OnItemClicked for a random item in the map list. This means that, if the filters are showing the right stuff in the options menu, the button can only pick one from that list.

> It also refused to select some which were.

It's random. You would have to click an infinite number of times to prove this.  :p

**Comment by aeoncleanse** [comment]
300 clicks is a pretty BLOODY good indicator that it's simply not selecting correctly, and yes, I did indeed click that many times to try it.

Try it: Go to options, set filter to 81*81. On my version, with few custom maps downloaded, it filters to Betrayal Ocean, Debris, and Frostmill Ruins.

The random button then returns a mix of Alpha 7 Quarantine, a 40k not even in the display, Frostmill Ruins, and Debris. Betrayal Ocean will never come up.

Now go to 5*5 filter. For me, that's Ambush, Blasted, Canis, Crag, Four-Corners, Sentry, Sludge, Theta, Williamson's, Winter.

I get Blasted, Canis, Crag, Four-Corners, Sentry, Sludge, Theta, Williamson's, Winter,  Daroza's Sanctuary (Not in the list), Setons (Not in the list), Never gets me Ambush Pass, the first on the list again... I don't know what's wrong, I haven't the foggiest, but something, somewhere, isn't working as you're expecting. Is mapList updating properly? Perhaps the listed maps, the top one is assigned to 0? Perhaps random 1 -> maplist never returns == 1?

**Comment by Sheeo** [comment]
According to the [lua documentation](math.random(lower, upper) generates integer numbers between lower and upper):

```math.random(lower, upper) generates integer numbers between lower and upper.```

So we should be good here, and infact `floor()` should be unnecessary, but that's a detail.

Crash needs its own thread.

**Comment by aeoncleanse** [comment]
Wait, so what just happened?

**Comment by ChrisKitching** [comment]
Oh, right, William made item lists 0 based, so the range needs to be shifted down by one, that's probably the cause of the crash, too, as it'll be requesting an out of range value.

Thanks, William.

**Comment by Sheeo** [comment]
Good catch :+1:
