### ISSUE TITLE
Build Menu Resets selected options when platoon changes size (units die)

### ISSUE THREAD

**Issue by piisawheel** [FAForever/fa#4601]
**Describe the bug**
See Title.

**To Reproduce**
Go into a game.  Create 5 cybran support commanders.  Select a *different* option on the build menu (maybe you want to see the t2 cerberus for example).  Destroy 1 Unit (maybe put him near an enemy turret so he dies while you have the platoon selected - or self d and select the platoon before the countdown).  The menu has reset back to tier 3 (the default) because the platoon changed sizes (1 unit was killed).  This is *extremely* annoying to those of us with low apm, who, in the middle of a firefight, have to spam t2 and then hope we can select the cerberus turret before 1 of your 50 units dies and reset the build menu back to t3.  I've selected the t3 torpedo launcher so many times in survival it's not funny, and almost frustrated me to the point of rage quitting the game I was in (survival ffa, not leaving a team screwed).

**Expected behavior**
When units are already selected, and the squad changes size *not due to player interaction* (units die), the menu should not reset, unless no units are alive that can build that tier.

**Comment by Garanas** [comment]
We'll pick it up 👍
