### ISSUE TITLE
Message marker position changes during the game

### ISSUE THREAD

**Issue by OCGDFS** [FAForever/fa#462]
During the game or watching a replay, message marker change their position to outside the map, or are set outside the map in replay

**Comment by Crotalus** [comment]
Are you sure they are not simply moved by players? It's a quick way to "delete" markers

**Comment by Sheeo** [comment]
This will not happen magically -- an issued command is needed for a message marker to move position.

Unless we can get a replay where this happens without such a command being issued, I'm closing this.

**Comment by OCGDFS** [comment]
i can give u a lot of replays because it is in nearly every game the case.

**Comment by Sheeo** [comment]
Do provide.

**Comment by OCGDFS** [comment]
![bildschirmfoto vom 2015-02-04 00 14 42](https://cloud.githubusercontent.com/assets/7430874/6031873/46540390-ac03-11e4-8cd3-09a2dd38b8a1.png)
 replay id: 3054357

**Comment by OCGDFS** [comment]
![bildschirmfoto vom 2015-02-04 00 31 15](https://cloud.githubusercontent.com/assets/7430874/6032105/75e3b748-ac05-11e4-8395-f5d7f9da47e4.png)
ok Crotalus i forgot that, but in this replay sone marked sonar on the beach navy spot and suddenly it moves outside the map ~min 16:30
ID: 3052735

**Comment by Sheeo** [comment]
Markers were moved in that replay (According to the commandstream) at the following times near 16 minutes:
```
Marker updated at 0:14:49
Marker updated at 0:15:48
Marker updated at 0:16:18
Marker updated at 0:16:19
Marker updated at 0:16:49
Marker updated at 0:18:17
```

**Comment by aeoncleanse** [comment]
Basically, another player was moving them to get the out of the way, without asking or notifying you.
