### ISSUE TITLE
Seraphim

### ISSUE THREAD

**Issue by TJCUPP** [FAForever/fa#463]
Hello, 

Over the last 2 weeks. Me and a few people I regularly play with have noticed some issues with Seraphim. 

First : Strat bombers - They rarely fire on the first drop. They'll just fly over the target, then fly back to bomb it. They won't micro at all or do what you command. They cancel the command to attack.

Second - Commanger. This is only happened once - only had the opportunity to do it once. I had a fully upgraded commander and dropped it in water, walked it in land. It was firing and everything was fine. Then he stopped moving, wouldn't respond to commands and just stood there (In front of T1 PD) As you can imagine - he blew up. But my issue was that he refused to move at all? 

Thanks,

If you would like to discuss this more via FAF chat - JustDont

**Comment by ResinSmoker** [comment]
There are a few reasons i can think of here...
-RandomTurnMulti could be influencing things and thus making it difficult for the unit to line up for the attack.
-The minimum attack distance required to line up on the target is large enough that the bomber may not be able to face the target in time if its too close when the attack was initiated.
-Weapon has too tight of a firing arc or tolerance.

**Comment by Sheeo** [comment]
Need replay ID's for this, and it should be split up into seperate issues.
