### ISSUE TITLE
UI-Scaling deletes player position Info/Colours from Game Lobby

### ISSUE THREAD

**Issue by Khayul** [FAForever/fa#4646]
UI-Scaling deletes player position Info/Colours from Game Lobby.

If you play on a larger resolution, for example 4k, you can use the UI upscaling to be actually able to read the information. However after you use the setting and join a lobby, the colours and map positions go missing.

![20230128025137_1](https://user-images.githubusercontent.com/123786659/215235713-778620e6-9d15-4151-97dc-110cb19ac7c2.jpg)

UI Scaling should not remove the ability to see the positions of other players and yourself in the game lobby.

**Comment by 4z0t** [comment]
Can you point out what's exactly wrong here in the image? I see no issues.

**Comment by Khayul** [comment]
> Can you point out what's exactly wrong here in the image? I see no issues.

if you zoom in enough on the Map, you can see that all of the Commanders have 100% transparent colours, therefore not showing on which spot they are.

**Comment by 4z0t** [comment]
Can you provide me with screenshot when the option "optimal balance: mirrored" is on and off?

**Comment by speed2CZ** [comment]
4K, 150% scale, current dev

![ForgedAlliance_2023-02-13_10-37-03](https://user-images.githubusercontent.com/10947024/218426496-51ed53d9-c735-4e65-aa42-22a90a838e4a.png)
