### ISSUE TITLE
Issue launching from FAF/Joining a Jobby.

### ISSUE THREAD

**Issue by SteseDav** [FAForever/fa#4653]
An Error Occurs when trying to join a lobby (Either joining another players lobby or creating my own)

![image](https://user-images.githubusercontent.com/8818293/215338871-ab208d82-7b87-4b5a-8b58-92c4b26109a9.png)

IPV6 is disabled, Windows Firewall open for FAF.

v2023.1.0

**Comment by Garanas** [comment]
This is fixed with the hot fix for the client. Make sure you update vo version `2023.1.1`. See also:

- https://forum.faforever.com/topic/5521/client-release-2023-1-1
