### ISSUE TITLE
Preset creation is broken

### ISSUE THREAD

**Issue by ChrisKitching** [FAForever/fa#467]
Attempts to create a new preset result in:

WARNING: Error running OnRelease script in <deleted object>: attempt to use as string a nil value
         stack traceback:
         	[C]: in function `AddItem'
         	c:\users\chris\dropbox\fa\lua\ui\lobby\lobby.lua(5299): in function `RefreshAvailablePresetsList'
         	c:\users\chris\dropbox\fa\lua\ui\lobby\lobby.lua(5232): in function `ShowPresetDialog'
         	c:\users\chris\dropbox\fa\lua\ui\lobby\lobby.lua(3304): in function `OnClick'
         	...d alliance\gamedata\mohodata.scd\lua\maui\button.lua(133): in function <...d alliance\gamedata\mohodata.scd\lua\maui\button.lua:122>

**Comment by aeoncleanse** [comment]
I don't get this on Develop, preset creation works fine for me.

**Comment by ChrisKitching** [comment]
Seems like it was actually just some broken data from an earlier version lurking in my profile.
Unless there's a route from a fresh profile to this, this isn't a real bug.
