### ISSUE TITLE
Migrate dialog_txt.lua to use existing localisation system

### ISSUE THREAD

**Issue by ChrisKitching** [FAForever/fa#470]
For some reason, hotstats and friends uses its own, deeply broken, hardcoded-to-english localisation system.

Someone who is extremely bored needs to look at /lua/ui/dialogs/dialog_txt.lua, merge its contents with the various localiser string databases, and update every use of dialog_txt.lua:trad() with an appropriate call to LOC.

**Comment by Sheeo** [comment]
That milestone should eventually be renamed to something like "In a long time ..."

**Comment by ChrisKitching** [comment]
"Some sunny day"

**Comment by Sheeo** [comment]
> In a galaxy, far far away

**Comment by aeoncleanse** [comment]
Well holy crap we have a hero. It seems Luke Skywalker killed the Emperor after all! https://github.com/FAForever/fa/pull/1573
