### ISSUE TITLE
Cybran MAA and cruiser firing delay

### ISSUE THREAD

**Issue by RabidPope** [FAForever/fa#4700]
**Describe the bug**
Units that have a targeting laser seem to have a delay when first engaging a target. The turret will turn but will only start firing after a short delay. This behavior does not seem to be present in other MAA and cruisers, 

**To Reproduce**
Have an air unit fly over these units and look at the turret. The air units get much closer than they would otherwise before the cybran units start firing.

**Expected behavior**
Turrets fire as soon as they face the target like other units of same type.

**Comment by Garanas** [comment]
This is a balance issue, @Tagada14 what do you want here?

**Comment by Tagada14** [comment]
I don't understand why there should be a delay, it doesn't make much sense neither game-design-wise nor balance-wise. If possible please remove it.

**Comment by RabidPope** [comment]
My guess is that because aa mode for these weapons are set to ground attack mode by default, they have some sort of delay when switching over to AA mode. This can be seen in the units script file. My HDD with the test environment broke so I am currently unable to test.

**Comment by RabidPope** [comment]
Ok so keeping the aa gun enabled kind of fixes it. But I realised the turret is broken even on live version.
![image](https://user-images.githubusercontent.com/55444317/220216578-73e690bb-496b-446c-a42f-6fb9ca679413.png)

**Comment by RabidPope** [comment]
@Garanas I don't agree that this is a balance issue. It basically stems from the fact that unit scripts don't trigger as regularly as they should. I don't know if there is a way to change that. 
Also how do I link this issue to a pull request?

**Comment by Garanas** [comment]
It is a balance issue because it changes balance, regardless whether it is a bug. For example: perhaps because of this delay the weapon received more range to compensate. Removing the delay would indicate a buff.

We should still fix it of course, but it is important to notify the balance people about it
