### ISSUE TITLE
Incorrect vet sync to UI

### ISSUE THREAD

**Issue by speed2CZ** [FAForever/fa#4702]
1. Select a unit with vet
![ForgedAlliance_2023-02-18_11-53-45](https://user-images.githubusercontent.com/10947024/219856503-3273fdf6-fbee-495b-820f-711987131dc7.png)

2. Mouse over other units that can't get vet (factory, shield, engie, etc...) and they will show the same amount of starts as the unit with vet.
![ForgedAlliance_2023-02-18_11-56-48](https://user-images.githubusercontent.com/10947024/219856598-5e90d212-ee52-4fc9-854f-d8ac9c7aa756.png)

**Comment by Garanas** [comment]
Fixed with #4703
