### ISSUE TITLE
Error on hitting mod manager 'OK' button

### ISSUE THREAD

**Issue by aeoncleanse** [FAForever/fa#471]
WARNING: Error running OnRelease script in <deleted object>: c:\github\fa\lua\ui\lobby\lobby.lua(2030): attempt to call method `IsHost' (a nil value)
         stack traceback:
         	c:\github\fa\lua\ui\lobby\lobby.lua(2030): in function `OnModsChanged'
         	c:\github\fa\lua\ui\lobby\modsmanager.lua(186): in function `OnClick'
         	...d alliance\gamedata\mohodata.scd\lua\maui\button.lua(133): in function <...d alliance\gamedata\mohodata.scd\lua\maui\button.lua:122>

I can't find the IsHost function anywhere, so it's either deleted, which would explain this, or it's native, which wouldn't.

**Comment by ChrisKitching** [comment]
You sure this is on current develop? Line 2030 of lobby.lua is an UpdateGame call, and I can't reproduce this.

STR, please.

**Comment by aeoncleanse** [comment]
What the hell... So I noticed this while making the new branch with the option screen stuff, and it was 100% happening when I finished. Posted that error right near the end. Now that I've published the branch, I can't reproduce! I'm sure I had some mods enabled, then I disabled them, then clicked the button and that's when this began to happen.

I'm very confused :/

**Comment by ChrisKitching** [comment]
Reopen if you can get clear STR.
