### ISSUE TITLE
AI files that use globals instead of locals

### ISSUE THREAD

**Issue by relent0r** [FAForever/fa#4717]
**Describe the bug**
While investigating a dead loop and looking for oddities I found a bunch of varaibles related to AI that are set as global instead of local. This could be causing issues with AI where they are sharing/modifying each others variables during games which would cause strange behavior.

I'll go through and look to fix the AI specific ones that I understand and consult others for ones that are not directly AI. The biggest culprits are the Sorian functions.

**List of noted fuctions and associated vars**

**aibehavours.lua**

function GetNavalPlatoonMaxRange
- [ ] isTech1 is not local
- [ ] selectedWeaponArc is not local

function CDRRunAway
- [ ] cmd is not local

function CDROverCharge
- [ ] searchRadius is not local
- [ ] enemyCdrThreat is not local
- [ ] friendlyThreat is not local

TempestBehavior = function(self)
- [ ] scoutPath is not local

function CDROverChargeSorian
- [ ] shieldPercent is not local
- [ ] enemyCdrThreat is not local
- [ ] friendlyThreat is not local

function CommanderThreadSorian
- [ ] moveOnNext is not local
- [ ] moveWait is not local

AhwassaBehaviorSorian
- [ ] cmd is not local

aibuildstructures.lua

function DoHackyLogic
- [ ]aiBrain is not local

**aiutilities.lua**

function AIGetSortedScoutingLocations
- [ ] rand is not local

function GetNearestPathingPoint
- [ ] retPos is not local

function AIFindPingTargetInRangeSorian
- [ ] unit is not local

function AIFindAirAttackTargetInRangeSorian
- [ ] unit is not local

function AIFindBrainTargetInRangeSorian
- [ ] unit is not local

function AIFindUndefendedBrainTargetInRangeSorian
- [ ] unit is not local

**sorianutilities.lua**

function AIHandleLandIntel
- [ ] nextBase is not local

function AIRandomizeTaunt
- [ ] tauntid is not local

function AIHandlePing
- [ ] nextping is not local

function FindUnfinishedUnits
- [ ] donePercent is not local

function FindDamagedShield
shieldPercent is not local

function Round(x, places)
- [ ] shift is not local
- [ ] result is not local

function CreateExplosionMesh
- [ ] proj is not local

**navgenerator.lua**
- [x] 451 z is not local
- [x] 466 z is not local

**maputil.lua**
function GetStartPositions
- [ ] 204 pos is not local

**unicountbuildconditions.lua**
function UnfinishedUnits
- [ ] 1395 donePercent

**Comment by Garanas** [comment]
Tackled the issue with `navgenerator.lua` via https://github.com/FAForever/fa/pull/4761
