### ISSUE TITLE
Improper reverse behavior for T2/T3 Aeon engineers

### ISSUE THREAD

**Issue by Basilisk3** [FAForever/fa#4720]
**Describe the bug**
In the most recent patch, the backup distance for all engineers was increased. However, the change does not appear to have an effect on Aeon T2 and T3 engineers.

**To Reproduce**
Simply issue a move order directly behind the engineers when playing. They will behave differently compared to other engineers.

**Expected behavior**
Aeon T2/T3 engineers should roughly behave the same as other engineers.

**Comment by Garanas** [comment]
We may have forgotton those, I'll look at it 👍
