### ISSUE TITLE
Integrate LazyShare

### ISSUE THREAD

**Issue by Sir-Prize** [FAForever/fa#474]
As per the title, I don't see a downside to integrating LazyShare with unbound buttons in the F1 menu. I guess it would mean the LazyShare mods in the vault would need blacklisting? I don't have the technical ability to do this, but as a general point the more this type of (I imagine) uncontroversial UI mod that just adds nice simple functionality to the game, like GAZUI and HotBuild that is integrated the better. Also, probably leads to less conflicts with other UI mods.

Thoughts?

**Comment by Sheeo** [comment]
:+1:

**Comment by aeoncleanse** [comment]
3652 is feature locked, moving to 3653

**Comment by HUSSAR-mtrela** [comment]
i think we are better off with integrating SSB mod which has UI functionality of LazyShare mod 
http://forums.faforever.com/viewtopic.php?f=41&t=10887

**Comment by Crotalus** [comment]
Yes would be nice to integrate that and at the same time sync some ally economy info so we can give better overflow information in UI during games.

**Comment by HUSSAR-mtrela** [comment]
@Crotalus speaking of ally economy info, do you mind if I first integrate that part of EcoManager mod in my SSB mod such that there is no conflict between our mods? Also, it should help once we start porting functionality of these UI mods to FA game.

**Comment by Crotalus** [comment]
Yeah np but the current overflow information in EM is kind of sucky + it's uses a chat channel to transfer the information between players. It is much nicer to get sim "backend" support and transfer the information that way instead.

AFAIK you currently use "backend" values already when watching replay, we can just make those values accessible during the game also (if you're allies ofc).

**Comment by HUSSAR-mtrela** [comment]
I agree that would be better solution for both mods. Thanks for quick reply.

**Comment by HUSSAR-mtrela** [comment]
@Sheeo this issue can be closed per Crotalus' and my comments. 
Also, I captured all above request for changes in issue #1182
