### ISSUE TITLE
Ctrl+k-ing an ACU gives veterancy to enemy ACUs before the explosion damage is applied

### ISSUE THREAD

**Issue by ChessBerry** [FAForever/fa#4750]
**Describe the bug**
Ctrl+k-ing an ACU gives veterancy to enemy ACUs before the explosion damage is applied, making them survive even when below 2500 HP. 

This wasn't the case previously, but I'm not entirely sure when exactly the behavior changed. It can't be more than a couple months though, probably only a couple weeks or less, as the predictability of a draw when both ACUs are below 2500 HP is critical for competitive play.

**To Reproduce**
Have two enemy ACUs shoot each other until they are at below 2500 HP, but above ~1500 HP, then ctrl+k one of them. The other ACU will live due to the veterancy HP bonus even though it should have died.

19355735: Sandbox game showcasing the bug.

19355193: Game where the bug first appeared - Yudi ctrl+k's himself in mid @6:37, which should have killed both me and Nory as I was at 2100 HP and nory at below 5000, but didn't due to the above bug.

**Expected behavior**
The HP bonus of a commander explosion should be applied after the explosion damage, so that all ACUs in range of the 2500 damage explosion, and below 2500 HP, die with certainty.

**Comment by Garanas** [comment]
This is likely due to the new veterancy implementation. I'll look into it.

**Comment by speed2CZ** [comment]
If you killed enemy ACU you did get vet before getting hit by the explosion. So it sounds like the current state is correct.

**Comment by Garanas** [comment]
Yes, but I recall there was an exception in the old veterancy code where if you CTRL + K a unit it doesn't disperse / give veterancy. I thought that was quite random, but in this specific case it makes quite a difference

**Comment by ChessBerry** [comment]
I'm like 99% certain that if you ctrl+k'd your ACU while the enemy ACU was at below 2.5k HP, they would always die. I did it multiple times and it happened to me multiple times. If really needed I'm sure I can find examples too.

Semi related: Whatever the behavior for ctrl+k-ing is should be the behavior for dying to anything else as both are, from the outside, the same explosion (and training people to always hover their finger over the ctrl+k button while fighting with their ACUs doesn't sound like something we want to encourage).

**Comment by ChessBerry** [comment]
#18440528: A game from November last year where pepsi's death kills yudi, who's at 2.2k hp, and bullied, who's at 4.9k and dies due to being in the range of both ACU explosions for a total of 5k damage

**Comment by Garanas** [comment]
> And training people to always hover their finger over the ctrl+k button while fighting with their ACUs doesn't sound like something we want to encourage

By reverting to the old behavior, isn't this exactly what we're teaching them?

The problem with reverting to the old behavior is that when you CTRL + K an experimental _just before it dies_ it doesn't give any veterancy either. That sounds unhealthy to me

**Comment by ChessBerry** [comment]
If the old behavior was: "Deal damage before the veterancy kicks in _only_ if you ctrl+k'd your ACU", then yes that is bad.

What I would propose though is "If an ACU with less than 2.5k hp is in range of an ACU explosion, they always die, regardless of the enemy ctrl+k-ing or not."

Note that this importantly should also apply to chain explosions. I.e. if an ACU is in range of two explosions, the second triggered by the first, they should take exactly 5k damage with no exception.

I'm less certain, but still like 90%, that both of those were guaranteed in the old behavior. See e.g. the example game I posted above (#18440528) where pepsi dies, unsure wether via ctrl+k or not, and kills both his primary target yudi and his secondary target bullied which is only possible if none of them gained any veterancy before the explosion chain is over

**Comment by Garanas** [comment]
> If the old behavior was: "Deal damage before the veterancy kicks in only if you ctrl+k'd your ACU", then yes that is bad.

That is exactly what it was - veterancy would not disperse when you CTRL + K a unit. Therefore the opponents ACU would get no vet, no health bonus and you both perish.

> Note that this importantly should also apply to chain explosions. I.e. if an ACU is in range of two explosions, the second triggered by the first, they should take exactly 5k damage with no exception.

They do take that amount of damage. They just also gain some health.

**Comment by ChessBerry** [comment]
You are correct, I phrased this badly. What I meant was: "An ACU that's in the explosion range of a chain-ACU-explosion should die if their health is below n*2500 hp, where n is the number of ACUs in the explosion chain that are in range of the first ACU, regardless of if the chain was initiated via a natural death or a ctrl+k"

As my memory is unreliable on the best of days, I tested old vs new behavior w/o pressing ctrl+k. I went back to a random commit of november last year, beb6c010fb1f9ac6b8c4e2b3ecd73b1154716c55 on the master branch, and had two ACUs shooting each other:

![Screenshot_105](https://user-images.githubusercontent.com/90977374/221809702-c75b6d34-6324-41dc-aaad-b0d33d7294e6.png)

I stopped one of the ACUs from shooting so that the other was roughly 2k health above the former:
![Screenshot_106](https://user-images.githubusercontent.com/90977374/221809892-edc41757-24e3-49f1-accc-a9ebf8948c03.png)
![Screenshot_107](https://user-images.githubusercontent.com/90977374/221809902-7a99f2f6-017e-41f7-93ff-d2fdf328d1b0.png)

If you let this play out, w/o pressing ctrl+k or anything else, both ACUs die:

![Screenshot_113](https://user-images.githubusercontent.com/90977374/221810029-daaf59ee-25ba-483e-884f-81e3caba6c8c.png)

If you use the current state of the master branch 339420bfd8d73b2ba36d6303c2d175da840b49fe and do the same:
![Screenshot_108](https://user-images.githubusercontent.com/90977374/221810214-028ad1fe-0523-4de1-b409-ede4d0c84959.png)

![Screenshot_110](https://user-images.githubusercontent.com/90977374/221810377-02b4c71a-31a0-406a-b599-6669dc0503da.png)
![Screenshot_109](https://user-images.githubusercontent.com/90977374/221810218-786898f7-37fc-4ad7-a294-8a3018752ba4.png)

The ACU with ~2k more health now lives, where it would have died in November:
![Screenshot_112](https://user-images.githubusercontent.com/90977374/221810929-a2b32e4d-bc87-4b86-b3cf-6a867556f857.png)
![Screenshot_111](https://user-images.githubusercontent.com/90977374/221810913-cd31bfa2-5e18-486a-816a-04dde4605408.png)

If I did the above tests correctly, this means that a couple months ago the damage from an ACU explosion was applied before the veterancy health bonus, regardless of how the ACU died. 

Of course what was the case in the past is kind of irrelevant for what we want it to be today. 

Personally, I very much prefer the predictability and simplicity of "if the enemy is below 2.5k hp, it's a draw" to the different health thresholds one would need to learn for the current implementation. 

I'm not sure how exactly one would adjust the current veterancy system to achieve that. Maybe just removing the 1k mass killed that an ACU seems to count as for the purpose of veterancy gain would be a trivial solution. Maybe adding an explicit check to the death/veterancy gain of ACUs would be better.

**Comment by Garanas** [comment]
This is the pull request responsible:

- https://github.com/FAForever/fa/pull/4686/files

And this is the bit of logic that changed the behavior: 

![image](https://user-images.githubusercontent.com/15778155/222235791-f48ab68d-7659-46ff-a7de-57ba0e7860fe.png)

Experience is now dispersed before the damage is dealt. Therefore units heal before they take damage, and hence they do not die in your situation. I'll make a pull request to apply the damage first as that was the old behavior

**Comment by Garanas** [comment]
@ChessBerry the fix is merged on faf develop, can you confirm it is fixed?

**Comment by ChessBerry** [comment]
Looks like it's fixed, both when ctrl+k-ing and when having an ACU die naturally. Works for chain explosions too. Great work as always :D
