### ISSUE TITLE
Structures placed in editor dont keep their rotation when spawned

### ISSUE THREAD

**Issue by speed2CZ** [FAForever/fa#4751]
I suspect the new code that snaps building to the terrain doesn't respect their current orientation and just overrides it.

Red arrows shows where the effects should be facing
![ForgedAlliance_2023-02-27_16-42-39](https://user-images.githubusercontent.com/10947024/221611522-c4d950db-221e-464e-bfaf-6a042e120414.jpg)

This is how it looks in the map editor, the editor arrows are always at the back side of the unit
![SCEditor_2023-02-27_16-50-47](https://user-images.githubusercontent.com/10947024/221612331-2c5a16a1-88c6-403a-b9cd-498bd2e2e52d.png)

**Comment by Garanas** [comment]
🤔 , how can we work around this
