### ISSUE TITLE
Issue with cycling through hotbuild

### ISSUE THREAD

**Issue by bullydozer** [FAForever/fa#4753]
**Describe the bug**
When hitting a key for hotbuild, placing a structure, and pressing the key again, it cycles through to the second building in that hotbuild, instead of starting back at the first structure. Let's take land/air/navy factories as an example.
In the past, hitting Q (my keybind) would select land factory. If I placed a factory and quickly hit Q again, it would select land factory again. However since most recent patch, it will cycle through to the air factory. This might be an intended game change but it messes with many player's muscle memory. I've constantly been placing flak instead of sams, I've watched harzer accidently place air factories on stream, and SpikeyNoob claims he's seen Yudi and himself do the same.

This messes with people's muscle memory because it is common to place the first factory without holding shift to get rid of any other of the engineer's orders, then hitting the hotkey again to then place more of that same building with shift held down.

**To Reproduce**
Hit any hotbuild hotkey, place a building, and hit the hotkey again

**Expected behavior**
After hitting the hotbuild hotkey and placing a building, the hotbuild cycle should restart at the first building

**Screenshots**

**Additional context**
This issue might exist due to the default Cycle Reset Time being increased in ingame Options -> Interface -> Cycle Reset Time. If this is the case, I believe all players should be informed because this pretty majorly impacts their gameplay

_This bug report will be read by people that have not experienced the bug themselves - this report is all they have to investigate. The more precise your report, the easier it becomes for us to help you._

**Comment by Garanas** [comment]
This change is not intended. I'll look at it.

**Comment by Garanas** [comment]
@bullydozer the fix is merged on towards the development branch. We'll release it this weekend. Can you confirm that it is fixed? If it is not, you can re-open this issue
