### ISSUE TITLE
redundant entries for anti-torpedo weapons' `FireTargetLayerCapsTable`

### ISSUE THREAD

**Issue by haifron** [FAForever/fa#4788]
Description
-----------
Anti-torpedo weapons in the game have a variety of different values for this table, all being some subset of `Water|Seabed|Sub` (and the cooper's antitorp enthusiastically being able to attack `Land` too 😄).

#### list of the number of weapons with each variety of `FireTargetLayerCapsTable`
```Lua
19 'Seabed|Sub|Water'
1 'Sub|Water'
1 'Sub|Water|Seabed|Land'
1 'Water'
```
After some testing, I've concluded the only required layer is `Water` however, which the t3 aeon sonar's antitorp has.

Question
----------------
Do these excess entries cause the game to search more units/projectiles than it needs to? Like is there any point in making them all just `Water`.

**Comment by Garanas** [comment]
These values are used to enable / disable targets as the unit switches layer. As an example: the destroyer disables the torpedo launchers as it walks on land. Submarines disable their deck guns as they submerge.

That they exist but can not be used has no impact on performance.

**Comment by relent0r** [comment]
I would have thought they'd need seabed as well since thats the layer that things like the wagner switch to when they are under water.

**Comment by haifron** [comment]
@relent0r I tested having each layer in the table (including all at once _except,_ `water`) with ship, sub, plane & amphibious launched torpedoes and the antitorp only ever killed torpedoes when `water` was included. So apparently not.

You can also test this yourself whenever with the T3 aeon sonar which only has `water`.

**Comment by haifron** [comment]
> These values are used to enable / disable targets as the unit switches layer

@Garanas I'm actually referring to the values of the table, not the keys - the layers the weapon can fire _at_ not fire _from_. So in 
```Lua
FireTargetLayerCapsTable = {
    Water = 'Sub|Water|Seabed|Land',
},
```
I'm referring to `Seabed|Sub|Water` (not `Water`) - which are being used unless I'm mistaken. Regardless of the probably tiny performance change, if it's ok for me to change this just to make the blueprints more concise & precise then I'd probably like to do that anyway; the bps are mysterious enough as they are.

**Comment by Garanas** [comment]
I miss understood - feel free to fix this for weapons where it makes no sense to be able to target a specific layer
