### ISSUE TITLE
UI locks up and stop showing mass or energy when energy storage is destroyed.

### ISSUE THREAD

**Issue by piisawheel** [FAForever/fa#4792]
**Describe the bug**
A clear and concise description of what the bug is. Do not forget to append the game logs.
After energy storage is destroyed, the UI locks up and stops updating mass and energy.  The underlying game runs fine but I'm flying blind.  Rebuilding up to the storage that you had before seems to fix the issue, as it works when you are in an E-stall and your energy is below your current *actual* storage.  But when topped out, it locks up, like it's expecting to be able to add more e than you have available storage.  Rebuilding storage so your energy is at previous maximum or more seems to fix the issue.

This game was not modded, And I believe the only limits were air, navy, and teleport.
[game_19436382.log](https://github.com/FAForever/fa/files/10937488/game_19436382.log)

Played as PatientBeard as cybran.
https://replay.faforever.com/19436382

**To Reproduce**
A clear and concise set of instructions on how to reproduce the issue. Best accompanied with a sandboxed replay. An in-action replay is helpful but not sufficient - the burden to investigate how to reproduce the issue is then moved to the maintainer.
Build energy storage.  Have it be destroyed.   Your ui should lock up, the mass and e bar lock up, and the score locks up.  If you go into an e-stall, and your energy is below what you can actually store, it seems to function, but it seems to have an issue when the e hits your actual cap after the cap has been raised and then lowered.

**Expected behavior**
The ui should pretty much never lock up and should always display actual values if able/appropriate.

**Screenshots**

**Additional context**

_This bug report will be read by people that have not experienced the bug themselves - this report is all they have to investigate. The more precise your report, the easier it becomes for us to help you._

**Comment by Garanas** [comment]
This is becaues of `info:         Supreme Economy 2.3   (8c28a269-8655-4639-8e54-3d311fc376f8)`, which is fixed with the latest version.

**Comment by piisawheel** [comment]
I do apologize.  Sometimes I forget UI is a separate category of mods, and forgot I had those on.  Thanks!
