### ISSUE TITLE
veterancy levelup, when the enemy ACU dies out of range.

### ISSUE THREAD

**Issue by hex-5** [FAForever/fa#4797]
In the replay ([19452532](https://replay.faforever.com/19452532)) at timestamp 7:19, the white ACU gets a veterancy levelup without kill (T1-Artillery gets the actual kill). Somehow the 200 mass kill gets added to the ACU vet.

**Comment by Garanas** [comment]
That is how veterancy works - it works with the amount of damage that you did to a unit. Not on whether you get the kill. The veterancy is then dispersed accordingly.
