### ISSUE TITLE
T2-Artillery hits through shield without collision

### ISSUE THREAD

**Issue by hex-5** [FAForever/fa#4798]
In the replay ([19137039](https://replay.faforever.com/19137039)) at minute 10:44, the enemy stationary T2-Artillery shoots through a T2 shield without collision.
Maybe it has something to do with the Jitter-Patch, which was introduced at this time.
The bug could not be reproduced anymore, but happens all the time in the replay.
Around the timestamp ~8:20 the arty also shoots engineers through the shield.

**Comment by Garanas** [comment]
There's nobody named `hex-5` in-game, I can't determine who the enemy is. Which side is having the issues?

![image](https://user-images.githubusercontent.com/15778155/224527394-f72f9756-87e0-4b6e-9764-25afc88f86d6.png)

**Comment by hex-5** [comment]
#### T2-Artillery hits engineers under shield:
https://user-images.githubusercontent.com/56544052/224546575-d00e88b1-4873-44c1-b7f1-a4f13213b551.mp4

#### T2-Artillery hits T2-Artillery under shield:
https://user-images.githubusercontent.com/56544052/224546578-4c4a0fa7-2df3-41e6-a00b-b3aa6825b793.mp4

**Comment by Garanas** [comment]
Nice - this happens because the Aeon artillery creates a second projectile on impact, which can then occasionally pierce a shield

**Comment by MrRowey** [comment]
@Garanas Is this something that can be fixed?

**Comment by MrRowey** [comment]
@lL1l1 or @clyfordv can you see if this could be fixed ?

**Comment by clyfordv** [comment]
I have reproduced the issue XD: 
<img width="751" alt="image" src="https://github.com/FAForever/fa/assets/7411478/4eaed0f5-5337-4a84-a75c-f79ce092b0f0">

**Comment by clyfordv** [comment]
A grind with an unsatisfying conclusion, but it's done: https://github.com/FAForever/fa/pull/6163/files
