### ISSUE TITLE
New cheat window has broken scaling

### ISSUE THREAD

**Issue by speed2CZ** [FAForever/fa#4815]
150%

![ForgedAlliance_2023-03-15_20-27-36](https://user-images.githubusercontent.com/10947024/225421661-23e3213d-496e-4d60-a169-16eafe265512.png)

**Comment by speed2CZ** [comment]
![ForgedAlliance_2023-03-15_20-29-56](https://user-images.githubusercontent.com/10947024/225422044-17bf2839-c571-44e3-8087-f6654d9e04ea.png)

**Comment by Garanas** [comment]
I just did a release 😭

**Comment by speed2CZ** [comment]
Forgot the testing part? :P

**Comment by Garanas** [comment]
I did test this for several hours, but I forgot about the UI scaling 😞

**Comment by 4z0t** [comment]
Ig Layouter must be first thing to check in UI prs...

**Comment by HUSSAR-mtrela** [comment]
this is already fixed in PR #5410

**Comment by Garanas** [comment]
@HUSSAR-mtrela feel free to close issues when they are already fixed in the future 😃
