### ISSUE TITLE
5756 on Linux Stuck on Loading Screen

### ISSUE THREAD

**Issue by veqqq** [FAForever/fa#4816]
**Describe the bug**
After launching a game on Linux (clicking x to confirm, then clicking launch), it gets stuck on the loading screen and you must restart the Linux to use the computer otherwise. Hotkeys (ctrl alt del) do nothing. The power button makes the shutdown menu appear, but you can't select anything. Holding down the power button forces a shut down.

**To Reproduce**
Linux Mint, everything was fine until it downloaded patch 3756 (N.b. The changelog 3756 hasn't been released yet? "March 18")

**Additional context**
Everything was fine until it downloading this patch today. I played a game 24 hours ago. I updated Proton Experimental on Steam a few days ago (3?)

_This bug report will be read by people that have not experienced the bug themselves - this report is all they have to investigate. The more precise your report, the easier it becomes for us to help you._

Bad game:
[game_19485315.log](https://github.com/FAForever/fa/files/10988074/game_19485315.log)

Last good game on 3755:
[game_19478400.log](https://github.com/FAForever/fa/files/10988226/game_19478400.log)

The end of the logs clearly show the issue:

`warning: Error running CreateGameInterface script in CScriptObject at 115900f4: ...iance\mods\supremescoreboard\modules\score_board.lua(1611): attempt to perform arithmetic on field `actual' (a nil value)
         stack traceback:
         	...iance\mods\supremescoreboard\modules\score_board.lua(1611): in function `CreateTeam'
         	...iance\mods\supremescoreboard\modules\score_board.lua(207): in function `InitializeStats'
         	...iance\mods\supremescoreboa
rd\modules\score_board.lua(468): in function `SetupPlayerLines'
         	...iance\mods\supremescoreboard\modules\score_board.lua(383): in function `CreateScoreUI'
         	....faforever\gamedata\lua.nx2\lua\ui\game\gamemain.lua(1104): in function <....faforever\gamedata\lua.nx2\lua\ui\game\gamemain.lua:1098>
         	....faforever\gamedata\lua.nx2\lua\ui\game\gamemain.lua(1123): in function `CreateUI'
         	....faforever\gamedata\lua.nx2\lua\ui\game\gamemain.lua(502): in function <....faforever\gamedata\lua.nx2\lua\ui\game\gamemain.lua:496>
info: Hooked /lua/ui/game/score.lua with /mods/supremescoreboard/hook/lua/ui/game/score.lua
warning: GetResource: Invalid name ""
info: Can't find texture "" -- trying fallback.
warning: GetResource: Invalid name ""
info: Can't find texture "" -- trying fallback.
warning: GetResource: Invalid name ""
info: Can't find texture "" -- trying fallback.
warning: GetResource: Invalid name ""
info: Can't find texture "" -- trying fallback.
warning: GetResource: Invalid name ""
info: Can't find texture "" -- trying fallback.`

**Comment by Garanas** [comment]
Does the game launch without any (UI) mods enabled?

**Comment by MrRowey** [comment]
@veqqq Are you Able to play with recent patches ?
