### ISSUE TITLE
Buildings that should not have drag-build enabled are draggable

### ISSUE THREAD

**Issue by Basilisk3** [FAForever/fa#4817]
**Describe the bug**
It is possible to drag-build units like mass extractors and radars/sonars. This is likely an unintended change that made its way into the patch via the new cheat menu. This will cause players to accidentally build multiple radars in the same place, which isn’t useful and a waste of resources. 

**To Reproduce**
Select an engineer and drag-build radars, sonars or mass extractors.

**Expected behavior**
Drag-build is disabled for sonars, radars and extractors.

**Comment by Garanas** [comment]
I wasn't aware that those were not draggable. I'll look into it 👍

**Comment by MrRowey** [comment]
I don't understand the issues Radars and sonars have always been draggable

**Comment by Basilisk3** [comment]
Originally they were draggable. This was then removed, because it caused players to accidentally build two radars in the same spot. Then at some point they were made draggable again, I don't know why or if that was unintended. Either way, they should not have drag-build enabled, there is just no point in dragging radars.

**Comment by MrRowey** [comment]
@Garanas I can see that for example this Aeon Radar dosnet have the 'DRAGBUILD' Categorie 
![image](https://user-images.githubusercontent.com/20344151/236638253-7c04f624-4e5b-4577-8cbe-ca9e8e158e56.png)
as it was removed back in 2020 but not sure why it can be draggable with out that tag not sure where this is decided if it can be drag built or not

**Comment by Garanas** [comment]
It was re-introduced through the blueprints loading process to make the cheat window easier to work with.

**Comment by HUSSAR-mtrela** [comment]
Mass extractors should remain draggable because this is useful on maps that have CrazyRush script or when a mod uses that script to generate mass deposit next to built mass extractor. Also, there are maps that have multiple mass deposits in diagonal placement. In those cases, dragging order for building multiple mass extractor is useful.

**Comment by Garanas** [comment]
The tags are added during blueprint loading. I don't see the harm in the long run, but I understand that it can be frustrating initially because you're used to a different behavior. 

Now all structure placements behave the same, which is ideal in my opinion.

**Comment by Basilisk3** [comment]
Extractors staying draggable is not a big deal for me. However, radars and sonars really should not have this enabled, as it just causes issues and is not useful, as outlined in the OP. I do not think this is a grave issue, but I also think that the reasons for removing previously were valid, at least for radars and sonars.
