### ISSUE TITLE
Mods that add extra factions can cause the lobby background to choke

### ISSUE THREAD

**Issue by ChrisKitching** [FAForever/fa#482]
See:
http://forums.faforever.com/forums/viewtopic.php?f=3&t=9380&p=93315

What probably happened was he played Nomads (or similar) and it wrote a dodgy value to "LastFaction".

The solution is probably to just rename the field we use for storing faction, so we no longer collide with what everyone else is poking.

**Comment by Sheeo** [comment]
Seems reasonable. How is this looking on current develop?

**Comment by CookieNoob** [comment]
fixed in https://github.com/FAForever/fa/commit/02202519e18cb704d24761c536a7ff430462df79
@aeoncleanse close plz
