### ISSUE TITLE
Missing description for two keys in the debug menu

### ISSUE THREAD

**Issue by Basilisk3** [FAForever/fa#4822]
**Describe the feature**
The new debug menu is a big improvement over the old one, however I found two keys which appear to have a function, but it is unclear what exactly they do. I am referring to the two buttons next to the _**visibility**_ key. The one on the left appears to toggle the **_visibility_** key itself, and the one on the right seems to allow the player to spawn dummy units. 

**Expected behavior**
This is not a big problem, but it would probably be good if they were named or had a description.

**Comment by Garanas** [comment]
Can you make a screenshot with an arrow pointing to the buttons?

**Comment by Basilisk3** [comment]
Apologies, the key I was referring was not shown in my comment for some reason. I edited my comment to say which one.

**Comment by HUSSAR-mtrela** [comment]
@Garanas @MrRowey this issue can be closed since the debug menu has been recently improved and description of visibility key/button is not missing anymore
