### ISSUE TITLE
AI not getting Start Location markers for functions using GetMarkersByType

### ISSUE THREAD

**Issue by relent0r** [FAForever/fa#4833]
**Describe the bug**
The GetMarkersByType function within the markerutilities.lua expects a marker type of 'Spawn' but the marker type that is being sent to it by various functions is 'Start Location'. The functions that are using this get marker function need to be changed to request the 'Spawn' marker type instead of 'Start Location' type.

Due to the dependency that other AI have on this marker type this is going to cause issues. Specifically around the EngineerBuildAI function. I wanted to refactor the AIFindStartLocationNeedsEngineer function to leverage the new marker utilities marker functions as it performs better. But I know that other AI's are using it with the marker type of 'Start Locaiton'. So doing this would cause them to break.

**To Reproduce**
The AI builder called Start Location Attack is configured to use the 'Start Location' marker type. In the logs we see the following.
debug: Caching 0 markers of type Start Location!
You will notice the platoon just sits there because it can't find the markers that it is expecting.

**Expected behavior**
Platoon will get the correct markers and go forth.

**Comment by relent0r** [comment]
@Garanas could I get your opinion on this. The obvious solution would be to get any function thats asking for a 'Start Location' marker to change it to 'Spawn' similar to how the default changed it to 'Blank'.

**Comment by Garanas** [comment]
I'm not sure, but does #4836 solve this issue?

**Comment by relent0r** [comment]
> I'm not sure, but does #4836 solve this issue?

Yup that sorts it out great thanks!
