### ISSUE TITLE
Veterancy values are unintuitive

### ISSUE THREAD

**Issue by Basilisk3** [FAForever/fa#4841]
**Scenario 1:**
A T4 artillery destroys a Paragon. The result is that it will not gain the full 250k mass cost of the paragon as veterancy, but only around 83k. This is incorrect, and the unit would need to destroy several Paragons to even gain a single level of veterancy.

**Scenario 2:**
A land T4 destroys a paragon. The UI will now show that the unit has killed 14k mass (in the case of the Galactic Colossus). This results in it being impossible to instantly gain full vet, of a single unit. Balance wise, this makes sense in my opinion. 

Nevertheless, the value displayed in the UI is still wrong and misleading. I have noticed that a lot of players use the veterancy UI to learn how much mass a unit has killed. However, as shown here, in some cases this is very inaccurate.

Another example could be: A tech 1 bomber killing a tech 2 mass extractor.

One possible solution would be to implement two separate indicators, one for the veterancy values, and one for how much mass the unit destroyed.

**Comment by lL1l1** [comment]
With paragon this happens because it takes damage 3 times from a mavor: 5000 damage from the shell (it only has 5000 HP), 5000 damage from the inner nuke explosion, and 5000 damage from the outer nuke explosion. This means it took 15000 damage and 5000 came from the mavor, so the mavor gets 1/3 of its mass as vet, 83400 as shown in the bug.

**Comment by clyfordv** [comment]
I'll take a swing at it.

**Comment by clyfordv** [comment]
https://github.com/FAForever/fa/pull/6110

**Comment by clyfordv** [comment]
I think two values by default (Experience and MassValueKilled) is probably a UI hazard, but some way of accessing total mass killed seems very reasonable. The overhead of tracking that for every unit is not nothing, so separate PR here: https://github.com/FAForever/fa/pull/6111
