### ISSUE TITLE
Recall despite veto

### ISSUE THREAD

**Issue by andreasley** [FAForever/fa#4845]
I've experienced multiple times that a teammember initiated a recall prompt and after I vetoed it, the recall happened anyway.

Most recent game where this happened is #19579472.

My understanding (and feedback from the chat) is that the recall is only supposed to be happening if all player agree. 
Is that correct or is it actually majority-based?

**Expected behavior**

- If it's supposed to be unanimous, there's a bug somewhere.
- If it's supposed to be majority-based, the term "veto" is inaccurate, as it usually describes the power to unilaterally stop something. My suggestion would then be to label the buttons "Continue playing" and "Give up" and maybe some textual hint that this is a voting.

**Comment by MrRowey** [comment]
its only requires 50% of the current players that are alive to complete the recal

**Comment by andreasley** [comment]
> its only requires 50% of the current players that are alive to complete the recal

So it is majority-based and leaning towards recall (in a 50:50 split).

I'd suggest to change the wording (see first post) and maybe reconsider the behaviour at equal votes, so more >50% of votes are required to end the game.

**Comment by Garanas** [comment]
We already have, see also:

- https://github.com/FAForever/fa/pull/4698

You can find the recall criteria here:

- https://github.com/FAForever/fa/blob/deploy/fafdevelop/lua/shared/RecallParams.lua

The text changes will be released in June with the next developers iteration.

**Comment by andreasley** [comment]
Beautiful; thank you!
