### ISSUE TITLE
Suthanus Unable To Fire Backwards

### ISSUE THREAD

**Issue by ComradeStryker** [FAForever/fa#4889]
**Describe the bug**
The Seraphim T3 Mobile Heavy Artillery (Suthanus) is unable to shoot in its rear ~120* Arc.

---

**To Reproduce**
Sandbox game:
- Spawn in a Suthanus 
- Give it an attack order. 

If the order is placed in its rear arc, the unit will not be able to shoot even though it has the animation to do so. 
All other factions' Mobile Heavy Artillery can do this without issues.

---

**Expected behavior**
Suthanus unit to be able to fire in any and all directions.

---

**Screenshots**
![image](https://user-images.githubusercontent.com/121060254/235310655-104d7d8d-4689-4898-bf12-c1b5816be70d.png)

---

**Additional context**
This bug is only noticeable when the player ground fires this unit, as, if the unit automatically targets or is manually given a target, it will adjust itself to face the target before firing.

3-minute replay showcasing the bug:
https://replay.faforever.com/19844347

**Comment by Garanas** [comment]
@The-Balthazar any idea why this is when you look at the blueprint?

**Comment by The-Balthazar** [comment]
On Steam the deadzone appears to only be this size 
![image](https://github.com/FAForever/fa/assets/11473693/e57887f8-b358-46dd-a0ce-44b1eacb548a)
It looks like it might be indirectly animation related, with how that interacts with the pitch ranges.
