### ISSUE TITLE
Aeon & Cybran T2 Transports Receive Inconsistent Torpedo Damage

### ISSUE THREAD

**Issue by ComradeStryker** [FAForever/fa#4890]
**Describe the bug**
Aeon and Cybran T2 Transports do not take damage from subs as consistently when landed / idle on water.

---

**To Reproduce**
Sandbox: 
Spawn in the Aeon and Cybran T2 Transports and let them land on water.
Spawn in an enemy submarine.
Notice how the torpedoes miss a majority of the time as the hitbox of the transport is slightly off preventing the torpedoes from colliding with the transport.

---

**Expected behavior**
Transports take damage from torpedoes consistently, as all other transports do.

---

**Screenshots**
![image](https://user-images.githubusercontent.com/121060254/235311010-4a3514cd-d221-4b83-8841-b63dcfca6acb.png)

---

**Additional context**
2-minute replay showcasing the bug:
https://replay.faforever.com/19844536

**Comment by Garanas** [comment]
This should be fixed with https://github.com/FAForever/fa/pull/4570
