### ISSUE TITLE
GC Creates Invulnerable Units Upon Death

### ISSUE THREAD

**Issue by ComradeStryker** [FAForever/fa#4893]
**Describe the bug**
The Galactic Colossus can make invulnerable and untargettable units via its tractor claws upon death. 
If a GC dies during the precise moment a grappled unit makes contact with its claws, the unit is dropped or launched and then made invulnerable, with an added side effect _sometimes present_ of the unit still spinning as if the GC was still tractor beaming it.
The GC wreckage still has the tractor beam special effect on its hand at times when this bug occurs.
These units can still be controlled and can still shoot back at targets.

---

**To Reproduce**
Warning: _Incredibly precise moment needed to replicate this bug._
Adjustable game speed is highly recommended to slow down the match to increase your window of reproducing this bug.

Sandbox game:
- Spawn in GC
- Spawn in an enemy unit
- Let the GC tractor beam a unit 
- Then Ctrl+K or let the GC die as soon as the unit is about to make contact with the hand.

If timed correctly, the unit will drop and become invulnerable.

**Expected behavior**
Either A, the unit dies, as expected, or B, the unit is dropped, but not invulnerable or untargettable.

---

**Screenshots**
These Units are now invulnerable and enemy units do not automatically target them. 
Notice how one of them is not spinning like the others.
![image](https://user-images.githubusercontent.com/121060254/235314720-777ffe7c-2f64-456e-a4a3-9254674a8b1b.png)

The Wreckages of the GCs still showcase the Grapple Effect.
![image](https://user-images.githubusercontent.com/121060254/235314742-744a9bbb-55a1-4b65-8b80-e47ae2029755.png)

If the units die at an off Elevation, then manually targeted, the 'hitbox' of the unit is floating in mid-air.
![image](https://user-images.githubusercontent.com/121060254/235313751-03a31512-c229-47f8-bddd-c57db0c16db0.png)

---

Additional Image:
![image](https://user-images.githubusercontent.com/121060254/235313753-1e60636e-0f2b-4f0d-a6d6-559cc0495822.png)

---

**Additional context**
Even though these units are invulnerable and (automatically) untargettable, being able to survive a Yolo Nuke to the face, 
they still succumb to being reclaimed.

Replay ID Showcasing Bug:
https://replay.faforever.com/19845111

**Comment by Garanas** [comment]
This issue has been fixed 👍
