### ISSUE TITLE
Navmesh request - Simplify return strings and Threat pathing return on failure.

### ISSUE THREAD

**Issue by relent0r** [FAForever/fa#4894]
## Describe the query

Request for simplified navmesh string returns on queries.

The navmesh returns string when there are failures or successes. While these are very human readable they are not as readable for the lua code. I would like to request that we modify these to be shorter responses with no spaces within the text.

for example.
line 490 reads 'Did not manage to find the destination'
If I want an AI function to understand this I need to say `if msg == 'Did not manage to find the destination' then`
Which is prone to error and extends the code. It would be better to just say `if msg == 'DestinationNotFound' then`, that way a platoon which is making these queries can have a response without big long strings in the if statement and as a developer I'm less likely to have silent failures because I forgot a space, or accidentally added a space on the end or something.

Request for normalized threat return on threat based pathing failures for PathToWithThreatThreshold function

When a path goes above the threat threshold this function will return a failure. But for the platoon or logic that made the request there is no way to understand how dangerous it was so that other logic can be run. 
For example if a platoon receives a threat based pathing failure it doesn't know if merging with another platoon would allow it to push its own threat over the threshold as it has no data to work with.
It also doesn't allow advanced support functions to be used. For example if a platoons path fails due to threat then there is always an option to call for air support to help decrease the enemy threat or at least allow the AI to perform a more thorough analysis of the area in question.
One valid option would be to return the cells that returned the threat failure and the threat number that was received. Please note that with the default threat function we usually request a ring of cells to be checked so this will need to be taken into account for the return data. 

The original pathing function would (almost) never decline a path based on threat so there is currently no logic in how to deal with this new capability. With the ability to fail paths due to threat it should help engineers and transports understand where they can and can't go. In the case of transports it could mean that they could perform shorter drop paths.

**Comment by Garanas** [comment]
Do you want them to be PascalCase or camelCase or do you prefer it-like-this?

**Comment by relent0r** [comment]
> Do you want them to be PascalCase or camelCase or do you prefer it-like-this with dashes?

Good question. Do we have any standard currently?  I'm one of those people that does PascalCase for params and outputs and camelCase for local variable names. Pascal 'seems' like a good option for this scenario, but thats just my pov.

**Comment by Garanas** [comment]
We do not have a standard. We'll go with PascalCase 😄 !

**Comment by Garanas** [comment]
I'll include this with the hot fix 👍
