### ISSUE TITLE
A warning should be shown in the UI while a map with no AI markers is selected and AI are in the game

### ISSUE THREAD

**Issue by ChrisKitching** [FAForever/fa#492]
Currently, you get a warning when you switch to a map with no AI markers and have AI, but if you add the AI later on nothing alerts you to the problem.
Probably worth, at least, a launch-time modal dialog.

**Comment by quark036** [comment]
@duk3luk3 , you were working on the mapselect dialog right?

**Comment by duk3luk3** [comment]
So was @ChrisKitching ;)

**Comment by ChrisKitching** [comment]
But we have this thing called Git, so it's fine?

**Comment by MrRowey** [comment]
@Garanas is this still an issuse with older maps ?

**Comment by ChrisKitching** [comment]
If memory serves, this ticket isn't a map issue (anyone can create a map that lacks ai markers), it's an issue with the lobby UI not warning you that you probably shouldn't play a game with AI on such a map. But only in the case where you:
- select the map
- then add the AI.

AI markers are metadata added to maps to give the AI hints on how to play. The AI plays very stupidly on a map which lacks the markers (to the extent that the game is pretty boring).

No idea if anyone fixed it in the intervening 7 years, but that's what the bug was about ;)

**Comment by Garanas** [comment]
Still there - it would be a nice quality of life feature for the AI players.

**Comment by Garanas** [comment]
Closing this issue - there's more to AIs than just markers. Especially as some AIs no longer use markers.
