### ISSUE TITLE
ren_ShadowBias  

### ISSUE THREAD

**Issue by robotcatt** [FAForever/fa#4920]
can use ConExecute("ren_ShadowBias 1") to clear shadow artifacts on edges
default 0

**Comment by Garanas** [comment]
With shadow bias of 0:

![image](https://github.com/FAForever/fa/assets/15778155/27685230-3471-4f80-a306-eea2afff75b4)

With shadow bias of a non-zero value:

![image](https://github.com/FAForever/fa/assets/15778155/8dc6017d-8a81-4541-a205-d04e5a987a85)

It appears to disable self-shadowing. That is fine for a UI mod, but not something that should be part of the game on its own.

**Comment by robotcatt** [comment]
is it possible to fix the blinking of the shadow during self-shadowing? maybe a higher resolution of self-shadow textures

**Comment by Garanas** [comment]
With extended graphics we push the resolution to 2048. Anything more doesn't appear to have an immediate visual effect

**Comment by robotcatt** [comment]
i found some. 
in mesh.fx
float ComputeShadowPCF( float4 shadowCoords)
...
float offset = texel; to float offset = texel+1; or more fix shadow blinking 
(check uef com and uef mex)
