### ISSUE TITLE
JSON serializer can produce invalid floating point values for integers

### ISSUE THREAD

**Issue by Askaholic** [FAForever/fa#4933]
**Describe the bug**
Here's an error from the server log:
```
WARNING  May 20  02:07:01 GameConnection.19995744        Malformed game stats reported by Tefen: '..."massin":{"total":-1.,"reclaimed":70100....'
```
The game id for this game is `19995744`.

I was able to verify that the issue is that `1.0` gets serialized as `1.` by running the following code:
```python
import json

json.loads('1.')
```

**Expected behavior**
Integers should either be serialized with no period or with a `0` on the end.

**Comment by Garanas** [comment]
This is related to the module we use: `lua\system\dkson.lua` 🤔

**Comment by Garanas** [comment]
How high of a priority is this? Does it, for example, also impact the rating of a game?

**Comment by Askaholic** [comment]
I don’t think it happens very often so probably not a very big issue. This is the first time I’ve ever noticed an error like that in the server logs. I think it probably only affects achievements, but if the same JSON serializer is used for other messages it could affect those too.
