### ISSUE TITLE
shadow blinking

### ISSUE THREAD

**Issue by robotcatt** [FAForever/fa#4940]
With extended graphics we push the resolution to 2048. Anything more doesn't appear to have an immediate visual effect

i found some.
in mesh.fx
float ComputeShadowPCF( float4 shadowCoords)
...
float offset = texel; to float offset = texel+1; or more fix shadow blinking with self shadow
(check uef com leg and uef mex)

_Originally posted by @Garanas in https://github.com/FAForever/fa/issues/4920#issuecomment-1554267632_

**Comment by Garanas** [comment]
@BlackYps can you look into this?

**Comment by robotcatt** [comment]
with beta-for-pbr-shaders 
[kyros.nxt.zip](https://github.com/FAForever/fa/files/11522750/kyros.nxt.zip)

**Comment by BlackYps** [comment]
When you say shadow blinking, you mean that the self-shadows sometimes seemingly randomly disappear when moving the camera?

**Comment by robotcatt** [comment]
yes, disappear  or drastically change

**Comment by BlackYps** [comment]
I can't confirm that changing the offset helps with shadow flickering at all.

**Comment by robotcatt** [comment]
agree, it work only for current camera position.
im try undestand how it work. 
float ComputeShadowPCF( float4 shadowCoords)
points for shadow lookup
 float depthArray[5];
im add more points, shadow better, but more  more load
float depthArray[10];
 depthArray[0] = tex2D( shadowPCFSampler, shadowCoords.xy + float2( -(texel * 0.5f),	0.0f ) ).r;
    depthArray[1] = tex2D( shadowPCFSampler, shadowCoords.xy + float2( 0.0f,  -(texel * 0.5f)) ).r;
    depthArray[2] = tex2D( shadowPCFSampler, shadowCoords.xy + float2( -offset,			0.0f ) ).r;
    depthArray[3] = tex2D( shadowPCFSampler, shadowCoords.xy + float2(  offset,			0.0f ) ).r;
    depthArray[4] = tex2D( shadowPCFSampler, shadowCoords.xy + float2( 0.0f,		  -offset ) ).r;
    depthArray[5] = tex2D( shadowPCFSampler, shadowCoords.xy + float2(  (texel * 0.5f),	0.0f ) ).r;
    depthArray[6] = tex2D( shadowPCFSampler, shadowCoords.xy + float2( 0.0f,		  offset ) ).r;
    depthArray[7] = tex2D( shadowPCFSampler, shadowCoords.xy + float2( 0.0f,		  offset* 0.5f) ) ).r;   
    depthArray[8] = tex2D( shadowPCFSampler, shadowCoords.xy + float2( -offset*2,			0.0f ) ).r;
    depthArray[9] = tex2D( shadowPCFSampler, shadowCoords.xy + float2(  offset*2,			0.0f ) ).r; 
[shadow .nx2.zip](https://github.com/FAForever/fa/files/11558552/shadow.nx2.zip)

 need cheak

**Comment by robotcatt** [comment]
i can. it work with pbr shaders. just delete .zip
[kyros.nxt.zip](https://github.com/FAForever/fa/files/11561487/kyros.nxt.zip)
![pbr+ shadow](https://github.com/FAForever/fa/assets/133477991/2b1fd96f-e9f0-4576-a756-fb8ef0d13c9e)

**Comment by BlackYps** [comment]
Feel free to reopen, but this seems to be abandoned
