### ISSUE TITLE
feature request: lessen the impact of bad apples

### ISSUE THREAD

**Issue by jnorthrup** [FAForever/fa#496]
rationale: sometimes something sucks. not all participants handle adversity in the same way, and nowhere more obvious than in the skill bracket that enables FAF to grow as a community of players, the lowest skill bracket.

As an average player, in the average matches, I find this is still a common turn-off, but I also have kids who play and are missing the best part, online competition, due to the predictably awful things that roll across the screen.

taking cues from several more recent (dare I say "Family") game communities that don't typical unleash verbal abuse upon participants:
- provide a match option which doesn't allow banter between non-allied players. rationale: frequently a player realizing an unintended handicap goes on tilt and starts to guide the enemy to vulnerabilities; poor sportsmanship is unenjoyable for both sides.
- provide a match option which allows team vote-kick.  rationale: same as previous 
- provide a match option which allows in-game /ignore
- language filter option (yeah, weak, but still better than nothing)

**Comment by ChrisKitching** [comment]
> provide a match option which doesn't allow banter between non-allied players.

This seems quite achievable, and more generally useful: the amount of times I've failed to hold shift while pushing enter and leaked sensitive information to the enemy is embarrassingly high.

Of course, this isn't sufficient to avoid undesirables and their verbal tirades.

> provide a match option which allows team vote-kick. rationale: same as previous

What's the use-case of this? Doesn't losing a teammate (even an objectionable one) simply make the game differently unpleasant?

> provide a match option which allows in-game /ignore

There are already plans to expand the reach of the "foe" system from the FAF client into the game, so should you end up in a game with a foe their messages won't reach you. It'd be a relatively simple matter to allow writing to the foe list from in-game.

> language filter option (yeah, weak, but still better than nothing)

Language filters do not work.

- Anyone with half a brain can figure out how to express their chosen expletive in a way that tricks the filter.
- In a multilingual environment such as this one the false positive rate will be unacceptably high: objectionable words in one language are perfectly valid in another.

It's simply not possible to do language filtering right. The frustration to users from the inevitable false-positives will most surely outweigh the gains from providing a (very slightly) more child-friendly environment.


In general, it's impossible to both have a usable chat system and to prevent anyone from ever seeing some bad words. Even "child-friendly" communities such as "Club Penguin" rely quite heavily on human moderation to try and weed out irritating people (as well as employing a truly rage-inducingly restrictive language filter).

Sensible ways forward, then, seem to be:

- Allow the hosts of games to disable inter-team chat. (useful to prevent accidents as well as to reduce the chance of having to talk to irritating morons)
- Provide an option in the game settings to disable chat entirely (which would presumably be sufficient for you to protect your children from badness, at the expense of their being able to communicate). This could perhaps be extended to allow the stipulation of a whitelist of people with whom you can communicate.
- Extend the "foe" system into the game.

**Comment by MrRowey** [comment]
@Garanas with by uing the foe you cna stop player joining the game. i dont see us adding a vote to kick / dont see it being possible with out abuse
