### ISSUE TITLE
Building explosions should flatten trees

### ISSUE THREAD

**Issue by BlackYps** [FAForever/fa#4976]
**Describe the feature**
When volatile buildings die they deal damage. Currently trees are pretty unfazed by this. Interestingly they sometimes catch fire, but in general they just keep standing there. It would be pretty cool if the explosion flattened the trees. This would also help people to get a feeling how far the damage radius reaches on different volatile buildings, but this is just a sidenote.

Additional sidenote: It would be even cooler if we spawned a sonic wave that grows to the size of the explosion radius, but this might be complicated to do, because then we probably have to sync the speed of the shockwave with the trees falling and suddenly everything gets 10 times as complicated. So as a baseline I think the trees simply falling is enough.

**Comment by Garanas** [comment]
We're already working on your suggestions 👍 

> Additional sidenote: It would be even cooler if we spawned a sonic wave that grows to the size of the explosion radius, but this might be complicated to do, because then we probably have to sync the speed of the shockwave with the trees falling and suddenly everything gets 10 times as complicated. So as a baseline I think the trees simply falling is enough.

The ACU gate-in animation does this, it isn't as difficult as it looks like but it does require careful tweaking

> When volatile buildings die they deal damage. Currently trees are pretty unfazed by this. Interestingly they sometimes catch fire, but in general they just keep standing there. It would be pretty cool if the explosion flattened the trees. This would also help people to get a feeling how far the damage radius reaches on different volatile buildings, but this is just a sidenote.

I agree, see also: 

- https://github.com/FAForever/fa/pull/4977


There's a lot we can do to improve the death threads (explosion) of units in general.

**Comment by Garanas** [comment]
![image](https://github.com/FAForever/fa/assets/15778155/85bc2b8f-ac9a-494c-b2f4-3ffb49ca18ca)
