### ISSUE TITLE
Balance idea: Torp Bomber Anti Torp Interaction

### ISSUE THREAD

**Issue by Spikey84** [FAForever/fa#4979]
## Intended changes

Allow torp bomber torpedoes to be blocked by anti torp. Make sure each flare has a limit to how many torps it can block.

## Thoughts on the changes

This will further nerf torp bombers while making the interaction more intuitive for the player.

_This is a balance idea from the balance team. It is not set in stone, it may be adjusted or rejected as the changes are tested._

**Comment by Garanas** [comment]
Do you want me to pick this up?

**Comment by Spikey84** [comment]
That would be awesome.
