### ISSUE TITLE
Balance idea: Cooper Adjustment

### ISSUE THREAD

**Issue by Spikey84** [FAForever/fa#4980]
## Intended changes

Cooper:
```
- Formation change to clump them more
- Increase range by 5
- Decrease hp, mass, e, and build time by 10%
```

## Thoughts on the changes

Coopers will be getting a more tight formation so they cover eachother better with their torp defense. Additionally they get multiple stat changes to get an overall buff.

_This is a balance idea from the balance team. It is not set in stone, it may be adjusted or rejected as the changes are tested._

**Comment by Fichom** [comment]
Can you elaborate on what "tighter formation is"? I'm guessing it's how close they are when you move them. That sounds great, but the problem is you usually move them in a group of other units, so that wouldn't affect the grouping? Or am I wrong?

**Comment by MrRowey** [comment]
> Can you elaborate on what "tighter formation is"? I'm guessing it's how close they are when you move them. That sounds great, but the problem is you usually move them in a group of other units, so that wouldn't affect the grouping? Or am I wrong?

yes and if all goes as plan you will be able to try the changes as of next week on fafbeta
