### ISSUE TITLE
Balance idea: Aeon Carrier TMD

### ISSUE THREAD

**Issue by Spikey84** [FAForever/fa#4982]
## Intended changes

Add TMD to the aeon carrier. Would include some model work.

## Thoughts on the changes

Gives aeon the ability that all other carriers have.

_This is a balance idea from the balance team. It is not set in stone, it may be adjusted or rejected as the changes are tested._

**Comment by MrRowey** [comment]
@MadMaxFAF Don't supposed you would be intrested in helping out with this ?

**Comment by Garanas** [comment]
It is better to first just add the weapon to experiment with the changes. Once accepted, Madmax can adjust the mesh accordingly with the guarantee that it will end up in the game

**Comment by MadMaxFAF** [comment]
you can use some random bone for the tmd for testing, then is accepted i can redo the mesh and as jip says

**Comment by MrRowey** [comment]
@Spikey84
