### ISSUE TITLE
Balance idea: Mercy Rework

### ISSUE THREAD

**Issue by Spikey84** [FAForever/fa#4985]
## Intended changes

```
- Lower damage
- High AOE
- Buff HP
```

## Thoughts on the changes

Based on [Deribus's suggestion](https://forum.faforever.com/topic/1834/ideas-for-mercy-changes/12?_=1685304186726) from a while ago, this changes the mercies role from a snipe unit to a low damage AOE unit. 

_This is a balance idea from the balance team. It is not set in stone, it may be adjusted or rejected as the changes are tested._

**Comment by Azraeel** [comment]
Buff Fuel pls
