### ISSUE TITLE
Factories upgrading to support factories recieve damages on their build bar and not health bar

### ISSUE THREAD

**Issue by ppipp** [FAForever/fa#499]
Not sure if it's a known bug, but I watched a game between Voodoo and Lextoc and noticed that a land factory that is being upgraded to a support factory (not HQ) is invincible. I checked in game afterwards and got the same result with a land factory. If you upgrade it to HQ and it is attacked, it will be damaged. If you upgrade it to support factory, it will not recieve any damage until the upgrade is over (and if you pause the upgrade, it's invincible to damage for a good amount of time, not forever though). It's still vulnerable to reclaim.

**Comment by ppipp** [comment]
Replay 3136043.

I figured what happens : during the upgrade, the construction progress bar takes the damage as if it was the health bar. So either the attack force is strong enough to counterbalance the buildspeed, either it's not and the factory finishes to be built without having been injured.

**Comment by aeoncleanse** [comment]
Yeah the upgrade process here, in fact the entirety of the Engiemod factory implementation needs to be totally rewritten. It's needlessly overcomplicated and full of holes.

**Comment by Sheeo** [comment]
Thanks for the amendment @ppipp! Indeed these are issues with the engimod implementation of support factories.

I thought we had this fixed with #104. It's related to #65, for which we also need a fitting issue.

**Comment by Crotalus** [comment]
Fixed in release/3641
