### ISSUE TITLE
Change shield of the Bulwark

### ISSUE THREAD

**Issue by BlackYps** [FAForever/fa#4990]
## Intended changes

Change the shield height scale on the UEF shield boat, so the shield equator is at the sea level. This will help seeing where the shield actually intersects with the water surface. As right now that is very hard.
![Screenshot 2023-05-28 231443](https://github.com/FAForever/fa/assets/52536103/7553576c-7240-4f47-9503-f2d194a345b1)

**Comment by Garanas** [comment]
It is offset to prevent interceptors and fighters from interacting with it

**Comment by BlackYps** [comment]
here is an excellent diagram of what I am proposing
![grafik](https://github.com/FAForever/fa/assets/52536103/d5f7f4cb-a638-4f06-b597-e1318a694401)

**Comment by BlackYps** [comment]
how does the czar shield work?

**Comment by Garanas** [comment]
It is a personal shield with a custom mesh, but in the end the collider is still a box:

![image](https://github.com/FAForever/fa/assets/15778155/b8001e18-0cc2-4c9f-a32c-2c43d8018c42)

**Comment by BlackYps** [comment]
And the sphere can't be scaled along one axis?

**Comment by Garanas** [comment]
Not that I am aware of. We can only give it an offset, which is what we did to the Bulwark: the shield is really large, but because of the offset we only see the top bit of the sphere

**Comment by ComradeStryker** [comment]
Would it be possible to give it the same properties as that of the UEF T2 static shield?

This way, you're using an existing model without needing to adjust the actual shield side and or scaling it.

**Comment by BlackYps** [comment]
I don't really understand what problem exactly you are trying to solve here and how your solution would solve it. Can you elaborate?

**Comment by ComradeStryker** [comment]
Your goal was to adjust the shield size and scale, correct?
Instead of doing that, since it seems it isn't possible... 
Would it instead be possible to copy the shield properties from a different unit or, rather structure in this case, and replace the Bulwark's shield entirely?

Baring actual shield stats, you'd be replacing the physical shield itself, if that makes sense.
Could that work?

**Comment by ComradeStryker** [comment]
When I messed with the shield boat a while back for one of my forum posts, 
I recall seeing that units/structures and their shields are two separate entities, meaning... 
you could theoretically swap them, no?
I mean... I didn't swap them, but I replaced them, lol.

---

https://forum.faforever.com/topic/4606/the-problems-with-the-uef-part-5-the-bulwark?_=1686430019757
https://forum.faforever.com/assets/uploads/files/1659076084124-383baa31-aea6-4a3a-a140-679c8b38566b-image.png
https://forum.faforever.com/assets/uploads/files/1659076388789-2df045bc-55d5-48ce-856b-5adfdcc5ab2e-image.png

**Comment by BlackYps** [comment]
Ah, this seems to be a misunderstanding. Jip was saying that it is impossible to scale the shield bubble along a single axis to create an elliptical shape. That was what I was suggesting. Changing other properties of the shield is no problem.

**Comment by MrRowey** [comment]
@BlackYps Could you provide a draft version of what you propose?

**Comment by BlackYps** [comment]
Here is what I propose: https://github.com/FAForever/fa/issues/4990#issuecomment-1567425188
But according to Jip it is technically impossible

**Comment by ComradeStryker** [comment]
The closest I was able to mimic the current shield size, whilst making it steeper at the edges was at these values:

ShieldSize = 120 -> 87
ShieldVerticalOffset = -50 -> -33

Here are some images to showcase the changes.
(Left is new, right is old.)

Near similar height.
![image](https://github.com/FAForever/fa/assets/121060254/56396af5-b8a4-479d-aa2d-3838901a0395)

Near similar usable range at Sea level
![image](https://github.com/FAForever/fa/assets/121060254/148907e1-985e-40fe-88af-21cbe9697b28)

Noticeably Steeper:
![image](https://github.com/FAForever/fa/assets/121060254/10291ac4-50a5-445c-84f8-3de43bf6e2ff)

Hope this helps! 

---

~ Stryker

**Comment by Spikey84** [comment]
Can I close this? Since its technically impossible

**Comment by BlackYps** [comment]
Idk, Stryker's proposal seems like an improvement

**Comment by ComradeStryker** [comment]
Just a small improvement, If I may say.
But, I'm sure you guys could probably alter the stats so that would look a lot better.

---

~ Stryker

**Comment by MrRowey** [comment]
Closing this issue for now as it's not technically possible to do what we want

**Comment by Garanas** [comment]
And we have a different way to visualize where it intersects, with thanks to https://github.com/FAForever/fa/pull/5737
