### ISSUE TITLE
Shields do not protect from ACU explosions

### ISSUE THREAD

**Issue by Basilisk3** [FAForever/fa#5006]
**Describe the bug**
ACU explosions can destroy units through shields, even though they only do 2500 damage. A low damage explosion like this should not be able to kill units that are protected by shields that sometimes offer over 20000hp of protection. 

This is also very undesirable gameplay wise, as it enables players to teleport into clumps of drones or tech 3 engineers around high value targets, and destroy them all at the same time. 

**There is no counterplay to this, it is impossible to prevent. This is highly abusable and very easy to do.**

**Expected behavior**
ACU explosions should be blocked by shields, if the shield bubble has enough hp left.

**Additional context**
Inspired by a recent thread on the FAF forums.

My guess is, that this is because ACU explosions are handled similarly to those of stationary nukes internally.

**Comment by Garanas** [comment]
I tried to look it up but I can't find how these explosions are made at the moment. Your explanation sounds legit.

This is a balance issue, therefore @Spikey84

**Comment by ComradeStryker** [comment]
I've also noticed this. 
When a player disconnects (in TMM), even if they are under a shield, everything around them blows up with them. 
Radars, engineers, units, etc.

I believe this is because all projectiles - and consequently - their damage and explosions go through allied shields without nullification since they are not an enemy damage source.

**Comment by Tagada14** [comment]
Would love to have this fixed if anyone has the know-how to pick this up

**Comment by Garanas** [comment]
This is possible 😄 . The problem is that the 'average nuke' doesn't deal normal area damage but it deals 'ring damage'. And ring damage ignores shields. If we make the nuke deal normal area damage (and make those overlap) then it can take into account shields.

https://github.com/FAForever/fa/assets/15778155/329c82b2-a911-474f-b155-22049ce95ee6

![image](https://github.com/FAForever/fa/assets/15778155/6fd65853-6a86-450c-aa4e-8e8cc0d43c2a)

**Comment by Garanas** [comment]
A Sanctuary 😃 

![image](https://github.com/FAForever/fa/assets/15778155/958a67c9-fd02-44f6-9b88-2b3756b5bada)

**Comment by ComradeStryker** [comment]
That's actually cool.

**Comment by Basilisk3** [comment]
**Amazing.** This is a big deal, and makes much more sense as well.

**Comment by Tagada14** [comment]
Will this effect normal nukes? They should still ignore shields.

**Comment by Garanas** [comment]
No, they'll do what they do now

**Comment by lL1l1** [comment]
@Garanas I tried replicating this and I found it's far more difficult than it seems. Using the default DamageArea function is easy, but the way shields work when they have armor is that they reduce the incoming damage by the armor multiplier, and then let the rest through. 
For example: 2500 damage explosion with 50% damage vs 'structure' armor is reduced by 1250 by the shield (2500 * 0.5), and the remaining 1250 damage passes right through onto all the units under the shield. With the current 0.032 multiplier the shield absorbs 80 damage and lets 2420 through.
It also behaves very weirdly with overlapping shields.
Annoyingly the armor only updates after restarting the game, and it crashes if you use the in-game restart game after changing `armordefinition.lua`.
<details>
<summary> My test weapon inside defaultweapons.lua that replaces DeathNukeWeapon for ACUs</summary>

```lua
---@class ACUDeathWeapon : BareBonesWeapon
ACUDeathWeapon = ClassWeapon(BareBonesWeapon) {
    ---@param self ACUDeathWeapon
    OnFire = function(self)
    end,

    ---@param self ACUDeathWeapon
    Fire = function(self)
        local bp = self.Blueprint
        local unit = self.unit
        local proj = unit:CreateProjectile(bp.ProjectileId, 0, 0, 0, nil, nil, nil):SetCollision(false)
        proj:ForkThread(proj.EffectThread)

        -- Play the explosion sound
        local audNukeExplosion = proj.Blueprint.Audio.NukeExplosion
        if audNukeExplosion then
            self:PlaySound(audNukeExplosion)
        end

        --Inner then outer ring damage
        DamageArea(unit, unit:GetPosition(), bp.NukeInnerRingRadius, bp.NukeInnerRingDamage,
            bp.DamageType or 'Normal', bp.DamageFriendly or false, false)
        DamageArea(unit, unit:GetPosition(), bp.NukeOuterRingRadius, bp.NukeOuterRingDamage,
            bp.DamageType or 'Normal', bp.DamageFriendly or false, false)
    end,
}
```
</details>

**Comment by Garanas** [comment]
I'll have to look into it again. I do not recall running into the problems you describe

**Comment by Basilisk3** [comment]
> A Sanctuary 😃
> 
> ![image](https://private-user-images.githubusercontent.com/15778155/264422917-958a67c9-fd02-44f6-9b88-2b3756b5bada.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg3MTM5ODksIm5iZiI6MTcwODcxMzY4OSwicGF0aCI6Ii8xNTc3ODE1NS8yNjQ0MjI5MTctOTU4YTY3YzktZmQwMi00NGY2LTliODgtMmIzNzU2YjViYWRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIzVDE4NDEyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYyZDgxMDU1MDc5NjQ2NGY1MGVhY2Y1OTJjYjdiMzRkYmVjYjMzNTlhMTA0Y2YzOWNjNzRiN2YzMDFhNTg4NWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XMdeRl3mwBHSrmEzLguTDpAXvDX6-XODLFcq1LR3vmo)

Do you still have the code? I would love to test this out!
