### ISSUE TITLE
Shield disruptor not working on personal shields

### ISSUE THREAD

**Issue by Sheeo** [FAForever/fa#501]
http://forums.faforever.com/forums/viewtopic.php?f=3&t=9518&p=95067#p95045

**Comment by aeoncleanse** [comment]
How did we overlook this one? 0_0

**Comment by ResinSmoker** [comment]
Any lua errors from this?

**Comment by Sheeo** [comment]
It fails silently, #504 fixes it.

We should look at the performance implications of doing this for all units at some point, however. It would be more ideal to use the `State` class to avoid having to do this for all units in all states.

**Comment by Crotalus** [comment]
2706b373a6497c156d7088980752d34a45c3ada2
