### ISSUE TITLE
Balance idea: Amphibious Land Unit Torp Change

### ISSUE THREAD

**Issue by Spikey84** [FAForever/fa#5012]
## Intended changes

```
30 dps for bricks
7.7 -> 15 dps Wagner
15 -> 30 dps for Othuum
15.4 -> 10 seconds for torp defense fire cycle
```

## Thoughts on the changes 

Changes based on [this](https://github.com/FAForever/fa/pull/4935) Pr by [Basilisk3](https://github.com/Basilisk3). We went a bit farther as to make these units more viable underwater. 

_This is a balance idea from the balance team. It is not set in stone, it may be adjusted or rejected as the changes are tested._

**Comment by Basilisk3** [comment]
Hey, I tested the changes, and they seem fine for the most part. The only issue I see, is that the Brick seems too strong with this. Two of them will handily beat a Seraphim destroyer. I think that is a bit too much.

**Comment by MrRowey** [comment]
the idea of these Issues are that they get completed so they can be pushed to the FAFBeta game type so more people can test out the changes. can you make the PR with the changes as descried so we can add them in
