### ISSUE TITLE
Balance idea: E Storage Buff and OC Nerf

### ISSUE THREAD

**Issue by Spikey84** [FAForever/fa#5016]
## Intended changes

E Storage
```
- Increase the capacity x2
- Increase adjacency x2
```

OC
```
Increase the energy required by x1.5
```

## Thoughts on the changes
This works to make ACU less oppressive vs higher tech units. Works with #5014 to reduce the effectiveness of the Aeon gun com.

_This is a balance idea from the balance team. It is not set in stone, it may be adjusted or rejected as the changes are tested._

**Comment by AugustZilakovs** [comment]
Ill work on this one
