### ISSUE TITLE
Adjacency on SMLs & SMDs.

### ISSUE THREAD

**Issue by ComradeStryker** [FAForever/fa#5029]
**Describe the bug**
Resource buildings adjacent to SMLs and SMDs will not affect the structure's resource cost draw if they had started building a projectile before the adjacency came to be.

For example, if a player constructs an SMD, starts construction of a missile, then surrounds the launcher with any tech-level power generator, the adjacency bonus will not take place UNLESS the structure finishes the current project or the project is restarted.

The opposite is true as well. If a resource generator (power or mass) is placed adjacent, then the launcher starts construction, the removal of the adjacent structure will not increase the cost of the projectile back to normal until the project is complete or restarted.

---

**To Reproduce**
Sandbox game:

No Resource Reduction:
- Spawn in an SMD/SML
- Start a missile.
- Cap with pgens, mexes/mass fabs
- Observe resource costs

Free Resource Reduction:
- Spawn in an SMD/SML
- Cap with pgens, mexes/mass fabs
- Start a missile.
- Remove pgens, mexes/mass fabs
- Observe resource costs

---

**Expected behavior**
Adjacency works properly.

---

**Additional context**
Gametype: FAF (Live)
Replay showcasing bug:
https://replay.faforever.com/20144284

**Comment by MrRowey** [comment]
https://github.com/FAForever/fa/issues/3641 <- See @Garanas Comment here cant fix that issuse

**Comment by ComradeStryker** [comment]
Ahh, bummer. 

Welp. Apologies for being late to the party.
