### ISSUE TITLE
Emerge/Submerge toggle buttons do not work correctly

### ISSUE THREAD

**Issue by EvildrewFAF** [FAForever/fa#5039]
![image](https://github.com/FAForever/fa/assets/46637108/15c7a82c-0fd4-48d5-ba4e-e280827901d2)
If you click on the icon while submerging/emerging (double click) you can be confused by the symbol indicating that you can emerge and already emerged sub, same for a submerged sub looking like it is surfaced based on the icon. It can cause confusion....

Either the button should be disabled or not appear temporarily after clicking it during the emerge/submerge process until it is complete.

**Comment by Garanas** [comment]
The UI layer doesn't know when the sequence is complete. We can try and temporarily disable it for a second?

**Comment by EvildrewFAF** [comment]
Emerging/Submerging takes about 10 seconds but that is just a number, might be possible to put it in the OnMotionVertEventChange / OnLayerChange function in the scripts? Could be possible to use the logic behind upgrading your ACU with a TML launcher and removing it to make the icon appear/disappear?

**Comment by Garanas** [comment]
The suggestion works
