### ISSUE TITLE
Balance idea: Tweak Mercy

### ISSUE THREAD

**Issue by MrRowey** [FAForever/fa#5044]
## Intended changes
Update the changes made to the mercy that is currently in beta
```
- Increase AoE from 5 to 7
- Decrease Damage from 70 (1.4k total) to 30 (600 total)
- Add Vision Entity (Like the Lobo)
```

_This is a balance idea from the balance team. It is not set in stone, it may be adjusted or rejected as the changes are tested._

**Comment by AugustZilakovs** [comment]
ill get this one
