### ISSUE TITLE
Balance idea: Deceiver Buff

### ISSUE THREAD

**Issue by MrRowey** [FAForever/fa#5053]
With the Changes made in #5052 the Deciver will recite a buff to make it so this isn't a Nerf.

```
- Buff Range by 15% 
```

_This is a balance idea from the balance team. It is not set in stone, it may be adjusted or rejected as the changes are tested._

**Comment by MrRowey** [comment]
@Ruan7053 would you be interested in picking this one up?

**Comment by Ruan7053** [comment]
I will get it @MrRowey.
