### ISSUE TITLE
Game crash - "Error ` `"

### ISSUE THREAD

**Issue by 63427083** [FAForever/fa#5067]
**Describe the bug**
Game crashed. No debug window like in #5030 popped up, but just a two line window saying something like "Error ` `".

**To Reproduce**
Like #5030 there wasn't any specific interaction happening. At the time i was quite literally just watching getting more SACUs produced. 

**Expected behavior**
Not crash.

**Screenshots**
\-

**Additional context**
Log in game_20170017.log. There was no debug window to copy text from.

[game_20170017.log](https://github.com/FAForever/fa/files/11738722/game_20170017.log)

**Comment by MrRowey** [comment]
https://discord.com/channels/197033481883222026/1083855787518079066 Please See the Tech-Support Forum on the discord and enable the debugger so it can give more information and then repost the log if the issue happens again
