### ISSUE TITLE
ACU teleports too fast.

### ISSUE THREAD

**Issue by ThePlasmaWolf** [FAForever/fa#5078]
**Describe the bug**
ACU teleport has been reduced to 15 seconds, several months ago. It **still** hasn't been reverted back to the 25 seconds it used to be. See Also Jip's comment in this thread: https://forum.faforever.com/topic/5850/teleport-speed

**To Reproduce**
Spawn in ACU, get teleport upgrade, order to teleport. It'll take 15 seconds

**Expected behavior**
Used to be 25 seconds for years.

**Comment by Garanas** [comment]
This is fixed in the game patch set for the 24th of June
