### ISSUE TITLE
Bad consumption values when mass stalling on develop

### ISSUE THREAD

**Issue by Sheeo** [FAForever/fa#509]
d1966971b75cfa78308ebc3a2a020ab15402aadb on the 3641 release branch reverts commit e70de3d18589acdee319a1453f10be536917e331 because it causes wrong economy drain rate information when mass stalling.

**Comment by Crotalus** [comment]
Oh, seems like I reversed useRequested and useActual in the if-statement for storage level

**Comment by Sheeo** [comment]
All right -- it can go in 3641 if we remember to regression test it thoroughly

**Comment by Crotalus** [comment]
Let's wait to remerge to 3641 for now though... it can as well come in balance patch
