### ISSUE TITLE
Balance idea:  UEF Bubble Shield

### ISSUE THREAD

**Issue by MrRowey** [FAForever/fa#5095]
## Intended changes
Small Buff to the Regen Rate of the Bubble Shield that's on beta

```
- Regen Rate: 42 > 60
- Recharge Time: 175 > 90
```

_Various thoughts on the reasoning of these changes_

_This is a balance idea from the balance team. It is not set in stone, it may be adjusted or rejected as the changes are tested._

**Comment by Term-AZ** [comment]
ill get this one

**Comment by Term-AZ** [comment]
is this for both the commander and support commanders?

**Comment by MrRowey** [comment]
This is for the ACU as it has been moved to be decoupled from the Personal shield upgrade on beta
