### ISSUE TITLE
Balance idea: Torpedo Change

### ISSUE THREAD

**Issue by MrRowey** [FAForever/fa#5096]
## Intended changes
```
Make all Torpedos Invuneralble to Splash Damage
```
_Various thoughts on the reasoning of these changes_

_This is a balance idea from the balance team. It is not set in stone, it may be adjusted or rejected as the changes are tested._

**Comment by MrRowey** [comment]
@Garanas what would be the best approach to this?

**Comment by Garanas** [comment]
I don't know yet. I'll look into it after the release of the developers iteration
