### ISSUE TITLE
Balance idea: Missile Speed

### ISSUE THREAD

**Issue by MrRowey** [FAForever/fa#5097]
## Intended changes
Increasing the Speed of the Missile of Mobile Missile Launchers (MML) & Spearhead

```
- 1.5x Speed Increase
- Lower the Acceleration
- Test that they can still hit targets
```

_Various thoughts on the reasoning of these changes_

_This is a balance idea from the balance team. It is not set in stone, it may be adjusted or rejected as the changes are tested._

**Comment by Term-AZ** [comment]
ill get this one

**Comment by Term-AZ** [comment]
> 

yeah will do

**Comment by MrRowey** [comment]
@Term-AZ just realised that you edited the projectiles them self not the weapon on the units will revert the merged changes and could you re-submit your PR

**Comment by BlackYps** [comment]
The unit BP doesn't have these variables. It's all in the projectile files

**Comment by MrRowey** [comment]
Maybne the 1.5x speed was too slow as it didn't see any difference maybe it needs to be 1.75
