### ISSUE TITLE
Balance idea: Economy Structures

### ISSUE THREAD

**Issue by MrRowey** [FAForever/fa#5098]
## Intended changes
Changes to Mass Extractors/Power Generators/ Mass Storage HP

### T1 Mex
```
Cyb: 500 -> 360
Uef: 760 -> 400
Aeon 600 -> 370
Sera: 650 -> 380
```
### T1 Power
```
Uef: 760 -> 600
Aeon: 600 -> 525
Sera:  650 ->  550
```
### T2 Mex
```
Cyb: 1800 -> 1800
Uef: 2500 -> 2000
Aeon: 1900 -> 1900
Sera: 2000 -> 1950
```
### T2 Power
```
Cyb: 1800 -> 2200
Uef: 2500 -> 2500
Aeon: 1900 -> 2300
Sera: 2000 -> 2400
```
### T3 Mex
```
Cyb: 6000 -> 6250
Uef: 9000 ->7000
Aeon: 6200 -> 6500
Sera: 7000 -> 6750
```
### Mass Storage
```
Cyb: 800 -> 600
Uef: 1200 -> 800
Aeon: 1000 -> 650
Sera: 1100 -> 700
```

_A clear concise description of the changes_

## Thoughts on the changes

_Various thoughts on the reasoning of these changes_

_This is a balance idea from the balance team. It is not set in stone, it may be adjusted or rejected as the changes are tested._

**Comment by Ruan7053** [comment]
I'll get this one
