### ISSUE TITLE
Drones Struggle To Assist Naval Facilities

### ISSUE THREAD

**Issue by ComradeStryker** [FAForever/fa#5115]
**Describe the bug**
Drones are unable to assist naval factories when the factory is currently building a unit.
During this timeframe, the drones fly back to land and idle on the beach for a second or two. 
Then they fly back to the Naval Factory to assist it.

---

**To Reproduce**
Sandbox Game:
- Spawn Kennel Drones / ACU with Drone Upgrades / SACU with Drone Upgrade (Engineer Preset).
- Spawn Naval Factory and start construction of a unit.
- Order Drones to assist Naval Factory
- Observe Movement

---

**Expected behavior**
Drones fly to Naval Facility and assist without delay or issue.

---

**Additional context**
Gametype: FAF (Live)
Replay showcasing bug:
https://replay.faforever.com/20214915

**Comment by Garanas** [comment]
It could be because of the mountains in your replay, causing the drones to go up and down

![image](https://github.com/FAForever/fa/assets/15778155/70cbe9f4-ace8-461c-8151-bf2b8117e12a)

When I test the same type of behavior on Seton's Clutch it appears to work fine:

https://github.com/FAForever/fa/assets/15778155/7c49eba0-acc4-4ec1-a507-3e2f4686169b

**Comment by ComradeStryker** [comment]
https://replay.faforever.com/20215054

https://replay.faforever.com/20215015

**Comment by ComradeStryker** [comment]
In this replay, the pathing 'bug' happens only with the factory that is closest to land.
So, perhaps this is a clue as to what's going on?

Map: Adaptive Turtle Beach
https://replay.faforever.com/20215113

**Comment by Garanas** [comment]
Then what likely happens is that the drones are trying to land, to 'save fuel'. We can adjust that behavior

**Comment by ComradeStryker** [comment]
Update:
Steam FA game has this issue as well, but not as prominent as FAF.
