### ISSUE TITLE
Generate Naval Area markers for MarkerUtilities.lua

### ISSUE THREAD

**Issue by relent0r** [FAForever/fa#5129]
**Describe the feature**
We currently generating some markers when using navmesh like expansion and rallypoint. But we are missing 'Naval Area' markers so the AI does not know where to build naval bases.

The markers should be accessable via the MarkerUtilities module and should be generated along with the GenerateExpansionMarkers function call.

With the current generator for naval areas we get this sort of placement. 

![image](https://github.com/FAForever/fa/assets/34614077/d245f8e0-3dfd-4f25-8022-71c218820e2a)

From memory it is looking for land labels within a certain distance that can be connected to the water node via an amphibious layer. That is why you see the naval area positions in relatively sensible positions except where edge building might be used there won't be any.
It will also make sure there are no other naval area markers within a 60 unit radius of one that has been created. I think this works pretty well.

Its not perfect by any stretch but has some validity. I think taking start markers into account will improve some of the culling. Though keep in mind we can't have a hard cutoff distance wise as there are plenty of maps where the water is quite far from the start location. 

Important to have labels attached to the markers. 

The AI should then be able to figure out which markers it wants to build on via its own logic. They would leverage the return table from PR #4297 to achieve the best position to expand on.

**Comment by Garanas** [comment]
Implemented with https://github.com/FAForever/fa/pull/5407
