### ISSUE TITLE
Issue with default Expansion generation for AI

### ISSUE THREAD

**Issue by relent0r** [FAForever/fa#5140]
**Describe the bug**
The Generate function in /lua/sim/MarkerUtilities/Expansions.lua does not take Spawn markers into account when generating expansion markers.

This will cause AI that don't have validation to try and build expansions on its own Spawn position.

**To Reproduce**
I noticed this on the Swarm AI. It will get an expansion marker using the default AIFindExpansionAreaNeedsEngineer function to pull expansion markers. Then find one that is at the same location at its main base and promptly build a new base. This will in turn cause all sorts of problems with the various managers as it will have two bases running within the same radius.

**Expected behavior**
The Expansion Generation will not create expansion markers within 60-80 units of a 'Blank' marker aka Start Position aka Spawn marker.

**Comment by Garanas** [comment]
Picked this up before the release of 3758
