### ISSUE TITLE
Seraphim Advanced Restoration Field (Enh)

### ISSUE THREAD

**Issue by ResinSmoker** [FAForever/fa#516]
When Enh is swapped out for another, the following lua error shows:
WARNING: Error running /lua/sim/tasks/EnhanceTask.lua script in CScriptObject at 21aaf2f0: ...\gamedata\units.nx2\units\xsl0001\xsl0001_script.lua(410): *WARNING: BUFF: unitBuff.Count is nil.  Unit: xsl0001 Buff Name: SeraphimACURegenAuraSelfBuff Unit BuffTable: 
         stack traceback:
         	[C]: in function `error'
         	...gramdata\faforever\gamedata\lua.nx2\lua\sim\buff.lua(529): in function `RemoveBuff'
         	...\gamedata\units.nx2\units\xsl0001\xsl0001_script.lua(410): in function `CreateEnhancement'
         	...gramdata\faforever\gamedata\lua.nx2\lua\sim\unit.lua(3547): in function `OnWorkEnd'
         	...rever\gamedata\lua.nx2\lua\sim\tasks\enhancetask.lua(83): in function <...rever\gamedata\lua.nx2\lua\sim\tasks\enhancetask.lua:51>

**Comment by ResinSmoker** [comment]
Forgot to mention that this is just FAF, no mods loaded.

**Comment by Sheeo** [comment]
Why was this closed?

**Comment by ResinSmoker** [comment]
Sorry I don't understand

**Comment by Sheeo** [comment]
You closed the issue, I assume this was a mistake.

**Comment by ResinSmoker** [comment]
Aye

**Comment by ResinSmoker** [comment]
So now that this is posted as an issue who can i open a file for this? Initiate a pull ?

**Comment by ResinSmoker** [comment]
I have the fix for this...
XSL0001_script.lua line 410 to 411 looks like this...

            Buff.RemoveBuff(self, 'SeraphimACURegenAuraSelfBuff')
            Buff.RemoveBuff(self, 'SeraphimACUAdvancedRegenAuraSelfBuff')

Change to this...

			if Buff.HasBuff( self, 'SeraphimACURegenAuraSelfBuff' ) then
				Buff.RemoveBuff(self, 'SeraphimACURegenAuraSelfBuff')
			end
			if Buff.HasBuff( self, 'SeraphimACUAdvancedRegenAuraSelfBuff' ) then
				Buff.RemoveBuff(self, 'SeraphimACUAdvancedRegenAuraSelfBuff')
			end

Note: I'll look to see if the Sub commander has the same issue and report back.

Resin

**Comment by ResinSmoker** [comment]
Looks like this is an ACU only bug...
Obviously once this is updated this should resolve this issue.

Cheers!

Resin

**Comment by aeoncleanse** [comment]
:+1:

**Comment by Sheeo** [comment]
I think I would rather change `Buff.RemoveBuff` semantics so it doesn't emit an error if the buff was not there -- interested parties can use `Buff.HasBuff` if they need this information, so the code seems to be overly whiney.

**Comment by ResinSmoker** [comment]
Other parts of the same unit script already using HasBuff. Now as this mechanic already exists it made sense to use it.

**Comment by Sheeo** [comment]
Well can you think of a situation where removing a nonexistant buff would be considered an error?

**Comment by ResinSmoker** [comment]
So long as we remain within the existing "Buffs" infrastructure we won't create problems for third-party mods. However altering Buffs.lua to verify a nill statement instead of doing it on the unit side of things could potentially cause some issues.

**Comment by Sheeo** [comment]
Feel free to comment on the code.
