### ISSUE TITLE
AI does not work anymore - Commander just doing nothing.

### ISSUE THREAD

**Issue by j0schi** [FAForever/fa#5163]
**Describe the bug**
For Uveso, Sorian and the standard AI this is true. The only working AI i found was M27. Commanders just sit there and do nothing. We play on a regular basis with 3 friends, we dont like pvp so much, so the AIs where a good option for us. 

**To Reproduce**
Start any game against AI with 1 other player. The AI also doesnt move when its in the same team as the player so its easy to reproduce. 3 different people tryed to host a game. 

**Expected behavior**
AI should just build and work

**Comment by MrRowey** [comment]
Know issue was due to the recent game update changes in how the base AI system works. Uveso & other AI Dev should be pushing an update soon.
