### ISSUE TITLE
Enemy cannot reclaim upgrading mex that is paused

### ISSUE THREAD

**Issue by Cheyans** [FAForever/fa#519]
Basically what's in the title
Replay: 3219275

**Comment by Crotalus** [comment]
Neutral engineer didn't have any energy so capture is stalling for that reason

**Comment by Crotalus** [comment]
Reopened, seems that it fails to reclaim in Patrol / Attack mode.

**Comment by Crotalus** [comment]
For reference, seems to be a very old bug, 3610 has the same problem

**Comment by aeoncleanse** [comment]
So I think this is fixed in 3641, close issue?

**Comment by Sheeo** [comment]
If this is fixed in 3641, we don't have a pointer to the commit -- can anyone dig that up?

**Comment by aeoncleanse** [comment]
PR 572, not merged yet, my bad. It is, however, ready-looking.

**Comment by Crotalus** [comment]
Yeah, not merged yet due to SetCollisionShape('None') known to crash sim (with sinking air wrecks). Maybe it's to use in this case but I guess it can wait until next patch, we have lots of potential bugs already in 3641

**Comment by aeoncleanse** [comment]
My plan was to get things moving again. To that end, I want to merge a whole bunch of PRs, then look at the list of things which are meant to be fixed and test them all. In the process, any errors can be logged and we can hunt them down and fix the whole lot.

How does no collision shape crash with sinking air wrecks?

**Comment by Crotalus** [comment]
When no collision shape was set on dying air units that was sinking it caused the sim to crash randomly, probably because they sank through seabottom into infinity or something. Probably had to do with the wreck being attached to the sinking projectile.

So my **guess** would be that this change would be safe but you never know :)

**Comment by aeoncleanse** [comment]
That's what I thought, which is why I want to merge and test. Then in the slight chance it's not worked, we can flag and fix it :)

**Comment by Sheeo** [comment]
@aeoncleanse merging into the release branch isn't a precondition for testing.

**Comment by aeoncleanse** [comment]
Which is why I checked it out and did some testing. I cannot make it crash, at least not so far. Trouble is, with something like this, there may not BE a way to replicate it every time, if it ever happens.
