### ISSUE TITLE
Frigate AA performance impact

### ISSUE THREAD

**Issue by Basilisk3** [FAForever/fa#5239]
**Describe the problem**
These weapons are a performance hog. Frigates are spammed a lot, and they all have fast firing AA solutions with lots of low damage projectiles. As soon as a single spy plane flies over them, which happens very often, they all shoot and can cause the game to slow down. Another example would be an ASF-fight over frigates, a scenario which is also pretty common. 

This issue mostly applies to Cybran and Seraphim frigates, UEF frigates have a rather slow rate of fire.

**Possible solutions I could come up with:**
- Reduce their rate of fire by 1/3 or 1/2 but increase their damage accordingly
- Reduce their range
- Remove their projectiles earlier (needs evaluation)

**Comment by Garanas** [comment]
Do you have data on how much the game slows down, such as the amount of time it takes to process a tick of the game (sim time)?

**Comment by Basilisk3** [comment]
I only have anecdotal evidence, it is mostly something that I have been noticing in games. Late in the game, the sim can drop by up to one "sim speed" when a spy plane flies over a lot of frigates.

**Comment by Garanas** [comment]
You can see the sim time by using `ren_ShowNetworkStats`. In your example, say we have this:

https://github.com/FAForever/fa/assets/15778155/032bf0a4-29c5-4b3e-aeff-e9a298a7337c

You can see the base line, it is roughly 2 ms per tick to just have the frigates exist. There are 89 frigates. When there are 23 spy planes flying over it jumps up to 3.0 / 3.5 ms per tick. Which is very reasonable, and a lot more reasonable then we used to have 😄 

What likely happened in your games is that the game was at the edge of the threshold between two sim rates and the spy planes flying over was the drop in the bucket to make it spill over.

What we did in the past to improve this situation is described here:
- https://forum.faforever.com/topic/3808/weapon-target-check-intervals

And some of the result of that is this flag being applied to secondary weapons:
- https://github.com/FAForever/fa/blob/deploy/fafdevelop/units/UES0103/UES0103_unit.bp#L271

**Comment by Basilisk3** [comment]
Hi Garanas, thanks for your detailed reply,

I did the same test with the Seaphim frigate (I think you used the Cybran one in your test).

**Results:**
- Roughly 2 ms with the frigates and spy planes simply existing
- Roughly 6 ms with all frigates shooting at the spy planes

So it looks like the Cybran frigate is fine, but the Seaphim frigate has a much higher performance impact than the Cybran one. Do you believe this is a significant difference and worth tackling?
