### ISSUE TITLE
Aeon shield is barely visible

### ISSUE THREAD

**Issue by speed2CZ** [FAForever/fa#5244]
Now:
![ForgedAlliance_2023-07-20_09-24-53](https://github.com/FAForever/fa/assets/10947024/5e628951-34f8-44aa-ac5d-f41393600179)

Before:
![firefox_2023-07-20_09-24-39](https://github.com/FAForever/fa/assets/10947024/1114982d-6a89-496a-998e-5d64c9f281db)

**Comment by Garanas** [comment]
It is a known issue on land-only maps, should be fixed with https://github.com/FAForever/fa/pull/5162
