### ISSUE TITLE
Request - Repo Permission

### ISSUE THREAD

**Issue by HUSSAR-mtrela** [FAForever/fa#5257]
@Garanas Last year, you gave me [permission](https://github.com/FAForever/fa/pull/4018#issuecomment-1175159034) to push my local branches directly to the FA repo but now it looks like this permission was removed. Can you restore my permission so I can contribute more pull requests or do I need to use forks?

![image](https://github.com/FAForever/fa/assets/11665978/db5ea477-dd01-483d-98b2-48f228e11856)

**Comment by Garanas** [comment]
The permission was removed because you were idle for a while 😄 , I'll give it back to you

**Comment by HUSSAR-mtrela** [comment]
@Garanas thanks for solving this so quickly and I will keep creating PRs more regularly.
