### ISSUE TITLE
Links to github in Units section

### ISSUE THREAD

**Issue by 13DaGGeR** [FAForever/fa#5260]
**Describe the bug**
The unit section of the lobby application has links to users (?). Clicking on such a link will result in a GitHub page displayed in the lobby app, breaking the units section interface.

**To Reproduce**
1. Got to Units tab
2. Click on UEF t1 engineer (or any other unit, as far as I can see)
3. Click the "Compare" yellow button
4. Click the "UEL0105" link under the unit title
5. See "Error Looks like something went wrong!" GitHub page

**Expected behavior**
Either:
1. replace the links with simple text
2. or change the URL to a working one and allow a user to close this page afterward somehow.

**Screenshots**
![image](https://github.com/FAForever/fa/assets/749037/31b5cf3e-2015-48b6-a32a-aa3c07c3a971)
![image](https://github.com/FAForever/fa/assets/749037/ad8e460a-0f09-4c82-b20d-6d6970e529a5)

**Additional context**
FAF version 2023.6.1, launched on win 11.

**Comment by Garanas** [comment]
I don't think this is related to the game, but to the tool behind the units tab. @Sheikah45 do you know what that tool is?

**Comment by Sheikah45** [comment]
Depends which unit database they are using

**Comment by Garanas** [comment]
This is the one that is in the client

**Comment by Sheikah45** [comment]
There are two in the client depending on which one people choose in the settings

**Comment by MostLostNoob** [comment]
The UnitIDs in both the Rackover & Spooky DB in the client will lead to the GitHub pages.

At the present time, links are indeed returning with Error messages, so that needs to be fixed.

@13DaGGeR, regarding getting back to the unit selection page, you just need to right-click the GitHub page & select Go Back, so there's nothing that needs to be fixed with regards to that. With that said, there's no mention of that to be seen, so adding a header or something that is easily seen may be worth looking into.

**Comment by Garanas** [comment]
What are the repositories of those applications?

**Comment by MostLostNoob** [comment]
If I'm not mistaken, these are the repos for the databases:

Spooky: https://github.com/FAForever/spooky-db

Rackover: https://github.com/FAForever/UnitDB

**Comment by Garanas** [comment]
I don't know what more actions are required to get the changes into production. Do you know that @Sheikah45 ?

**Comment by MrRowey** [comment]
This is a Client issue not the UnitDBs as you can use the web version and the link works fine

**Comment by MrRowey** [comment]
Closing as the link are working
