### ISSUE TITLE
Mods Manager is overlapping mod info over the search box

### ISSUE THREAD

**Issue by HUSSAR-mtrela** [FAForever/fa#5280]
**Describe the bug**
Mods Manager is overlapping mod info over the search box in **some window heights** 

**To Reproduce**
- Open Mods Manager
- Change to compact mod list
- Observer search box

NOTE if this does not occur when testing, close Mods Manager and increase height of FA window by 50 pixels and then repeat above instructions.

**Expected behavior**
Mods Manager is not overlapping mod info over the search box. 

**Screenshots**
![image](https://github.com/FAForever/fa/assets/11665978/b1d0fd7a-41e5-4059-81c7-a9652aa26c50)

**Comment by HUSSAR-mtrela** [comment]
I will work on this issue this week

**Comment by Garanas** [comment]
There's also a similar problem with the description of mods being too long. Please make sure you have some UI scaling enabled (at 125%, for example) to also test the UI scaling aspect of it

**Comment by lL1l1** [comment]
Fixed by #5405
