### ISSUE TITLE
The sharing of bases rotates buildings

### ISSUE THREAD

**Issue by Basilisk3** [FAForever/fa#5293]
**Replay ID:** 
#20483389 from 00:21:40 onwards. Best noticed on the pgens, arties and flak in the middle of the map.

**Comment by Garanas** [comment]
@ChessBerry being greedy 😞 

![image](https://github.com/FAForever/fa/assets/15778155/1dde6ac6-5aa8-4d8c-a0ed-4f413e5607e8)

**Comment by Garanas** [comment]
https://github.com/FAForever/fa/assets/15778155/c07cdb27-8b1a-404f-aa89-7828d4dbbc71
