### ISSUE TITLE
chat blocked for host

### ISSUE THREAD

**Issue by spooky** [FAForever/fa#531]
No idea how to reproduce this, but I hosted a game, fiddled with the settings, changed the lobby rule and after that wasn't able to write to chat any more.

**Comment by spooky** [comment]
I was able to write into chat again after a few connects/disconnects from other players

**Comment by Sheeo** [comment]
This was fixed with 59a757b19b1919d868a1623c63b98110fbb176b4

**Comment by Sheeo** [comment]
Reopened this as it still happens.

**Comment by Crotalus** [comment]
Reproducible by opening "Presets" window and closing the windows (welcome + preset window) with ESC-key

**Comment by Crotalus** [comment]
Seems like the escape handler in lua/ui/uimain.lua triggers:
https://gist.github.com/Crotalus/d72cb9f7d3c249a032db#file-uimain-lua-L119

**Comment by ChrisKitching** [comment]
Should be really fixed with 6a7d2512c87961b259f0d8ee096198381b3f19f7 and  6aa5841c2a049732d7ee88abc43603437b4fdd26
