### ISSUE TITLE
Torpedoes do not retarget after original target is destroyed

### ISSUE THREAD

**Issue by Basilisk3** [FAForever/fa#5311]
**The Scenario:**
5 subs/coopers launch their torpedoes at a low-health tech 1 sub. After it is destroyed, all other torpedoes going for this unit self-destruct, even though there are other targets nearby. This leads to a lot of wasted DPS and is really odd to look at sometimes.

The longer the range of the unit, and the slower the torpedoes travel, the worse this gets. Thereby, it is especially noticeable for Coopers, the Atlantis, and Tech 3 subs, which suffer the most from this.

I believe this was fixed for SAM-turrets, and I think it would make sense for it to be fixed here too, especially since torpedoes are much slower.

**Comment by Garanas** [comment]
@Spikey84 and me experimented with this and turned that into a pull request. I can't find it sadly, must have named it wrong

**Comment by Spikey84** [comment]
https://github.com/FAForever/fa/pull/4094 This one i think @Garanas

**Comment by Basilisk3** [comment]
That looks promising. I would love to see this implemented, as it makes units like the Atlantis more viable and also makes more sense in general.

**Comment by Basilisk3** [comment]
There would probably have to be a fail-safe to prevent the unit from abusing this to reach units outside its range.

**Comment by Garanas** [comment]
There already is - it uses the new target of the launcher. That can't be outside of the range of the unit

**Comment by Garanas** [comment]
Marked it as a balance request, @Spikey84 or @Tagada14 can you include it in the next balance meeting?

**Comment by Garanas** [comment]
This was discussed and approved
