### ISSUE TITLE
'launch game' button activate/deactivate logic doesn't work.

### ISSUE THREAD

**Issue by spooky** [FAForever/fa#533]
I'm unable to determine the exact behavior of that button, but it is possible for the button to be active when not all players are ready and that it's inactive when all players are... may be connected to a case when the host has an x before everyone joins in.

**Comment by Sheeo** [comment]
Was connected to a regression with c9cf56dbe2b69ed873cc76792ccba975dbf35ca1.

Changing teams helps in cases when it is disabled, this is being worked on

**Comment by JeroenDeDauw** [comment]
Also observed this. What I noticed is that the button remains disabled when as host you x while not everyone else has yet, and then the other people x. Unchecking ready as host and rechecking it enables the button.

**Comment by Sheeo** [comment]
This should be fully resolved by now on current master
