### ISSUE TITLE
Alternative use of channels for new terrain shaders

### ISSUE THREAD

**Issue by Garanas** [FAForever/fa#5341]
**Describe the feature**

The Direct Draw Surface (DDS) format can introduce compression artifacts. They are best shown 

We expect normals to look like this:

![image](https://github.com/FAForever/fa/assets/15778155/248e3995-af79-4ee1-9592-d5b1e9b8171c)

![image](https://github.com/FAForever/fa/assets/15778155/7cd24066-9022-49c8-8cea-1fe2f2b3324e)

But they end up looking like this if you compress them:

![image](https://github.com/FAForever/fa/assets/15778155/4f372578-10e2-40d9-90d2-c3cb59c9015f)

![image](https://github.com/FAForever/fa/assets/15778155/de9ff34e-c5d0-46ca-8e25-651da2cd141f)

![image](https://github.com/FAForever/fa/assets/15778155/8fb6e000-a100-4739-9d36-20a92efe0504)

The artifacts at the little squares - those are 4x4 clusters of pixels that are mangled by the compression. We can circumvent this by changing what channels we use.

At the moment we use the following channels:

Upper Albedo
 - Red = X-coordinate of map-wide normals
 - Blue = Z-coordinate of map-wide normals
 - Green = Map wide shadows
 - Alpha = Unused

Stratum Albedo 8
 - Red = Red channel of map-wide albedo
 - Blue = Blue channel of map-wide albedo
 - Green = Green channel of map-wide albedo
 - Alpha = Alpha channel of map-wide albedo

Stratum Normals 8
- Red = Map wide specular
- Blue = Unused
- Green = Unused
- Alpha = Unused

I propose we change it to the following:

Upper Albedo
 - Red = Unused (set to 1)
 - Blue = X-coordinate of map-wide normals
 - Green = Unused (set to 0)
 - Alpha = Z-coordinate of map-wide normals

Stratum Albedo 8
 - Red = Red channel of map-wide albedo
 - Blue = Blue channel of map-wide albedo
 - Green = Green channel of map-wide albedo
 - Alpha = Alpha channel of map-wide albedo

Stratum Normals 8
- Red = Unused (set to 1)
- Blue = Map wide specular
- Green = Unused (set to 0)
- Alpha = Map wide shadows

That way we can circumvent the compression artifacts.

**Comment by BlackYps** [comment]
Looks good in theory, but I noticed a problem. You only managed to use the normal layer because you commented out the Sratum6Albedo in the Terrain003 shader. Without that the shader doesn't compile because we exceed the 16 texture limit.

**Comment by BlackYps** [comment]
I think the easiest solution is to just take the memory hit of not compressing that particular texture. If we only store normal channels in the upper albedo then we also have to come up with a solution where we store the shadow map for Terrain001.

We could still try if we can minimise the artifacts by storing the normal in the red and alpha channel and putting the shadow in the green channel
