### ISSUE TITLE
Bug in the latest balance patch, Cruisers TMDs were nerfed instead of getting buffed

### ISSUE THREAD

**Issue by K-ETFreeman** [FAForever/fa#5356]
The quote from the patch note http://patchnotes.faforever.com/balance/3761.html :
"Non-Aeon TMD is buffed to deal with a larger number of missiles"
So, the intention was to **buff** cruisers tmds,
but what was really changed is **Rate of Fire (RoF): 0.5 → 0.25**
Rate of fire is the amount of tmd shots per second, so if before patch TMD was shooting 1 time every 2 seconds, after patch it shoots 1 time every 4 seconds, so it was nerfed in 2 times instead of receiving a buff

Need to change RoF accordingly to the balance team intentions
#5002, #4984

**Comment by K-ETFreeman** [comment]
#4984

**Comment by Garanas** [comment]
@Tagada14 / @Spikey84 What was the intention, to buff the TMDs?

**Comment by Tagada14** [comment]
Yes, my bad. Could you make a change and release it with the dev patch?

**Comment by Garanas** [comment]
Change from `0.25` -> `1.0`?

**Comment by Tagada14** [comment]
Yes

**Comment by MrRowey** [comment]
FYI the Doc was to make the reload time slower not faster 
![image](https://github.com/FAForever/fa/assets/20344151/715cf1f4-c9fe-4e18-bb5e-93f95ca8de1f)

**Comment by Garanas** [comment]
I'll include this with the hotfix, next weekend

**Comment by Tagada14** [comment]
> FYI the Doc was to make the reload time slower not faster. so this is opposite to what was discussed during that meeting ![image](https://user-images.githubusercontent.com/20344151/263522821-715cf1f4-c9fe-4e18-bb5e-93f95ca8de1f.png)

The idea was to decrease the reload time thus increase the rate of fire.

**Comment by Garanas** [comment]
I forgot to include this 😞

**Comment by Garanas** [comment]
Processed Cybran cruisers / carriers in #https://github.com/FAForever/fa/pull/5525
