### ISSUE TITLE
Unit restrictions not working for some maps in some cases

### ISSUE THREAD

**Issue by K-ETFreeman** [FAForever/fa#5373]
**Describe the bug**
Creating a lobby with restriction for UEF drones and hosting a game on 10 The Pass map leads to a game with not-working unit restrictions (you will still be able to create ACU drone despite it should not be possible)
I guess this working not only for uef drones, but i didnt test for other restrictions
Also i know that this bug is somehow related to the map - when i tested the same on other map, everything worked just fine
10 The Pass map is not on the vault for some reason, and the map which i tested after that (flat v2) - is in the vault
My guess is that this bug happens to any not-in-the-vault map, but i am not sure

**To Reproduce**
Host a lobby on the map [10 The Pass](https://drive.google.com/file/d/1SN82lN_YuwdZH7aaZGjphc6AV4BclHxc/view) 
Set unit restrictions for uef drones, start a game as UEF, build ACU drone

**Expected behavior**
building ACU drone is not possible due to working unit restrictions

**Comment by Garanas** [comment]
The map overwrites the restrictions on enhancements. There's nothing we can do about that. See also:

```lua
local tblArmy = ListArmies() 
for index,army in tblArmy do 
   ScenarioFramework.RestrictEnhancements({'Teleporter'})
end 
```
