### ISSUE TITLE
Shield On/Off Toggle Missing for Bubble Shield

### ISSUE THREAD

**Issue by ComradeStryker** [FAForever/fa#5376]
**Describe the bug**
The UEF ACU's Bubble Shield is missing the toggle to turn the shield on and off.
Hotkeys do not work either.

---

**To Reproduce**
Sandbox Game:

- Spawn in a UEF ACU
- Obtain Bubble Shield Upgrade
- Observe Command Queue (Notice Shield Toggle is missing.)

---

**Expected behavior**
The toggle is visible, clickable, and works as expected.

---

**Screenshots**
Bubble Shield:
![image](https://github.com/FAForever/fa/assets/121060254/ec0c16bc-b3aa-4e42-9164-4e262eca0c8c)

Personal Shield:
![image](https://github.com/FAForever/fa/assets/121060254/374934e8-c4db-4887-9fb8-3d158d1e6d20)

**Comment by Garanas** [comment]
Fixed with: https://github.com/FAForever/fa/commit/a25dad7e788f189f67c821e5f47fe51e929af6fa
