### ISSUE TITLE
Autoteam manual/off broken

### ISSUE THREAD

**Issue by MattDeering** [FAForever/fa#538]
Manual doesn't give any control to host.
Off doesn't work once going through the settings back to off with ai. Haven't tested with people

**Comment by ChrisKitching** [comment]
*Manual* auto-teams is a bit weird. The idea is that the host clicks on spots on the map to assign teams to *positions*.

It's like "Auto-teams with manually created spatial->team mappings".

The tooltips added in 0ac119a2c4dd2d314122115b904483c4ec484042 make this comprehensible, as it was possibly the least discoverable feature ever previously.
(It's also possible this was broken at some point, but testing at that commit shows it definitely works, so once that ships I'll close this)

**Comment by ChrisKitching** [comment]
Nope, this seems to be legitimately broken. More magic needed.

**Comment by MattDeering** [comment]
To think you would doubt my bug reporting is more horrible than this being broken

**Comment by ChrisKitching** [comment]
I didn't doubt your bug reporting, but we've shipped a lot of hotfixes in the last three days, and I saw it working locally earlier.

Unfortunately, it turns out that the code for receiving the messages that specify the team mappings, uh, doesn't exist.
It's not clear that this feature ever actually got finished (and what there is of it is a crime against both sanity and software engineering).

Next hotfix should do it.

**Comment by MattDeering** [comment]
Wooo

**Comment by aeoncleanse** [comment]
Did this get hotfixed?

**Comment by ChrisKitching** [comment]
Amusingly not. More pressing things caught fire.

**Comment by ChrisKitching** [comment]
Clearly, doing this in an evening is a good idea.

CHARGE

**Comment by irswat** [comment]
Can I help with this?

**Comment by duk3luk3** [comment]
Sure, just find the broken code and fix it. :-)

**Comment by quark036** [comment]
I think he meant "is @ChrisKitching still working on this"?

**Comment by Sheeo** [comment]
He's not, this is up for grabs :)

**Comment by MrRowey** [comment]
@Garanas didnt i see a mention of new team balanicng featuer being worked on ?

**Comment by Garanas** [comment]
This is no longer broken.
