### ISSUE TITLE
List of network ports is not publicly available.

### ISSUE THREAD

**Issue by neverwinter-nights** [FAForever/fa#5382]
Greetings.

_FAF_, or _"Forged Alliance Forever"_, does not have a publicly available list of network ports to open in order to host multiplayer games. 

The _"Supreme Commander"_ and _"Supreme Commander: Forged Alliance"_ games, on which _FAF_ is based, on the other hand have a list of network ports which are used in multiplayer games. These lists are available in the internet and they contain a small and fixed number of network ports.

Network monitoring software shows that ports used by _FAF_ are always random or they seem to be very random. So, the question arises.

**The Question.**
Which ports should a host forward on the network router in order to host the _FAF_ game properly ?

Answers like "all ports", "DMZ", "UPnP", "ports from 1 to 65535" and similar answers are not accepted.

Thank you.

**Comment by Garanas** [comment]
I have no idea. Maybe @Brutus5000 can help you

**Comment by Brutus5000** [comment]
The correct answer is: none. We use [Internet Connectivity Establishment rules](https://en.wikipedia.org/wiki/Interactive_Connectivity_Establishment) to open network connections through router. This technology is by other services such as WebRTC based telephony and has proven to be working there.
Also ICE uses random ports on your computer in a huge range that are currently not configurable (not sure if they are).
