### ISSUE TITLE
Menu options sometimes not avaiable

### ISSUE THREAD

**Issue by OCGDFS** [FAForever/fa#539]
The lowest options "Exit to Windows" and "Close Menu" are sometimes visible, but u cant click on it.
when: mostly after replay finished, not during the replay.

during replay:
![vlcsnap-2015-04-09-01h10m42s593](https://cloud.githubusercontent.com/assets/7430874/7057416/bb4db8ec-de55-11e4-8844-2225d952aeae.png)
at the end of the replay
![vlcsnap-2015-04-09-01h11m48s070](https://cloud.githubusercontent.com/assets/7430874/7057420/cabeba88-de55-11e4-9162-d4e93312ddd2.png)

**Comment by Sheeo** [comment]
Likely a manifestation of #536

**Comment by ChrisKitching** [comment]
Closed as duplicate of #536. It's the invisible, broken desync dialog that's stopping you from clicking.
