### ISSUE TITLE
TMD becomes unable to move its turret when a missile flies directly over it

### ISSUE THREAD

**Issue by Basilisk3** [FAForever/fa#5395]
I saw this in this replay:
#20722995 at 14:15 onwards. Watch the TMD directly under the UEF Naval-HQ.

The TMD aims at a missile that flies directly over it, which causes it to lock up, with its barrel is stuck aiming vertically into the sky. It is not functional afterwards, the player loses two extractors.

**Comment by Garanas** [comment]
Fixed with https://github.com/FAForever/fa/issues/5525  by reducing the maximum range from 90 to 80
