### ISSUE TITLE
Seraphim Sniper Switching Modes Fires Wrong Projectile

### ISSUE THREAD

**Issue by lL1l1** [FAForever/fa#5399]
**Describe the bug**
Switching modes during a reload makes the sniper fire the wrong projectile. It reloads and move likes the new mode, but still fires the old mode's projectile.

**To Reproduce**
Spawn a sniper and a nano SACU as a target.
After the sniper shoots its rapid shot, switch modes.
Notice how it shoots a rapid shot but reloads and moves slowly like with a powerful shot.
Switch modes during the long reload, and it will then fire a powerful shot but reload and move quickly.

**Expected behavior**
After shooting a rapid shot and switching modes, it should shoot a powerful shot, slow down, and reload for a long time.
After shooting a powerful shot and switching modes, it should shoot a rapid shot, speed up, and reload quickly.

**Comment by K-ETFreeman** [comment]
If you press switch modes in short-reload state, it first finishes the short reload, then shoots rapid shot, then starts to prepare for a long shot
If you press witch modes in long-reload state, it will still moves slowly, and after heavy shot, he switches to "rapid fire" state
Everything is working as intended, it finishes the current shot then switches mode
Otherwise you will be able to get free short extra dps boost by switching the mode from rapid to heavy fire, which is probably not what balance team wants, i suppose

**Comment by lL1l1** [comment]
> first finishes the short reload, then shoots rapid shot, then starts to prepare for a long shot

If it was "preparing" for a long shot, then switching modes would force the sniper to reload, regardless if it is currently reloading or not. This would mean that the correct behavior would be:
- Not in combat: Pressing switch modes forces a reload of the new mode.
- In combat: Rapid shot -> 3 second reload -> Realize you are switching modes (cannot shoot, or else you ought to reload 3 seconds) -> 15 second reload -> powerful shot
> it finishes the current shot then switches mode 

Since it fires the rapid shot and then does a 15 second reload to "prepare" without doing a 3 second reload, you are incorrect that it "finishes the current shot".
> Otherwise you will be able to get free short extra dps boost by switching the mode from rapid to heavy fire

You can still get a dps boost by starting combat in snipe mode and switching to rapid mode during the first reload:
Powerful shot -> 15 seconds reload -> powerful shot -> 3 seconds reload -> rapid shots/3 second reload
So it's clearly intended that it is a "reload" and not a "preparation". This means that the reload should be an effect of the shot fired before, which does not currently always happen because the firing mode is not updated at the proper time.
Here's a new example I found:
- Start in rapid fire mode -> shoot at target -> switch modes during reload -> move out of the rapid fire range during reload -> mode will not update despite the reload finishing
- Start in sniper mode -> shoot at target -> switch modes during reload -> move out of sniper range during reload -> sniper stays stuck in sniper mode until you click the switch modes button twice again.
