### ISSUE TITLE
Broken UI in Nomads after latest UI update

### ISSUE THREAD

**Issue by ppipp** [FAForever/fa#540]
Since last update, the Nomad in game UI is broken. Among other things :
- Option menu is not clickable anymore when you mouse over the button (which doesn't exist anymore).
- resources informations are overlapping with ping and other menus
- build menu lack options such as repeat build order, or some icons ; improper yellow lines are displayed
![broken ui](https://cloud.githubusercontent.com/assets/8941976/7075717/7f5afb2e-df04-11e4-81fc-05e0e3c44250.jpg)
![broken ui1](https://cloud.githubusercontent.com/assets/8941976/7075725/86cda852-df04-11e4-92f8-da9364522ba1.jpg)
![broken ui2](https://cloud.githubusercontent.com/assets/8941976/7075726/8a3673f2-df04-11e4-84ad-38e63fa48a24.jpg)
![broken ui 3](https://cloud.githubusercontent.com/assets/8941976/7075728/8cb2a9f2-df04-11e4-850b-87ae16e37c8e.jpg)

- when you select a unit, the informations concerning the unit have a yellow background instead of the proper window

**Comment by ChrisKitching** [comment]
Most likely it's responding badly to changes in the UI code.

The good news is the UI code got a lot nicer: take a look in lua/ui/controls for a variety of easy-to-use and well documented classes for building UIs. Takes much of the pain out of it.

Unfortunately, the Nomads code on BitBucket is sufficiently insane that I'm not prepared to spend time writing patches patches for it. If you have any questions about porting your code to work with the new UI library (which won't be changing in incompatible ways again), you can reach me via IRC.

Closed as not our bug.
