### ISSUE TITLE
Sera Snipers and Loyalist Secondary Missing Indirect-Fire Range Ring

### ISSUE THREAD

**Issue by lL1l1** [FAForever/fa#5400]
**Describe the bug**
Seraphim snipers used to have a yellow indirect-fire ring to constantly indicate their second mode's range, but now there is only the direct-fire range ring which changes range only after the sniper reloads. 
I see how it's a bit more intuitive, since it does not actually have an indirect fire weapon, but it unnecessarily makes micro more difficult since you can't always see what range you will get from the different modes, and it is not completely unexpected because the majority of units with secondary direct-fire weapons use indirect fire rings: GC tractor claws, Monkeylord Bolters, and the Othuum Thau Cannon. Loyalists are the only exception, with both of its weapons being direct-fire rings (in fact it is a little buggy: it doesn't turn to aim at the target when the longer range weapon is in range, even though it is on a turret so it would not impede movement).
Also, range preview mods still show the indirect fire ring for the sniper, and many unit mods also use indirect fire rings for secondary direct fire weapons.
I think the commonality with other secondary weapons, range preview mods, and unit mods plus the easier to visualize micro outweighs the very initial, noob-helping intuition that the sniper bot only has 1 direct fire weapon.

**Expected Behavior**
It would be best for the old static direct-fire and indirect fire range rings to return to snipers.
Alternatively it would be fine if the range ring was able to change immediately with the snipe mode, instead of waiting for the weapon to reload.
Loyalists can also be updated with the idea that the longer range secondary should have an indirect fire ring.
It would be nice for loyalists to turn their turret if the secondary is in range, but it's understandable if that's impossible because of no turret control priority to accommodate the loya's weapons' differing targeting priorities.

**Screenshots**
![image](https://github.com/FAForever/fa/assets/82986251/81cd0780-a91e-445e-92d9-1a22382ea53e)

**Comment by Garanas** [comment]
I'll try to include this with the hotfix of next Saturday 😄
