### ISSUE TITLE
Unit Manager should not show dummy Mobile Factory

### ISSUE THREAD

**Issue by HUSSAR-mtrela** [FAForever/fa#5404]
@ComradeStryker found that the new Mobile Factory is considered a Dummy unit
https://github.com/FAForever/fa/pull/5264#issuecomment-1705752179

@Garanas said that it should excluded in the Unit Manager

![image](https://github.com/FAForever/fa/assets/11665978/77d3a944-4058-4491-a590-96726c498458)

**Comment by Garanas** [comment]
Fixed with https://github.com/FAForever/fa/commit/7f101c3a5b5c2f6164fd84e4bf80db796a8271b2
