### ISSUE TITLE
Feature request: A dark skin for the Cybran UI as an official option

### ISSUE THREAD

**Issue by Basilisk3** [FAForever/fa#5411]
There currently exists a UI-mod (Dark Cybran Skin from 4z0t) that switches all the bright red UI-elements of Cybran to black ones.  Unfortunately, I can't get it to work, but I think it might be a useful feature to have in game.

**Comment by Garanas** [comment]
This is best achieved by a mod. @4z0t can you look into your Cybran dark skin mod, see what is going on?

**Comment by 4z0t** [comment]
Works for me.
