### ISSUE TITLE
Balance idea: Telemazor

### ISSUE THREAD

**Issue by Blodir** [FAForever/fa#5420]
## Intended changes

Teleport (all)
Max range: 350
Increase teleport fx radius by 25%

_This is a balance idea from the balance team. It is not set in stone, it may be adjusted or rejected as the changes are tested._

**Comment by Garanas** [comment]
And what about the LOD of the effects? Increasing that makes it visible sooner when zoomed out

**Comment by Blodir** [comment]
Keep the LOD levels as they are for now, as there's no agreement about raising them.
