### ISSUE TITLE
Tooltip is clipped in Unit Manager

### ISSUE THREAD

**Issue by HUSSAR-mtrela** [FAForever/fa#5424]
Tooltip is clipped in Unit Manager when hovering over an unit with long description

Open Unit Manager (Restrictions) in lobby options
Hover over an unit with long description, e.g. SML
Observer with of tooltip

![image](https://github.com/FAForever/fa/assets/11665978/2df826f6-3557-4d8f-b99c-f51a63eb6c2f)

**Comment by lL1l1** [comment]
This happens at UI scales more than 100%. The picture is from 150% UI scale. There are many UI scaling issues in the `UnitTooltip` script, this text is just one of them.
