### ISSUE TITLE
Automatic translation of chat messages

### ISSUE THREAD

**Issue by Nexolight** [FAForever/fa#5429]
**Describe the feature**

An option to automatically translate the chat in game as well as the lobby. Primarily thinking about russian & english. 

**Expected behavior**

An option is added to insert a translated second message into the chat during the game and in the lobby when a foreign language is detected. The target language can be selected in the options. 

This is done by either interferring with an existing project such as suggested below or loading an ML translation model directly. The message either appears as from the same user who wrote the original message or as a system message. 

**Additional context**

I've been using an OCR tool and DeepL so far. This however could be implemented in the code directly without the need for OCR and any online translation service by using an existing ML translation model that is cheap in performance. One such project that works offline, can be used from command line and provides translation models is: 

https://github.com/argosopentech/argos-translate

**Comment by Garanas** [comment]
The game is unable to load in a machine learning model. Instead, I'd highly encourage a chat wheel like in Dota 2 where you select one of a set of predefined options with predefined translations

**Comment by Nexolight** [comment]
there's no way to interfere with a python module? The game itself doesn't need to load the model itself.

**Comment by Garanas** [comment]
No, there's no way we can do that.
