### ISSUE TITLE
Lobby chat doesnt allow russian

### ISSUE THREAD

**Issue by Exotic-Retard** [FAForever/fa#543]
you cant type Russian into lobby chat for some reason. however, you can paste in Russian and it appears fine.

i think in game this problem does not exist

**Comment by Sheeo** [comment]
Indeed the ingame chat supports UTF-8.

This was regressed with the ingame lobby in patch 3640.

**Comment by ChrisKitching** [comment]
Further testing suggests this varies randomly between machines.

This *might* be a font problem. Ensure the font you have installed called Arial contains the glyphs you need (it seems unlikely that Arial on a Russian computer would be lacking Russian glyphs, however).

Strange.

**Comment by aeoncleanse** [comment]
Fixed in 3686
