### ISSUE TITLE
Lobby chat doesnt allow selection

### ISSUE THREAD

**Issue by Exotic-Retard** [FAForever/fa#545]
Please allow selecting text from the game lobby chat.

not sure if this applies to in game chat as well

**Comment by Sheeo** [comment]
I believe the OP wants copy-paste support along with this

**Comment by ChrisKitching** [comment]
This is, in theory, not quite impossible.

**Comment by Crotalus** [comment]
Send string via "GPGNet" to FAF Lobby which manipulates windows clipboard? :)

**Comment by Sheeo** [comment]
It's bat-shit-crazy, but I like it.

**Comment by ChrisKitching** [comment]
That's not the insane part.

You see, gpg doesn't provide a multi line text control, nor does it seem to provide a selectable single line control.

As a result, we have to arrange a set of single line text controls to form a multiline control. Each row needs to have multiple textboxes, one coloured to indicate selection, and to move text between the boxes in response to mouse events to show selection.

It isn't *technically* impossible, but we're not doing it soon. :P

**Comment by MrRowey** [comment]
@4z0t nice one for you if you could figure it out ;)

**Comment by 4z0t** [comment]
I can make a huge crutch that uses edit to display text, but I will try it anyway xd

**Comment by Garanas** [comment]
I'd rather you spent your time on something else, but it is your time 😃 .

**Comment by 4z0t** [comment]
Studying for example 😌
