### ISSUE TITLE
Allow mass extractor build previews to snap to occupied mass points

### ISSUE THREAD

**Issue by Sir-Prize** [FAForever/fa#546]
Shamelessly stealing tatsu's ideas here: http://forums.faforever.com/forums/viewtopic.php?f=2&t=9541#p95449

The main one that would be awesome is to enable the snapping to mass point of a mass extractor build preview for occupied mass points - no more botched storage placement!

Some of those other features look interesting, particularly point 1 about only moving the camera to the control group when you double tap the number, not changing the zoom.

**Comment by Sir-Prize** [comment]
Bump :)

**Comment by aeoncleanse** [comment]
Zock would like this to be in balance patch 1, assuming it's possible, so can we bump this up the priority list. @Crotalus, any idea if this can be done, or where I should be looking?

**Comment by ChrisKitching** [comment]
Since the mouse interactions with build templates are (I think) implemented in native code, this may not actually be possible.

**Comment by Crotalus** [comment]
If we could get the current cursor position and then check this vs the location of mexes we probably could do some ugly hack to realign the build template to make sure it's centered on the mex.

SetActiveBuildTemplate() takes arguments of buildings to build and the coordinate of the actual buildings so offsetting the coordinates there could work.

**Comment by quark036** [comment]
This and #731 are the duplicates
