### ISSUE TITLE
Seraphim air factories are harder to place than other air factories when terrain deformations are present

### ISSUE THREAD

**Issue by Basilisk3** [FAForever/fa#5460]
Seraphim air factories are considerably more picky when it comes to finding a valid place to build them. I only noticed this recently, perhaps this bug was introduced by the changes to terrain deformation through buildings.

**To Reproduce**
1. Go to the southern air slot on Seton's Clutch
2. Locate the topmost mex of the 4 core mexes (the one where the first air factory is usually built)
3. Drag build 3 air factories adjacently to the topmost mex (drag the buildings upwards)

You will see that all factions can build three air factories, except for the Seraphim, which can only build two.

**Expected behavior**
Seraphim air factories should behave like any other air factory.

**Comment by Garanas** [comment]
I'm not sure if this is correct, can you take a screenshot of where it happens?

![image](https://github.com/FAForever/fa/assets/15778155/f4cc44bc-af49-45dc-92e8-6f584375e42a)

**Comment by Basilisk3** [comment]
I think you built Aeon factories, it works with those. However, building the same structure as shown in your screenshot with Seraphim factories is impossible. You can build the topmost factory as Aeon, but not as Seraphim.

**Comment by Garanas** [comment]
![image](https://github.com/FAForever/fa/assets/15778155/447ffaf7-134c-40e8-abd9-3a59f593d506)

**Comment by Garanas** [comment]
note that there is a difference between the Seraphim air factory and other structures: because it is floating, it doesn't flatten the ground

**Comment by Basilisk3** [comment]
This is very odd. Did you make sure the bottom factory is adjacent to the mass extractor? Which version of the map are you using? The grid shown in your screenshot is impossible on my end.

**Comment by Garanas** [comment]
Could you please take a screenshot of what you're trying to do? It would reduce the amount of guessing by a lot 😃 

This is on the FAF version of the map; the factory is adjacent

**Comment by Basilisk3** [comment]
Your screenshot already shows what I meant perfectly 😃. The reason to why you cannot reproduce the problem, is because you used the FAF-version of the map. Try it on the original version and you will see what I mean. You cannot build the topmost factory in the pattern displayed in your screenshot there as Seraphim, but you are able to build 3 UEF factories.

**Comment by Garanas** [comment]
![image](https://github.com/FAForever/fa/assets/15778155/ea69aa77-da98-4997-8ebb-386106e46dd6)

Mmhh, I see now. It is odd, the max ground variation is the same for both:

![image](https://github.com/FAForever/fa/assets/15778155/ea738330-77cd-421a-be5f-89b05b20f64b)

The only difference that seems related that I can find is this:

![image](https://github.com/FAForever/fa/assets/15778155/77e5ddf6-991d-470c-80a4-686fdbb42da0)

But changing that appears to have no effect. @The-Balthazar do you have a suggestion why this particular air factory can't queue 3 structures in a row at the specific location?

**Comment by Garanas** [comment]
The preview is entirely unaware of the terrain flattening, always has been

**Comment by Garanas** [comment]
It does work 'as expected' in Steam 

![image](https://github.com/FAForever/fa/assets/15778155/ace1aa39-225c-47de-87ca-c48d33a24a9b)
