### ISSUE TITLE
Game quality not truncated in lobby

### ISSUE THREAD

**Issue by msgerbs** [FAForever/fa#5462]
**Describe the bug**
The game quality label in the lobby is not being truncated anymore and shows a silly number of significant figures (like 81.52564212301%).

**To Reproduce**
Join a lobby with more than 1 player and observe the game quality label.

**Expected behavior**
It should be truncated, I think it used to be 2 decimal points.

**Additional context**
I think it was probably broken by this commit https://github.com/FAForever/fa/commit/fd3205075499e36833f185ebb114b2419cf15957 Otherwise I see nothing else that has changed with the lobby any time recently and I just noticed it in the last week or so.

**Comment by ComradeStryker** [comment]
The in-game upgrade timer was also broken as seen below: 

![image](https://github.com/FAForever/fa/assets/121060254/39c0226f-f38a-4259-b74c-5d70deab0d8b)

**Comment by Garanas** [comment]
Ah! @msgerbs you're correct, it must've been that change 😃 . I'll pick it up

**Comment by Garanas** [comment]
This is resolved 😃
