### ISSUE TITLE
Spawn markers have incorrect names

### ISSUE THREAD

**Issue by relent0r** [FAForever/fa#5476]
**Describe the bug**
I think I take responsibility for this as I was asked to validate it and didn't validate the data all the way through.

When Spawn markers are created they are using the key which comes out as Army_X and this will be attached to the name.
BUT
When GetMarkersByType is used and no cache exist then it will do this.

    for k, marker in AllMarkers do
        if marker.type == type then
            -- mod support syntax
            marker.Name = k
            marker.Size = marker.size
            marker.Resource = marker.resource
            marker.Type = marker.type
            marker.Orientation = marker.orientation
            marker.Position = marker.position
            marker.Color = marker.color
            ms[n] = marker
            n = n + 1
        end
    end

It looks like we are overwriting the marker.Name with the index key instead of keeping the original name. So the Name for Spawn markers is no longer ARMY_X but just X

**To Reproduce**
Start a map and log the Spawn markers that are generated. Then have an AI request the Spawn markers, the resulting table will have invalid names causing AI to fail the check.

**Expected behavior**
This type of query will return the correct markers.

        local tempMarkers = AIGetMarkerLocations(aiBrain, 'Spawn')
        for k, v in tempMarkers do
            if string.sub(v.Name, 1, 5) == 'ARMY_' then
                table.insert(markerList, {Position = v.Position, Name = v.Name})
            end
        end

**Comment by relent0r** [comment]
Obviously the alternative is to just remove that string check since you don't need it. I'm not sure how many other AI do a similar check. I know the default has a bunch of these sorts of string checks due to the usage of marker type 'Blank Marker'

**Comment by relent0r** [comment]
I had a look over the codebase for this to see what the ramifications of removing the string check are.

These are the locations where we are referencing start positions.
aiutilities.lua
92 - AIGetStartLocations - References the marker chain so not impacted.

106 - AIGetSortedScoutingLocations - Uses the ScenarioUtils.GetMarker function to query the ARMY_ string.

345 - AIGetMarkerLocations - Uses new method but is checking for string.

504 - AIGetMarkerLeastUnits - Uses new method but is checking for string.

613 - AIFindStartLocationNeedsEngineer - Uses new method but is checking for string.

3094 - AIFindFurthestStartLocationNeedsEngineer - Uses new method but is checking for string.

The AI brains uses the ScenarioUtils.GetMarker function for initial threat assignment and building scout locations.

All in all there is limited impact except where 3rd party AI may be also referencing the new marker utilities and doing string checks. tbc.

**Comment by Garanas** [comment]
What if we add a guard to check if the `Name` field exists of a marker, and if it does, we use that instead of the index?

**Comment by relent0r** [comment]
actually yes that would work perfectly.
