### ISSUE TITLE
attack move doesn't work with gun upgrade

### ISSUE THREAD

**Issue by shalkya** [FAForever/fa#548]
since i was ask to split the different sACU bugs : 

http://forums.faforever.com/forums/viewtopic.php?f=3&t=9765

this one is a bug for ACU and sACU.

"when you get range upgrade on commander or support ACU, and then use the attack move, it won't stop at the upgraded range to shoot. "

**Comment by Sheeo** [comment]
This should be a matter of updating GuardScanRadius along with the range enhancement.

**Comment by aeoncleanse** [comment]
Yeah, except I don't think it can be done. There's no engine command to update that parameter, and the way we did the attack move change was in blueprints.lua, changing them on load :/

**Comment by Sheeo** [comment]
It should be possible to reload the blueprint for a unit explicitly. Needs investigation.

**Comment by Crotalus** [comment]
Can't remember, what side-effects are there from having GuardScanRadius >> weapon range? They run away too far when in patrol?

Otherwise we could set the GSR to the increased range as default, they would anyway go into the default weapon range if needed?
