### ISSUE TITLE
 Aeon nano upgrade doesn't work after getting a vet.

### ISSUE THREAD

**Issue by shalkya** [FAForever/fa#549]
all is said : you lose the regen ability after a vet

logs here : http://forums.faforever.com/forums/viewtopic.php?f=3&t=9446

content.faforever.com/faf/vault/replay_vault/replay.php?id=3105472
from 2 min 20 to 3 min 10

**Comment by shalkya** [comment]
have you got any idea for this one ?

**Comment by Sheeo** [comment]
Not yet, but I think we should prioritize it for 3641
