### ISSUE TITLE
assist ground with sACU doesn't work.

### ISSUE THREAD

**Issue by shalkya** [FAForever/fa#551]
your sACU won't assist the construction when using assist ground. 

content.faforever.com/faf/vault/replay_vault/replay.php?id=3105472

from 3:40 to 4:30 min

here are the logs : http://forums.faforever.com/forums/viewtopic.php?f=3&t=9446

**Comment by Crotalus** [comment]
REBUILDER flag on SCUs seems to create this behavior. They also doesn't start a build project "in advance" if they are assisting another builder. 

Posted about this in 2013:
http://forums.faforever.com/forums/viewtopic.php?f=2&t=3124

**Comment by aeoncleanse** [comment]
@Crotalus didn't you just remove REBUILDER as part of the mex capping change? If so, did we accidentally resolve this issue?

**Comment by Crotalus** [comment]
Yeah this should be fixed by the REBUILDER removal

**Comment by Exotic-Retard** [comment]
isnt rebuilder the bit which lets them rebuild dead structures?

that sounds like a feature removal to me

**Comment by aeoncleanse** [comment]
It was rebuilt into lua.

**Comment by aeoncleanse** [comment]
Also, expanded on so all Engies basically do it now, remember? Repair a dead structure to rebuild it :)

**Comment by Exotic-Retard** [comment]
i guess its just me being retarded then, in which case awesome, do whatever xD

**Comment by aeoncleanse** [comment]
Confirmed working
