### ISSUE TITLE
UI Freeze during games on FAF Develop

### ISSUE THREAD

**Issue by relent0r** [FAForever/fa#5517]
**Describe the bug**
I have seen for the last few weeks video freezes with the current develop version of the game. I'm doing AI development work so spend time watching games at +10 speeds.
What I'm seeing is that after a certain period of play (there is no set amount of time here) when I am scrolling in or out the video will freeze jumping between 2 frames. The Sound (and I assume the sim) are still running in the background but the video dies. If I alt-tab from the game and come back in I get a black screen.

Initially I thought I could have some strange dead loop within the AI I was testing but the symptoms don't fit as in those scenarios the video doesn't freeze.

I haven't seen anyone else mention this problem so I'm unsure if it is just me, but I'd hate to see it affect users post release.

**To Reproduce**
Create sandbox games and run at +10 speed zooming in and out throughout.

**Expected behavior**
No freeze

**Screenshots**
When I tried to take a screenshot of this I got a shot of the terrain with no units / UI present. Will try grab another screenshot and update this issue. This is what I get as a screenshot when it happens.

![image](https://github.com/FAForever/fa/assets/34614077/33c5c96c-cac6-44e8-aeed-a90037b34003)

**Additional context**
There is no indication in the logs that anything is wrong when this happens, the game seems to continue running happily in the background.
Video card is an old 980ti
![image](https://github.com/FAForever/fa/assets/34614077/68187b51-144c-4108-86d8-a9a1595f6b7d)

**Comment by Garanas** [comment]
This seems unrelated to the sim, but rather related to the UI and / or your graphics card

**Comment by relent0r** [comment]
I guess my concern is that I don't see it on the current release version of the game. I forgot to grab more details last night but will tonight.

**Comment by Garanas** [comment]
Looking at your screenshot; this appears to be a shared issue. Is there nothing in the logs about a missing technique?

**Comment by relent0r** [comment]
I'll double check tonight as I was looking at the end of the logs for an error rather than something earlier on. I'll just add the log to the issue.

**Comment by relent0r** [comment]
These are the only warnings that showed up in the logs that I wouldn't consider normal. Though I couldn't correlate them to the problem.

warning: attempt to retrieve annotation from unknown technique AeonNavy
warning: c:\work\rts\main\code\src\libs\gpggal\EffectD3D9.cpp(89) invalid effect technique requested: AeonNavy

warning: Error running lua script: g:\code\relent0r\fa\lua\defaultcomponents.lua(506): Game object has been destroyed
         stack traceback:
         	[C]: in function `CreateSplatOnBone'
         	g:\code\relent0r\fa\lua\defaultcomponents.lua(506): in function <g:\code\relent0r\fa\lua\defaultcomponents.lua:483>

**Comment by relent0r** [comment]
Confirmed that the first warning does show up on freeze.

warning: attempt to retrieve annotation from unknown technique AeonNavy
warning: attempt to retrieve annotation from unknown technique CybranNavy
warning: attempt to retrieve annotation from unknown technique UEFNavy
warning: c:\work\rts\main\code\src\libs\gpggal\EffectD3D9.cpp(89) invalid effect technique requested: CybranNavy

**Comment by Garanas** [comment]
That means your cache did not reset

**Comment by relent0r** [comment]
Ah ok, yea thats something I don't do very often. Is there a rule to how often or when you should use the faf client to start develop games since I usually just run off the repo.

**Comment by Garanas** [comment]
Your dev init file should clean the repo for you, but maybe that is commented out. Next time we have a voice call make sure that we check that; then you no longer run into shader issues

**Comment by relent0r** [comment]
Closing at this looks related to the cache not being cleared.
