### ISSUE TITLE
sACU hitboxes

### ISSUE THREAD

**Issue by shalkya** [FAForever/fa#552]
When you move sACU from side to side, GC and ML (and other beam weapon i assume) won't target them well.

content.faforever.com/faf/vault/replay_vault/replay.php?id=3105472
from 4:50 to 6 min

here are the logs : http://forums.faforever.com/forums/viewtopic.php?f=3&t=9446

**Comment by Sheeo** [comment]
Debugging the sACU hitboxes show that they are highly inaligned with the targetbones. Needs fixing for 3641.

**Comment by aeoncleanse** [comment]
This is fixed in hitbox fixes, and has been fixed for quite some time now guys!!! When are we gonna ship that lot? Yes, there are balance concerns, but the sheer frequency these complaints pop up makes me kinda mad :D

**Comment by Sheeo** [comment]
If you would cherry pick just the hitboxes for scu's, as these are the most broken, that would be great.

**Comment by Crotalus** [comment]
891a2cf8236e653a4e085b823565303374f23610
