### ISSUE TITLE
sACU assist building rebuild bug

### ISSUE THREAD

**Issue by shalkya** [FAForever/fa#553]
sACU put on assist on a building, will rebuild it after the building died. Even if :
- It's other faction tech (aeon sACU can rebuild a uef quantum gateway, for exemple)
- You can't build that unit straight, like HQ or ED5. Which means you will be able to get ED5 in cost of its upgrade which is like 1/4 of real price of shield with reclaiming wreck first by SCU. But it will rebuild on the wrecks for the T3 land facto HQ for exemple.

content.faforever.com/faf/vault/replay_vault/replay.php?id=3106329

here are the logs : http://forums.faforever.com/forums/viewtopic.php?f=3&t=9446

**Comment by Sheeo** [comment]
Originates from #522

**Comment by Crotalus** [comment]
Have no way of controlling the default REBUILDER behavior, it's an engine function. Best solution would probably be to implement the rebuild-mechanics in lua and remove REBUILDER flag from SCUs so they at least get the normal engineer assist behavior.

**Comment by quark036** [comment]
What rebuild mechanics do we need to implement?

**Comment by quark036** [comment]
Am I correct in thinking it's just rebuilding whatever they are assisting if it dies?

**Comment by bamboofats** [comment]
May I add that, If the SACU happens to assist and upgraded stage 2 or 3 hive. When the hive is destroyed, the sACU rebuilds it, to produce this glitched looking structure.
![wierd](https://cloud.githubusercontent.com/assets/13047748/8400466/82b90716-1e51-11e5-95d2-c5829eed97b1.jpg)

**Comment by ChrisKitching** [comment]
> It's other faction tech (aeon sACU can rebuild a uef quantum gateway, for exemple)

This no longer occurs as of e6c744749d7b77292a23076926d93001eb207ad7. SCUs will only rebuild things that they could be ordered to build anyway.

**Comment by ChrisKitching** [comment]
> You can't build that unit straight, like HQ or ED5. Which means you will be able to get ED5 in cost of its upgrade which is like 1/4 of real price of shield with reclaiming wreck first by SCU. But it will rebuild on the wrecks for the T3 land facto HQ for exemple.

I am not yet certain (but will verify), but the build cost defined in the blueprint for these upgraded units should reflect the total cost, so this should also no longer be happening.
