### ISSUE TITLE
DirectionTo issue where position is not returned, how to handle.

### ISSUE THREAD

**Issue by relent0r** [FAForever/fa#5532]
## Describe the query

There are some state machines that use the following function call.

local waypoint, length = NavUtils.DirectionTo('Land', origin, destination, 60)

I've been troubleshooting some scenarios in the state machines where we were getting into dead loops in state switching.

The navigation state has this logic.

                -- generate a direction
                local waypoint, length = NavUtils.DirectionTo('Land', origin, destination, 60)

                -- something odd happened: no direction found
                if not waypoint then
                    self:LogWarning(string.format('no path found'))
                    self:ChangeState(self.Searching)
                    return
                end
                
The loop is when a waypoint is not returned from this function, the machine goes back into searching, picks up the same destination then switches to navigating. Repeat forever.

I'm looking for suggestions on how to approach this scenario. Obviously I can put a wait in when the waypoint is not returned though I feel there are other methods of handling this either from within the DirectionTo function or within the logic. 
I've tried various distances and while it can help in some scenarios it seems to cause problems in others.

**Comment by Garanas** [comment]
This is likely one of the issues

![image](https://github.com/FAForever/fa/assets/15778155/067b9975-12d0-45f1-aab2-953036849391)

**Comment by Garanas** [comment]
These edge cases should be fixed with the new coarse implementation of #5579
