### ISSUE TITLE
fire-state ui is bugged

### ISSUE THREAD

**Issue by anihilnine** [FAForever/fa#556]
I refer the the ui where you can swap between hold fire / ground fire / return fire.

It is still usable but
a) it looks wrong
b) there are warnings in the log file

its to do with checkboxes

WARNING: stack traceback:
WARNING:         ...ramdata\faforever\gamedata\lua.nx2\lua\ui\uiutil.lua(349): in function `UIFile'
WARNING:         ...ged alliance\gamedata\lua.scd\lua\ui\game\orders.lua(431): in function <...ged alliance\gamedata\lua.scd\lua\ui\game\orders.lua:424>
WARNING:         ...ged alliance\gamedata\lua.scd\lua\ui\game\orders.lua(470): in function <...ged alliance\gamedata\lua.scd\lua\ui\game\orders.lua:467>
WARNING:         ...ged alliance\gamedata\lua.scd\lua\ui\game\orders.lua(537): in function `OnClick'
WARNING:         ...alliance\gamedata\mohodata.scd\lua\maui\checkbox.lua(96): in function `HandleEvent'
WARNING:         ...ged alliance\gamedata\lua.scd\lua\ui\game\orders.lua(860): in function <...ged alliance\gamedata\lua.scd\lua\ui\game\orders.lua:841>
WARNING: Warning: Unable to find file: /textures/ui/cybran/game/ability_brd/chat_brd_ll.dds

**Comment by ChrisKitching** [comment]
Fixed in 755223c5acbd3243a85b8dddf08da4e559b90a3c
