### ISSUE TITLE
Skipping firing cycle by manually re-ordering attacks

### ISSUE THREAD

**Issue by lL1l1** [FAForever/fa#5576]
**Describe the bug**
It seems like RackSalvoReloadTime can be skipped if the unit has a faster fire rate by issuing a stop command or a new attack command.

**To Reproduce**
Spawn two lightning tanks or Cougars or Bouncers and a target (Czar). Micro one of them by issuing a stop command when they finish firing, and it should start firing basically immediately in comparison to the other one.

**Expected behavior**
Lightning tank has a RackSalvoReloadTime of 5 seconds, so it should only be able to fire every 5 seconds.
Cougar has a 12 muzzle salvo, fires one at a time every 0.1 seconds, a 1 second chargeup, and a 4.5 second reload so it should only be able to fire every 6.7 seconds.

**Additional context**
- Lightning tank can be fixed trivially by using the RateOfFire instead of RackSalvoReloadTime
- Bouncer requires its fire rate for its firing cycle
- Cougar waits double its RateOfFire if you use it instead of RackSalvoReloadTime, and I think it needs the rack firing sequence instead of fire rate for its animations.
- There may be other units I haven't noticed that could abuse this.

**Comment by Garanas** [comment]
There are a lot of subtle bugs with weapons. It's essentially a state machine but the engine is unaware of that concept

**Comment by lL1l1** [comment]
I looked through the defaultweapons.lua and did some limited experimentation to make this chart, is it generally correct? My experiments are just testing normal weapons and logging the game tick when state functions are called and when projectiles are created.

![FAF Weapon State Machine (3)](https://github.com/FAForever/fa/assets/82986251/7ed29353-9982-4108-994c-f67afd53b12c)

An example of using this to analyze the Cougar (1 fire rate, 1 rack charge, 12 x 0.1 salvo delay, 4.5 rack reload).
Normal behavior: Charge 10 ticks -> FireReady state idling 1 tick -> OnFire (engine calls OnFire before the state is changed, so the ready state idles 1 tick after changing) -> firing state 12 ticks -> reload 45 ticks -> we have a target, but _bug: CanFire is always false within the reload state_, so we go to the idle state -> **Idle state OnFire** 1 tick -> charge 10 ticks (thankfully, this charge time is longer than the fire rate) -> repeat
Skipping bug: _Caused by changing states interrupting any previous waits._ Reloading -> OnLostTarget -> Packing -> 5 ticks engine acquiring new target then OnGotTarget -> Unpack, but we have no animation so we dont wait -> charge 10 ticks -> FireReady -> OnFire 1 tick -> Firing 12 ticks -> Reload -> repeat
Why Fire Rate fix doesn't work: If we look in the normal behavior, we see that we "use up" our fire cooldown in the idle state's onfire, wait 10 ticks charging, then attempt to fire in the FireReady OnFire. This means for a reloading weapon the cycle is this long (FRC is fire rate cooldown): `charge>= 0, reload > 0, salvo >= 0, (FRC > charge ? FRC - charge : charge + 1) + (FRC > reload + salvo ? FRC - reload - salvo : reload + salvo + 1)`
## Further Work
Let me know if I missed some edge cases or made a mistake.
As I started with the above formula, I should be able to create a reload formula for any weapon in the game, even with weird fire rate + state machine interactions.
There should be a fix for the canFire check (the variable, not the engine function) in the reload state. I don't know how it behaves since it's an engine function. Maybe check if the fire rate cooldown < salvo + reload in addition (canFire = CanFire() or X)? I think that fixes the fire rate fix for cougar.
There is a bug with spearhead's custom OnLostTarget function messing up the firing cycle, information here is useful for solving that.

**Comment by Garanas** [comment]
So interesting enough, this diagram already helped me understand a bug with the new anti-projectile setup 😃

**Comment by Sprouto** [comment]
You can see why I felt it needed to be tackled as well - so many shortcuts and bypasses really make it rather chaotic.

**Comment by Garanas** [comment]
It is definitely chaotic. I recall you removed all the `SetBusy` statements, how did that turn out in the end?

**Comment by Sprouto** [comment]
That worked out just fine - and I eliminated a lot of those empty shortcuts as well - so pretty much all weapons go down the complete firing cycle.   That really helps with sorting out a great many timing and firing issues - as we discussed previously, many weapons have some need of pre-fire and/or post-fire delays, which actually make a great deal of sense when you put them into play.  A lot of weapons have, IMHO, been coded rather haphazardly, most either being unaware of, or unsure of, how to use them to get a real grip on the firing cycle.    A lot of those shortcuts and exclusions were predicated on just that - so, when you take them away, and make the process a lot more homogenous - then you can sort out a lot of the nonsense that goes on.
