### ISSUE TITLE
Unknown sim freeze

### ISSUE THREAD

**Issue by Mrzcion** [FAForever/fa#558]
Replay ID: 3322512

**Comment by Crotalus** [comment]
The replay desyncs unfortunately so it's impossible to reproduce the sim-lock. I've manually checked the final commands of the replay, nothing unusual there which could have caused the lock.

**Comment by Sheeo** [comment]
@Mrzcion do you have a local replay that does not desync?

**Comment by Mrzcion** [comment]
sry i dont, the replay (which is this one: 3322555, afaik, and not the previusoly mentioned) desyncs for me around 20min in game...

**Comment by Sheeo** [comment]
That's sad, I tried finding other issue like this one, but there weren't any, so I'll leave this open as a long-term investigation of unknown sim freezes that we can come back to.

**Comment by Mrzcion** [comment]
maybe this one works 
![3322555-mrzcionfafreplay](https://cloud.githubusercontent.com/assets/11930278/7209964/d47308f0-e54d-11e4-8ddc-98b1c210eaad.jpg)

**Comment by KionX** [comment]
The sim version has been changed many times. This error cannot be reproduced.
