### ISSUE TITLE
Balance idea: Give all shields "discharge" abilitty

### ISSUE THREAD

**Issue by Tagada14** [FAForever/fa#5589]
## Intended changes

Give a “discharge shield” ability to all shields. This should reduce the shield hp to 0, such that it can be recharged (since recharging is faster than regen).

## Thoughts on the changes

This is a QoL change to allow players the option to micro-manage their shields to take advantage of the faster recharge rate at the expense of not having a shield during that time.

_This is a balance idea from the balance team. It is not set in stone, it may be adjusted or rejected as the changes are tested._

**Comment by Garanas** [comment]
Interesting idea.
