### ISSUE TITLE
Balance idea: Rebalance UEF Bubble shield

### ISSUE THREAD

**Issue by Tagada14** [FAForever/fa#5590]
## Intended changes

Shield hp 9k > 7k
Regen time 2:30 → 1:45
Recharge time 1:30 → 1:00
Mass cost 2300 > 2000
E cost 112.500 > 70.000
Bt cost 2100 > 1700 

## Thoughts on the changes

Currently, the bubble shield isn't used as it's too expensive and arrives too late. We hope that by shifting the upgrade to the mid-game stage it will allow UEF players to better take advantage of the upgrade with a Mongoose push or by protecting their first T3 units from OCs.

_This is a balance idea from the balance team. It is not set in stone, it may be adjusted or rejected as the changes are tested._

**Comment by apollodeathstar** [comment]
Is it possible to get this balance change reevaluated?, I feel the change failed to achieve its objectives as the bubble shield remains unpicked. #5527
