### ISSUE TITLE
Balance idea: Reduce the T3 pgen adjacency

### ISSUE THREAD

**Issue by Tagada14** [FAForever/fa#5592]
## Intended changes

Reduce T3 pgen adjacency so that it reduces ASF cost by 250 e/s (per pgen) instead of 300 e/s (4 t3 pgens around an air fac should decrease the drain while constructing an ASF from 1600 e/s to 600 e/s instead of 400 e/s)

## Thoughts on the changes

T3 pgens adjacency is extremely efficient and scaling your grid by adding extra T3 pgens and support air factories is the only viable choice. With this change, we hope to force players to make a conscious decision if they wish to quickly scale their production by increasing the assistance on their HQ or rip the long-term benefits of expanding their air grid.
This change also simply makes spamming higher amounts of ASAFs harder.

_This is a balance idea from the balance team. It is not set in stone, it may be adjusted or rejected as the changes are tested._

**Comment by MrRowey** [comment]
@Tagada14 Thier are a few issues with this one
- Changing the T3 Adj will affect all units in the factory
- change will affect all buildings that have the same size of a factory theis new adj will be applied

So this small change has quite a large impact on other sutff

**Comment by Garanas** [comment]
@MrRowey is there a pull request with the changes that we can use to test?

**Comment by MrRowey** [comment]
Didn't make the changes was a discussion about it in game Dev of topic

**Comment by Tagada14** [comment]
We are aware of the first point, that's intended and ASAF were just used as an example since they are the biggest offender.
I was aware of the 2nd point but I'm not sure if the rest of the balance team were. The units that would be effected would be T3/T4 arties with the same size, correct? I don't think there are any other buildings of this size that use adjacency

**Comment by MrRowey** [comment]
> We are aware of the first point, that's intended and ASAF were just used as an example since they are the biggest offender. I was aware of the 2nd point but I'm not sure if the rest of the balance team were. The units that would be effected would be T3/T4 arties with the same size, correct? I don't think there are any other buildings of this size that use adjacency

Yes So the SIZE16 is T3/T4 Arty and All land/Air Factoryies
