### ISSUE TITLE
There is no hotkey label for the AttackMove order

### ISSUE THREAD

**Issue by Basilisk3** [FAForever/fa#5597]
There is no hotkey label for Attack move, even though it should be RMB.

Related PR from 2017: #1859

Here, immutableOrderKeys wants to apply a fix hotkey label for the AttackMove order on the bottom left of the ui. For example, the label for patrol changes as you change your hotkey for it. But since Attack move is always Alt+RMB immutableOrderKeys tries to label it as "RMB" permanently.

**Comment by Garanas** [comment]
Could you enlighten us with some more context? 😃

**Comment by Basilisk3** [comment]
@Garanas I updated my description.
