### ISSUE TITLE
Lobby team button icons

### ISSUE THREAD

**Issue by Exotic-Retard** [FAForever/fa#561]
it seems in the latest hotfix the lobby autoteam buttons for top vs bottom and odd vs even are the same - im not 100% sure but i think they should be different - i remember another icon for odd vs even. screens:
http://puu.sh/hdwNX/cc76e7e444.png
http://puu.sh/hdwTh/80598dc748.png

**Comment by Sheeo** [comment]
This is odd behavior, I can't reproduce it.

Can you attach your `game.log` file?

**Comment by ChrisKitching** [comment]
No need for logs: it's readily reproduced whenever you are using the "random" factional skin.

@aeoncleanse has been notified: we'll get this patched as soon as he finishes being buried under uni work and finds time to make the missing graphics :P

**Comment by Exotic-Retard** [comment]
it seems that the button icons are broken again. and apparently in the same way as before.
this was fixed correctly but in the latest(?) faf (and faf beta) patch it has reappeared.
http://puu.sh/k2XE2/ffcfb1012b.png
http://puu.sh/k2XDa/85bad4b794.png
i deleted old screens so here are new ones
@Sheeo

**Comment by aeoncleanse** [comment]
These icons have been a right bloody pain forever

**Comment by Exotic-Retard** [comment]
i have a possible update!
its only a bug if you have random team selected - all the factions appear fine for me

**Comment by aeoncleanse** [comment]
MY GOD HE'S RIGHT

http://bestanimations.com/Holidays/Fireworks/fireworks-animation-46.gif

**Comment by Sheeo** [comment]
@aeoncleanse @Exotic-Retard this is nothing new. Chris said it like, four posts above?

**Comment by aeoncleanse** [comment]
Yeah it was fixed for a time, then came back, then was fixed (Or at least I couldn't repro). Now it's really back.

**Comment by aeoncleanse** [comment]
@Exotic-Retard Let's get this out of the way

**Comment by aeoncleanse** [comment]
@Exotic-Retard  this is still a thing!

**Comment by aeoncleanse** [comment]
ac3625b6bf69fa4634796b5c0ffe9e542fcf6ca3
