### ISSUE TITLE
"Downgradable" template

### ISSUE THREAD

**Issue by DemoneX1704** [FAForever/fa#5612]
Who don't have a template that have a mix different Tech level? For example, you have a T2 Torpedo Defense template with a mix of T2 and T3 AA, you want to build it, but you only have T2 engies.
So, why don't make it that you can select that template with a T2 engie but the the T2 engie only will build T2 and lower Tech structures of the template? 

And, when is about upgradable structures, such like factories or mexes, the engie build a "downgraded" version of the original structure. For example, you have a T3 Mex ringed template, you select the template with your engie, but because your engie is T2 instead of build a T3 mex builds a T2 mex rindged.

**Comment by Garanas** [comment]
We do have 'upgradeable' templates, see also the [context based templates](https://wiki.faforever.com/en/Play/Game/Hotkeys/OrdersMouseContext#cycle-templates)
