### ISSUE TITLE
Minimap doesnt save settings

### ISSUE THREAD

**Issue by speed2CZ** [FAForever/fa#562]
there is a proble with in-game minimap, it doesnt save settings with enabled resources. Have to be turned on every game. This bug appeared in one of the latest patches

**Comment by Sheeo** [comment]
This will have never worked. Even in the base game, the minimap uses the nonexisting prefs key `minimap_resources` where the multifunction UI that toggles the resource rendering uses the key `minimap_resource_icons`.
