### ISSUE TITLE
3772: Engineers built from Cybran and UEF air factories do not automatically rotate towards the optimal rollout point

### ISSUE THREAD

**Issue by Basilisk3** [FAForever/fa#5625]
Instead, the engineers turn inside the factory and then move out themselves. This is significantly slower than them being turned instantly, like it is the case with Aeon engineers from Aeon air factories. This results in Aeon having better air factories than the other factions.

**Comment by Garanas** [comment]
This has always been the case 😃

**Comment by Basilisk3** [comment]
That is not ideal then, because like this some air factories are better than others for the basic task that is building engineers. I don't really see a reason why some factories shouldn't have this feature, as it gives them a disadvantage. This difference will add up over the course of the game, especially when considering that these are some of the earliest units being built and sometimes left on engineer production for 10+ minutes. This also results in some factories having fewer pathfinding problems than others, which is not ideal either. 

I think the automatic turning was a great feature added in FAF, and that all factories should have it enabled.

**Comment by Garanas** [comment]
I agree with you; just pointing out that the behavior has always been like this
