### ISSUE TITLE
Capping T3 Air Factory with T3 PGen and vice versa

### ISSUE THREAD

**Issue by FredrikBergelin** [FAForever/fa#5657]
Capping to grow your air grid with what you need. Example: Have a lot of power, cap a pgen at the edge - need more power, cap a factory. Your grid grows, no need for templates or manually getting it right.

Right-click to cap might interfere with assisting the factory, but using a hotkey to cap should solve that.

Even if it isn't desired for the vanilla experience, it would be nice to have it unlocked for mods. Because, correct me if I'm wrong, this can not be done by mods, right?

I'll gladly do it myself, just say the word.

// FreadyFish

**Comment by Garanas** [comment]
This is already implemented using [context based templates](https://wiki.faforever.com/Play/Game/Hotkeys/OrdersMouseContext#cycle-templates). As an example:

https://github.com/FAForever/fa/assets/15778155/1b0c753c-5817-426a-9eab-91969674cbd8

**Comment by FredrikBergelin** [comment]
Kind of same for sure but with the limitation that it doesn't allow for prioritizing one over the other depending on current eco, and it also needs that manual alignment with current grid.

**Comment by Garanas** [comment]
You can create your own templates through UI mods. The alignment problem still exists of course, we hope to tackle that in the future.

**Comment by FredrikBergelin** [comment]
Ok that's true, but more clicks and kind of defeats the purpose of being fast. But works i guess. I'd still do it if you change your mind 👍🏻
