### ISSUE TITLE
Pulse 100% vision at the start of ladder matches or otherwise show civilians

### ISSUE THREAD

**Issue by Sir-Prize** [FAForever/fa#567]
As per the title, people lose games on ladder (and probably on team games too) partly due to not knowing where the civilians are. it's incredibly frustrating for new players to find out that, no, you can't just go through the middle of Syrtis Major, or due south on Balvery Mountains, or pretty much anywhere on Sleipnir with an early engineer or important group of units. What options are there to do this and how easy is it?

**Comment by Sheeo** [comment]
I think this is within the realm of the next balance patch -- from memory there is a thread on the forums about this, I remember ZLO pointing out that it allows you to target bombers without scouting, which you couldn't previously.

**Comment by Sir-Prize** [comment]
I don't understand how you could target bombers with this - the intel flash would occur before ACUs had even spawned surely?

**Comment by Sheeo** [comment]
Yes the point being that you now have a blip on your map of civilian structures, which you can use for targeting -- without the flash that won't happen.

**Comment by Sir-Prize** [comment]
Oh as in you no longer have to scout civs to clear them? That's kind of the point I guess - you just talked about bombers as in a way to clear civs right?

**Comment by aeoncleanse** [comment]
So this works... Is it able to go into 3641, or is this one a real debate topic?

**Comment by Sir-Prize** [comment]
I don't think it has a balance implication... But I would say that. Maybe raise it in the research thread? Apologies if I'm behind the times, busy irl and not checking faf stuff.

**Comment by speed2CZ** [comment]
Done in 3652 https://github.com/FAForever/fa/pull/929
