### ISSUE TITLE
notha bomb splash damage not working properly

### ISSUE THREAD

**Issue by phongu** [FAForever/fa#5685]
https://replay.faforever.com/21236797 @ 8:40, SPCR (tan player) attempts to bomb orange t2 power with a ground-fire order. the bomb dropped by the 2nd Notha does no splash damage after apparently hitting an engineer directly instead of the ground.

**Comment by Garanas** [comment]
It hit the ground just fine:

https://github.com/FAForever/fa/assets/15778155/075b9582-891d-4ff0-b171-04c25cc03e92

There's no bug as far as I can see. The bomber was aimed right in between the two power generators and given that Cybran power generators have a smaller hit box than other factions it simply didn't connect.

![image](https://github.com/FAForever/fa/assets/15778155/f6edf6d1-451c-41a1-9dfc-d7d080c99ca4)

![image](https://github.com/FAForever/fa/assets/15778155/2f9bdc94-78f2-4d00-9eee-869174705f28)

No bug; everything is working as intended. Just a skill issue 😃

**Comment by MLGTASTICa** [comment]
Should fix the cybran power gen hitbox?

**Comment by Garanas** [comment]
What's wrong with it?

**Comment by phongu** [comment]
the first bomb did splash damage, the 2nd did not. are we sure it's working as intended?

**Comment by Garanas** [comment]
They both did splash damage. The first bomb simply was closer to the power generator to the top left, see also:

![image](https://github.com/FAForever/fa/assets/15778155/e5b27be1-1e02-421a-ae11-aef7fefed3bb)

And that allowed it to connect and deal damage to the power generator (one of the two)

**Comment by MLGTASTICa** [comment]
> What's wrong with it?

its extremly small compared to the model

**Comment by Garanas** [comment]
That depends on the perspective, see also:

![image](https://github.com/FAForever/fa/assets/15778155/86f87757-06ca-4225-8dfb-d522eabbfdb2)

Note that this unit is a triangle while the game only supports bounding boxes and bounding spheres. There's no good answer, haha
