### ISSUE TITLE
Cybran interceptors miss the Aeon Tech 1 transport

### ISSUE THREAD

**Issue by Basilisk3** [FAForever/fa#5697]
An Aeon Transport flies through a cloud of interceptors but manages to land, because the interceptors miss almost all of their shots. Even after the transport dropped its units, the interceptors keep missing it, because they shoot in front of it, instead of aiming their shots directly at the transport. I saw this in a recent game, it happened in the current patch.

Replay ID: 21258525
Timestamp: 12:00, watch the green transport on the top of the map

**Comment by Basilisk3** [comment]
@Garanas Is this another hitbox issue? This seems to be similar to the bug that causes lasers to overshoot their target.

**Comment by Garanas** [comment]
The transport doesn't have target bones. Therefore they aim at the center. But the collision box has an offset. The location where they aim doesn't take that into account however. As a result they appear to miss quite often when the transport zig-zags a bit

We can fix it by increasing the size of the hitbox

**Comment by Garanas** [comment]
Ah, yes - it is CTRL + SHIFT + ALT + C. It requires cheats to be enabled

**Comment by Basilisk3** [comment]
Thanks, if I find more of these cases, I will proceed similarly👍
