### ISSUE TITLE
aeon engineer preset SACU inactive using assist-ground

### ISSUE THREAD

**Issue by jnorthrup** [FAForever/fa#574]
When you specify assist-ground with at least one canned SACU variant, the engineer pack, the SACU goes idle

example replay aeon player zentrodi using ground assist a few times with SACU.  mode of SACU selection is the idle-engineer button to provide order context. #3355493

**Comment by jnorthrup** [comment]
example replay aeon player zentrodi using ground assist a few times with SACU.  mode of SACU selection is the idle-engineer button to provide order context.

**Comment by shalkya** [comment]
bug already described here  #553

**Comment by shalkya** [comment]
bug already described here : #551
