### ISSUE TITLE
Balance idea: what if more units can move backwards?

### ISSUE THREAD

**Issue by Garanas** [FAForever/fa#5754]
This issue is related to https://github.com/FAForever/fa/pull/5745.

This issue is more of a discussion.

At the moment very few units can move backwards, even though the engine supports this. Giving units the ability to move backwards in general can help improve the average pathfinding experience for people. As a few quick examples:

- More responsiveness: units that are ordered to move back a tiny bit would otherwise pivot around first, which can take many times longer to complete than the actual distance it moves.

- More control: it makes it easier to kite units to some degree. You can move forward, start the engagement and then move backwards as hostile units starts to approach you.

- More consistency: at the moment some units can, while others can not move backwards. We should at least communicate (using the unit property tooltip?) when a unit is able to move backwards.

**Comment by Garanas** [comment]
@Basilisk3 / @Tagada14 I'd love to hear what you think about this. There's a few properties that we can use to approach this:

- `Backup distance`

Used to determine when the engine should try to move backwards. If the move order is within the backup distance it will consider moving backwards a possibility.

- `MaxSpeedReverse` 

Used to determine the maximum velocity that a unit can move backwards. We can use this to make kiting more difficult.

As a quick and dirty example:

- Hover units can move backwards and perceive almost no penalty (`MaxSpeedReverse = 0.95 * MaxSpeed`)
- Land units with tracks can move backwards and perceive a small penalty (`MaxSpeedReverse = 0.85 * MaxSpeed`)
- Land units with bipeds can move backwards and receive a significant penalty (`MaxSpeedReverse = 0.5 * MaxSpeed`

And for the backup distance:

- Tech 1 units have a backup distance of 6
- Tech 2 units have a backup distance of 8
- Tech 3 units have a backup distance of 10
- Tech 4 units have a backup distance of 16

Or perhaps, the backup distance should be the same for the consistency of the user? What if we introduce a new overlay to show the backup distance of units?

**Comment by Basilisk3** [comment]
I will make a PR that tackles this for various units in the next couple of days. I think this is a good outline for how to proceed.

As long as the unit is small, fast and can turn its turret, adding a lot of backup distance might not be as useful as for the Othuum, for example. So giving said units a smaller increase, makes sense. Particularly, units like the Yenzyne would get a smaller backup distance.

**Comment by Garanas** [comment]
👍 , wait a day or two to allow Tagada to catch up and join in. I was thinking it would be interesting to add the property here:

![image](https://github.com/FAForever/fa/assets/15778155/cd781ace-20ec-4554-9df6-ac943bbf64a6)

You can start with that already, if you're interested!

**Comment by Garanas** [comment]
When reviewing # I noticed that the reverse speed is visible when you build a unit:

![image](https://github.com/FAForever/fa/assets/15778155/02182e61-2ac6-4a9d-80db-ea3d38280479)

So there is _some_ indication of units being able to move in reverse

**Comment by lL1l1** [comment]
> Or perhaps, the backup distance should be the same for the consistency of the user? What if we introduce a new overlay to show the backup distance of units?

The back up distance should be an automatic game behavior hidden like nav pathing. Therefore it should be mathematically optimized to get to the waypoint as fast as possible based on speeds and turn rates, with exceptions for units with equal forward/reverse speeds, limited turret arcs, and slow turning turrets relative to the body.

Based on turning 180 degrees while using forward speed to get to the waypoint (pic related):
![image](https://github.com/FAForever/fa/assets/82986251/637574e0-afaa-483d-948d-0eb3cbc7f407)
This ignores turn radius, but if it's 0 then you can just divide the distance traveled during the rotation time by the difference in reverse and forward speeds to get the back up distance `x = (180/w) * u / (v-u)`. u is the reverse speed, v is the forward speed, and w is the turn rate. Not sure how the game chooses between turn radius/turn rate.
The equation is  `x/u = 180/w + sqrt(((360*v)/(pi*w))^2 + x^2)/v` where x is the reverse distance where reverse and forward movement arrive at the same time. You can put it into wolframalpha to solve for x and get a simplified expression. Compared to turning on the spot, it gives 2-3 times higher values for back up distance, so using it does make a difference.
