### ISSUE TITLE
Balance idea: Salvation nerf compared to Mavor

### ISSUE THREAD

**Issue by lL1l1** [FAForever/fa#5781]
## Intended changes
[AdjacencyBuffs.lua](https://github.com/FAForever/fa/blob/deploy/fafdevelop/lua/sim/AdjacencyBuffs.lua)
```
T1PowerGenerator RateOfFire Size20 discount: 0.1 -> 0.053 OR 0.085
T2PowerGenerator RateOfFire Size20 discount: 0.0625 -> 0.027 OR 0.05
T3PowerGenerator RateOfFire Size20 discount: 0.005 -> 0.0029 OR 0.0045
```
## Thoughts on the changes

Salvation's rapid fire rate and consistent shield-killing spread should be more than enough for it to compete with Mavor. It doesn't need extreme DPS on top of that.
If equalizing the DPS feels like too much of a nerf, there is an alternative option based off the 2 second max fire rate from before https://github.com/FAForever/fa/commit/71d6a36ecd7579fcc5192ab9e8149f8a5fadacd8 (2016). I chose this because I heard that Salvation was weak/balanced in the past, and this is the only balance change currently in effect. The logic for the higher Salvation DPS would be that Mavor can get higher DPS by multiplying its damage through splash, while salvation doesn't multiply its damage as much. Of course Salvation doesn't suffer from terrible overkill on low HP shields.
| Unit | DPS | Reload Discount | Adjacent DPS |
| -----|------|---------------|-- |
| Mavor | 2000 | 40% | 3333|
|Salvation|2555|42%|4400 (+32%)|
|New Salvation|2555|22.36%|3300 (-1%)|
|2016 Salvation|2555|35.8%|3960 (+19%)|

*Fire rate tick rounding is taken into account.*
The adjacency bonuses are also disproportionately changed so that the t1 pgens cut off 0.1 seconds from the reload time.
|Unit | Reload| T1 Reload | T2+T1 Reload | T3 Reload | T3+T1 Reload|
|--|--|--|--|--|--|
|Salvation |         3.1 | 2.8 | 2.2 | 1.9 | 1.8 |
|New Salvation | 3.1 | 2.9 | 2.7 | 2.5 | 2.4 |
|2016 Salvation | 3.1 | 2.8 | 2.4 | 2.1 | 2   |

I was also considering reducing the turret pitch and yaw speed from 6 to 3 to be equal to Mavor because it is 10% cheaper in mass and 3x cheaper in buildtime, but I don't want to unnecessarily impact Paragon.

**Comment by Basilisk3** [comment]
A 25% nerf is too much. The Mavor has the advantage of very high alpha damage, which makes it harder to shield against. Also, if the 2016 Salvation was deemed weak, then nerfing it to be much worse than even its version from 2016, does not make sense.

**Comment by MrRowey** [comment]
I've pushed this topic to the balance team so hopefully, we will have some general idea within the next week or so on how we want to proceed :)

**Comment by MrRowey** [comment]
@lL1l1 were all for nerfing the salvation, the current 25% nerf is a bit too much would you be able to recalculate your stats for a 10% nerf

**Comment by MrRowey** [comment]
please see the linked issue above to the route the balance team would like to take

**Comment by MrRowey** [comment]
@lL1l1 I've been asked about this for the salvation MuzzleChargeDelay: 0.15 > 0.2 (revert older changes)
is this what decreases the salvation dps?

**Comment by lL1l1** [comment]
> MuzzleChargeDelay: 0.15 > 0.2 (revert older changes)
is this what decreases the salvation dps?

No, that stat only does a visual change for Salvation. The DPS was not decreased with the merged PR.
What actually buffed Salvation's DPS in the past was fixing a bug with adjacency where Salvation would reload before it charged, causing it to reload a 2nd time (0.6*2x reload time instead of 0.6x). So there is no way to get a lower DPS from older stats, you have to adjust the adjacency bonus or damage directly.
