### ISSUE TITLE
Strategic icon scale not applied to subsequent games

### ISSUE THREAD

**Issue by andreasley** [FAForever/fa#5793]
c696d43311f70140f81a5911c3cc92bc59389d0e by @Garanas added the ability to scale strategic icons – a godsend for large  displays. However, the setting is only applied for the current game; subsequent games launch with default scale (despite the setting being persisted and shown correctly in the dialog).

When launching a new game, the scale setting should be applied again.

Also: Thanks to all devs and a happy 2024!

**Comment by Garanas** [comment]
The assembly patch was done by @4z0t  😃 , is this when you play offline and start multiple (skirmish) games in a row?

**Comment by andreasley** [comment]
This happened in every single game and replay, if I remember correctly.

I worked around the issue by creating a simple mod that just called "ui_StrategicIconScale 2.0" two seconds after game launch.

If I read https://github.com/FAForever/FA-Binary-Patches/pull/45 correctly, it provides the function `ui_StrategicIconScale` but does not apply it.

**Comment by 4z0t** [comment]
It has to be executed each time you run the game.

**Comment by Garanas** [comment]
@andreasley fixed, thank you for taking the time to report it!
