### ISSUE TITLE
Unit stats (UI): unitviewDetail shows incorrect numbers for the DamageRadius stat

### ISSUE THREAD

**Issue by Basilisk3** [FAForever/fa#5825]
According to: https://github.com/FAForever/fa/blob/deploy/fafdevelop/units/UEB2204/UEB2204_unit.bp the Air Cleaner has a DamageRadius of 3.5. The unit stats in the preview before you build the unit (https://github.com/FAForever/fa/blob/deploy/fafdevelop/lua/ui/game/unitviewDetail.lua) only show 3.

**Comment by Garanas** [comment]
This is like a similar rounding error that you fixed for the build rate value.
