### ISSUE TITLE
Cheating backdoor for Coop games

### ISSUE THREAD

**Issue by speed2CZ** [FAForever/fa#5833]
This functions https://github.com/FAForever/fa/blob/deploy/fafdevelop/lua/SimCallbacks.lua#L724-L740
allows cheating when there's only a single Human player. That is a problem with coop if you're playing solo, as it bypasses `CheatsEnabled()` check.
So this way you can play with default coop settings, cheat and get your time to leaderboards, since neither the game or the server considers the game to be cheated as the cheating is disabled in the options.

Whats the reason for this function? Its marked for `Development / debug related functionality`
Whats the problem with debugging with cheats on?

**Comment by Garanas** [comment]
I forgot about that, you were right in the end @Hdt80bro  😃 . I'll include it with the hotfix

**Comment by Garanas** [comment]
Fixed with https://github.com/FAForever/fa/commit/460fcda1b485844edb37ac09b94fbcf585349773
