### ISSUE TITLE
Balance idea: No wrecks to spawn unless building completed

### ISSUE THREAD

**Issue by MrRowey** [FAForever/fa#5837]
## Intended changes

This is based on these older issues (#2375). The team discussed and would like it to be that it doesn't leave any wrecks when a building or experiment is built unless it is completed.

- This should affect just the Building and Experimentals themself.

_This is a balance idea from the balance team. It is not set in stone, it may be adjusted or rejected as the changes are tested._

**Comment by lL1l1** [comment]
What about units in factories? Should they also leave no wreck if the factory is destroyed?

**Comment by MrRowey** [comment]
This is for structures and experimental.
