### ISSUE TITLE
Balance idea: Salvation Nerf

### ISSUE THREAD

**Issue by MrRowey** [FAForever/fa#5839]
## Intended changes

_A clear concise description of the changes_

After some discussion from the team, we agree that it needs a nerf but not as drastic as what is proposed in #5781 what we are proposing instead is the following changes

Edit new Proposed changes
```
- HP > 9k
- EnegeryRequired: 15k > 25k (Wasent updated when the Ecost per shot was increased)
- MuzzleChargeDelay: 0.15 > 0.2 (revert older changes)
- MuzzleVelocity: 150 > 98 (Revert older change)
- Min Range: 175 > 150 
```

## Thoughts on the changes

_Various thoughts on the reasoning behind these changes_

_This is a balance idea from the balance team. It is not set in stone, it may be adjusted or rejected as the changes are tested._

**Comment by Basilisk3** [comment]
> After some discussion from the team, we agree that it needs a nerf but not as drastic as what is proposed in #5781

You say that this change is not supposed to be as drastic as #5781 (a 25% nerf), but the damage nerf in this proposition would already be an 18% nerf. Then add the AOE nerf on top of this (this makes it perform worse against heavily shielded units + it already suffers from very low AOE in the current balance) and account for the loss of additional DPS through adjacency. At best, you will arrive at something similar to #5781, which does not make sense as you want your nerf to be less drastic, and not about the same.

**Comment by Garanas** [comment]
If you change the footprint size then please also update the context-based templates of the Salvation.

**Comment by lL1l1** [comment]
- Reload with maximum adjacency: 1.8 -> 1.9
- Damage: 220 -> 180 * 6 * 6
- Therefore DPS: 4400 -> 3410 (-22.5%)

This is much further than the -10% nerf you requested. As for the recalculation, it's already done as the "2016 Salvation" in my previous post (4400 -> 3960 (-10.0%)).
This also nerfs Paragon Salvations by 18%, which should get some reasoning in the "thoughts on the changes".
Not sure why the footprint is reduced either.

**Comment by MrRowey** [comment]
> - Reload with maximum adjacency: 1.8 -> 1.9
> - Damage: 220 -> 180 * 6 * 6
> - Therefore DPS: 4400 -> 3410 (-22.5%)
> 
> This is much further than the -10% nerf you requested. As for the recalculation, it's already done as the "2016 Salvation" in my previous post (4400 -> 3960 (-10.0%)).
> This also nerfs Paragon Salvations by 18%, which should get some reasoning in the "thoughts on the changes".
> Not sure why the footprint is reduced either.

Hmmm okay, can you work out the 10% nerf then.

**Comment by lL1l1** [comment]
With the footprint changes, it would be 220 -> 209 damage.

**Comment by MrRowey** [comment]
> With the footprint changes, it would be 220 -> 209 damage.

Can you make the changes ? And we can get it on develop for testing
