### ISSUE TITLE
Missing Unit Restrictions

### ISSUE THREAD

**Issue by venomdragoon** [FAForever/fa#586]
Lobby Unit Restrictions are missing options for disabling all "Super game enders":
Mavor, Salvation, *Yolono*, scathis, salvation.

In particular, the only way to disable the Yolono along with the others is to either:
-disable game enders (removes normal T3 arty) 
-disable nukes (removes standard nukes)

It would be nice to be able to remove all "Super game enders", or have a separate option for the yolono.

**Comment by aeoncleanse** [comment]
Close this, it's in

**Comment by venomdragoon** [comment]
Thanks!
