### ISSUE TITLE
Trees that die to fire damage leave decals that take 25 in-game hours to disappear

### ISSUE THREAD

**Issue by Basilisk3** [FAForever/fa#5867]
Easily reproducible by spawning in a location that has trees nearby. I recommend Seton's Clutch.

**Comment by Garanas** [comment]
![image](https://github.com/FAForever/fa/assets/15778155/c9d8149d-a06a-44fd-a7de-54ec9b0eba47)

**Comment by Basilisk3** [comment]
I fixed the title 😃

That `*` probably should be a `+` then

**Comment by Garanas** [comment]
Yes, feel free to tweak the values in a pull request. Something like 2 minute should be fine. You can find the functions here:

https://github.com/FAForever/fa/blob/develop/lua/defaultexplosions.lua#L614-L645
