### ISSUE TITLE
Holding Ctrl + Alt should not show Attack Move cursor

### ISSUE THREAD

**Issue by FredrikBergelin** [FAForever/fa#5876]
Currently, holding Alt for attack move triggers when holding Ctrl+Alt as well. This is probably not useful to anyone and is a bit unexpected/annoying in my opinion.

Furthermore, some hotkeys kan not be bound with Alt modifier because it interferes with detecting hovered units. If I remember correctly this is the case for the copy orders hotkey for example. When Alt is held it doesn't detect the unit under the attack cursor and no orders are copied.

So this would at least free up Ctrl-Alt for use with those hotkeys. Ideally it should work for only Alt as well.

**Comment by Garanas** [comment]
You can tweak the behavior to _some degree_ using this game option:

![image](https://github.com/FAForever/fa/assets/15778155/ba224ecb-3142-4b50-97a2-ee6fdbe0d8fc)

That way it does not flat out override everything else. The game does bound alt to attack-move, we have no additional control over that.
