### ISSUE TITLE
Thunderhead Class: UEF Tech 1 Frigate

### ISSUE THREAD

**Issue by Garanas** [FAForever/fa#5889]
# Thunderhead Class: UEF Tech 1 Frigate

![image](https://github.com/FAForever/fa/assets/15778155/889bd85d-4930-4d87-9598-d4da19a6c8ea)

- Blueprint: `ues0103`

## Known issues

- [x] Pillow-like lighting because of poor normals (`/units/UES0103/UES0103_NormalsTS.dds` in the Steam game data folder) (fixed with https://github.com/FAForever/fa/pull/5914)
- [x] Radar rotators keep on rotating when the unit dies (fixed with https://github.com/FAForever/fa/pull/5890)

**Comment by Ajamajan** [comment]
I'm taking this one. i've already started work on the remodel in blender. not sure about the radar rotation issue though

**Comment by Garanas** [comment]
I fixed the radar rotation issue in #5890 😃

**Comment by Ajamajan** [comment]
somebody please check if i did the PR correctly. it looks a lot better but i do welcome feedback for more changes 
![Thunderhead_Finished_InGame](https://github.com/FAForever/fa/assets/34185217/d73073ae-a906-4e73-bdd3-a9d388a4abcf)

**Comment by jospoortvliet** [comment]
Really nice work, seriously. Loving it.
