### ISSUE TITLE
Gifting issues

### ISSUE THREAD

**Issue by Sheeo** [FAForever/fa#590]
A couple of reports coming in with players gifting their base just before death in share-until-death, and having the gifted units persist in the game. This presumably happens when units have been transferred more than 1 time between players.

One such replay is http://replay.faforever.com/3406184.

Was the gifting code touched in 3641 so far?

**Comment by Crotalus** [comment]
There was some changes that would return units back to the original owner if it was given away in share until death mode and the receiving player dies. I'll investigate it further
