### ISSUE TITLE
TMM Team colours should default to Hot/Cold

### ISSUE THREAD

**Issue by SteseDav** [FAForever/fa#5927]
**Describe the feature**
TMM / Auto Team colours should default to Hot or Cold colours

**Expected behavior**
Teams should default to being in 'opposing' colours, so that team identification is easier in strategic or mini map view. This would be especially helpful for casting.

**Comment by MrRowey** [comment]
This is already the case
![image](https://github.com/FAForever/fa/assets/20344151/85567240-2db3-4a56-9b20-2192ca1671dc)
