### ISSUE TITLE
It is impossible to share HARMS

### ISSUE THREAD

**Issue by Basilisk3** [FAForever/fa#5952]
They get destroyed when you receive them via full share.

**Comment by Basilisk3** [comment]
The bug appears to be caused here:

https://github.com/FAForever/fa/blob/26ad5882f07c51f194b2441e089235523b916b59/units/XRB2308/XRB2308_script.lua#L18C1-L48C1

**Comment by MrRowey** [comment]
It probs to do with the fact that there 2 units one for when it is built on the surface of the water and then when it's built and submerged a different unit.

**Comment by lL1l1** [comment]
Fixed by https://github.com/FAForever/fa/pull/6343
