### ISSUE TITLE
Aeon tmd (possibly only those from battleships) can counter nukes in some cases.

### ISSUE THREAD

**Issue by ArtemisFowl0** [FAForever/fa#5955]
**Describe the bug**
Aeon tmd (possibly only those from battleships) can counter nukes in some cases(while being shoot by tmd at the sime time).

**To Reproduce**
Make a few aeon bs, shoot at them with tactical missiles from cruiser, shoot nuke to them, enjoy.

**Expected behavior**
Tmd should not interact with nukes in any cases

**Screenshots**

**Additional context**
https://replay.faforever.com/22000127 - min 33 cheeseberry fire nuke from beach to yew bs, nice firework.

**Comment by Garanas** [comment]
This is fixed already, but not released yet 😃 !
