### ISSUE TITLE
projectile.lua error in current fafdevelop branch

### ISSUE THREAD

**Issue by relent0r** [FAForever/fa#5957]
**Describe the bug**

```
warning: Error running lua script: g:\code\fa\lua\sim\projectile.lua(200): attempt to call method `SetNewTargetGroundXYZ' (a nil value)
         stack traceback:
         	g:\code\fa\lua\sim\projectile.lua(200): in function <g:\code\fa\lua\sim\projectile.lua:155>
```

Error received in the current fafdevelop branch

Function thats happening in is OnTrackTargetGround

The the first event that it happens this is loaded just prior to the error.
debug: Loading module: /projectiles/siflaansetacticalmissile01/siflaansetacticalmissile01_script.lua

**To Reproduce**
Run a game on faf develop. AI games are fine.

**Expected behavior**
No error

**Comment by Garanas** [comment]
This means you do not have the latest exe while running the development environment 😃 !

**Comment by Garanas** [comment]
This week we'll hopefully do a release, then the exe's are in sync again 😃
