### ISSUE TITLE
Windowed mode CTD

### ISSUE THREAD

**Issue by aeoncleanse** [FAForever/fa#597]
Every time, I get this sequence:

Start game windowed. Launch. Play about a bit. Quit to main menu. Try to get back into lobby for another test after perhaps changing something in a mod and saving. CTD...

Also sometimes happens when I try to quit to main menu, just shudders then CTD.

Nothing in the logs.

**Comment by Sheeo** [comment]
Can't reproduce. If you're using `/EnableDiskWatch` and modifying the UI state, this causes undefined behavior in many cases.
