### ISSUE TITLE
ForgedAllaince.exe crashes with exit code 2

### ISSUE THREAD

**Issue by obydog002** [FAForever/fa#5975]
**Describe the bug**

Can't create a game/ladder. There is no corresponding game.log generated at all. After running faf-client and piping stderr I found

```
4-03-14T21:47:24.397+08:00  INFO 6286 --- [FAF Client] [or-http-epoll-9] c.f.c.fa.ForgedAllianceLaunchService     : Starting Forged Alliance with command: [%USER_PROFILE%/.faforever/bin/ForgedAlliance.exe, /init, init.lua, /nobugreport, /log, %USER_PROFILE%/.faforever/logs/game_22056729.log, /gpgnet, 127.0.0.1:40473, /mean, 1885.92, /deviation, 170.576, /savereplay, gpgnet://127.0.0.1:40871/22056729/obydog002.SCFAreplay, /country, AU, /numgames, 635, /numgames, 15] in directory: %USER_PROFILE%/.faforever/bin
/home/<REDACTED>/.faforever/bin/ForgedAlliance.exe: 1: MZ<90>^C^Dÿÿ¸@0^A^N^_º^N´: not found
/home/<REDACTED>/.faforever/bin/ForgedAlliance.exe: 1: Syntax error: word unexpected (expecting ")")
```

A full client.log with stderr appended is here. As an aside I had to redact my home directory.

[client.log](https://github.com/FAForever/fa/files/14603395/client.log)

**To Reproduce**

No clue why this started happening. I played some games yesterday, went to work, came back and it crashes.

Launching forged alliance from steam works, game dll paths in the client.log are correct

**Expected behavior**
Game launches

**Screenshots**

![error](https://github.com/FAForever/fa/assets/38587157/61ffec1c-9af2-442a-bc05-0bde77a8c81c)

**Additional context**
OS: Linux

_This bug report will be read by people that have not experienced the bug themselves - this report is all they have to investigate. The more precise your report, the easier it becomes for us to help you._

**Comment by obydog002** [comment]
Hex of that thing it cant find:
4d 5a 90 03 04 ff ff b8 40 30 01 0e 1f ba 0e b4

**Comment by Garanas** [comment]
It appears this is on Linux and we do not officially support Linux. A lot of other Linux users found each other on our [official Discord server](https://discord.com/channels/197033481883222026/1083855787518079066) however and they occasionally manage to get everything working.

**Comment by obydog002** [comment]
All good, I figured it out

If anyone was wondering:
I destroyed my game preferences accidentally and along with the command line format with executable settings.
This is the error if you try to run it without proton.
