### ISSUE TITLE
Dying Units cancel current command

### ISSUE THREAD

**Issue by Eximius** [FAForever/fa#598]
If you are making a command. I.e. Select Units, press A (you have the attack cursor now), if a unit dies which is in the selection, the command is cancelled.

**Comment by Sheeo** [comment]
Are you sure this is a regression?

**Comment by Eximius** [comment]
Not sure.

**Comment by Crotalus** [comment]
Seems like it's an issue since GPG-times

**Comment by aeoncleanse** [comment]
This looks to be fixed
