### ISSUE TITLE
Document Console Commands

### ISSUE THREAD

**Issue by lL1l1** [FAForever/fa#6011]
**Describe the feature**
Documentation of the console commands similar to the annotated functions in /engine/. This would help understand some code, maybe discover useful commands, and make referencing the commands easy.

**Additional context**
The best resource I could find so far was on the fandom wiki:
https://supcom.fandom.com/wiki/Console
CON_ListCommands | List all console commands and variables.

**Comment by Garanas** [comment]
They're documented here too: https://github.com/FAForever/fa/wiki/Console-commands

**Comment by Garanas** [comment]
@MrRowey closing as `not planned` is a different message over closing as `completed` - in this example, it should be `completed`
