### ISSUE TITLE
Balance idea: Stealthing unexplored buildings should remove the generic grey "building square" from the map, like it does when you lose radar.

### ISSUE THREAD

**Issue by piisawheel** [FAForever/fa#6014]
## Intended changes
Currently, if you construct some buildings on the map, they will be grey squares on the enemies radar. If you construct a stealth gen nearby, they turn a darker grey, indicating there "was" something there. However, if the opponent loses radar entirely, they completely disappear, and won't reappear until the stealth is removed, stalled, with omni, or it gets explored.
_A clear concise description of the changes_
To be consistent, the squares should be removed when stealth is in range, or all the "building" squares should just "darken" when an enemy loses radar, the way they do when you've explored the buildings, but aren't sure if they're still there.
## Thoughts on the changes
It makes it pretty obvious that you've built stealth in the area.
_Various thoughts on the reasoning of these changes_
You would need to pay proper attention to changes on the map, or not let your radar stall or be destroyed. It would put a little more importance on the value of scouting.

_This is a balance idea from the balance team. It is not set in stone, it may be adjusted or rejected as the changes are tested._

**Comment by MrRowey** [comment]
@Garanas is this even possible ?

**Comment by SteseDav** [comment]
In my head, it's a bit strange to lose radar and have all contact intel completely disappear... so in order to balance , should we not darken all contacts if radar (or LOS) is lost, no matter the reason?

a nearby stealth field would have the same effect, removing the contact from radar, but not from a record of 'there was a thing here'.

just my 2pence opinion. :)

**Comment by RegalEagIe** [comment]
> In my head, it's a bit strange to lose radar and have all contact intel completely disappear... so in order to balance , should we not darken all contacts if radar (or LOS) is lost, no matter the reason?
> 
> a nearby stealth field would have the same effect, removing the contact from radar, but not from a record of 'there was a thing here'.
> 
> just my 2pence opinion. :)

In my opinion, while your suggestion makes sense, the issue is that it would be too much of a nerf on cybran, and stealth is already an unreliable mechanic, so it's better to keep it consistent and make stealthed buildings grey out aswell.

**Comment by Garanas** [comment]
> Currently, if you construct some buildings on the map, they will be grey squares on the enemies radar. If you construct a stealth gen nearby, they turn a darker grey, indicating there "was" something there.

https://github.com/FAForever/fa/assets/15778155/160ee8fe-2622-4a4f-9d56-b5ca640dfb9d

I'm unable to reproduce the described behavior. Out of interest, can you record it for us?

> @Garanas is this even possible ?

No, intel is entirely managed by the engine and we should definitely not interfere with that from Lua 😃 . It would hurt performance too much.

**Comment by piisawheel** [comment]
Is this behavior different on replays?
When viewing a replay from a person's point of view, it exhibits this behavior.
My apologies if replays are dealt with differently.
I assumed viewing a replay from someone's point of view was a perfect replication of what they see in game.

**Comment by Garanas** [comment]
I'm not sure if the replay is different. What is different is the switching of focus armies, I can imagine the engine being unable to completely restore the state properly.
