### ISSUE TITLE
Navy units fall through seabottom

### ISSUE THREAD

**Issue by Crotalus** [FAForever/fa#603]
`release/3641`

Naval units have no collision detection (not attached to a projectile like hover / air units), so the sea-bottom collision -> create wreck code will never be run.

**Comment by ChrisKitching** [comment]
Yeah, sorry, known regression, been trying to find a better way to solve this problem.

Stuff that sinks with an animation is annoying: it sinks a fixed distance and then the animation stops. The animation will merrily proceed through the seafloor in shallow water, and won't reach the bottom in deep water.

There doesn't seem to be a nice way to get the position of the unit after the animation (is there?). An ideal solution would seem to be to run the animation, then spawn the usual projectile at the position underwater it has sunk to and use the usual sinking logic from there. We can detect at kill-time if the water is deep enough to for the animation to run without going through the floor, and if not just use the physics-based sinking code from the start.

Remember, GPG's approach didn't care about this, as they just sunk the units and then deleted them. I'd like to avoid the old "Run animation and then spawn a magically-teleporting wreck on the bottom" approach if possible, it's somewhat jarring.

Alas, I don't seem to be able to find a way (short of manually creating a mapping) of figuring out the post-animation position of the unit. Any ideas? I guess you ran into this yourself before.

**Comment by Crotalus** [comment]
I think self:GetPosition() with bone argument works to get the actual position of the animated unit so like:
```
local watchBone = self:GetBlueprint().WatchBone or 0
self:GetPosition(watchBone)
```

Another solution could be to add a CollisionDetector to the watchbone and hopefully it emits a signal when hitting terrain, CreateCollisionDetector()

```
self.Detector = CreateCollisionDetector(self)
self.Trash:Add(self.Detector)
self.Detector:WatchBone(watchBone)
```

A third option would be to attach a dummy projectile to the unit to detect terrain impact but not sure if that works in combination with the animation.

**Comment by ChrisKitching** [comment]
Ah, I knew of neither of those things, so that's probably worth a look. You can have a fiddle with it yourself if you like.

Before I came along and broke it, it would just run the animation and then spawn a wreck on the bottom, right?
If we can detect bone collision with the floor, we can run the animation even in shallow water, which is pretty neat, and in deep water supplement the animation with projectile-sinking to get it to sink all the way down and then create a wreck, probably all with improved performance because no more SeabedWatcher... hopefully :P

**Comment by aeoncleanse** [comment]
Where are we on this right now then? That PR... is that for 3641, does it work?

**Comment by Crotalus** [comment]
I suggest we go for this for 3641 and try to solve this more effective forward.  We got rid of seabed watcher for air (and hover) which is a non-negligible part of the sinking wrecks + increased wait time for sinking wrecks.

**Comment by Sheeo** [comment]
I concur--so long as it works, we can come up with something better for next patch.

**Comment by Crotalus** [comment]
3ce5b9326bb1ec95129c0b021b87cb7c67741ef9
