### ISSUE TITLE
What if certain structures were slightly easier to place?

### ISSUE THREAD

**Issue by Basilisk3** [FAForever/fa#6032]
## Intended changes

The idea is to make structures easier to place by having them accept higher variations in terrain. 

## How this can be achieved

Making units accept higher variations in terrain is trivial, and can be achieved via the `MaxGroundVariation` field under `Physics` in their blueprint. The default value is `1`.

**Units that should be evaluated:**

- All Tech 3 Power Generators (for air grids)
- Larger Game Enders like the Paragon or the Salvation, as they can be pretty difficult to place sometimes
- Shield Generators
- ...

## Testing

- `MaxGroundVariation = 1.1` is a reasonable and safe value, visually there is almost no difference.
- `MaxGroundVariation = 1.2` still reasonable, but fits some structures more than others.

## Additional context

Possible since #4584, as structures do not deform the terrain underneath them as much anymore.

**Comment by Garanas** [comment]
This is an interesting direction. Your suggested values are far from it, but we have to be careful as the terrain deformation allows one to create passages when the maximum ground variation is set too high:

![image](https://github.com/FAForever/fa/assets/15778155/b2d3848e-fa9a-488a-a94f-5414444c62bf)

**Comment by Basilisk3** [comment]
If the balance team agrees, I will go with `1.1` for Shields, Factories, and Tech 3 Power Generators, and `1.2` for Game Enders. I think changing it for smaller structures is not necessary, at least for now.

**Comment by Garanas** [comment]
This is not up to the balance team - it doesn't involve any balance. If something just works better then we should go for it
