### ISSUE TITLE
Seraphim experimental nuke is immune to its own missile

### ISSUE THREAD

**Issue by ChrisKitching** [FAForever/fa#605]
We should either fix that, or label it as having this ability.

Discuss.

**Comment by aeoncleanse** [comment]
There we go. The original three have DamageFriendly = true. The Seraphim ones introduced in FA do not. That's the cause. I suspect this is unintentional, it certainly doesn't make logical or gameplay sense to me, and my vote as I cast it is to add this to both the normal and experimental missile launchers.

**Comment by Crotalus** [comment]
Unless there is some lore-reason for seraphim nukes not damaging their own structures (nukes and acu/scu explosions) I vote to make it damage itself.

Would maybe be cool with some non-structure damaging AOE damage (like EMP) but that's different  discussion  :)

**Comment by ChrisKitching** [comment]
81ff6c5ec21ad29d91e930ba190c80df7f30264e
