### ISSUE TITLE
Game crashes, closed, device restarted, but the game menu is stuck as a print on my screen even on the BIOS start.

### ISSUE THREAD

**Issue by AlezziSpace** [FAForever/fa#6070]
After tying to create a custom game. my screen started to go slowly darker. After a minuter or two the game crsheson the "Create game" screen. Closed the game, but the same screen from the menu is no permanentley printed on my screen. Restarted the PC, the game menu was a background on the BIOS start screen, on my normal background,  can see it tansperantly on any opene app. Multiple PC restarts, shutdows, ended all applications from the task manager (that will not crash the system, updated gpu drivers. Still can see the "Custom game" menu everyhere, but its getting darker ... aaybe ina weak it will dissapear, but thats insane ... the game is closed, the device restarted, but its still there.
Running Win 10 with Nvidia 1060 6gb and i7 9'th gen cpu, device Predator Helios 300, never seen somethink like this,

**Comment by Garanas** [comment]
This sounds more like a drivers issue and not so much related to the game.
