### ISSUE TITLE
External factory can be deattached by deploying

### ISSUE THREAD

**Issue by Garanas** [FAForever/fa#6078]
**Describe the bug**

When you issue a deploy order with the Fatboy and/or the Atlantis the external factory (and any unit that is being built at that moment) is detached from the primary unit.

**To Reproduce**

Spawn in a Fatboy and/or an Atlantis, build a unit and issue the deploy order immediately after.

**Expected behavior**

For things not to detach 😞 !

**Screenshots**

![image](https://github.com/FAForever/fa/assets/15778155/c6cecbe2-a4db-4670-877d-2a251c589c8a)

**Additional context**

Initially the feature had an entity in between the primary unit and the external factory. I can not entirely recall why we removed that entity, but I'm sure that re-introducing the entity will fix the bug as the entity will not be 'deployed' like other units.

**Comment by Garanas** [comment]
@clyfordv you worked on the mobile factories, can you recall the reason we removed the entity?

**Comment by clyfordv** [comment]
Yes, it was to make it so the external factories could only be selected with the button (and not from the worldview). Just a smoke and mirrors thing, so definitely contradicted in this case.

**Comment by Garanas** [comment]
You can select those too but the selection box of the primary units are too big and therefore always overlap the selection box of the external factory.

Initially the external factory was always at the 'back' of the unit just to make it easier to select. This was traded in favor to the button you worked on and now the external factories are where the 'factory' is visually in the mesh.

**Comment by clyfordv** [comment]
It's the "CARRIER" category--adding it to the Fatboy both prevents the exFac from being selected in the worldview, and prevents it from detaching (no idea how or why).
