### ISSUE TITLE
Zthuee targeting problems

### ISSUE THREAD

**Issue by HardlySoftly** [FAForever/fa#610]
Zthuee don't fire at a target if its moving over 4 speed, e.g t1 land scouts (4.5 speed), battlecruisers (4.25 speed), as well as most other navy.

They do fire at mech marines (4 speed) but not reliably.

**Comment by Sheeo** [comment]
It still has issues shooting at close range targets, too, despite containing this [comment in the blueprint](https://github.com/FAForever/fa/blob/develop/units/XSL0103/XSL0103_unit.bp#L340): `fixes t1 artillery sometimes not shooting at target in range bug [125]`

**Comment by aeoncleanse** [comment]
Yeah this can be closed.
