### ISSUE TITLE
Gifting units cancels ongoing captures

### ISSUE THREAD

**Issue by Sheeo** [FAForever/fa#617]
When gifting a unit that is being captured, the capture is cancelled. Original report [here](http://forums.faforever.com/forums/viewtopic.php?f=3&p=100268#p100268)

**Comment by Crotalus** [comment]
The easy solution would be to prevent the ability to give units that are being captured.

Otherwise we have to re-issue capture command on all capturing units and set the progress accordingly, not sure it's even possible.

**Comment by Sheeo** [comment]
It makes sense that capturing disables gifting, and it is indeed simpler to implement -- so I'd vote for that.

**Comment by VoRGoR** [comment]
I agree with that.

**Comment by Crotalus** [comment]
Fixed in b31c8cc7bfcb7891a1dbc1da6e9f4430c6572366
