### ISSUE TITLE
Unplayable, abandoning game, unsubscribing from issue, courtesy feedback, unplayable, resolution cuts off the bottom, no where to set resolution.

### ISSUE THREAD

**Issue by Innomen** [FAForever/fa#6170]
I'm not spending an hour on this post sorry not sorry. It's 2024 this should not be an issue. How do you not have basic graphics settings anywhere?

Like 1920x1080 is an alien resolution.

![image](https://github.com/FAForever/downlords-faf-client/assets/134324/30cd623c-4644-4c62-addb-302d11907539)
![image](https://github.com/FAForever/downlords-faf-client/assets/134324/77cb97dd-ddb0-452e-804a-37909c1d7e29)

**Comment by MrRowey** [comment]
You have to set the Graphic setting to either ingame (host game on your own) or Open up the Steam version of Forged Alliance

**Comment by Innomen** [comment]
> You have to set the Graphic setting to either in game (host game on your own) or Open up the Steam version of Forged Alliance

Yes, that is how I fixed it, logged in, watched a replay, finally got access to display settings. Changed settings in the reply. Also the steam change doesn't work, it's as if it's separate games to some extent. I still say this counts as a bug. Especially if you knew the answer that fast. Clearly I'm not the only one. There should be a display settings menu inside FAF, even if it's just a text box explaining why there aren't settings in FAF.

Sorry for the rage, sorta. I'm less angry now, but I still agree with what I said, if that makes any sense.

**Comment by MrRowey** [comment]
> > You have to set the Graphic setting to either in game (host game on your own) or Open up the Steam version of Forged Alliance
> 
> Yes, that is how I fixed it, logged in, watched a replay, finally got access to display settings. Changed settings in the replay. Also the steam change doesn't work, it's as if it's separate games to some extent. I still say this counts as a bug. Especially if you knew the answer that fast. Clearly I'm not the only one. There should be a display settings menu inside FAF, even if it's just a text box explaining why there aren't settings in FAF.
> 
> Sorry for the rage, sorta. I'm less angry now, but I still agree with what I said, if that makes any sense.

For most it's not much of an issue as you require to launch the game at least once before being able to play faf via faf to generate all the files.

**Comment by Innomen** [comment]
I wonder why my edits to the steam version are not applying to FAF. Meh, whatever, it works now. Not exactly a flood of new players anyway. :)
