### ISSUE TITLE
Recall votes can't be changed between successive votes, sometimes

### ISSUE THREAD

**Issue by ChessBerry** [FAForever/fa#6172]
**Describe the bug**
In this game [#22477391](https://replay.faforever.com/22477391) our team voted for recall twice. The first time we voted against the recall 1:3, but shortly thereafter everyone of us 4 on the team voted for a recall 4:0 in the second vote, but this seemingly didn't end up changing any of the votes of players that previously voted no. There vote was seemingly stuck on "no" even if they voted "yes" afterwards.

**To Reproduce**
I don't know. Recall seems generally unstable these days, but I haven't found a pattern yet.

**Expected behavior**
Recall votes should be counted correctly.

**Screenshots**
<img width="315" alt="Screenshot_323" src="https://github.com/FAForever/fa/assets/90977374/0f65f29f-6024-4a85-a773-77a0a0127970">

<img width="335" alt="Screenshot_324" src="https://github.com/FAForever/fa/assets/90977374/e28dcb26-a3d8-454e-91c1-a63e0782f5d9">

<img width="470" alt="Screenshot_325" src="https://github.com/FAForever/fa/assets/90977374/73f6e772-bb00-4d8a-84e8-831efc2d1d39">

**Additional context**
Game and client logs:
[game_22477391.log](https://github.com/FAForever/fa/files/15284695/game_22477391.log)
[client.log](https://github.com/FAForever/fa/files/15284696/client.log)

**Comment by lL1l1** [comment]
Should be fixed among the many fixes in https://github.com/FAForever/fa/pull/6396, even though I haven't replicated this bug exactly, I did catch a lot of edge cases.

The reason for the bug might have been the number of votes to end a recall early not calculating correctly or old votes not being cleared for dead players, both reasons are fixed.
