### ISSUE TITLE
"Commander Under Attack" Audio Warning Delay is Missing on FAF Develop

### ISSUE THREAD

**Issue by ChessBerry** [FAForever/fa#6214]
**Describe the bug**
Every single instance of taking damage causes the "Commander Under Attack" audio warning message to play, without any cooldown period/delay between them. 

**To Reproduce**
Host an game on FAF Dev and have your ACU take damage. See e.g. the test game: [22567665](https://replay.faforever.com/22567665) and recording:

https://github.com/FAForever/fa/assets/90977374/7307ca37-7d2d-4f1f-8e39-3d2910870833

**Expected behavior**
The previously existing warning delay of about a second or so between playing the same audio warning, that's currently on the base version of FAF, should be maintained.

**Comment by Garanas** [comment]
We're aware of it; it is fixed with https://github.com/FAForever/fa/pull/6208 but the deployment is not functional at the moment. So we can't deploy the fix.
