### ISSUE TITLE
The player's kick fails when there are several teams in the lobby.

### ISSUE THREAD

**Issue by GodFuper** [FAForever/fa#6219]
https://github.com/FAForever/fa/blob/6625471d6762dd0b421a17233b709c5597ac8fb2/lua/ui/lobby/lobby.lua#L4368

**Describe the bug**
The kick observer with index 0 fails.

**To Reproduce**
Put multiple players in Observers. And try to kick it at the top one.

**Expected behavior**
A window with "Are you sure?" should appear. So that you can kick.

**Screenshots**
![Анимация6](https://github.com/FAForever/fa/assets/40344333/2f8b6e97-55ac-46d7-a033-7a2b2db252a1)

**Comment by GodFuper** [comment]
![изображение](https://github.com/FAForever/fa/assets/40344333/9fe3716f-ee0c-4e93-a664-5b247e5b6833)
If there are 2 teams in lobby, then you will not be able to kick the first 2 Observers.
The whole function needs to be reviewed, as it does not work correctly.
https://github.com/FAForever/fa/blob/6625471d6762dd0b421a17233b709c5597ac8fb2/lua/ui/lobby/lobby.lua#L4351-L4364

**Comment by Garanas** [comment]
Best bug report of the season 👍 , @4z0t or @lL1l1 would either of you have time to look into it?
