### ISSUE TITLE
Resource waste when using high amounts of bp

### ISSUE THREAD

**Issue by HardlySoftly** [FAForever/fa#622]
High amounts of build power can cause more than the cost of a unit to be spent on it.

Test shows a t1 mex being constructed by a t1 acu under assist from 100 hives.  Total expenditure is ~400 mass and 4k energy, actual cost of unit is 36 mass and 360 energy.

http://content.faforever.com/faf/vault/replay_vault/replay.php?id=3474851

**Comment by aeoncleanse** [comment]
Can we confirm that storage is being used, or is this just a UI display error?

**Comment by VoRGoR** [comment]
Yes, it uses more resources than it needs due to the excessive buildpower. This bug has been known for a long time, it's just that no one ever really reported it.

**Comment by Garanas** [comment]
There has been a seven minute Youtube video that described this issue extensively. I am not sure where that is - does anyone happen to know what I am talking about?

**Comment by Garanas** [comment]
This issue still exists, but there's nothing we can do about it. The bottom line: don't overkill a single air factory with 25 hives.
