### ISSUE TITLE
You can instantly destroy reclaim of buildings from across the map.

### ISSUE THREAD

**Issue by VoRGoR** [FAForever/fa#623]
Only works with same faction, since you need to be able to build the building which made the wreck.

Replay 3474855.
http://content.faforever.com/faf/vault/replay_vault/replay.php?id=3474855

You *used* to be able to use this to rebuild buildings at 1/2. It was made so that this didn't work, but as you can see, effects still remain.

This also was part of a bug that let you rebuild a line of buildings from 1/2 from dragging from a wreck - that was also fixed.

To clarify, no reclaim mass is received.

**Comment by Sheeo** [comment]
This needs to be fixed for 3641

**Comment by Crotalus** [comment]
Hmm, I've messed with this a bit and not found any good solutions yet.

Seems like the wreck is flagged to be removed at the instant you place down the build order, at that moment GetRebuildBonus() is called on the builder. The actual removal of the wreck happens when the builder starts to build, even if you have moved the build location.

Can't see any way to block the actual removal of the wreck, maybe the only solution would be to insta-respawn an identical prop at the location.

**Comment by quark036** [comment]
In GetRebuildBonus, it provides the builder as one of the arguments, does the builder have a property saying where it is building?

**Comment by Crotalus** [comment]
No, the builder hasn't start building when GetRebuildBonus is called and there's no way of getting the current build plan from the sim side (command-queue is invisible from sim).

**Comment by ChrisKitching** [comment]
Various possibilities:

- Check that the health of the wreck you're about to delete is zero (or possibly near zero). This would suggest you've just reclaimed it (and hence are building in the right place).
- Check that the engineer is sufficiently close to the wreck than it's in build range. If not, you're definitely not building in the right place.

**Comment by quark036** [comment]
I don't think either of those work. As to the first one, you don't reclaim the wreck, you just build on top of it (starting from halfway done). For the second, it would prevent people from queuing up factories on wrecks that are out of range.

**Comment by quark036** [comment]
So, to sum it up, our goal is to not remove wrecks if the new building that was placed on them is moved. However, we don't know the position of the wreck, or if the building was moved.

**Comment by aeoncleanse** [comment]
Do we not see when queued buildings are dragged from UI, and can then tell the Engie to GetRebuildBonus again?

**Comment by quark036** [comment]
How would that solve the wreck being removed?

**Comment by aeoncleanse** [comment]
Well if GRB is nil once moved, perhaps it will be unflagged for removal

**Comment by quark036** [comment]
I don't think that would happen, because it wouldn't store the wreck, and
it doesn't get passed to GRB.
