### ISSUE TITLE
Create a Github Workflow to convert markdown changelog files into Lua changelog files

### ISSUE THREAD

**Issue by Garanas** [FAForever/fa#6238]
Description
-----------

Needs: https://github.com/FAForever/fa/issues/6237

Create a new workflow file to convert the changelog files from the markdown format to a Lua format. This workflow should use the tool created in https://github.com/FAForever/fa/issues/6237 . The output of the workflow is an artifact with all the changelog files in a Lua format.

**Comment by Zjonn** [comment]
Hi @Garanas, I have some questions about this issue:
- `with all the changelog files in a Lua format.` Do you want this workflow to parse all changleog files each time it's runned?
- Should it be runned  (only) on push to:
  - develop
  - deploy/fafdevelop
  - deploy/fafbeta
 - How about workflow_call and workflow_dispatch, should they be also added?

**Comment by Garanas** [comment]
Yes - the goal is to have one place where we manage the changelog files. These are written in Markdown. We then generate lua-compatible changelog files from the markdown changelog files. For now, this is not a complicated task - we essentially add `"` to the start and end of each line and then generate a Lua table around it with the remaining properties. In the future we may want to extrapolate more information so that we can generate links to pull requests for example, but that's a feature for the future.

> Do you want this workflow to parse all changleog files each time it's runned?

Yes, the input is all Markdown changelog files in an input folder. And the output is one Lua file for each Markdown changelog file in an output folder. We then store that output in an artifact. That's the entire scope of this issue.

> How about workflow_call and workflow_dispatch, should they be also added?

Yes, the workflow should be a separate workflow that can trigger on both `workflow_call` and `workflow_dispatch`. Dispatch allows us to run it manually, useful for testing 😃 . Call allows us to run it from another workflow, which allows us to integrate it into the existing deployment workflows. 

To repeat myself - this issue is only about the new workflow, which should generate an artifact with all the Lua-compatible changelogs. Integrating it with the existing deployment workflows is another pull request/issue. It requires a little more work, as the game also needs to support the new format (one file for each changelog, instead of one massive file with all changelogs in it).
