### ISSUE TITLE
ForkThread

### ISSUE THREAD

**Issue by EvildrewFAF** [FAForever/fa#6248]
This is mostly a question about ForkThread. 
Was the function removed or changed? 
It seems to me like several things that use it do not work anymore.

**Comment by Garanas** [comment]
It's better to ask questions such as this on Discord.

The only change to the global is this:

- https://github.com/FAForever/FA-Binary-Patches/pull/46/files

Which checks whether you sent in a Lua function. Nothing else changed, as far as I am aware.
