### ISSUE TITLE
Crash when selecting multiple sized nukes

### ISSUE THREAD

**Issue by aeoncleanse** [FAForever/fa#627]
In release/3641, Chris found that when you select multiple nukes with different damage radiuses, the game crashes thanks to the reticle scaling. I think this will also apply to T3 Arty, TMLs etc thanks to the way Crotalus expanded the idea to all of those.

**Comment by Crotalus** [comment]
Hmm, I only get the expected "WARNING: Nuke decal called for non-nuclear weapon", no crash. 

Tried with all four SML + Exp Nuke. How to replicate the crash?

**Comment by Sheeo** [comment]
@ChrisKitching

**Comment by aeoncleanse** [comment]
I misunderstood. The 'crash' is the fact that it shows the error rather than a decal. IMO it should show whichever is the largest decal.
