### ISSUE TITLE
Beams collide with missiles. Should they?

### ISSUE THREAD

**Issue by aeoncleanse** [FAForever/fa#628]
Softly brought this to my attention. Confirmed for ML and Sera PD

**Comment by HardlySoftly** [comment]
Collisions occur for ML, Sera t2 pd, t3 battlecruiser, sera destroyer, acu laser, lightning tank.

Missiles do not collide with GC beam.

**Comment by aeoncleanse** [comment]
Aeolus gave a pretty convincing response. They want beams to collide with missiles, and kill the missiles instead of not killing them as they do now.

**Comment by speed2CZ** [comment]
I saw also missiles from cybran MML colide with Sera T2 static arty shots, killing the arty shots.

**Comment by ppipp** [comment]
I don't think beam weapons should kill missiles or other projectiles. They are not supposed to be anti projectiles weapons and in some cases, projectiles will nullify beams.

**Comment by Crotalus** [comment]
The current behavior is silly though, flying missiles blocks off the beam weapon of a monkeylord, the realistic fallout would be to kill the missile. An artillery shell colliding with a missile should destroy both.

We probably should try to streamline these behaviors across the line, friendly fire of weapons and projectiles.

**Comment by aeoncleanse** [comment]
OK then so it turns out this is quite a complicated story. Let's begin with ML vs MML, and I'll update this as I discover more stuff. So, in this matchup, what happens is that the beam decides it has collided with the projectile, thus cutting short. It passes to DoDamage, which, because 99% of beams have a damage radius, uses the DamageArea command to damage the impact site. However, the DamageArea command does NOT affect projectiles, so the projectile doesn't take damage.

The only reason the Cybran TMD (Which is a beam) works is because it has no radius, so it uses the Damage command instead, which apparently DOES affect projectiles.

Meanwhile, the projectile has also detected a collision, but "Missile hits DirectFire" is one of the clauses which returns negative collision, so the projectile decides it has not hit anything after all.

The GC's beam, on the other hand, has DoNotCollideList 'MISSILE' set in the blueprint. I cannot find any reference to this entry in the lua in a place accessible to this weapon (It's found in unit.lua, shield.lua and projectile.lua, but this case doesn't access any of them), and logging shows that the GC beam doesn't even register detecting the missile at all. I can only assume that moho.CollisionBeamEntity performs a check on that collision list automatically, and that CollisionBeam's OnImpact() is called from that if the collision check in engine returns true.

So... What do we want to do here?

**Comment by aeoncleanse** [comment]
Wonder why this didn't autoclose, the other one worked...
