### ISSUE TITLE
Replays desyncing, typically on disconnects

### ISSUE THREAD

**Issue by Sheeo** [FAForever/fa#63]
Hypos:
- Bad hotstats
- Bad FAFWin detection
- Possible lobby relay issue.

**Comment by Crotalus** [comment]
Got this error in a live replay:

info: Client 0:Replay claiming command source 6, but not authorized for it.
info: Sim crashed hard in DoSimBeat(): Attempt to construct EntIdSet with different types of IDs (0 and 10) in DecodeEntIdSet

Starting to think the "stream-switching" of the replay server is at fault, thus happening when players (current replay writer) disconnects from the replay.

**Comment by Justify87** [comment]
Is this still getting investigated? I find a lot of replay of games that completed succesfully, but the replay desyncs mid game or at the end of it.

This is an example replay:
6151835

**Comment by CookieNoob** [comment]
it would be great if someone would pick this up.

@aeoncleanse why do you think this is an engine bug? replays from FA (not FAF) desync with much lower frequency and the amount of desyncs increased significantly during the last 2 years (the rate went up when the server was changed +- a few patches)

**Comment by aeoncleanse** [comment]
Because we're not talking about FA replays, if we go back in time we're talking about GPG replays. Which did desync a lot. It's the whole DC thing I think, and I have no idea what to do about it.
