### ISSUE TITLE
3641 testing - show reclaim in score table not working

### ISSUE THREAD

**Issue by Exotic-Retard** [FAForever/fa#630]
seems that the showing of the reclaim in score doesn't work when you reclaim a factory;

what i did:
start building factory but don't finish
reclaim that fully
start building another factory
receive errors

you get this in the log:
http://pastebin.com/eztDCP4n

hoping this helps :/
hoping im doing this right :/

**Comment by aeoncleanse** [comment]
This is to do with the show reclaim feature, which is not working for me. Pressing ctrl + shift does nothing, and I don't see it under F1 or in Options.

**Comment by Crotalus** [comment]
Try now, there was an error with resetting world view and reclaim labels

**Comment by aeoncleanse** [comment]
:+1:

**Comment by Crotalus** [comment]
`release/3641`
Score calculation formula isn't using reclaimed mass / energy when doing its calculation, the data is there though so the function needs to be updated

**Comment by ChrisKitching** [comment]
Can you take this one, Crotalus, as you seem to know what's going on?

**Comment by Crotalus** [comment]
We could leave this for 3642+, the score calculation only takes mass spent into account (which also includes reclaimed mass), same as the current behavior. The question is if we also want to give points if you actually reclaim something.

**Comment by ChrisKitching** [comment]
E_INSUFFICIENT_FUCKS_GIVEN
