### ISSUE TITLE
testing 3641 - sacu drone rebuild not working

### ISSUE THREAD

**Issue by Exotic-Retard** [FAForever/fa#631]
spawned sacu
select drone
ctrl-K
recieve error:

http://pastebin.com/AMwNM0b2

hope this is usefull :/

**Comment by aeoncleanse** [comment]
Very useful. Fixed now, both on the testing branch and on the PR.

**Comment by Sheeo** [comment]
@aeoncleanse please reference commits when you post comments like this, so you leave a followable trail.

**Comment by aeoncleanse** [comment]
Oops, right you are, it's #616
