### ISSUE TITLE
testing 3641 - yolona oss aded to super game enders category bad description

### ISSUE THREAD

**Issue by Exotic-Retard** [FAForever/fa#632]
everything works it seems but the description of the restriction is the same as before in the lobby, title is changed as it should be.

also a restriction called "super game enders" which also doesn't restrict the paragon is a bit confusing

hope this helps :/

**Comment by aeoncleanse** [comment]
Agree about not restricting paragon, but that already has its own option, so they just click that one too.

**Comment by Sheeo** [comment]
Hang on -- there's a real issue with a category that's meant to restrict super game enders but doesn't. Do we have an issue to replace that?

**Comment by aeoncleanse** [comment]
I saw no reason to add the Paragon to the list because the Paragon already has an option to disable it, and only it. I assumed that's the only reason the guy who brought it up didn't ask for Paragon too. In future, I plan to make the system 100% modular on a per-unit basis anyway.

**Comment by Sheeo** [comment]
Well yes that's not my point; my point is that the other option is confusing.

Does your plan have a corresponding issue we can reference?

**Comment by aeoncleanse** [comment]
No. TBH it's a bit of a pipe dream at present. :(

**Comment by ChrisKitching** [comment]
No point overhauling the UI like that, really. Lots of work for no real gain.

**Comment by aeoncleanse** [comment]
No point, no, but it's something I'd like to do for myself, so... If I get the time :)
