### ISSUE TITLE
Personal shield bugs

### ISSUE THREAD

**Issue by Sheeo** [FAForever/fa#634]
![Aeon SCU hitbox](https://dl.dropboxusercontent.com/u/6523304/bad-hitbox.png)

**Comment by aeoncleanse** [comment]
So Aeon has a bubble when it should not, but plays the ACU sound. UEF has no bubble, as is correct without the bubble upgrade, but does not play the sound.

**Comment by aeoncleanse** [comment]
Incorrect bubble placement corrected here
https://github.com/aeoncleanse/fa/commit/32e95d0d6847b8b9074d8e4de7d72b65a4565f02

**Comment by Sheeo** [comment]
@aeoncleanse please submit a PR to `release/3641`.
