### ISSUE TITLE
[Balance Idea]: add DifferentialUpgradeCostCalculation to Mexs

### ISSUE THREAD

**Issue by GodFuper** [FAForever/fa#6354]
### Intended Change

If we add "DifferentialUpgradeCostCalculatio", it turns out that the T3 extractor will become cheaper by 900 mass. Will need to adjust the price.
Upgrade should be encouraged, not rebuild.

### Reasoning

Rebuilding "extractors" makes it economically profitable if destroyed and rebuilt quickly. 
Players gain an advantage if they build the t3 extractor right away, skipping the t2 stage. Although logically it should be the other way around.

### Expected behavior

Example: t3 mex = 5500 mass (4600 + 900) and 37025 energy (31625 + 5400).
The figures are approximate.

This mechanism is used in shields, why are extractors worse?

**Comment by Hdt80bro** [comment]
Why should upgrading be preferred to rebuilding, how does this encourage that, and how do the benefits out-weigh the downsides?

**Comment by MrRowey** [comment]
This has already been denied by the balance team last year as it not what the team wants.

**Comment by lL1l1** [comment]
Don't think balance team is going to change their mind on this. It's a tradeoff of APM for a slight boost in economic efficiency (you only get 648 mass - 9 mass/s * time spent building t3 mex), while also requiring good eco balance. It's an interesting choice to make in the game, as obtuse as the mechanic may be.
