### ISSUE TITLE
[Balance Idea]: Mercy buff

### ISSUE THREAD

**Issue by lL1l1** [FAForever/fa#6357]
### Intended Change

Make the Mercy cheaper in a way comparable to the Fire Beetle. Stat changes by Farms ([Discord](https://discordapp.com/channels/197033481883222026/1259659473203630110/1259675509479182417)):
- Mass cost 300 -> 230
- Energy cost 6000 -> 4600
- Build time cost 2000 -> 1200

### Reasoning

- Mass/Energy costs: The Mercy is currently unused because it has ACU-sniper costs (unchanged from the rework) but is meant for killing armies and low HP structures such as T1 power generators.
- Buildtime: A single use unit should have low build time.

### Expected behavior

It is used against armies more often kind of like the fire beetle.

**Comment by lL1l1** [comment]
@MrRowey The balance idea form is kind of awkward because an "Expected Behavior" doesn't make sense for a balance change. I think a description of the balance issue (explain why you think a unit is bad to help other contributors understand what you're fixing), intended changes to fix the balance issue, and reasoning for the intended changes would be more appropriate sections for a balance idea form.

**Comment by MrRowey** [comment]
Well expected behaviour of the balance change is how it's going to effect the balanced gameplay with he intended change.
