### ISSUE TITLE
[Bug]: Part-complete buildings dont transfer in full share

### ISSUE THREAD

**Issue by maudlin27** [FAForever/fa#6361]
### Describe the Bug

Part-constructed buildings don't transfer on death.

### Reproduce the bug

Example of how to reproduce - create a game with an AI teammate in full share.  Cheat in some t2 engineers and start building a T2 PD.  Ctrl-K your ACU.  The part-complete T2 PD will die instead of transferring over.

### Additional context

See this forum post discussing the issue:
https://forum.faforever.com/topic/7914/why-do-unfinished-units-buildings-ctrl-k-in-fs-games

Also this pull request (referenced in the above) which fixed the issue for experimentals:
https://github.com/FAForever/fa/pull/2530

One comment in the pull request was "This transfer is pretty complex and we don't want to transfer too many units this way. So it doesn't contain nukes/smd buildings, as their cost are too low compare to t4/arty." - I took this to mean that it could be a performance issue for not expanding the functionality.  However, Jip noted Strogoo and Keyser were members of the balance team at the time and thought it intentional for balance reasons for only experimental units to be transferred.

I've messaged Tagada (balance team lead) to see if it can be clarified whether it's intended from a balance team perspective that only experimentals should transfer in full-share on a teammate's death.  If the balance team doesn't object to expanding this, then I can look at changing this and quantifying the performance impact to assess if fixing what feels like a bug would have prohibitive performance implications.

**Comment by Garanas** [comment]
Calling it a bug is a little off - it works exactly as intended. That times change and people want it different is fine, but that does not make it a bug 😉 - that is a feature adjustment.

Which is fine by me - I'm fine with it either way.
