### ISSUE TITLE
Replace `#XYZW` with a link to the pull request in question

### ISSUE THREAD

**Issue by Garanas** [FAForever/fa#6376]
### Description

When we create a release on GitHub all pull request references in the description that start with `#` are transformed to a link to the pull request. As an example, take the following release:

- https://github.com/FAForever/fa/releases/tag/3810

Meanwhile the source code is:

![image](https://github.com/user-attachments/assets/4a369671-2814-44ce-a207-011f3c84f7a6)

We'd like to do something similar for to-be introduced website that contains (generated) changelogs. As an example:

- https://faforever.github.io/fa/patches/fafbeta

Where all the pull request references should be turned into a hyperlink that takes you to the pull request in question. Not only does the average pull request contain additional information about the changes for the user, it also provides a low-weight introduction to get people to view GitHub and perhaps start contributing themselves.

### Course of Action

According to our friend ChatGPT there is a tool called `sed` in Linux to perform a 'find and replace (all)' type of operation on a file. It supports regular expressions and so we end up with something like:

`sed -E 's/#([0-9]{4,5})/[#\1](https:\/\/github.com\/FAForever\/fa\/pull\/\1)/g' inputfile.txt > outputfile.txt`

Which translates:

```
This is a reference to #12345.
Here is another one: #6789.
And yet another: #54321.
```

To:

```
This is a reference to [#12345](https://github.com/FAForever/fa/pull/12345).
Here is another one: [#6789](https://github.com/FAForever/fa/pull/6789).
And yet another: [#54321](https://github.com/FAForever/fa/pull/54321).
```

If we apply this transformation _right before_ we build the website then we have the same behavior as a GitHub release: the source is simple (just `#1234`), where as the final output is a link. This is convenient to the developer and to the user. 

Steps to take:

- (1) Add a new script file called `changelog-links.sh` to the [scripts folder](https://github.com/FAForever/fa/tree/develop/.github/workflows/scripts)
- (2) Update the [build workflow for pages](https://github.com/FAForever/fa/blob/develop/.github/workflows/docs-build.yml) so that the scripts become globally available. You can review how that is done in the [changelog workflow](https://github.com/FAForever/fa/blob/develop/.github/workflows/changelog.yaml#L99-L101)
- (3) Update the [build workflow for pages] to run the script over all the [posts](https://github.com/FAForever/fa/tree/develop/docs/_posts). These posts represent the changelogs. Make sure to run it _after_ we populate the posts for `fafbeta` and `fafdevelop`.

### Test Plan

You can write and test `changelog-links.sh` locally. It should take in a folder as a program argument and update all files in-place. 

Testing the workflow is less trivial, but you can get a long way by creating a branch and using the `workflow_dispatch` trigger and then choose the branch that you're working on.

Note: the processed markdown files should not be pushed.

### Learning Goals

Become more familiar with writing Bash scripts and integrating it in a workflow.

### Progress

_Not applicable_

**Comment by relent0r** [comment]
@Garanas  Initial script test output looks like this(thanks for the sed example). I'm thinking we want to only apply to .md files.

![image](https://github.com/user-attachments/assets/29d45bb7-8a4f-4d69-b9d6-64b8a0bfbd6f)

**Comment by Garanas** [comment]
That looks good 👍 , and yes - we only want it to apply to Markdown files. You can use a bash script with a for loop on the pattern `*.md` for that
