### ISSUE TITLE
[Balance Idea]: UEF T2 Stinger can build a single T1 land unit on its hook

### ISSUE THREAD

**Issue by apollodeathstar** [FAForever/fa#6387]
### Intended Change

UEF T2 Stinger can build a single T1 land unit on its hook at a very slow rate. 1/8 or less T1 land factory build rate. This will allow it to equip itself with a MM and replace its mech marine if it is destroyed, but not act as a factory replacement due to its low build rate. Player would select their stingers, set to auto build MM and the stinger would build 1 on its hook over a period of time, it could then drop these or keep them on the hook to fight with the gunship.

### Reasoning

Auto-loading of Stingers was rejected. This is a alternative method of allowing the stinger to have a easier way to equip Mech marines and make the function useful and used.

### Expected behavior

Players can build stingers and set them to auto build themselves Mech marines on the hook, the stinger would have its own BP and would build the stinger on its hook and hold them until the MM was destroyed or dropped, it would then be able to build another mech marine. it would not produce them 1 after the other. once it has completed a MM it would not build another until the player manually dropped the MM.

**Comment by Garanas** [comment]
If it is up to me then we're not turning every Stinger into a mobile factory. Mobile factories are difficult to maintain, they are relatively expensive on the simulation let alone that the behavior that you describe here:

> it would not produce them 1 after the other. once it has completed a MM it would not build another until the player manually dropped the MM.

Would need to be created from scratch and it would fight against how the engine like factories to work.

There are recent introductions such as the [Load into transports](https://wiki.faforever.com/en/Play/Game/Hotkeys/OrdersAdvanced#load-into-transports) hotkey (that is also applied by right-clicking the transport action) to help ease the loading process for transports in general. I'd suggest to use that more 😃 !

**Comment by lolaenter** [comment]
i hope you dont introduce  this stingrey balace idea.

**Comment by Rhaelya** [comment]
As the balance team has previously discussed Stingers wont come preloaded with a mechmarine and neither will they be turned into a mobile factory.
