### ISSUE TITLE
Don't stop factories assisting

### ISSUE THREAD

**Issue by aeoncleanse** [FAForever/fa#640]
Had a lot of complaints about this 'Fix'. Apparently since it works as long as you press shift, this 'fix' will upset and irritate a lot of players who have just worked around it. speed2 suggests copying the ACU, which cannot actually be given any orders except pause and cancel while it's upgrading. Why, he reasons, can we not do that? @Crotalus

**Comment by speed2CZ** [comment]
The idea is actually to look at Coding Squirel's Notify mod that allows to qeue up commands to ACU on upgrade. It allows to qeue up other upgrades and all other commands (move, assit, everything)
And yes, DO NOT disable assist on factory that is on upgrade

**Comment by HardlySoftly** [comment]
Assist command from an upgrading factory is something I use (almost) every game.

**Comment by Crotalus** [comment]
Hmm, FYI I created the original Notify mod + the queuing up enhancements (he forked it and added messages to more upgrades).

But I agree that removing command cap isn't optimal. I've been researching this some more now and found out a (bit ugly) hack. By setting the factory state to 'Enhancing'  we inform the engine that it shouldn't clear the current running command.

This is the best we can do, if you give assist order without shift = nothing happens (same as when trying to give order to a unit which isupgrading). If you give the assist order while pressing shift it will get queued up.

**Comment by aeoncleanse** [comment]
Ah, enhancing. I tried Upgrading and that didn't work. in fact, the set unit state command didn't work at all, so if you can make it happen, go nuts!

**Comment by Crotalus** [comment]
Ugh, engine didn't like that particulary well, made engineers unable to assist the Upgrhancing factory, they just get stuck in some weird assist loop. 

I've tried lots of workarounds to no avail... if someone wants to give it a try, replace this in `defaultunits.lua`: 

Line 627: `self:RemoveCommandCap('RULEUCC_Guard')` with `self:SetUnitState('Enhancing', false)`
Line 645: `self:AddCommandCap('RULEUCC_Guard')` with `self:SetUnitState('Enhancing', true)`

**Comment by Sheeo** [comment]
@aeoncleanse bcf7a7cabceadd572bce94385a64001121d2ea1e is not in `release/3641`, a changelog entry does reference it, however.

**Comment by aeoncleanse** [comment]
bcf7a7cabceadd572bce94385a64001121d2ea1e appears to be affecting release/3641... I checked the file and the changes are there, and git blame shows it too??
https://github.com/FAForever/fa/blame/release/3641/lua/defaultunits.lua#L626

**Comment by Sheeo** [comment]
Odd, it wasn't showing up. Indeed it was there -- reverted now.
