### ISSUE TITLE
prioritize repair over assist on un-build facto

### ISSUE THREAD

**Issue by shalkya** [FAForever/fa#643]
at the moment, when a facto isn't finish, right click on it with engie/acu = assist (lead to range of building....)
I would suggest to switch (1st) right click to repair (=building). 
And for right click (=building/repair) + (shift + right click) (=assit)

**Comment by quark036** [comment]
Isn't this done in 3641?

**Comment by Sheeo** [comment]
It should be, yes -- thanks for helping us sanitize issues :)
