### ISSUE TITLE
FA Lobby AI selecting issue

### ISSUE THREAD

**Issue by DarkmatterVale** [FAForever/fa#644]
When attempting to select an AI, the preview window that describes the AI does not give information on the selected AI. Instead, it gives me a preview of the AI two slots below. For example, if I hover over "AI: Easy", the preview window shows information about the "AI: Adaptive"

I have tested by creating a custom Forged Alliance Forever custom game with a random password on Seton's Clutch as the default map. Other maps are the same as well.

**Comment by ChrisKitching** [comment]
Fixed with 09bc8e1.

**Comment by DarkmatterVale** [comment]
Awesome! Thanks for fixing this!
