### ISSUE TITLE
Refactor inheritance chain of construction units

### ISSUE THREAD

**Issue by Sheeo** [FAForever/fa#647]
Spinoff from [this discussion](https://github.com/FAForever/fa/commit/a6948c9#commitcomment-11556014).

We need the inheritance chain cleaned up for construction units. Exmples of bad inheritance:
- CommandUnit doesn't inherit from ConstructionUnit
- StructureConstructionUnit doesn't inherit from ConstructionUnit

Moreover, many classes that derive directly from their base are defined in `defaultunits.lua`, making it difficult to hook a base class without also redefining all derived classes. We should look into moving these definitions into seperate files, making it easier to mod.

**Comment by MrRowey** [comment]
@Garanas would this come under the Optimisation that you have been working on

**Comment by Garanas** [comment]
This would be code style. It is very relevant, but also not worth the effort for now.

**Comment by Garanas** [comment]
This can break mods that expect the current hierarchy, closing as not planned.
