### ISSUE TITLE
Units which need bones adding

### ISSUE THREAD

**Issue by aeoncleanse** [FAForever/fa#651]
Add above water bone:
UEF T1/T2/T3 Sonar
UEF/Cybran/Aeon Torpedo Launchers

Add more bones, centralised bones, or indeed decentralised bones:
Cooper
Mermaid
Naval Factories
Megalith
Hovertanks

**Comment by bamboofats** [comment]
Ill try this. 
Can I confirm the above water bone list?
UEF Sonar: T1 T2 T3.   (Only Uef, no others)

UEF Torp T1 T2
Cybran Torp T1 T2
Aeon Torp T1 T2
(Seraphim not required)

**Comment by bamboofats** [comment]
I had a look through the models of all sonars and torps. The sera t1 torp has above water bones but its at the muzzle exit offset laterally. And the sonar bones are quite varied. Stuff like the cybran t1 sonar has bones above, but missed quite a good % possibly due to its rather flat surface (Hitbox?). The t2 UEF sonar had quite high evasion vs my destroyer at max range, only 1/3 hit, but it already has a bone above water??.
Ill try create a new targetting bone for all of them centralised and somewhere 40% of the protruding height from the water surface. Except for sera sonars. Those 2 are quite well placed already.
Shifting the exisiting bones altered the position of some of the effects attached to them so ill not do that.

**Comment by aeoncleanse** [comment]
Take a look at my collision instances PR,  or the issue on this topic.  Only those using the raised class need a new bone

**Comment by ChrisKitching** [comment]
> Stuff like the cybran t1 sonar has bones above, but missed quite a good % possibly due to its rather flat surface (Hitbox?)

In-game, you can press CTRL+ALT+SHIFT+C, CTRL+V, and CTRL+B to show collision boxes, bones, and bone names.

If a bone being used for targeting is outside (or near the edge of) the blue collision box, it's going to produce disproportionately many misses.


> Ill try create a new targetting bone for all of them centralised and somewhere 40% of the protruding height from the water surface. Except for sera sonars. Those 2 are quite well placed already.

This sounds like a sensible approach. Remember you have to update the TargetBones list in the blueprint before your changes will affect how targeting occurs (you'll have to put the new bone name in the list higher than any existing bones, basically).

> Shifting the exisiting bones altered the position of some of the effects attached to them so ill not do that.

That's how it works ;)

You'll just want to add new dummy bones used for targeting only, basically.


Let me know if you have any more questions.

**Comment by aeoncleanse** [comment]
Yup, the above list is what needs doing, Sera Torps for instance are fine. And yes, new bones please.

**Comment by bamboofats** [comment]
I think this could be quite a success, but you all have to test it a bit first. 
I added targetting bones for the following, in LOD0 high poly model 
=Aeon Torp T1 T2
=UEF Torp T1 T2
=Cybran Torp T1 T2
=Sera Torp T1 T2   (Sear t1 torp hit accuracy is much improved by adding bones i tested, anyway the sera t2 torp has the bones named in blueprints wrongly, using UAB2205 when it should be XSB2205. I added bones for it just to go along with the rest and change it to Abovetgt)
=UEF Sonar T1 T2 T3

The bone is called "Abovetgt"  same name used for all. This should be the only targetting bone in the blueprints now, delete others like Turret_Barrel, they apparently arnt needed. Can someone add this to all 11 blueprints?
    AI = {
        TargetBones = {
            'Abovetgt',
        },
    },

With this using a destroyer max range I was able to achieve almost 100% hit rate on them. Torpedoes and bombers also target correctly as it previously did.

Folder with 11 models
https://www.dropbox.com/sh/ir587xv3l00tixm/AAC4Yh46igdpQ6z94o6BfpEqa?dl=0

Let me know how it goes!

**Comment by ChrisKitching** [comment]
> This should be the only targetting bone in the blueprints now, delete others like Turret_Barrel, they apparently arnt needed.

This surprises me.

I would have expected torpedo launchers to use an underwater targetbone.

In any case, I shall merge your changes now. Thank you.

**Comment by aeoncleanse** [comment]
No, don't delete the others. have the new one top. We must have a below-water for torps, or the opposite happens.

**Comment by aeoncleanse** [comment]
I should also say... THANK YOU SO MUCH :D :D :D :D :D :D :D :D

**Comment by bamboofats** [comment]
Oh, the below water bones were a bit inconsistent between the various units. Eg All sonars do not reference targetting bones in the blueprints, T1 torps, eg Aeon, bone called "Turret" is underwater, while T2 torp bone is called "UAB2205" which is at coordinates 0,0,0,  and sera T2 torps bones is called "UAB2205" (which is totally wrong as the model bones are called XSB2205).

But all these can be targetted properly by torpedoes.  So I tried removing them, and just adding one above water bone reference. It seems to work fine. I use subs to target each model will 100% hits, depth charges, torpedo bombers work correctly.

**Comment by aeoncleanse** [comment]
The base UID bone, eg UAB2205, counts as underwater. The fact that 0,0,0 is submerged is the reason we need to do this.

**Comment by bamboofats** [comment]
Ok then. You could retain them. Just...  just change the SERA T2 torps from UAB2205 to XSB2205,  cos thats the correct one in the model. 

For the sonars, do you want to add an underwater bone as well?  The default blueprints are empty. I just added only above water as 'Abovetgt'   .  
If you do want, then, 
UEF T1      will be 'UEB3102'   at 0,0,0
T2          could use 'B14'    , cos UEB3202 is acutally postiive Z
Same for T3, could use 'B14'    for the same reason

**Comment by bamboofats** [comment]
You're welcome!  Do let me know the bone issues for the other units you mentioned,  if they need tweaking too

**Comment by aeoncleanse** [comment]
For the sonars, the UID bone is the underwater. Same for all these units. 

Let's see... The Megalith wants a bone at centre-mass of the main unit.
Naval Factories have the same problem as the Sonar/Torps, no above water bone, support and normal facs.
Cooper and mermaid have no center-mass bones, similar to the Sera Torp, they're at each end of the ship. Same for Hovertanks.

**Comment by ChrisKitching** [comment]
Merged with 67c695877709ce8d1b53fa468a485b34d237762f and 4f10f14935406f1f3c432b0a891e4d5444932a97

**Comment by bamboofats** [comment]
Could I clarify, the hovertanks you refer to, which units exactly are they? There are a few units which are tanks and hover?, I hope i dont miss any.

**Comment by bamboofats** [comment]
Hmm, I assumed the Hover tanks to be the Aeon UEF and SERA amphi class T2 tanks, I added a central bone for all but feel free to ignore those units that I mistakenly edited.
I edited these unit models to add a single bone
Megalith XRL0403
UEF T2 torpboat XES0102
CYB T2 intelboat XRS0205
Aeon Hover XAL0203
UEF Hover UEL0203
Sera Hover XSL0203

The bone is called 'Centraltgt'  
6 files
https://www.dropbox.com/sh/7tko7bmgch6nyij/AAAVh_6y-8_wm4eW6_OCh5wLa?dl=0

I tried a few targetting rounds with them and no obvious issues so far. 
But I somehow cant test out the megalith. I normally test the units by doing a model swap in the mod with an incorrect model, and see if it shows up in game, just to demonstrate that the file is the correct one.  But doing so for the megalith XRL0403 has no effect. Even making the file blank, the original megalith model still shows up in game. Trying with XRL0403_LOD0.scm  
Can someone help me test if my modifed file XRL0403_LOD0.scm  will produce the updated bones in game? And that  the textures, walking,firing, awake and death animations still work correctly.

**Comment by aeoncleanse** [comment]
You guessed right :)

**Comment by bamboofats** [comment]
@aeoncleanse 
I checked with the model files. It looks like all naval factories have above water bones, mulitple even, although they arnt distributed equally. 
Are there targetting issues affecting them? Is it because of the longish shape?
I tried shooting, the shots try to land in the centre for aeon cyb sera, but for uef the shots tend to go either ends of the yard, not in the middle. But no unusual misses though.

You want me to create 3 targetting bones, spread out along the model, for them to be explicitly referenced in the blueprints?

**Comment by aeoncleanse** [comment]
Oh cool. You definitely understand the problem,  and when it occurs.  I'll leave this to your best judgement.

**Comment by bamboofats** [comment]
Alright, after hours its done. I added targetting bones to all 20 shipyards and Im quite satisfied with the results during testing. Projectiles, torps and bombs show more variation in the hit locations. The model files are uploaded here.
https://www.dropbox.com/sh/hqk7nr6vhur4wkt/AAALFiWFubHvJ3j1lhTifvlAa?dl=0

=====AEON:
UAB0103 UAB0203 UAB0303 ZAB9503 ZAB9603
Add the following bones in this order
Tgt1
Tgt2
Tgt3
Tgt4

======UEF
For T1, T2 HQ, T2   UEB0103 UEB0203 ZEB9503
Bones:
Tgt1
Tgt2
Tgt3
Tgt4
B13

For T3 HQ, T3   UEB0303 ZEB9603
Bones:
Tgt1
Tgt2
Tgt3
Tgt4
Center_Deck

=====Cybran:
URB0103 URB0203 URB0303 ZRB9503 ZRB9603
Bones:
Tgt3
Tgt1
Tgt4
Tgt2

======Seraphim
XSB0103 XSB0203 XSB0303 ZSB9503 ZSB9603
Bones:
Tgt1
Tgt2
Tgt3
Tgt4

. Again, let me know how the new stuff works out.
I have just yet to test the megalith to make sure it functions properly.

**Comment by aeoncleanse** [comment]
We're going to need a special "Super genius anti-hack person" section in the changelog, just for you :)

**Comment by bamboofats** [comment]
:) hehe

I resolved my own confusion with the megalith. It appears that the unit ID is XRL0403, but it uses the model file in XRL0404. So i produced the edited model files for 0404 with the central bone, but edited 0403 for consistency(i have no idea if 0403 is used any where else in the game)

The following files should be placed this way for the megalith
XRL0403  -> XRL0403_LOD0.scm  and XRL0403_unit.bp (add bone 'Centraltgt' at the top)
XRL0404 -> XRL0404_lod0.scm

**Comment by ChrisKitching** [comment]
The only models referenced from the blueprint are /Units/xrl0404/xrl0404_LOD1.scm and /Units/xrl0404/xrl0404_LOD0.scm

The one in 0403 is just junk: GPG fucked something up here.

You need to modify the LOD1 one, as well, or badness seems likely.

**Comment by bamboofats** [comment]
Hmm, i tested with just modifing the LOD0 but nothing nasty appeared so far. Anycase, I modded the LOD1 as well with the same centraltgt bone at the same location.  Uploaded both to the folder. (check the previous edited post)
I deleted the junk 0403 one.

**Comment by bamboofats** [comment]
@ChrisKitching I noticed the megalith blueprints XRL0403_unit.bp has the added bone "centraltgt",  but my updated models were not included yet, meaning the bone is currently invalid?
Only the torps and sonar models were added for this issue, at this time.

**Comment by ChrisKitching** [comment]
Merged it now. Whoops.
