### ISSUE TITLE
Restricted upgrades can be started from UI mods

### ISSUE THREAD

**Issue by HardlySoftly** [FAForever/fa#661]
For example if the game is no t3 units, a ui mod can still start an upgrade to a t3 mex from a t2 mex.

A player without UI mods remains unable to upgrade mexes to t3.

Confirmed for t2 and t3 mex upgrades, probably true for other things like factories.

**Comment by Varaxis** [comment]
Quick and dirty fix is to disable this (which breaks all UI mods that use it):
 IssueBlueprintCommand("UNITCOMMAND_Upgrade", unit:GetBlueprint().General.UpgradesTo)

Complicated and more elegant fix is to somehow fix unit restrictions to be more thorough, doing much more than remove units from build menus.

**Comment by Sheeo** [comment]
Not just all UI mods, but the normal UI. That's no fix.

The restrictions need to be enforced sim side.

**Comment by Varaxis** [comment]
I honestly would like to keybind such a command to a key, honestly.

 Have to note that campaign scripted maps disable units from players, yet allows them to exist for the AI, and also later unlock the units as the script progresses.

**Comment by Sheeo** [comment]
Keybinding currently works, I'm not sure how anything suggested here changes that.

Enforcing them sim side--at a proper time, in a sane manner--doesn't conflict with allowing units already on the field.

**Comment by ChrisKitching** [comment]
This was actually fixed *ages* ago in CBFP, in a surprisingly sensible way:
https://github.com/FAForever/fa/blob/release/3641/lua/game.lua#L130

Somehow this code has become dead. Time to spruce it up a bit.

**Comment by ChrisKitching** [comment]
... Okay, not really, that code was a nightmare, but it's fixed now:
65882eae58eb437e23eb61bb6864c9933d30bc6b
