### ISSUE TITLE
Interceptors can't fire at transports landed on water

### ISSUE THREAD

**Issue by HardlySoftly** [FAForever/fa#662]
Is this intended behaviour?

If so then should interceptors be able to fire at transports landed on land?

**Comment by quark036** [comment]
It should probably be consistent

**Comment by shalkya** [comment]
it's kinda part of the gameplay now ^^'
you can rush transport on water map without taking a lot of risk.
not sure if we want to remove it. I heard it was made like that because we allowed torpedo to fire on landed on water transport.

**Comment by ChrisKitching** [comment]
Wouldn't having both make sense?

**Comment by ChrisKitching** [comment]
(It'd be confusing to have weirdly inconsistent rules like this, methinks. Perhaps shitty t1 planes are just incapable of firing at landed targets?)

**Comment by quark036** [comment]
Probably something to ask the forums or the council, considering icedreamer's point about it being part of gameplay now

**Comment by aeoncleanse** [comment]
Last I saw this, I thought it best to ask people what they wanted. Personally I want Inties to be able to shoot them while landed, land and water. Changing this is trivial, and has nothing to do with the landed transport being hit by Torpedoes. - IceDreamer
