### ISSUE TITLE
Need to revert support factory upgrade no-assist fix

### ISSUE THREAD

**Issue by aeoncleanse** [FAForever/fa#665]
too much opposition to this change. A better solution to the upgrade canceling bug needs to be found, possibly as part of #647

**Comment by Sheeo** [comment]
Please document both where to find the 'fix' and where to find the opposition.

**Comment by aeoncleanse** [comment]
Commit bcf7a7cabceadd572bce94385a64001121d2ea1e

opposition here https://github.com/FAForever/fa/issues/640
and in the original issue, which I can't seem to find...
+ aeolus

**Comment by Sheeo** [comment]
So this issue is actually a _duplicate_ of #640. Closing as such.
