### ISSUE TITLE
In game PMs get displayed incorrectly in replay.

### ISSUE THREAD

**Issue by HardlySoftly** [FAForever/fa#667]
Various symptoms, examples include the pm coming up as someone speaking to themselves, the name of the sender not matching the faction+colour logo correctly.

**Comment by quark036** [comment]
Darnit Crotalus I was just working on that. Is it possible to launch a fafreplay via command line?

**Comment by Crotalus** [comment]
Hmm, I still think there's a problem with faction so you could fix that :)

**Comment by Crotalus** [comment]
fafreplays need to go through the lobby due to uncompression so I usually just double-click .fareplay files, someone else maybe have a better idea

**Comment by quark036** [comment]
ok, so how do you launch them to test your modified code?

**Comment by Crotalus** [comment]
Oh good question, this being an UI change so I hooked the file with an UI-mod

(forgot that EcoManager had this change for ages, should have included it into FAF earlier)

**Comment by quark036** [comment]
Ah, that makes sense, thanks!
