### ISSUE TITLE
Clan tag in lobby doesn't show up until you x

### ISSUE THREAD

**Issue by quark036** [FAForever/fa#685]
When you join a game, the clan tag doesn't show up on people in the lobby with you. Once you x in ready, the clan tags show up, and they remain even if you uncheck ready.

**Comment by HardlySoftly** [comment]
Clan tags don't show until you do something to update the UI, e.g moving slots, readying up, changing faction.

Other people joining doesn't load people's clan tags.

This occurs in 3640 and 3641.
