### ISSUE TITLE
Lobby: Exception when closing because of missing UI element pointer

### ISSUE THREAD

**Issue by duk3luk3** [FAForever/fa#686]
When closing the lobby, both in 3641 and 3640, the following exception is triggered:

warning: Error running OnRelease script in <deleted object>: ...ta\faforever\gamedata\lua.nx2\lua\ui\lobby\lobby.lua(517): attempt to call method `AcquireFocus' (a nil value)
         stack traceback:
         	...ta\faforever\gamedata\lua.nx2\lua\ui\lobby\lobby.lua(517): in function `OnClosed'
         	...er\gamedata\lua.nx2\lua\ui\controls\popups\popup.lua(63): in function `Close'
         	...ramdata\faforever\gamedata\lua.nx2\lua\ui\uiutil.lua(775): in function `OnClick'
         	...mdata\faforever\gamedata\lua.nx2\lua\maui\button.lua(135): in function <...mdata\faforever\gamedata\lua.nx2\lua\maui\button.lua:124>

Steps to reproduce:
1. Run FAF Lobby or Faforever.eve
2. Host a game (Launch ingame lobby)
3. Close the game lobby
4. Exception will appear in game.log

I believe it happens because the ```quitDialog.OnClosed``` event doesn't have access to the GUI object.

I don't know how to fix that because I'm not familiar enough with the code to know if there is a way to pass the GUI object into the OnClose handler or if the call should just be removed, but this should be easy enough for someone experienced.

**Comment by aeoncleanse** [comment]
@ChrisKitching  ?
