### ISSUE TITLE
Default settings in-game lobby set to Share until death

### ISSUE THREAD

**Issue by Totaltuna** [FAForever/fa#687]
Default settings share option change: 
From Full Share to Share until Death. 

Small side-note: Maybe move This display a bit up the list so if the option is set wrong people in the lobby will spot it more easily

**Comment by duk3luk3** [comment]
+1

**Comment by aeoncleanse** [comment]
:+1:

**Comment by Totaltuna** [comment]
I HAZ SUBMITTED GUT ISSUE
