### ISSUE TITLE
Quantum Gateways still can't assist one another

### ISSUE THREAD

**Issue by ppipp** [FAForever/fa#688]
Although patch 3641 is supposed to fix this issue, a Quantum Gateway can't assist another one.

**Comment by quark036** [comment]
I don't know if this would affect it, but Quantum Gateways don't have the 'CONSTRUCTION' category on it.

**Comment by quark036** [comment]
Also, I was just testing, and they were able to assist each other.
Soooo....

**Comment by aeoncleanse** [comment]
Yeah they can. Close please.

**Comment by ppipp** [comment]
My bad, now that I try again, it works. Yesterday, I had the possibility to select the assist symbol (normally it's greyed out) but it didn't do anything when actually assisting. I'm sure I was on the patch because cheat menu was not messed up. I don't know what happened.
You can close it indeed.
