### ISSUE TITLE
Mass indicator colour broken

### ISSUE THREAD

**Issue by aeoncleanse** [FAForever/fa#693]
Apparently it used to be green +, yellow - (This is broken), red when stalled.

**Comment by quark036** [comment]
I think it was changed when GAZUI was integrated. Now I think it depends on
the percent of storage left and - or +.

**Comment by aeoncleanse** [comment]
OK so here's where we stand...

Mass: 

Background glows and flashes red the fuller you are. When overflowing, the number flashes.
Negative is green to begin with, turns yellow lower down.
Red when stalling.

Energy:

Background never does the glow or flash red. Number does not flash when overflowing.
Goes yellow immediately on drain, but starts flashing yellow when it gets lower
Red when stalling

Can we have some consistency please?

**Comment by quark036** [comment]
Sure!

**Comment by quark036** [comment]
I have no suggestions though

**Comment by ChrisKitching** [comment]
> Can we have some consistency please?

It makes sense to have different behaviour for the two resources. They behave in roughly opposite ways: wasting mass is bad, wasting energy is less so. Having blinky-white when you're overflowing on energy wouldn't be useful.

Perhaps the way to go is to restore the yellow-when-negative behaviour for both.
