### ISSUE TITLE
3641 Test: Crash when using cybran builders to assist missile preparation for TML & SML

### ISSUE THREAD

**Issue by bamboofats** [FAForever/fa#694]
Encountered a fatal crash when cybran builders (engineers ACU SACU mantis hive) are used to assist any TML or SML missile creation (of any faction),  since the 3641 test patch 26/06/15.

Assisting building the structure is ok, but loading the missiles, the moment the build bots spawn the sim crashes.

**Comment by aeoncleanse** [comment]
Confirmed, it just crashes, nothing in the log at all. It's the floating micro-builders at fault here

**Comment by aeoncleanse** [comment]
The problem is line 48 in the unit script, killing the UpdateConsumptionValues function to stop the eco overlay spam. Removing the line stops this crash, so at least we can undo the change if there's not a better solution out there
