### ISSUE TITLE
Engineers assist loading SMD at cost of building

### ISSUE THREAD

**Issue by Sheeo** [FAForever/fa#697]
Original forum report [here](http://forums.faforever.com/forums/viewtopic.php?f=3&t=9578#p95893)

**Comment by aeoncleanse** [comment]
Old or regression?

**Comment by Sheeo** [comment]
Old

**Comment by duk3luk3** [comment]
I'm grabbing this one.

**Comment by duk3luk3** [comment]
Steps to reproduce:

1. Build SMD with ACU
2. Set engies to assist on SMD, observe normal resource drain
3. Start an ACU upgrade on ACU, observe resource drain equal to build cost for SMD

**Comment by bamboofats** [comment]
I can reproduce this. 
ACU builts the TML, SML, SMD  (if another eng initiates the build I couldnt repro)
Engies assist the ACU, while the ACU assists the missile loading.
So the engies will auto assist the missile loading. normal resource drain
While in progress, start an ACU upgrade. Engies continue to assist the missile loading, but at build cost.

TML SML are affected too.

**Comment by aeoncleanse** [comment]
Sounds like ACU doesn't call UpdateConsumptionValues somewhere along the line, because the Engies are not re-acquiring their focus.

**Comment by duk3luk3** [comment]
Interesting note: With 3641 I can only reproduce it if the engies were assisting the SMD through assist command on the ACU; with 3640 it also works if they are assisting the SMD directly.

That said, I've been looking through the unit code and can't find the part that's responsible for resetting things after a building or enhancement is completed... Can anyone point me in the right direction?

**Comment by duk3luk3** [comment]
I am slowly getting to the bottom of this. When an engy is assisting an ACU and the ACU starts an upgrade, the engy (in UpdateConsumptionValues) thinks it is assisting the ACU upgrade even if it is actually assisting something else (like an SMD).

**Comment by aeoncleanse** [comment]
Are we sure the engies ARE assisting the missile load? Could it be that the fx are still pointed at the silo, but in fact their BP is going correctly to the ACU, hence the higher cost?

**Comment by duk3luk3** [comment]
The focus item is always the SMD.

I am now 99% certain that the bug is in this line: https://github.com/FAForever/fa/blob/release/3641/lua/sim/Unit.lua#L976
It definitely hits the if branch at https://github.com/FAForever/fa/blob/release/3641/lua/sim/Unit.lua#L974

**Comment by Crotalus** [comment]
This originalBuilder stuff has to do with subtracting base-value at upgrades, seems like it wasn't reset after a building completed.

A bit locked up at the moment so haven't really tested it too much

**Comment by duk3luk3** [comment]
I'll pull this in and test it - good to know that's the proper way to fix it. I had no idea originalBuilder wasn't meant to be set there.

**Comment by duk3luk3** [comment]
Something is wrong with your patch (I cherry-picked your commit onto release/3641 branch)

WARNING: Error running OnStartBeingBuilt script in Entity xsb4302 at 1d0b6908: e:\git\fa\lua\sim\unit.lua(1785): attempt to call method `IsState' (a nil value)
         stack traceback:
         	e:\git\fa\lua\sim\unit.lua(1785): in function `OnStartBeingBuilt'
         	e:\git\fa\lua\defaultunits.lua(69): in function <e:\git\fa\lua\defaultunits.lua:68>

Also, related to the code snippet or not related: At the end of this replay: https://dl.dropboxusercontent.com/u/2808338/crotalustest.SCFAReplay

The engy doesn't use any resources when assisting the ACU upgrade (happens after damaging the SMD) but this doesn't happen in a newly started game with just an ACU and an engy so don't know where that comes from.

**Comment by Sheeo** [comment]
@duk3luk3 that would imply the building is being started by something that doesn't have `IsState` (I.e. a non-unit) -- try getting more logging output.

**Comment by Crotalus** [comment]
I had a typo in the first version of the patch, it should be `IsUnitState` not `IsState`
