### ISSUE TITLE
Feature idea: Lobby option to unrank game

### ISSUE THREAD

**Issue by quark036** [FAForever/fa#698]
Currently, people just restrict something like paragon, but there should just be an option to unrank the game.

**Comment by quark036** [comment]
I'll do this.

**Comment by speed2CZ** [comment]
don't do this, its better to have as many rated games as possible to have rating accurate, making easy way to "not lose points" and all games will be unrated again...

**Comment by quark036** [comment]
That's a good point. Can someone close this?
