### ISSUE TITLE
pause doesn't stop missile firing

### ISSUE THREAD

**Issue by aeoncleanse** [FAForever/fa#701]
if it was meant to, fix. if not, we need a way to do this

**Comment by aeoncleanse** [comment]
So I think what we need to do here is enable the attack mode toggle on TMLs, and make it stop Launches.

**Comment by bamboofats** [comment]
Do remember to enable changes to both TMLs and SMLs if successful, as they are quite similar.

I think overall It is important to retain the option to pause inprogress missile construction to stop resource drain, while being able firing off the collection of built missiles.
If pause button adds on to stop missile firing, it will have two functions; pausing firing and pausing construction at the same time. 

Best is to get the attack toggle to work.
I couldnt get the missiles to pause by enabling toggleretaliate and holding fire in game though. Maybe someone can try?

**Comment by quark036** [comment]
Well, can't you already stop missile loading with the toggle auto build missile? So then the pause button should just pause the firing

**Comment by bamboofats** [comment]
The toggle auto build off prevents the subsequent missile from being loaded but it doesnt stop the current one. I was considering the SML for that actually, where the drain is quite high, long build time. Unless microed, unpause-fire-pause, or only implement pause button for TML, not SML. I dont think pressing stop to discard the half-missile is desired.

For TMLs, if the additional resource use just to complete the single missile is deemed acceptable (For that moment when the player wants to stop missile construction drain, yet wants to fire the stockpile), then yes, implement the pause button for TMLs. 

One small issue with autobuild if this is implemented though. If a player did not use it. Instead he/she orders 5 missiles by clicking the button 5 times, toggling autobuild cant stop loading the 5. Have to either pause (cannot fire), or press stop (careful to do it after a fresh missile is loaded or resources would have been wasted)
