### ISSUE TITLE
ACU tactical missiles need to be hit by three TMD attacks to be destroyed

### ISSUE THREAD

**Issue by ChrisKitching** [FAForever/fa#702]
This property of the missiles isn't made clear.

It does perhaps make some sense: the expense of the nuclear one in particular perhaps justifies it being a bit tougher than an ordinary tactical missile, but this probably makes early-game ACU-mounted tactical missiles OP.

Perhaps we want to make the tactical missiles have 1HP like every other tactical missile in the game, and the nuclear one be a special case with 3HP?

This does produce bad user experience: buzzkills are seen shooting at a missile and apparently doing nothing. This routinely gets reported as "buzzkills keep missing shit!".

**Comment by duk3luk3** [comment]
imho ACU TMLs should have 2 HP instead of 3, the billynuke is a gimmick that isn't used much so for balance purposes who cares.

**Comment by quark036** [comment]
I think that the billy should have more hp, but the normal acu tac missiles should just have 1hp (maybe two if people want that). 

The billy change probably wouldn't have much effect, but if you want to change the normal acu tac missiles that'd be balance.

**Comment by Varaxis** [comment]
I propose that missile build time be increased to 30 seconds unassisted with T2 ACU build rate, and also change the script to use the same missile trajectory as standard TML, as to not avoid being shot down from flying so high. The extra cost of the upgrade would still justified by building fast with T3 upgrade and when being assisted, being mobile, and being tough to remove.

I also propose buffing the build time of Sera SCU missiles to 30 seconds unassisted with their base build rate, with similar trajectory change. Currently, their missile build time is far too long, even with Rapid Fab upgrade.

**Comment by Varaxis** [comment]
https://github.com/FAForever/fa/pull/707 - Implementation of my proposal.

**Comment by VoRGoR** [comment]
They are more powerful due to the expense of the upgrade.

I'm ok with changing the hp down to 2hp, but the main problem with them right now is their ability to fly over tmd, and another in the large range. Resolving that first, then looking at this again is best imo.

As for the billy, it's largely useless.

**Comment by Zockyzock** [comment]
taken care of in 3644, closing this
