### ISSUE TITLE
3641 Test: please clamp the number of floating cybran engineer bots

### ISSUE THREAD

**Issue by Divran** [FAForever/fa#704]
Due to the number of bots scaling with the build speed, if you have a mod that increases the build speed, the number of bots quickly add up and rape your FPS. There are several mods that increase build speed, and I don't think any of them are going to be fixed by their authors any time soon, if ever. This is such a simple fix that I think you guy could easily fix it on your end before it even becomes a problem.

**Comment by duk3luk3** [comment]
:+1: Made a PR
