### ISSUE TITLE
3641 Test: if you build a lot of things that take a short time to finish, the cybran engineer bots go EVERYWHERE

### ISSUE THREAD

**Issue by Divran** [FAForever/fa#705]
![untitled](https://cloud.githubusercontent.com/assets/1485728/8397690/a29aec5c-1dd4-11e5-89f1-3bf6477b8cbb.png)

**Comment by duk3luk3** [comment]
Looks like a feature to me ;-)

**Comment by Divran** [comment]
inb4 the enemy finds your cloaked and stealthed base due to the cybran bots flying across the map

**Comment by ChrisKitching** [comment]
The proper fix here may be to just make them turn more sharply

**Comment by aeoncleanse** [comment]
Reduce speed, increase turnrate.

**Comment by ChrisKitching** [comment]
Surely we want the speed to be the same but the acceleration and turning rate to be higher. This problem is caused, I think, by them overshooting the target and having to loop round and come back (like a bomber might behave)

**Comment by aeoncleanse** [comment]
Test dropping speed and upping turnrate first,  simple and it should do the trick

**Comment by ChrisKitching** [comment]
Tweaking the speeds doesn't really fix the problem. The weird behavious is caused by the drones effectively being repeatedly given move orders and having them cancelled in successive ticks.

By adding a check to dampen this behaviour, the drones behave less absurdly from 9332703.

**Comment by ChrisKitching** [comment]
... Gonna call that "done". This is definitely an edgcease anyway: builds that complete in one simtick aren't really a thing.

**Comment by Divran** [comment]
They are when I play (even without mods)
