### ISSUE TITLE
Big crash at main menu on current release/3641

### ISSUE THREAD

**Issue by aeoncleanse** [FAForever/fa#708]
Introduced with this https://github.com/FAForever/fa/commit/e4b0f619c116dffd90b3ea23c9297d2397029d5e

WARNING: e:\github\fa\lua\ui\game\chat.lua(45): Attempt to set attribute 'feed_background' on nil
WARNING: stack traceback:
WARNING:         [C]: in function `error'
WARNING:         ...alliance\gamedata\mohodata.scd\lua\system\config.lua(12): in function <...alliance\gamedata\mohodata.scd\lua\system\config.lua:11>
WARNING:         e:\github\fa\lua\ui\game\chat.lua(45): in main chunk
WARNING:         [C]: in function `doscript'
WARNING:         [C]: in function `pcall'
WARNING:         ...alliance\gamedata\mohodata.scd\lua\system\import.lua(48): in function `import'
WARNING:         ...alliance\gamedata\mohodata.scd\lua\system\import.lua(37): in function `import'
WARNING:         e:\github\fa\lua\ui\game\gamemain.lua(35): in main chunk
WARNING:         [C]: in function `doscript'
WARNING:         [C]: in function `pcall'
WARNING:         ...alliance\gamedata\mohodata.scd\lua\system\import.lua(48): in function `import'
WARNING:         ...alliance\gamedata\mohodata.scd\lua\system\import.lua(37): in function `import'
WARNING:         e:\github\fa\lua\ui\menus\main.lua(54): in function `CreateUI'
WARNING:         ...r forged alliance\gamedata\lua.scd\lua\ui\uimain.lua(59): in function <...r forged alliance\gamedata\lua.scd\lua\ui\uimain.lua:46>
WARNING:         [C]: in function `EngineStartFrontEndUI'
WARNING:         ...d alliance\gamedata\lua.scd\lua\ui\splash\splash.lua(51): in function <...d alliance\gamedata\lua.scd\lua\ui\splash\splash.lua:48>
WARNING:         ...d alliance\gamedata\lua.scd\lua\ui\splash\splash.lua(68): in function <...d alliance\gamedata\lua.scd\lua\ui\splash\splash.lua:55>
WARNING: ...alliance\gamedata\mohodata.scd\lua\system\import.lua(37): Error importing '/lua/ui/game/chat.lua'
WARNING: stack traceback:
WARNING:         [C]: in function `error'
WARNING:         ...alliance\gamedata\mohodata.scd\lua\system\import.lua(52): in function `import'
WARNING:         ...alliance\gamedata\mohodata.scd\lua\system\import.lua(37): in function `import'
WARNING:         e:\github\fa\lua\ui\game\gamemain.lua(35): in main chunk
WARNING:         [C]: in function `doscript'
WARNING:         [C]: in function `pcall'
WARNING:         ...alliance\gamedata\mohodata.scd\lua\system\import.lua(48): in function `import'
WARNING:         ...alliance\gamedata\mohodata.scd\lua\system\import.lua(37): in function `import'
WARNING:         e:\github\fa\lua\ui\menus\main.lua(54): in function `CreateUI'
WARNING:         ...r forged alliance\gamedata\lua.scd\lua\ui\uimain.lua(59): in function <...r forged alliance\gamedata\lua.scd\lua\ui\uimain.lua:46>
WARNING:         [C]: in function `EngineStartFrontEndUI'
WARNING:         ...d alliance\gamedata\lua.scd\lua\ui\splash\splash.lua(51): in function <...d alliance\gamedata\lua.scd\lua\ui\splash\splash.lua:48>
WARNING:         ...d alliance\gamedata\lua.scd\lua\ui\splash\splash.lua(68): in function <...d alliance\gamedata\lua.scd\lua\ui\splash\splash.lua:55>
WARNING: Error running '/lua/ui/uimain.lua:StartFrontEndUI': ...alliance\gamedata\mohodata.scd\lua\system\import.lua(37): Error importing '/lua/ui/game/gamemain.lua'
         stack traceback:
         	[C]: in function `error'
         	...alliance\gamedata\mohodata.scd\lua\system\import.lua(52): in function `import'
         	...alliance\gamedata\mohodata.scd\lua\system\import.lua(37): in function `import'
         	e:\github\fa\lua\ui\menus\main.lua(54): in function `CreateUI'
         	...r forged alliance\gamedata\lua.scd\lua\ui\uimain.lua(59): in function <...r forged alliance\gamedata\lua.scd\lua\ui\uimain.lua:46>
         	[C]: in function `EngineStartFrontEndUI'
         	...d alliance\gamedata\lua.scd\lua\ui\splash\splash.lua(51): in function <...d alliance\gamedata\lua.scd\lua\ui\splash\splash.lua:48>
         	...d alliance\gamedata\lua.scd\lua\ui\splash\splash.lua(68): in function <...d alliance\gamedata\lua.scd\lua\ui\splash\splash.lua:55>

**Comment by Sheeo** [comment]
Please include the entire game log

**Comment by aeoncleanse** [comment]
http://pastebin.com/1e6pzNC8
