### ISSUE TITLE
Minor inconsistency in UEF kennel "radar effect"

### ISSUE THREAD

**Issue by bamboofats** [FAForever/fa#709]
![uefeng](https://cloud.githubusercontent.com/assets/13047748/8414201/d818e7cc-1ec8-11e5-8bbd-239abbaa3c8f.jpg)

The UEF engineering station: 
Stage one has a radar effect, while stage two does not. 
However, I cant think of any gameplay reason to suggest why the lower tiered station would have the effect instead of the larger one. Should probably remove the effect from stage 1 as the stations only have vision as intel, no radar. 
If not at least make them both have it for consistency

XEB0104_unit.bp   vs   XEB0204_unit.bp

The stage one kennel  0104  has this idle effects lines, while the 0204 does not.

        IdleEffects = {
            Land = {
                Effects = {
                    {
                        Bones = {
                            'B04_Tower',
                        },
                        Type = 'Radar01',
                    },
                },
            },
        },

**Comment by aeoncleanse** [comment]
I'm gonna make this happen, I like the idea of having a radio control visual :)
