### ISSUE TITLE
Reclaim status can be discerned without scouting

### ISSUE THREAD

**Issue by HardlySoftly** [FAForever/fa#712]
"Reclaim status" meaning whether or not it is still there.

Reclaim orders on wrecks that have been reclaimed since you last scouted do not snap to supposed reclaim location.

Reclaim orders on wrecks that have not been reclaimed/destroyed do snap to the reclaim location.

This means you can tell if it is still there or has otherwise been removed from the map.

**Comment by Crotalus** [comment]
Yep, seems like the recon system is bugged for props. Another problem is that you instantly see if a unit dies and turns into a wreck.

The alternative we have at the moment is to set them to 'Intel' visibility but then they don't get "permanent visible" when outside visiblility range which feels odd.

**Comment by ChrisKitching** [comment]
GPG left a comment about this, in the routine that create wreckage props:

    --FIXME: SetVizToNeurals('Intel') is correct here, so you can't see enemy wreckage appearing
    -- under the fog. However the engine has a bug with prop intel that makes the wreckage
    -- never appear at all, even when you drive up to it, so this is disabled for now.

**Comment by ChrisKitching** [comment]
... Props don't have OnSpotted.

Well, shit.

**Comment by NyxVxyN** [comment]
Would be good if it was possible to make it so that it only shows reclaim and wrecks inside FOW range or makes those outside invisible.

**Comment by Garanas** [comment]
We're so used to the status quo - closing this issue.
