### ISSUE TITLE
SACU rebuild hives through assist has model glitch

### ISSUE THREAD

**Issue by bamboofats** [FAForever/fa#713]
This is an issue based on https://github.com/FAForever/fa/issues/553
Where SACUs can rebuild structures (even those not directly buildable) by actively assisting the structure just before it dies.
While the sACU rebuild behaviour may be a whole new challenge to solve, I opened a new issue because I may have found some kind of fix for one of the derivative glitches.

![oldrebuild](https://cloud.githubusercontent.com/assets/13047748/8424803/bb1f9c7e-1f31-11e5-89a0-fd73ee6d54c3.jpg)
When sACUs rebuild upgraded stage 2 or 3 hives, the resulting structure is glitched out. This is because the stage 2 and 3 hives were never meant to be directly builable, only as an upgrade. If I were to set the flags for the stage 2 and 3 hives to be builable eg'BUILTBYTIER2ENGINEER', placing the structure gives this model glitch as well. 

When upgrading, eg stage 1 to stage 2, stage 2 is spawned, but relevant bones hidden so only the new portion is shown under construction. After it is done, stage 1 is deleted while stage 2 somehow readjusts to have all the bones shown. However, if stage 2 was directly built, it is created with some bones hidden as in the upgrade state. So the result is a boolean B - A kinda thing.

I found a potential fix, in  XRB0204_script.lua  and  XRB0304_script.lua
I deleted this portion from both files  
        self:HideBone('xrb0304', true)
        self:ShowBone('TurretT2', true)
        self:ShowBone('Door2_B02', true)
        self:ShowBone('B02', true)
        self:ShowBone('Attachpoint02', true)
So the model does not hide bones at any time. Building/rebuilding looks correct.
![newrebuild](https://cloud.githubusercontent.com/assets/13047748/8425025/41456304-1f34-11e5-9860-a5c88b43486d.jpg)

However, the tradeoff with this method is that the in progress upgrade appears differently. The whole model is placed for the upgrading electric visuals, including the bottom portion.
Old visuals
![oldupgrad](https://cloud.githubusercontent.com/assets/13047748/8425045/6b274b88-1f34-11e5-8f63-4115f647c624.jpg)

New visuals after so called "fix"
![newupgrade](https://cloud.githubusercontent.com/assets/13047748/8425051/744bc388-1f34-11e5-9d1f-fdc8d42c1b39.jpg)

**Comment by duk3luk3** [comment]
I think the consensus among the dev team is currently that the REBUILDER behaviour flag is just bugged and should be removed and reimplemented in Lua; rebuilding structures that aren't buildable is a bug.

**Comment by ChrisKitching** [comment]
While that's true, we're probably not doing something so drastic for 3641 (that seems a fairly big change).

A more sensibly-sized thing we can fix prettymuch straight away is to make the costs right. This can probably be done as part of a more holistic unfucking of the consumption/costs system, so is well worth doing nowish.

So, yes, let's fix this, but also preserve the bone hiding behaviour. Thanks for the highly detailed report!

**Comment by ChrisKitching** [comment]
There seems to be existing logic that subtracts the build cost of the earlier version of a unit from the cost of the upgraded unit when doing an upgrade.

That seems to be the way to go: We insist that the blueprint cost for every upgraded unit be the "complete" cost of it, and the incremental upgrade cost is this subtract the cost of the un-upgraded version. That will naturally fix the REBUILDER cost bug.
