### ISSUE TITLE
ACU incorrectly displays mass+energy spend

### ISSUE THREAD

**Issue by HardlySoftly** [FAForever/fa#717]
Symptom: ACU economy always shows default value (or increased if it has ras upgrade)

This means it doesn't display as using mass/energy when you build something.

To reproduce:  Use acu overcharge.  This causes the bug.

**Comment by ChrisKitching** [comment]
https://www.dropbox.com/s/hg0n00jpoimy8n4/Screenshot%202015-07-03%2012.55.17.png?dl=0

Works for me.

**Comment by HardlySoftly** [comment]
I should say: once you have overcharged, the bug will be apparent whenever you try to build something.

**Comment by ChrisKitching** [comment]
Ah, now I can reproduce it.

... Holy shit, the consumption system is fucked beyond belief.

**Comment by aeoncleanse** [comment]
Yeah, it's no wonder we keep running into shit with it :(

**Comment by Crotalus** [comment]
Seems like info.massRequested / info.energyRequested is reported as 0 after the ACU has overcharged, even if massConsumed / energyConsumed > 0 when it's building something.

Maybe a problem with CreateEconomyEvent() or a specific with overcharge, needs to be investigated.

**Comment by aeoncleanse** [comment]
Did this go anywhere?
