### ISSUE TITLE
The origin bone name does not always match the unit ID

### ISSUE THREAD

**Issue by ChrisKitching** [FAForever/fa#719]
In particular, the xrb0104 and xrb0204 have this property. It's annoying, and something which is assumed to hold generally in a few other places.

We can add it to the rapidly growing list of "shit we could easily fix if we had someone who could edit models"

**Comment by bamboofats** [comment]
I tried my hand at blender + the supcom plugin. I edited the bone names (which is all im capable of now), but Im not sure I didnt export a complete rubbish model file. The size is about 80% of the original so Im a bit suspect.
I corrected for LOD0, LOD1 (the low q version) is named correctly after the ID. An initial test in FA shows it didnt crash the game and renders correctly so thats a relief.

Chris, maybe you could try these files to see if the new bone reference works. And that there isnt anything broken.

https://www.dropbox.com/s/56xr04tpv3sot2m/XRB0104_lod0.scm?dl=0

https://www.dropbox.com/s/s01ur1pvykfwsod/XRB0204_lod0.scm?dl=0

**Comment by bamboofats** [comment]
I had some success modifiying the bones of torp defense, shifting the targeting ones to absurd locations and getting other units to fire at them. Gravity bombs and torpedoes still land squarely on the hitbox. I might be able to assist if my model exports are tested to be working correctly.

**Comment by ChrisKitching** [comment]
> I had some success modifiying the bones of torp defense, shifting the targeting ones to absurd locations and getting other units to fire at them. Gravity bombs and torpedoes still land squarely on the hitbox. I might be able to assist if my model exports are tested to be working correctly.

They are. These test models work.

This is fantastic news. Are you on Slack? We can work more closely there to sort out the backlog of model problems, if you like.

**Comment by ChrisKitching** [comment]
To be specific about the torpedo defense problem:

Each unit blueprint defines a list of "target bones". An attacker will try and aim its weapons at each bone on this list in the given order, and open fire as soon as it finds one it can use.
A bone can be used if it's on a layer that the weapon can fire in (so it has to be underwater for torpedoes, for example), and if there's a line of sight to the bone from the weapon.

The problem with the torpedo defense is that it has no bones *at all* above the water line. Surface weapons therefore fail to acquire any target bone, and fallback to the default behaviour of shooting at a top corner of the bounding volume of the unit: hence why stuff misses so much.

So: All you need to do is either create a new bone above the water line in roughly the middle of the mass (a sensible place to aim a surface gun at), and then I'll add that one to the target bone list in the blueprint (or you can, of course).
Alternatively, you can just move the existing origin bone up into an appropriate place.

This problem exists for a number of torpedo launchers/sonar platforms. I'll furnish an exhaustive list in a moment.

**Comment by ChrisKitching** [comment]
Oh wait, IceDreamer did it already here:
https://github.com/FAForever/fa/issues/651

**Comment by bamboofats** [comment]
Ive never heard of that o_o, But i can join in if needed.   But do point me to where I can get more info on the problem lists. Im quite free these few days so I can try out. Its night here Ill check back in sometime saturday

**Comment by ChrisKitching** [comment]
The ones I can find quickly are #651 and #723 (which has apparently been floating about in my head for  a while without ever making it into the issue tracker.)

**Comment by ChrisKitching** [comment]
This one is also relevant to your interests:
https://github.com/FAForever/fa/issues/79


You might like to ask Sheeo about Slack. It's an IM system type thing we use to keep in touch with lower latency than GitHub.

**Comment by bamboofats** [comment]
Alright Ill have a look at those issues. Might I ask, for a bone to be considered above water, any positive Z value for the bone is considered acceptable? eg  +0.5  or whatever scale the model uses.

**Comment by ChrisKitching** [comment]
Any positive value, but not zero, yes. Ideally fairly central, I think, though not quite sure how that might interact with bombers.

**Comment by bamboofats** [comment]
One more thing. The model files has two LODs, hi LOD0 and lo LOD1. 
Is it sufficient that I only modify LOD0?      My initial random testing, modifying LOD1 did not appear to affect targetting. And LOD1 for some units dont even have the full set of bones, or are named differently from the blueprint targetting bones. So I can just leave that out?

**Comment by ChrisKitching** [comment]
> One more thing. The model files has two LODs, hi LOD0 and lo LOD1. 
> Is it sufficient that I only modify LOD0? My initial random testing, modifying LOD1 did not appear to affect targetting. And LOD1 for some units dont even have the full set of bones, or are named differently from the blueprint targetting bones, with _lod1 suffix. So I can just leave that out?

AFAIK, one model is swapped out for the other as you zoom out. One is basically an ultra crappy low-poly version of the other one that is used when you are zoomed out a long way.

I have absolutely no idea what happens if you do something funky here. I guess try it and see?
You might like to get yourself a working test environment set up.

**Comment by MrRowey** [comment]
@Garanas this could be closed off

**Comment by Garanas** [comment]
Is the issue solved though?

**Comment by MrRowey** [comment]
Oh sad the models were provided and seemed to have been fix for the issues but the field was never implemented into faf and not they are no longer available this need a Moder to fix still for the XRB0104 & xrb0204 

![image](https://user-images.githubusercontent.com/20344151/141205459-85638176-5970-4b06-8d9b-73b81cf5a263.png)
![image](https://user-images.githubusercontent.com/20344151/141205502-2e883509-9c9d-471c-a493-6dc53376657f.png)

![image](https://user-images.githubusercontent.com/20344151/141205634-b22f6c27-e5e3-40ae-9fc1-8afe454c6f3d.png)
![image](https://user-images.githubusercontent.com/20344151/141205675-fa32738e-7006-49b2-bdea-03eaabeb2a2e.png)

**Comment by Garanas** [comment]
What should the modeler do exactly - just remove the _lod1 and _lod0 parts of the root bone?

**Comment by ChrisKitching** [comment]
If memory serves, the issue was that the native code which decides how to target missiles/torpedos would by default select the bone with the name equal to the unit ID.

If that bone does not exist, it would pick the corner of the unit's bounding box nearest the origin, which frequently caused things to miss. At the time, this was causing weapons to very consistently miss some units (notably various torpedo platforms).

So yeah: pretty sure all you gotta do is rename it. Someone might have implemented a horrible Lua-side hack to fix the problem in the meantime, however...

I suggest that you open up the model for a random unit that isn't one of the identified problem units and exactly copy the naming convention used there (in terms of when to include `_lodX` in names and whatnot).
