### ISSUE TITLE
A 1x2 map border model is required

### ISSUE THREAD

**Issue by ChrisKitching** [FAForever/fa#723]
Maps come in three aspect ratios: 1x1, 1x2, and 2x1.

When rendering the map border (the fancy 3D model around the map), the game loads a map border of the appropriate aspect ratio, scales it preserving ratio to the width of the map, and applies it.
Alas, there is no 1x2 map border, so tall maps would previously be given the 1x1 and overlap hideously.

The hideous overlap was mitigated with e4837aaa0bf472f8676928881af38e7c947b5d2e, but at the expense of tall maps getting no pretty map border at all.

Someone needs to make a 1x2 map border (which would presumably be a relatively trivial scaling job given the existing 2x1 and 1x1 ones).
We, alas, cannot fix how painfully stupid the method the game uses to do this is: all we can do is put in the asset they forgot to include ;)

The 1x1 meshes can be found at `meshes/game/map-border_squ*`, and the 2x1 at `meshes/game/map-border_hor*`

**Comment by bamboofats** [comment]
I'll try this after I sort out the torps

**Comment by MutantGenepool** [comment]
Yes it would and yes it would. What then is need to do, is turn the UV map 90 deg. Rename the mesh in the Blender Outliner to map-border_vert_sera_lod0. Export the .scm file. Then copy and rename the .dds files. Change "map-border_hor_sera_normalsTS.dds" to "map-border_vert_sera_normalsTS.dds and ofc any other files associated with the model. No need to rotate the .dds files.
But, I'll do this np. I just put this up so you know.

**Comment by ChrisKitching** [comment]
Get cracking, then :)

**Comment by MutantGenepool** [comment]
I can't open the UEF hor file. Blender keeps crashing. Can someone send me a file in .obj?
Also, is there another file that needs to be adjusted other than the skin file?

**Comment by ChrisKitching** [comment]
We have no files you don't, unfortunately.

This is very much not my area: I guess you're on your own. Fixing only a few of the factions is still of nonzero use.

**Comment by MutantGenepool** [comment]
(MutantGenepool) Quote; What then is need to do, is turn the UV map 90 deg. Wrong. Do not rotate the UV Map.

**Comment by MutantGenepool** [comment]
How do I upload the folder?

**Comment by ChrisKitching** [comment]
> How do I upload the folder?

Pull request or if you can't git, stick it on Dropbox or such.



> Also, I did a test on removing doubles in the game folder. Ping, Attack Ping, Move etc and they work just fine. If you want me to continue removing doubles, please let me know.

"Doubles"?
This is your poly-reduction idea?

**Comment by MutantGenepool** [comment]
It does not reduce polys. The game engine renders vertices first then polys for the GPU to render materials. If the engine has to render more vertices than is necessary, it takes up memory and lags the game.
Some light reading if interested. http://wiki.polycount.com/wiki/Polygon_Count

**Comment by ChrisKitching** [comment]
Sounds good, as long as it doesn't negatively impact appearance I'm happy to approve it.

**Comment by MutantGenepool** [comment]
YT video of a test after vertices reduction in the game file. Looks like no problems.
https://www.youtube.com/watch?v=g0gB8Q2y3Fw

Will do more testing with units file.

**Comment by MutantGenepool** [comment]
Dropbox link; https://www.dropbox.com/s/9zcmxflr1svfoym/1x2_Borders.zip?dl=0

**Comment by bamboofats** [comment]
You could upload the move/ping icons you did first.!

For the units, if it is successful I think it would be better to roll them out in a patch all at once instead of incremental. But there are a lot of units to do, and each has two LOD model files. It will take quite some time.

You mind creating a vertex reduction for the GC just for me? UAL0401  LOD0,  one file
I would like to test out the performance gain first hand

**Comment by bamboofats** [comment]
I tried it out myself. Not sure whats the best way to do the vertex reduction, but i used the blender function "remove doubles" for the mesh, using the default settings. Import->select mesh->remove doubles->export.   Do correct me if it is inadequate.

For the GC, it has 7840 vertices. Remove doubles reports about 3600 removed. However, after exporting and reimporting to check, the model has 7690 vertices. Im not sure if its the scm plugin has something to do with this, but it might turn out to be just 2% of the vertices removed. 

More surprisingly, the model with "removed doubles" had lower performance in game.
![gcmess](https://cloud.githubusercontent.com/assets/13047748/8539520/460bc29a-24af-11e5-9cce-130e8d2bc8a6.jpg)

With 500 GC spawned, separated and not dancing about, The edited mesh model gives 46fps. The original GPG model gives 49fps. I tried this 3 times each and the fps reported is very stable.

Again, if I am doing anything wrong please correct me.

**Comment by MutantGenepool** [comment]
OK. I didn't think to re-import the meshes. It looks like the .scm format separates the mesh by UV seams. I'm going to have to redo the seams and texture maps by baking them first.
I'll do the GC.

**Comment by MutantGenepool** [comment]
Well. I give up on the vertex reduction. Can't make it work using scm format.

**Comment by bamboofats** [comment]
Thanks for the attempt though.
For the remaining 1x2 models, we cant open the UEF or cybran ones possibly due to the size.
Either someone manages to sort out the import script, or try the alternative plugin with 3dmax. If not looks like it'll be stuck here for now.

**Comment by bamboofats** [comment]
The cheap alternative would be to use the rotated Aeon border for UEF and cybran, but changing the dds colours to blue or red. If this beats not having a map border at all.

**Comment by MutantGenepool** [comment]
Cybran 1x2 border. Hope it works in the game. I re-imported the mesh into Blender and it seems to. 
https://www.dropbox.com/s/2b0bqeirrjfmwun/Cybran_1x2.zip?dl=0

Too bad we can't use .fbx format for the meshes.

**Comment by MutantGenepool** [comment]
I took a big risk with my imagination and created a UEF 1x2 border. Any changes small or large needed. Please advise. :+1: 
https://www.dropbox.com/s/85cvyqvv9wxg1wv/UEF_1x2.zip?dl=0

**Comment by bamboofats** [comment]
Oh that might be a smart way using the other cybran model file. I believe the game uses the "cybran" one, which is the big file with brick textures that we cant open.
You used the "cybran_a" one and scaled to 1x2. So I think that the textures to go along are the "cybran_a" ones previously from the 1x1 set, which is a red gradient kinda thing.  The one you included is the brick textures from "cybran". This is just my thoughts, i didnt preview the mapping or test in game.

Just one issue with the mesh, which comes from the original unscaled GPG one.
![cybran](https://cloud.githubusercontent.com/assets/13047748/8585295/b3aea088-2612-11e5-88bd-b95b550fbb97.jpg)
One of the sides has this intersecting triangle. Not sure if it will cause any glitchy looking stuff ingame. If it does are you able to fix this? Delete the triangle or reorder it?

I cant give much feedback for the UEF one as I cant preview the final result, but its quite cool that youre able to do that. Roughly fits with the microchip theme of the original. But i noticed that the scale is much smaller? then the others. Is it necessary to match the same size of the inner rectangle with the other 1x2s?

**Comment by MutantGenepool** [comment]
"You used the "cybran_a" one and scaled to 1x2. So I think that the textures to go along are the "cybran_a" ones previously from the 1x1 set, which is a red gradient kinda thing. The one you included is the brick textures from "cybran". This is just my thoughts, i didnt preview the mapping or test in game." OK Just copy/paste and change the cybran from hor_ to vert_ . I'll make a cybran_vert background mesh for the cybran_a_vert mesh.

Good spotting on the mesh. :+1: 
I'll re-size the UEF mesh as well. Forgot to re-size it. I had to reduce the size 'coz of camera clipping.

**Comment by bamboofats** [comment]
I think you could adjust the camera by going  view->properties->Clip:End  raise it to 10000 or something. It worked for me

**Comment by MutantGenepool** [comment]
Cybran 1x2 folder. https://www.dropbox.com/s/2b0bqeirrjfmwun/Cybran_1x2.zip?dl=0

**Comment by bamboofats** [comment]
Good work. I stuck in the 1x2 border manually for testing. Though I couldnt find a 1x2map (i only got squares), i think you can get the feel from this. Bloom on
![untitled-1](https://cloud.githubusercontent.com/assets/13047748/8590351/5812e514-2652-11e5-8ab3-2a0e94f44a0f.jpg)
I think this one is much too distracting. Too much white glow over red. Maybe a colour similar to the ui but a tad darker might be better. I see if i can edit the dds to get something different.

**Comment by MutantGenepool** [comment]
Red River is a 1x2 map.
I think faction_ and faction_a should load at the same time. Not sure. Just what I thought. Looking at the sera_ and sera_a meshes you'd think so as they fit together.
Re-uploaded the 1x2's as there was a couple of things needed fixing.
https://www.dropbox.com/s/2b0bqeirrjfmwun/Cybran_1x2.zip?dl=0

**Comment by MutantGenepool** [comment]
How do you get them to load? I can test them before sending them to you. Save you time.

**Comment by ChrisKitching** [comment]
Make sure you get the depth right, or you'll overlap the map.

This reminds me: On some maps, the map border interferes with the lowpoint.
Check out the map "Balmy" and try it with a variety of different factional map borders. Look at the bottom of the ponds.
Some of the map borders actually come up underneath the map and interact with the bottom of the ponds.

You could fix that while you're at it ;)

**Comment by MutantGenepool** [comment]
OK. Take a look at these. Redid the UEF as well.
https://www.dropbox.com/s/9zcmxflr1svfoym/1x2_Borders.zip?dl=0
https://www.dropbox.com/s/2b0bqeirrjfmwun/Cybran_1x2.zip?dl=0
https://www.dropbox.com/s/85cvyqvv9wxg1wv/UEF_1x2.zip?dl=0

Has the code been done in the 3641 patch so I can test these myself?

**Comment by ChrisKitching** [comment]
You can play with them on this branch:
https://github.com/FAForever/fa/tree/2x1

Unfortunately, they are not scaled correctly yet:
https://www.dropbox.com/s/5o7vvjv3sg1h92h/Screenshot%202015-07-10%2003.40.33.png?dl=0

**Comment by bamboofats** [comment]
I tested them by loading into programdata(win7)/faforever/gamedata/meshes 
By renaming the nx2 to zip, put them in, them rename back to nx2.
Then run a standalone game by using faforever/bin  forgedalliance.exe  
Though there might be a more efficient way,  i mainly use this.

The original cybran one GPG uses for FA is a single model  "cybran" only.  
The 2 meshes for the 1x2 you put out are completely different, and as what you suggested. might want to load together. cybran and cybran_a
Youll could edit the skins.lua   lua/skins/skins.lua

 cybran = {
        default = "default",
        texturesPath = "/textures/ui/cybran",
        imagerMesh = "/meshes/game/map-border_squ_cybran_mesh",
        imagerMeshHorz = "/meshes/game/map-border_hor_cybran_mesh",
        imagerMeshVert = "/meshes/game/map-border_vert_cybran_mesh",

to add extra
        imagerMeshDetailsVert = "/meshes/game/map-border_vert_cybran_a_mesh",
just for vert, following the aeon or sera example.
I believe this will load the other one to go with it.

Im quite sure the textures need a bit editing and fitting though, probably left in a halfassed state as GPG went for the other border for cybran.

**Comment by MutantGenepool** [comment]
Well I'm not getting any vert borders up. I copied the meshes and lua folders and put them in the ProgramData/FAForever/gamedata folder and changed from .zip to .nx2. Nudda!
Anyway, I combined the two cybran borders and made a dds albido.

**Comment by Sheeo** [comment]
@bamboofats you should take the time to setup an init file that'll launch the game with a clone of this repo as a baseline: https://github.com/FAForever/fa#setting-up-a-development-init-file

**Comment by bamboofats** [comment]
that 'll be useful. Im usually testing the game version a few days behind actual progress. thanks

**Comment by MutantGenepool** [comment]
This is all the code regarding that patch in my uiutil.lua file.
--* skin control, sets the current skin table
function SetCurrentSkin(skin)
    local skins = import('/lua/skins/skins.lua').skins
    
    if skins[skin] == nil then
        skin = 'uef'
    end

Shall I include the patch code into the file?
plus

    elseif mapHeight == mapWidth * 2 then
-- Vertical maps
                     MapBorderAdd(skins[skin].imagerMeshVert)
                     if skins[skin].imagerMeshDetailsVert then
                         MapBorderAdd(skins[skin].imagerMeshDetailsVert)
                     end

**Comment by ChrisKitching** [comment]
The changes to skins.lua in this commit show you everything that needs changing code-side, as far as I know:
https://github.com/FAForever/fa/commit/48c747fa3b62c8f4ec542dcb8221315fe6b98bbd

You might want to talk to @aeoncleanse about the proper settings to use for exporting dds images, though his experience is for the UI-side stuff: the requirements for textures actually used on models may be different.

**Comment by MutantGenepool** [comment]
New UEF vert map.
https://www.dropbox.com/s/85cvyqvv9wxg1wv/UEF_1x2.zip?dl=0

Every time I change something in the program side, it breaks, so I'm not doing it. Modeling for me only.

**Comment by ChrisKitching** [comment]
> Every time I change something in the program side, it breaks, so I'm not doing it. Modeling for me only.

I literally gave you the code change you need:
https://github.com/FAForever/fa/commit/48c747fa3b62c8f4ec542dcb8221315fe6b98bbd

Cherry-pick the changes to skins.lua from this commit and you're golden (the only extra guff in that commit is your models and blueprints, which should be familiar)

**Comment by MrRowey** [comment]
@Garanas I don't see the need for this. if you can see a need keep it open if not I think it could be closed

**Comment by Garanas** [comment]
With the Ozonex editor only supporting square maps the chances of seeing a non-square map (without shrinking the playable area) is nil. The only other person but me would've been biass - as we're the last that use the GPG editor.
