### ISSUE TITLE
Mass/Energy overflow

### ISSUE THREAD

**Issue by aeoncleanse** [FAForever/fa#725]
Zock would like the first balance patch to be small and fast, and this is one of the few things he'd like to be in it. I know @Crotalus has done some work on this, may have what Zock wants because I'm not 100% sure.

**Comment by Zockyzock** [comment]
Hi,

We want to integrate the part of ecomod that prevents resources to get wasted if they get sent to a teammate that has already full storage by sending them to other teammates instead. 

Maybe we also want to integrate the part of ecomod that you can share resources before you storage is full, but that is not decided yet.

**Comment by Crotalus** [comment]
We must take the default overflow behavior into account  and handle this sim side, so current ecomod implementation is of no use.

I was messing around with this earlier but then got stuck with some ugliness with storage, if someone has full energy storage but -500 drain and you "boost" him 500 energy same tick the storage will still go down 500 next tick. A player need to have storage available to be able to get the boost.

A nicer solution would be to add the actual overflow as income to a player (via a structure / unit) when there is team overflow. For instance, if the team overflows +100 mass and +500 energy to you, your acu gets this extra income that tick. This way it works better with the eco system. 

We also need to calculate the normal overflow a player gets or disable that system completely so we don't give away free resources.

**Comment by Crotalus** [comment]
Hmmm, has anyone really verified that the overflow system is bugged? I did a quick test and power from a T3 Power gen is distributed across the rest of the team as expected. If a player has full storage and only uses a fraction of the overflow the other players in team get the rest instead.

**Comment by aeoncleanse** [comment]
Yeah, AFAIK the default overflow system in the game works absolutely fine. No clue why we even needed this ecoshare mod anyway.

**Comment by ChrisKitching** [comment]
> Hmmm, has anyone really verified that the overflow system is bugged?

I thought you wrote an "eco share" mod at some point? Wasn't this the first thing you did ;)

> Yeah, AFAIK the default overflow system in the game works absolutely fine. No clue why we even needed this ecoshare mod anyway.

I think the specific claim is that overflow is divided evenly among the team, even if some of the team have full storage (so that portion of the overflow is wasted, instead of being given to someone else who might need it)

**Comment by Varaxis** [comment]
I was testing a cheat map with ridiculous reclaim and used the opportunity to check out overflow, and mass overflow seems to work as expected. One engineer (no ACU) set to build over a stack of rocks sending +50 mass over to all other teammates, split evenly. If one other teammate is full, he overflows his overfull share evenly among others. The income reports on other plays seems to reflect that properly.

**Comment by aeoncleanse** [comment]
So GPG did something right at last lol.  Excellent!

**Comment by Sheeo** [comment]
@Varaxis I hope it's not too much to ask -- but do you have a replay for verification?

**Comment by Crotalus** [comment]
> I thought you wrote an "eco share" mod at some point? Wasn't this the first thing you did ;)

Yeah but the main reason for the autoshare stuff was to let teammates get unused resources from storage, the actual "this overrides the overflow bug" was a later discovery. Maybe that bug is a FAF urban legend.

**Comment by aeoncleanse** [comment]
According to 3644 changelog etc, this is not an issue which ever existed. Close please! :)
