### ISSUE TITLE
Fix transport dropping beetle directly on the acu

### ISSUE THREAD

**Issue by Zockyzock** [FAForever/fa#730]
Problem: Transports can drop beetles directly on the head of an ACU, there is no chance to kill the beetles.

Is it possible to prevent this?

**Comment by aeoncleanse** [comment]
I'll see about making Beetles have to be on land to detonate their weapon. There's no circumstance where they should det without being on land right?

**Comment by Exotic-Retard** [comment]
afaik this also has to do with how beetles are moving before the land/dropoff animation fully plays - if you do a beetle drop correctly (queue attack before loading) then this .. issue/thing/phenomenon happens, making it seem like they are teleporting. this is also how you don't have to drop exactly on the acu for an instant kill

removing this behavior could help solve the issue but i don't know if its possible, and it might create other problems with path-finding, beetles are fussy enough already with their movement. (things like in-built formations/group moves and large targets cause problems)

ideally i would like to see beetles with improved handling, and have them changed in other ways to avoid/reduce the super annoying beetle snipe.

hope this helps.
