### ISSUE TITLE
Make mass storages "snap to grid" like mass extractors do 

### ISSUE THREAD

**Issue by Zockyzock** [FAForever/fa#731]
Guess it'll be complicated to do with all the different templates, and single storage, but i hope its possible and would be great to have this for 3642. 

Important would be to only "snap" them, when your cursor is close to a mex, to keep it possible to place storages elsewhere.

**Comment by ChrisKitching** [comment]
Mouse interactions with the worldview are handled by native code.

The degree to which we can control this is highly limited: there's a blueprint flag that causes buildings to snap to mass/hydrocarbon points when they exist in an active build template.

Probably the closest we can do is to synthesize a no-op unit that snaps to mass extractors and intelligently place it inside suitable arrangements of storage units at template-activation time.

**Comment by Exotic-Retard** [comment]
if its possible you could have mexes snap to mass points that are already occupied, meaning that a template with a t1 mex in the middle of 4 storages should still snap to the mex.
maybe not completely ideal behavior but this template is already used by some and imo this is just as good.

**Comment by aeoncleanse** [comment]
Well, it would be nice if at least we could get templates which include a mex to snap to even an empty point. They currently don't.

**Comment by Exotic-Retard** [comment]
if it helps at all, i discovered that this is an only template thing - just mexes already snap to spots that are occupied while templates snap to nothing at all it seems (same for hydros btw)

**Comment by HUSSAR-mtrela** [comment]
An alternative/easier way of implementing this feature is to add an option to already built mex that would spawn 4 mass storages in similar way higher tech level mex is placed when mex upgrade is initialized.

**Comment by Crotalus** [comment]
Yup, made a mod that worked liked this, should be in the mod vault. It added the ability for mexes to build their own mass storages.

**Comment by aeoncleanse** [comment]
We have to require an Engineer at the site. A major play aspect is killing off expanding Engineers on their way to cap mexes, don't want to remove that.

**Comment by Crotalus** [comment]
True, maybe could add a new UI option which turns an assist order by engineers on T2 mex into a 4x mass storage build around that mex or similar. One issue with that would be when the user intended to repair the mex instead starting to build mass storages.
