### ISSUE TITLE
3641 Test: Map doesnt zoom in at game start

### ISSUE THREAD

**Issue by bamboofats** [FAForever/fa#735]
I downloaded the updated 3641 available at this very moment, but I cant seem to start any skirmish games. The map appears, all ACUs spawn, but the map doesnt zoom in. I get stuck at this point with unresponsive controls. Tried clearing the game prefs but still persists.
Im not sure what causes it but Im only certain its the lua datafile.
Does anyone else get this?

**Comment by Sheeo** [comment]
Make sure you post logs when reporting issues such as this.

There's a live regression when hosting with AI's that causes this issue.

**Comment by bamboofats** [comment]
Right, apologies I forgot logs. 
https://www.dropbox.com/sh/wflvcc0zoqsc0go/AADQAG7VI6P21OSy5Ge3ZKIaa?dl=0

Yes you are correct. Only hosting with AI's give this problem. Player only works fine.

**Comment by ChrisKitching** [comment]
I've fixed this locally: I'll push when I'm at my desk again.

**Comment by bamboofats** [comment]
This looks fixed in the latest 3641 downloadable. Closing
