### ISSUE TITLE
Continental shield bubble remains active while sinking/crashing

### ISSUE THREAD

**Issue by ChrisKitching** [FAForever/fa#740]

**Comment by ChrisKitching** [comment]
Fixed by 0dbdfeaa22e6103dc293508b9bac2321da574b38

**Comment by aeoncleanse** [comment]
Given the cont is the only unit affects,  would it not be better to do this only in the unit script and leave any modder wanting to make shielded air,  which wont be common even in a mod,  to also put the stuff into their scripts?
