### ISSUE TITLE
Unit Detail window no longer fades in and out.

### ISSUE THREAD

**Issue by CodingSquirrel** [FAForever/fa#743]
In live the unit view detail window will fade in and fade out when you hover over a unit. In 3641 it currently will appear and disappear instantly.

**Comment by Sheeo** [comment]
I discussed this with Chris yesterday -- this was the case since 07fa8b84b7c6ae4ce8284c0cc42dcecb2c9ec3de. Is it worth bringing back?

**Comment by ChrisKitching** [comment]
I think it's a positive change, and we should make the construction tooltips follow suit.

If nothing else, it may reduce perceived UI lag.

**Comment by Crotalus** [comment]
Yeah, I remember a mod at the GPG-forum which fixed some UI-lag by removing the OnFrame fading effect. I would guess it's only noticable if you have a crappy GPU which already is loaded though.

**Comment by ChrisKitching** [comment]
> I would guess it's only noticable if you have a crappy GPU which already is loaded though.

There are hundreds of things in the codebase with that property. In combination, the effect ceases to be negligible.

**Comment by CodingSquirrel** [comment]
I personally prefer the fade effect, but I'm not married to it either. I figured it was at least worth a discussion.

**Comment by ChrisKitching** [comment]
> I personally prefer the fade effect, but I'm not married to it either. I figured it was at least worth a discussion.

Well, we release tomorrow and killing the effect for construction is simpler than getting it to work right with unitview :p 
Charge!
