### ISSUE TITLE
Chat window no longer transparent

### ISSUE THREAD

**Issue by CodingSquirrel** [FAForever/fa#749]
The background of the chat is now a solid black. The edit box also lost its border.

![chat](https://cloud.githubusercontent.com/assets/13072675/8638831/edfc28c6-2894-11e5-8f9d-958256b02f2f.png)

**Comment by Sheeo** [comment]
https://github.com/FAForever/fa/commit/d75045dd91217eca7c6aeb011b9d75cc5a4229f8
