### ISSUE TITLE
Remove friendly fire for all TMLs 

### ISSUE THREAD

**Issue by Zockyzock** [FAForever/fa#754]
Surely people will find other ways to get banned, but this should make it a bit harder.

It is rather rare that you would hit a allied unit with a TML by accident, so there shouldn't be any downside.

**Comment by VoRGoR** [comment]
This would eliminate the risk of tmls to yourself.
With no downside you could tml large parts of your own base to kill enemy units around/ launch them indiscriminately when they could kill your own army/acu/pds etc. I think it's worth a bit more thought?

**Comment by Zockyzock** [comment]
Is it possible to keep friendly fire for own, but not allied units? 

Else i think the situations where a friendly fire tml on yourself would have any relevant impact (try to kill units in your base with a TML..it is unlikely you will hit, and if you do, unlikely that you would have hit something that belongs to you, do you have replays where someone would not fire a tml in fear of hitting own units?) are too rare to be a meaningful reason against this change.

**Comment by VoRGoR** [comment]
> Is it possible to keep friendly fire for own, but not allied units?

This allows you to simply transfer the tmls across to a team member in teamgames.



> Else i think the situations where a friendly fire tml on yourself would have any relevant impact (try to kill units in your base with a TML..it is unlikely you will hit, and if you do, unlikely that you would have hit something that belongs to you, do you have replays where someone would not fire a tml in fear of hitting own units?) are too rare to be a meaningful reason against this change.

Well, I think partly this is because it would kill everything. If you knew that they wouldn't damage your own units at all, we may see production of tml launchers for this sort of effect. Fights between xp units and/or sacus might qualify for this also.

I'm not too concerned admittedly. I'm just being the advocate of caution.

**Comment by aeoncleanse** [comment]
This also kills loyalist reflections doing anything

**Comment by ChrisKitching** [comment]
> It is rather rare that you would hit a allied unit with a TML by accident, so there shouldn't be any downside.

This logic can also be applied to nukes and artillery.

> Surely people will find other ways to get banned, but this should make it a bit harder.

This is not a reason to do anything. Ever.

**Comment by Zockyzock** [comment]
For nukes and artys there are much higher chances that there is something friendly in the area of desired impact. I don't think it is comparable, the damage radius and/or use is way different from TMLs. Both isn't so easily dodgeable either. In all my games i didn't have a single situation where i would not fire a TML out of fear to hit something friendly, but many situations where arty or nuke would, or did, hit them. (Anecdotal, but considering my number of games probably still not useless) 

I think the issue and of people getting teamkilled is huge and destroys fun and eventually lead to players quitting. Everything that helps to reduce that is a good reason for a change, as long as it is not negatively impacting the game. It would be better to automatically track TML-teamkills and send the replays to the moderators to investigate (ZeP wanted to do that), but until then, or a better solution is in place, every bit helps.

**Comment by Sheeo** [comment]
The better solution is trivial to do, actually

**Comment by aeoncleanse** [comment]
Which is why punishing troublemakers is always more effective than preventing the teamkills. Stop the idiots from doing this,  they will find other ways to grief. This community will improve much more,  much faster,  if instead of being namby pamby we just say "you deliberately tml an ally,  you get permabanned from faf,  no warning,  no chances." IMO someone who even THINKS about doing this is someone we don't want. 

Leave moderation to the moderators.  They get a complaint,  they verify,  potential trouble is gone.  GG

**Comment by Zockyzock** [comment]
The problem is that many people don't know that teamkilling is bannable, and don't report. 

However if the automatic solution is already possible for the next patch, we don't need this one. But i do want to have some improvement regarding this issue in 3642, and leaving the issue to the moderators alone is apparently not enough, as the issue keeps happening, and you keep have to explain to people that they should report (and that are only the ones who complain about it in chat).

**Comment by VoRGoR** [comment]
> For nukes and artys there are much higher chances that there is something friendly in the area of desired impact. I don't think it is comparable,

This is absolutely true.


> The problem is that many people don't know that teamkilling is bannable, and don't report.

This ^ is true and a real problem, not only for this, but for everything - I met countless people who had no idea there was even moderation. More public knowledge is the answer, but not sure how.

**Comment by Sheeo** [comment]
@VoRGoR with #756 which spawned off of this, you'll get a chance to raise awareness.
