### ISSUE TITLE
No Hover or Select effect for SCU Presets

### ISSUE THREAD

**Issue by CodingSquirrel** [FAForever/fa#755]
There is no hover effect for the SCU presets:
- [x] no tooltips when hovering over icons in the Quantum Gateway
- [ ] no semi transparent overlay when hovering over icons while they are in a transport

Also, there is no select effect for the SCU presets:
- [ ] icon background does not change when selecting the SCU in the transport to be dropped individually

**Comment by CodingSquirrel** [comment]
Added pull request #765 with a fix for this.

**Comment by HUSSAR-mtrela** [comment]
cannot reproduce first part of this issue in the 3652 patch but the last two items are still present.

**Comment by aeoncleanse** [comment]
Missing tooltips is this?

**Comment by HUSSAR-mtrela** [comment]
yes, I think tooltips were missing for the first item and I added more info to description of this issue

**Comment by CodingSquirrel** [comment]
I don't remember what I wrote initially but I believe it was about the hover effect, not the tooltip. Basically, there's no visual effect on the icon when hovering over the SCU presets. Other units, when you hover over their icons it creates a slight glow on the icon.

**Comment by aeoncleanse** [comment]
Can we get a check on the status of this?

**Comment by Nojoke185** [comment]
if I have understood the issues correctly then the below seem to still be problems:

1 - SACU presets in a factory, when you hover over the preset icons you dont get a glow when hovering over the icon

2 - same applies to SACU loaded in a transport - when hovering over there is no glow effect

3 - Load a few SACU in a transport, select a single SACU for drop from the transport, there is no selection change unit highlight to show which one is selected for drop (for engineers you can see which are selected in the same scenario)

**Comment by MrRowey** [comment]
Icons for the presets are being pulled from the textures/ui/common/icons/units folder where there seems to be customer Icons made for the presets and I've tested and it's definitely pulling them from there but dose does not seem to be applying the switch between icons when I've added the btn_down/up/over.dds files but this is a start

**Comment by Garanas** [comment]
Can you create the pull request with the work so far? It makes the discussion easier.

**Comment by MrRowey** [comment]
@Garanas i think the best way to implement this would be to create a Clone of the SACU and rename them and add those to the Quantum gate which would allow for the effect to work. just to how this was first implemented you can only have a single image and not the switch between ones like for the normal sacu

**Comment by MrRowey** [comment]
This Dose not affect the gameplay it just a Ui element that doesn't visually show. For now will close as Unplanned but if someone want to pick it up and finish it off feel free to reopen it
