### ISSUE TITLE
When ACU dies, check if the damage that killed it was friendly

### ISSUE THREAD

**Issue by Zockyzock** [FAForever/fa#756]
If yes, report game ID and timestamp to the moderator team or create a list visible by them. 

If the amount of false-reports is too high, exclude damage from ACU explosions and/or other sources that lead to non-abusive friendly fire kills.

**Comment by aeoncleanse** [comment]
We could have such a detection pop up a dialog along the lines of... "You have been killed by friendly fire.  The deliberate killing of team-mates is against FAF rules.  If you feel your death was deliberate or unsportsmanlike,  press the report button below." and provide a report button which notifies mods,  and an exit button.

**Comment by VoRGoR** [comment]
I'm all for this.

Anything in-game that can raise awareness of the fact that there is moderation and rules also gets a plus from me. Added to that an easy way (click) of actually doing it, removes the problem of people being too lazy.

**Comment by Zockyzock** [comment]
To be effective, it also needs to check ALL friendly fire damage, on mex, pgs, t4 in construction..

**Comment by aeoncleanse** [comment]
This issue has pretty much been addressed with the team-kill detection and reporting system I think.
