### ISSUE TITLE
Ythotha becomes invisible when walking in water

### ISSUE THREAD

**Issue by duk3luk3** [FAForever/fa#763]
This may be a regression, maybe has something to do with the bone fixes? Replay: http://content.faforever.com/faf/vault/replay_vault/replay.php?id=3641286

**Comment by quark036** [comment]
It happens with the megalith too, might be all experimentalist, probably something to do with them being partially submerged

**Comment by Sheeo** [comment]
I don't believe this is a regression, but we definitely want to fix it :)

Sounds like the origin bone is low to the ground, causing the unit to be considered submerged early on.

**Comment by aeoncleanse** [comment]
Can't reproduce... Replay corrupted.

**Comment by duk3luk3** [comment]
It's my latest replay, on canis, just search dukeofearl in the replay
vault.

**Comment by aeoncleanse** [comment]
Yeah, it's corrupted
it won't download or play

**Comment by duk3luk3** [comment]
I watched my local replay, it doesn't happen in the replay. :(

**Comment by ChrisKitching** [comment]
As soon as it gets its feet wet it's considered a layer change and anything (such as a spy plane) that lacks underwater vision can no longer see it.

The game isn't too good at supporting the notion of units in multiple layers, alas.

**Comment by MattDeering** [comment]
#3825572 for you icedreamer. 26 mins in. Chicken is shooting at my inti with just sees a naval blip

**Comment by aeoncleanse** [comment]
I'll take a look once im home, but I'm 99% sure this is what chris said, that it happens to spider/megalith too, and that it's unfixable.

**Comment by MattDeering** [comment]
Its a very longstanding bug. You cant hack it to be on 2 layers at once?

**Comment by aeoncleanse** [comment]
Pretty sure we either cant, or it would make the engine blow up. I wouldnt know how to even begin to attempt that path anyway, layers are all controlled in the engine

**Comment by quark036** [comment]
I agree that layers are icky engine side stuff, but one thing we might be
able to do is detect if it is in shallow water and if so, create a radar
blip, which would alleviate the problem

**Comment by duk3luk3** [comment]
Is this a target bone thing? Are we doing something wrong with the positioning of bones on the model?

**Comment by aeoncleanse** [comment]
For once no.

**Comment by quark036** [comment]
It's that the layer change gets called the moment the feet hit water and
after that you need sonar to see it.

**Comment by MattDeering** [comment]
And then it sits next to the beach invisible and shoots everything! (more relevant to fatty and mega)

**Comment by quark036** [comment]
So I guess it is a little bit due to the bones-not because they are wrong,
but because firing depends on if the bone is out of the water but
visibility depends on the feet being out of the water. Another solution
could be to completely disable all land weapons until it is completely out
of the water.

**Comment by aeoncleanse** [comment]
Which we dont want to do. It was decided a long time ago that we want them to fire once the weapon looks like it can, for realism, but not be unhittable. Im really not sure of a good solution to this

**Comment by quark036** [comment]
I'm going to try implement my idea where if the guns can fire, it l radar
blip or just becomes visible to radar.

**Comment by MattDeering** [comment]
Can we get current y coord and water y coord and unit height?

**Comment by aeoncleanse** [comment]
Yes, but how does that help?

**Comment by quark036** [comment]
Check out GetSurfaceHeight(x,z), GetTerrainType(x,z), GetTerrainHeight(x,z)
in the Luadoc, and also Unit:GetCurrentMoveLocation

**Comment by shalkya** [comment]
hello, kind of a necro; kind of want a summarize here since it's an annoying issue.
is it possible or not to make unit that have feet in water but the head over the water visible from the other unit (and so targatable) ?
If not is there any other fix that can diminish the issue, like this one #2056 ?

**Comment by aeoncleanse** [comment]
In theory, giving all land units watervision would do the trick (I think). But then they could see subs, ACUs... Nothing could escape underwater properly any more

**Comment by Exotic-Retard** [comment]
in practise, watervision is disabled when a unit is on the land layer. :|
for some absurd reason. unless theres some script im missing it seems to be just engine things

**Comment by JaggedAppliance** [comment]
![intel](https://user-images.githubusercontent.com/5166284/26979424-9c80667a-4d26-11e7-8fb4-6ca4b044a01c.png)
![intel2](https://user-images.githubusercontent.com/5166284/26979432-a20a202c-4d26-11e7-8791-fd906f3eedff.png)

The water is about knee deep for ACUs here. The Mega and Ythotha disappear from radar but the other amphibious XPs remain on radar. ACUs and SCUs remain on radar. The Percy, Brick and Othuum disappear from radar. All of these units can still see and shoot at units on land. I have no idea what governs why some are on radar and others aren't.

I know that units can't shoot until their weapon is just above the water. Could we link the weapon disabling with when it appears on radar/counts as submerged?

**Comment by shalkya** [comment]
1st try :
![image](https://user-images.githubusercontent.com/11618427/26986470-fce76560-4d47-11e7-8c50-ae9154ca5ed8.png)

![image](https://user-images.githubusercontent.com/11618427/26986478-0541ea8c-4d48-11e7-982c-bf27ffca8009.png)

2nd try : 
![image](https://user-images.githubusercontent.com/11618427/26986796-5ffa81ae-4d49-11e7-8b89-e4144ded1baf.png)
![image](https://user-images.githubusercontent.com/11618427/26986797-65fd3b50-4d49-11e7-90cd-3bc7c1a35d48.png)

clearly only GC and ML appear on both example.

**Comment by shalkya** [comment]
![image](https://user-images.githubusercontent.com/11618427/26987348-909f29de-4d4b-11e7-9146-fd805191e1f9.png)
![image](https://user-images.githubusercontent.com/11618427/26987356-95614c22-4d4b-11e7-99e2-0ea456a461a9.png)
get pretty much same result, brick seems to still appear for some reason. 
So mega, ythota, percy, (~othuums) seems to disappear and not the other unit


and on other test with higher level of water (higher than ACU/SCU/T3.5 bot)
1st try :
![image](https://user-images.githubusercontent.com/11618427/26986470-fce76560-4d47-11e7-8c50-ae9154ca5ed8.png)

![image](https://user-images.githubusercontent.com/11618427/26986478-0541ea8c-4d48-11e7-982c-bf27ffca8009.png)

2nd try : 
![image](https://user-images.githubusercontent.com/11618427/26986939-d7683b00-4d49-11e7-97ff-3955af313e32.png)

![image](https://user-images.githubusercontent.com/11618427/26986946-dd9db5e0-4d49-11e7-87d5-a47b39f2b98e.png)


clearly only GC and ML appear on both example.

**Comment by aeoncleanse** [comment]
Yeah I have no clue why this is

**Comment by JaggedAppliance** [comment]
Seems like the units with problems are ones added in FA. Just throwing that out there, dunno if it could be helpful.

**Comment by aeoncleanse** [comment]
It's the root bone. This needs a modeller to fix it. A unit becomes invisible when the root bone is submerged to a certain distance. I've not measured it, but it looks to be about 0.5 map units. A general rule of making sure the root bone is above the weaponry should be put into place for bottom-walking amphibious units.

**Comment by Exotic-Retard** [comment]
so as an update, this is nothing to do with the root bone, its done with a blueprint value.
