### ISSUE TITLE
Shield icon covers housed units icon

### ISSUE THREAD

**Issue by CodingSquirrel** [FAForever/fa#768]
This should only affect the Continental and Fatboy. If a unit has a shield and also loads a unit for transport the icons overlap.

I don't think there are enough spaces on the current 2x3 grid to properly account for this.

**Comment by aeoncleanse** [comment]
Still a problem

**Comment by MrRowey** [comment]
@Garanas 
![image](https://user-images.githubusercontent.com/20344151/139725467-54d3b99b-98e7-4a64-9cd2-d7f956522d9b.png)

As you can see in this image dose not seem to be an issues any more as it clearly shows the units amount of units in the transported below the shield icon
