### ISSUE TITLE
Right click should repair facs instead of assist

### ISSUE THREAD

**Issue by anihilnine** [FAForever/fa#769]
If you repair an incomplete building, it will finish the building at range (assuming you are in range) but if you assist it instead of repairing, the engie will walk in close (even if you are in range) and finish it building, then assist it with whatever it is working on.

In the 3642 release notes it said a new feature was "Assist now prioritize building over repair" which I assumed fixed this annoyance but I can't see this in my testing.

I found this issue: https://github.com/FAForever/fa/issues/643 which says its done. 

So it would be nice if right clicking an incomplete fac would repair it instead of assisting it. That way the building would get completed without unnecessary walking.

It would be even nicer if assisting a building could happen at range without unnecessary walking. Although that might impact other things (like when you select 400 engies to assist your setons t3 air fac)

**Comment by aeoncleanse** [comment]
I'm clearing any milestones for this. The 3642 change meant that, when an assist order was in place, an engineering unit would assist any task being done before attempting to repair the unit (Previously the other way around). 

Additionally, the behaviour is already as desired for non-Factory units (EG, PGens, PD...).

 What you're asking for would involve changing the order that pops up when you mouse over an unfinished factory from being Assist to Repair... I'm not entirely sure it can be done.

**Comment by MrRowey** [comment]
@Garanas close as limited by the engine ? i recall some discussion about this on the discord
