### ISSUE TITLE
Minimal range ring not updating with bp value

### ISSUE THREAD

**Issue by ppipp** [FAForever/fa#778]
If I change the MinRadius of the ACU TML (from 5 to 15 for instance, or 40), the yellow circle remains the same (5).

**Comment by Crotalus** [comment]
UEF ACU I presume? Could be Billy range that's shown in that case, try remove RangeCategory for it and see if it works.

**Comment by aeoncleanse** [comment]
^that

**Comment by ppipp** [comment]
That's it, thanks.
