### ISSUE TITLE
Sera T2 Transport allows active shields in hooks

### ISSUE THREAD

**Issue by Varaxis** [FAForever/fa#780]
Sera T2 Transport allows all shields to be active, both bubbles and personal shields. No other transport allows this, based on testing in sandbox.

**Comment by duk3luk3** [comment]
Should be an easy fix, I'm taking a look at it.

**Comment by duk3luk3** [comment]
Investigation progress: Sera T2 Transport is not part of the mod, so its script gets loaded from base files, so it doesn't inherit from airtransport base class. I suspect this is where the shield disable stuff happens.

**Comment by duk3luk3** [comment]
Indeed the BaseTransport class in https://github.com/FAForever/fa/blob/develop/lua/defaultunits.lua#L1646 has shield disable logic for transported units.

So what probably needs to be done to fix this is to redo the Sera T2 Transport (XSA0104) to properly inherit from AirTransport base class.

Who is familar with the reclassing stuff? @Sheeo? @aeoncleanse?

**Comment by Sheeo** [comment]
@ChrisKitching is the one who did the original refactor -- it saves sim execution time.

Indeed that's a easy fix.

**Comment by ChrisKitching** [comment]
> So what probably needs to be done to fix this is to redo the Sera T2 Transport (XSA0104) to properly inherit from AirTransport base class.

Yup. Do that. It's almost certainly a trivial matter of deleting most of the script :P

> it saves sim execution time.

And, more usefully, gives us abstractions that make sense (AirTransport itself inherits from BaseTransport (a base class of "things that hold other things" which encompasses things such as aircraft carriers, the CZAR, and kennels, all of which previously had variously inconsistent copies of identical code in them :/))

**Comment by duk3luk3** [comment]
I won't have the time to fix and test this for a while.
