### ISSUE TITLE
Help with improving sniper bots' behaviour

### ISSUE THREAD

**Issue by ppipp** [FAForever/fa#783]
I removed the unpack animation in the past because snipers are useless with them (they lose the reload of their weapon if they move after the unpack animation started, even if they don't shoot, they don't aim at target unless you don't move them wasting a lot of time and DPS). I compensated with firingrandomness on the move but people don't like it.

In order to get more satisfying snipers, it would be good to simply tell the unit to stop / pause for a very short time (new parameter maybe) just before it shoots (precisely before the muzzlecharge animation starts), then resume walking. It would be the time to aim precisely at the target and that requires immobility.
Maybe it could be used for other units too, like Aurora or Percival.

**Comment by aeoncleanse** [comment]
This is no longer an issue
