### ISSUE TITLE
Unit gets pushed into unwalkable terrain (incomplete fac) and stuck

### ISSUE THREAD

**Issue by duk3luk3** [FAForever/fa#784]
http://replay.faforever.com/3657775 around 6:50 uef acu gets bumped into incomplete fac by collision with mantis and cannot move afterwards.

This kind of thing, also with terrain features, happens only occasionally in my experience but is fairly game breaking when it does.  
Maybe happens mainly with units that cannot turn on the spot or move in reverse so they can get into an obstacle but not out of it.

I don't know how to fix this, maybe we need to detect units with a valid path who are not managing to move and teleport or bump them out of obstacles.

**Comment by MrRowey** [comment]
A part of linked issues on why this happens.
