### ISSUE TITLE
Complains about new pause

### ISSUE THREAD

**Issue by ppipp** [FAForever/fa#787]
Just reporting here a detailed complain about the new way pause works. It was not in the tech forum subsection so I fear it may have remained unnoticed for now.

http://forums.faforever.com/forums/viewtopic.php?f=2&t=10333

**Comment by Zockyzock** [comment]
I have the same problems with it. A different pause key for the new command-pause and the old build/upgrade pause would be nice.

**Comment by Sheeo** [comment]
I have reverted this for 3643 in https://github.com/FAForever/fa/commit/15d3651c634c697df3d5b326425ff569ea712914.

What about making the "Stop" button right-clickable to achieve this behavior (Along with a default-mapped hotkey to some unused key). We need a new texture (Or some option overlay) for the newly toggleable button in this case.

**Comment by Sheeo** [comment]
Pushing it in scope for 3644, since we can't make it if we want to release 3643 in time :)

**Comment by Sheeo** [comment]
Feature not implemented yet.

**Comment by aeoncleanse** [comment]
We probably want this dealt with for 3660. Any volunteers? Also, could @Zockyzock or @Sheeo outline exactly what needs to be achieved?

**Comment by Garanas** [comment]
This issue has aged. If people still have problems with the unit pause functionality then they can make a new issue describing the problem.
