### ISSUE TITLE
Automatic overcharge toggle

### ISSUE THREAD

**Issue by julesjacobs** [FAForever/fa#789]
For the balance patch we would like to have an automatic overcharge toggle for sera SCUs, as well as for ACUs (for consistency). The idea is that you can right click on the overcharge icon to make overcharging automatic: it will overcharge as soon as you have enough energy. It's similar to how you can right click on the ACU TML icon to build TMLs automatically. If possible this would be turned ON by default for SCUs, and OFF by default for ACUs.

**Comment by Zockyzock** [comment]
A tooltip to make clear how it works should not be forgotten too.

**Comment by duk3luk3** [comment]
Why do we want that? Has there been any debate on this that can be cited? Manual overcharge is an explicit micro-heavy game element, automating it would shift the balance hugely by making ACUs immensely stronger.

In general I am all for reducing micro, but this seems like a really big change.

**Comment by quark036** [comment]
Well, zock is the balance councilor...
Also, manual would be more effective, because auto wouldn't target clumps.

**Comment by duk3luk3** [comment]
I don't think the point of the balance councillor office is to just make decisions without prior deliberation and discussion that involves the community.

**Comment by Zockyzock** [comment]
The purpose is to avoid the need for impossible amounts of micro to use multiple sera SCUs with OC. Without toggle they will be either OP in low numbers or weak in high numbers when you can't use OC manually anymore. 

I don't see automatic OC buffing ACUss significantly, the advantage of OC is to kill high priority/clumped targets, automatic OC would often just consume your energy and damage on a not-optimal target.

**Comment by duk3luk3** [comment]
:+1:

**Comment by julesjacobs** [comment]
I think the only time you would want this on your acu is in the very lategame where 5000 energy is nothing, and you turn it on just in case some units try to run past your acu. If you are actually microing your acu you would always turn it off so that you can find a better target manually, even in the late game.

**Comment by hepko** [comment]
Automatic OC will be perfect :) for killing ACU-s trying to escape, as now your ACU stops for some time when you manualy click overcharge action, so you can only overcharge ~3 times until the enemy is out of range. Or do you (ZOCK :) ) have some trick to keep walking all the time and use OC ?

**Comment by zlo-faf** [comment]
If you OC in same direction where ACU is facing and instantly  place move order in same direction it was walking then you will not slow down or very very little slowdown.

**Comment by duk3luk3** [comment]
I always queue a walking order right after giving OC order.

**Comment by zlo-faf** [comment]
That way ACU will slow down, you should avoid it if you can...

**Comment by aeoncleanse** [comment]
This is in, but I think this issue should be left open for feedback on it.

**Comment by aeoncleanse** [comment]
Added the toggle tooltip requested. The target priorities look good too. Icon when activated is a bit ugly, might have to do something about that at some point.
