### ISSUE TITLE
New Modelling Process

### ISSUE THREAD

**Issue by aeoncleanse** [FAForever/fa#79]
Not entirely sure this issue belongs in FA, but there doesn't appear to be a misc section. 

BannanaHammer has made good progress towards fixing Issue #23 properly. The theory is correct and adding a new bone is the way forwards. However, the importer used with Blender is currently broken, not importing Normals properly and making the entire process far, far harder than it needs to be.

I think we need to put a long-term goal in place to either find out what program(s) GPG used to create models in the first place, contact as many of the old/current modellers as we can, and get documentation together on how to do this, and how to avoid or solve the common problems.

It is also worth, I think, writing a new importer or whatever it takes to make editing models as easy and painless as possible, if such an endeavour is even achievable.

How it's meant to look: http://snag.gy/WvyIV.jpg
How it looks post-edit: http://snag.gy/euISO.jpg

**Comment by ChrisKitching** [comment]
Turns out there's a widely available plugin that handles this.
