### ISSUE TITLE
End Game closes the application

### ISSUE THREAD

**Issue by CodingSquirrel** [FAForever/fa#790]
Before 3641 End Game would kick you back to the main menu if you launched the game outside of FAF. Now, after exiting the score screen it just closes the application.

**Comment by bamboofats** [comment]
It appears this fix causes this
https://github.com/FAForever/fa/commit/c11bdd850e947cdffd0b9fa3943ca3d62c675c81

**Comment by aeoncleanse** [comment]
@Sheeo Is it worth trying to do something about this? It's not so bad really IMO.

**Comment by Exotic-Retard** [comment]
somewhat annoying for testing stuff sometimes

**Comment by Nojoke185** [comment]
yes - agreed, I recall sometime back (many patches ago) in the FAF world ending a game used to drop you back into the menu rather than out of the game. Would speed things slightly with testing to put this back in

**Comment by Uveso** [comment]
Not only for testing, also for normal play.

Whe sould add someting like:
```
If game-was-launched-from-FAFlobby then
    exit game
else
    return main menu
end
```
