### ISSUE TITLE
Cybran engy drone air unit classification bugs out NO AIR restriction

### ISSUE THREAD

**Issue by duk3luk3** [FAForever/fa#791]
New patch classifies all engy drones, including cybran "bats", as air units, which causes thermo no air players a lot of grief.

I haven't had time to repro it or check if someone is already working on it, just dumping an issue here to keep track of it.

**Comment by Sheeo** [comment]
Fixed in d549694502f96b90a31655e66d30b47b899a52f9. Oddly can't find another issue for this.
