### ISSUE TITLE
Particles from certain enemy units/projectiles rendering through fog

### ISSUE THREAD

**Issue by Varaxis** [FAForever/fa#793]
Sera T3 Heavy Arty Hovatham shots (shows as flame aura)
Aeon T3 Heavy Arty Emissary shots (shows as a distinctly defined glow shaped just like the projectile)
Aeon T3 Rapid Fire Arty Salvation shots (shows as dark smoke)
Sera Strategic nuke missile (esp the T4, very visible)
... more, which are not as big of a deal, like cyb arty projectile impacts, t4 bomber bomb, and sera scu gun. 

This type of intel proved to be enough of a strategic (dis)advantage that it could alert the enemy to react accordingly, taking guesswork out of things such as dodging a nuke, or pinpointing the location of valuable enemy units. Similar to how in the past, the Sera ACU regular shots showed through the fog when fighting civs, also showing wrecks, weapon impacts, and explosions.

**Comment by duk3luk3** [comment]
Are you sure that this isn't a feature in the case of static artillery and nukes?

**Comment by quark036** [comment]
If it is, it should probably be even between factions

**Comment by Varaxis** [comment]
Picture it this way: a very effective defense versus arty is assisting a shield. If UEF can see the shots through the fog, they can effectively protect a wide area with this tactic following the shots and sending drones to assist shields accordingly.

**Comment by duk3luk3** [comment]
Yes, this should be balanced - either all nukes and strategic artillery shots should be tracable, or none should be.

**Comment by Varaxis** [comment]
There used to be a console command that let you clearly see enemy nuke missile paths, through the fog, actually drawing a red trail behind it, but it was disabled in a FAF prior patch.

**Comment by bamboofats** [comment]
I dont have a solution to offer for the impact effects, Eg cybran arty ground impact glows. 
It comes from the CreateLightParticle() and they are all over the place from the projectile script files to the EffectTemplates file.

But i have for those trails visible through the fog. This should prevent tracing back the shots.
Trail issue affects
Aeon T3 static arty trail
Aeon Rapid fire art trail
Sera T3 static arty trail
Sera T3 mobile arty trail
Sera Scu regular shots trail
Sera Scu OC shots trail
Sera ACU OC shots trail
Cybran T1 arty trail
Sera T4 bomber trail (not the nukelike impact)
Sera Antinuke trail
Sera nuke trail (from static launcher or from naval nuke)
UEF nuke trail (from static launcher or from naval nuke)
Cybran nuke trail (from static launcher or from naval nuke)

Fix is done similar to https://github.com/FAForever/fa/commit/8a987da5fab49c61409a5b9b71b82abff32381e4
Change EmitIfVisible to true and set the LOD~ 500 is fine even for Arty shots.

The following files in  effects/emitters  should be added and altered
aeon_heavy_artillery_trail_01_emit.bp
aeon_quanticcluster_fxtrail_01_emit.bp
aeon_quanticcluster_fxtrail_02_emit.bp
mortar_munition_03_emit.bp
nuke_munition_launch_trail_04_emit.bp
nuke_munition_launch_trail_05_emit.bp
nuke_munition_launch_trail_06_emit.bp
nuke_munition_launch_trail_07_emit.bp
seraphim_chronotron_cannon_overcharge_projectile_fxtrail_01_emit.bp
seraphim_chronotron_cannon_overcharge_projectile_fxtrail_02_emit.bp
seraphim_chronotron_cannon_overcharge_projectile_fxtrail_03_emit.bp
seraphim_expnuke_fxtrails_01_emit.bp
seraphim_expnuke_fxtrails_02_emit.bp
seraphim_inaino_fxtrails_01_emit.bp
seraphim_inaino_fxtrails_02_emit.bp
seraphim_khu_anti_nuke_fxtrail_01_emit.bp
seraphim_khu_anti_nuke_fxtrail_02_emit.bp
seraphim_light_chronotron_cannon_overcharge_projectile_fxtrail_01_emit.bp
seraphim_light_chronotron_cannon_overcharge_projectile_fxtrail_02_emit.bp
seraphim_light_chronotron_cannon_projectile_fxtrail_01_emit.bp
seraphim_light_chronotron_cannon_projectile_fxtrail_02_emit.bp
seraphim_light_chronotron_cannon_projectile_fxtrail_03_emit.bp
seraphim_ohwalli_strategic_bomb_fxtrails_01_emit.bp
seraphim_ohwalli_strategic_bomb_fxtrails_02_emit.bp
seraphim_ohwalli_strategic_bomb_fxtrails_03_emit.bp
seraphim_ohwalli_strategic_bomb_fxtrails_04_emit.bp
seraphim_ohwalli_strategic_bomb_fxtrails_05_emit.bp
seraphim_ohwalli_strategic_bomb_fxtrails_06_emit.bp
seraphim_rifter_artillery_projectile_fxtrails_01_emit.bp
seraphim_rifter_artillery_projectile_fxtrails_02_emit.bp
seraphim_rifter_artillery_projectile_fxtrails_03_emit.bp
seraphim_rifter_artillery_projectile_fxtrails_04_emit.bp
seraphim_rifter_artillery_projectile_fxtrails_05_emit.bp
seraphim_rifter_artillery_projectile_fxtrails_06_emit.bp
seraphim_rifter_mobileartillery_projectile_fxtrails_01_emit.bp
seraphim_rifter_mobileartillery_projectile_fxtrails_02_emit.bp
seraphim_rifter_mobileartillery_projectile_fxtrails_03_emit.bp
seraphim_rifter_mobileartillery_projectile_fxtrails_04_emit.bp
seraphim_rifter_mobileartillery_projectile_fxtrails_05_emit.bp
seraphim_rifter_mobileartillery_projectile_fxtrails_06_emit.bp

Tested on my end and it works as intended.

**Comment by Uveso** [comment]
Is this a balance issue ? I fear balance terrorists !

Ok, lets start with the example fix https://github.com/FAForever/fa/commit/8a987da5fab49c61409a5b9b71b82abff32381e4

LODCutoff is set to 1200 for the weaponemitter of the ACU.
But the ACU Unit itself has a LODCutoff of 175.

So the LODCutoff of the transmitter should be 175 and not 1200.
It makes no sense to show the emiter close to max zoom out without showing the unit.
(We should change that)

Also arty shots need a LODCutoff way higher then 500. For example a landfactory has a LODCutoff of 500.
A projectile from an arty can fly up to 1400 and LODCutoff is set normaly to -1 (always shown)

We should not set new LODCutoffs. The old ones are working fine. And its not necessary for the PR itself.

We only have to change `EmitIfVisible = true,` inside all blueprints posted by @bamboofats.


---

Privat note:
I like to see the trails from nukes and T3 Arty inside fog of war.
Do we really remove them ? :)
(Say it and i will do it^^)

**Comment by Exotic-Retard** [comment]
balance terrorists arriving right on cue!

thing about fog of war is that a very long list of explosions, mostly death explosions show through gof of war, so you can often get some free intel in things like ffas. i would say this is actually a good thing since you are not so blind but dont know exactly whats going on. 

i would make it consistent across factions.
nuke trails is not great because you can abuse it to have a reasonable advantage (check out the dodger ui mod), and we can also say that it might have a similar impact on t3 arty, though not so great since its harder to predict the exact position and direction.

**Comment by Uveso** [comment]
I checked the dodger ui mod, and as i can see the `ConExecute("UI_RenProjectileArcs")` command is no longer working in FAF.
I also don't see any trails from nukes. Is this still working ? maybe a new version ? I tested V1 from the vault.

**Comment by aeoncleanse** [comment]
That command was disabled in faf i think. And yes, we remove all trails in FoW.

**Comment by aeoncleanse** [comment]
b3a31c914d02e4013f5343fdb1361447a00855c9
