### ISSUE TITLE
Transports pause at waypoints

### ISSUE THREAD

**Issue by julesjacobs** [FAForever/fa#794]
When you give a transport multiple orders with shift, it pauses for a second at each waypoint.

**Comment by duk3luk3** [comment]
Which other air units do or don't do it? How is "not pausing" implemented (or how can we implement it), is the waypoint deleted as the unit gets close?

**Comment by julesjacobs** [comment]
I think it's only transports (maybe gunships?). The problem is that the transport flies to the waypoint, then slows down until it's really close to the waypoint, and then continues to the next waypoint. Other units don't slow down when you give multiple waypoints. Maybe it can be solved by deleting the waypoint sooner, so that the transport goes to the next waypoint before slowing down, but I really have no idea how that works internally.

**Comment by KionX** [comment]
This problem is no longer there.
