### ISSUE TITLE
Don't allow construction of drones when engineering station restriction is on

### ISSUE THREAD

**Issue by Sheeo** [FAForever/fa#798]
https://github.com/FAForever/fa/tree/feature/no_drones starts work on this.

TODO:
- [x] Modify UI to disallow construction of drones when the restriction is enabled
- [x] Add localizations

**Comment by HUSSAR-mtrela** [comment]
Sheeo, I would like to work on this issue if you dont mind,

**Comment by Sheeo** [comment]
Of course, by all means :) :+1:

**Comment by aeoncleanse** [comment]
7feef8fa305d073b0f77bfb3da18e7b5fa4f060d

**Comment by Sheeo** [comment]
TODO list not completed on this issue.

**Comment by aeoncleanse** [comment]
Which UI is in need of modification??

**Comment by HUSSAR-mtrela** [comment]
I think that he means UI for unit construction

**Comment by HUSSAR-mtrela** [comment]
closing because this issue was fixed with PR #1187 and a few hotfixes that followed it.
