### ISSUE TITLE
Units lose orders when stunned (by cybran SCU)

### ISSUE THREAD

**Issue by julesjacobs** [FAForever/fa#799]
Can we make it so that units do not lose orders when stunned? This makes microing against cybran SCUs very annoying, especially when they have stealth since then your units stop shooting at all.

**Comment by quark036** [comment]
Sort of seemed to me that this was a feature rather than a bug

**Comment by quark036** [comment]
So, I looked into this. As far as I can tell, the stun buff is implemented engine side. The medusa and the scu have the same buff, but medusa stun doesn't remove orders. In Buffs.lua it didn't have code for stun either. If we really want to change this, the way to do it would be to remove the Stun buff, and reimplement it in our own code.

**Comment by quark036** [comment]
Also, we can't access the command queue, so we can't save that and replace it afterwards.

**Comment by ChrisKitching** [comment]
> Also, we can't access the command queue, so we can't save that and replace it afterwards.

_well_

I think we can _get_ the command queue, we just can't edit it. Check out Unit:GetCommandQueue in Luadoc.

So, I suppose, we could get it, save it, clear it, and rebuild it. Kinda ugly, however. There'll be a better way, I'm sure.

**Comment by duk3luk3** [comment]
> As far as I can tell, the stun buff is implemented engine side. The medusa and the scu have the same buff, but medusa stun doesn't remove orders.

So why *does* the medusa stun remove the orders? And what about other stun effects, like aeon bomber and sera (right?) chrono dampener ACU?

**Comment by quark036** [comment]
I didn't look at the others. Chrono damper is aeon. I'm not sure why scu removes orders while medusa doesn't, and I'm pretty sure aeon bomber doesn't either. Feel free to check out the code, but the enhancement code for the scu is just "add stun buff," and there's nothing in buffs.lua to differentiate them

**Comment by quark036** [comment]
Actually, one thing I noticed in buffs.lua was a comment that "this won't work for stun" (sorry I can't get the line number right now, just search stun), so I assume stun was implemented in the engine and that's why some lose orders and some don't

**Comment by aeoncleanse** [comment]
I, too, cannot see any reason for the SCU stun to act differently to the others :/

**Comment by duk3luk3** [comment]
Huh? I thought I fixed that.

**Comment by aeoncleanse** [comment]
I'm moving this out of 3652 seeing as we don't have the first idea where to start with it, and the patch is imminent.

**Comment by MrRowey** [comment]
@Tagada14 if this is not an issue anymore can this be closed :)

**Comment by 4z0t** [comment]
Who can confirm this bug?

**Comment by MrRowey** [comment]
Closing for now Balance Team Can Re open if needed

**Comment by Garanas** [comment]
This is an issue, and one we can't fix.
