### ISSUE TITLE
Expiring buffs don't update current health/regen rates

### ISSUE THREAD

**Issue by Sheeo** [FAForever/fa#804]
Buffs that affect these unit parameters do not update them when they expire.

See /lua/sim/Buff.lua line 448

**Comment by aeoncleanse** [comment]
Did this get fixed in the regen overhaul in 3652?

**Comment by aeoncleanse** [comment]
This just needs checking out.

**Comment by Nojoke185** [comment]
checked this tonight and have not seen any issues with regen

**Comment by aeoncleanse** [comment]
Nor me. Closing.
