### ISSUE TITLE
3643 Resuming a paused construction (doesnt work as intended)

### ISSUE THREAD

**Issue by bamboofats** [FAForever/fa#812]
ACU or eng builds something. 
Press pause (build beams still show)
Unpause (construction does not resume)

And the AI , eg sorian, totally becomes noob, only builds from 2 factories and doesnt move its combat units.

I kindof traced it to the removal of 
GetUnitBeingBuilt = function(self)
    return self.UnitBeingBuilt
end,

from sim/unit.lua   during the factory wreck patch

**Comment by Crotalus** [comment]
Fixed here a46e5ca4b9ae4f47fa2f1182b61ee07364a4cd69

**Comment by bamboofats** [comment]
Do check that the fix also restores the AI behaviour. Not sure if I is my poor technique of applying the file changes, the pause bug is fixed but the AI still behaves noobly. Great if a quick verification of the sorian AI could be done for the hot fix. Set up a game and run the game speed 10+, watch just for the first 10 game minutes.

![wrong](https://cloud.githubusercontent.com/assets/13047748/8887913/ff46c516-32c9-11e5-9d66-82166320d979.jpg)
Noobed behaviour. Just builds 2 factories and spams units to a corner


![corr](https://cloud.githubusercontent.com/assets/13047748/8887914/02539e14-32ca-11e5-9bb8-adcbc1ff9f5a.jpg)
Prior correct behaviour
