### ISSUE TITLE
Remove Ahwassa from select all fighters hotkey 

### ISSUE THREAD

**Issue by Zockyzock** [FAForever/fa#813]
I believe fighterbombers already got removed from it (if not please do too) .

**Comment by quark036** [comment]
#166 should have fixed this for both, if it's wrong now it's a regression

**Comment by Zockyzock** [comment]
I didn't test it but petric complained about it when we played

**Comment by quark036** [comment]
Ok, I'll test it soon

**Comment by SwayGin-FAF** [comment]
I noticed this before but (at least for me) this is fixed.

**Comment by ChrisKitching** [comment]
Looks like it. Since it's had the BOMBER category added this is no longer a thing.
