### ISSUE TITLE
Alredy list units in transport-menue when queued up to load them

### ISSUE THREAD

**Issue by Zockyzock** [FAForever/fa#815]
So you can already give orders to drop single units

Currently they only get displayed after being loaded, and you have to wait for the transport to pick them up before you can give orders to drop them in different places.

**Comment by aeoncleanse** [comment]
We can't do this, because it is possible to queue more units on a transport order than the transport has slots. Not only would it probably break many things, you'd also have any units who fail to get picked up wandering across the map to get their orders completed.

**Comment by micheljung** [comment]
While I think this would end up being pretty confusing and not easy to do consistently (what about ferry points?), I don't agree that we couldn't do this or that it would cause units wandering around (he just wants to be able to drop them)

**Comment by aeoncleanse** [comment]
I don't see any way to do it. How would you handle a unit you've selected to drop that then never gets picked up? What if you gave it post-drop commands (Very common thing to do)? There's all sorts of issues with this.
