### ISSUE TITLE
Engy doesn't resumer building after pause

### ISSUE THREAD

**Issue by duk3luk3** [FAForever/fa#820]
http://content.faforever.com/faf/vault/replay_vault/replay.php?id=3689021

At around 3 minutes I pause an engy building a land fac. Construction pauses, build animation continues. At around 3 minutes I unpause the engy but it doesn't resume construction.

I had EcoManager and Notify on, could this be EcoManager's fault @Crotalus ?

**Comment by duk3luk3** [comment]
Is probably related to EcoManager's automatic pause/unpause feature, since it also just happened in a ladder game where engy was building mex and was pause without even showing pause icon overlay on unit. content.faforever.com/faf/vault/replay_vault/replay.php?id=3689604

**Comment by Crotalus** [comment]
Known error with unit pausing in 3643, next patch will solve it

**Comment by duk3luk3** [comment]
:+1:

**Comment by Sheeo** [comment]
If it's known and fixed--where's the issue for it? Can't close this as dupe :)

**Comment by Crotalus** [comment]
True, this is the only github issue for the problem

This commit solves it a46e5ca4b9ae4f47fa2f1182b61ee07364a4cd69

**Comment by duk3luk3** [comment]
Was the problem that OnUnpaused wasn't getting called because trying to
call GetUnitBeingBuilt caused an exception?

**Comment by Sheeo** [comment]
There were more callsites.

These two commits are relevant, too:
 - https://github.com/FAForever/fa/commit/2279cb17cee5faf0b674a44ca83636947dab0e61
 - https://github.com/FAForever/fa/commit/4b05a7dcb06d1002870f6e0ce2bcb38d63a79ddf

I've amended our contribution guidelines so this doesn't happen again:
https://github.com/FAForever/fa/commit/68febbc60365b39606bc4f036d81a79e6bc18361
