### ISSUE TITLE
Small capture range on ACU/sACU

### ISSUE THREAD

**Issue by speed2CZ** [FAForever/fa#824]
Its much smaller than displayed build range / reclaim range (yellow circle). Engies work well, only ACU and sACU dont.

**Comment by aeoncleanse** [comment]
Done some digging just now. I think this is handled engine side, nowhere in lua is it set, and MaxBuildRange has no effect.

**Comment by Garanas** [comment]
I am closing this issue - it small capture range is still there but as far as I can see we can not fix it.
