### ISSUE TITLE
Sera Destroyer underwater vision

### ISSUE THREAD

**Issue by MattDeering** [FAForever/fa#828]
Replay: 3693763

Underwater sera destroyer can't see barracuda right next to it

**Comment by ChrisKitching** [comment]
The sonar/radar don't work, either.

**Comment by ChrisKitching** [comment]
It also can't see surface ships (even when surfaced itself), nor can it see land units.

It has no capacity for intel any more _at all_

**Comment by Sheeo** [comment]
:+1:
