### ISSUE TITLE
Engineer problem perhaps even worse

### ISSUE THREAD

**Issue by SwayGin-FAF** [FAForever/fa#829]
Replay #3694494.  Mods enabled; tested without, same problems.

Unless used very carefully, "Pause" now means that construction will be paused, but resources will still be expended.

Honestly, why not go back to 3641 engineers until this can really be fixed?

**Comment by duk3luk3** [comment]
I agree, unless there is a comprehensive fix in time for 3645 release, engineer / command pause changes should be rolled back for 3645 imo.

@Crotalus it's your work what do you think?

**Comment by ppipp** [comment]
How can I reproduce the bad behaviour you are describing? Things seem fine at first glance.

**Comment by Sheeo** [comment]
This is obviously not a feature, @SwayGin-FAF. We are meant to be back at 3640 pausing, not 3641.

**Comment by SwayGin-FAF** [comment]
Yes, I know its not a feature.  I don't know the difference between 3640 and 3641 but 3641 was ok.

The replay is designed for exactly this issue, with commentary.  I've found it in both "FAF" and "FAF (beta)"

**Comment by Crotalus** [comment]
Thanks for the report, the bug is fixed now.

As a side note, this bug has been in the game for a long time. Tested with 3636 and it's there. The fact is 3644+ has way less consumption bugs overall.

**Comment by duk3luk3** [comment]
Well I find it weird that I never noticed command pause related bugs until
the recent round of patches and then saw bugs where an engy was supposed to
be building but there was no build progress twice on the same day...
(reported in another issue here)

**Comment by quark036** [comment]
I think what happened is that there were some issues created by the patch, but then people reported and/or started to notice some older bugs at the same time with the same thing

**Comment by shalkya** [comment]
ok there is still lot of bug with engie.

1st : if you assist engie on com, and then start upgrade, engie won't assit = invest ressource into upgrade. (the assist doesn't work only if engie doesn't need to move)
2nd : if you assist a com doing an upgrade but on "pause", engie won't start assist. It would require that the com "un-pause" to start assisting.
3697099
3697075
3697118

**Comment by quark036** [comment]
The second one at least has been around for a long time

**Comment by SwayGin-FAF** [comment]
Any idea when it'll be put into the Beta?

**Comment by Crotalus** [comment]
Fixed the problem with the need to unpause / pause a commander upgrade to get engineers to start working on it

55a280f07df0d68000db74832c08437d9f9aa592

**Comment by ChrisKitching** [comment]
(We fixed this, riiiight?)
