### ISSUE TITLE
Enhanced unitview does not show build rate anymore

### ISSUE THREAD

**Issue by bamboofats** [FAForever/fa#830]
The build rate at the low left corner of the unitpanel is not shown anymore.
Traced it to lua/ui/game/unitview.lua
This update 
https://github.com/FAForever/fa/commit/2bc029f5c1611c6d32edd58d38d7183dd48535ea
and the subsequent syntax fix https://github.com/FAForever/fa/commit/14ecf2b9a04f5c16246ec5a856d68d6c8a8be333

The shield adjustments were done before the Buildrate portion, but the syntax fix places a missing "end" after it.

This is the current 3643 code compared to one of the prior versions which had buildrate working.
![code](https://cloud.githubusercontent.com/assets/13047748/8928672/852365a6-3552-11e5-8f38-1d3dc8cfaf30.jpg)

shifting the "end" before the buildrate portion makes it appear again

**Comment by Sheeo** [comment]
Good catch bamboo. Could you make this diff as a pull request instead of an image? :)

**Comment by bamboofats** [comment]
Ok i tried

**Comment by ChrisKitching** [comment]
76b4f8a
