### ISSUE TITLE
UEF buildbots dying to no-air restriction

### ISSUE THREAD

**Issue by bamboofats** [FAForever/fa#832]
https://github.com/FAForever/fa/commit/6ce716685f92b925f9852d22736fb6ed25b27fa5
This fixes the UEF buildbots for the commander. The Kennel engineering station bots still die to the restriction.
The kennel bots have a different unit bp   XEA3204
The changes should be applied to this unit as well.

**Comment by ChrisKitching** [comment]
e30f2cf
