### ISSUE TITLE
personal shield doesn't transfert damage to hp

### ISSUE THREAD

**Issue by shalkya** [FAForever/fa#836]
it's well explained here : http://forums.faforever.com/forums/viewtopic.php?f=3&t=10417

in few word : you can land a nuke or a T4 bomb, anything, on a 1% remaining shield, shield will disappear, but no damage will be done to hp.

**Comment by ChrisKitching** [comment]
Pretty sure this is intended. We may wish to special case nukes

**Comment by shalkya** [comment]
intended ? wtf ?

**Comment by ChrisKitching** [comment]
Fairly sure this is the shield behaviour in vanilla, too (with the possible exception of nukes, as we fixed the area damage bug)

**Comment by ppipp** [comment]
This is certainly not intended. All personal shields should have (or behave as if they have) the parameter             PassOverkillDamage = true, and all personal shields should transfer the extra damage to the unit except maybe in certain rare circumstances, the exact same way static shields don't block nukes.

**Comment by Sheeo** [comment]
Yes indeed, the only shields which shouldn't have this parameter are normal bubble shields, where the building itself has low hp.

Nukes that collide with the shield, t4 bombs etc. may need to be specialcased, or we could make them not collide with the shields?

**Comment by duk3luk3** [comment]
This should be tagged <balance>.

**Comment by shalkya** [comment]
i don't think so, this bug was bring since the last patch.

**Comment by Crotalus** [comment]
Indeed, it's a regression

**Comment by ChrisKitching** [comment]
60cd3b890ded077edceaeee5b49c798fe64d8e6c

**Comment by ChrisKitching** [comment]
(All personal shields except those on command units have the general PassOverkillDamage flag, for commanders we preserve the original behaviour except for nukes)

**Comment by shalkya** [comment]
please make it working for every thing, not only nuke. I don't see the point of fixing it only for nuke.
ahwassa bomb, and czar crash, can still deal nearly 0 damage, depending of the health left on the shield.

**Comment by Sheeo** [comment]
@Zockyzock @ppipp what are your opinions on this?

**Comment by Zockyzock** [comment]
Needs to work for everything, as he said and it used to work.

**Comment by shalkya** [comment]
Can you make it work for everything please ?

**Comment by ppipp** [comment]
Yes, it should have been done for last patch. It should work the same for everything, not just nukes. Since there will be a hotfix soon for firebeetles, this should be done too.

**Comment by duk3luk3** [comment]
Related: #892

**Comment by aeoncleanse** [comment]
The change for nuke damage was unnecessary and broke things (#892). This issue was caused by only 3 units (Obsidian, Titan and Harbinger) actually having the necessary flag set.

Nukes already ignore shields, flying through them, impacting the ground, and doing their damage to all entities, ignoring bubbles in the way.

**Comment by shalkya** [comment]
btw still not fix against T4 bomber, but i guess it's not worth mentioning it

**Comment by aeoncleanse** [comment]
It's not live on beta yet...

**Comment by aeoncleanse** [comment]
Confirmed fixed for T4 bomber and, with #1036, with T4 Nuke.
