### ISSUE TITLE
Extractor VS Storage Priority

### ISSUE THREAD

**Issue by aeoncleanse** [FAForever/fa#84]
Nombringer came up with this one: "Not sure if this is inside the scope of this patch, but I think it would be a great improvement if mass extractors had a higher target priority than mass storage."

**Comment by Crotalus** [comment]
#406 will help with this.

**Comment by Zockyzock** [comment]
Good idea, can do this in this patch already.

**Comment by Sheeo** [comment]
Doing this is non trivial, unfortunately.

We need to take into account that mass extractors shouldn't have higher priority than special targets -- so every single weapon in the game needs to be updated.

**Comment by ChrisKitching** [comment]
We can do that with a script, sheeo. Just ssearch for a category containing one thing, and insert another thing before it in the target priority list.
I'll crack out the sed when I'm not on a mountain.

**Comment by Sheeo** [comment]
Yes I'm aware, it wasn't within my time limit for releasing 3643 however :)

**Comment by quark036** [comment]
Or, we could add the speciallowpri category to mass extractors

**Comment by shalkya** [comment]
already tried the speciallowpri, didn't work because ACU/exp were targeted after mexx. #2509 
i will try to make a script

**Comment by shalkya** [comment]
fixed with #2787
