### ISSUE TITLE
UI broken with Civilian units.

### ISSUE THREAD

**Issue by speed2CZ** [FAForever/fa#840]
This is how UI looks if you select some of the civilian units:
http://puu.sh/jl9Da/615995a58c.jpg
it gives this warning: http://pastebin.com/JN6fXxZ1
tested in current stable patch, and yes it affect coop as well

**Comment by bamboofats** [comment]
Might have something to do with this? If reverted the civilian icons appear properly again.
https://github.com/FAForever/fa/commit/40173f40cd829054bc1be256e81e3ab120967c7f

**Comment by ChrisKitching** [comment]
just change the + to a .. on line 434 of that commit: looks like it has a typo.
Without the typo, the commit is semantically null.

**Comment by speed2CZ** [comment]
@ChrisKitching that doesnt fix it http://pastebin.com/2wGtyhCg

**Comment by ChrisKitching** [comment]
b906720
