### ISSUE TITLE
T2 Mobile Missile Friendly Fire

### ISSUE THREAD

**Issue by bamboofats** [FAForever/fa#841]
Could Consider. 
Out of all the 4 T2 Mobile missile launchers, only the UEF, UEL_0111  does not do friendly fire as it has DamageFriendly = false .

**Comment by ChrisKitching** [comment]
Should probably at least make them consistent...

**Comment by Sheeo** [comment]
@pip / @Zockyzock

**Comment by ppipp** [comment]
Should be like the others.

**Comment by Thimization** [comment]
Has this been fixed and never closed? This would be a trivially easy starting ticket for me if nobody bothered to make the change...

**Comment by aeoncleanse** [comment]
Heh, amazing: The latter. Go nuts my friend.

**Comment by aeoncleanse** [comment]
@JaggedAppliance - Can you make a PR for this targeted at Balance branch please.

**Comment by JaggedAppliance** [comment]
#1528
