### ISSUE TITLE
Ingame Lobby: Warn about buggy maps

### ISSUE THREAD

**Issue by duk3luk3** [FAForever/fa#842]
[UI] [Enhancement] [Nice to have] [Please make me a contributor so I can add labels myself]

Had a game today where host accidentally selected Canis version with broken hydro.

Since the mapselect dialog already uses a hard-coded list of "Original" Maps, why not add a hard-coded list of "Buggy" Maps and somehow inform the user when they select one (and add a filter that excludes them)?

If nobody has an objection, I will implement this - I've been working on the mapselect dialog already (#811) so I know my way around it.

**Comment by ChrisKitching** [comment]
There's a map blacklisting system in the modman branch which will hopefully be shipping soon: that's used to flag out of date maps. Could be readily extended to flag buggy maps (though the real solution is also to presumably delete them from the vault)

**Comment by duk3luk3** [comment]
Deleting from the vault helps but maps stick around because they are virally distributed from hosts, I hope this will be taken into account.

**Comment by Sheeo** [comment]
@duk3luk3 I've invited you to the org/game team, should give you permission to label issues :)

Please do refrain from pushing to `{master, develop}` or other peoples branches, and use PR's exclusively :)

**Comment by HUSSAR-mtrela** [comment]
@duk3luk3 has this feature been already implemented when the Hide Obsolete filter was added to Game Options? 

![image](https://cloud.githubusercontent.com/assets/11665978/14838001/0e289e6a-0beb-11e6-961f-897305155e37.png)

**Comment by aeoncleanse** [comment]
I think so. We just need to upkeep the list properly.
