### ISSUE TITLE
spread attack not working as intended

### ISSUE THREAD

**Issue by shalkya** [FAForever/fa#843]
http://forums.faforever.com/forums/viewtopic.php?f=3&t=10485&p=106485#p106485

this make spread attack un-reliable. better to fake a pause, and manual target opponent unit. Since first strike/path can change a game. for exemple, you can kill 100% of your opponent's cruisers with your torpedo bomber (if they were all targeted well, by the good number of torpedo) and spread attack make your torpedo bomber only attack 60% of his cruiser on the first path, making ton of overkill. you lose all your torpedo bomber because of that, and the game in the end.

**Comment by CodingSquirrel** [comment]
So I was playing around with this a bit and while having a stable split attack is nice, random still probably gives the best results. The naive approach I tried (first unit kills 1,2,3, and 4, second unit kills 2,3,4, and 1, etc.), if you have something like 5 t1 queued up first and then 5 t3 queued after, once the t1 is dead the first 6 units are killing the first t3, while the last 4 are killing the other 4 t3. I'm having a hard time coming up with a suitable algorithm that solves that and other similar issues.

Perhaps a hybrid, where the first attack is stable but the rest are random?

**Comment by Sheeo** [comment]
https://github.com/FAForever/fa/pull/851

**Comment by quark036** [comment]
So is this good?

**Comment by CodingSquirrel** [comment]
Pull request was moved to #858 and is awaiting review.
