### ISSUE TITLE
Air units continue to play engine/flying sound as they sink

### ISSUE THREAD

**Issue by bamboofats** [FAForever/fa#845]
With the new sinking mechanics, air units sink when they fall into the water. The unit's ambient sound is still playing as the air unit is sinking, and only stops once it turns into a wreck at the bottom. This can have a strange effect especially if the water is quite deep. 

I found a possible way to cut it off in the sinking code in unit.lua
DeathThread function

There are these lines of functions to terminate effects,
        self:DestroyAllDamageEffects()
        self:DestroyTopSpeedEffects()
        self:DestroyIdleEffects()
        self:DestroyBeamExhaust()
        self:DestroyAllBuildEffects()

Adding
        self:StopUnitAmbientSound( 'AmbientMove' )
To them stops the sound for all default air units. I tested and it works for all of them at least.

**Comment by ChrisKitching** [comment]
We probably want a general approach to stop all sound effects for all units as soon as they've hit the water (aside from the splash sound)

**Comment by bamboofats** [comment]
That would be best. 
There are two units which will keep playing the ambient sound as they sink, I cant stop it using that StopUnitAmbientSound approach. It seems that the sound is played a few seconds after the sinking starts, even though the unit was stationary prior to destruction and wasnt producing ambient sound.
Uef Amph tank and Sera hover tank. UEL0203 XSL0203

**Comment by bamboofats** [comment]
This probably wont be used for the general approach but ill leave it here in case it happens to be useful.
The two hover units UEL XSL0203 have two movement sounds, AmbientMoveLand and AmbientMoveWater; one plays for movement on land and the other for water. When the unit dies while moving on water, AmbientMoveWater continues playing. Adding self:StopUnitAmbientSound( 'AmbientMoveWater' ) causes the initial sound to be cutoff once the unit dies, but the sound comes back a few seconds later during sinking, (and for the uef one, changes pitch randomly several times). Perhaps the unit is considered 'water moving??' as it is sinking.

I changed both AmbientMoveLand and AmbientMoveWater into one AmbientMove and used the land sound. (I didnt notice any difference between the land and water sounds, but please correct me if there is). Then self:StopUnitAmbientSound( 'AmbientMove' ) works fine.

**Comment by duk3luk3** [comment]
Whoops.
