### ISSUE TITLE
Stealth generator projected area not so accurate.

### ISSUE THREAD

**Issue by bamboofats** [FAForever/fa#847]
Original raised issue on forums.
http://forums.faforever.com/forums/viewtopic.php?f=3&t=10474&p=106850

Possibly related: http://forums.faforever.com/forums/viewtopic.php?f=3&t=10515&p=106851

I reproduced it during a sandbox session. Didnt try other factions or map locations, but it seemed consistent with what some players experienced.

**Comment by 4z0t** [comment]
Afaik all "circles" in the game are not circles at all, they are discrete, so thats why it may accur, vision for example has same issue.

**Comment by MrRowey** [comment]
@4z0t i did exstencive testing they are offset and its hard to visualise the offset as you needed to amke a chn\ge andthen test how far it has moved

**Comment by Garanas** [comment]
@MrRowey were you working on fixing this?

**Comment by MrRowey** [comment]
Could never get an Accurate Fix for it Somone else is more than welsome to take a stab at it

**Comment by Garanas** [comment]
Closing it instead - they're inaccurate, but in practice it is irrelevant because:

- all players have the same inaccuracy
- intel is delayed anyway, it is very difficult to spot this
