### ISSUE TITLE
Air scout infinite intel bug

### ISSUE THREAD

**Issue by speed2CZ** [FAForever/fa#848]
http://content.faforever.com/faf/vault/replay_vault/replay.php?id=3728134

First scout from blue player got shot down off map and was giving infinite intel on opponent's base.

**Comment by ChrisKitching** [comment]
Sheeo and I watched the replay: the scout provided intel for 20s after crashing as expected, then it went away.

Not a bug.

**Comment by Varaxis** [comment]
I've encountered this bug before, able to reproduce it, but somewhat unreliably, by sending massive amounts of sera t1 scouts to get shot down by a variety of AA emplacements.

**Comment by speed2CZ** [comment]
I watched the replay and radar coverage on that base from dead scout was there for more than 10 minutes

**Comment by ChrisKitching** [comment]
Ah, the radar. Wish you'd said that before, I was checking out the VizMarker.

**Comment by speed2CZ** [comment]
well that's what I said, Intel, not vision :P you just think too fast

**Comment by Sheeo** [comment]
Vision, UnderwaterVision, Radar and Omni are all 'intel'.

**Comment by speed2CZ** [comment]
you forgot Sonar, but whatever :P

**Comment by Sheeo** [comment]
Indeed :)

**Comment by duk3luk3** [comment]
Happened to me in a ladder game the other day on flooded tabula. Infinite radar over opponent's base.

**Comment by Sheeo** [comment]
@duk3luk3 can you provide the replay id?

**Comment by duk3luk3** [comment]
replay.faforever.com/3760775

**Comment by duk3luk3** [comment]
Could this be fixed by making maps bigger but restricting the playable size?

**Comment by aeoncleanse** [comment]
I have a fix in mind if we confirm this ia the cause
