### ISSUE TITLE
Continuous beam weapons do not stop firing

### ISSUE THREAD

**Issue by bamboofats** [FAForever/fa#849]
Im not sure if this has been reported before. Continuous beam weapons do not stop under specific firing conditions. 
If the unit SELF TARGETTED a hostile, killed it with the beam, and no other hostiles are around, the weapon becomes idle and the beam stops. It works correctly.
But if the unit was ORDERED to attack a hostile, killed it with the beam, and no other hostiles are around, the weapon doesnt stop firing. Even moving around, or pressing stop. Though this doesnt have any adverse gameplay effect, it looks odd.
To get the beam to stop, have to either use holdfire, or get it to kill another hostile without giving the attack order.

To reproduce, give a cont beam unit an attack order on a single hostile unit, without any other hostiles nearby. Make sure to click attack on the hostile (dont let your unit kill the hostile automatically without you issing the command)

This issue isnt present in the original FA, so its probably related to some beam weapons overhaul in FAF?

Affects the continous beam units whose  Beamlifetime=0
Cybran ACU microwave
Cybran T3 AA DRLK001
GC, CZAR, Monkeylord

**Comment by ChrisKitching** [comment]
I think this issue is known (insofar as we've seen lasers not stopping), but there's not another GitHub ticket, and I didn't know this extra information about the situation in which it occurs. Now it's plausibly fixable :)

(I also thought vanilla did this?)

**Comment by bamboofats** [comment]
I checked with vanilla. It doesnt have this behaviour  with the attack order.

**Comment by bamboofats** [comment]
I am so sorry. Upon furthur checking, it appears vanilla also has this bug. I couldnt get it to reproduce  reliably with CZAR in vanilla, but GC and monkey has them.
 So this is a not a regression afterall.

**Comment by Sheeo** [comment]
No problem @bamboofats, thanks for taking the time to thoroughly test :)

**Comment by aeoncleanse** [comment]
This is definitely a vanilla bug. I've tried to track down the cause loads of times and failed, and also failed at defensively adjusting stuff to try and stop it. It's a right bloody pain!

**Comment by ChrisKitching** [comment]
Having clear STR makes it a much more approachable problem, however. I'll have a look soonish.

**Comment by bamboofats** [comment]
I had some luck with lua/sim/defaultweapons.lua   without modifying too much.
Under the DefaultBeamWeapon at the end, the WatchForHoldFire function.
It checks every 1 sec for the hold fire status, and cuts the beam if it is. 
I tried adding one more condition for cutting the beam, if the unit/weapon is idle.
It worked for unit  IsIdleState  or something like that. The beam cutsoff after destroying the specified enermy. But this isnt enough as it doesnt work if the unit moves immediately after destroying the enermy with the beam. 
Im not familiar with the possible weapon states, when the weapon is idle, but the unit isnt(eg moving).
So i think a fix could be possible for this? I just cant do with my noob skill.

**Comment by bamboofats** [comment]
I found the cause of this bug by bringing a GC along for a stroll into those neutral civilian bases and start force firing at them. Because there arnt any other hostiles to target, and the attack requires a manual click, the bug always appears.

**Comment by aeoncleanse** [comment]
Check if idlestate or moving and weapon gettarget is false

**Comment by ChrisKitching** [comment]
I am unable to reproduce this in vanilla with a spiderbot, yet I can do so on FAF.

**Comment by ChrisKitching** [comment]
An additional problem appears to exist in FAF that is not present in FA: the spinny bit on the end of the spiderbot's gun seems to accelerate endlessly, instead of spinning up to a meanacing speed and staying there.

**Comment by shalkya** [comment]
There a "bug" that might be realated to this :  emp won't stop lazer from being fired.
It means loya doesn't reduce of ML/GC's dps against other exp/high hp unit.
You can still try to get out of the laser (like if it was ground fire) but it doesn't work that well.

**Comment by bamboofats** [comment]
I managed to get a solve for this that works, though in a hideously primative manner.
Feel free to look at it if there is anything useful.
https://github.com/FAForever/fa/pull/853
