### ISSUE TITLE
Tooltip no longer appears on hover for build queue

### ISSUE THREAD

**Issue by CodingSquirrel** [FAForever/fa#855]
http://forums.faforever.com/forums/viewtopic.php?p=106792#p106792

**Comment by bamboofats** [comment]
It has something to do with this fix 
https://github.com/FAForever/fa/commit/bb41a8b7905914dc5291cd8ba808b9d679c96b18

**Comment by aeoncleanse** [comment]
Fixed here https://github.com/FAForever/fa/pull/1316
