### ISSUE TITLE
ASF / units with high targetcheckinterval unable to attack during move

### ISSUE THREAD

**Issue by Sheeo** [FAForever/fa#856]
http://forums.faforever.com/forums/viewtopic.php?f=3&t=10573

Caused by https://github.com/FAForever/fa/commit/d1352a7a7dc0bb438408912ce7d986cc544ee62a#diff-7d1c65a3fbe3fe1c1cf7016d8b83b162R253

**Comment by ChrisKitching** [comment]
How does this even have this effect?

**Comment by ChrisKitching** [comment]
I guess stuff doesn't scan for new targets while in "Attacking" mode?

**Comment by ChrisKitching** [comment]
Revered that commit and reimplemented with 57f690c6218779030381768240d8a8c43ea22b5a, which seems to not cause this problem.
