### ISSUE TITLE
Megalith does not gain speed boost when being built underwater

### ISSUE THREAD

**Issue by bamboofats** [FAForever/fa#860]
A megalith constructed underwater does not gain the water speed multiplier until it exits and reenters the water.

According to the file XRL0403_script.lua, the speedmult is only applied upon layer change, but not when the unitstopsbeingbuild.

Tested before and after the fix in a sandbox and it works.

On a side note, the self:DisableUnitIntel('Sonar') stuff recently introduced for the monkeylord and megalith could apply to the unitstopsbeingbuild part too, as the sonars might still be on when the units are completed on land at first.

**Comment by aeoncleanse** [comment]
Nice one. Go. Fix.  :p

**Comment by duk3luk3** [comment]
Did you make a PR?

**Comment by bamboofats** [comment]
I didnt! You can go ahead and make one if you got the time. Thanks!

**Comment by duk3luk3** [comment]
It sounded like you made a fix?

**Comment by bamboofats** [comment]
Ah, i made a fix through my own mod. Now I just made a PR for the main game.

**Comment by duk3luk3** [comment]
:+1:

**Comment by duk3luk3** [comment]
Review pls.
