### ISSUE TITLE
New foe'ing system

### ISSUE THREAD

**Issue by Totaltuna** [FAForever/fa#863]
Just wondering when this gets updated and if it's finished or not

**Comment by Sheeo** [comment]
Related to https://github.com/FAForever/fa/issues/496.

This issue lacks a bit of context and description, but the idea is to integrate foes from the client with the ingame lobby, making it so they cannot join your games.

**Comment by Totaltuna** [comment]
Oh haha well I was referencing the quacking mechanism, Instead just remove the text completely. I heard ideas about this. Would like to see that implemented

**Comment by Sheeo** [comment]
Removal of quacking is done in the client on develop already, pending release :)

**Comment by duk3luk3** [comment]
Can this issue be closed?

**Comment by ChrisKitching** [comment]
Nope.

**Comment by ChrisKitching** [comment]
Well, the integration of the foes with the client/lobby is not yet done.

**Comment by Sheeo** [comment]
Until foes are banned from joining your games, it isn't.

The ingame lobby needs to support this, even if we also make the server support this, in case a malicious client attempts to connect anyway.

**Comment by ChrisKitching** [comment]
> Until foes are banned from joining your games, it isn't.

... It doesn't do this already?

In any case, that needs enforcing server-side. Should the server simply not report your games to your foes? The code I just wrote to only report friends-only games to your friends can  easily be repurposed for that.

**Comment by duk3luk3** [comment]
The host's lobby can just autokick foes? Why does this need server enforcement?

**Comment by Sheeo** [comment]
If anything it saves a few bytes in total outgoing broadcast.

To enforce it fully the ingame lobby does need to kick foes who manage to join anyway.

**Comment by MrRowey** [comment]
@Garanas https://github.com/FAForever/fa/issues/863 Server now stops Foe's from joining games you host
