### ISSUE TITLE
QAI commands in server tab and in PM's to avoid aeolus flooding

### ISSUE THREAD

**Issue by Totaltuna** [FAForever/fa#864]
While I'm logged in here i had an idea in aeolus: 

[BC]CasimusLives: 
Can't we make these command / again? So it shows up in server tab and maybe pm you with the link to avoid flooding in aeolus?

Personally wouldn't really miss all the inqueries for !casts !streams etc. etc.

**Comment by Sheeo** [comment]
Belongs in client, created issue here https://github.com/FAForever/client/issues/226.
