### ISSUE TITLE
UEF Cruiser Attack move/patrol

### ISSUE THREAD

**Issue by speed2CZ** [FAForever/fa#868]
If set on patrol or attack move it stops at the range on missiles instead of direct fire cannon

**Comment by CodingSquirrel** [comment]
Isn't that a good thing? You want the cruiser to stay away and shoot with its missiles, not run up and get itself killed.

**Comment by speed2CZ** [comment]
other dont, and it completey messes up attack platoons in coop :D so its a bad thing

**Comment by CodingSquirrel** [comment]
I don't think game behavior should be determined by what AI does.

**Comment by speed2CZ** [comment]
Seraphim cruiser doesnt stay on missile range, just UEF and Aeon missile ship. Its understandable at missile ship since its the only weapon it has. But cruisers are meant against air.
Another thing is that they wont ever hit anything moving at that range and you wont need to much heavy micro against static targers.
UEF cruiser has direct fire weapon as well and that should determinate where it stops to attack from distance.

**Comment by CodingSquirrel** [comment]
Seraphim doesn't have a direct fire gun, so what range is it going to if not the missile range? (I'd like to test that when I get home)

Sure, the UEF cruiser has a direct fire weapon, but that direct fire weapon does as much DPS as a frigate. If you want frigate damage then spend 1/7 of the mass and build a frigate instead. I for one would rather not waste almost 2/3 of my cruiser range just to add 50 DPS from the deck gun.

What scenario do you have in mind that this would be useful/not a hindrance in a normal game?

**Comment by quark036** [comment]
I just tested it, Seraphim cruiser on attack move goes up to the minimum range of its tac missiles before it stops

**Comment by quark036** [comment]
which seems dumb

**Comment by CodingSquirrel** [comment]
Seraphim cruiser shouldn't have a min radius for the tac missiles. Do you mean tac defense range?

**Comment by quark036** [comment]
Ah yeah, that's probably it. There's no range ring so I just assumed it was the tac's minimum range

**Comment by CodingSquirrel** [comment]
OK, so it looks like the reason the Seraphim cruiser doesn't have the correct attack-move behavior is because the code in blueprints.lua which sets it up so that attack-move goes to the weapon max range (https://github.com/FAForever/fa/blob/develop/lua/system/Blueprints.lua#L454) requires the unit to have certain categories. This should be fixed by adding the INDIRECTFIRE category to the Seraphim cruiser.

**Comment by duk3luk3** [comment]
I can only repro this with the Aeon cruiser on develop branch. Replay: http://home.in.tum.de/~erlacher/Cruisers.SCFAReplay

**Comment by duk3luk3** [comment]
This was fixed by #873.

**Comment by speed2CZ** [comment]
so just the 'INDIRECTFIRE' category decides if crusers stop on missile range to attack or not?

**Comment by duk3luk3** [comment]
This is the code that adjusts the GuardScanRadius, which is where units stop when they are given an attack move: https://github.com/FAForever/fa/blob/develop/lua/system/Blueprints.lua#L454
