### ISSUE TITLE
Scripted map which tests balance of armies

### ISSUE THREAD

**Issue by Crotalus** [FAForever/fa#87]
Would be good to have a scripted map which can test certain balance aspects of the game. This will of course not cover all scenarios but could be an indication if a change tilts the balance too much.

Preferably each test would be in it's own function and the total results of it written to a textfile or similar, then you can have CI on it automatically.

**Comment by Garanas** [comment]
@Tagada14 is there interest from the balance team for a feature such as this? If not, you can close this issue.

**Comment by Tagada14** [comment]
Would be nice, not sure if it's really a priority or who would be able to set up such a thing.

**Comment by KaukaHan** [comment]
I think auomated balancetesting is not possible cuz, the game is too complex. Every unit has a counter and more than one usecase. Like how do you test  balance for t1 tanks ? Aurora can float and are only strong with (complex) micro. You would have to test them on every map with different strategies. The testscript would evolve into an AI. And then you only test how well the (AI) script handels the unit(s). 
Another example is how do you test spezial abbilities like salems on land or stealth units ?
So i think this should be closed.

**Comment by MrRowey** [comment]
@Garanas Thought on this new Poster :) beat me too it
