### ISSUE TITLE
Megalith: Inconsistent Layer-based AA Gun enable/disable

### ISSUE THREAD

**Issue by duk3luk3** [FAForever/fa#871]
https://github.com/duk3luk3/fa/blob/develop/units/XRL0403/XRL0403_script.lua#L112

AA Gun is enabled when changing layer to Land, but not disabled when changing Layer to seabed.

Should probably just delete the enable call?

**Comment by duk3luk3** [comment]
(This is related to #860 and #872)

**Comment by Sheeo** [comment]
If the AA guns are somehow disabled by other means automatically then indeed this call doesn't make sense.

In the interest of due dilligence, figuring out what causes them to be disable would be good :)

**Comment by duk3luk3** [comment]
As per discussion in slack: Engine disables guns that are underwater based on firing capabilities set in blueprint.

Because targetting bones are set up correctly now, we can rely on the engine to do things right and we can remove layer-based weapon toggling from all unit code.
