### ISSUE TITLE
No tooltip in table for key: Lobby_Gen_GameSpeed

### ISSUE THREAD

**Issue by speed2CZ** [FAForever/fa#875]
as title says, if you move cursor over slider that is changing game speed you'll get this warning

**Comment by duk3luk3** [comment]
I tried simply replacing the `Lobby_Gen_GameSpeed` ID in https://github.com/FAForever/fa/blob/develop/lua/ui/game/score.lua#L297 by `replay_speed` but the game UI is still looking for `Lobby_Gen_GameSpeed` despite the string `Lobby_Gen_GameSpeed` not being left anywhere in the fa code.

Possibly something is wrong with the file concat'ing? I need help on this...

**Comment by duk3luk3** [comment]
so the modded score.lua gets imported, but the old `SetupPlayerLines` function is called. This maybe has something to do with gamemain.lua calling everything directly from import() but I'm stumped.

**Comment by duk3luk3** [comment]
So what I *think* may be happening is that because score.lua is not modular, the `SetupPlayerLines` function never manages to shadow the global `SetupPlayerLines` that is somehow coming out of the original GPG score.lua. But I am not confident enough with Lua and how the GPG Lua interpreter handles the concat'ing stuff to be sure.

**Comment by Sheeo** [comment]
`gamemain.lua` isn't hooked by the base game or FAF, so there's no problem with concat'ing.

The import system returns cached modules, so that's not a problem either.

@duk3luk3 How are you running and testing your game locally? I suspect the problem to be with your init setup.

**Comment by duk3luk3** [comment]
init.lua: https://dpaste.de/UP6R

**Comment by duk3luk3** [comment]
I added `warn('Hi <functionname>')` to all functions starting from OnFirstUpdate.

    WARNING: HI OnFirstUpdate
    DEBUG: Loading module '\000/modules/hotbuild.lua\000'
    INFO: Hooked /modules/hotbuild.lua with /mods/notify/hook/modules/hotbuild.lua
    DEBUG: Loading module '\000/modules/upgradetab.lua\000'
    DEBUG: Loading module '\000/modules/buildingtab.lua\000'
    DEBUG: Loading module '\000/lua/usermusic.lua\000'
    WARNING: Hi CreateScoreUI
    WARNING: CreateScoreUI calling SetupPlayerLines
    WARNING: CreateScoreUI called SetupPlayerLines

Between the last two warnings there should have been a "Hi SetupPlayerLines".

**Comment by duk3luk3** [comment]
Could someone please try to repro this?

* Put a LOG statement into SetupPlayerLines function in `/lua/ui/game/score.lua`
* Launch a replay
* Observe that the LOG statement never shows up

@Sheeo?
