### ISSUE TITLE
Log spammed with Warning GetUnitBeingBuilt

### ISSUE THREAD

**Issue by speed2CZ** [FAForever/fa#876]
This issues started recently few patches ago in coop. Some of the fix that was already deployed reduced the log spam from 10times/second to once in 10 second but its still there. 
```
warning: Deprecated function GetUnitBeingBuilt called at
warning: stack traceback:
warning:         ...gramdata\faforever\gamedata\lua.nx2\lua\sim\unit.lua(3921): in function `GetUnitBeingBuilt'
warning:         ... alliance\gamedata\lua.scd\lua\scenarioplatoonai.lua(1316): in function `StartBaseConstruction'
warning:         ... alliance\gamedata\lua.scd\lua\scenarioplatoonai.lua(1046): in function <... alliance\gamedata\lua.scd\lua\scenarioplatoonai.lua:932>
```
Back then @Sheeo told me to do a mod for it to eliminate this until patch is relased so I can test coop. To put this into lua\sim\Unit.lua
```
oldUnit = Unit
Unit = Class(oldUnit) {
    GetUnitBeingBuilt = function(self)
        return self.UnitBeingBuilt
    end,
}
```
Thing is this mod works and eliminates this log spam completely. So this might be also a solution? I don't know what it is or how it works, so leaving this one for someone smarter.

**Comment by duk3luk3** [comment]
Can you please check if https://github.com/duk3luk3/fa/tree/hotfix/GetUnitBeingBuilt fixes the problem?

**Comment by Sheeo** [comment]
It's unclear where my commit that deals with this has gone.

@duk3luk3 please make this a pull request for immediate merge.

**Comment by duk3luk3** [comment]
Please test this, I don't know how to test coop scenarios.

**Comment by speed2CZ** [comment]
This doesn't fix it :(

**Comment by duk3luk3** [comment]
How did you apply the fix? Is the warning still the same?

**Comment by speed2CZ** [comment]
added your modified file. Its still the same. (Maybe I fucked up :|) If you wanna try it yourself, host some FA mission (first or third one) to download it and coop patch and then launch FAF from
```
C:\ProgramData\FAForever\bin\
```
with
```
ForgedAlliance.exe /init init_coop.lua
```
in main menu click skirmish select the map and start it. Once AI starts building the warning spams the log

**Comment by duk3luk3** [comment]
OK I'll see if I can reproduce that.

**Comment by duk3luk3** [comment]
I get this if I launch 

    WARNING: Deprecated function GetUnitBeingBuilt called at
    WARNING: stack traceback:
    WARNING:         ...gramdata\faforever\gamedata\lua.nx2\lua\sim\unit.lua(3921): in function `GetUnitBeingBuilt'
    WARNING:         ...ta\lua.scd\lua\editor\basemanagerbuildconditions.lua(250): in function `CategoriesBeingBuilt'
    WARNING:         ...ta\lua.scd\lua\ai\opai\basemanagerplatoonthreads.lua(117): in function <...ta\lua.scd\lua\ai\opai\basemanagerplatoonthreads.lua:72>

So it's a different file now ;)

I'll have to find them all...

**Comment by duk3luk3** [comment]
There are 14 files in lua.scd where GetUnitBeingBuilt is used, I guess about 5 or so haven't been replaced in the FAF mod, should I replace all of them or just add this file? @Sheeo / @ChrisKitching ?

**Comment by Sheeo** [comment]
I don't think the API change is worth it at this point.

@ChrisKitching said he grepped the base source code for occurences, but I guess we can conclude there are quite a few more than expected.

**Comment by duk3luk3** [comment]
Sure, the easy "fix" would be just to remove the warning...

**Comment by speed2CZ** [comment]
ehm, what does it actually do? since I havent noticed any issues with AI base functionality

**Comment by Crotalus** [comment]
It's a warning to mainly mod developers that unit:GetUnitBeingBuilt() function is unecessary and unit.UnitBeingBuilt works as well.

Maybe change the warning system so it only outputs X times, then mutes itself

**Comment by duk3luk3** [comment]
Yeah we should definitely throttle warnings more, there is basically no reason to spam the logs with warnings.
