### ISSUE TITLE
Unify Intel building classes and FX

### ISSUE THREAD

**Issue by duk3luk3** [FAForever/fa#877]
https://github.com/FAForever/fa/blob/develop/lua/defaultunits.lua#L1156

Do we actually have upgradeable jammer towers? Should they really be nonfunctional while upgrading, or does this code only shut down the improved jammer while it's under construction?

**Comment by ChrisKitching** [comment]
The latter: the way upgrades seem to work is by spawning the "new" unit on top of the old one and then deleting the old one when the new one is finished building.

**Comment by duk3luk3** [comment]
Are there any mods that have upgradeable jammer/stealth buildings?

**Comment by ChrisKitching** [comment]
Unknown, but it seems safe to assume there are some. Why do you ask? Making things less insane generally takes priority over "But maybe a mod...", because _everything we ever do_ fails the "But a mod might depend on this" test.

**Comment by duk3luk3** [comment]
Scrolling through defaultunits.lua there are like a dozen different ways of creating the IdleEffects for sonar/radar/stealth etc. units, so maybe we can some day unify all those. I'm just trying to understand how stuff goes together.

**Comment by ChrisKitching** [comment]
Yes, I noticed this and it bugs me, too. Patches welcome

**Comment by Garanas** [comment]
I'm closing this issue next Monday unless there are objections.

These changes require quite some refactoring and testing with the sole aim to improve the code style. It is not worth it in my opinion.

**Comment by MrRowey** [comment]
@Garanas No Objections to closing this :)
