### ISSUE TITLE
Seraphim Nuke and self damage

### ISSUE THREAD

**Issue by bamboofats** [FAForever/fa#878]
In 3641, the Yolona Oss self damage was fixed ref https://github.com/FAForever/fa/issues/605
https://github.com/FAForever/fa/commit/81ff6c5ec21ad29d91e930ba190c80df7f30264e

However, the basic seraphim nuke launcher still does not damage itself. The changes in the commit should be applied to this nuke controller as well
effects/Entities/InainoEffectController01/InainoEffectController01_script.lua

**Comment by Sheeo** [comment]
Please do provide a pull request :)

**Comment by bamboofats** [comment]
This should be simple enough!
