### ISSUE TITLE
gamemain.lua importing score.lua twice

### ISSUE THREAD

**Issue by duk3luk3** [FAForever/fa#879]
https://github.com/FAForever/fa/blob/develop/lua/ui/game/gamemain.lua#L99-L101

**Comment by duk3luk3** [comment]
All the importing of files instead of importing once is pretty weird too...

**Comment by Sheeo** [comment]
Why an issue for this rather than a PR?

**Comment by duk3luk3** [comment]
Because I have no clue what is going on, see #875

**Comment by ChrisKitching** [comment]
Due to the caching in the import function, this shouldn't make a difference by itself.

**Comment by ChrisKitching** [comment]
(As the second import of the same thing just returns the object produced by the first import)

**Comment by Sheeo** [comment]
It wasn't actually just an import, but an extraneous call to SetLayout().

There is potentially a reason for GPG importing all the files inside of functions... Something something different lua states.

Hypothesis remains to be proven. It could just be plain madness.
