### ISSUE TITLE
Changing fire mode

### ISSUE THREAD

**Issue by lextoc** [FAForever/fa#88]
"Cycle through all of the available fire states." is a key binding option which can be found under "Orders" when you press F1 in game.

Right now it has a delay of a second on it each time you use the key binding. However, when you change fire mode by clicking on it with the mouse it'll happen instantly.

The delay can be annoying when microing a bomber which already takes a lot of time and effort.

**Comment by Crotalus** [comment]
This delay is due to net_lag 500ms, could be fixed by having the toggling all UI side and then handle the sim commands in the background

**Comment by aeoncleanse** [comment]
Not much we can do about this other than changing net_lag. Close issue?

**Comment by Sheeo** [comment]
If we change the command that is sent to the sim, we can update the UI immediately rather than waiting for a user<->sim roundtrip, so that's a possibility.

It should be an idempotent command rather than a toggle one.
