### ISSUE TITLE
UnitDB needs some updates/fixes

### ISSUE THREAD

**Issue by Exotic-Retard** [FAForever/fa#881]
the units db seems to be behind 3650.

also the damage for the janus is incorrect:
http://content.faforever.com/faf/unitsDB/unit.php?bp=DEA0202
it deals twice as much damage as listed in the unit db (i tested this)

hope this helps

**Comment by Sheeo** [comment]
It's very much behind, at around 3633.

Wrong repository for this. There's also no other issue for this yet -- but what we need is for the original author to give us permission to publish the code so somebody can update it.

Or get someone to write a new unit database with updated values.

**Comment by duk3luk3** [comment]
What about https://github.com/spooky/unitdb?
