### ISSUE TITLE
ERROR: THERE IS NO INSTIGATOR FOR DAMAGE ON THIS COLLISIONBEAM

### ISSUE THREAD

**Issue by duk3luk3** [FAForever/fa#883]
info: *ERROR: THERE IS NO INSTIGATOR FOR DAMAGE ON THIS COLLISIONBEAM = \000{
info:   CollideFriendly=false,
info:   DamageAmount=0,
info:   DamageFriendly=false,
info:   DamageRadius=0,
info:   DamageType="Normal"
info: }

https://dpaste.de/dQeN

**Comment by Sheeo** [comment]
For information; from the attached log: ```info: REPLAY ID: 3795356```

**Comment by duk3luk3** [comment]
Ah I didn't know I could get the replay id from the log, I made this issue before the game ended.

**Comment by duk3luk3** [comment]
@ppip in #916:
> It's due to the fact Ze Pilot didn't properly implement the unit, and didn't add some fx (the red tracking beam fx). It should be easy to fix this when looking at the files in the mod "t3 mobile AA" in the vault.

**Comment by duk3luk3** [comment]
#999 should fix most of the logspam.
