### ISSUE TITLE
Cannot cancel shield gen upgrade

### ISSUE THREAD

**Issue by duk3luk3** [FAForever/fa#884]
Happened in a game I just played. The shield gens were paused at the time I clicked the upgrade button. "Stop" button didn't become available and hitting shortcut key for Stop didn't do anything.

Replay: http://replay.faforever.com/3795356
Game log: https://dpaste.de/dQeN#L

**Comment by aeoncleanse** [comment]
OK, confirmed. None of the T2 Shield Generators have the STOP button light up when they are upgrading. However, I cannot reproduce the shortcut being ineffective.

**Comment by aeoncleanse** [comment]
Confirmed this is not a regressions. Shields have never had the UI light up.
