### ISSUE TITLE
Make random show as random in the players list

### ISSUE THREAD

**Issue by julesjacobs** [FAForever/fa#887]
When you go random your opponent can see your faction in the players list as soon as the game has started. It would be nice if it showed a neutral icon instead, so that your opponent has to scout to determine the faction. This would give random a tiny advantage in return for not picking the best faction for the spot or for ladder.

**Comment by shalkya** [comment]
I m all up for it.

**Comment by duk3luk3** [comment]
:+1:

**Comment by MrRowey** [comment]
@4z0t could this be posible as it would be nice, expecial for TMM

**Comment by 4z0t** [comment]
Im afraid it requires some sim stuff and ui provides this info on creation of ui, so, yeah, sim part, i think

**Comment by Garanas** [comment]
We could do this, but people can ignore any chance we make as the content is available on the UI side. We'd just be 'hiding' it. Therefore any UI mod (like Supreme Scoreboard) would just still show the factions. I am fond of the idea, but I do not think it is safe for matchmaking.
