### ISSUE TITLE
ScriptBitToggle not working?

### ISSUE THREAD

**Issue by aeoncleanse** [FAForever/fa#89]
I've had reports from numerous players today, one of whom I absolutely trust, that the Cybran T1 MAA and T2 Cruiser, units with weapon toggles, are bugging out. For example, apparently the Cruiser will fire both guns at ground targets without being toggled. I've not had a chance to test this yet, but I've checked the unit scripts and they appear to be in order.

One of them gave me a possible lead. He thinks this only began happening in the same update as my unit description changes went live.

**Comment by Crotalus** [comment]
I've tried to replicate this behavior but can't seem to get it. They probably had some UI mod issues? If this was widespread we would have gotten more reports by now. 

I'm closing this for now
