### ISSUE TITLE
Set up a linter

### ISSUE THREAD

**Issue by duk3luk3** [FAForever/fa#890]
Find a lua linter that can be used to catch stuff like #874.

**Comment by MrRowey** [comment]
@Garanas is this needed when we will have bugsplat in the client next release ?

**Comment by Garanas** [comment]
The auto debugger will not cover these type of errors - it triggers on hard-crashes. I am also not confident a linter exists that understands how the game imports files as the `require` mechanic that Lua uses typically is not used.
