### ISSUE TITLE
Cybran sACU is able to emp units without the upgrade

### ISSUE THREAD

**Issue by VoRGoR** [FAForever/fa#891]
Certain units, e.g t2. Read above.

**Comment by MattDeering** [comment]
#3804485

**Comment by quark036** [comment]
I think this is from 47bb03d, where it adds different stun buffs to the weapon for different categories (lines 685, 696)

**Comment by quark036** [comment]
My instinct is that not all the buffs are being removed in line 29 of units/URL0301/URL0301_script.lua 
(https://github.com/FAForever/fa/blob/d551e8e53ecdcc34f460ef14bc6120260260fef8/units/URL0301/URL0301_script.lua)

**Comment by quark036** [comment]
Not sure how to fix it though

**Comment by quark036** [comment]
Ok, I did more testing. They stun t2 units, not t3 units, and stun scus. I couldn't tell for t1 units because I couldn't find one they didn't oneshot.

**Comment by quark036** [comment]
Oh wait, I realized I can just change the hp of a spirit to 2000000.

Turns out they do not stun t1.

So that means of the four stun buffs that they have, numbers 1 and 3 are being deactivated, but 2 and 4 are not. No idea why, tracing DisableBuff in weapon.lua didn't yield any results.

**Comment by duk3luk3** [comment]
I'll see if I can get to the ground of this.

**Comment by quark036** [comment]
Have at it :)
