### ISSUE TITLE
Shields get overkill damage from nukes (or something)

### ISSUE THREAD

**Issue by Exotic-Retard** [FAForever/fa#892]
replay id: 3809087

when the shield is activated, and the nuke is not in range of the actual shield building at all, but is in range of the shield, then the building also dies. a nuke fired in the same location with the shield deactivated, then the nuke doesn't harm it. affects allied and enemy shields the same way it seems.

as a bonus(!), this also contains cyb engineering drones leaving wrecks when engy stations are destroyed, giving 0 reclaim. maybe consider removing it? (its kinda a cool feature though)

hope this helps

**Comment by aeoncleanse** [comment]
Long since fixed
