### ISSUE TITLE
Atlantis AA friendly fire intended?

### ISSUE THREAD

**Issue by Varaxis** [FAForever/fa#893]
The AoE on Atlantis anti-air is indiscriminate, damaging everything it hits, included allied aircraft and even the Atlantis's owner's air force.

Other AA units checked for friendly fire, all coming up negative:
Cruisers, inc Sera's AoE
Naval carriers
SAMs, inc Sera T3 AA Turret
Static flak and hover flak

Easy way to test is with czars set to hold fire (copy-paste during pause to get them in position): 
![Example of Atlantis friendly fire testing](http://imgur.com/jO40CUi.jpg)

**Comment by duk3luk3** [comment]
Is this intended? @Zockyzock @ppipp

**Comment by Cheyans** [comment]
AA behavior should be consistent across the board

**Comment by Zockyzock** [comment]
Yes, if they should deal ff or not is a more difficult question, but making it consistent to begin with is good.
