### ISSUE TITLE
Seraphim acu restoration field BUG

### ISSUE THREAD

**Issue by hepko** [FAForever/fa#899]
Seraphim ACU restoration field has a bug that it lowers hp regeneration of units in range which have more HP regen then 200. For example SACU upgraded with nano regen should have 265 hp regen stock, and when in range of acu restoration field it should be like ~450 hp/s regen, but in reality it is only less then 200 hp/s - the ACU effect overrides the nano effect. The situation is worse as now the restoration field affect allies.

This might ring the bell:
BuffType = 'COMMANDERAURA', Stacks = 'REPLACE',

**Comment by ppipp** [comment]
Yes, the aura regen value should be added (STACK) and not replace any other regen value. I thought Crotalus had improved that ability some time ago.

**Comment by duk3luk3** [comment]
#923 should be taken care of with this as well.
