### ISSUE TITLE
Ctrl-Shift to show reclaim gives free intel

### ISSUE THREAD

**Issue by quark036** [FAForever/fa#902]
You can see where your opponent has reclaimed by seeing that the number no longer shows up for that piece of reclaim, even if you haven't scouted at all. This could affect some maps fairly significantly, like on isis, seeing if they have gotten to the center yet.

**Comment by quark036** [comment]
Also it seems to slow down performance a fair amount.

**Comment by HardlySoftly** [comment]
Related to https://github.com/FAForever/fa/issues/712 ?

**Comment by aeoncleanse** [comment]
Definitely. @Crotalus is there anything at all we can do about this?

**Comment by MrRowey** [comment]
@Garanas dose this still happen with the latest changes you have made to the labels ?

**Comment by Garanas** [comment]
Yes it does - and I am not confident if we can or should change this part of the behavior.

**Comment by Garanas** [comment]
Closing this issue - there is nothing we can do against this without introducing significant bookkeeping.
