### ISSUE TITLE
desync dialogue covers the close game dialogue

### ISSUE THREAD

**Issue by Exotic-Retard** [FAForever/fa#908]
http://puu.sh/k6EPq/325829610d.jpg
if you get a desynch window the close game dialog is covered up by it.

pretty self explanatory

but it seems you can click through it

to reproduce simply play one of the broken coop missions and get a desync by building exp

**Comment by quark036** [comment]
I can't think of anything we'd want to cover up the close game dialogue, so we could just move it to the very front

**Comment by ChrisKitching** [comment]
Then again, you can just tick "Don't tell me any more", press OK, and move on with your life.

**Comment by speed2CZ** [comment]
but if you dont do it and try to leave game instead you are trapped there until you kill the game in the task manager

**Comment by Garanas** [comment]
Fixed with 3732.
