### ISSUE TITLE
Really random Crash

### ISSUE THREAD

**Issue by theeggroll** [FAForever/fa#911]
This has happened twice now where ill be in game and everything just freezes for me only, The only thing ive changed recently is clicked the upnp box (my dad is hella paranoid with internet so no port forwarding :( ) but yeah its the randomest thing and makes me sad
https://gist.github.com/theeggroll/7afbf7f6a0e2752b4b16
https://gist.github.com/theeggroll/2e12395ea6cf96787606

**Comment by duk3luk3** [comment]
Does the audio loop or does it keep playing normally? If it keeps playing normally, it usually means your graphics card killed itself. If the audio loops, it's the game itself that's hanging.

Either way I don't think we can do much about it :/

**Comment by theeggroll** [comment]
Everything freezes, including sound. I normally have to hit x and then it gives windows popup of "wait for problem to resolve or close program" and I have to close it. Doesn't effect anyone but me

**Comment by KionX** [comment]
I think it should be closed since it has been 5 years.
