### ISSUE TITLE
Weapons locked on out of range target

### ISSUE THREAD

**Issue by Crotalus** [FAForever/fa#913]
If a weapon locks on a target and this target gets out of fire range (but still in tracking range) the weapon will be deadlocked until the target is outside tracking range.

For instance, had an Aeon T2 PD happily locking a unit right outside fire range while other units walked right up to it.

Weapon.AlwaysRecheckTarget doesn't work either, it's only triggered after each shot of the weapon.

**Comment by aeoncleanse** [comment]
Really not sure there is anything we can do about this :/
