### ISSUE TITLE
Warning in log when building Spider in water

### ISSUE THREAD

**Issue by speed2CZ** [FAForever/fa#917]
```WARNING: Error running OnLayerChange script in Entity url0402 at 26b08c08: ...gramdata\faforever\gamedata\lua.nx2\lua\sim\unit.lua(2248): attempt to perform arithmetic on field `?' (a nil value)
         stack traceback:
         	...gramdata\faforever\gamedata\lua.nx2\lua\sim\unit.lua(2248): in function `EnableUnitIntel'
         	...\gamedata\units.nx2\units\url0402\url0402_script.lua(67): in function <...\gamedata\units.nx2\units\url0402\url0402_script.lua:63>```

**Comment by duk3luk3** [comment]
Please try this with https://github.com/duk3luk3/fa/tree/hotfix/LayerChange, it should be fixed by #872

**Comment by duk3luk3** [comment]
@speed2CZ does this still happen in develop? It was merged into develop here: https://github.com/FAForever/fa/commit/81feb57104b5e75a61fc182153d721786ed9aa6a

**Comment by speed2CZ** [comment]
@duk3luk3 looks good :+1:

**Comment by duk3luk3** [comment]
Fixed by #872 :-)
