### ISSUE TITLE
It is not possible to pm observer

### ISSUE THREAD

**Issue by OCGDFS** [FAForever/fa#919]
Observer can send a private message to players in the lobby, but player cant answer this way
edit: not tried by /whisper XXX to observer but the option by right-clicking the name would be better for practical use anyway

**Comment by NyxVxyN** [comment]
There is good reason for this, it stops easy ghosting.

**Comment by NyxVxyN** [comment]
Answering with "/r"  would be nice/easy

**Comment by MrRowey** [comment]
@Garanas Surly this could be closed as this would allow for Ghosting in-game ?

**Comment by speed2CZ** [comment]
Well if you have an observer, then there's nothing stopping them from being in voice chat with someone in the game. So restricting PMs is kinda useless, isnt it?

**Comment by Garanas** [comment]
No - that logic doesn't add up 😄 .

Observers are observers - they should not be able to interact through the game with players in any form or shape.
