### ISSUE TITLE
Assist failure on paused ACU/sACU upgrades when assisted unit is bumped

### ISSUE THREAD

**Issue by SwayGin-FAF** [FAForever/fa#921]
Replay

3872076

made to demonstrate this

A unit assisting a paused ACU or sACU will stop assisting if the ACU/sACU is bumped.  Important for ACU RAS in particular.

**Comment by duk3luk3** [comment]
I'm assigning this medium priority because it's more or less well-known in the community that assisting paused (s)ACUs is buggy. I hope we can fix it though.

**Comment by MrRowey** [comment]
Old issues, If still an issues can be reopened with updated info
