### ISSUE TITLE
Adjust Othuum and Rhino models

### ISSUE THREAD

**Issue by aeoncleanse** [FAForever/fa#938]
Could our resident modeler please take a look at how easy it would be to slightly raise the height of the Rhino's turret, and the two side turrets on the Othuum?

This would be an alternative to #937, which in a perfect world would be a stopgap.

**Comment by supcomBlackMaster** [comment]
How about this height. I added a neck to the rhino
![unbenannt](https://user-images.githubusercontent.com/30982627/30240482-45be60ec-9571-11e7-91ca-d394c4b7aa9e.png)

**Comment by aeoncleanse** [comment]
This is extremely promising work! :)

**Comment by supcomBlackMaster** [comment]
![unbenannt](https://user-images.githubusercontent.com/30982627/30277504-45d4e7d4-9708-11e7-950c-ba6bb3cc3a12.png)
Slept over night, thought desing is too sloppy. here is a new example. leme know if i get closer to cybran look.

**Comment by supcomBlackMaster** [comment]
@aeoncleanse council rejectet change, want to close topic?

**Comment by MrRowey** [comment]
@Garanas Close this due to seeing no reason to change the models
