### ISSUE TITLE
Cybran drones leave wreckages in certain circumstances

### ISSUE THREAD

**Issue by Varaxis** [FAForever/fa#940]
If a Cybran drone is deployed, and the engineering unit's ownership is transferred to another player, such as under Full Share rules, the drones leave wrecks.

These wrecks annoyingly block clear open space for construction. They are worth literally nothing, and merely just waste about 1 second per drone that needs to be cleared out by reclaiming.

**Comment by ChrisKitching** [comment]
Not a bug.

**Comment by aeoncleanse** [comment]
OK, poor design then. Having a 0-mass thing getting in the way is a legitimate concern which can't just be brushed aside. I agree with Varaxis, it's annoying, it's unnecessary, and it adds nothing to the game.
