### ISSUE TITLE
Problems and questions about autobalance script

### ISSUE THREAD

**Issue by irswat** [FAForever/fa#946]
Swat here, 

I noticed some definite failings on the part of the autoteam/auto balance script and thought maybe I'd try my hand at lua coding and contributing. Not sure I'll be able to figure this out, or if you guys want the help of an amateur.

Looking at the lobby code I found the relevant sections that pertain to autobalance. I noticed there are several functions for autobalance which I assume are different approaches to autobalance theory/algorithm. 

Some questions:

1.) Where is the autobalance function called?
2.) I am assuming that since there are several different routines for autobalance that some of these functions are merely algorithims.approaches to autobalance that were tried in the past and abandoned. If this is true which of the functions is currently in use?
3.) I recall looking at this code in the past and seeing that there was a team_balance easyblock that was being used. The logic seemed to be create up to 100 combinations of the players in game according to the number of teams and select 3 of these combinations of players/team that have the best rated balance. From these 3 pick a random combination. Is this segment of code still implemented somewhere? If so where is it?

**Comment by irswat** [comment]
These were the functions in question. 

---------------------------
-- autobalance functions --
---------------------------
local function team_sort_by_sum(t1, t2)
    return t1['sum'] < t2['sum']
end

local function autobalance_bestworst(players, teams_arg)
    local players = table.deepcopy(players)
    local result = {}
    local best = true
    local teams = {}

    for t, slots in teams_arg do
        table.insert(teams, {team=t, slots=table.deepcopy(slots), sum=0})
    end

    -- teams first picks best player and then worst player, repeat
    while table.getn(players) > 0 do
        for i, t in teams do
            local team = t['team']
            local slots = t['slots']
            local slot = table.remove(slots, 1)
            local player

            if(best) then
                player = table.remove(players, 1)
            else
                player = table.remove(players)
            end

            if(not player) then break end

            teams[i]['sum'] = teams[i]['sum'] + player['rating']
            table.insert(result, {player=player['pos'], rating=player['rating'], team=team, slot=slot})
        end

        best = not best
        if(best) then
            table.sort(teams, team_sort_by_sum)
        end
    end

    return result
end

local function autobalance_avg(players, teams_arg)
    local players = table.deepcopy(players)
    local result = {}
    local teams = {}
    local max_sum = 0

    for t, slots in teams_arg do
        table.insert(teams, {team=t, slots=table.deepcopy(slots), sum=0})
    end

    while table.getn(players) > 0 do
        local first_team = true
        for i, t in teams do
            local team = t['team']
            local slots = t['slots']
            local slot = table.remove(slots, 1)
            local player
            local player_key

            for j, p in players do
                player_key = j
                if(first_team or t['sum'] + p['rating'] <= max_sum) then
                    break
                end
            end

            player = table.remove(players, player_key)
            if(not player) then break end

            teams[i]['sum'] = teams[i]['sum'] + player['rating']
            max_sum = math.max(max_sum, teams[i]['sum'])
            table.insert(result, {player=player['pos'], rating=player['rating'], team=team, slot=slot})
            first_team = false
        end

        table.sort(teams, team_sort_by_sum)
    end

    return result
end

local function autobalance_rr(players, teams)
    local players = table.deepcopy(players)
    local teams = table.deepcopy(teams)
    local result = {}

    local team_picks = {
        {},
        {1,2,  2,1,  2,1,  1,2,  1,2,  2,1},
        {1,2,3,  3,2,1,  2,1,3,  2,3,1},
        {1,2,3,4,  4,3,2,1,  3,1,4,2},
    }

    local picks = team_picks[table.getn(teams)]

    if(not picks or table.getsize(picks) == 0) then
        return
    end

    i = 1
    while (table.getn(players) > 0) do
        local player = table.remove(players, 1)
        local team = table.remove(picks, 1)
        local slot = table.remove(teams[team], 1)
        if(not player) then break end

        table.insert(result, {player=player['pos'], rating=player['rating'], team=team, slot=slot})
    end

    return result
end

local function autobalance_random(players, teams_arg)
    local players = table.deepcopy(players)
    local result = {}
    local teams = {}

    players = table.shuffle(players)

    for t, slots in teams_arg do
        table.insert(teams, {team=t, slots=table.deepcopy(slots)})
    end

    while(table.getn(players) > 0) do

        for _, t in teams do
            local team = t['team']
            local slot = table.remove(t['slots'], 1)
            local player = table.remove(players, 1)

            if(not player) then break end

            table.insert(result, {player=player['pos'], rating=player['rating'], team=team, slot=slot})
        end
    end

    return result
end

function autobalance_quality(players)
    local teams = nil
    local quality = nil

    for _, p in players do
        local i = p['player']
        local team = p['team']
        local playerInfo = gameInfo.PlayerOptions[i]
        local player = Player.create(playerInfo.PlayerName,
                                     Rating.create(playerInfo.MEAN or 1500, playerInfo.DEV or 500))

        if not teams then
            teams = Teams.create()
        end

        teams:addPlayer(team, player)
    end

    if teams then
        quality = Trueskill.computeQuality(teams)
    end

    return quality
end

**Comment by irswat** [comment]
A couple thoughts on theory:

1.) Get total rating of all players in game/the number of players. Fill team table such that each team has total rating points as close to (total rating points/number of teams) as possible.
2.) Get highest rated player and assign as their opponent the next highest rated player.

**Comment by irswat** [comment]
The reason for even addressing this issue is due to finding auto teams bugged in some way such that some times it creates teams that do not come close to being balanced.

**Comment by Crotalus** [comment]
A quick description of the different autobalance functions:

With `autobalance_bestworst` each team first picks the highest rated player available, in the next round each team picks the worst rated player and then repeat.

`autobalance_avg` tries to keep the rating sum of each team so close to each other as possible, the team with the lowest sum will pick the next player, preferably within the max_sum of all teams.

`autobalance_rr` lets each team pick the best player available, with team order alternating each round to even it out.

`autobalance_random` just randomize the team

So which of the functions are used? All of them. It will create teams with rr, bestworst, avg and pick out the best team composition from those. This team composition will then be used as a benchmark for the optimal team while generating 100 random team compositions. Three combination that is within 95% of the game quality of the best combination will also be considered as an OK option.

So in the end it will have 4 team combinations (the optimal one + 3 almost as good random ones) and then pick a random team combination out of those four.

The reason for adding the randomness into the mix is to prevent same teams coming up with repeated games / restarts with the same players.

Also, it's not possible to just look at the rating value and decide that the teams are unbalanced, the actual trueskill quality algorithm uses mean / dev to calculate the balance quality of the teams.

**Comment by Crotalus** [comment]
Feel free to create a new autobalance function and add to the above mentioned ones, if it finds a better optimal team in some cases that solution will be used as the prime one.

**Comment by irswat** [comment]
The reason for thinking the autobalance was broken was because from time to time auto teams yields teams that are not optimally balanced. 

This is what I think is happening: in these games there are only 1 or 2 team configurations which are balanced at all. Even the 3rd and 4th most balanced configurations may be imbalanced. This may be happening when the range of rating is greater, and when  there is an odd number/ratio of higher/lower rated players. 

While I appreciate the intention of the randomization function to keep teams fresh perhaps it wouldn't be a bad idea to add a conditional statement that if randomized balance yields a game quality that is less than say 85%, then it will forego the randomization function and instead choose one of the configurations that are above 85%?

A more complex approach to this may be to get the standard deviation from the mean and if there are an  odd number of players greater than say 1 STD than it will implement a seperate balancing algorithim.

What do you think?

**Comment by Crotalus** [comment]
It currently requires the random team composition be within 95% of the best, but I agree that if the best quality is like <= 85% it shouldn't be allowed to sink any further anyway. In that case it would be best to go for the most optimal one it has found.

**Comment by Crotalus** [comment]
Added an >= 85% safeguard to random now 319772088c9806a3235b5a2dd31dba2251b55664

**Comment by Exotic-Retard** [comment]
another thing about autobalance is it gets "tripped up" by a noob among pros - im not sure about this but the noob rating is higher than it should be (example a new player has 1500 rating) due to his high deviation, which for some reason leads to the team with the noob on having really really good players on it, which is  a bit unfair and often leads to a win for them. im not sure if this is an issue per se, but just thought you might want to know.

i also don't know if the system uses displayed or actual rating to calculate the game quality, but that would make a difference, and normally players balance games by displayed rating so it might make sense to use that

hope this helps

**Comment by Sheeo** [comment]
This is live in `FAF (Beta)`, please test and open a new issue if there are more problems.
