### ISSUE TITLE
hoplite path to projectile not added

### ISSUE THREAD

**Issue by Exotic-Retard** [FAForever/fa#947]
Ithilis found it! world is ending!

i translated what he said into english for you guys:

[e]Liberius_Quo: ok i found one mistake by the developers that have bad code, and should be good when its repaired
[e]Liberius_Quo: it took me about 3 evenings of frustration.
[e]Liberius_Quo: hoplite weapon
[e]Liberius_Quo: i struggled to add a new function, because on script is missing local path and i was playing all the time with the hooked version
[e]Liberius_Quo: only this guys: Dru Staltman, Eric Williamson, Gordon Duclos were not paying attention and forgot to add path to cybran unit and weapon, so every change on script, will not occur, because doesnt have path on script. This can be issue on multiple cybran units because it was made by the same people

also some mystery pastebin file where he fixed it or something: http://pastebin.com/7NFdXWwq

enjoy his contribution :DDDDDDDDDDDDDDD

EDIT: ithilis says im retarded  (and hes drunk) and this desc is a bit wrong - its mostly a modding thing because some things just wont work without the path set properly, like trying to add a new ability or sth like that, in any case i dont understand anything, talk to ithilis about this

**Comment by Varaxis** [comment]
Is this related to the bug where Hoplite missiles always seem to fall short if you right click on a fleeing units (ex. ACU) that's at the limit of its range?

**Comment by aeoncleanse** [comment]
From what I got from this is Ithilis is being an idiot again. The hoplite simply wouldn't work with a bad weapon path. I checked my files and all seems OK. Is he trying to debug with his mod turned on again?

**Comment by aeoncleanse** [comment]
Yup, that pastebin is much facepalm afaik. It looks like he doesn't remotely understand the import system and how it works. The default code is fine. His version is an overcomplicated mess.

**Comment by aeoncleanse** [comment]
Sorry, didn't mean to be so harsh about this. Basically, they are using inline imports in this file instead of defining a local as the imported function. Have Ithilis put this as his mod's file:

http://pastebin.com/MctuWFxi

**Comment by Sheeo** [comment]
Not our bug, Ithilis can contact a seasoned modder to get advice.
