### ISSUE TITLE
Hoplite missiles fall short of fleeing target at max range

### ISSUE THREAD

**Issue by Varaxis** [FAForever/fa#948]
Right click to attack a fleeing unit, such as an ACU, and Hoplite missiles miss (fall short and slightly off trajectory) of the target every time. Hard to observe in an actual game, due to fog of war covering it up, but easily confirmed in replays and in sandbox.

Screenshot of 1 of 3 hoplite missiles impacting ground relatively far from fleeing ACU.

![Hoplite missiles missing](http://i.imgur.com/C68hzvA.jpg)

**Comment by aeoncleanse** [comment]
This is 99% sure due to the MuzzleVelocity is lower than needed.

**Comment by aeoncleanse** [comment]
I tried this out against all 4 ACUs. When I tell them to flee and the Hoplite to attack, the missiles hit. Visually, they look a tiny bit short, but that's because everything's moving. Sometimes they hit square in the back. The MuzzleVelocity I confirmed is enough to fire at max range.

**Comment by Crotalus** [comment]
Hmm, I can confirm @Varaxis behavior, attack command with Hoplite @ retreating acu results in missiles hitting ground behind it more often than not

**Comment by aeoncleanse** [comment]
Increasing MV did nothing. It looks short, but the ACU takes the damage fine

**Comment by Crotalus** [comment]
`BallisticArc = 'RULEUBA_LowArc'` instead of None seems to make it lead aim better.

**Comment by aeoncleanse** [comment]
It's on none? Well, that's just silly...
