### ISSUE TITLE
Cybran drones leave annoying wreck

### ISSUE THREAD

**Issue by aeoncleanse** [FAForever/fa#949]
Spawned from #940.

It's not a bug, but it's poor design. Making the drones fall from the sky, crash, and burn, was a great visual idea. An unintended consequence was leaving a wreck. Thought not to be a problem, the wreck is 0 mass but gets in the way of building things, so it takes up time while the engineers have to reclaim it for 0 value. 

#941 Addresses this whole thing. It keeps the crash and burn, just transmits overkill damage through the code to ensure that a wreck is not spawned. It's clean, keeps the visuals, and tidies up the annoyance of having these wrecks all over the shop. I request it be re-opened and merged.

**Comment by speed2CZ** [comment]
Either the wreck should have some value so its worth the time you need to spend reclaiming or no wreck at all.
First option is a problem that the value would have to be something worth and that cant be put there, so option 2 is way to go. Make the game less annoying.

**Comment by aeoncleanse** [comment]
Exactly, the wreck has 0 value. We're talking about the wreck from the tiny drones every Cybran Engie spawns when they build stuff. Have them with a value and you're generating free mass! I know some Cybran players would love this, but... hehehehe

**Comment by Crotalus** [comment]
Yes, not good that the wrecks blocks when building new structures, especially when they always lie in the vicinity of a current base.

I guess it would be possible to make the wrecks non-collidable so units would ignore them when building. Another option would be to let them expire very quickly

**Comment by duk3luk3** [comment]
:+1: to keeping the visuals but removing the wreck.
