### ISSUE TITLE
Air scouts

### ISSUE THREAD

**Issue by Crotalus** [FAForever/fa#950]
Seems like air scouts (units?) doesn't get Vision when they are spawned, probably due to the latest intel layer change

**Comment by Sheeo** [comment]
@duk3luk3 did I mess up the merge?

**Comment by duk3luk3** [comment]
@Sheeo I'll try to have a look, most likey won't get to it before the weekend though. Might actually get to it tonight but who knows...

**Comment by Sheeo** [comment]
All right :)

**Comment by duk3luk3** [comment]
From a quick test this only applies to air scouts, which I did not touch, soooo... what you lookin' at me for?

**Comment by duk3luk3** [comment]
Well shoot. Don't know how this could happen but here's a hotfix...
