### ISSUE TITLE
"Waiting for other players" captures escape

### ISSUE THREAD

**Issue by Sheeo** [FAForever/fa#955]
This dialog isn't meant to be escapeable at all, infact, it's not even a dialog (There's no interaction).

This and and the connectivity dialogue need to be specialcased so they do not capture the escapehandler.

**Comment by Sheeo** [comment]
https://github.com/FAForever/fa/issues/959

**Comment by ChrisKitching** [comment]
The Popup class defines an OnEscapePressed function. Just set it to the empty function and bob's your uncle.

You might want to make a subclass or a constructor parameter that does this. Definitely trivial to fix without overhauling the escape handling system.

**Comment by Sheeo** [comment]
#959 supercedes this. "Waiting for other players" doesn't capture escape (As originall hinted by this issue) nor should it.
