### ISSUE TITLE
Map select blows up if no scenario preselected

### ISSUE THREAD

**Issue by duk3luk3** [FAForever/fa#957]
Steps to reproduce:
* Start FAF with with a weird "saved state" so that no scenario is preselected (I believe in my case it was because I had been testing coop scenarios and then started normal FAF Dev version so the coop maps weren't there)
* Start Skirmish lobby
* Click "Options"
* Observe brokenness and error:
```
WARNING: Error running OnRelease script in <deleted object>: e:\git\fa\lua\ui\dialogs\mapselect.lua(978): bad argument #1 to `lower' (string expected, got nil)
         stack traceback:
         	[C]: in function `lower'
         	e:\git\fa\lua\ui\dialogs\mapselect.lua(978): in function `PopulateMapList'
         	e:\git\fa\lua\ui\dialogs\mapselect.lua(667): in function `CreateDialog'
         	e:\git\fa\lua\ui\lobby\lobby.lua(2442): in function `OnClick'
         	e:\git\fa\lua\maui\button.lua(85): in function <e:\git\fa\lua\maui\button.lua:78>
```
The problem is that [Line 977 of mapselect.lua](https://github.com/FAForever/fa/blob/develop/lua/ui/dialogs/mapselect.lua#L977) is not sufficiently guarded against `selectedScenario` not being set, **or** that it is possible for the game to be in a state where `selectedScenario` is not set and that line is hit.  
Which one it is, and how it needs to be fixed, is up to the person who last touched that line, namely @ChrisKitching.

**Comment by aeoncleanse** [comment]
The problem is this bit: string.lower(selectedScenario.file), as the first can't be reached. Think we should just do something like - if not selectedScenario then set it to the first line in the filtered selection?

**Comment by duk3luk3** [comment]
Sorry, a fix for this was already merged by crotalus, because I had still had it lying around in my branch from when I found the bug and submitted it because nothing happened in this bug.

This can be closed.
