### ISSUE TITLE
Messy escapehandling

### ISSUE THREAD

**Issue by Sheeo** [FAForever/fa#959]
The escapehandling code is 'messy'.

We have two primary mechanisms used; that inside of gamemain.lua and that inside of eschandler.lua.

I wholly disabled the popup classes' automatic pushing/popping of escapehandlers in develop because the statemachine is broken. Fixing it requires going through every dialog and everything that pushes escapehandlers and correcting any assumption errors. From my quick testing the OnClosed() function in popup.lua doesn't always get called as per the documentation.

**Comment by Garanas** [comment]
Closed as a stale issue - I agree that what we have right now is a mess but it is not vital.
