### ISSUE TITLE
possible jamming fix

### ISSUE THREAD

**Issue by Exotic-Retard** [FAForever/fa#968]
just have a global time for all units with jamming - if jamming is on, toggle jamming, wait 10 seconds, repeat.

what this does: solve the jamming issue where the blips dont reappear after being scouted. unless you toggle the jamming.

making a mod for this would be just as good

**Comment by duk3luk3** [comment]
> blips dont reappear after being scouted

Are we sure this is a bug and not a feature?

**Comment by aeoncleanse** [comment]
It's neither. It's functioning as programmed so it's not a bug, but it's also not deliberate enough to be a 'feature'. What it is is poor implementation of a cool idea.

**Comment by MrRowey** [comment]
@Tagada14 Close if an issuse

**Comment by Tagada14** [comment]
This is a good idea, balance team will take a look

**Comment by MrRowey** [comment]
@Tagada14 Maybe this can be relooked at if not a priority or happy with how it is the issues can be closed

**Comment by MrRowey** [comment]
#3927
