### ISSUE TITLE
Torpedo Bombers

### ISSUE THREAD

**Issue by aeoncleanse** [FAForever/fa#99]
A major discussion needs to take place around what these units should be. Currently, some hit the target dead on, some do not, which creates an enormous power gulf. The conversation needs to address bomb path, minimum effective depth, tracking, and torpedo defence vulnerability.

**Comment by quark036** [comment]
Stuff happened in #758

**Comment by ChrisKitching** [comment]
That PR was closed without merging.

**Comment by Crotalus** [comment]
The latest torpedo changes handles this? Closing
