### ISSUE TITLE
Make it possible to turn off renamed unit display?

### ISSUE THREAD

**Issue by duk3luk3** [FAForever/fa#996]
Especially given some of the rename mods, I think it would be useful to have an option or hotkey to turn off display of custom unit names. Just show the normal unit name instead.

Anyone against it?

(I bet this could be done in a UI mod pretty easily as well, but I'm not a modder :P )

**Comment by speed2CZ** [comment]
What about Options - Interface - Always Render Custom Names?

**Comment by speed2CZ** [comment]
I'd change this to make a blacklist of people that abuse it too much :D and disable this feature for them.

**Comment by Crotalus** [comment]
`ui_RenderCustomNames`
